vaadin/web-components

packages/vaadin-context-menu/test/items.test.js, scripts/updateTests.js
Build example: https://github.com/web-padawan/components-monorepo/pull/24/checks?check_run_id=1729795903
```
❌ items > default > scrolling > Should properly move overlays on scrolling distance within y axis
Error: AssertionError: expected 16 to be close to -134 +/- 1 (http://localhost:8000/node_modules/@polymer/polymer/lib/utils/render-status.js:56)
at http://localhost:8000/__web-test-runner__/test-framework/home/runner/work/components-monorepo/components-monorepo/node_modules/ (web/test-runner-mocha/dist/autorun.js:1:322910)
❌ items > default > scrolling > Should properly move overlays on scrolling distance within x axis
Error: AssertionError: expected 16 to be close to -134 +/- 1 (http://localhost:8000/node_modules/@polymer/polymer/lib/utils/render-status.js:56)
at …
```
=> Skip flaky tests in Firefox and WebKit

package.json, packages/vaadin-combo-box/test/combo-box-light.test.js, packages/vaadin-combo-box/test/keyboard.test.js, packages/vaadin-context-menu/test/device-detector.test.js, packages/vaadin-context-menu/test/integration.test.js, packages/vaadin-menu-bar/test/sub-menu.test.js, packages/vaadin-radio-button/test/radio-button.test.js, packages/vaadin-rich-text-editor/test/basic.test.js, packages/vaadin-text-field/test/text-area.test.js, scripts/updateTests.js
The old regexp used for Safari was also affecting Chrome, updated the script to use the correct one.
=> Fix skipping tests, add debug script

scripts/generateReleaseNotes.js
Based on the Flow components monorepo script but with some adjustments.
This script does not group by component by default. Instead, there are two modes:
Run using `yarn changelog`. Output example:
```
- [`accordion`](https://github.com/vaadin/vaadin-accordion), [`app-layout`](https://github.com/vaadin/vaadin-app-layout), [`avatar`](https://github.com/vaadin/vaadin-avatar), [`board`](https://github.com/vaadin/vaadin-board), [`button`](https://github.com/vaadin/vaadin-button), [`charts`](https://github.com/vaadin/vaadin-charts), [`checkbox`](https://github.com/vaadin/vaadin-checkbox), [`combo-box`](https://github.com/vaadin/vaadin-combo-box), [`confirm-dialog`](https://github.com/vaadin/vaadin-confirm-dialog), [`context-menu`](https://github.com/vaadin/vaadin-context-menu), …
```
=> chore: add release notes script

packages/vaadin-grid/src/vaadin-grid-keyboard-navigation-mixin.js, packages/vaadin-grid/test/keyboard-navigation.test.js
- Add dispatch cell-focus event on cell-focusin
- Add cell-focus test
Connected to https://github.com/vaadin/vaadin-grid/issues/1536
=> feat: cell-focus event

packages/vaadin-grid/src/vaadin-grid.js, packages/vaadin-grid/test/column.test.js
Fixes vaadin/vaadin-grid#1981
The error is caused by the grid manually invoking notifyPath for all columns regardless if they're detached or not. This fix adds a check that the column is attached.
=> fix: check if grid column is attached

scripts/generateReleaseNotes.js
Previously, when running `node scripts/generateReleaseNotes.js` without `--from` parameter used the first tag.
It does not make much sense as in practice we want to collect changes since the most recent tag.
This PR changes the script to properly collect changes between last 2 tags for running this script in release build.
=> chore: use recent tag for release notes

packages/vaadin-context-menu/src/interfaces.d.ts
Add a type definition for the `details` object inside of the `ContextMenuRendererContext` interface.
Fix vaadin/vaadin-context-menu#309
=> fix: define details type at ContextMenuRendererContext

yarn.lock
Regenerated `yarn.lock` to pick up latest dependencies by running `yarn upgrade`
Fixes #208
=> chore: upgrade dependencies in yarn.lock

packages/vaadin-crud/src/vaadin-crud.js, packages/vaadin-crud/test/crud.test.js, web-test-runner.config.js
Fixes #207 
Setting `editedItem` initially to open the editor will lead to updating the `__isNew` flag to `true` by accident after `__clearItemAndKeepEditorOpened` changes the `editedItem` to `undefined`. 
This can be noticed when editing the item by setting `editedItem` twice in a row. It will result in new item creation instead of updating the existing one.
**Important note:** crud does already have tests for flags, so following the same pattern and adding a new one. 
In addition, the logic for editing the item via changing `editedItem` could be refactored and aligned with the one coming through `edit()`.
=> fix: do not override __isNew when editedItem is changed on closing the editor

packages/vaadin-login/test/login-form.test.js, packages/vaadin-login/test/login-overlay.test.js
First of all, existing tests were using `pressEnter` which in turn uses `pressAndReleaseKeyON` helper that contains a [setTimeout](https://github.com/PolymerElements/iron-test-helpers/blob/8c6ad1d3fa3b73d38f4b63da785344c7ab99a5a6/mock-interactions.js#L442-L446) for `keyup`. We should not use that helper to avoid this problem (even though it's not the case here). 
To make the test reliable I have updated them to use [enter](https://github.com/vaadin/testing-helpers/blob/cad53ff9d6db5c4118cdaa3e5e91fcebf2ec74fd/src/keyboard.ts#L154-L157) helper instead (which is synchronous).
I believe the original `pressAndReleaseKeyOn` was async because of IE11 which had a somewhat related problem.
But the actual problem was that the tests were lacking `action` attribute on the `vaadin-login-form`.
This …
=> test: fix login form submission tests

packages/vaadin-crud/test/crud.test.js
After a recent Playwright update, CRUD tests started to crash in WebKit for some reason.
I could not quickly identify which logic causes this. Everything has been working before.
Related to #219 (but is not a proper fix).
=> test: skip CRUD tests in WebKit due to crash

package.json, packages/vaadin-crud/test/crud.test.js, yarn.lock
It looks like downgrading from 1.10.0 to 1.9.2 helps to make tests pass.
Fixes #219
=> chore: downgrade playwright to 1.9.2

packages/vaadin-element-mixin/test/dir-mixin.test.js, packages/vaadin-element-mixin/vaadin-dir-mixin.d.ts, packages/vaadin-element-mixin/vaadin-dir-mixin.js
The current DirMixin implementation basically reimplements the native `HTMLElement.dir` property and makes it readonly, which breaks the native API which allows you to set the direction through the property directly:
```
element.dir = 'rtl';
```
This PR fixes it by allowing write access to the property, while syncing changes from the property to the attribute, which is also native behavior.
I also removed the incompatible `dir` property declaration in the typings as it should now match the property inherited from `HTMLElement`.
=> Fix dir-mixin not respecting native HTMLElement API

packages/vaadin-grid/src/vaadin-grid.js, packages/vaadin-grid/test/row-details.test.js
ATM the grid does not update a rows `details-opened` attribute when the data provider changes. This PR fixes that by updating the attribute in the `_updateItem` method which should be run when the data provider changes.
Fixes https://github.com/vaadin/vaadin-grid/issues/2129
=> fix: clear row details opened attribute when item is removed

packages/vaadin-accordion/test/typings/accordion.types.ts, packages/vaadin-accordion/vaadin-accordion-panel.d.ts, packages/vaadin-accordion/vaadin-accordion-panel.js
This PR adds a missing export of `vaadin-accordion-panel` so it becomes possible to import it from the outside:
```
import '@vaadin/vaadin-accordion';
import '@vaadin/vaadin-accordion-panel';
```
=> fix(vaadin-accordion): export vaadin-accordion-panel

.github/workflows/lumo.yml, .github/workflows/material.yml
This PR is intended to provide access to screenshots that failed during visual regression tests in CI.
It uses `actions/upload-artifact@2` for uploading failed screenshots to Github. So that they become available to download from the build report:
Related to #235 (issue)
=> chore: upload screenshots that failed during visual tests to Github

packages/vaadin-context-menu/test/visual/common.js, packages/vaadin-context-menu/test/visual/lumo/context-menu.test.js, packages/vaadin-context-menu/test/visual/material/context-menu.test.js, web-test-runner-lumo.config.js, web-test-runner-material.config.js, wtr-utils.js
It turns out the `openSubMenus` helper was not using promises and the test was apparently passing or failing randomly, most likely depending on the network latency (in some cases, the screenshot was taken before last menu was opened).
Fixes #238
=> test: reduce visual regression tests flakiness

packages/vaadin-upload/src/vaadin-upload.js, packages/vaadin-upload/test/upload.test.js
Currently the upload element clears (setting it to `false`) the `uploading` status on a file element when:
- there is a progress event
- and the progress equals 100
...but before the XHR ready state changes, and thus possibly some time before the `upload-success` or `upload-failed` event is sent.
This can be a problem in the Flow component when doing multi-file uploads. Basically whenever the Flow component receives a success or failure event, it will check if all files have `uploading == false` and then report that all uploads are finished. But when using multiple files that state can be true before all files have sent their success event, which can lead to the following observed event flow on the Flow component:
```
File 1 success
File 2 success
All finished
File 3 success
```
In the …
=> fix: fix clearing uploading status before upload success event

.env.dist, .gitignore, README.md, package.json, web-test-runner-firefox.config.js, web-test-runner-lumo.config.js, web-test-runner-material.config.js, web-test-runner-webkit.config.js, web-test-runner.config.js, yarn.lock
While setting up Sauce Labs for visual tests, I was kind of hesitant to add the credentials on a user level. From my previous job I was used to setting up these kind of variables per project.
I would propose to introduce `.env` file support to the repo where we can configure all project-level variables. This would also help as a documentation of all variables that exist in the project on how/where/why they are used.
=> chore: Add .env file support

.eslintrc.json, package.json, yarn.lock
This PR configures ESLint so that it makes linting `.ts` files possible as well as it works for other files now. 
It turned out to be a zero-cost change so nothing was found to be fixed afterward.
Related to #226
**Note:** This PR doesn't lead to any changes of Code Style.
=> chore: configure ESLint to lint TS files

.eslintrc.json, packages/vaadin-element-mixin/vaadin-element-mixin.d.ts, packages/vaadin-grid/src/vaadin-grid-column.js, packages/vaadin-rich-text-editor/src/vaadin-rich-text-editor.js
This PR enables the recommended rules from the `@typescript-eslint` package to force ESLint to check type-specific cases.
I've decided to disable 5 out of 21 rules which I considered as debatable and leading to unnecessary changes.
Let's discuss it if you have a different opinion.
Related to #226
=> chore: add recommended TS rules to ESLint config

packages/vaadin-menu-bar/src/vaadin-menu-bar-interactions-mixin.js
There used to be a global outside click listener which was removed by https://github.com/vaadin/vaadin-menu-bar/pull/77
Let's cleanup the code related to it because it does not do anything.
=> refactor: cleanup no longer existing listener

wtr-utils.js
Update the web test runner change detection script to use `20.0` as a base branch for Vaadin 20.
Related to #259
=> chore: update change detection branch to 20.0

packages/vaadin-login/src/vaadin-login-form.js, packages/vaadin-login/test/login-form.test.js
Automatically picks up a CSRF token written by Vaadin to the page if it is present and includes it in the form submission.
Fixes #201
=> feat: include an available CSRF token in login request

packages/vaadin-grid/src/vaadin-grid-dynamic-columns-mixin.js, packages/vaadin-grid/src/vaadin-grid-filter-mixin.js, packages/vaadin-grid/src/vaadin-grid-sort-mixin.js, packages/vaadin-grid/src/vaadin-grid-sorter.js, packages/vaadin-grid/test/filtering.test.js, packages/vaadin-grid/test/helpers.js, packages/vaadin-grid/test/sorting.test.js
Fixes: vaadin/vaadin-grid#1969
Warranty: Fixes exception related to sorting when recreating columns
Cherry-pick: https://github.com/vaadin/vaadin-grid/pull/2122
Fixes vaadin/vaadin-grid#1969
=> Cherry-pick fix: update filtering and sorting when grid and columns are attached / detached (#2122)

packages/vaadin-grid/src/vaadin-grid-data-provider-mixin.js, packages/vaadin-grid/test/scroll-to-index.test.js
In some cases, the calling `scrollToIndex` with values closer to the end of the Grid, could lead to some rows being mistakenly reused leaving some rows empty.
For instance, if a TreeGrid has an expanded item, but the subitems are not placed yet when the scroll is called.
This change flushes the `_debounceIncreasePool` debouncer before scrolling, so it will be able to place the remaining items properly.
Fixes https://github.com/vaadin/vaadin-grid/issues/2145
=> fix(grid): flush debouncer to fix timing issue with scroll to index

packages/vaadin-app-layout/src/vaadin-app-layout.js, packages/vaadin-app-layout/test/app-layout.test.js
ATM the app layout does not implement the iron resize behaviour, meaning that toggling the drawer, or changing the drawers contents, will not notify children in the main slot about the resize. To fix this I added the iron resize behaviour to the app layout and make it notify about resizes when:
- the drawer is opened / closed
- the drawer switches between regular and overlay mode
- the drawers contents are changed (cleared, which makes the drawer hide; or added, which could result in a size change)
Fixes https://github.com/vaadin/vaadin-app-layout/issues/182
=> fix: notify app-layout children about the resize

packages/vaadin-avatar/src/vaadin-avatar.js, packages/vaadin-avatar/test/avatar.test.js
Currently if the avatar element can not load an image for some reason, it shows a broken image icon, or title (depending on browser).
This change handles image load failures more gracefully:
Fixes https://github.com/vaadin/vaadin-avatar/issues/111
- this was not really done, but seeing that this is a GFI and has a reasonable scope I assume it's OK
=> feat: show abbreviation as fallback if image can not be loaded

packages/vaadin-avatar/src/vaadin-avatar.js
Changing the border radius of the host should affect the colored border as well. Otherwise, when customizing the border radius, you would need to remember to do it for two elements (the host and the `::before` pseudo element).
=> fix: Allow colored avatar border to respect the host border radius

scripts/generateReleaseNotes.js
Current script lacks the title for the release which has to be the [text up to the first blank line](https://github.com/github/hub/blob/c8e68d548a39ec0fab6f674a669c21b54d4eec61/commands/release.go#L80):
```
The text up to the first blank line in <MESSAGE> is treated as the release
title, and the rest is used as release description in Markdown format.
```
=> chore: add version to release notes [skip ci]

packages/vaadin-date-time-picker/src/vaadin-date-time-picker.js, packages/vaadin-time-picker/src/vaadin-time-picker.js
Clarifies the description of the `step` property in vaadin-date-time-picker and vaadin-time-picker components to make it clear that it's a number of seconds between steps, not the number of steps in a day.
Fixes #254
Related PR to update the docs: https://github.com/vaadin/docs/pull/424
=> docs:  fix time-picker `step` property API docs [skip ci]

.github/workflows/lint.yml
Currently the `lint` script is executed as part of Chrome workflow and causes it to take more time.
Let's split these scripts into separate `Lint` workflow so we could also add other checks there later on.
=> chore: move lint script to separate workflow

packages/vaadin-lumo-styles/badge.d.ts, packages/vaadin-lumo-styles/color.d.ts, packages/vaadin-lumo-styles/mixins/field-button.d.ts, packages/vaadin-lumo-styles/mixins/menu-overlay.d.ts, packages/vaadin-lumo-styles/mixins/overlay.d.ts, packages/vaadin-lumo-styles/mixins/required-field.d.ts, packages/vaadin-lumo-styles/sizing.d.ts, packages/vaadin-lumo-styles/spacing.d.ts, packages/vaadin-lumo-styles/style.d.ts, packages/vaadin-lumo-styles/typography.d.ts, packages/vaadin-material-styles/color.d.ts, packages/vaadin-material-styles/mixins/field-button.d.ts, packages/vaadin-material-styles/mixins/menu-overlay.d.ts, packages/vaadin-material-styles/mixins/overlay.d.ts, packages/vaadin-material-styles/mixins/required-field.d.ts, packages/vaadin-material-styles/shadow.d.ts, packages/vaadin-material-styles/typography.d.ts, packages/vaadin-select/package.json, packages/vaadin-select/test/accessibility.test.js, packages/vaadin-select/test/scrollable-viewport.test.js, packages/vaadin-select/test/select.test.js, packages/vaadin-themable-mixin/package.json, packages/vaadin-themable-mixin/register-styles.d.ts, packages/vaadin-themable-mixin/register-styles.js, yarn.lock
Upgrades from using `lit-element` 2 to `lit` 2 (containing `lit-element` 3)
Fixes #241
=> feat!: upgrade to use Lit 2 for css tagged literals

packages/vaadin-template-renderer/package.json
The actual implementation was not published to npm because of incorrect `files` field.
We need to think about how to avoid this in future.
=> fix: publish vaadin-template-renderer src folder

packages/vaadin-combo-box/src/vaadin-combo-box-item.js, packages/vaadin-combo-box/src/vaadin-combo-box-mixin.d.ts, packages/vaadin-combo-box/src/vaadin-combo-box-mixin.js, packages/vaadin-combo-box/src/vaadin-combo-box.d.ts, packages/vaadin-combo-box/src/vaadin-combo-box.js, packages/vaadin-combo-box/test/combo-box-light.test.js, packages/vaadin-combo-box/test/dropdown.test.js, packages/vaadin-combo-box/test/fixtures/mock-combo-box-light-template-wrapper.js, packages/vaadin-combo-box/test/fixtures/mock-combo-box-template-wrapper.js, packages/vaadin-combo-box/test/item-renderer.test.js, packages/vaadin-combo-box/test/item-template.test.js, packages/vaadin-combo-box/test/toggling-dropdown.test.js, packages/vaadin-template-renderer/src/vaadin-template-renderer-templatizer.js, packages/vaadin-template-renderer/src/vaadin-template-renderer.js, packages/vaadin-template-renderer/test/list.test.js, packages/vaadin-template-renderer/test/vaadin-template-renderer.test.js, packages/vaadin-template-renderer/test/x-component-host.js, packages/vaadin-template-renderer/test/x-component.js, packages/vaadin-template-renderer/test/x-list-host.js, packages/vaadin-template-renderer/test/x-list.js
=> feat!: remove polymer template api from vaadin-combo-box

package.json, wtr-utils.js, yarn.lock
1. Updated `@web/test-runner` to the latest version to get coverage fix
2. Changed warnings filter to only hide the warnings that are in the "allowed" list (these only manifest in our tests)
=> chore: bump test-runner, update warnigns

packages/vaadin-overlay/src/vaadin-overlay.js, packages/vaadin-overlay/test/renderer.test.js
While I was working on #353, I discovered that `vaadin-overlay` doesn't clear the content after removing the renderer function. 
This PR aims to address this issue in `20.0`.
=> fix: clear the content when removing the renderer in vaadin-overlay

packages/vaadin-custom-field/package.json, packages/vaadin-custom-field/test/visual/lumo/custom-field.test.js, packages/vaadin-custom-field/test/visual/material/custom-field.test.js, packages/vaadin-overlay/src/vaadin-overlay.js, packages/vaadin-overlay/test/renderer.test.js, packages/vaadin-select/package.json, packages/vaadin-select/src/vaadin-select.d.ts, packages/vaadin-select/src/vaadin-select.js, packages/vaadin-select/test/renderer.test.js, packages/vaadin-select/test/template.test.js
=> feat!: remove polymer template api from vaadin-select

packages/vaadin-notification/src/vaadin-notification.js, packages/vaadin-notification/test/renderer.test.js
While I was working on #345, I discovered that the notification card isn't cleared after removing the renderer function.
This PR aims to address this issue for `20.0` branch.
=> fix: clear notification card when removing renderer

packages/vaadin-themable-mixin/register-styles.d.ts, packages/vaadin-themable-mixin/register-styles.js, packages/vaadin-themable-mixin/test/typings/register-styles.types.ts
There is a breaking change and Lit 2 which means we should make `registerStyles` respect new types.
Fixes #359
=> fix: make registerStyles work with Lit 2

packages/vaadin-dialog/src/vaadin-dialog.js, packages/vaadin-dialog/test/renderer.test.js
Currently, `vaadin-context-menu` doesn't clear the content after removing the renderer function. 
This PR aims to address this issue in the `20.0` branch.
=> fix: clear dialog content when removing renderer

packages/vaadin-context-menu/package.json, packages/vaadin-context-menu/src/vaadin-context-menu-overlay.js, packages/vaadin-context-menu/src/vaadin-context-menu.d.ts, packages/vaadin-context-menu/src/vaadin-context-menu.js, packages/vaadin-context-menu/src/vaadin-contextmenu-items-mixin.d.ts, packages/vaadin-context-menu/src/vaadin-contextmenu-items-mixin.js, packages/vaadin-context-menu/test/context.test.js, packages/vaadin-context-menu/test/integration.test.js, packages/vaadin-context-menu/test/items.test.js, packages/vaadin-context-menu/test/overlay.test.js, packages/vaadin-context-menu/test/properties.test.js, packages/vaadin-context-menu/test/renderer.test.js, packages/vaadin-context-menu/test/selection.test.js, packages/vaadin-context-menu/test/template.test.js, packages/vaadin-context-menu/test/touch.test.js, packages/vaadin-context-menu/test/visual/lumo/context-menu.test.js, packages/vaadin-context-menu/test/visual/material/context-menu.test.js
=> feat!: remove polymer template api from vaadin-context-menu

packages/vaadin-select/src/vaadin-select.js, packages/vaadin-select/test/renderer.test.js
Currently, `vaadin-select` doesn't clear the content after removing the renderer function.
This PR aims to address this issue in the `20.0` branch.
=> fix: clear select content when removing renderer

packages/vaadin-themable-mixin/register-styles.js
This should slightly simplify the logic we have, by not registering a `dom-module` element to get styles from its template.
Instead, use `stylesFromTemplate` directly - that's the same API as used [here](https://github.com/Polymer/polymer/blob/401c7837ecb347d6c7d4e84b17e16b3ea239e410/lib/utils/style-gather.js#L88-L93) but without using `querySelector` etc).
=> refactor: optimize registerStyles logic

packages/vaadin-notification/src/vaadin-notification.js, packages/vaadin-notification/test/renderer.test.js
Currently, `vaadin-notification` throws an exception if you set the renderer before the notification is added to DOM. 
This PR aims to address this issue.
Fixes #375
=> fix: don't throw when renderer is set before adding to DOM

packages/vaadin-notification/src/vaadin-notification.js, packages/vaadin-notification/test/renderer.test.js
This PR aims to address #379 in the `20.0` branch.
Fixes #379
=> fix: don't throw when renderer is set before adding to DOM (#379) (CP: 20.0)

packages/vaadin-notification/src/vaadin-notification.js, packages/vaadin-notification/test/notification.test.js
Currently, `vaadin-notification-card` has the ID attribute. As soon as you open multiple notifications simultaneously, all the notifications end up in the Shadow DOM of `vaadin-notification-container` that leads to duplicating IDs.
Fixes #378
=> fix: remove ID attribute from notification card

packages/vaadin-grid/src/vaadin-grid-styles.js, packages/vaadin-grid/src/vaadin-grid.js, packages/vaadin-grid/test/resizing.test.js
These changes are required to make https://github.com/vaadin/flow-components/pull/978 pass
1. A grid with `heightByRows` and an invisible header should be able to generate row elements. If the scroll target's height is 0, the virtualizer doesn't try to create any elements even if the grid has items. So we force a 1px default height to the grid's scroll target that would otherwise have a height of 0,  if `heightByRows` is in use. [Link to the failing test case.](https://github.com/vaadin/flow-components/blob/4a61d259fd6b32020243f6f690d7566fd4f97a2a/vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/RecalculateColumnWidthsIT.java#L31)
2. The grid [connector used index arguments](https://github.com/vaadin/flow-components/blob/4a61d259fd6 …
=> fix: make sure rows are generated to an empty grid with heightByRows

packages/vaadin-grid/src/vaadin-grid-keyboard-navigation-mixin.js, packages/vaadin-grid/src/vaadin-grid.js
Can't come up with a local test case. This is needed to fix [this test](https://github.com/vaadin/flow-components/blob/4a61d259fd6b32020243f6f690d7566fd4f97a2a/vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridHugeTreeNavigationIT.java#L41) in https://github.com/vaadin/flow-components/pull/978
=> fix: handle leading hidden body rows

packages/vaadin-template-renderer/src/vaadin-template-renderer.js, packages/vaadin-template-renderer/test/fixtures/mock-component-host.js, packages/vaadin-template-renderer/test/fixtures/mock-component-slotted-host.js, packages/vaadin-template-renderer/test/fixtures/mock-component.js, packages/vaadin-template-renderer/test/fixtures/mock-list-host.js, packages/vaadin-template-renderer/test/fixtures/mock-list.js, packages/vaadin-template-renderer/test/list.test.js, packages/vaadin-template-renderer/test/observer.test.js, packages/vaadin-template-renderer/test/vaadin-template-renderer.test.js
Currently, `vaadin-template-renderer` can process and observe only children templates which are not inside a slot. 
The support of slotted templates is a necessary step towards removing the Polymer Template API from `vaadin-grid`. It actively uses slotted templates in the tests.
This PR aims to support processing and observing slotted templates for `vaadin-template-renderer`.
Part of #326.
**Note:** I preferred using the Polymer Flattened Observer instead of creating an own implementation as far as it supports observing slotted nodes out of the box, and we already have the `@polymer/polymer` dependency.
=> feat: support rendering slotted templates for template renderer

.env.dist, package.json, scripts/transferIssues.js, yarn.lock
Intended usage: `node scripts/transferIssues.js` to transfer all open issues from individual web component repos into the web-components monorepo for each of the web components in the `./packages` folder of this monorepo.
Labels on the transferred issues are transferred as well. The transferred issues remain in the same pipelines (columns) on all ZenHub boards (if both the web-components monorepo and the original issue's repo are present on the board).
If a label was missing in the web-components repo, it will be created (with the same color as in the original repo).
Fixes https://github.com/vaadin/components-team-tasks/issues/580
=> chore: add a `transferIssues` script [skip ci]

scripts/transferIssues.js
`require('fs/promises')` is supported from node 14 onwards. The Node version on the Bender CI server is below that.
Related to https://github.com/vaadin/components-team-tasks/issues/580
=> chore: node12 compat fix for the transferIssues script [skip ci]

packages/vaadin-virtual-list/README.md, packages/vaadin-virtual-list/package.json, packages/vaadin-virtual-list/src/vaadin-virtual-list.d.ts, packages/vaadin-virtual-list/src/vaadin-virtual-list.js, packages/vaadin-virtual-list/src/virtualizer-iron-list-adapter.js, packages/vaadin-virtual-list/test/template.test.js, packages/vaadin-virtual-list/test/typings/virtual-list.types.ts, packages/vaadin-virtual-list/test/virtual-list.test.js, packages/vaadin-virtual-list/test/virtualizer.test.js, packages/vaadin-virtual-list/theme/lumo/vaadin-virtual-list.js, packages/vaadin-virtual-list/theme/material/vaadin-virtual-list.js, packages/vaadin-virtual-list/vaadin-virtual-list.d.ts, yarn.lock
Implements the `<vaadin-virtual-list>` Web Component
Closes https://github.com/vaadin/web-components/issues/283
=> feat: vaadin-virtual-list

scripts/transferIssues.js
When running on the CI the API call to disable repo issues consistently fails (even though is runs OK when running locally using an API token with fewer scopes).
Related https://github.com/vaadin/components-team-tasks/issues/580
=> chore: do not disable repo isses by the transfer script [skip ci]

scripts/transferIssues.js
Skip open PRs in the `transferIssues` script. The GitHub API to iterate over open issues sometimes returns PRs as well. This commit adds the logic to skip them in the transfer.
Related https://github.com/vaadin/components-team-tasks/issues/580
=> chore: skip open PRs in `transferIssues` script [skip ci]

packages/vaadin-virtual-list/src/vaadin-virtual-list.js, packages/vaadin-virtual-list/test/virtual-list.test.js
Fixes to default styles:
- Make the child elements 100% wide by default
- Make the component not collapse inside a flex box
=> fix: virtual list styles

package.json, packages/vaadin-grid/src/vaadin-grid-keyboard-navigation-mixin.js, packages/vaadin-grid/test/keyboard-navigation.test.js
When the grid is in interaction mode, then pressing tab / shift-tab is supposed to cycle focus between the focusable elements (inputs, selects,...) in the cell contents. The cycle could be broken if the focus target cell in a grid section was in the tab order between two inputs. For example:
- navigating to a cell by keyboard, which updates to focus target cell
- pressing enter to enter interaction mode, which focusses input within focus target cell
- pressing shift-tab
- expected outcome: input in previous cell is selected
- actual outcome: focus target cell is focussed because it is in the tab order between the current and the previous input
This change modifies the interaction mode to remove the focus target cell in a grid section from the tab order while the user is in interaction …
=> fix: disable grid section focus target in interaction mode

packages/vaadin-virtual-list/src/virtualizer-iron-list-adapter.js
Prevent scroll to index when the virtualizer has 0 size.
Reorganize and document code in the iron-list-adapter.
=> refactor: skip scroll to index when virtualizer has no items

scripts/transferFlowIssues.js
Intended usage: `node scripts/transferFlowIssues.js` to transfer all open issues with the `flow` label from the `web-components` repo into `flow-components`. In order to run with the `vaadin-bot` credentials, run this script via the [Transfer issues to the flow-components monorepo](https://bender.vaadin.com/buildConfiguration/VaadinWebComponents_TransferIssuesToTheFlowComponentsMonorepo/232264?buildTab=log&expandAll=true&focusLine=2909) CI build.
Labels on the transferred issues are transferred as well (except for the `flow` label, which is dropped). The transferred issues remain in the same pipelines (columns) on all ZenHub boards.
If a label was missing in the web-components repo, it will be created (with the same color as in the original repo).
Fixes …
=> chore: add a `transferFlowIssues` script [skip ci]

packages/vaadin-grid/src/vaadin-grid.js, packages/vaadin-grid/test/column.test.js
Make sure that the cell structure of hidden rows gets updated when the column structure of a hidden grid changes
Fixes a regression from [this change](https://github.com/vaadin/web-components/pull/321/files#diff-f55be1687931f6b0777e240bb62e036552dd9f76d85bc316689f8b1258d7a79bL734-R812)
=> fix: update the structure of hidden rows

packages/vaadin-virtual-list/src/vaadin-virtual-list.d.ts, packages/vaadin-virtual-list/src/vaadin-virtual-list.js, packages/vaadin-virtual-list/src/virtualizer-iron-list-adapter.js, packages/vaadin-virtual-list/src/virtualizer.js, packages/vaadin-virtual-list/test/typings/virtual-list.types.ts, packages/vaadin-virtual-list/test/unlimited-size.test.js, packages/vaadin-virtual-list/test/virtual-list.test.js
Related to https://github.com/vaadin/flow-components/issues/853
The `IronList` Flow component's TestBench element has [APIs for getting the first and last visible item indexes](https://github.com/vaadin/flow-components/blob/20.0/vaadin-iron-list-flow-parent/vaadin-iron-list-testbench/src/main/java/com/vaadin/flow/component/ironlist/testbench/IronListElement.java#L37-L53).
In order to have the same APIs in VirtualList's TestBench element, the `<vaadin-virtual-list>` Web Component needs to expose `firstVisibleIndex` and `lastVisibleIndex` properties.
=> feat: add first/last visible index APIs to virtual list

packages/vaadin-accordion/test/accordion.test.js, packages/vaadin-app-layout/test/app-layout.test.js, packages/vaadin-avatar/test/avatar-group.test.js, packages/vaadin-avatar/test/avatar.test.js, packages/vaadin-board/test/basic.test.js, packages/vaadin-button/test/button.test.js, packages/vaadin-charts/test/chart-element.test.js, packages/vaadin-confirm-dialog/test/confirm-dialog.test.js, packages/vaadin-cookie-consent/test/cookie-consent.test.js, packages/vaadin-date-time-picker/test/basic.test.js, packages/vaadin-details/test/details.test.js, packages/vaadin-dialog/test/dialog.test.js, packages/vaadin-icon/test/icon.test.js, packages/vaadin-item/test/item.test.js, packages/vaadin-login/test/login-form.test.js, packages/vaadin-menu-bar/test/menu-bar.test.js, packages/vaadin-messages/test/message-input.test.js, packages/vaadin-messages/test/message-list.test.js, packages/vaadin-messages/test/message.test.js, packages/vaadin-ordered-layout/test/horizontal-layout.js, packages/vaadin-ordered-layout/test/scroller.test.js, packages/vaadin-ordered-layout/test/vertical-layout.test.js, packages/vaadin-progress-bar/test/progress-bar.test.js, packages/vaadin-tabs/test/tabs.test.js
We have a bunch of tests checking the `version` getters in components and they fail for `20.0.0-rc1`:
```
❌ tabs > custom element definition > should have a valid version number
AssertionError: expected '20.0.0-rc1' to match /^(\d+\.)?(\d+\.)?(\d+)(-(alpha|beta)\d+)?$/
at o.<anonymous> (packages/vaadin-tabs/test/tabs.test.js:40:54)
```
=> test: fix version regex to allow RC

packages/vaadin-grid/src/vaadin-grid-styles.js, packages/vaadin-grid/test/resizing.test.js
Related to https://github.com/vaadin/start/issues/1249
Follow-up for https://github.com/vaadin/web-components/pull/387
The previous selector with `items:empty` doesn't apply when there are `hidden` rows in the DOM. This PR makes the `items` container always have a min-height of 1px when `heightByRows` is used. This is to make sure the virtualizer generates rows even when there are non-visible rows in the DOM.
=> fix: make sure rows are generated to an emptied grid with heightByRows

packages/vaadin-grid/src/vaadin-grid-column.d.ts, packages/vaadin-grid/src/vaadin-grid-column.js, packages/vaadin-grid/src/vaadin-grid-filter-column.d.ts, packages/vaadin-grid/src/vaadin-grid-filter-column.js, packages/vaadin-grid/src/vaadin-grid-selection-column.d.ts, packages/vaadin-grid/src/vaadin-grid-selection-column.js, packages/vaadin-grid/src/vaadin-grid-sort-column.d.ts, packages/vaadin-grid/src/vaadin-grid-sort-column.js, packages/vaadin-grid/src/vaadin-grid-tree-column.d.ts, packages/vaadin-grid/src/vaadin-grid-tree-column.js, packages/vaadin-grid/src/vaadin-grid.js, packages/vaadin-grid/test/filtering.test.js, packages/vaadin-grid/test/renderers.test.js, packages/vaadin-grid/test/selection.test.js, packages/vaadin-grid/test/sorting.test.js, packages/vaadin-grid/test/tree-toggle.test.js
Previously, some internal grid components used Polymer templates to render a pre-defined cell content. 
The PR introduces the concept of default renders and converts all the internal grid templates to default renderers.
Fixes #1963
Related to #326 (removing the Polymer Template API from grids)
I found the logic of computing a final renderer to render is quite messy and not obvious to work with. The renderers used to be re-assigned in different observers, so that made it hard to know which renderer is being used at the moment. 
After a refactoring, all such the logic has been moved to computed properties, e.g:
- [`__computeHeaderRenderer`](https://github.com/vaadin/web-components/pull/1967/files#diff-37fc749a7a99c4f9c6690e4879c4657c493c59e185d41c3abdff95d08963c76dR694)
- …
=> ref!: convert internal grid templates to renderers

packages/vaadin-grid/src/vaadin-grid-column.js
After closing #1967, I rebased [the branch](https://github.com/vaadin/web-components/pull/2052) about removing Grid Template API. Surprisingly, default renderers didn't work when [the template logic](https://github.com/vaadin/web-components/pull/2052/files#diff-37fc749a7a99c4f9c6690e4879c4657c493c59e185d41c3abdff95d08963c76dR276-R280) is removed. 
According to [the Polymer documentation](https://polymer-library.polymer-project.org/3.0/docs/devguide/observers#define-a-computed-property), it doesn’t invoke a computed function until at least one of its dependencies gets defined (`!== undefined`). 
It turns out that after removing the template properties from the dependency list, all the remaining properties were `undefined`, so the final renderer wasn't computed.
This PR introduces a private …
=> fix: compute final renderers even dependencies are undefined

packages/vaadin-rich-text-editor/src/vaadin-rich-text-editor.js
`overflow: hidden` breaks the field highlight of Collaboration Engine. To me this property seems redundant, because `overflow: hidden` is also defined on the content part of RTE, and at least I couldn't find out a way to break anything with this change. Let me know if I've overlooked something.
More details in comment: https://github.com/vaadin/collaboration-engine/issues/29#issuecomment-845123081
Fixes https://github.com/vaadin/collaboration-engine/issues/29
=> fix: remove overflow: hidden from RTE

packages/vaadin-template-renderer/src/vaadin-template-renderer-templatizer.js, packages/vaadin-template-renderer/test/fixtures/mock-list-host.js, packages/vaadin-template-renderer/test/list.test.js
When calling `setProperties(...)` to re-render a Polymer template instance, it compares the new properties with old ones using the `===` operator to skip rendering not changed properties.
However, in case of an object property, the `===` operator can't determine whether the object has been mutated inside. Thus, the property won't be re-rendered when mutated. 
This issue appears in the template renderer when mutating the `model.item` object after it is bound to a template. 
This PR introduces a workaround that forces `model.item` template bindings to re-render even the new item is strictly equal to the old item.
=> fix: force model's item bindings to re-render in template renderer

packages/vaadin-grid/test/basic.test.js, packages/vaadin-virtual-list/src/virtualizer-iron-list-adapter.js
This fixes a regression from https://github.com/vaadin/web-components/pull/321
Open https://vaadin.com/docs/latest/ds/components/grid Scroll any of the grids on Safari and the header disappears once the scrolling stops (as the DOM rows get reordered)
The [original fix to the issue was removed](https://github.com/vaadin/web-components/pull/321/files#diff-087afca125e21a05da8e5d0dd9093fbd66f748f1fa124c4076fd2c4b28fac8d0L317-L323) because it wasn't caught by any of the tests with the new architecture. Turns out the issue was still there but the test just needed a change in timing. This PR restores the [original fix](https://github.com/vaadin/vaadin-grid/pull/1799).
=> fix: workaround a Safari sticky positioning issue

packages/vaadin-grid/src/vaadin-grid.js, packages/vaadin-grid/test/column-auto-width.test.js
This fixes a regression from #321 and slightly changes the behavior of `column.autoWidth`
After #321, the number of DOM elements representing the items (`<tr>`) is no longer deterministic. This had a direct impact on the resulting column widths when using `column.autoWidth` (making the resulting column auto width also non-deterministic).
This PR changes the behavior so that samples for the auto width calculation are only taken from the body cells, whose parent rows are included in the _visible viewport_. Any rows outside the viewport, even if in the DOM, are excluded from the calculation.
=> fix: exclude non-visible body cells from grid column auto width calc

packages/vaadin-date-picker/src/vaadin-date-picker-mixin.d.ts, packages/vaadin-date-picker/src/vaadin-date-picker-mixin.js
Corrected date picker docs to state that the whole i18n object must be replaced to trigger data-binding, and provided example on how to extend the existing i18n object with just a few specific properties.
=> docs: clarify date picker i18n usage

wtr-utils.js
Fixes test runner config to also apply filters for packages without unit/visual tests when all packages are tested.
=> chore: fix test runner filtering when no packages have changed

.eslintrc.json, packages/vaadin-grid/src/vaadin-grid-filter-column.js
As long as the Vaadin Platform targets ES2019 we can't use the optional chaining operator (`?.`) in the mono-repo.
This PR removes any uses of the optional chaining operator in the mono-repo and fixes the ECMA version for the ESLint parser to align it with the Platform's version (`2019`).
=> fix: don't use optional chaining operator

packages/vaadin-grid/src/vaadin-grid-a11y-mixin.js, packages/vaadin-grid/src/vaadin-grid-row-details-mixin.js, packages/vaadin-grid/src/vaadin-grid.js, packages/vaadin-grid/test/renderers.test.js, packages/vaadin-grid/test/row-details.test.js
`bodyRenderer` is invoked with the `model.detailsOpened` property that means the renderer's result can depend on this property. 
The correct behavior would be to re-call the body renderer once opening details, that unfortunately doesn't happen now.
[According to the code](https://github.com/vaadin/web-components/blob/master/packages/vaadin-grid/src/vaadin-grid-row-details-mixin.js#L157), `rowDetailsRenderer` is invoked with only: `model.item` and `model.index`.
As for template instances, it seems they are invoked with the “standard” row model including `item`, `index`, `level`, `expanded` and so on. (look at [here](https://github.com/vaadin/web-components/blob/master/packages/vaadin-grid/src/vaadin-grid-row-details-mixin.js#L163) and …
=> fix!: re-render row when toggling details

packages/vaadin-grid/src/interfaces.d.ts, packages/vaadin-grid/src/vaadin-grid-event-context-mixin.d.ts, packages/vaadin-grid/src/vaadin-grid-event-context-mixin.js, packages/vaadin-grid/src/vaadin-grid-keyboard-navigation-mixin.js, packages/vaadin-grid/src/vaadin-grid.d.ts, packages/vaadin-grid/src/vaadin-grid.js, packages/vaadin-grid/test/typings/grid.types.ts
Added API docs and type definitions for the cell-focus event. Also corrected type definitions for `EventContextMixin.getEventContext` to always return a `GridEventContext` with all props being optional.
Related to: #337
=> feat: add API docs for grid cell focus event

packages/vaadin-template-renderer/src/vaadin-template-renderer-templatizer.js, packages/vaadin-template-renderer/test/vaadin-template-renderer.test.js
Currently, the template renderer doesn't re-render the template instance after the instance's root has been detached from DOM (by the user, for example).
This issue came up while removing Polymer Template API from `vaadin-grid-pro`. There is `editModeRenderer` that replaces the content rendered by `renderer` with an input when editing a column. Once you finish editing, it calls `renderer` to return the original content to the column, but at that time the template instance' root turns disconnected with DOM and nothing is rendered.
This PR aims to address this issue. From now on, the template renderer creates a new template instance if for some reasons the instance's root is detached from DOM.
Related to #410.
=> fix: re-create template instance after detaching instance's root

packages/vaadin-grid/package.json, packages/vaadin-grid/src/vaadin-grid.js, packages/vaadin-grid/test/lit.test.js
This fixes a regression from #321
Seems that with very specific timing, it's possible to end up with a grid that has non-empty `items` but no visible rows. The bug was reported as part of a Lit project and I couldn't find a way to reproduce it without using Lit in the test as well.
The offending line [was added a long time ago](https://github.com/vaadin/vaadin-grid/commit/7957099c02e1636adcaf7fa83770976058c4a2f8#) and doesn't seem to be relevant anymore. Only the virtualizer should be in charge of hiding/unhiding the body row elements.
=> fix: don't hide rows in the grid logic

packages/vaadin-icons/package.json
The new `vaadin-iconset.js` file should be included in the package
=> fix: include vaadin-iconset.js in the package

packages/vaadin-crud/src/vaadin-crud-edit-column.js, packages/vaadin-crud/src/vaadin-crud.js
A small refactoring that makes `vaadin-crud-edit-column` use the default renderer instead of defining a custom renderer in the constructor.
=> ref: use default renderer for crud edit column

packages/vaadin-grid/src/vaadin-grid-selection-column.js, packages/vaadin-grid/test/selection.test.js
Seems that the `<vaadin-grid-selection-column>`'s default value for the `selectAll` property causes pre-selection to get cleared.
=> fix: avoid having selectAll default value clear pre-selections

packages/vaadin-text-field/theme/lumo/vaadin-text-area-styles.js
Fixes #1149
When you hover over an invalid `vaadin-text-area` it should keep the background as is.
Fixes the problem by excluding `[invalid]` state when applying `:hover` styles.
=> fix: keep the invalid indicating background on hover

packages/vaadin-virtual-list/src/vaadin-virtual-list.js, packages/vaadin-virtual-list/test/virtual-list.test.js
Align the default height of `<vaadin-virtual-list>` with that of `<vaadin-grid>` as suggested [here](https://github.com/vaadin/flow-components/issues/179#issuecomment-411301614)
=> chore: increase the virtual-list default height

packages/vaadin-grid/src/interfaces.d.ts, packages/vaadin-grid/test/typings/grid.types.ts
It shouldn't be possible for the grid body renderer not to have a defined `model`. The current typings require you to either check for the `model`:
```ts
private renderer: GridBodyRenderer<Person> = (root, _column, model) => {
root.textContent = model ? model.item.lastName : '';
};
```
or use non-null assertion:
```ts
private renderer: GridBodyRenderer<Person> = (root, _column, model) => {
root.textContent = model!.item.lastName;
};
```
=> fix: make grid renderer arguments required

packages/vaadin-template-renderer/src/vaadin-template-renderer.js, packages/vaadin-template-renderer/test/fixtures/mock-component.js, packages/vaadin-template-renderer/test/fixtures/mock-grid-host.js, packages/vaadin-template-renderer/test/grid-body.test.js, packages/vaadin-template-renderer/test/grid-editor.test.js, packages/vaadin-template-renderer/test/grid-footer.test.js, packages/vaadin-template-renderer/test/grid-header.test.js, packages/vaadin-template-renderer/test/grid-row-details.test.js, packages/vaadin-template-renderer/test/vaadin-template-renderer.test.js
Previously, all the components which had the public support of the Polymer Template API used to throw an exception when using both a template and a renderer. So far as it was a part of the Template API and we no longer support this API, it was decided that the Template Renderer should throw such exceptions instead.
This PR has a purpose to support throwing such exceptions for the Template Renderer.
=> feat: throw when using both a template and a renderer

packages/vaadin-combo-box/src/vaadin-combo-box-mixin.js, packages/vaadin-context-menu/src/vaadin-context-menu.js, packages/vaadin-dialog/src/vaadin-dialog.js, packages/vaadin-element-mixin/package.json, packages/vaadin-element-mixin/templates.js, packages/vaadin-element-mixin/test/templates.test.js, packages/vaadin-grid-pro/test/grid-pro.test.js, packages/vaadin-grid/src/vaadin-grid-column.js, packages/vaadin-grid/src/vaadin-grid.js, packages/vaadin-notification/src/vaadin-notification.js, packages/vaadin-notification/test/renderer.test.js, packages/vaadin-select/src/vaadin-select.js, packages/vaadin-time-picker/src/vaadin-time-picker.js, packages/vaadin-virtual-list/src/vaadin-virtual-list.js
Since the Template API has been removed, we need to warn the user to import `@vaadin/vaadin-template-renderer` if he attempts to use templates inside a component that previously supported the API.
Fixes #312, #1970.
=> feat: warn if using legacy Template API

packages/vaadin-template-renderer/src/vaadin-template-renderer.js, packages/vaadin-template-renderer/test/warning.test.js, wtr-utils.js
Since [the previous PR](https://github.com/vaadin/web-components/pull/2101), we have started showing a warning when the user attempts to use legacy Template API without importing the template renderer. 
But even when the user has imported the template renderer, we want to show another warning once per component to encourage using renderer functions instead of templates, e.g:
```
WARNING: <template> inside <vaadin-combo-box> is deprecated. Use a renderer function instead (see https://vaad.in/template-renderer)
```
This warning can be manually suppressed by adding the `suppress-template-warning` attribute to a component that the user wants to use templates with:
```html
<vaadin-combo-box suppress-template-warning>
<template>
...
</template>
</vaadin-combo-box>
```
Closes #313
=> feat: warn if suppress-template-warning attribute is not defined

packages/vaadin-lumo-styles/all-imports.d.ts, packages/vaadin-lumo-styles/all-imports.js, packages/vaadin-lumo-styles/utilities/accessibility.js, packages/vaadin-lumo-styles/utilities/background.js, packages/vaadin-lumo-styles/utilities/border.js, packages/vaadin-lumo-styles/utilities/flexbox-grid.js, packages/vaadin-lumo-styles/utilities/index.d.ts, packages/vaadin-lumo-styles/utilities/index.js, packages/vaadin-lumo-styles/utilities/layout.js, packages/vaadin-lumo-styles/utilities/shadows.js, packages/vaadin-lumo-styles/utilities/sizing.js, packages/vaadin-lumo-styles/utilities/spacing.js, packages/vaadin-lumo-styles/utilities/typography.js
Add the latest version of the Lumo utility classes from https://github.com/anezthes/lumo-css-framework as a new Lumo style module.
Removed the `space-...` /  `spacing-...` classes after discussion with Jonte + Rolf. They had some behaviour that could be unexpected and we decided to only support `gap-...` for flex box and grid layouts for now.
=> feat: add lumo utility classes

packages/vaadin-virtual-list/src/vaadin-virtual-list.js, packages/vaadin-virtual-list/src/virtualizer.js
The type of `firstVisibleIndex` and `lastVisibleIndex` currently documents as `?` in https://cdn.vaadin.com/vaadin-web-components/21.0.0-alpha8/#/elements/VirtualListElement#property-firstVisibleIndex. This PR fixes the getter return types.
=> fix: update typing of virtual-list first/lastVisibleIndex getters

packages/vaadin-lumo-styles/package.json
Individual files containing utility classes were not added to package.json, which means they would not be released.
Fixes #2147
=> chore: add utility classes to package.json files

packages/vaadin-charts/src/interfaces.d.ts, packages/vaadin-charts/src/vaadin-chart.d.ts, packages/vaadin-charts/src/vaadin-chart.js, packages/vaadin-charts/test/chart-element.test.js, packages/vaadin-charts/test/chart-properties.test.js, packages/vaadin-charts/test/events.test.js, wtr-utils.js
LitElement reserves the `update()` method so that we cannot use it to update chart configuration anymore.
This PR deprecates `update()` and introduces `updateConfiguration()` instead. Though calling `update()` still updates chart configuration, now it shows a deprecation warning as well.
Part of #73 (issue)
=> feat: deprecate update() in favor of updateConfiguration()

packages/vaadin-upload/src/vaadin-upload.js, packages/vaadin-upload/test/upload.test.js
This change separates error messages of `vaadin-upload` component based on their origin. Those that are client error, specifically 401 and 403 errors which are related to authentication and authorization, and the one that has 0 as status code which generally means browser wasn't able to make the request (timeout, ...)
This change also has changed the structure of `i18n` file to better reflect these errors on translation keys.
Fixes #425
=> feat: improve error messages of upload

packages/vaadin-grid/src/vaadin-grid-keyboard-navigation-mixin.js, packages/vaadin-grid/test/keyboard-navigation.test.js
This PR solves the issue with the grid when the table body of the grid is clicked and enter key is hit, the error shows when no row of the table is selected, Or as in the mentioned in the issue when a row is clicked and empty area of the table is selected and enter key is hit.
Fixes: https://github.com/vaadin/flow-components/issues/1011
=> fix: issue with grid when grid table body is clicked and enter key is hit

packages/vaadin-menu-bar/src/vaadin-menu-bar-buttons-mixin.js, packages/vaadin-menu-bar/test/menu-bar.test.js, wtr-utils.js
LitElement reserves the `render()` method to return TemplateResult so we cannot use it for re-rendering `vaadin-menu-bar` anymore.
This PR deprecates `render()` for `vaadin-menu-bar` and supposes it to be removed later.
Part of #73
=> feat: deprecate render() for menu-bar

packages/vaadin-combo-box/src/vaadin-combo-box-item.js, packages/vaadin-combo-box/src/vaadin-combo-box-mixin.d.ts, packages/vaadin-combo-box/src/vaadin-combo-box-mixin.js, packages/vaadin-combo-box/test/item-renderer.test.js, packages/vaadin-context-menu/src/vaadin-context-menu.d.ts, packages/vaadin-context-menu/src/vaadin-context-menu.js, packages/vaadin-context-menu/test/renderer.test.js, packages/vaadin-dialog/src/vaadin-dialog.d.ts, packages/vaadin-dialog/src/vaadin-dialog.js, packages/vaadin-dialog/test/renderer.test.js, packages/vaadin-grid/src/vaadin-grid.d.ts, packages/vaadin-grid/src/vaadin-grid.js, packages/vaadin-grid/test/class-name-generator.test.js, packages/vaadin-grid/test/column.test.js, packages/vaadin-grid/test/data-provider.test.js, packages/vaadin-grid/test/renderers.test.js, packages/vaadin-notification/src/vaadin-notification.d.ts, packages/vaadin-notification/src/vaadin-notification.js, packages/vaadin-notification/test/renderer.test.js, packages/vaadin-overlay/src/vaadin-overlay.d.ts, packages/vaadin-overlay/src/vaadin-overlay.js, packages/vaadin-overlay/test/renderer.test.js, packages/vaadin-select/src/vaadin-select.d.ts, packages/vaadin-select/src/vaadin-select.js, packages/vaadin-select/test/renderer.test.js, wtr-utils.js
LitElement reserves the `render()` method to return `TemplateResult` so we cannot use it to run renderers anymore.
This PR deprecates `render()` and introduces `requestContentUpdate()` instead. 
**Difference:**
- `render()` **did** guarantee that rendering happens immediately after the method is called.
- `requestContentUpdate()` **does not** guarantee that rendering happens immediately (synchronously) after the method is called.
**Components:**
Fixes #73.
=> feat: deprecate render() in favor of requestContentUpdate()

packages/vaadin-virtual-list/src/virtualizer-iron-list-adapter.js, packages/vaadin-virtual-list/test/virtualizer.test.js
Fixes https://github.com/vaadin/web-components/issues/2164
=> fix: skip virtualizer flush if scrollTarget is hidden

packages/vaadin-grid/src/vaadin-grid-keyboard-navigation-mixin.js, packages/vaadin-grid/src/vaadin-grid.d.ts, packages/vaadin-grid/test/keyboard-navigation.test.js, packages/vaadin-grid/test/typings/grid.types.ts
This change adds event context for grid cells into the event object itself and removes an excess call to another method for getting the context that the event happened. It also modifies some type to reflect newly added fields into the propagated event.
It also adds required test cases and also modifies another test so that newly added tests run correctly.
Fixes #2130
=> feat: add context to event data and update relevant types.

packages/vaadin-grid-pro/package.json, packages/vaadin-grid-pro/src/vaadin-grid-pro-edit-column.js, packages/vaadin-grid-pro/test/lit.test.js, packages/vaadin-grid/src/vaadin-grid-column.js, packages/vaadin-grid/test/lit-renderers.test.js, packages/vaadin-grid/test/lit.test.js, packages/vaadin-notification/package.json, packages/vaadin-notification/src/vaadin-notification.js, packages/vaadin-notification/test/lit.test.js, packages/vaadin-overlay/package.json, packages/vaadin-overlay/src/vaadin-overlay.js, packages/vaadin-overlay/test/lit.test.js
Disposes of Lit parts after clearing `innerHTML` to prevent throwing exceptions when running Lit-based renderers afterward.
Fixes #2161 (issue)
=> fix: dispose of Lit parts after clearing innerHTML

package.json, rollup.config.js, yarn.lock
Replaced `@open-wc/rollup-plugin-html` with a newer version `@web/rollup-plugin-html` which has less dependencies.
=> chore: update rollup dependencies and config

packages/vaadin-date-picker/theme/material/vaadin-date-picker-light.js
The style import of the `material` theme for `vaadin-date-picker-light` where pointing at the wrong files.
This PR corrects them.
Fixes # (issue)
=> fix: Correct material theme imports of `vaadin-date-picker-light`

packages/vaadin-split-layout/src/vaadin-split-layout.js, packages/vaadin-text-field/src/vaadin-text-area.js, packages/vaadin-text-field/src/vaadin-text-field-mixin.js
The `iron-resize` event is an internal implementation detail, yet it's currently documented as a part of the public API of:
- vaadin-text-field
- vaadin-number-field
- vaadin-email-field
- vaadin-password-field
- vaadin-text-area
- vaadin-split-layout
This commit adda a depracation note for this event in  the API docs. The intention is to drop this even in the future when the implementat will change from IronResizableBehavior to ResizeObserver.
Fixes #2167
=> docs: deprecate the `iron-resize` event [skip ci]

packages/vaadin-grid/src/iron-list.js, packages/vaadin-grid/test/basic.test.js
If a resize or any event that triggers `iron-resize` happens as the Grid is about to hide, it may lead to some calculations to happen when the Grid is already hidden. That may lead to some misbehavior, like described on the linked issue.
This fix checks the visibility status of the Grid to skip metrics calculation in case the Grid is not visible.
Fixes https://github.com/vaadin/web-components/issues/2127
=> fix: skip calculation when grid is hidden

packages/vaadin-text-field/test/text-area.test.js, packages/vaadin-text-field/test/text-field.test.js
This is a follow-up from #2232 
1. Updated the tests to use `shadowRoot` and not `root`
2. Removed an old test which does not make sense anymore
=> test: cleanup helper text unit tests

packages/vaadin-checkbox/test/checkbox-group.test.js, packages/vaadin-custom-field/test/helper.test.js, packages/vaadin-text-field/test/text-area.test.js, packages/vaadin-text-field/test/text-field.test.js
1. Updated all the tests for helper focus removal to use spy and avoid relying on `focused` attribute.
2. Minor cleanup: removed nested components in slotted helper tests, removed empty newlines.
See #2255
=> test: cleanup and fix helper focus tests

packages/vaadin-crud/src/vaadin-crud.d.ts, packages/vaadin-crud/src/vaadin-crud.js
1. Updated API docs to mention `slot="toolbar"` instead of no longer existing `new` and `footer` slots,
2. Fixed the code snippet in API docs that was broken when adding JS snippet for column renderers.
=> docs: fix API docs for crud slots [skip ci]

wtr-utils.js
Update the web test runner change detection script to use 21.0 as a base branch for Vaadin 21.
=> chore: update change detection branch to 21.0

packages/field-base/index.d.ts, packages/field-base/index.js, packages/field-base/src/field-aria-mixin.d.ts, packages/field-base/src/field-aria-mixin.js, packages/field-base/src/helper-text-mixin.d.ts, packages/field-base/src/helper-text-mixin.js, packages/field-base/src/validate-mixin.d.ts, packages/field-base/src/validate-mixin.js, packages/field-base/test/field-aria-mixin.test.js, packages/field-base/test/helper-text-mixin.test.js, packages/field-base/test/validate-mixin.test.js
This is a second batch of mixins that are needed to implement slotted `input` support in field components.
Fixes #2183
=> feat: add mixins to handle slotted helper and error message

packages/vaadin-combo-box/src/interfaces.d.ts, packages/vaadin-combo-box/src/vaadin-combo-box-mixin.d.ts, packages/vaadin-combo-box/test/typings/combo-box.types.ts
This PR fixes the inconsistency between `selectedItem` type in combo box mixin definition and interfaces that we have defined for events.
Fixes #2214
=> fix: allow null and undefined in selected-item-changed event

.github/workflows/chrome.yml, .github/workflows/firefox.yml, .github/workflows/lint.yml, .github/workflows/lumo.yml, .github/workflows/material.yml, .github/workflows/webkit.yml
Updated GitHub Actions config to use the built-in caching, see https://github.com/actions/setup-node/pull/272
=> chore: use actions/setup-node built-in cache

.github/workflows/firefox.yml, .github/workflows/webkit.yml
The GitHub Action is deprecated (see its [README](https://github.com/microsoft/playwright-github-action)) and it is recommended to use Playwright CLI, starting with Playwright 1.8.0.
=> chore: use playwright-cli to install deps

packages/field-base/index.d.ts, packages/field-base/index.js, packages/field-base/src/delegate-focus-mixin.d.ts, packages/field-base/src/delegate-focus-mixin.js, packages/field-base/src/disabled-mixin.d.ts, packages/field-base/src/disabled-mixin.js, packages/field-base/src/focus-mixin.d.ts, packages/field-base/src/focus-mixin.js, packages/field-base/test/delegate-focus-mixin.test.js, packages/field-base/test/disabled-mixin.test.js, packages/field-base/test/focus-mixin.test.js
This is a third batch of mixins that are needed to implement slotted `input` support in field components.
The code is mostly the same as in `ControlStateMixin`, but there are two important differences:
1. We expect the `focusElement` to be in light DOM so event listeners are updated accordingly,
2. We no longer set `tabindex` on the host element, and it is no longer focusable. So we don't handle `tabindex` and expect the user to set it directly on the slotted `<input>` if needed (although we should not encourage doing this).
Fixes #2186
=> feat: add mixins to handle focus and disabled state

packages/field-base/index.d.ts, packages/field-base/index.js, packages/field-base/src/clear-button-mixin.d.ts, packages/field-base/src/clear-button-mixin.js, packages/field-base/src/input-props-mixin.d.ts, packages/field-base/src/input-props-mixin.js, packages/field-base/test/clear-button-mixin.test.js, packages/field-base/test/input-props-mixin.test.js
This is a PR to add two mixins:
1. `InputPropsMixin` used to propagate some properties to the slotted `input`.
2. `ClearButtonMixin` used to handle a clear button in field components.
Fixes #2187 
=> feat: add mixins for input properties and clear button

packages/field-base/index.d.ts, packages/field-base/index.js, packages/field-base/src/input-field-mixin.d.ts, packages/field-base/src/input-field-mixin.js, packages/field-base/src/text-field-mixin.d.ts, packages/field-base/src/text-field-mixin.js, packages/field-base/test/input-field-mixin.test.js, packages/field-base/test/text-field-mixin.test.js
This is a PR to add two mixins:
1. `InputFieldMixin` used to implement hanling `value` and a few other properties,
2. `TextFieldMixin` used to add validation constraints such as `pattern`, `maxlength` and `minlength`.
Fixes #2188 
=> feat: add mixins for text-field and related components

packages/vaadin-grid/src/vaadin-grid-row-details-mixin.d.ts, packages/vaadin-grid/src/vaadin-grid-row-details-mixin.js, packages/vaadin-grid/src/vaadin-grid-selection-mixin.d.ts, packages/vaadin-grid/src/vaadin-grid-selection-mixin.js, packages/vaadin-grid/test/typings/grid.types.ts
The properties `selectedItems` and `detailsOpenedItems` which expected to always contain an array of items.
Both have a default value which is an empty array, so we should disallow setting them to `null` or `undefined`.
Fixes #2296
- Bugfix
=> fix: use more strict types for grid properties

packages/vaadin-grid/src/vaadin-grid-column-group.js, packages/vaadin-grid/src/vaadin-grid-column-reordering-mixin.js, packages/vaadin-grid/src/vaadin-grid-helper.js, packages/vaadin-grid/src/vaadin-grid-helpers.js, packages/vaadin-grid/test/column-groups.test.js
This PR fixes the issue with setting `order` of header columns, the current approach uses bases of 10 to assign order correctly to columns and their children.
The current approach assignes multiple of `_orderBaseScope` (equal to 10000000) to root columns and children order are calculated based on these base numbers. For example if we have 100 children for our group, because number of digits of child count is 3, we can uniquely assign each child an order from numbers in this range 1xxx0000. (or by adding multiples of 10000 to base order). When doing so, multiples of 10, introduce and extra zero to our newly order and this extra zero, causes the calculations to go wrong in some nodes.
This PR solves this issue by avoiding multiples of 10 when forming new order value for child columns or …
=> fix: correct setting order of columns when we have more than 10 columns

packages/field-base/src/input-field-mixin.js, packages/field-base/test/input-field-mixin.test.js
This is a small fix to align the new implementation of the text field components with the old one.
Fixes #2317
- Bugfix
=> fix: do not reset initial invalid state

packages/text-field/theme/lumo/vaadin-text-field-styles.js, packages/text-field/theme/material/vaadin-text-field-styles.js
This is a small fix to make it possible to use new `vaadin-password-field` and old `vaadin-text-field`.
The module IDs was incorrectly duplicated causing rendering issues, so we need to update it.
- Bugfix
=> fix: avoid conflicting style module IDs

packages/custom-field/src/vaadin-custom-field.js, packages/custom-field/theme/lumo/vaadin-custom-field-styles.js, packages/custom-field/theme/material/vaadin-custom-field-styles.js, packages/number-field/src/vaadin-number-field.js, packages/text-area/src/vaadin-text-area.js, packages/text-field/src/vaadin-text-field.js, packages/text-field/theme/lumo/vaadin-input-field-shared-styles.js, packages/text-field/theme/material/vaadin-input-field-shared-styles.js, packages/vaadin-lumo-styles/mixins/required-field.js, packages/vaadin-material-styles/mixins/required-field.js
1. Updated the required indicator to use a dedicated HTML element with `indicator` part
2. Changed the new fields to use the new indicator (the old ones are still using pseudo element)
3. Updated Lumo to include fix for incorrect animation by always using `padding` on the label part.
See https://github.com/vaadin/vaadin-lumo-styles/pull/92
Fixes #2301
Fixes #1634
- Feature
=> feat: add indicator part to new fields

packages/email-field/theme/lumo/vaadin-email-field-styles.js, packages/email-field/theme/material/vaadin-email-field-styles.js, packages/email-field/theme/material/vaadin-email-field.js, packages/password-field/theme/lumo/vaadin-password-field-styles.js, packages/password-field/theme/material/vaadin-password-field-styles.js, packages/text-field/test/visual/lumo/text-field.test.js, packages/text-field/test/visual/lumo/vaadin-text-field.js, packages/text-field/test/visual/material/text-field.test.js, packages/text-field/test/visual/material/vaadin-text-field.js, packages/text-field/theme/lumo/vaadin-text-field-styles.js
This is a follow-up from #2323 tackling the same problem but in a better way.
1. Commented out the new theme module that applies to `vaadin-text-field` component, 
2. Updated `@vaadin/password-field` and `@vaadin/email-field` to import the new module,
3. Updated the visual tests in the `@vaadin/text-field` to keep visual tests working.
This fixes visual tests in the following PRs: #2319 , #2320 
- Bugfix
=> fix: temporarily disable new text-field styles

packages/vaadin-combo-box/package.json, packages/vaadin-combo-box/src/vaadin-combo-box-item.js, packages/vaadin-combo-box/test/item-renderer.test.js, packages/vaadin-combo-box/test/lit.test.js, packages/vaadin-virtual-list/package.json, packages/vaadin-virtual-list/src/vaadin-virtual-list.js, packages/vaadin-virtual-list/test/lit.test.js, packages/vaadin-virtual-list/test/virtual-list.test.js
Fixes #2235
This is a follow-up for https://github.com/vaadin/web-components/pull/2172 and addresses the same issues in `<vaadin-combo-box>` and `<vaadin-virtual-list>`.
=> fix: dispose of Lit parts after changing a renderer [combo-box, virtual-list]

packages/vaadin-upload/src/vaadin-upload-file.js
> Whenever is possible, decrease the complexity of CSS selectors to facilitate their overriding for the user later on.
This PR is a follow-up for https://github.com/vaadin/web-components/pull/2316 and intends to decrease the complexity of a CSS selector applied for `vaadin-upload-file`.
=> fix: decrease complexity of CSS selectors

packages/password-field/src/vaadin-password-field.d.ts, packages/password-field/src/vaadin-password-field.js, packages/password-field/test/password-field.test.js
Added `i18n` object to the new version of `vaadin-password-field` to allow customizing the reveal button `aria-label`.
Fixes #2327
- Feature
=> feat: add i18n property to password-field

packages/text-field/theme/lumo/vaadin-input-field-shared-styles.js, packages/text-field/theme/material/vaadin-input-field-shared-styles.js
The old implementations with the `input` in Shadow DOM apply these styles (they get inherited from the `:host`).
We need to update the new components to apply them too, it should prevent regressions in some visual tests.
- Bugfix
=> fix: set font smoothing to slotted input

packages/vaadin-charts/src/vaadin-chart.js, packages/vaadin-charts/test/chart-element.test.js
This PR reduces the initialization time of charts up to ~2x by replacing a `redraw` call in a loop (by series) with a single `redraw` at the end of the loop.
~~This PR also is assumed to improve the situation described in the https://github.com/vaadin/flow-components/issues/937 issue.~~
Part of  #227
**Machine:** Mac Mini M1 16gb.
**Browser:** Chrome 92.
**Screen size:** 700x700.
- Each series represents 20 values
```html
<div id="chart"></div>
import { render, html } from 'lit';
import '@vaadin/vaadin-charts';
const series = [...new Array(10)].map((_, i) => {
return {
values: [...new Array(20)].map(() => i)
}
});
render(html`
<vaadin-chart>
${series.map((series) =>
html`
<vaadin-chart-series .values="${series.values}"></vaadin-chart-series>
`
)}
</vaadin-chart>
`, …
```
=> perf: reduce charts initialization time up to ~2x

packages/vaadin-rich-text-editor/test/basic.test.js
Manual cherry-pick of c73dcabee9732c5a589015d1c421aa49b308d02e from `20.0`, to be cherry-picked to `21.0` by bot.
=> test: fix version regex to allow RC (#1999) (#2051)

packages/button/package.json, packages/button/src/vaadin-button.d.ts, packages/button/src/vaadin-button.js, packages/button/test/button.test.js
As it turns out, `DelegatedFocusMixin` doesn't support delegating focus through Shadow DOM. That causes new buttons (from `@vaadin/button`) to end up with no `focus-ring` attribute when focusing via <kbd>Tab</kbd>.
This PR brings `@vaadin/button` back to use `ControlStateMixin` instead of `DelegatedFocusMixin`.
It also adds missing tests for the `focus-ring` attribute and removes some legacy tests.
Part of #2224
=> fix: set focus-ring attribute on new button

packages/vaadin-avatar/test/avatar.test.js, packages/vaadin-control-state-mixin/test/control-state-mixin.test.js, packages/vaadin-custom-field/test/basic.test.js, packages/vaadin-grid-pro/test/edit-column-overlay.test.js, packages/vaadin-grid-pro/test/edit-column-renderer.test.js, packages/vaadin-grid-pro/test/edit-column-type.test.js, packages/vaadin-grid-pro/test/edit-column.test.js, packages/vaadin-grid/test/keyboard-navigation.test.js, packages/vaadin-menu-bar/test/menu-bar.test.js, packages/vaadin-rich-text-editor/test/a11y.test.js, packages/vaadin-rich-text-editor/test/basic.test.js, packages/vaadin-time-picker/test/form-input.test.js
Updated some tests to use `focusin` and `focusout` helpers from `@vaadin/testing-helpers` package.
=> test: use focusin and focusout helpers

packages/vaadin-menu-bar/src/vaadin-menu-bar-buttons-mixin.js, packages/vaadin-menu-bar/src/vaadin-menu-bar-interactions-mixin.js
Refactored `vaadin-menu-bar` mixins to move some code into separate methods.
The idea behind this approach is to override some of them when updating component to place buttons in light DOM.
At the same time, most of the implementation will remain unchanged to make the diff smaller and easier to review.
Related to #2227
=> refactor: split code into smaller methods

packages/vaadin-menu-bar/src/interfaces.d.ts, packages/vaadin-menu-bar/src/vaadin-menu-bar.d.ts, packages/vaadin-menu-bar/src/vaadin-menu-bar.js, packages/vaadin-menu-bar/test/menu-bar.test.js
Same as #2381 but from the branch in this repo.
To be accessible, the menu bar overflow button needs the aria-label attribute to be set.
The attribute should be localizable. As such, this adds an i18n object to the menu bar,
and uses it to set the aria-label of the overflow button.
Connected to #87
=> feat: add i18n property to menu bar

packages/button/src/vaadin-button.js
At this moment, text on the new button can be selected that is not allowed for the native `<button>`.
This PR prevents text selection for the new button to align its behavior with the native `<button>`.
Part of #2224
=> fix: prevent text selection for new button

packages/vaadin-app-layout/src/vaadin-drawer-toggle.js, packages/vaadin-app-layout/test/drawer-toggle.test.js
This PR is a follow-up for https://github.com/vaadin/web-components/pull/2373#discussion_r698256932. 
The new accessible implementation of `<vaadin-button>` doesn't utilize the native button anymore; thus, the native button should be also removed from `<vaadin-drawer-toggle>` (because it extends `<vaadin-button>`).
Part of #2224.
=> refactor!: remove native button from drawer toggle

packages/vaadin-grid/src/vaadin-grid-tree-column.js, packages/vaadin-grid/test/tree-toggle.test.js
A tree grid item's level doesn't get applied to a `<vaadin-grid-tree-toggle>` generated by the `<vaadin-grid-tree-column>` default renderer:
This PR fixes the issue by applying the level in the column's default renderer:
=> fix: reflect tree grid level in a tree column toggle

packages/field-base/src/field-aria-mixin.js, packages/field-base/src/helper-text-mixin.js, packages/field-base/test/field-aria-mixin.test.js, packages/field-base/test/helper-text-mixin.test.js
1. Added a check for custom helper `id` to not override it with the generated one (to now break component ITs)
2. Added a `MutationObserver` to detect removal of a custom `id` on the helper and restore the generated one
Fixes #2382
- Bugfix
=> fix: do not override custom helper component ID

packages/field-base/src/tabindex-mixin.js, packages/field-base/test/tabindex-mixin.test.js
This PR fixes a regression that appeared in Flow ITs after we released the new `@vaadin/button` package:
> When setting a custom `tabindex` attribute before the initialization of the button, the attribute gets overridden with the default `tabindex` value (`0`).
Fixes #2442
=> fix: accept custom tabindex attribute

packages/button/src/vaadin-button.js, packages/field-base/index.d.ts, packages/field-base/index.js, packages/field-base/src/active-mixin.d.ts, packages/field-base/src/active-mixin.js, packages/field-base/src/clear-button-mixin.d.ts, packages/field-base/src/clear-button-mixin.js, packages/field-base/src/keyboard-mixin.d.ts, packages/field-base/src/keyboard-mixin.js, packages/field-base/test/active-mixin.test.js, packages/field-base/test/keyboard-mixin.test.js
The `ActiveMixin`, `ClearButtonMixin` and future [`CheckedMixin`](https://github.com/web-padawan/a11y-vaadin-proto/blob/master/src/mixins/checked-mixin.js) all need to handle the `keyup` and `keydown` events. 
Along with that, [the prototype](https://github.com/web-padawan/a11y-vaadin-proto/blob/master/src/v-checkbox.js#L9) of the new Checkbox component supposes it to inherit both `ActiveMixin` and `CheckedMixin`. This being so, these mixins will end up in the same scope and there may happen a naming collision (in case both define a `_onKeyDown` method, for example).
So it was decided to introduce `KeyboardMixin` that is responsible for subscribing to the keyboard events while leaving actual implementation of the event handlers to the client (a component or another mixin).
See the …
=> feat: add KeyboardMixin and make other mixins use it

packages/button/src/vaadin-button.js, packages/button/test/button.test.js, packages/field-base/src/disabled-mixin.js, packages/field-base/test/disabled-mixin.test.js, packages/vaadin-app-layout/src/vaadin-drawer-toggle.js
The PR fixes a regression that appeared after we released the new `@vaadin/button` package:
> The `click` event doesn't get fired on the button once the user presses an activation key (Enter, Space) so that the button ends up not fully accessible from the keyboard.
Note, `<vaadin-drawer-toggle>` now fires the `drawer-toggle-click` event on `keydown` rather than `keyup` the way it was before. This might be considered as a breaking-change.
Fixes #2437
~~**WARNING:** Please, do not merge this PR before #2432 is merged.~~ (merged)
- https://www.w3.org/TR/wai-aria-practices/examples/button/button.html
- https://www.w3.org/TR/uievents/#event-type-keydown
=> fix: fire click on Enter and Space, but not when disabled

packages/vaadin-combo-box/package.json, packages/vaadin-combo-box/src/vaadin-combo-box-data-provider-mixin.js, packages/vaadin-combo-box/src/vaadin-combo-box-dropdown-wrapper.js, packages/vaadin-combo-box/src/vaadin-combo-box-mixin.js, packages/vaadin-combo-box/test/basic.test.js, packages/vaadin-combo-box/test/combo-box-light.test.js, packages/vaadin-combo-box/test/dynamic-size.test.js, packages/vaadin-combo-box/test/filtering.test.js, packages/vaadin-combo-box/test/helpers.js, packages/vaadin-combo-box/test/keyboard.test.js, packages/vaadin-combo-box/test/lazy-loading.test.js, packages/vaadin-combo-box/test/lit.test.js, packages/vaadin-combo-box/test/object-values.test.js, packages/vaadin-combo-box/test/overlay-position.test.js, packages/vaadin-combo-box/test/selecting-items.test.js, packages/vaadin-combo-box/theme/lumo/vaadin-combo-box-dropdown-styles.js, packages/vaadin-combo-box/theme/material/vaadin-combo-box-dropdown-styles.js, yarn.lock
Replaces the Polymer-based `<iron-list>` used for the dropdown items virtual scrolling with the internal virtualizer from `<vaadin-virtual-list>`.
Certain Flow `ComboBox` tests and the TB element still expect the `<vaadin-combo-box>` Web Component to use an `<iron-list>` internally. There's a [branch](https://github.com/vaadin/flow-components/tree/combo-box-virtualizer) with necessary changes to `ComboBox` that needs to be merged together with the Web Component version bump.
=> refactor: replace iron-list with virtualizer in combo-box

packages/vaadin-virtual-list/src/virtualizer-iron-list-adapter.js, packages/vaadin-virtual-list/test/virtualizer.test.js
This PR adds a fix that prevents virtualizer from creating unnecessary elements under specific conditions:
1. size is larger than zero but less than the existing physical elements count
2. iron-list's `_increasePoolIfNeeded` gets scheduled (for example by `scrollToIndex()` call)
3. size gets synchronously increased before the debouncer for `_increasePoolIfNeeded` is flushed
=> fix: don't create unnecessary virtualizer elements on size change

.gitignore
I don't want to accidentally add unnecessary files to the repository. 
Avoid accidentally committing `.vscode` folder and `.DS_Store` files.
=> chore: add vscode config folder and macos DS_Store files to gitignore

packages/field-base/index.d.ts, packages/field-base/index.js, packages/field-base/src/checked-mixin.d.ts, packages/field-base/src/checked-mixin.js, packages/field-base/test/checked-mixin.test.js, packages/field-base/test/delegate-state-mixin.test.js
This PR introduces `CheckedMixin` that manages the `checked` state of a component. 
This mixin is based on [the a11y prototype](https://github.com/web-padawan/a11y-vaadin-proto/blob/master/src/mixins/checked-mixin.js).
Note, the prototype implementation also manages the `aria-checked` attribute on the element. However, according to [the documentation](https://developer.mozilla.org/en-US/docs/Web/API/Element/ariaChecked), there is no need for `aria-checked` when using the native checkbox or radio button, hence `aria-checked` is not included in the final implementation.
This mixin is going to be used within the new accessible implementation for:
- `<vaadin-checkbox>` (#2212).
- `<vaadin-radio-button>` (#2213) 
Fixes #2210
=> feat: add CheckedMixin for checkbox and radio-button

packages/vaadin-lumo-styles/icons.js
Currently it is not possible to use the Lumo iconset with the `vaadin-icon` component that was introduced in 21:
```html
<vaadin-icon icon="lumo:bar-chart"></vaadin-icon> 
```
The issue is that the Lumo iconset is currently not loaded as a `vaadin-iconset`, which means that `vaadin-icon` can not find the icon collection.
To fix this I included the `vaadin-iconset.js` of the Lumo theme into the all imports file (via `icons.js`). That also means that both, the `iron-iconset` and `vaadin-iconset` versions of the Lumo iconset will be loaded, increasing the payload transmitted to the browser. As I understand it that is intended to allow backwards compatibility with `iron-icon` in the meantime.
Also not 100% in which versions this fix should land. For now I targeted master and 21.
=> fix: use lumo iconset with vaadin-icon

packages/vaadin-grid/test/keyboard-navigation.test.js
cherry-pick from https://github.com/vaadin/web-components/pull/2434
=> test: use a new grid instance in each keyboard navigation test

packages/field-base/src/slot-target-mixin.d.ts, packages/field-base/src/slot-target-mixin.js, packages/field-base/test/delegate-state-mixin.test.js, packages/field-base/test/slot-target-mixin.test.js
This PR introduces `SlotTargetMixin` that forwards every node from a source slot to a target element.
The `SlotTargetMixin` is based on [the prototype](https://github.com/web-padawan/a11y-vaadin-proto/blob/master/src/mixins/slot-target-mixin.js).
The `SlotTargetMixin` is needed by the future [`SlotLabelMixin`](https://github.com/web-padawan/a11y-vaadin-proto/blob/master/src/mixins/slot-label-mixin.js) to move the content from the default slot (a conventional way to define a label for a checkbox) to the slotted `<label>` element.
Part of #2211
=> feat: add SlotTargetMixin for checkbox and radio-button

packages/field-base/src/helper-text-mixin.d.ts, packages/field-base/src/input-field-mixin.js, packages/field-base/src/input-slot-mixin.d.ts, packages/field-base/src/text-area-slot-mixin.d.ts, packages/select/src/interfaces.d.ts, packages/select/src/vaadin-select.d.ts, packages/vaadin-notification/src/vaadin-notification.d.ts, tsconfig.json
Disables `skipLibCheck` in `tsconfig.json` in order to make the TypeScript compiler checking the components' type declarations again, e.g: `packages/button/src/vaadin-button.d.ts`.
The PR also fixes regressions in the type declarations which occurred during the period the option was enabled.
Fixes #2501
=> fix: disable skipLibCheck in tsconfig.json

packages/vaadin-grid/test/resizing.test.js
Updated tests for `all-rows-visible` to use `beforeEach` hook and move fixtures there.
- Tests
=> test: refactor all-rows-visible grid tests

packages/password-field/src/vaadin-password-field.js, packages/password-field/test/password-field.test.js
1. Updated the logic to check `getRootNode().activeElement` instead of using `:matches` selector
2. Changed the tests to reuse single button instance for tests that rely on `sendKeys`
This fixes failing tests in WebKit for `password-field` package.
- Bugfix
=> refactor: improve password-field logic and tests

packages/button/src/vaadin-button.js, packages/button/test/button.test.js
This PR fixes a regression that occurred after we released the new `@vaadin/button` component:
> The new implementation of vaadin-button scrolls the page on Space key press.
Fixes #2478
=> fix: prevent scrolling when pressing Space on button

package.json, yarn.lock
This seems to address the WebKit crashes - [example](https://github.com/vaadin/web-components/pull/2511/checks?check_run_id=3585758190)
See https://github.com/microsoft/playwright/issues/8873#issuecomment-917953613
- Dependency bump
=> chore: bump playwright to latest alpha

packages/field-base/src/delegate-focus-mixin.js, packages/field-base/test/delegate-focus-mixin.test.js
The original problem happens because of how we apply mixins: unlike other fields, in case of `vaadin-select` we initialize `focusElement` in the component itself, and not in a deeply nested mixins like `InputSlotMixin`.
But the root cause is the fact that `disabled` property is not set on the lazily added `focusElement`. This PR fixes it.
Fixes #2472
- Bugfix
=> fix: set disabled on lazily added focusElement

packages/vaadin-charts/src/vaadin-chart.js, packages/vaadin-charts/test/chart-element.test.js
The PR reduces chart redraws when updating a chart via `updateConfiguration()` method so that the chart is now re-drawn only 1 time after `updateConfiguration()` is called.
This significantly improves the time of updating a chart with many series (up to 29x in case of 20 series).
Part of #227
Related to https://github.com/vaadin/flow-components/issues/937
**Machine:** Mac Mini M1 16gb.
**Browser:** Chrome 93.
**Screen size:** 1000x900.
- The chart represents 20 series
- Each series represents 20 values
```html
<vaadin-chart id="chart"></vaadin-chart>
import '@vaadin/vaadin-charts';
import { nextRender } from '@vaadin/testing-helpers';
const series = [...new Array(20)].map((_, i) => {
return {
name: `Series ${i}`,
data: [...new Array(20)].map(() => i)
};
});
await …
```
=> refactor: reduce chart redraws for updateConfiguration()

packages/vaadin-crud/src/vaadin-crud.js
Needed for https://github.com/vaadin/flow-components/pull/2063.
It enables overriding of the save auto-enable logic by overriding `__isSaveBtnDisabled` method.
=> feat: add method to control disabled state of save button

packages/field-base/src/input-constraints-mixin.js, packages/field-base/test/input-constraints-mixin.test.js, packages/number-field/src/vaadin-number-field.js, packages/number-field/test/number-field.test.js
Updated `InputConstraintsMixin` which is responsible for validation to also validate on `change` event.
Then the `change` event is manually re-dispatched on the host, with a reference to the original event.
Fixes #2517
-  Bugfix
=> fix: fire change event after validate

packages/custom-field/test/custom-field.test.js, packages/field-base/src/label-mixin.d.ts, packages/field-base/src/label-mixin.js, packages/field-base/src/slot-label-mixin.d.ts, packages/field-base/src/slot-label-mixin.js, packages/field-base/src/slot-target-mixin.d.ts, packages/field-base/src/slot-target-mixin.js, packages/field-base/test/label-mixin.test.js, packages/field-base/test/slot-label-mixin.test.js, packages/field-base/test/slot-target-mixin.test.js
This PR introduces `SlotLabelMixin` that forwards any content from the default slot to the label node which makes it possible to define a label for a component not only with the `label` property but also with the default slot.
The mixin is required for the new checkbox and radio-button accessible implementations.
Note, the PR also changes the rule of when to set the `has-label` attribute on the host element:
**Before:** 
```js
// The element is considered to have a label if its content is not an empty string.
const hasLabel = this._labelNode.textContent !== '';
this.toggleAttribute('has-label', hasLabel);
```
**Now:**
```js
const hasLabel = (
// 1. The element is considered to have a label if it has any element children.
this._labelNode.children.length > 0 || 
// 2. The element is …
```
=> feat: add SlotLabelMixin for checkbox and radio-button

dev/index.html, package.json, web-dev-server.config.js, web-dev-server.config.mjs
Open a listing of dev pages on `npm start`
=> chore: open dev page listing by default

packages/vaadin-date-picker/package.json, packages/vaadin-date-picker/src/vaadin-date-picker-light.js, packages/vaadin-date-picker/src/vaadin-date-picker-mixin.js, packages/vaadin-date-picker/src/vaadin-date-picker-overlay.js, packages/vaadin-date-picker/src/vaadin-date-picker-styles.js, packages/vaadin-date-picker/src/vaadin-date-picker.js, packages/vaadin-date-picker/test/basic.test.js, packages/vaadin-date-picker/test/dropdown.test.js, packages/vaadin-date-picker/theme/lumo/vaadin-date-picker-overlay-styles.js, packages/vaadin-date-picker/theme/material/vaadin-date-picker-overlay-styles.js, packages/vaadin-overlay/src/vaadin-overlay-position-mixin.js, packages/vaadin-overlay/test/position-target.test.js
Removes internal overlay positioning logic from `<vaadin-date-picker>` in favour of using the `vaadin-overlay-position-mixin`.
Related https://github.com/vaadin/web-components/pull/2497 and https://github.com/vaadin/web-components/pull/2510
=> refactor: use overlay-position-mixin with date-picker

packages/field-base/src/helper-text-mixin.js, packages/field-base/src/input-slot-mixin.js, packages/field-base/src/label-mixin.js, packages/field-base/src/text-area-slot-mixin.js, packages/field-base/src/validate-mixin.js, packages/field-base/test/helper-text-mixin.test.js, packages/field-base/test/input-slot-mixin.test.js, packages/field-base/test/label-mixin.test.js, packages/field-base/test/text-area-slot-mixin.test.js, packages/field-base/test/validate-mixin.test.js, packages/select/src/vaadin-select.js, packages/select/test/accessibility.test.js
This is a small change to make generated IDs use the same numbers as much as possible.
Added some tests using private APIs which is something I'm not happy about 😕 
We can separately consider using the same as Lion which generates one random ID per component instance.
- Refactor
=> refactor: use separate fields to store unique IDs

packages/vaadin-combo-box/src/vaadin-combo-box.js, packages/vaadin-combo-box/test/aria.test.js, packages/vaadin-date-picker/src/vaadin-date-picker.js, packages/vaadin-date-picker/test/wai-aria.test.js
Currently both `vaadin-combo-box` and `vaadin-date-picker` have `aria-describedby` set incorrectly on the host.
Updated to override `_ariaTarget` and added missing tests to cover the ARIA attributes that it refers to.
- Bugfix
=> fix: set ARIA attributes properly, add tests

packages/vaadin-notification/src/vaadin-notification.js, packages/vaadin-notification/test/statichelper.test.js
Fixed the recently introduced `NotificationElement.show` helper to handle a duration value of zero.
=> fix: static show helper should accept zero duration

package.json, packages/app-layout/src/vaadin-drawer-toggle.d.ts, packages/crud/src/vaadin-crud-edit-column.d.ts, packages/vaadin-dialog/src/vaadin-dialog.d.ts, packages/vaadin-dialog/src/vaadin-dialog.js, packages/vaadin-dialog/test/dialog.test.js, yarn.lock
Changed `ariaLabel` property type to align with the one present in `HTMLElement`.
Fixes #2585 
- Bugfix
=> fix: use correct type for ariaLabel property

dev/combo-box.html, packages/vaadin-combo-box/src/vaadin-combo-box-dropdown.js, packages/vaadin-combo-box/test/basic.test.js
We need to make sure the overlay width is only updated if a value is set to `positionTarget`. We also need to refresh the overlay's width when the value of `positionTarget` changes. These changes get rid of the error reported in the related issue and makes sure the overlay is properly updated when the necessary requisites are met.
```html
<vaadin-combo-box opened></vaadin-combo-box>
```
Fixes #2597
=> fix: update overlay width when positionTarget is updated

packages/vaadin-combo-box/src/vaadin-combo-box-dropdown.js, packages/vaadin-combo-box/src/vaadin-combo-box-item.js, packages/vaadin-combo-box/src/vaadin-combo-box-overlay.js, packages/vaadin-combo-box/src/vaadin-combo-box-scroller.js, packages/vaadin-time-picker/src/vaadin-time-picker-combo-box.js, packages/vaadin-time-picker/src/vaadin-time-picker-dropdown.js, packages/vaadin-time-picker/src/vaadin-time-picker-item.js, packages/vaadin-time-picker/src/vaadin-time-picker-overlay.js, packages/vaadin-time-picker/src/vaadin-time-picker-scroller.js, packages/vaadin-time-picker/test/aria.test.js, packages/vaadin-time-picker/test/keyboard-navigation.test.js
Update the implementation to make `vaadin-time-picker` use own tag names for internal elements:
- `vaddin-time-picker-dropdown`
- `vaddin-time-picker-overlay`
- `vaadin-time-picker-scroller`
- `vaadin-time-picker-item`
This also removes `ComboBoxDataProviderMixin` which we don't really need in time-picker.
- Refactor
=> refactor: override internal elements in time-picker

packages/vaadin-combo-box/src/vaadin-combo-box-light.js, packages/vaadin-combo-box/src/vaadin-combo-box-mixin.js, packages/vaadin-combo-box/test/combo-box-light.test.js, packages/vaadin-combo-box/test/selecting-items.test.js, packages/vaadin-time-picker/test/time-picker.test.js
Currently there is a regression in `vaadin-time-picker`: on clear button click the input loses focus.
Updated to use the same approach as with toggle button and prevent `mousedown`.
Also removed the `click` listeners which are no longer needed, and updated tests.
- Bugfix
=> refactor: prevent mousedown to keep focus on clear

packages/vaadin-combo-box/test/basic.test.js
In https://github.com/vaadin/web-components/pull/2611 a change was introduced to update the overlay once the `positionTarget` is loaded, but no test was added to make sure the overlay's content is of the expected width.
This PR adds the missing test.
=> chore: add test to check for overlay content's width when combo-box is pre-opened

packages/vaadin-combo-box/package.json, packages/vaadin-combo-box/src/vaadin-combo-box-light.d.ts, packages/vaadin-combo-box/src/vaadin-combo-box-light.js, packages/vaadin-combo-box/test/combo-box-light.test.js
We no longer want to support `iron-` and `paper-` elements as these are deprecated.
Updated the implementation and tests to use `vaadin-text-field` and custom input.
=> refactor!: drop paper-input and iron-input support

packages/vaadin-grid-pro/src/vaadin-grid-pro-inline-editing-mixin.js, packages/vaadin-grid/src/vaadin-grid-column-reordering-mixin.js, packages/vaadin-grid/src/vaadin-grid-column-resizing-mixin.js, packages/vaadin-grid/src/vaadin-grid-column.d.ts, packages/vaadin-grid/src/vaadin-grid-column.js, packages/vaadin-grid/src/vaadin-grid-data-provider-mixin.js, packages/vaadin-grid/src/vaadin-grid-drag-and-drop-mixin.js, packages/vaadin-grid/src/vaadin-grid-dynamic-columns-mixin.js, packages/vaadin-grid/src/vaadin-grid-keyboard-navigation-mixin.js, packages/vaadin-grid/src/vaadin-grid-row-details-mixin.js, packages/vaadin-grid/src/vaadin-grid-scroll-mixin.js, packages/vaadin-grid/src/vaadin-grid.d.ts, packages/vaadin-grid/src/vaadin-grid.js, packages/vaadin-grid/test/basic.test.js, packages/vaadin-grid/test/column-reordering.test.js
All the currently supported browsers have the native `Element.toggleAttribute()` API built-in, so there's no longer a need for the `grid._toggleAttribute()` helper.
=> refactor: remove grid._toggleAttribute

packages/custom-field/src/vaadin-custom-field.js, packages/email-field/test/dom/__snapshots__/email-field.test.snap.js, packages/integer-field/test/dom/__snapshots__/integer-field.test.snap.js, packages/number-field/src/vaadin-number-field.js, packages/number-field/test/dom/__snapshots__/number-field.test.snap.js, packages/password-field/test/dom/__snapshots__/password-field.test.snap.js, packages/select/src/vaadin-select.js, packages/select/test/dom/__snapshots__/select.test.snap.js, packages/text-area/src/vaadin-text-area.js, packages/text-area/test/dom/__snapshots__/text-area.test.snap.js, packages/text-field/src/vaadin-text-field.js, packages/vaadin-combo-box/src/vaadin-combo-box.js, packages/vaadin-date-picker/src/vaadin-date-picker.js, packages/vaadin-lumo-styles/mixins/required-field.js, packages/vaadin-material-styles/mixins/required-field.js, packages/vaadin-time-picker/src/vaadin-time-picker.js
Renames the `indicator` part to `required-indicator`. 
The `required-indicator` name was chosen to align the name with the existing `setRequiredIndicatorVisible` Flow method.
Fixes #2621
=> refactor!: rename indicator part to required-indicator

packages/charts/test/exporting.test.js, packages/charts/test/styling.test.js, packages/component-base/test/dir-mixin.test.js, packages/vaadin-combo-box/test/combo-box-light.test.js, packages/vaadin-combo-box/test/filtering.test.js, packages/vaadin-combo-box/test/lazy-loading.test.js, packages/vaadin-custom-field/test/helper.test.js, packages/vaadin-date-picker/test/form-input.test.js, packages/vaadin-grid-pro/test/grid-pro.test.js, packages/vaadin-grid/test/column-group.test.js, packages/vaadin-notification/test/statichelper.test.js, packages/vaadin-overlay/test/position-target.test.js
This PR is the result of a one-pass run of the `import/order` ESLint rule with the following configuration:
```json
"import/order": ["error", {
"groups": ["builtin", "external", "internal", "parent", "sibling", "index"],
"pathGroups": [
{ "pattern": "@vaadin/testing-helpers", "group": "external" },
{ "pattern": "@vaadin/testing-helpers/**", "group": "external" },
{ "pattern": "@polymer/polymer/polymer-element.js", "group": "internal", "position": "after" },
{ "pattern": "@polymer/**", "group": "internal", "position": "after" },
{ "pattern": "lit", "group": "internal", "position": "after" },
{ "pattern": "lit/**", "group": "internal", "position": "after" },
{ "pattern": "@vaadin/component-base/**", "group": "internal", "position": "after" },
{ "pattern": "@vaadin/field-base/**", "group": …
```
=> refactor: sort import statements

packages/custom-field/src/vaadin-custom-field.js, packages/custom-field/test/custom-field.test.js, packages/vaadin-custom-field/src/vaadin-custom-field-mixin.js, packages/vaadin-custom-field/test/basic.test.js, packages/vaadin-date-time-picker/src/vaadin-date-time-picker-custom-field.js, web-test-runner.config.js
`<vaadin-custom-field>`'s value is composed from the inputs it contains in its light DOM. Now that vaadin form fields are switching to use slotted inputs, we need to change custom-field's input query to filter them out.
```html
<vaadin-custom-field>
<vaadin-text-field> <- should be included
<input type="text" slot="input"> <- should be ignored
</vaadin-text-field>
</vaadin-custom-field>
```
The [workaround for the issue in date-time-picker](https://github.com/vaadin/web-components/blob/099754fdfc900b49ea1e3699cf0cc2037cb3dae5/packages/vaadin-date-time-picker/src/vaadin-date-time-picker-custom-field.js#L49-L56) can be removed
=> fix: ignore slotted inputs in custom-field

packages/vaadin-lumo-styles/presets/compact.js
Shady CSS is no longer needed by any supported browsers.
=> refactor: remove unnecessary duplicate selector from compact preset

package.json, web-test-runner.config.js, wtr-utils.js
We've been having issues with code coverage with tests when running tests for a single package. By changing the web test runner configuration so that coverage is only used when running tests from all packages we can avoid CI failing because of not meeting the testing threshold. We can also increase the coverage threshold again.
=> chore: change test coverage to only run when running all tests

packages/vaadin-grid/theme/lumo/vaadin-grid-styles.js
Reduce the opacity of the drag overlay when `dragover="on-top"`.
Extend the drag overlay to cover the frozen column divider (right border of the last frozen column), so that the overlay is perceived as one single element on top of all columns (no gaps).
Remove unnecessary styles that target IE/Edge (no longer supported).
This PR is required before merging #2626 (see https://github.com/vaadin/web-components/pull/2626#issuecomment-927725400).
=> refactor: update grid dragover=on-top visual style (Lumo)

packages/horizontal-layout/src/vaadin-horizontal-layout.js, packages/horizontal-layout/test/horizontal-layout.test.js, packages/horizontal-layout/theme/lumo/vaadin-horizontal-layout-styles.js, packages/horizontal-layout/theme/material/vaadin-horizontal-layout-styles.js, packages/vertical-layout/src/vaadin-vertical-layout.js, packages/vertical-layout/test/vertical-layout.test.js, packages/vertical-layout/theme/lumo/vaadin-vertical-layout-styles.js, packages/vertical-layout/theme/material/vaadin-vertical-layout-styles.js
Use standard `gap` property instead of margins on the slotted child elements to create spacing between layout items.
Closes #2174 
Fixes #804 
Fixes #854 
Fixes https://github.com/vaadin/flow-components/issues/1159
=> refactor: use CSS gap property for ordered layout spacing

packages/component-base/package.json, packages/component-base/src/element-mixin.d.ts, packages/component-base/src/element-mixin.js, packages/component-base/test/element-mixin.test.js
Added support for reactive controllers to `ElementMixin`. 
Currently only `hostConnected` and `hostDisconnected` are implemented.
First step of #2632
=> feat: add controllers support to ElementMixin

packages/vaadin-grid/src/vaadin-grid.d.ts, packages/vaadin-grid/src/vaadin-grid.js, packages/vaadin-grid/test/resizing.test.js, wtr-utils.js
`grid.notifyResize` has been a no-op since Vaadin 21. Add a deprecation warning message and documentation to the function.
Related: https://github.com/vaadin/flow-components/pull/2167
=> chore: deprecate grid.notifyResize()

.github/workflows/coverage.yml, README.md, wtr-utils.js
The main purpose of this PR is to introduce a new CI workflow to calculate code coverage. The workflow will only run after pushes to master, and is otherwise a duplication of the Chrome workflow.
This PR also contains other changes:
- add a new flag `-all` to the test config in order to force running tests for all packages in CI. Currently the test config will exit the process if there are no changed packages, and the process runs in CI. If we want to keep this behaviour for pull requests, then we need an alternative to force running all packages.
- adds a new flag `--coverage` to the test config in order to collect code coverage from test runs. The previously introduced solution to only collect coverage when all packages are tested is too opaque and difficult to discover. Let's rather …
=> test: introduce coverage CI workflow

packages/custom-field/package.json, packages/radio-group/package.json
1. Added missing dev dependencies to `custom-field` (used in visual tests) from `vaadin-custom-field`
2. Removed no longer used `@vaadin/vaadin-control-state-mixin` from `radio-group`
=> chore: update and cleanup dependencies

packages/vaadin-icon/README.md, packages/vaadin-icon/package.json, packages/vaadin-icon/src/vaadin-icon-svg.d.ts, packages/vaadin-icon/src/vaadin-icon-svg.js, packages/vaadin-icon/src/vaadin-icon.d.ts, packages/vaadin-icon/src/vaadin-icon.js, packages/vaadin-icon/src/vaadin-iconset.d.ts, packages/vaadin-icon/src/vaadin-iconset.js, packages/vaadin-icon/theme/lumo/vaadin-icon.js, packages/vaadin-icon/theme/material/vaadin-icon.js, packages/vaadin-icon/vaadin-icon.d.ts, packages/vaadin-icon/vaadin-icon.js, packages/vaadin-icon/vaadin-iconset.d.ts, packages/vaadin-icon/vaadin-iconset.js
Re-create `@vaadin/vaadin-icon` for backwards compatibility.
Part of #1992
Fixes #2667
=> refactor: re-create vaadin-icon for backwards compatibility

packages/field-base/src/input-controller.js, packages/field-base/test/input-controller.test.js
The PR fixes the regression that occurred after the a11y refactorings:
> The `value` property is not forwarded to the input element, only the `value` attribute is forwarded.
Fixes #2692.
=> fix: forward value property to input element

packages/field-base/src/label-mixin.js, packages/field-base/test/label-mixin.test.js
If a field has a slotted label with empty child elements, the field should still get `has-label` attribute added
=> fix: make label with empty children add has-label attribute

packages/vaadin-lumo-styles/typography.js, packages/vaadin-material-styles/typography.js
Not needed anymore, native shadow DOM is supported in all the browsers we support.
=> chore: remove duplicate CSS in typography modules

packages/input-container/src/vaadin-input-container.js, packages/vaadin-lumo-styles/mixins/input-field-shared.js, packages/vaadin-lumo-styles/typography.js, packages/vaadin-material-styles/mixins/input-field-shared.js, packages/vaadin-material-styles/typography.js
Do not duplicate the theme styles (Lumo and Material) in `typography.js`, but keep them only in `input-field-shared.js`. This makes it easier for custom themes to override the styles.
This is basically another way of solving the same issue as with #2184
=> refactor: avoid input placeholder styles duplication

packages/vaadin-lumo-styles/mixins/input-field-shared.js, packages/vaadin-material-styles/mixins/input-field-shared.js
The font-smooth property is inherited according to MDN, and at least in my testing, it is enough that the host specifies it, it affects the rendering of the slotted input as well.
=> chore: remove unnecessary CSS

packages/radio-group/src/vaadin-radio-group.js, packages/radio-group/test/radio-group.test.js
The PR fixes the regression that occurred after the radio-group's refactoring:
> The `disabled` attribute initially set for a radio-button gets removed at radio-group initialization.
Fixes #2705.
=> fix: don't enable initially disabled radio buttons

packages/vaadin-combo-box/src/vaadin-combo-box-mixin.js, packages/vaadin-combo-box/test/basic.test.js
Connected to https://github.com/vaadin/flow-components/issues/2135
=> fix: Prevent firing custom value set event when readonly

packages/vaadin-upload/src/interfaces.d.ts, packages/vaadin-upload/src/vaadin-upload.d.ts, packages/vaadin-upload/src/vaadin-upload.js
fix: Remove Cancel key from i18n file on vaadin-upload component
Remove unused Cancel key on vaadin-upload.js and vaadin-upload.d.ts
Fixes #2337
=> fix: remove unused cancel key on vaadin-upload

.husky/pre-commit, package.json, yarn.lock
=> chore: update husky dev dependency to v7

packages/crud/src/vaadin-crud-grid.js, packages/crud/test/crud-grid.test.js
Parse camel case field label to sentence case and use for column header e.g. 'passwordField' should be converted to 'Password field'.
Fixes #533
=> fix: generate sentence case header for camel case columns

packages/vaadin-combo-box/src/vaadin-combo-box-mixin.js, packages/vaadin-combo-box/test/object-values.test.js
When ComboBox is used inside polymer template and referenced inside a Java view, some property updates are not happening in order like other use cases, this caused the web component break on a very specific usage. 
After some investigation we found out that in the list of values that `selectItemChanged` observer should be run, `itemValuePath` is missing, so when `itemValuePath` is changed, `value` is not changed respectively (which happens in `selectItemChanged`).
The proposed solution is to add `itemValuePath` to  list of parameters for computed observer `selectItemChanged`.
Fixes https://github.com/vaadin/flow-components/issues/1880
=> fix: add itemValuePath to selectItemChanged observer.

packages/vaadin-combo-box/src/vaadin-combo-box-mixin.js, packages/vaadin-combo-box/test/basic.test.js
cherry-pick of #2721
(cherry picked from commit 62a9e8af33e6f5c22e3030aaa967f474103e1002)
=> fix: do not fire custom-value-set event when readonly (CP: 21)

packages/custom-field/test/custom-field.test.js, packages/date-picker/test/wai-aria.test.js, packages/email-field/test/dom/__snapshots__/email-field.test.snap.js, packages/email-field/test/dom/email-field.test.js, packages/field-base/src/field-mixin.js, packages/field-base/test/field-mixin.test.js, packages/integer-field/test/dom/__snapshots__/integer-field.test.snap.js, packages/integer-field/test/dom/integer-field.test.js, packages/message-input/test/dom/__snapshots__/message-input.test.snap.js, packages/number-field/test/dom/__snapshots__/number-field.test.snap.js, packages/password-field/test/dom/__snapshots__/password-field.test.snap.js, packages/password-field/test/dom/password-field.test.js, packages/radio-group/test/radio-group.test.js, packages/select/test/dom/select.test.js, packages/text-area/test/dom/__snapshots__/text-area.test.snap.js, packages/text-area/test/dom/text-area.test.js, packages/text-field/test/dom/__snapshots__/text-field.test.snap.js, packages/text-field/test/dom/text-field.test.js, packages/vaadin-combo-box/test/aria.test.js, packages/vaadin-time-picker/test/aria.test.js
Fixes #2382
This is an attempt to make the new behavior more or less aligned with that we used to have previously, i.e.
```html
<slot name="helper">[[helperText]]</slot>
```
Notable changes:
1. Setting `helperText` property (or attribute) only updates text content for the default helper, not for custom one.
2. Text content from the custom helper is set to `helperText` property when it is inserted, but not updated later.
3. When the custom helper is removed, the default one is restored. I had to use `FlattenedNodesObserver` for it.
- Bugfix
=> fix: create default helper element lazily

packages/vaadin-lumo-styles/mixins/input-field-shared.js
Connected to #119 
Use a "shake" animation instead of text color change to indicate that the character/input was rejected/prevented.
Note, that the placeholder styles were already updated in another PR, and the exact issue listed in #119 does not happen any longer (the placeholder text color is not affected, only if the user has already entered some characters then the color of those would change).
=> refactor: do not use color when preventing invalid input (Lumo)

packages/vaadin-combo-box/src/vaadin-combo-box-mixin.js, packages/vaadin-combo-box/test/object-values.test.js
cherry-pick of  https://github.com/vaadin/web-components/pull/2718
cherry-picked from commit `cc1b2ed`
=> fix: add itemValuePath to selectItemChanged observer (#2718)

dev/checkbox.html, dev/radio-group.html, packages/checkbox/src/vaadin-checkbox.js, packages/checkbox/test/checkbox.test.js, packages/checkbox/test/visual/lumo/checkbox.test.js, packages/checkbox/test/visual/material/checkbox.test.js, packages/field-base/src/slot-target-mixin.d.ts, packages/field-base/src/slot-target-mixin.js, packages/field-base/test/slot-target-mixin.test.js, packages/radio-group/src/vaadin-radio-button.js, packages/radio-group/test/radio-button.test.js, packages/radio-group/test/visual/lumo/radio-button.test.js, packages/radio-group/test/visual/material/radio-button.test.js, wtr-utils.js
Fixes #2609 
This PR changes the behavior of `slot-target-mixin` so that the nodes in the source slot are no longer moved but copied inside the slot target.
Also, a warning is now shown if the default slot is used for defining a label for checkbox / radio-button
=> refactor: make slot-target-mixin clone instead of moving

packages/vaadin-tabs/src/vaadin-tabs.js, packages/vaadin-tabs/test/dom/__snapshots__/tabs.test.snap.js, packages/vaadin-tabs/test/dom/tabs.test.js
Set `aria-hidden` to back / forward button in tabs as it shouldn't be read by screen reader.
Fixes #443
=> fix: screen reader should not read back/fwd button in tabs

packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js, packages/grid/test/keyboard-navigation.test.js
Fixes https://github.com/vaadin/web-components/issues/2610
Space "keyup" event should not be prevented when interacting with controls inside the grid cells.
=> fix: don't prevent space keyup while interacting in grid

dev/combo-box.html, packages/vaadin-combo-box/package.json, packages/vaadin-combo-box/src/vaadin-combo-box-dropdown.js, packages/vaadin-combo-box/src/vaadin-combo-box-item.js, packages/vaadin-combo-box/src/vaadin-combo-box-mixin.js, packages/vaadin-combo-box/src/vaadin-combo-box-scroller.js, packages/vaadin-combo-box/test/aria.test.js, packages/vaadin-combo-box/test/combo-box-light.test.js, packages/vaadin-combo-box/test/dynamic-size.test.js, packages/vaadin-combo-box/test/item-renderer.test.js, packages/vaadin-combo-box/test/item-template.test.js, packages/vaadin-combo-box/test/keyboard.test.js, packages/vaadin-combo-box/test/lazy-loading.test.js, packages/vaadin-combo-box/test/lit.test.js, packages/vaadin-combo-box/test/object-values.test.js, packages/vaadin-time-picker/src/vaadin-time-picker-combo-box.js, packages/vaadin-time-picker/test/aria.test.js
Fixes #2483
Fixes #1338
Fixes #1341
Fixes #1350 (as we remove the timeout)
- Feature
=> feat: improve accessibility based on ARIA 1.2

packages/date-picker/test/basic.test.js, packages/vaadin-combo-box/test/basic.test.js, packages/vaadin-time-picker/test/time-picker.test.js
As a result of adding `InputControlMixin` in #2632 we now have `autoselect` available in the following components:
- `vaadin-combo-box`
- `vaadin-date-picker`
- `vaadin-time-picker`
This PR adds unit tests to cover this feature. It does not seem to need any other changes.
Closes #1160
Closes #1801
- Tests
=> test: add unit tests for autoselect property

packages/field-base/src/field-mixin.js, packages/radio-group/test/radio-group.test.js
This PR fixes the regression that has occurred since the last a11y refactoring of the radio-group:
> Removing the custom helper node doesn't lead to removing the `has-helper` attribute on the radio-group.
Fixes #2755
=> fix: remove has-helper attribute when helper node is removed

packages/checkbox/src/vaadin-checkbox.js, packages/checkbox/theme/lumo/vaadin-checkbox-styles.js, packages/checkbox/theme/material/vaadin-checkbox-styles.js
The PR enhances the checkbox's clickable area so that it becomes clickable over the whole area. This is done by:
- Setting `padding` on the slotted `<label>` element rather than `margin` on the `label` part.
- Stretching the input element over the `checkbox` part including its margins.
Fixes #2693
=> fix!: enhance clickable area for checkbox

packages/radio-group/src/vaadin-radio-button.js, packages/radio-group/theme/lumo/vaadin-radio-button-styles.js, packages/radio-group/theme/material/vaadin-radio-button-styles.js
The PR enhances the radio-button's clickable area so that it becomes clickable over the whole area.
- Removed the `label` part ([proposal](https://github.com/vaadin/web-components/pull/2739#issuecomment-935794813)).
- Set `padding` on the slotted `<label>` element.
- Stretched the input element over the `checkbox` part including its margins.
Fixes #2690
=> fix!: remove label part and enhance clickable area

packages/confirm-dialog/test/typings/confirm-dialog.types.ts, packages/split-layout/test/typings/split-layout.types.ts
Updated remaining files in `test/typings` to import from `../../vaadin-*` and not `../../src/vaadin-*` 
Closes #181
- Tests
=> test: import root entrypoints in typings tests

packages/accordion/test/accordion.test.js, packages/component-base/src/focus-mixin.d.ts, packages/component-base/src/focus-mixin.js, packages/password-field/src/vaadin-password-field.js, packages/password-field/test/password-field.test.js
Added a protected getter to access `keyboardActive` flag handled by `FocusMixin` in password-field.
Fixes #2962
- Bugfix
=> fix: do not set focus-ring on mousedown focus

packages/avatar-group/test/avatar-group.test.js, packages/avatar/src/vaadin-avatar.d.ts, packages/avatar/src/vaadin-avatar.js
The only reason for copy-paste in the original implementation was the lack of `FocusMixin` back then.
Note, we can change the tests separately to use `sendKeys` - for now current tests might be OK.
- Refactor
=> refactor: use FocusMixin instead of custom logic

packages/menu-bar/theme/lumo/vaadin-menu-bar-button-styles.js, packages/menu-bar/theme/material/vaadin-menu-bar-button-styles.js
As reported by @jouni at https://github.com/vaadin/web-components/pull/2955#issuecomment-957436657, moving styles caused a regression in Menu Bar styles. 
This is what happens on hover when `item.component` is used e.g. to provide custom icon:
Caused by the following style (same also happens in Material theme):
https://github.com/vaadin/web-components/blob/c2d88fd6d8402311306647915f162ac60610f7f3/packages/item/theme/lumo/vaadin-item-styles.js#L67-L69
- Bugfix
=> fix: reset background for menu-bar item in button

packages/board/src/vaadin-board.d.ts, packages/charts/src/vaadin-chart-series.d.ts, packages/charts/src/vaadin-chart.d.ts, packages/component-base/src/focus-mixin.js, packages/cookie-consent/src/vaadin-cookie-consent.d.ts, packages/crud/src/vaadin-crud-form.d.ts, packages/grid-pro/src/vaadin-grid-pro-edit-column.d.ts, packages/grid-pro/src/vaadin-grid-pro.d.ts, packages/list-box/src/vaadin-list-box.d.ts, packages/tabs/src/vaadin-tab.d.ts, packages/tabs/src/vaadin-tabs.d.ts, packages/upload/src/vaadin-upload.d.ts, packages/vaadin-overlay/src/vaadin-overlay.d.ts
Same as #2881 but rebased so the original PR can't be reopened.
- Refactor
=> refactor: remove private API from TS definitions

packages/text-area/src/vaadin-text-area.js
Fixes https://github.com/vaadin/flow-components/issues/2296
=> fix: workaround an issue with disabled textarea freezing the browser

packages/grid-pro/src/vaadin-grid-pro-edit-select.js, packages/grid-pro/test/edit-column-type.test.js, packages/grid-pro/test/edit-column.test.js, packages/item/src/vaadin-item-mixin.d.ts, packages/item/src/vaadin-item-mixin.js, packages/item/test/item-mixin.test.js, packages/select/src/vaadin-select.js, packages/tabs/src/vaadin-tab.js, packages/vaadin-list-mixin/vaadin-list-mixin.js
- Changed to use `ActiveMixin` and `FocusMixin` so that we handle these consistently for all components.
- Added some necessary tweaks to preserve setting `focus-ring` when focusing an item inside a list-box
- Previously, the `focus-ring` was always set **unless** there was a `mousedown` event before `focusin`,
- Now, the `focus-ring` is set **only** if there was a `keydown` (same as in button, input fields etc),
- But we still need to have `focus-ring` set by `vaadin-select`, `vaadin-list-box`, `vaadin-menu-bar`.
- Refactor
=> refactor: use new mixins, simplify keyboard handling logic

packages/vaadin-text-field/src/vaadin-text-area.js
=> fix: workaround disabled textarea freezing Firefox (#2981)

packages/select/src/vaadin-select.js, packages/select/test/renderer.test.js
This PR prevents throwing an exception in the select component when requesting the content update before the component is attached to the DOM.
Extracted from #2990.
=> fix: don't throw when requesting content update before attaching to DOM

packages/combo-box/theme/lumo/vaadin-combo-box-item-styles.js, packages/combo-box/theme/material/vaadin-combo-box-item-styles.js
Folow-up from #2955 - some CSS rules are now duplicates and can be removed.
I had to keep `focused` styles for Lumo because the item uses `focus-ring`.
- Refactor
=> refactor: cleanup duplicate combo-box item styles

packages/grid/test/keyboard-navigation.test.js, yarn.lock
Updated Playwright from `1.15.0` to `1.16.3` - let's see if some tests fail again and if we should fix something.
=> chore: update Playwright to 1.16.3, fix grid keyboard test

packages/date-picker/package.json, packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/src/vaadin-date-picker-overlay-content.js, yarn.lock
One more step towards having less Polymer legacy dependencies.
- Refactor
=> refactor: remove IronA11yKeysBehavior dependency

packages/avatar-group/src/vaadin-avatar-group-overlay.js, packages/combo-box/src/vaadin-combo-box-overlay.js, packages/combo-box/src/vaadin-combo-box.js, packages/context-menu/src/vaadin-context-menu-overlay.js, packages/date-picker/src/vaadin-date-picker.js, packages/date-time-picker/src/vaadin-date-time-picker.js, packages/dialog/src/vaadin-dialog-resizable-mixin.js, packages/dialog/src/vaadin-dialog.js, packages/email-field/src/vaadin-email-field.js, packages/grid/src/vaadin-grid-styles.js, packages/menu-bar/src/vaadin-menu-bar-button.js, packages/message-input/src/vaadin-message-input-button.js, packages/message-input/src/vaadin-message-input-text-area.js, packages/message-list/src/vaadin-message-avatar.js, packages/number-field/src/vaadin-number-field.js, packages/rich-text-editor/src/vaadin-rich-text-editor-content-styles.js, packages/rich-text-editor/src/vaadin-rich-text-editor-icons.js, packages/rich-text-editor/src/vaadin-rich-text-editor-toolbar-styles.js, packages/rich-text-editor/src/vaadin-rich-text-editor.js, packages/select/src/vaadin-select-overlay.js, packages/select/src/vaadin-select-value-button.js, packages/select/src/vaadin-select.js, packages/text-area/src/vaadin-text-area.js, packages/text-field/src/vaadin-text-field.js, packages/time-picker/src/vaadin-time-picker-overlay.js, packages/time-picker/src/vaadin-time-picker.js
Since #2594 `register-styles.js` is just a re-export so we can use the `themable-mixin.js` import instead.
- Refactor
=> refactor: simplify themable-mixin imports in src

packages/charts/test/exporting.test.js, packages/charts/test/styling.test.js, packages/combo-box/test/lazy-loading.test.js, packages/combo-box/test/not-animated-styles.js, packages/combo-box/test/visual/common.js, packages/confirm-dialog/test/not-animated-styles.js, packages/context-menu/test/not-animated-styles.js, packages/date-picker/test/not-animated-styles.js, packages/date-picker/test/visual/common.js, packages/dialog/test/draggable-resizable.test.js, packages/grid-pro/test/not-animated-styles.js, packages/grid/test/data-provider.test.js, packages/grid/test/dynamic-item-size.test.js, packages/grid/test/physical-count.test.js, packages/grid/test/row-height.test.js, packages/login/test/login-form.test.js, packages/login/test/visual/common.js, packages/menu-bar/test/menu-bar.test.js, packages/menu-bar/test/not-animated-styles.js, packages/notification/test/animation.test.js, packages/notification/test/multiple.test.js, packages/number-field/test/visual/common.js, packages/polymer-legacy-adapter/test/style-modules-lazy-import.test.js, packages/select/test/not-animated-styles.js, packages/text-field/test/visual/common.js, packages/time-picker/test/visual/common.js, packages/vaadin-overlay/test/animations.test.js, packages/vaadin-overlay/test/styling.test.js
Since #2594 `register-styles.js` is just a re-export so we can use the `themable-mixin.js` import instead.
Same as #3009 but for test folders, therefore the commit is `test:` and not `refactor:`
- Refactor
=> test: simplify themable-mixin imports in tests

packages/select/src/vaadin-select-item.js, packages/select/src/vaadin-select-list-box.js, packages/select/src/vaadin-select-value-button.js, packages/select/src/vaadin-select.d.ts, packages/select/src/vaadin-select.js, packages/select/test/items.test.js, packages/select/test/renderer.test.js, packages/select/test/select.test.js, packages/select/test/typings/select.types.ts, packages/select/theme/lumo/vaadin-select-styles.js, packages/select/theme/material/vaadin-select-styles.js
The PR adds support for the `items` property in the select component by adding the default renderer that renders items when they are provided by the property and clears the select's content otherwise.
```html
<vaadin-select></vaadin-select>
<script>
import '@vaadin/select';
const select = document.querySelector('vaadin-select');
select.items = [
{ label: 'Jose', value: 'jose' },
{ component: 'hr' },
{ label: 'Pedro', value: 'pedro' },
{ label: 'Manolo', value: 'manolo', disabled: true }
];
</script>
```
Fixes #501
=> feat: add support for items property in select

packages/checkbox-group/src/vaadin-checkbox-group.d.ts, packages/checkbox-group/src/vaadin-checkbox-group.js
This enables adding reactive controllers to `vaadin-checkbox-group`, like `FieldHighlighter` - see #3031
- Refactor
=> refactor: use ElementMixin instead of DirMixin

packages/grid/src/vaadin-grid.js, packages/grid/test/class-name-generator.test.js
Fixes https://github.com/vaadin/web-components/issues/2988
=> fix: regenerate cell class names after column tree update

packages/vaadin-grid/src/vaadin-grid.js, packages/vaadin-grid/test/class-name-generator.test.js
Backport https://github.com/vaadin/web-components/pull/3033 for V21
=> fix: regenerate cell class names after column tree update (#3033)

packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/test/keyboard.test.js
In the event of pressing the <kbd>Esc</kbd> key, if the event is "consumed" by the combo-box, it must stop its propagation. If no action is performed by the combo-box, then the event must be propagated so other components can act accordingly.
Some conditions were missing to cover all cases.
Related: #984
=> fix: stop Escape keydown propagation if the event was handled

packages/vaadin-overlay/src/vaadin-overlay.d.ts, packages/vaadin-overlay/src/vaadin-overlay.js, packages/vaadin-overlay/test/renderer.test.js
Some cleanup for `vaadin-overlay` that I'd like to get done for V23 before trying to convert it to Lit.
- Breaking change (internal API)
=> refactor: drop support for setting instanceProps

packages/component-base/src/iron-list-core.js, packages/component-base/src/virtualizer-iron-list-adapter.js
Looks like we forgot to change imports when moving virtualizer code to `@vaadin/component-base`.
=> chore: use relative imports for virtualizer

packages/app-layout/src/detect-ios-navbar.js, packages/component-base/src/browser-utils.js, packages/component-base/src/virtualizer-iron-list-adapter.js, packages/context-menu/src/vaadin-contextmenu-event.js, packages/custom-field/src/vaadin-custom-field.js, packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/src/vaadin-infinite-scroller.js, packages/grid/src/vaadin-grid.js, packages/notification/src/vaadin-notification.js, packages/rich-text-editor/src/vaadin-rich-text-editor.js, packages/vaadin-overlay/src/vaadin-overlay.js
When working on #1139, I realised that detecting `inputmode` value will require more iOS and Android checks.
So instead of copying the relevant lines again, I decided to create a new helper file for those.
=> feat: add common browser detection utils

dev/upload.html, packages/upload/src/vaadin-upload-file.js, packages/upload/src/vaadin-upload.js, packages/upload/test/a11y.test.js, packages/upload/test/dom/__snapshots__/vaadin-upload-file.test.snap.js, packages/upload/test/dom/__snapshots__/vaadin-upload.test.snap.js, packages/upload/test/dom/vaadin-upload-file.test.js, packages/upload/test/dom/vaadin-upload.test.js, packages/upload/theme/lumo/vaadin-upload-styles.js, packages/upload/theme/material/vaadin-upload-styles.js
Fixes #2863 
The issue was caused by the `<li>` element having a `tabindex` applied. This PR fixes it by moving the `tabindex` to the `<vaadin-upload-file>` host.
=> fix: set tabindex on the vaadin-upload-file element

packages/polymer-legacy-adapter/src/template-renderer-templatizer.js, packages/polymer-legacy-adapter/test/vaadin-template-renderer.test.js
Fixes https://github.com/vaadin/flow-components/issues/2355
The change includes `model` property (a reference to the template instance), in all events bound declaratively in a Polymer template. The property is being [accessed by the TemplateRenderer via RendererUtil](https://github.com/vaadin/flow-components/blob/e68fd61a0866957a4cc6ea6f09ae2783a3864e87/vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/RendererUtil.java#L126) in flow-components.
=> fix: include model reference in declaratively bound events

packages/vaadin-template-renderer/src/vaadin-template-renderer-templatizer.js, packages/vaadin-template-renderer/test/vaadin-template-renderer.test.js
Backport https://github.com/vaadin/web-components/pull/3078 for V21
=> fix: include model reference in declaratively bound events (#3078)

packages/component-base/src/virtualizer-iron-list-adapter.js, packages/component-base/test/virtualizer.test.js
Fixes a regression from https://github.com/vaadin/web-components/pull/2910
Internal discussion: https://vaadin.slack.com/archives/C3TGRP4HY/p1637235071283900
Description:
Since the virtualizer now updates the item elements just once / index, we need to make sure an unhidden element gets re-updated with an index even if it was updated with the same index before getting hidden.
=> fix: ensure virtualizer re-renders unhidden items

packages/vaadin-virtual-list/src/virtualizer-iron-list-adapter.js, packages/vaadin-virtual-list/test/virtualizer.test.js
Backport https://github.com/vaadin/web-components/pull/3081 for V21
=> fix: ensure virtualizer re-renders unhidden items (#3081)

packages/field-highlighter/test/visual/common.js
Currently the field highlighter tests are very flaky: they expect user tags to be shown, but they are visible for 2 seconds.
This change adds `mouseenter` event which was missed during the visual tests conversion to show them permanently.
- Tests
=> test: add mouseenter event to reduce flakiness

packages/combo-box/src/vaadin-combo-box-light.d.ts, packages/combo-box/src/vaadin-combo-box.d.ts, packages/combo-box/test/typings/combo-box.types.ts, packages/custom-field/src/vaadin-custom-field.d.ts, packages/custom-field/test/typings/custom-field.types.ts, packages/date-picker/src/vaadin-date-picker-light.d.ts, packages/date-picker/src/vaadin-date-picker.d.ts, packages/date-picker/test/typings/date-picker.types.ts, packages/date-time-picker/src/vaadin-date-time-picker.d.ts, packages/date-time-picker/test/typings/date-time-picker.types.ts, packages/email-field/src/vaadin-email-field.d.ts, packages/email-field/test/typings/email-field.types.ts, packages/integer-field/src/vaadin-integer-field.d.ts, packages/integer-field/test/typings/integer-field.types.ts, packages/number-field/src/vaadin-number-field.d.ts, packages/number-field/test/typings/number-field.types.ts, packages/password-field/src/vaadin-password-field.d.ts, packages/password-field/test/typings/password-field.types.ts, packages/rich-text-editor/src/vaadin-rich-text-editor.d.ts, packages/rich-text-editor/test/typings/rich-text-editor.types.ts, packages/select/src/vaadin-select.d.ts, packages/select/test/typings/select.types.ts, packages/text-area/src/vaadin-text-area.d.ts, packages/text-area/test/typings/text-area.types.ts, packages/text-field/src/vaadin-text-field.d.ts, packages/text-field/test/typings/text-field.types.ts, packages/time-picker/src/vaadin-time-picker.d.ts, packages/time-picker/test/typings/time-picker.types.ts
The main idea behind this improvement is providing a type for `target` property of the `change` event object.
This is especially important because typically inside a change event listener users check `event.target.value`.
We might consider updating all the other custom events to have type for `target` separately later.
Fixes #3040 
- Feature
=> feat: add type definitions for change event

packages/combo-box/src/vaadin-combo-box-light.d.ts, packages/combo-box/src/vaadin-combo-box.d.ts, packages/combo-box/test/typings/combo-box.types.ts
Unlike other field components, `vaadin-combo-box` does not use mixin functions (which apply these classes internally).
This is due to using generics (mixins can't accept generic type parameters). So we have to list all the mixin classes.
- Bugfix
=> fix: add missing combo-box mixin classes

packages/upload/src/vaadin-upload.js, packages/upload/test/adding-files.test.js
It turns out that Firefox on Playwright, and Chrome (in manual mode) opened native file upload on synthetic click.
Updated the tests to add spy that calls `event.preventDefault()` in `beforeEach` to prevent this behavior.
- Tests
=> test: prevent opening add file dialog in tests

packages/field-base/src/utils.d.ts, packages/field-base/src/utils.js, packages/field-base/test/utils.test.js, packages/form-layout/package.json, packages/form-layout/src/vaadin-form-item.d.ts, packages/form-layout/src/vaadin-form-item.js, packages/form-layout/test/form-item.test.js
The PR makes screen readers announce the form-item label when tabbing to the first field inside the item. This is achieved by linking the label with the field via the `aria-labelledby` attribute on:
- the ARIA target element when the field specifies the `ariaTarget` property (that typically refers to a slotted input)
- the field element itself otherwise
Fixes #1145
=> fix: link form-item label to field via aria-labelledby

packages/app-layout/src/vaadin-app-layout.d.ts, packages/app-layout/src/vaadin-app-layout.js
No `part="content"` in the shadow DOM.
=> docs: remove incorrectly documented stylable part

packages/app-layout/src/vaadin-app-layout.js
No longer needed with the iOS support we promise.
=> refactor: remove no longer needed CSS property

packages/app-layout/src/safe-area-inset.js
`env()` is supported since iOS 11.3: https://caniuse.com/css-env-function
=> refactor: remove use of `constant()` as no longer required

packages/vaadin-themable-mixin/test/lit-setup.js, packages/vaadin-themable-mixin/vaadin-themable-mixin.js
The `styles` argument in `static finalizeStyles(styles) {` may be undefined in the case a LitElement based component doesn't implement `static get styles()`.
The undefined `styles` must be excluded from the array returned by `finalizeStyles`.
=> fix: skip undefined LitElement styles

packages/vaadin-combo-box/src/vaadin-combo-box-dropdown.js, packages/vaadin-combo-box/test/dialog.test.js, packages/vaadin-combo-box/test/dropdown.test.js
Fixes combo box closing lower-layer overlays, when closing the combo box dropdown. The original issue was about the time picker, but the root cause was the outside click handler logic in the combo box dropdown. I moved the outside click handler logic into the overlay itself, inspired by the recent refactoring here https://github.com/vaadin/web-components/pull/2497. That allows to reuse the regular overlay closing logic, which makes sure that only the uppermost overlay is closed.
The issue is already fixed in v22 and v23 due to https://github.com/vaadin/web-components/pull/2497, this fix is for v21. Will check v14 after merging the fix.
Fixes #2978
=> fix: prevent combo box closing other overlays (v21)

packages/polymer-legacy-adapter/test/style-modules-lit.test.js
Add one more test permutation where the `vaadin-themable-mixin` test suites get run with:
- `LitElement` based components
AND
- `<dom-module theme-for="...">` -styling (via the polymer-legacy-adapter).
=> test: add LitElement / <dom-module> -styling test permutation

packages/component-base/src/slot-mixin.js, packages/component-base/test/slot-mixin.test.js
This is a pre-requisite for creating `vaadin-confirm-dialog-overlay-content` that is planned to use `SlotMixin`.
Based on https://github.com/ing-bank/lion/pull/1496
=> feat: add default slot support to SlotMixin

package.json, yarn.lock
The PR bumps Playwright to 1.17.0-next-alpha-nov-5-2021 to get the most recent fix of the issue (https://github.com/microsoft/playwright/issues/9811) where Webkit falls on Mac OS Monterey with the following error:
> browser.newContext: Target closed
=> chore: bump Playwright to 1.17.0-next-alpha-nov-5-2021

packages/field-highlighter/src/fields/vaadin-date-picker-observer.js, packages/field-highlighter/test/field-components.test.js
A fix derived from https://github.com/vaadin/web-components/pull/3138
This makes the date picker observer in the field highlighter mind the new component structure; the date picker's focusable node is the `input` in the light DOM
=> fix: update date picker observer to mind the new structure

.eslintrc.json, packages/app-layout/src/detect-ios-navbar.js, packages/board/src/vaadin-board-row.js, packages/charts/src/vaadin-chart.js, packages/component-base/src/debounce.js, packages/component-base/src/dir-helper.js, packages/component-base/src/dir-mixin.js, packages/component-base/src/gestures.js, packages/component-base/src/iron-list-core.js, packages/component-base/src/virtualizer-iron-list-adapter.js, packages/component-base/src/virtualizer.js, packages/custom-field/test/common.js, packages/date-picker/src/vaadin-date-picker-light.js, packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/src/vaadin-date-picker-overlay-content.js, packages/date-picker/src/vaadin-infinite-scroller.js, packages/date-time-picker/src/vaadin-date-time-picker.js, packages/dialog/src/vaadin-dialog-resizable-mixin.js, packages/form-layout/test/form-layout.test.js, packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js, packages/grid/src/vaadin-grid-scroll-mixin.js, packages/notification/test/statichelper.test.js, packages/polymer-legacy-adapter/test/fixtures/mock-component.js, packages/upload/test/mock-http-request.js, packages/vaadin-overlay/src/vaadin-overlay-position-mixin.js, packages/vaadin-overlay/test/overlay.test.js, scripts/generateReleaseNotes.js
The PR adds more ESLint rules as proposed in #2987.
Part of #2987
=> refactor: add more rules to ESLint config, fix warnings

packages/avatar-group/package.json, packages/avatar-group/src/vaadin-avatar-group.js, packages/avatar-group/test/avatar-group.test.js, wtr-utils.js
Continue removing Polymer legacy dependencies.
This PR replaces the "iron-resize"/`notifyResize` mechanism in `<vaadin-avatar-group>` with a native `ResizeObserver`
=> refactor: remove iron-resizable-behavior from avatar-group

packages/date-time-picker/src/vaadin-date-time-picker.js, packages/date-time-picker/test/basic.test.js
Fixes the date time picker not removing the default slotted date and time pickers, when lazily adding custom ones. Solves an issue when using the Flow component in a Lit template, where the component is rendered with Lit, and ready, before the Flow component adds its custom slot contents.
The previous solution used a `slotchange` event to detect changes to a slot, and then always wired up the first child in that slot, which kind of requires you to manually remove the default slot content. That is problematic with Flow, because you don't have access to the default content. Instead I used the [DOM change listener approach used in CRUD](https://github.com/vaadin/web-components/blob/master/packages/crud/src/vaadin-crud.js#L668-L670) to detect if new slotted children were added, and then …
=> fix: remove generated pickers when adding custom pickers

packages/upload/src/vaadin-upload-file.js, packages/upload/src/vaadin-upload.js, packages/upload/test/file.test.js, packages/upload/theme/lumo/vaadin-upload-styles.js, packages/upload/theme/material/vaadin-upload-styles.js
1. Added `FocusMixin` and changed to use `focus-ring` styles, similarly as we did for `vaadin-scroller`,
2. Implemented custom `focusin` and `focusout` listeners to hanle focusing buttons in Shadow DOM.
Fixes #3117
=> feat: add focus-ring attribute to vaadin-upload-file

packages/component-base/src/focus-utils.js
The PR fixes the `getFocusableElements` utility to not call `forEach` on `HTMLCollection` as it causes an exception because `HTMLCollection` doesn't support such a method and needs to be converted to an array first.
The existing unit tests haven't been able to catch this bug because of a known issue with Mocha 8 extending `HTMLCollection` and some other classes with a `forEach` method globally (#3154).
Related to #3154
=> fix: don't call forEach on HTMLCollection

packages/context-menu/theme/lumo/vaadin-context-menu-styles.js
Fixes https://github.com/vaadin/web-components/issues/3133
Seems that having `-webkit-user-select: none;` always enabled for the menu-item causes the glitch on Safari. Worked around the issue by only having the rule enabled on hover.
=> fix: workaround Safari/VoiceOver menu navigation

packages/vaadin-overlay/src/vaadin-overlay.d.ts, packages/vaadin-overlay/src/vaadin-overlay.js, packages/vaadin-overlay/test/overlay.test.js, packages/vaadin-overlay/test/restore-focus.test.js, packages/vaadin-overlay/test/typings/overlay.types.ts
Needed by https://github.com/vaadin/web-components/issues/3104
Changes derived as a separate PR from https://github.com/vaadin/web-components/pull/3138
Add new API to `<vaadin-overlay>`:
- `restoreFocusNode`: If set, the overlay will focus `restoreFocusNode` on close instead of the automatically obtained reference to the last focused element before the overlay got opened.
- "vaadin-overlay-closing" -event: Dispatched when the overlay will be closed. The existing "vaadin-overlay-close" doesn't guarantee the overlay will be closed, because canceling the event also cancels the overlay closing.
=> refactor: add overlay.restoreFocusNode and vaadin-overlay-closing event

packages/component-base/index.d.ts, packages/component-base/index.js, packages/component-base/src/focus-trap-controller.d.ts, packages/component-base/src/focus-trap-controller.js, packages/component-base/test/focus-trap-controller.test.js
The PR introduces a controller for trapping focus within a DOM node that is basically an extraction of the respective logic from the overlay component.
The controller supports two methods:
- `.trapFocus(node)` – activates a focus trap for a DOM node and sets focus on the first focusable element inside the node if focus is not inside already.
- `.releaseFocus()` – deactivates the focus trap
**Todo List:**
Depends on #3141 
Part of #3134
=> refactor: add FocusTrapController for trapping focus within a node

packages/vaadin-overlay/src/vaadin-overlay.d.ts, packages/vaadin-overlay/src/vaadin-overlay.js, packages/vaadin-overlay/test/focus-trap.test.js, packages/vaadin-overlay/test/typings/overlay.types.ts
The PR drops the focus trap logic from the overlay component and makes it use `FocusTrapController` instead.
Depends on #3140
Fixes #3134
=> refactor: make overlay use FocusTrapController

packages/password-field/package.json, packages/password-field/src/vaadin-password-field-button.js, packages/password-field/src/vaadin-password-field.js, packages/password-field/test/dom/__snapshots__/password-field.test.snap.js, packages/password-field/test/password-field.test.js, packages/password-field/theme/lumo/vaadin-password-field-button-styles.js, packages/password-field/theme/lumo/vaadin-password-field-styles.js, packages/password-field/theme/lumo/vaadin-password-field.js, packages/password-field/theme/material/vaadin-password-field-button-styles.js, packages/password-field/theme/material/vaadin-password-field-styles.js, packages/password-field/theme/material/vaadin-password-field.js
Replaced `button` element with `vaadin-password-field-button` in order to leverage `focus-ring` styles.
Note, the "eye" icon itself used to show the button is still where it was (`[part="reveal-button"]`).
Fixes #3139
- Internal breaking change
=> refactor!: make reveal button extend vaadin-button

packages/combo-box/test/combo-box-light.test.js, packages/component-base/src/gestures.d.ts, packages/component-base/src/gestures.js, packages/password-field/test/password-field.test.js, packages/rich-text-editor/src/vaadin-rich-text-editor.js, packages/rich-text-editor/test/basic.test.js, packages/upload/src/vaadin-upload.js, packages/upload/test/adding-files.test.js
The ghost-click prevention mechanism in gestures is no longer necessary in modern browsers. Remove.
=> chore: remove unnecessary ghost-click prevention mechanism

packages/upload/src/vaadin-upload.js, packages/upload/test/dom/__snapshots__/vaadin-upload.test.snap.js
Fixes #2864 
Confirmed that the change fixed the issue on NVDA = "Drop files here" no longer gets announced and it can't be navigated to with the reading cursor
=> fix: hide upload drop files button from assistive technologies

packages/app-layout/src/vaadin-app-layout.js, packages/app-layout/test/app-layout.test.js, packages/app-layout/test/keyboard-navigation.test.js
When the app-layout drawer is closed, it should be inaccessible by the keyboard tabbing navigation. The PR solves this by adding `visibility: hidden` to the drawer when it is closed.
**WARNING: Do not merge this PR before #2395 is merged.**
Depends on #2395
Related to #95, #466, #2888
=> feat: prevent focusing drawer by keyboard when it is closed 

packages/checkbox-group/test/checkbox-group.test.js, packages/combo-box/test/aria.test.js, packages/custom-field/test/custom-field.test.js, packages/date-picker/test/wai-aria.test.js, packages/date-time-picker/test/aria.test.js, packages/field-base/src/field-mixin.js, packages/field-base/test/field-mixin.test.js, packages/radio-group/test/radio-group.test.js, packages/time-picker/test/aria.test.js
The PR introduces a workaround for `FieldMixin` that prevents double error message announcement when using NVDA, occurring as a side-effect of linking the error id to the ARIA target element. From now on, the error message is announced once and only when the `[role=alert]` attribute is added to the slotted error element.
The workaround is to add a `setTimeout` delay before linking the error id to the ARIA target element. This is the only workaround I was able to find. For the record, I tried `requestAnimationFrame` and `new Promise((resolve) => resolve())`, but they didn't work.
Fixes #3061
=> fix: prevent double error message announcement when using NVDA

packages/field-base/src/field-aria-controller.js
The PR makes `FieldAriaController` use attribute utils instead of its own implementation of adding and removing values from ARIA attributes.
=> refactor: use attribute utils in FieldAriaController

packages/combo-box/package.json, packages/combo-box/src/vaadin-combo-box-dropdown.js, packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/test/combo-box-light.test.js, packages/combo-box/test/filtering.test.js
`IronResizableBehavior` hasn't been necessary for `<vaadin-combo-box>` [since](https://github.com/vaadin/web-components/pull/2497) replacing the internal overlay positioning logic with `vaadin-overlay-position-mixin`
Part of https://github.com/vaadin/web-components/issues/331
=> refactor: remove iron-resizable-behavior from combo-box

packages/app-layout/src/vaadin-app-layout.d.ts, packages/app-layout/src/vaadin-app-layout.js, packages/app-layout/test/app-layout.test.js, packages/app-layout/test/dom/__snapshots__/app-layout.test.snap.js, packages/app-layout/test/typings/app-layout.types.ts
This PR adds an `i18n` property for localizing the app-layout. The property has the following structure:
```js
{
drawer: 'Drawer'
}
```
The `i18n.drawer` property can be used to customize the drawer's announcement when the drawer is opening in the overlay. In more specific terms, this i18n property affects the `aria-label` attribute that appears on the drawer element when it switches to the overlay mode.
Part of #466
=> feat: add i18n property to app-layout

dev/split-layout.html, packages/split-layout/package.json, packages/split-layout/src/vaadin-split-layout.d.ts, packages/split-layout/src/vaadin-split-layout.js, packages/split-layout/test/split-layout.test.js
Part of #331 
The video shows how the child components adapt to parent container size changes without split layout having to explicitly notify them.
https://user-images.githubusercontent.com/1222264/146634102-f7ccc4fd-9bac-4dc3-8da4-824da15876e9.mp4
=> refactor: remove iron-resizable-behavior from split-layout

packages/app-layout/package.json, packages/app-layout/src/vaadin-app-layout.js, packages/app-layout/test/app-layout.test.js
Part of #331
This PR effectively reverts https://github.com/vaadin/web-components/pull/229
Child components, such as `<vaadin-grid>` now use resize observers internally and thus no longer need to be notified of size changes by the parent container. The following example replicates the original issue covered in #229 but with `IronResizableBehavior` removed from `<vaadin-app-layout>`:
https://user-images.githubusercontent.com/1222264/146784481-7ee9cc0f-60a5-475d-9e72-031ca259caf5.mp4
=> refactor: remove iron-resizable-behavior from app-layout

packages/field-base/src/field-mixin.js, packages/field-base/test/field-mixin.test.js, packages/text-area/src/vaadin-text-area.js, packages/text-area/test/text-area.test.js, packages/text-field/test/text-field.test.js
Part of #331 
`<vaadin-text-area>` or other fields no longer need to dispatch the "iron-resize" event. Container components, such as `<vaadin-tabs>` or `<vaadin-grid>` use internal resize observers and automatically react to child resizes.
Here's an example, where a `<vaadin-text-area>` is placed inside the row details of `<vaadin-grid>`. Typing into the field expands it and the field is marked invalid using a timeout. In both cases, the grid automatically notices the size (row height) change and repositions its rows:
https://user-images.githubusercontent.com/1222264/146932375-d249e1f0-cfdb-42d1-9fee-7c431c962776.mp4
=> refactor: remove iron-resize event from field-mixin

packages/avatar/package.json
Avatar has never actually used `iron-resizable-behavior` so there are no other changes in this PR.
=> chore: remove an unused dependency

packages/form-layout/src/vaadin-form-item.d.ts, packages/form-layout/src/vaadin-form-item.js, packages/form-layout/test/form-item.test.js
Added a deprecation warning that since Vaadin 23, the user has to wrap multiple fields with a `<vaadin-custom-field>` instead of placing them directly to a form-item element. 
👎 **Deprecated:**
```html
<vaadin-form-item>
<label slot="label">Label</label>
<input />
<input />
</vaadin-form-item>
```
👍 **Recommended:**
```html
<vaadin-form-item>
<label slot="label">Label</label>
<vaadin-custom-field>
<input />
<input />
</vaadin-custom-field>
</vaadin-form-item>
```
Fixes #3065
=> feat: deprecate placing multiple fields directly to a form-item

packages/time-picker/theme/lumo/vaadin-time-picker.js, packages/time-picker/theme/material/vaadin-time-picker.js
Starting from Vaadin 22, we changed `vaadin-time-picker` to not use `vaadin-combo-box-light` but its own extension instead. So there is no need for importing the `-light` version, as it just brings some extra bytes to JS bundle.
- Refactor
=> refactor: update time-picker theme files imports

packages/combo-box/test/visual/common.js, packages/login/test/visual/common.js, packages/number-field/test/visual/common.js
Updated a few components to use `caret-color` CSS property instead of setting `font-size: 0` for consistency.
- Tests
=> test: do not use font-size for hiding blinking caret

packages/vaadin-lumo-styles/color.js, packages/vaadin-lumo-styles/typography.js
Flow intends to use (temporary) href attribute removal to disable anchors (as they lack a native disabled state), see https://github.com/vaadin/flow/issues/10924. This PR changes Lumo styling of anchors so that the regular styling is applied only to anchors with href (using the `:any-link` pseudoclass) and Lumo disabled text color is instead applied to those without.
Potential breaking change: if an app contains href-less anchors (and e.g. use click event to do stuff instead) they will now have a disabled text color. However, at least Flow apps are almost guaranteed to have an _empty_ href rather than missing one (unless developer has explicitly removed the empty href), so this is very unlikely to affect Flow-based apps.
Fixes #1594
=> feat: Distinct styling for anchors without href

dev/avatar-group.html, packages/avatar-group/package.json, packages/avatar-group/src/vaadin-avatar-group.js, packages/avatar-group/test/avatar-group.test.js, packages/avatar/package.json
Updated `vaadin-avatar-group` to use new `announce()` helper added in #3238
- Refactor
=> refactor: use a11y-announcer in avatar-group

packages/field-highlighter/package.json, packages/field-highlighter/src/vaadin-field-highlighter.js, packages/field-highlighter/test/field-highlighter.test.js
Updated `field-highlighter` to use new `announce()` helper added in #3238
- Refactor
=> refactor: use a11y-announcer in field highlighter

packages/date-picker/package.json, packages/date-picker/src/vaadin-date-picker-overlay-content.js, packages/date-picker/test/wai-aria.test.js
Updated `vaadin-date-picker-overlay-content` to use new `announce()` helper added in #3238
Note: using bigger delay `clock.tick(200)` here to ensure all the internal timeouts terminate.
- Refactor
=> refactor: use a11y-announcer in date-picker

packages/menu-bar/src/vaadin-menu-bar-buttons-mixin.js, packages/menu-bar/src/vaadin-menu-bar.d.ts, packages/menu-bar/src/vaadin-menu-bar.js, packages/menu-bar/test/menu-bar.test.js
Add logic to the `menu-bar` so if `disabled`, all buttons in the bar will be disabled. If not set, each item then will be `disabled` only if set on the item itself.
Related https://github.com/vaadin/web-components/issues/3202
=> feat: add disabled property to menu-bar

packages/vaadin-material-styles/color.js
This essentially reverts https://github.com/vaadin/vaadin-material-styles/commit/5fe9f9ebbf2aeaf3532ad25b7b226af5911683ca
The workaround was needed for polyfilled browsers that we no longer support.
- Refactor
=> refactor: remove obsolete IE11 workaround

packages/combo-box/src/vaadin-combo-box-scroller.js, packages/combo-box/test/aria.test.js, packages/time-picker/test/aria.test.js
Tested with NVDA and now the last item is properly announced. 
Not sure why I missed to handle it in https://github.com/vaadin/web-components/pull/2745#discussion_r722261384 🤷‍♂️ 
Fixes #2747
- Bugfix
=> fix: use correct 1-based index for aria-posinset

packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/test/toggling-dropdown.test.js, packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/test/dropdown.test.js, packages/field-base/src/virtual-keyboard-controller.d.ts, packages/field-base/src/virtual-keyboard-controller.js, packages/field-base/test/virtual-keyboard-controller.test.js
Fixes #3191 
This PR sets the `inputMode` property of the `<input>` element in date-picker/combo-box to "none" whenever the dropdown gets closed, effectively preventing the virtual keyboard from opening automatically.
https://user-images.githubusercontent.com/1222264/148064485-ee3c685c-249f-4e91-98ab-b0ac03f8cb8e.mp4
The `inputMode` property is reset back to its default value in two cases:
- **on blur:** a user might tab to the next input while the `inputMode` is "none". Tabbing back to the field should open the virtual keyboard (default behavior).
- **on touchstart:** a user can tap the field to get the virtual keyboard opened
=> fix!: prevent virtual keyboard open on combo-box/date-picker close

packages/component-base/src/focus-trap-controller.d.ts
Added missing `export` for the controller `.d.ts` file.
- Bugfix
=> fix: add missing export to FocusTrapController

packages/grid/src/vaadin-grid.js, packages/grid/test/accessibility.test.js
Fixes #3180 
This PR changes the `role` of the `<table>` element inside `<vaadin-grid>`'s shadow root from "grid" to "treegrid", which supports the `aria-level` attribute as desribed [here](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-level#within_treegrid_role). Changing the role to "treegrid" has been [discussed](https://github.com/vaadin/web-components/issues/97#issuecomment-818603600) earlier also.
The current `role="grid"` originates from times before hierarchy support was added to `<vaadin-grid>`. The [feature PR](https://github.com/vaadin/vaadin-grid/pull/1057) missed the necessary update to the `<table>` element's role.
=> fix: change grid table role to treegrid

packages/field-base/src/field-mixin.js, packages/field-base/src/helper-controller.d.ts, packages/field-base/src/helper-controller.js, packages/field-base/test/field-mixin.test.js, packages/select/test/accessibility.test.js
Updated `FieldMixin` to use `HelperController` for handling helper, similarly to `LabelController`.
- Refactor
=> refactor: extract helper logic to HelperController

packages/notification/src/vaadin-notification.js, packages/notification/test/notification.test.js
Currently interacting with a notification (clicking in it, pressing Escape while focusing a control within it), will also close the top-most vaadin-overlay. Notification does not use / integrate with vaadin-overlay, which means that those interactions are registered as outside interactions from the overlay.
This change makes the notification container listen for `vaadin-overlay-close` events, and cancels them if they occured in the notification. 
I think a better solution would be to stop propagation of click / keyboard events from the notification container, however vaadin-overlay uses a [capture event listener](https://github.com/vaadin/web-components/blob/master/packages/vaadin-overlay/src/vaadin-overlay.js#L755) for outside clicks. In order to support stopping propagation, we would …
=> fix: prevent closing overlays when interacting with notifications

packages/button/theme/lumo/vaadin-button-styles.js
Make the hover state more apparent when there is no transition. Currently the 0.2s duration makes it more difficult to notice the visual change when hovering over the button.
Considered technically as a (small) breaking change because some custom theme might rely on this property. Doesn't not break an app, but can some could consider it as a degradation of user experience.
I want to highlight this change in the release notes, that’s the main reason I marked this as "breaking", but I’m okay without marking it such.
=> refactor!: remove transition from hover state

packages/field-base/src/helper-controller.js, packages/field-base/test/field-mixin.test.js
The problem was caused by improper timings: by the time when the `helperText` property observer runs when attached, the `FlattenedNodesObserver` is not yet triggered. This is due to the fact that Polymer observers run before `ready()`. As a result, `this.node` does not exist yet. Changed to get the actual slot child every time to ensure it's up to date. 
-  Bugfix
=> fix: do not override custom helper on attach

packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/test/basic.test.js, packages/combo-box/test/scrolling.test.js
Part of https://github.com/vaadin/flow-components/issues/2524
This change fixes the main issue in https://github.com/vaadin/flow-components/issues/2524:
The "custom-item-set" event was dispatched even when the value matched the label of `comboBox.selectedItem`.
There's still another issue related to https://github.com/vaadin/flow-components/issues/2524 (the dropdown doesn't populate on the first open after setting new items) but it will be fixed separately.
=> fix: consider a value matching selected item label a known value

packages/date-time-picker/test/visual/common.js, packages/date-time-picker/test/visual/lumo/date-time-picker.test.js, packages/date-time-picker/test/visual/material/date-time-picker.test.js
Follow-up from #3310. This is needed to make visual test reliable (it failed when cherry-picking).
The same commit is already applied to the cherry-pick PR manually.
- Tests
=> test: add CSS to hide caret when focused

packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/test/wai-aria.test.js
Currently `autocomplete="off"` is set by combo-box and time-picker, but not by the date-picker. This PR fixes that.
Fixes https://github.com/vaadin/flow-components/issues/2510
- Bugfix
=> fix: disable autocomplete for date-picker

packages/vaadin-lumo-styles/mixins/input-field-shared.js
There’s no need to scope those styles to only apply when the field has a label. Also, scoping the error message styling to be based on the presence of the label is incorrect.
I traced this “bug” back to 4 years ago: https://github.com/vaadin/vaadin-text-field/commit/494cfbce406fe16b3c68e27892ec440fc338535f
=> fix: remove unnecessary [has-label] selectors

packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/test/filtering.test.js, packages/time-picker/test/combo-box.test.js
The original issue was found in `vaadin-time-picker` but the actual problem was in combo-box with `filteredItems`.
It was caused by the fact that `autoOpenDisabled` was treated the same as `opened` which isn't always correct.
Fixes #507
- Bugfix
=> fix: set correct index when autoOpenDisabled

packages/field-base/src/input-field-mixin.js, packages/field-base/test/input-field-mixin.test.js
The original issue is a regression introduced while adding slotted input support https://github.com/vaadin/vaadin-text-field/pull/283/commits/c56eff7d3fa8f8770573e07048e08bb345bbc458
In particular, [this block](https://github.com/vaadin/vaadin-text-field/pull/283/commits/c56eff7d3fa8f8770573e07048e08bb345bbc458#diff-4291a0d535966bc93fefcb9582856c416ff3d7924442b8b6e56e6d73bb450b6eR353-R360) added `return` for user input inside the observer so the `validate()` call could not be reached.
The logic has been changed, so overriding the `_onInput` listener seems like a correct place for this.
Fixes #2729
- Bugfix
=> fix: validate on input event when invalid

packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js, packages/grid/test/keyboard-navigation.test.js
=> fix: only accept a focusable child element as a focus target

packages/vaadin-lumo-styles/color.js, packages/vaadin-lumo-styles/typography.js
It turns out the selector `a:any-link` has higher specificity than `.link` which causes users styles to break.
We can fix this by using `a:where(:any-link)`: https://codepen.io/webpadawan/pen/OJOLgdp
See also https://css-tricks.com/using-the-specificity-of-where-as-a-css-reset/
Closes https://github.com/vaadin/start/issues/1730
- Bugfix
=> fix: decrease link selectors specificity using `:where()`

packages/grid/src/vaadin-grid-column.js, packages/grid/src/vaadin-grid-selection-mixin.js, packages/grid/test/selection.test.js
Fixes https://github.com/vaadin/flow-components/issues/2552
Fixes https://github.com/vaadin/web-components/issues/2247
Fixes https://github.com/vaadin/flow-components/issues/1913
=> fix: don't update items manually on selection change

packages/component-base/src/slot-controller.js, packages/email-field/test/dom/__snapshots__/email-field.test.snap.js, packages/field-base/src/error-controller.d.ts, packages/field-base/src/error-controller.js, packages/field-base/src/field-mixin.js, packages/field-base/test/field-mixin.test.js, packages/integer-field/test/dom/__snapshots__/integer-field.test.snap.js, packages/message-input/test/dom/__snapshots__/message-input.test.snap.js, packages/number-field/test/dom/__snapshots__/number-field.test.snap.js, packages/password-field/src/vaadin-password-field.d.ts, packages/password-field/src/vaadin-password-field.js, packages/password-field/test/dom/__snapshots__/password-field.test.snap.js, packages/select/test/dom/__snapshots__/select.test.snap.js, packages/text-area/test/dom/__snapshots__/text-area.test.snap.js, packages/text-field/test/dom/__snapshots__/text-field.test.snap.js
Similar to #3185 but for `error-message` slot.
- Refactor
=> refactor: move errorMessage logic to ErrorController

packages/date-picker/src/vaadin-month-calendar.js, packages/date-picker/test/basic.test.js, packages/date-picker/test/month-calendar.test.js, packages/date-picker/test/wai-aria.test.js
This is a first step of `vaadin-date-picker` overlay content a11y improvements.
Changed to use `<table>` markup. For now the focus is not yet changed.
The next step would be to use `<button>` in table cells like in [Duet Date Picker](https://duetds.github.io/date-picker/).
Related to https://github.com/vaadin/web-components/issues/3248
- Refactor
=> refactor!: update month calendar to use table

packages/confirm-dialog/theme/lumo/vaadin-confirm-dialog-styles.js
Use the same border radius on the footer as in the overlay container. Currently the footer corners are slightly overflowing
.
=> fix: align footer border-radius with overlay container

packages/date-picker/test/common.js, packages/date-picker/test/keyboard-input-old.test.js, packages/date-picker/test/keyboard-input.test.js, packages/date-picker/test/keyboard-navigation.test.js
Before re-implementing the date-picker keyboard navigation, I decided to update existing tests:
1. Updated `keyboard-input.test.js` to use `sendKeys()` instead of the fake input helpers e.g. `inputText`
2. Moved some tests to `keyboard-input-old.test.js` - some of these will be no longer relevant after the refactor
3. Grouped some tests into suites e.g. those related to focused date, invalid input, opening the overlay etc.
There will be another PR with the actual keyboard navigation changes based on this one.
- Tests
=> test: rewrite date-picker keyboard tests to use sendKeys

packages/select/test/typings/select.types.ts
Removes the linter warning (currently shown in every PR)
=> test: remove non-null assertion in select types test

packages/date-picker/test/common.js, packages/date-picker/test/keyboard-input.test.js, packages/date-picker/test/keyboard-navigation.test.js
Follow up on #3371, this is a second batch of date-picker keyboard tests converted to use `sendKeys`.
Again, it was extracted from #3372 - see https://github.com/vaadin/web-components/pull/3372/commits/8602303f6b8c362793df25c626607a4d48437df6
- Tests
=> test: use sendKeys for keyboard navigation tests

packages/crud/src/vaadin-crud-grid.js, packages/crud/test/crud-grid.test.js
=> fix: only run the crud grid header renderer once

dev/app-layout.html, packages/app-layout/src/vaadin-app-layout.js, packages/app-layout/src/vaadin-drawer-toggle.js, packages/app-layout/test/app-layout.test.js, packages/app-layout/test/drawer-toggle.test.js
1. Changed the default `aria-label` from "Toggle" to "Toggle navigation panel"
2. Added logic to set `aria-expanded` attribute depending on `drawerOpened`
Fixes #3368
- Bugfix
=> fix: improve drawer toggle ARIA attributes

packages/split-layout/src/vaadin-split-layout.js, packages/split-layout/test/split-layout.test.js
Added logic to remove `slot` attribute when nodes are removed from split-layout.
Fixes vaadin/flow-components#2581
- Bugfix
=> fix: cleanup slot attribute on removed nodes

packages/map/src/vaadin-map.js, packages/map/test/map.test.js
Moves initialization of the internal OpenLayers instance to the constructor, so that the map is configurable even when it is not attached to the DOM.
Fixes https://github.com/vaadin/flow-components/issues/2595
=> fix: ensure OpenLayers instance is initialized before adding map to DOM

packages/date-picker/src/vaadin-date-picker.js, packages/date-picker/test/basic.test.js
As described on [this issue](https://github.com/vaadin/flow-components/issues/2428), when the user clicks on the calendar icon when the `DatePicker` (or, in the case reported by the issue, a `DateTimePicker`) is inside a` GridPro`, the editor gets closed. The same do not happen when the clock icon on the TimePicker is clicked. 
The issue comes to the fact that when the user clicks on the calendar icon, the input field is briefly blurred, which causes a `blur` event that is listened by the `GridPro` and it stops the edit mode of the cell.
This change applies the same code that is used on ComboBox to prevent the blur event from being fired when the user clicks on the toggle button.
Part of https://github.com/vaadin/flow-components/issues/2428
=> [date-picker] fix: prevent input blur on calendar icon click

packages/date-picker/src/vaadin-date-picker-overlay-content.js, packages/date-picker/src/vaadin-date-picker.js, packages/date-picker/test/wai-aria.test.js
Removed `role="button"` from the internal elements that are excluded from screen readers using `aria-hidden`
1. Date-picker toggle button - see #3375
2. Date-picker year buttons - see #3349
- Refactor
=> refactor: cleanup no longer used button roles

packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/src/vaadin-combo-box.js, packages/combo-box/test/toggling-dropdown.test.js
Updated host event listener to check if the click was on the label or input field.
Fixes #3399
- Bugfix
=> fix: do not open dropdown on helper click

packages/field-base/src/input-control-mixin.js, packages/field-base/test/input-control-mixin.test.js
=> fix: fire input event when clearing on Esc

packages/map/theme/lumo/vaadin-map-styles.js, packages/map/theme/material/vaadin-map-styles.js
Makes keyboard focus visible for Map component controls (for example, zoom in and out buttons).
=> fix: show keyboard focus outline for map controls

packages/component-base/index.d.ts, packages/map/src/vaadin-map.d.ts, packages/map/src/vaadin-map.js, packages/map/test/map.test.js
Add ResizeMixin to the Map component, so that the internal OpenLayers map gets updated when the host elements size changes.
=> fix: trigger size updates for map on resize

packages/accordion/package.json, packages/accordion/test/dialog.test.js, packages/component-base/src/focus-trap-controller.js, packages/component-base/src/focus-utils.js, packages/component-base/test/focus-trap-controller.test.js
1. Restored the previous (Vaadin 14-23) logic for collecting focusable elements that was changed in #3141 and added tests for handling hidden elements
2. Added tests for `vaadin-accordion` inside `vaadin-dialog` to ensure <kbd>Tab</kbd> works
Fixes #3410
- Bugfix
=> fix: restore old logic for getting focusable elements

packages/component-base/src/tabindex-mixin.js, packages/field-base/src/delegate-focus-mixin.d.ts, packages/field-base/src/delegate-focus-mixin.js, packages/field-base/src/shadow-focus-mixin.js, packages/field-base/test/delegate-focus-mixin.test.js, packages/message-input/test/dom/__snapshots__/message-input.test.snap.js
Re-introduced logic to forward `tabindex` attribute to `DelegateFocusMixin` for handling `tabindex="-1"` on the host.
This PR also changes how `tabindex` property is defined:
- In `TabindexMixin` we set default value to `0` for components without `focusElement` such as `vaadin-button`
- In `DelegateFocusMixin` we reset value to `undefined` because we don't want host element to be focusable
- In `ShadowFocusMixin` we have to set value back to `0` to forward into shadow DOM for `vaadin-details`
Fixes https://github.com/vaadin/flow-components/issues/2455
- Bugfix (BFP)
=> fix: forward tabindex attribute to focusElement

packages/select/src/vaadin-select.js
This property is a leftover from older version of the component and it's not used anywhere.
- Refactor
=> refactor: remove unused private property

packages/details/theme/lumo/vaadin-details-styles.js
Other interactive components like button have this configure-able cursor - was wondering: should the details' summary have it as well? Somebody can interact with it.
=> refactor: use --lumo-clickable-cursor for details' summary

packages/component-base/src/media-query-controller.d.ts, packages/component-base/src/media-query-controller.js, packages/component-base/test/media-query-controller.test.js
Added `MediaQueryController` to replace `<iron-media-query>` currently used in some components.
=> feat: add controller to handle media queries

packages/date-picker/package.json, packages/date-picker/src/vaadin-date-picker-light.js, packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/src/vaadin-date-picker-overlay-content.js, packages/date-picker/src/vaadin-date-picker.js
Replaced `iron-media-query` with `MediaQueryController` for date-picker and overlay content.
Based on #3426
- Refactor
=> refactor: remove iron-media-query from date-picker

packages/grid/src/vaadin-grid-a11y-mixin.js, packages/grid/src/vaadin-grid-row-details-mixin.js, packages/grid/src/vaadin-grid.js, packages/grid/test/accessibility.test.js, packages/grid/test/row-details.test.js
Currently, `aria-expanded` is used by `vaadin-grid` web component in two cases:
1. Tree Grid rows: `aria-expanded` set on `<tr>` (which is correct)
2. Row details: `aria-expanded` set on `<td>` (does not look correct).
The reason for this is that row details feature was implemented before Tree Grid.
As discussed, let's remove `aria-expanded` from individual cells for now.
We can consider using `aria-details` when it has [better support](https://a11ysupport.io/tech/aria/aria-details_attribute).
Fixes #3425
- Bugfix
=> fix: do not set aria-expanded on grid cells

packages/grid/src/vaadin-grid-a11y-mixin.js, packages/grid/test/accessibility.test.js, packages/grid/test/data-provider.test.js
Updated the logic to only set `aria-level` attribute on expandable rows and their nested rows.
Fixes #3424
- Bugfix
=> fix: only set aria-level on tree grid rows

packages/combo-box/package.json, packages/combo-box/src/vaadin-combo-box-dropdown.js, packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/test/combo-box-light.test.js, packages/combo-box/test/filtering.test.js
Manual cherry-pick of #3195 to `22.0` branch for making it easier to backport fixes in the future.
- Cherry-pick
=> refactor: remove iron-resizable-behavior from combo-box (#3195) (CP: 22.0)

packages/field-base/src/label-controller.js, packages/field-base/test/field-mixin.test.js
The root cause of the issue was the wrong initialization order:
1. `initCustomNode` is called and it toggles `has-label` state which fires `label-changed` event
2. Inside the `FieldAriaController` we attempt to set `aria-labelledby` but the label ID is still empty
3. `initNode` is called and the slot initializer runs for the custom slotted label, setting the ID too late
Overall, I'm not happy about the implementation as it's quite a bit messy.
But this PR makes it work and aligns `LabelController` with other controllers:
https://github.com/vaadin/web-components/blob/4a031fefe3c64e425d5fcd25766d4b74b637f298/packages/field-base/src/helper-controller.js#L28-L29
https://github.com/vaadin/web-components/blob/4a031fefe3c64e425d5fcd25766d4b74b637f298/packages/field-base/src/error-controller.js#L6 …
=> fix: ensure slotted label ID is set properly

packages/date-picker/test/basic.test.js
We have removed `i18n.calendar` in Vaadin 23 as the toggle button is no longer supposed to be announced.
This is the only place where it remains to be set, so let's remove it as well.
- Tests
=> test: remove no longer existing property

packages/context-menu/src/vaadin-contextmenu-items-mixin.js, packages/context-menu/test/items.test.js
The `theme` feature (#2401) introduced a regression: removal of the `theme` attribute set on the `item.component`.
This PR checks if the component already has a theme to make sure it's preserved.
Fixes https://github.com/vaadin/flow-components/issues/2559
- Bugfix
=> fix: do not remove menu item component theme

packages/charts/src/vaadin-chart.d.ts, packages/charts/src/vaadin-chart.js, packages/charts/test/chart-element.test.js, packages/charts/theme/vaadin-chart-base-theme.js
Replaced an old workaround that only handled `chart.style.height` with a proper `ResizeObserver`.
Note, this fix only goes to Vaadin 23 because there is no `ResizeMixin` in older versions.
Fixes #1605
- Bugfix
=> fix: use ResizeMixin to observe chart resize

dev/map.html, packages/map/src/vaadin-map.js, packages/map/test/map.test.js, packages/map/test/styles.test.js
Adds a default size for the map component. The element already was a block element, which covers width. For height the element should align with Grid and Charts, which both have a default height of 400px.
Fixes https://github.com/vaadin/web-components/issues/3449
=> feat: add default size for map component

packages/custom-field/src/vaadin-custom-field.js, packages/field-base/src/input-control-mixin.js
Added JSDoc for events that were documented in `21.0` branch but are currently missing on `master`:
https://github.com/vaadin/web-components/blob/824e52a9aea964e57cc2937c097a375097c24a05/packages/vaadin-text-field/src/vaadin-text-field-mixin.js#L856-L867
https://github.com/vaadin/web-components/blob/824e52a9aea964e57cc2937c097a375097c24a05/packages/vaadin-custom-field/src/vaadin-custom-field-mixin.js#L248-L252
- Docs
=> docs: restore JSDoc for input and change events

packages/map/package.json, packages/map/test/typings/map.types.ts, yarn.lock
Change OpenLayers dependency to a dev version that contains fixes for the broken Typescript definitions. I tested this specific version against the Flow component, integration tests, docs, as well as the demo app. The plan is to upgrade to a new bugfix / minor release as soon as it is out.
Fixes #3465
=> fix: bump OL to dev version to solve Typescript issues

packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/test/basic.test.js
Currently the `custom-value-set` event can be fired in several cases:
1. When user "commits" the input value by pressing <kbd>Enter</kbd> key
2. When `opened` property changes to `false` (in the observer)
3. When combo-box loses focus (in the `focusout` listener)
However, user can perform custom logic on `custom-value-set` event.
For example, it can be opening a dialog that would cause blur.
Added a check to ensure the same custom value isn't confirmed twice.
Fixes https://github.com/vaadin/flow-components/issues/2523
- Bugfix
=> fix: do not fire custom-value-set event twice

packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/test/basic.test.js
This reverts commit eaba82b69e22080f59f4383bc8ee8c7243c8872e.
The fix caused `TimePicker` ITs to fail. Reverting for now to unblock beta release.
We might need to find a different solution for the original issue.
- Revert
=> Revert "fix: do not fire custom-value-set event twice (#3478)"

packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/test/basic.test.js
Updated the original fix to only check last custom value on `focusout` where the actual problem manifested.
To me it seems like a cleaner approach than attempting to reset that flag in all the possible cases.
Fixes https://github.com/vaadin/flow-components/issues/2523
- Bugfix
=> fix: check last custom value on focusout

packages/confirm-dialog/src/vaadin-confirm-dialog.d.ts, packages/confirm-dialog/src/vaadin-confirm-dialog.js, packages/confirm-dialog/test/confirm-dialog.test.js
Fixes confirm dialog to not apply the text and theme values when using custom buttons. Custom buttons should not be altered, especially the content, which might contain custom elements like icons.
This might break stuff for developers that have adapted to the broken behavior, and set text and theme in addition to adding a custom button. Seeing that we did not get a bug report about this behavior so far, it might not be a very common use-case.
Fixes https://github.com/vaadin/flow-components/issues/2709
=> fix: avoid overriding custom button content and theme

packages/number-field/test/number-field.test.js
When converting `vaadin-number-field` to LitElement, I discovered that some tests are using `forEach` loops.
With Polymer it's fine as updates are synchronous, but with LitElement we need `await field.updateComplete`
Refactored such tests to use `forEach` loops for creating many tests vs only one test with many assertions.
- Tests
=> test: update number-field tests to avoid loops

packages/password-field/src/vaadin-password-field.js
This PR changes `vaadin-password-field` to use `SlotController` in preparation for possible Lit conversion.
The main reason is the fact that `SlotMixin` uses `connectedCallback` but in case of Lit that's too early.
We should eventually get rid of the `SlotMixin` to only have 1 way of handling light DOM children.
- Refactor
=> refactor: use SlotController for reveal button

packages/password-field/src/vaadin-password-field.js, packages/password-field/test/password-field.test.js
This is a fix for regression introduced by #3416 and caused by incorrect overriding of the observer.
- Bugfix
=> fix: restore tabindex when field is re-enabled

packages/text-area/src/vaadin-text-area.js, packages/text-area/test/text-area.test.js
Fixes https://github.com/vaadin/web-components/issues/3494
=> fix: don't cancel text-area wheel event unnecessarily

packages/component-base/src/focus-trap-controller.js, packages/component-base/test/focus-trap-controller.test.js
In Vaadin 22, the focus trap logic was placed in `vaadin-overlay` where we checked if the current instance is the last one:
https://github.com/vaadin/web-components/blob/2d360f043e4825bc431c55ba41a269d38c6009cc/packages/vaadin-overlay/src/vaadin-overlay.js#L514-L517
Implemented similar "stack" logic in `FocusTrapController` to make sure it covers all the components using it.
For example, there could be a `vaadin-dialog` opened from the `vaadin-app-layout` modal drawer, etc.
Fixes #3491
- Bugfix
=> fix: make nested focus trap controllers work

packages/menu-bar/src/vaadin-menu-bar.js, packages/menu-bar/test/menu-bar.test.js
Updated to use the same approach as for other components, e.g. `vaadin-grid`:
https://github.com/vaadin/web-components/blob/36dea1bb06a51c566151a27f9c50c8ac56fe4403/packages/grid/src/vaadin-grid-styles.js#L22
Fixes #3503
- Bugfix
=> fix: do not expand to full available width

packages/component-base/src/element-mixin.js, packages/component-base/test/element-mixin.test.js
The PR disables the `cancelSyntheticClickEvents` Polymer setting through `ElementMixin`.
This setting determines whether the legacy Polymer gestures module should globally listen for click events on the page and cancel them if they are considered synthetic. Normally, the legacy gestures module is not supposed to be imported anywhere in the web components and `component-base/src/gestures.js` should be used instead which doesn't have that logic. However, if you import an iron component e.g. iron-icon or iron-list, it will implicitly cause the legacy gestures module to import.
This setting has to be disabled because otherwise, it affects `vaadin-button` components, preventing them from triggering actions on click. It occurs when (a) both a button and an iron component are used on the same …
=> fix: disable cancelSyntheticClickEvents globally

packages/checkbox-group/test/checkbox-group.test.js, packages/checkbox-group/test/visual/lumo/checkbox-group.test.js, packages/checkbox-group/test/visual/material/checkbox-group.test.js, packages/checkbox/test/checkbox.test.js, packages/radio-group/test/radio-button.test.js, packages/radio-group/test/radio-group.test.js, packages/radio-group/test/visual/lumo/radio-group.test.js, packages/radio-group/test/visual/material/radio-group.test.js, packages/vaadin-overlay/test/focus-trap.test.js
Updated all the cases of using `vaadin-checkbox` and `vaadin-radio-button` with a default slot to use `label` property.
- Tests
=> test: use label instead of deprecated default slot

packages/component-base/src/element-mixin.js, packages/component-base/test/element-mixin.test.js
This reverts commit 03b420e0bee214acc294e57934215f3cbe45d23d.
Reverting as the fix causes failures in Vaadin 22 when using with Flow (see https://github.com/vaadin/flow-components/pull/2795)
The reason is that V22 uses Polymer pinned to 3.2.0 and `setCancelSyntheticClickEvents` API was added later. 
This is not the case for V23 where we have upgraded Polymer to the latest one (3.4.1): https://github.com/vaadin/flow/pull/12935
The actual fix was targeting the issue with low impact (iOS VoiceOver users) and IMO it does not have to be in V22.
Users who care about a11y should use V23 instead as it contains more important fixes to other web components.
Also for pure web components users it can be easily done by applying the same fix manually.
- Revert
=> Revert "fix: disable cancelSyntheticClickEvents globally (#3515)" (22.0)

.gitignore, README.md, scripts/fixDistTag.sh
Added a script to run `npm dist-tag` for all packages after publishing a patch release.
Example: we published `23.0.1` and then `22.0.7` so it becomes marked as `latest`.
Run this script manually (for now) to ensure it updates `latest` tag back to `23.0.1` 
=> chore: add script to run npm dist-tag

packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js, packages/grid/test/keyboard-navigation.test.js
Currently, the stored column order is only reset on navigating left and right using keyboard.
This PR changes it to also reset on `mousedown` event to avoid using wrong column.
Fixes #2134
- Bugfix
=> fix: reset stored column order on mousedown

packages/date-picker/src/vaadin-date-picker-light.js, packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/src/vaadin-date-picker-overlay-content.js, packages/date-picker/src/vaadin-date-picker.js, packages/date-picker/src/vaadin-month-calendar.js, packages/date-picker/test/basic.test.js
This PR updates the date-picker logic in preparation for fixing events being fired in the wrong order.
Related to #3379
There are two different ways of how `vaadin-date-picker` value can be updated:
1. Programmatically, by setting `value` property with JS,
2. User-selected (by typing or selecting from the overlay).
In the first case, `value` is set and then internal `_selectedDate` property is updated accordingly. This works fine.
In the second case, `_selectedDate` is set first, then `value` is updated and then `_selectedDate` is set again:
https://github.com/vaadin/web-components/blob/4be73e80304191b3d518003c932ba7b3d25ec54f/packages/date-picker/src/vaadin-date-picker-mixin.js#L672
This part of logic is problematic because of how internal flags are used. Currently, there are two of …
=> refactor: handle user-selected date properly

wtr-utils.js
Update the web test runner change detection script to use `23.0` as a base branch for Vaadin 23.0
=> chore: update change detection branch to 23.0

packages/text-area/src/vaadin-text-area.js, packages/text-area/theme/lumo/vaadin-text-area-styles.js, packages/text-area/theme/material/vaadin-text-area-styles.js
When converting `vaadin-text-area` to Lit, I noticed that some styles placed in themes should be in `src`.
Using `white-space: pre-wrap` is needed to override this line:
https://github.com/vaadin/web-components/blob/54decd0cc017ec15d717a063aba63a4c4ccc396a/packages/input-container/src/vaadin-input-container.js#L34
Setting `align-self` for slotted `<textarea>` overrides this line:
https://github.com/vaadin/web-components/blob/54decd0cc017ec15d717a063aba63a4c4ccc396a/packages/input-container/src/vaadin-input-container.js#L21
- Refactor
=> refactor: move base styles from themes to src

packages/field-base/src/shadow-focus-mixin.js, packages/field-base/test/shadow-focus-mixin.test.js
Fixes `vaadin-details` to only delegate focus to its summary element when moving the focus into the element using keyboard navigation. This solves issues like text selection or click events on details content not working, if the element is not already focused.
One concern here is that the fix is applied to `ShadowFocusMixin`, which is currently only used in `vaadin-details`. However someone might expect `ShadowFocusMixin` to work differently when applied to other components, in that it should always delegate the focus, regardless whether the `focusin` event was caused by clicks or keyboard. I'm open for adding an override of the relevant `_shouldSetFocus` method to `vaadin-details` itself, and only apply the fix there. Alternatively we could add some sort of option to `ShadowFocusMixin`, …
=> fix: do not delegate focus when clicking on non-focusable child

packages/field-base/test/shadow-focus-mixin.test.js
Fixes a flaky test in FF that was introduced by #3565 
Only targeting `master` and `23.0`, for 22 I added a separate commit here: https://github.com/vaadin/web-components/pull/3568/commits/c59a66b0ad701abd010cb87d9054b8bc17807b81
=> chore: fix flaky shadow focus mixin test

packages/grid/test/frozen-columns.test.js
This test was originally introduced by https://github.com/vaadin/vaadin-grid/pull/1731 and it concerns two internal methods that were used prior to Vaadin 22 for transforming sticky sections: `_updateScrollerMeasurements()` and `_translateStationaryElements()`. 
Both methods have been removed as part of #2396 which changed to use CSS custom property. As the lines where the error could potentially happen no longer exist, I would suggest to remove this test as obsolete.
- Test
=> test: cleanup obsolete frozen column test

packages/grid/src/vaadin-grid-scroll-mixin.js, packages/grid/src/vaadin-grid.d.ts, packages/grid/src/vaadin-grid.js, packages/grid/test/scrolling-mode.test.js, packages/grid/theme/lumo/vaadin-grid-styles.js
Updated logic for setting `overflow` on the host to match the behavior used by `vaadin-tabs`.
Fixes #3575
- Refactor
=> refactor: use RTL compatible overflow values

packages/field-base/src/shadow-focus-mixin.js, packages/field-base/test/shadow-focus-mixin.test.js
Fixes a small regression introduced by #3565, where the `focused` attribute would not be set anymore when clicking into the `vaadin-details` content. This is different the previous behavior and also diverges from other container elements like `vaadin-scroller`, which set the `focused` attribute when clicking into the content.
This also fixes an issue in `ShadowFocusMixin` where clicking on a non-focusable slotted element after the focus was on a focusable slotted element, would not restore the `focused` attribute, which is different to `vaadin-scroller` for example, which would always set `focused` regardless if the focus moved from another slotted element.
Apart from that several checks and constructs in the mixin were not necessary anymore, and were cleaned up.
=> fix: restore focused attribute behavior

packages/date-time-picker/src/vaadin-date-time-picker.js, packages/date-time-picker/test/basic.test.js
This issue resolves a failure discovered while reviewing https://github.com/vaadin/flow-components/pull/2887
Fixes https://github.com/vaadin/flow-components/issues/2899
The root cause of the change is how Polymer runs observers:
1. First, `vaadin-date-time-picker` runs `__themeChanged` for `theme` property (set by attribute)
2. Then, adding the slotted date-picker calls the observer once again (the time-picker is still empty)
3. Setting `theme` on the date-picker triggers its `_propertiesChanged` callback and `notify` effects
4. Then `value-changed` event is fired and `__valueChangedEventHandler` event listener is called
5. Finally, `__formattedValue` is called and it tries to access `__timePicker.value` which throws
In theory, the same issue could happen if we had any other complex …
=> fix: do not throw when setting theme attribute

packages/grid/src/vaadin-grid.js, packages/grid/test/keyboard-navigation.test.js
Fixes a workaround in Chrome for the cell-focus event, where a mouse up event outside of the grid could trigger a cell focus event from a cell. The fix involves checking if the mouse up event occured on the same cell as the mouse down event.
Fixes https://github.com/vaadin/flow-components/issues/2863
=> fix: do not dispatch cell-focus on mouse up outside of cell

packages/grid/src/vaadin-grid-column-resizing-mixin.js, packages/grid/test/column-resizing.test.js
Fixes #3588
1. Updated logic to check padding on `vaadin-grid-cell-content`
2. Replaced hardcoded `10` with the actual resize handle width
Normal column minimum width after resize (the resize handle uses `35px`).
Last column minimum width after resize (the resize handle uses `18px`).
We could probably hardcode `35` for performance and consistency 🙈 
- Bugfix
=> fix: improve resizing column min width logic

packages/notification/src/vaadin-notification.js, packages/notification/test/notification.test.js
Related to https://github.com/vaadin/flow-components/issues/2857
We'd like to add `HasStyle` to `Notification` so that users would be able to set classes on the `vaadin-notification` host element and then they would be propagated to the `vaadin-notification-card` element by the connector.
So we need to enforce `display: none` to ensure that setting CSS class on the host would not have any side effects.
- Refactor
=> refactor: enforce hiding notification host element

packages/confirm-dialog/src/vaadin-confirm-dialog.js, packages/confirm-dialog/test/confirm-dialog.test.js
Related to https://github.com/vaadin/flow-components/issues/2909
We'd like to fix `HasStyle` in `ConfirmDialog` so that users would be able to set classes on the host element and then they would be propagated to the `vaadin-confirm-dialog-overlay` element for styling.
So we need to enforce `display: none` to ensure that setting CSS class on the host would not have any side effects.
- Refactor
=> refactor: enforce hiding confirm dialog host element

packages/dialog/src/vaadin-dialog.js, packages/dialog/test/dialog.test.js
Related to https://github.com/vaadin/flow-components/issues/2856
We'd like to add `HasStyle` to `Dialog` so that users would be able to set classes on the host element and then they would be propagated to the `vaadin-dialog-overlay` element for styling.
So we need to enforce `display: none` to ensure that setting CSS class on the host would not have any side effects.
- Refactor
=> refactor: enforce hiding dialog host element

packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js, packages/grid/src/vaadin-grid-scroll-mixin.js, packages/grid/src/vaadin-grid-styles.js, packages/grid/test/keyboard-navigation.test.js
Fixes https://github.com/vaadin/flow-components/issues/2930
=> refactor: use inline style for cell transform

dev/custom-field.html, packages/button/theme/material/vaadin-button-styles.js
Removes a Firefox specific style rule for changing the vertical alignment of buttons using the Material theme by `-13px`. The style rule was introduced with the initial commit for the Material theme with no specific mentions of the Firefox-specific behavior: https://github.com/vaadin/vaadin-button/pull/90. It seems that this was a workaround that is not necessary anymore:
Before:
After:
=> fix: material button alignment in Firefox

packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/test/keyboard.test.js
Currently the combo box stops propagation of enter key events whenever a value is committed. That leads to several problematic cases when auto open is disabled:
- enter a predefined option -> hit enter
- enter a custom option -> hit enter
- empty input -> hit enter
I'd say in all of that cases the combo box should commit the value and then let the enter key event bubble up, just like regular inputs and all the other fields we have do. It seems the propagation logic was not properly considered before, and the current logic in `onEnter` just evolved to a state where committing the value, maybe closing the combo box, and stopping propagation are mixed up as the same thing.
This PR changes the `onEnter` behavior to only stop propagation if the combo box is currently opened. That way the enter …
=> fix: propagate enter key event when combo box is not opened

packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/test/external-filtering.test.js, packages/combo-box/test/internal-filtering.test.js, packages/time-picker/test/combo-box.test.js
Fixes the regression where it was not possible to commit a custom value to a time-picker / combo-box after a value from the dropdown has been set.
The regression originates from #3316.
Fixes #3590
=> fix: don't prevent custom values when autoOpenDisabled

packages/dialog/src/vaadin-dialog-resizable-mixin.js
Prevent any “corner bleed” of contained elements, such as headers and footers.
=> fix: prevent child elements being drawn outside dialog content area

packages/grid/test/scrolling-mode.test.js
Skips the flaky grid scrolling test for WebKit until further investigation within https://github.com/vaadin/web-components/issues/3538.
A follow-up to #3627
=> test: skip flaky grid scrolling mode test for WebKit

packages/button/src/vaadin-button.js
It turns out the button component specifies some CSS properties for the container that are just a repetition of the default ones and therefore can be dropped. I guess they came out of the a11y refactoring whose initial version was based on the native `<button>`.
A finding from #3612
=> refactor: clean up button container styles

packages/button/package.json, packages/button/src/vaadin-button-mixin.d.ts, packages/button/src/vaadin-button-mixin.js, packages/button/src/vaadin-button.d.ts, packages/button/src/vaadin-button.js, packages/select/package.json, packages/select/src/vaadin-select-value-button.js, packages/select/src/vaadin-select.js, packages/select/theme/lumo/vaadin-select-styles.js, packages/select/theme/lumo/vaadin-select.js, packages/select/theme/material/vaadin-select-styles.js, packages/select/theme/material/vaadin-select.js
Updated `vaadin-select-value-button` to use mixins instead of extending `vaadin-button` directly.
Fixes #3607
- Refactor
=> refactor: update select to not use button

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js, packages/multi-select-combo-box/test/basic.test.js
This PR makes it possible to select multiple items by pressing <kbd>Enter</kbd> without closing overlay.
In order to close the overlay from keyboard, <kbd>Esc</kbd> should be used. 
Fixes #3650
- Bugfix
=> refactor: keep overlay open when pressing Enter

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/multi-select-combo-box/test/basic.test.js
Fixes #3643
This PR introduces two improvements for `vaadin-multi-select-combo-box`:
1. Do not unselect item when typing it manually and pressing <kbd>Enter</kbd>
2. Set correct focused index after selecting item, and preserve it on deselecting.
https://user-images.githubusercontent.com/10589913/162208437-c463f308-69fa-42b9-95a0-90ec01a86bfb.mp4
- Refactor
=> refactor: improve selecting item with keyboard

packages/vaadin-lumo-styles/color.js
This allows the OS/browser to adjust the styles of native controls to better conform to the color schemed defined by Lumo. It is especially noticeable with scrollbars:
Before:
After:
=> feat: use CSS `color-scheme` property

packages/date-picker/test/common.js, packages/date-picker/test/keyboard-input.test.js, packages/date-picker/test/keyboard-navigation.test.js
It was discovered that sometimes `await sendKeys(...)` resolves after the `scroll-animation-finished` event is fired which results in date-picker test failures because they were written with the assumption that the event will be always fired before. 
The reason is likely related to the implementation of `sendKeys`. There is no guarantee that the returned promise will resolve exactly at the moment you expect. It can take longer under some circumstances.
This PR attempts to deal with such test failures by introducing a `waitForScrollToFinish` test helper that doesn't wait if the scroll has already finished.
Part of #3538
=> test: make keyboard tests more reliable

packages/dialog/src/vaadin-dialog.js, packages/dialog/test/dialog.test.js, packages/login/src/vaadin-login-overlay.js, packages/login/test/login-overlay.test.js
Restores overlay opened state when disconnecting and then reconnecting the element, for example when moving the element in the DOM. Applies to `vaadin-dialog` and `vaadin-login-overlay`.
Fixes https://github.com/vaadin/flow-components/issues/2979
Fixes https://github.com/vaadin/flow-components/issues/2087
Fixes https://github.com/vaadin/web-components/issues/2125
=> fix: restore overlay opened state when moving within the DOM

packages/dialog/theme/lumo/vaadin-dialog-styles.js
Lumo theme currently set `padding: 0` to `[part=header]` and `[part=footer]` when theme `no-padding` is used. Remove the styling, as it makes sense to only apply it to `[part=content]`.
=> refactor: only apply no-padding theme to dialog content

packages/charts/src/vaadin-chart.js, packages/charts/test/chart-properties.test.js
Make `vaadin-chart` respect the global Highcharts language setting for the no data message. Also fixes an issue where setting the chart-specific empty text lazily would show the no data element even if the chart has data.
Note that there are other issues related to this behavior:
- clearing the chart-specific empty text does not revert to using the global language setting, but uses an empty string instead. Tried some solutions to properly clear the chart-specific setting, but none worked. Might be a Highcharts issue.
- updating the global setting does not affect existing charts (that is probably expected behavior by Highcharts)
Fixes https://github.com/vaadin/flow-components/issues/3003
- Bugfix
=> fix: make charts respect global Highcharts no data message

packages/combo-box/src/vaadin-combo-box-mixin.js
The `_onClosed` method is only called in the observer, when `opened` is set to `false` so the check is redundant.
Previously, this method used to be called twice but that has been changed in https://github.com/vaadin/vaadin-combo-box/pull/799 
- Refactor
=> refactor: cleanup no longer used code

README.md
The PR clarifies the list of supported browsers in `README.md` based on [the corresponding list](https://github.com/vaadin/platform/blob/93d83da0c9ce101ddb570cc1a631bc36d8f740d2/scripts/generator/templates/template-release-notes.md?plain=1#L61-L78) from platform releases.
Fixes #319
=> chore: clarify the list of supported browsers in README.md

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/multi-select-combo-box/test/basic.test.js
The issue with not clearing the input was coming from the fact that by default, `clear()` method only sets 'value' to empty string. However, it was already empty for an internal combo-box, so the observer to reset input value wasn't triggered.
Updated to manually set `inputElement.value` to empty string. Also, added logic to reset `filter` property, so that the component shows all the items after clicking / pressing <kbd>Enter</kbd> on the matching item in the dropdown.
Fixes #3644
- Bugfix
=> fix: clear filter when clicking matching value

packages/input-container/theme/lumo/vaadin-input-container-styles.js
Added missing style to `vaadin-input-container` Lumo theme to fix regression in Vaadin 22+
Fixes #3622
- Bugfix
=> fix: restore missing RTL pseudo element style

packages/time-picker/src/vaadin-time-picker-combo-box.js
This code was introduced in https://github.com/vaadin/web-components/pull/2618 and appears to be a copy-paste from `vaadin-combo-box-light` component.
The `_onChange` override is not needed because the clear button click is handled in `ComboBoxMixin`:
https://github.com/vaadin/web-components/blob/9b9fa8a6e26d6154cb06b27c1ddd3bda6e21e1df/packages/combo-box/src/vaadin-combo-box-mixin.js#L416-L418
Also `_isClearButton()` override isn't needed because in case of time-picker we can be sure that `clearElement` exists by the time when the component is initialised, and `this.querySelector('[part="clear-button"]')` returns a reference to it.
- Refactor
=> refactor: remove unused code from time-picker

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js
Same as #3690 but for `vaadin-multi-select-combo-box` which contains same copy-paste code.
- Refactor
=> refactor: cleanup not necessary method overrides

packages/menu-bar/test/not-animated-styles.js
It turned out that there was a box-shadow animation of menu-bar buttons in the Material theme that wasn't disabled in visual tests which resulted in their instability. The PR disables that animation.
Note, during the animation, the browser may allocate the involved elements to separate layers for optimization purposes, which in turn may affect the font rendering making the test flaky.
Part of #3538
=> test: disable buttons animation in visual tests

yarn.lock
Corrects a mistake in `yarn.lock` that occurred because I forgot to run `yarn install` after manually changing the sinon version from `13.0.2` to `^13.0.2`.
A follow-up to #3699
=> chore: update yarn lock after bumping sinon

packages/form-layout/src/vaadin-form-item.js, packages/form-layout/test/form-item.test.js
Fixes https://github.com/vaadin/web-components/issues/3682
=> fix: enable using custom id for form-item label

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-container.js
This element is only used to have a wrapper around chips and the input, and not intended to be used for theming.
Therefore we should not use `part` attribute for it, and use `class` instead to indicate it is internal.
- Refactor
=> refactor: do not set part on the internal wrapper

packages/vaadin-themable-mixin/test/lit-setup.js, packages/vaadin-themable-mixin/test/themable-mixin.test.js, packages/vaadin-themable-mixin/vaadin-themable-mixin.js
Fixes https://github.com/vaadin/web-components/issues/3616
=> fix: inherit parent styles to extensions without is getter

packages/charts/src/vaadin-chart.js, packages/charts/test/turbo-mode.test.js
Shows a warning when one or more series contain more data items than the turbo threshold configured in the chart, or series, plot options. The turbo mode is a Highcharts feature, and not something that is implemented in our logic, as such it is not straightforward to detect. We basically want this warning when:
- initializing with a series with more items than the configured threshold
- adding a series with more items than the configured threshold
- adding more items to a series, which then exceeds the configured threshold
Apart from that the Flow component also uses the Highcharts API directly, so it was not possible to add the check to existing methods that cover the above cases. Instead I listen for the chart's redraw event, which should be triggered everytime the chart's data is …
=> feat: show warning when engaging turbo mode in development mode

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-scroller.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/multi-select-combo-box/test/basic.test.js, packages/multi-select-combo-box/theme/lumo/vaadin-multi-select-combo-box-chip-styles.js, packages/multi-select-combo-box/theme/lumo/vaadin-multi-select-combo-box-styles.js, packages/multi-select-combo-box/theme/material/vaadin-multi-select-combo-box-chip-styles.js, packages/multi-select-combo-box/theme/material/vaadin-multi-select-combo-box-styles.js
As discussed internally, the dropdown should be also available when readonly, so user can see all the selected items.
In this case, interacting with the items isn't possible: you can't un-select them with keyboard or mouse click.
- Feature
=> feat: show dropdown with selected items when readonly

packages/component-base/src/dir-mixin.js, packages/component-base/test/dir-mixin.test.js
The only addition is `converter` for `dir` property that replicates the behavior of the overridden Polymer methods:
- `_attributeToProperty` -> `fromAttribute`
- `_valueToNodeAttribute` - `toAttriubute`
=> feat: add LitElement support to DirMixin

packages/component-base/src/async.d.ts, packages/component-base/src/debounce.d.ts
Added missing typings for `async.js` and `debounce.js` modules, so they can be used with TS. 
=> chore: add typings for async and debounce

packages/combo-box/test/internal-filtering.test.js, packages/combo-box/test/item-template.test.js, packages/combo-box/test/lazy-loading.test.js, packages/combo-box/test/selecting-items.test.js, packages/crud/test/helpers.js, packages/grid-pro/test/helpers.js, packages/grid/test/column-group.test.js, packages/grid/test/column-reordering.test.js, packages/grid/test/column-resizing.test.js, packages/grid/test/filtering.test.js, packages/grid/test/helpers.js
Removed no longer necessary calls for `flush()` as tests for combo-box and grid pass without them.
This makes sense as we now have our own copy of `debounce` and no longer support ShadyDOM.
- Test
=> test: remove no longer needed Polymer flush

packages/vaadin-themable-mixin/vaadin-themable-mixin.js
Addresses https://github.com/vaadin/web-components/issues/401#issuecomment-1106332369
The current code in ThemableMixin wouldn't pass the `!template` check [here](https://github.com/vaadin/web-components/blob/7ed1bda135dfe08a49cca552d329d2bbe1e767c4/packages/vaadin-themable-mixin/vaadin-themable-mixin.js#L208) anyway, but it's better to add an explicit check to avoid regressions in case the logic is changed in the future.
=> chore: avoid running PolymerElement specific code with LitElement

packages/date-picker/src/vaadin-date-picker.js
Restores `@mixes DatePickerMixin` on `vaadin-date-picker`. I think this was accidentally removed in https://github.com/vaadin/web-components/pull/2632
=> docs: restore missing DatePickerMixin

packages/combo-box/test/keyboard.test.js, packages/combo-box/test/lazy-loading.test.js, packages/combo-box/test/overlay-position.test.js, packages/combo-box/test/selecting-items.test.js
Did some cleanup to use `setInputValue()` helper instead of duplicating `filter()` helper functions in tests.
- Tests
=> test: update combo-box test to use helpers

packages/grid/src/vaadin-grid.js
This workaround was needed for iOS 10.
The  -webkit-overflow-scrolling is not supported after iOS 12. Vaadin 23 does not support these old versions, thus this setting is not needed anymore.
Furthermore, programmatic setting is prone to timing glitches.
Fixes https://github.com/vaadin/flow-components/issues/3037
=> fix: Remove -webkit-overflow-scrolling style setting

packages/time-picker/src/vaadin-time-picker.d.ts
=> fix: update type definition for i18n formatTime

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js
This style was added before adding support for `title` attributes (#3632) and `readonly` dropdown (#3686).
We should remove it now, to make it possible for users to see tooltips also when component is readonly.
- Bugfix
=> fix: do not disable pointer-events when readonly

packages/multi-select-combo-box/theme/lumo/vaadin-multi-select-combo-box-styles.js, packages/multi-select-combo-box/theme/material/vaadin-multi-select-combo-box-styles.js
Using `opacity` makes chips look a bit faint, especially with Material. 
Also, It's not really needed as we hide "remove" button anyway.
Here is how the component would look like with this change:
- Refactor
=> refactor: do not change readonly chips opacity

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/multi-select-combo-box/theme/lumo/vaadin-multi-select-combo-box-chip-styles.js, packages/multi-select-combo-box/theme/material/vaadin-multi-select-combo-box-chip-styles.js, packages/multi-select-combo-box/theme/material/vaadin-multi-select-combo-box-styles.js
Current min-width `4em` makes the chip look weird:
Updated to use `3em` which looks slightly better.
- Refactor
=> refactor: use smaller chip min-width for Material

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/multi-select-combo-box/test/basic.test.js
Updated the component to not run `validate()` on focusout when readonly.
Fixes #3750
- Bugfix
=> fix: do not mark as invalid when readonly

packages/grid-pro/theme/lumo/vaadin-grid-pro-styles.js, packages/grid-pro/theme/material/vaadin-grid-pro-styles.js
Fixes editable cell styles to use an opaque background on hover / focus, which prevents underlying cells from bleeding into the foreground.
The fix is based on the suggestion by Jouni here: https://github.com/vaadin/flow-components/issues/2365#issuecomment-1111155072
Fixes https://github.com/vaadin/flow-components/issues/2365
Lumo theme:
https://user-images.githubusercontent.com/357820/165781083-17871ede-3bdd-4c94-b684-dacc15f32d65.mp4
Lumo with `highlight-editable-cells` theme variant:
https://user-images.githubusercontent.com/357820/165780414-85499b44-beae-4d33-b4cc-77a6e32994c3.mp4
Material theme:
https://user-images.githubusercontent.com/357820/165781385-71d674a7-1785-460a-9de0-bec9ffb9c8c6.mp4
- Bugfix
=> fix: use solid background for editable cells

packages/dialog/src/vaadin-dialog.js, packages/dialog/test/header-footer.test.js
- Make header-title set `aria-label` instead of using `aria-labelleby` as it seems that Chrome + VoiceOver is not capable of announce the later.
- Make sure that the `aria-label` property set on the dialog is set in case both `aria-label` and `header-title` are defined.
- Change the markup of the resize container from `<div>` to `<section>`.
Fixes #3702
=> fix: make header-title be announced by screen readers

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-scroller.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.d.ts, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/multi-select-combo-box/test/accessibility.test.js, packages/multi-select-combo-box/test/basic.test.js, packages/multi-select-combo-box/test/typings/multi-select-combo-box.types.ts
1. Updated logic to set `aria-selected="true"` on selected items, and not on the focused item like in regular combo-box.
2. Added `aria-multiselectable="true"` on the scroller which has `role="listbox"` to indicate multi-selection support.
3. Added `i18n` and used `announce()` helper to announce selecting items - inspired by `<select multiple>`, see below:
Fixes #3711
- Feature
=> feat: add screen reader announcements support

packages/dialog/package.json
Added `lit.js` and `lit.d.ts` entrypoints to `files` of the dialog component `package.json`.
A follow-up to #3755
=> fix: add lit entrypoints to package.json

packages/dialog/test/typings/lit.types.ts
A minor improvement of the dialog Lit directives TS tests to make them also verify that directive classes are exported.
A follow-up to #3755
=> test: add TS tests making sure that Lit directive classes are exported

packages/combo-box/lit.d.ts, packages/combo-box/lit.js, packages/combo-box/package.json, packages/combo-box/src/lit/renderer-directives.d.ts, packages/combo-box/src/lit/renderer-directives.js, packages/combo-box/test/lit-renderer-directives.test.js, packages/combo-box/test/typings/lit.types.ts
This PR implements a Lit renderer directive for the `renderer` property of the combo-box component in order to provide a better DX for Lit users.
Part of #266
```diff
import { comboBoxRenderer } from '@vaadin/combo-box/lit.js';
<vaadin-combo-box
-  .renderer="${(root, model, column) => render(html`...`, root, { eventContext: this })}"
+  ${comboBoxRenderer((item, model, column) => html`...`)}
></vaadin-combo-box>
```
=> feat: add Lit renderer directive for combo-box

packages/grid/lit.d.ts, packages/grid/lit.js, packages/grid/package.json, packages/grid/src/lit/column-renderer-directives.d.ts, packages/grid/src/lit/column-renderer-directives.js, packages/grid/src/lit/renderer-directives.d.ts, packages/grid/src/lit/renderer-directives.js, packages/grid/test/lit-renderer-directives.test.js, packages/grid/test/typings/lit-renderer-directives.types.ts
This PR implements a Lit renderer directive for each renderer property of the grid component in order to provide a better DX for Lit users.
Part of #266
```diff
import { columnBodyRenderer } from '@vaadin/grid/lit.js';
<vaadin-grid-column
-  .renderer="${(root, model, column) => render(html`...`, root, { eventContext: this })}"
+  ${columnBodyRenderer((item, model, column) => html`...`)}
></vaadin-grid-column>
```
```diff
import { columnHeaderRenderer } from '@vaadin/grid/lit.js';
<vaadin-grid-column
-  .headerRenderer="${(root, column) => render(html`...`, root, { eventContext: this })}"
+  ${columnHeaderRenderer((column) => html`...`)}
></vaadin-grid-column>
```
```diff
import { columnFooterRenderer } from '@vaadin/grid/lit.js';
<vaadin-grid-column
-  .footerRenderer="${(root, column) …
```
=> feat: add Lit renderer directives for grid

packages/context-menu/lit.d.ts, packages/context-menu/lit.js, packages/context-menu/package.json, packages/context-menu/src/lit/renderer-directives.d.ts, packages/context-menu/src/lit/renderer-directives.js, packages/context-menu/test/lit-renderer-directives.test.js, packages/context-menu/test/typings/lit.types.ts
This PR implements a Lit renderer directive for the `renderer` property of the context-menu component in order to provide a better DX for Lit users.
Part of #266
```diff
import { contextMenuRenderer } from '@vaadin/context-menu/lit.js';
<vaadin-context-menu
-  .renderer="${(root, menu, context) => render(html`...`, root, { eventContext: this })}"
+  ${contextMenuRenderer((context, menu) => html`...`)}
></vaadin-context-menu>
```
=> feat: add Lit renderer directive for context-menu

packages/notification/lit.d.ts, packages/notification/lit.js, packages/notification/package.json, packages/notification/src/lit/renderer-directives.d.ts, packages/notification/src/lit/renderer-directives.js, packages/notification/test/lit-renderer-directives.test.js, packages/notification/test/typings/lit.types.ts
This PR implements a Lit renderer directive for the `renderer` property of the notification component in order to provide a better DX for Lit users.
Part of #266
```diff
import { notifitionRenderer } from '@vaadin/notification/lit.js';
<vaadin-notification
-  .renderer="${(root, notification) => render(html`...`, root, { eventContext: this })}"
+  ${notificationRenderer((notification) => html`...`)}
></vaadin-notification>
```
=> feat: add Lit renderer directive for notification

packages/select/lit.d.ts, packages/select/lit.js, packages/select/package.json, packages/select/src/lit/renderer-directives.d.ts, packages/select/src/lit/renderer-directives.js, packages/select/test/lit-renderer-directives.test.js, packages/select/test/typings/lit.types.ts
This PR implements a Lit renderer directive for the `renderer` property of the select component in order to provide a better DX for Lit users.
Part of #266
```diff
import { selectRenderer } from '@vaadin/select/lit.js';
<vaadin-select
-  .renderer="${(root, select) => render(html`...`, root, { eventContext: this })}"
+  ${selectRenderer((select) => html`...`)}
></vaadin-select>
```
=> feat: add Lit renderer directive for select

packages/multi-select-combo-box/theme/lumo/vaadin-multi-select-combo-box-styles.js, packages/multi-select-combo-box/theme/material/vaadin-multi-select-combo-box-styles.js
Currently, `<vaadin-multi-select-combo-box>` uses the following styles to hide placeholder text when value is set:
https://github.com/vaadin/web-components/blob/dbf014832da46cb617d027276158ffc7098fa833/packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js#L34-L36
This is especially useful because placeholder in this case is used for screen reader announcement of selected items.
However, this currently causes the problem of making the cursor caret hidden when focusing empty input.
This PR adds the styles for enforcing `caret-color` to Lumo and Material, to make the caret visible again.
- Bugfix
=> fix: do not hide caret when input is empty

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.d.ts, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/multi-select-combo-box/test/accessibility.test.js
This is a fix for the problem introduced in #3740: the temporary a11y placeholder used for screen readers wasn't reset.
Added the observer for `placeholder` property that contains a following logic:
1. Store user-defined placeholder in a private property and re-apply it when all the selected items are removed,
2. Override user-defined placeholder changed while selected items are set with temporary a11y placeholder.
- Bugfix
=> fix: set correct placeholder when removing items

packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/test/external-filtering.test.js
Fixes https://github.com/vaadin/flow-components/issues/3115
Previously, the component accepted `selectedItem` set before `filteredItems` but did not set focused index correctly.
This turned out to be the case with the Flow component where the logic makes property observers run in this order:
Note: setting `filteredItems` to an array of `ComboBoxPlaceholder` and then updating them later is how the ComboBox connector works, it's not important for this particular issue, only the order of the property observers matters.
- Bugfix
=> fix: focus selected item set before filtered items

packages/grid-pro/lit.d.ts, packages/grid-pro/lit.js, packages/grid-pro/package.json, packages/grid-pro/src/lit/column-renderer-directives.d.ts, packages/grid-pro/src/lit/column-renderer-directives.js, packages/grid-pro/test/lit-renderer-directives.test.js, packages/grid-pro/test/typings/lit-renderer-directives.types.ts
This PR implements a Lit renderer directive for each `editModeRenderer` property of the grid component in order to provide a better DX for Lit users.
Part of #266
```diff
import { columnEditModeRenderer } from '@vaadin/grid-pro/lit.js';
<vaadin-grid-pro-edit-column
-  .editModeRenderer="${(root, model, column) => render(html`...`, root, { eventContext: this })}"
+  ${columnEditModeRenderer((item, model, column) => html`...`)}
></vaadin-grid-pro-edit-column>
```
=> feat: add Lit renderer directive for grid-pro

packages/grid/src/vaadin-grid-styling-mixin.js, packages/grid/test/class-name-generator.test.js
The PR prevents the grid css class name generator from running on the rows that the data provider is still loading. That way [the Flow Grid class name generator](https://github.com/vaadin/flow-components/blob/52ddb8202580c9c9cd545e3e519174a589cffbab/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js#L1141-L1147) does no longer receive the cells that don't have `_item` assigned yet and thus the original error reported in the issue no longer takes place:
```
Cannot read properties of undefined (reading 'style')
```
**Scenario**: When a column group changes its hidden state, it triggers the cells' class names to re-generate. When that coincides with the data provider loading more rows, there may occur a race condition because of using …
=> fix: run the class name generator only for loaded rows

packages/field-base/test/delegate-state-mixin.test.js, packages/field-base/test/helpers.js, packages/field-base/test/input-constraints-mixin.test.js, packages/field-base/test/input-mixin.test.js, packages/field-base/test/pattern-mixin.test.js, packages/field-base/test/validate-mixin.test.js
Updated some of the `field-base` mixins to run tests for both Polymer and LitElement:
- `DelegateStateMixin`
- `InputConstraintsMixin`
- `InputMixin`
- `PatternMixin`
- `ValidateMixin`
- Tests
=> test: add LitElement tests for input mixins

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/multi-select-combo-box/test/basic.test.js
Added logic to clear selected items on <kbd>Esc</kbd> to align with the regular combo-box.
Fixes #3788
- Bugfix
=> fix: clear on Esc if clear button is visible

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js, packages/multi-select-combo-box/test/basic.test.js
Fixes #3787
Updated internal `focusout` listener to prevent dispatching extra `change` event for a dropdown item that matches `_focusedIndex` - currently, this extra event causes the previously selected item to be incorrectly unseleted.
Note, this PR does not cover #3645: custom values are handled differently and `custom-value-set` still fires on focusout.
- Bugfix
=> fix: do not unselect committed item on focusout

packages/grid-pro/src/lit/column-renderer-directives.d.ts, packages/grid-pro/src/lit/column-renderer-directives.js
The license headers were incorrectly copied from elsewhere. Updated them to use CVDL as in `vaadin-grid-pro`.
=> chore: update license for grid-pro renderer

packages/menu-bar/src/vaadin-menu-bar-buttons-mixin.js
The original issue contains an edge case where `container.offsetWidth` is `39` and `container.scrollWidth` is `40`: this only happens with certain customizations, see https://github.com/vaadin/flow-components/issues/2810#issuecomment-1060637732. I'm not sure if we should test that.
However, it still makes sense to make this logic more clear by ensuring `_hasOverflow` is only set to `true` when the count of the items in the overflow sub-menu is greater than `0`. This PR makes it explicit by adding another private method.
Fixes https://github.com/vaadin/flow-components/issues/2810
- Refactor
=> refactor: extract method for updating overflow

packages/board/package.json, packages/charts/package.json, packages/confirm-dialog/package.json, packages/cookie-consent/package.json, packages/crud/package.json, packages/grid-pro/package.json, packages/map/package.json, packages/rich-text-editor/package.json, packages/vaadin-board/package.json, packages/vaadin-charts/package.json, packages/vaadin-confirm-dialog/package.json, packages/vaadin-cookie-consent/package.json, packages/vaadin-crud/package.json, packages/vaadin-grid-pro/package.json, packages/vaadin-rich-text-editor/package.json
The PR adds `cvdlName` to `package.json` for every Vaadin pro component. This is needed for the new Flow license checker to be able to check the license at the project's build time.
Part of #3773
=> chore: add a cvdlName field to package.json of pro components

packages/board/src/vaadin-board.js, packages/charts/src/vaadin-chart.js, packages/confirm-dialog/src/vaadin-confirm-dialog.js, packages/cookie-consent/src/vaadin-cookie-consent.js, packages/crud/src/vaadin-crud.js, packages/grid-pro/src/vaadin-grid-pro.js, packages/map/src/vaadin-map.js, packages/rich-text-editor/src/vaadin-rich-text-editor.js
The PR adds a `cvdlName` getter to every Vaadin pro component. The getter will be used in license checking. 
Note, I haven't dropped the logic in `_finalizeClass` related to the old way of license checking. We can only do that after the new license checker is off the feature flag.
Fixes #3773
=> chore: add a cvdlName getter to pro components

packages/component-base/src/resize-mixin.d.ts, packages/component-base/src/resize-mixin.js, packages/component-base/test/resize-mixin.test.js
Added option to observe parent element resize to `ResizeMixin` - see #3824
Note: this isn't marked as `feat:` to make backporting possible.
=> refactor: add option to observe parent resize

packages/menu-bar/src/vaadin-menu-bar-buttons-mixin.js, packages/menu-bar/test/menu-bar.test.js
Added `ResizeObserver` for the menu-bar parent to detect cases when its width increases.
Note, this does not cover the following case described in the original issue:
> Changing of the content -> Update view title to be longer (e.g. upon navigation), MenuBar overflow is created, update title to be shorter overflow is not being updated.
Fixes #3739
- Bugfix
=> fix: observe parent resize to detect overflow

packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js, packages/grid/test/keyboard-navigation.test.js
When setting `tabindex` attribute on `vaadin-grid`, pressing <kbd>Shift</kbd> + <kbd>Tab</kbd> on it throws an error.
This is due to the fact that `_predictFocusStepTarget()` method returns `undefined` in this case.
Added a check for `undefined` value to not throw and not call `preventDefault()` so that native keyboard focus works.
Fixes https://github.com/vaadin/flow-components/issues/2181
- Bugfix
=> fix: do not throw on Tab if grid has tabindex

dev/multi-select-combo-box.html, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.d.ts, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/multi-select-combo-box/test/basic.test.js, packages/multi-select-combo-box/test/typings/multi-select-combo-box.types.ts, packages/multi-select-combo-box/test/visual/lumo/multi-select-combo-box.test.js, packages/multi-select-combo-box/test/visual/material/multi-select-combo-box.test.js
1. Updated `vaadin-multi-select-combo-box` to use same property / event for custom values as `vaadin-combo-box`.
2. Added `stopPropagation()` for the original `custom-value-set` event to ensure it can't mess up the users logic
- Refactor
=> refactor!: align custom value property and event

packages/icons/iconset.js, packages/vaadin-lumo-styles/iconset.js
Added deprecation warnings to the files that import and use legacy `<iron-iconset-svg>` element.
Fixes #3504
=> chore: add deprecation warnings for iron-iconset

packages/component-base/src/virtualizer-iron-list-adapter.js, packages/component-base/test/virtualizer-scrolling.test.js
Follow-up for #3843
To be on the safe side, also update `_physicalTop` and `_physicalStart` alongside `_virtualStart` [as done in `_render()`](https://github.com/vaadin/web-components/blob/d736621117d022ef276f9241526862f42980609e/packages/component-base/src/iron-list-core.js#L537-L539)
=> chore: make sure iron-list internal properties are in sync

packages/grid/src/lit/column-renderer-directives.js
Added missing extensions which break some tools, e.g. `webpack` 5 logs the following error:
```
Module not found: Error: Can't resolve '@vaadin/component-base/src/debounce' in '/Users/serhii/cf/ts-vaadin-examples/node_modules/@vaadin/grid/src/lit'
Did you mean 'debounce.js'?
BREAKING CHANGE: The request '@vaadin/component-base/src/debounce' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
resolve '@vaadin/component-base/src/debounce' in …
```
=> fix: add missing .js extensions to imports

packages/grid/src/vaadin-grid-selection-mixin.js
Maintain a Set containing the selected item ids to speed up isSelected queries
Fixes #3844
I'm afraid my JS skills are incredibly rusty and I have no experience with Polymer at all, so this may be completely incorrect. My intention with this PR was to get a discussion going if this approach made sense. Consider it a first draft of a suggested possible fix.
The idea here is that the selection mixin maintains a Set of the selected item ids alongside the existing selectedItems array. Lookups in a Set are typically `O(1)` instead of `O(n)` (depends on the exact implementation of course) which makes a significant difference when many items are selected.
=> refactor: Improve performance of SelectionMixinClass#isSelected

packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/src/vaadin-combo-box-scroller.js, packages/combo-box/test/lazy-loading.test.js
The previous fix (#3855) was incorrect as it did not set `_focusedIndex` for user's filter while loading.
As a result, the item loaded while user was typing did not get highlighted, causing Flow ITs to fail.
This change addresses the original issue in a less intrusive way: while `_focusedIndex` is still updated,
we now check if `loading` is true and only scroll to the focused index in case if loading has completed.
- Bugfix
=> fix: set focused index but not scroll into view

packages/component-base/src/iron-list-core.js, packages/component-base/src/virtualizer-iron-list-adapter.js
Follow up for https://github.com/vaadin/web-components/pull/321#discussion_r627206096
Remove `grid` mode specific code from iron-list-core.
=> chore: cleanup iron-list-core of grid mode

packages/grid/src/vaadin-grid-data-provider-mixin.js, packages/grid/src/vaadin-grid-selection-mixin.js
__selectedKeys and __expandedKeys are updated using observers. If other observers keyed on the same properties are triggered before the cache update observers, then those first observers may read stale values when calling _isSelected or _isExpanded.
Fixes #3844
=> refactor: update cached keys to use computed properties

packages/date-picker/src/vaadin-date-picker-light.js, packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/src/vaadin-date-picker-overlay-content.js, packages/date-picker/src/vaadin-date-picker.js
1. Updated logic to use single `date-tap` listener instead of two separate listeners
2. Removed obsolete `slot="dropdown-content"` leftovers from [`iron-dropdown`](https://github.com/PolymerElements/iron-dropdown/blob/daa603c091cd432a15cb999a6005fdf9dfdec73a/iron-dropdown.js#L37) 
3. Moved setting `role="dialog"` to the overlay content element itself in `ready()`
- Refactor
=> refactor: cleanup date-picker overlay content logic

packages/vaadin-overlay/src/vaadin-overlay.js, packages/vaadin-overlay/test/focus-trap.test.js
Current logic is wrong: the `focusTrap` is not checked when closing, so focus can be incorrectly released.
Related to #3881 where we can see how closing date-picker inside a dialog releases focus from it.
- Bugfix
=> fix: only release focus if focus-trap is set

packages/vaadin-overlay/src/vaadin-overlay.js, packages/vaadin-overlay/test/focus-trap.test.js
Cherry-pick of #3882 to `23.0` branch.
The automated cherry-pick failed due to `describe` change to use arrow function.
- Cherry-pick
=> fix: only release focus if overlay focus-trap is set (#3882) (CP: 23.0)

packages/field-base/src/input-control-mixin.js, packages/field-base/test/input-control-mixin.test.js
See https://github.com/vaadin/web-components/pull/3872#discussion_r876794175
Note: the `vaadin-combo-box` that has custom logic for clear button already uses `stopPropagation()`:
https://github.com/vaadin/web-components/blob/d19635afe89c647a260ecbe39c157fedadfbde25/packages/combo-box/src/vaadin-combo-box-mixin.js#L633-L636
- Bugfix
=> fix: call stopPropagation() when clearing on Esc

packages/avatar-group/theme/lumo/vaadin-avatar-group.js, packages/avatar-group/theme/material/vaadin-avatar-group.js, packages/combo-box/theme/material/vaadin-combo-box-dropdown-styles.js, packages/context-menu/theme/lumo/vaadin-context-menu.js, packages/context-menu/theme/material/vaadin-context-menu.js, packages/date-picker/theme/lumo/vaadin-date-picker-overlay-styles.js, packages/date-picker/theme/material/vaadin-date-picker-overlay-styles.js, packages/dialog/theme/lumo/vaadin-dialog.js, packages/dialog/theme/material/vaadin-dialog.js, packages/field-highlighter/theme/lumo/vaadin-user-tags.js, packages/field-highlighter/theme/material/vaadin-user-tags.js, packages/select/theme/lumo/vaadin-select.js, packages/select/theme/material/vaadin-select.js
Add missing imports of `@vaadin/vaadin-overlay/theme/[themename]/vaadin-overlay.js` to components with overlay extensions:
- Avatar group
- ComboBox (material only)
- Context menu
- Datepicker
- Dialog
- User-tags
- Select
Fixes #3887
=> fix: import themed overlay with themed extensions

packages/combo-box/src/vaadin-combo-box-data-provider-mixin.js, packages/combo-box/test/dropdown.test.js, packages/combo-box/test/lazy-loading.test.js
Due to how observers in the combo box dropdown are set up, the dropdown toggles its opened state whenever the filter, or the value is changed. To determine its opened state, the dropdown basically checks whether the combo box has any items or if it is loading. The problem is that the refresh logic in the data provider mixin clears the items before setting a loading state, and afterwards enables the loading state, which causes the dropdown to briefly close, before being opened again. This causes some noticable flickering while typing a filter. This also causes side-effects, such as https://github.com/vaadin/web-components/issues/3875.
This fix introduces a `_refreshData` method to the data provider mixin, that is called whenever the data should be cleared, and then possibly reloaded. The …
=> fix: prevent toggling overlay opened state when filtering

packages/date-picker/src/vaadin-date-picker-overlay-content.js
There is a code in the overlay content that accesses the `vaadin-date-picker-overlay` and sets `opened` to `false`.
This is not needed because the following `close` event will do it by using the `_close` method:
https://github.com/vaadin/web-components/blob/ddb628d61064147ecfbbbbf8e8490b46e89857c7/packages/date-picker/src/vaadin-date-picker-mixin.js#L488
https://github.com/vaadin/web-components/blob/ddb628d61064147ecfbbbbf8e8490b46e89857c7/packages/date-picker/src/vaadin-date-picker-mixin.js#L572-L578
- Refactor
=> refactor: remove obsolete overlay content code

packages/component-base/src/virtualizer-iron-list-adapter.js, packages/component-base/test/virtualizer-item-height.test.js
Part of https://github.com/vaadin/flow-components/issues/3206
If a virtualizer child element has a height of 0 after an update, currently the Virtualizer would set `min-height: 200px` for it to avoid `iron-list-core` from generating an unlimited amount of elements while trying to cover the viewport.
The problem with `min-height` is that once the element content gets changed asynchronously (in the case of `<flow-component-renderer>` when the content component gets loaded and appended), the effective height of the element would not change (it would still remain 200 pixels high) and internal resizing logic would not invoke.
This PR changes the Virtualizer to use `padding-top` instead of `min-height` for the placeholder size so that once the content updates, the element's effective height …
=> fix: make virtualizer react to asynchronous item size increase

packages/combo-box/test/dynamic-size.test.js, packages/component-base/src/virtualizer-iron-list-adapter.js, packages/component-base/test/virtualizer-item-height.test.js, packages/component-base/test/virtualizer-reorder-elements.test.js
Part of https://github.com/vaadin/flow-components/issues/3206
Using the static value of `200px` for the placeholder height doesn't play well when the actual item height is much smaller.
_Note: this is only an issue in the rare cases where the items have the intrinsic height of 0 after an update and then asynchronously increase in height._
This PR updates Virtualizer to dynamically update the placeholder height to be the average of the 10 previous actual item heights. Having the placeholder height be as close as possible to the actual item heights results in much nicer scrolling UX:
Static placholder height (of 200px):
https://user-images.githubusercontent.com/1222264/169641179-3c4fd9a6-3a83-4d9e-8ead-857c0c9c6f5c.mp4
Dynamic placeholder height: …
=> refactor: make virtualizer use dynamic placeholder height

packages/vaadin-overlay/src/vaadin-overlay.js, packages/vaadin-overlay/test/multiple.test.js
Updated the logic to also add `keydown` listener for modeless overlays, to allow closing them on <kbd>Esc</kbd> key.
Note, this can't be backported to V22 as is, because there we also use the same event listener for focus trap logic.
Fixes #867
- Bugfix
=> fix: allow modeless overlay to close on Esc

README.md
The previous wording in the "Integration Tests" section was a bit confusing as it could be interpreted as you need to run `yarn test:it` in the `integrations` folder which is not right. All the commands should be run in the root directory.
=> chore: improve integration tests section in README.md

packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/test/basic.test.js
This PR updates the "fullscreen" mode logic that is no longer relevant after #3372 was implemented.
The `overlayContent` element itself can't be focused now, so calling `.focus()` does nothing and `focus` event does not work anymore. I missed to address this in the original PR so this was unnoticed until today 😕 
- Refactor
=> fix: update incorrect fullscreen mode focus logic

packages/date-picker/src/vaadin-date-picker-overlay-content.js, packages/date-picker/test/basic.test.js
This is a fix for a regression introduced in #3872 which made it not possible to close date-picker on <kbd>Esc</kbd> when in fullscreen mode. Note, this logic can be probably removed in the future as part of #3918
- Bugfix
=> fix: do not stop propagation of Esc when fullscreen

integration/tests/dialog-date-picker.test.js, packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/src/vaadin-date-picker-overlay-content.js, packages/date-picker/test/keyboard-input.test.js
Added back logic related to calling `event.stopPropagation()` for <kbd>Tab</kbd> that was present in Vaadin 22.
Fixes #3881
- Bugfix
=> fix: make Tab navigation work inside a dialog

packages/context-menu/src/vaadin-contextmenu-items-mixin.js, packages/context-menu/test/items.test.js
Aligned `vaadin-context-menu` behavior with `vaadin-select` that has logic to close on overlay <kbd>Tab</kbd>:
https://github.com/vaadin/web-components/blob/e2d1c472aa0c5a58738cdc896fa97c6548b111e0/packages/select/src/vaadin-select.js#L520-L522
Here is a video illustrating how the context-menu closes and moves focus to the `<vaadin-button>` on <kbd>Tab</kbd>:
https://user-images.githubusercontent.com/10589913/170043037-8991151a-ed85-4f34-b827-affa02ba2dd6.mp4
Fixes https://github.com/vaadin/flow-components/issues/3221
- Bugfix
=> fix: close all menus when pressing Tab

packages/date-picker/src/vaadin-date-picker-light.js, packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/src/vaadin-date-picker.js, packages/date-picker/test/custom-input.test.js
The `vaadin-date-picker-light` is currently quite broken because the `_initOverlay()` does not get called for it.
This is due to the fact that we set `_overlayInitialized` to `true` so the logic in the observer is not executed - see the original issue for an explanation. I also had to update the method `_initOverlay()` for now to make it protected.
Note, this is supposed to be eventually changed in #3904 after we remove the usage of `disable-upgrade` hack.
However, that change affects the DOM structure so it will be only available in the next minor (Vaadin 23.2).
Fixes #3746
- Bugfix
=> fix: initialize date-picker-light overlay properly

packages/dialog/src/lit/renderer-directives.js, packages/grid/src/lit/column-renderer-directives.js, packages/lit-renderer/src/lit-renderer.js
The PR replaces public class field syntax with getters for Lit renderer directives because the Flow Webpack config turned out not to support that syntax at the moment:
```
ERROR in ../node_modules/@vaadin/lit-renderer/src/lit-renderer.js 15:16
Module parse failed: Unexpected token (15:16)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export class LitRendererDirective extends AsyncDirective {
|   /** @protected */
>   previousValue = VALUE_NOT_INITIALIZED;
| 
|   constructor(part) {
```
=> fix: don't use public class field syntax in Lit renderer directives

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/multi-select-combo-box/test/basic.test.js
Added default values for `itemLabelPath` and `itemValuePath` to align with the regular combo-box.
- Refactor
=> refactor: add default values for item properties

packages/component-base/src/dom-utils.d.ts, packages/component-base/src/dom-utils.js, packages/component-base/test/dom-utils.test.js
The PR adds a `getAncestorRootNodes` DOM utility for obtaining an array of ancestor root nodes for any given node. 
A use-case can be to subscribe to `scroll` events on the ancestor root nodes in order to get notified whenever any of the scrollable ancestors is scrolling and run some specific logic e.g. repositioning the original node relative to the currently scrolling ancestor.
A part of https://github.com/vaadin/web-components/issues/3540
=> feat: add a getAncestorRootNodes DOM utility

packages/time-picker/src/vaadin-time-picker.js, packages/time-picker/test/time-picker.test.js
The `clearButtonVisible` property in `vaadin-time-picker` was not propagated to the underlying combo-box.
As a result, the logic responsible for clearing the value on <kbd>Escape</kbd> was not called.
- Bugfix
=> fix: clear time-picker with clear button on Esc

integration/package.json, integration/tests/dialog-time-picker.test.js
Added missing tests to ensure pressing <kbd>Esc</kbd> does not close dialog when handled by `vaadin-time-picker`.
Depends on #3933
- Test
=> test: add tests for time-picker in dialog

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/multi-select-combo-box/test/visual/lumo/multi-select-combo-box.test.js, packages/multi-select-combo-box/test/visual/material/multi-select-combo-box.test.js
1. Removed logic responsible for updating overlay width because the `vaadin-multi-select-combo-box` no longer changes its input width dynamically based on the amount of chips selected (that's how the original addon worked).
2. Updated to use public `requestContentUpdate()` instead of accessing scroller. Also, clarified the related comment.
3. Updated visual tests to change input width before opening, to not rely on the removed behavior (see 1.)
- Refactor
=> refactor: cleanup multi-select-combo-box logic

packages/combo-box/src/vaadin-combo-box-dropdown.js, packages/combo-box/src/vaadin-combo-box-overlay.js
For historical reasons, the logic responsible for positioning `vaadin-combo-box-overlay` is currently placed in the `vaadin-combo-box-dropdown` component. Most of that logic was removed in #2497, the remaining part can be moved to the overlay itself.
This PR is a pre-requisite for the following one where the `vaadin-combo-box-dropdown` will be removed completely, with merging its logic into `ComboBoxMixin` to have less complex structure (that might be beneficial for moving to LitElement).
- Refactor
=> refactor: move positioning logic to overlay

packages/password-field/src/vaadin-password-field.d.ts
The usage of `SlotMixin` was replaced with `SlotController` in #3492 but the mixin was not removed from the `d.ts` file.
- Docs
=> docs: remove no longer used mixin from typings

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js
Updated to not use `theme` which was deprecated in #3529 and align with other components.
- Refactor
=> refactor: align theme propagation property

packages/vaadin-overlay/src/vaadin-overlay-position-mixin.js, packages/vaadin-overlay/test/position-mixin-listeners.test.js, packages/vaadin-overlay/test/position-mixin.test.js
The PR improves `PositionMixin` to run the reposition logic not only on `window` scroll but generally on scroll of any position target ancestor. This is needed to ensure the overlay is positioned properly when the position target is scrolling inside an element other than `document`. For example, this can be the case when using an overlay-based component in an app-layout (the app-layout's content has an individual scrollbar).
A part of https://github.com/vaadin/web-components/issues/3540
Based on the prototype: https://github.com/vaadin/web-components/pull/3841
=> fix: reposition the overlay on scroll of position target ancestors

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js
Applied the a11y change that was implemented in #3375 to `vaadin-multi-select-combo-box`.
Note: this will be covered with snapshot tests, I'm going to add them in a separate PR.
- Bugfix
=> fix: add aria-hidden to clear and toggle buttons

packages/context-menu/src/vaadin-contextmenu-items-mixin.js
Updated the logic to not use `flush()` as it's not needed: we no longer support ShadyDOM, and there are no debouncers that need to be flushed in case of attaching empty `vaadin-context-menu-list-box` (we initialize its items later).
- Refactor
=> refactor: update menu renderer to not use flush

packages/date-picker/test/common.js
For some reason, the logic in `getOverlayContent` helper updates buffer size for internal infinite scrollers.
This causes problems in particular when using `sendKeys({ press: 'Tab' })` to focus month calendar.
An example of such a test can be seen in #3910 - it passes in CI but fails locally in Chrome:
https://user-images.githubusercontent.com/10589913/169849752-119d0a90-b5e4-4482-8254-f3067afe1fa5.mp4
It's not fully clear to me why the problem happens, but at least `scroller._debouncerUpdateClones` looks suspicious.
After removing this logic, it seems like the problem with tests that use `sendKeys` no longer happens.
=> test: do not tweak infinite scroller buffers

packages/select/src/vaadin-select.js, packages/select/test/select.test.js
There is a logic in `vaadin-grid` that ignores `click` events in case if they are prevented:
https://github.com/vaadin/web-components/blob/8e5b388efe5a17201298aae23a43e0136ba27105/packages/grid/src/vaadin-grid-active-item-mixin.js#L52-L56
We need to use this in `vaadin-select` which opens the overlay on `click` to inform parent `vaadin-grid` that the click is handled. This is somewhat related to #3885 where the same approach is proposed to be used for <kbd>Esc</kbd> press.
Part of https://github.com/vaadin/flow-components/issues/3177
Note: this PR alone is not enough to fix the original issue, as the `GridFlow` connector has another [`click` listener](https://github.com/vaadin/flow-components/blob/5a39682194b303fb0ee8209a8f0f281657b572ca/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/re …
=> fix: prevent default for click event on open

packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/test/toggling-dropdown.test.js
Same as #3954 but for `vaadin-combo-box`: tested the original issue and `ComboBox` in `Grid` editor has the same problem.
Updated to call `event.preventDefault()` for toggle button click (always) and for host click (when auto-open is enabled).
- Bugfix
=> fix: prevent default for combo-box click on open

packages/avatar-group/src/vaadin-avatar-group-overlay.js, packages/avatar-group/src/vaadin-avatar-group.js, packages/avatar-group/test/dom/__snapshots__/avatar-group.test.snap.js
The `vaadin-avatar-group` appears to be the only remaining component that had some custom positioning logic.
Note: there were no tests and the logic itself was apparently a copy-paste from `vaadin-selecy` 🙈 
- Refactor
=> refactor: use PositionMixin instead of custom logic

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.d.ts, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/multi-select-combo-box/test/basic.test.js
This PR adds the public APIs that are currently missing in `vaadin-multi-select-combo-box` but are present in the regular `vaadin-combo-box`, especially `size` property (we have some tests where it's configured) and `clearCache()` method.
- Feature
=> feat: add missing API related to dataProvider

packages/field-highlighter/src/vaadin-user-tags.js, packages/field-highlighter/test/user-tags.test.js
The PR speeds up field highlighter unit tests by decreasing the delay and duration of the flashing animation.
**Before:**
```
yarn run v1.22.18
$ web-test-runner --group field-highlighter
Chrome: |██████████████████████████████| 3/3 test files | 93 passed, 0 failed
Finished running tests in 11.3s, all tests passed! 🎉
✨  Done in 11.78s.
```
**After:**
```
yarn run v1.22.18
$ web-test-runner --group field-highlighter
Chrome: |██████████████████████████████| 3/3 test files | 93 passed, 0 failed
Finished running tests in 1.7s, all tests passed! 🎉
✨  Done in 2.22s.
```
=> test: speed up field highlighter unit tests

integration/package.json, integration/tests/grid-combo-box.test.js, integration/tests/grid-select.test.js
Added integration tests for `vaadin-select` and `vaadin-combo-box` fixes done in #3954 and #3957.
- Tests
=> test: add ITs for active-item-changed grid event

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/multi-select-combo-box/test/basic.test.js
Prevent data provider mixin from clearing the input value when the data provider callback resolves. The data provider mixin relies on the `focused` attribute being present on the combo box to determine whether the component is actively used, however the `focused` attribute is never set on the internal combo box. This change propagates the `focused` attribute to the internal combo box to fix that.
Fixes #3969 
- Bugfix
=> fix: keep input value when data provider resolves callback

packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/test/basic.test.js
Same as #3954 but for `vaadin-date-picker` which is affected by the same issue, see the recording:
https://user-images.githubusercontent.com/10589913/171132701-5e8e1f49-539d-4ff2-b64f-481609b57bbf.mp4
Note: click on the toggle button is not affected because we use `stopPropagation()` for it:
https://github.com/vaadin/web-components/blob/51a1a42a6f2a825e13803a6f8c5c3705e2036c88/packages/date-picker/src/vaadin-date-picker.js#L235-L238
Also, clicks on `<input>` and `<label>` are ignored by `GridFlow` as both pass the `isFocused` check.
Integration test for this fix will be added in a separate PR to make cherry-picks possible.
- Bugfix
=> fix: prevent default for date-picker click on open

packages/field-highlighter/src/vaadin-user-tags.js, packages/field-highlighter/test/field-components.test.js, packages/field-highlighter/test/field-highlighter.test.js, packages/field-highlighter/test/user-tags.test.js
The PR introduces `IntersectionObserver` to `vaadin-user-tags` in order to watch for visibility changes of the target field and hide the overlay when the field is not visible.
- When adding users, the `user-tags` waits for the field to become fully visible before opening the overlay and beginning the flashing animation.
- The overlay is closed as soon as the field becomes not fully visible.
- If the field has focus, the overlay is re-opened as soon as the field becomes fully visible again.
A part of https://github.com/vaadin/web-components/issues/3540
Based on the prototype: https://github.com/vaadin/web-components/pull/3841
=> fix: show user tags overlay only when the field is fully visible

packages/crud/src/vaadin-crud-dialog.js, packages/time-picker/src/vaadin-time-picker-combo-box.js
Added missing `@private` JSDoc annotations to exclude internal elements from [API documentation](https://cdn.vaadin.com/vaadin-web-components/23.1.0-rc3/).
=> docs: hide internal elements from API docs

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.d.ts, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/multi-select-combo-box/test/basic.test.js
=> feat: add missing requestContentUpdate() method

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-dropdown.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-scroller.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.d.ts, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/multi-select-combo-box/test/basic.test.js, packages/multi-select-combo-box/test/typings/multi-select-combo-box.types.ts
Depends on #3982 where the tests for `renderer` were added.
Fixes #3980
- Bugfix
=> fix: pass the correct owner to item renderers

packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/test/basic.test.js
Added the same fix as in #3883 but for `vaadin-date-picker` that has `clearButtonVisible` set to `true`.
Note: also added `preventDefault()` for forwards compatibility with the approach suggested in #3885
The integration test for this fix will be added in a separate PR to make cherry-picking possible.
- Bugfix
=> fix: prevent and stop propagation when clearing

packages/tabs/src/vaadin-tab.js, packages/tabs/test/tab.test.js
For some reason, `vaadin-tab` was missing styles for `hidden` attribute 🙈 
- Bugfix
=> fix: add hidden attribute styles to vaadin-tab

package.json, yarn.lock
It turns out that Lerna 5.0 requires Node version that is not installed on TeamCity where we run cherry-picks:
```
[12:03:39][Step 1/1] yarn install v1.22.17
[12:03:39][Step 1/1] [1/4] Resolving packages...
[12:03:40][Step 1/1] [2/4] Fetching packages...
[12:03:41][Step 1/1] error lerna@5.0.0: The engine "node" is incompatible with this module. Expected version "^14.19.3 || >=16.0.0". Got "14.19.0"
[12:03:41][Step 1/1] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[12:03:41][Step 1/1] error Found incompatible module.
```
Let's downgrade back to 4.0 for now. After all the agents are updated to Node 16 internally, we can revert this PR.
=> chore: downgrade Lerna version to 4.0.0

wtr-utils.js
Currently, all the cherry-picks to `23.0` branch run all tests due to `yarn.lock` compared against `master` 🤦‍♂️ 
This PR fixes that to use `origin/23.0` instead to ensure the correct file is checked.
=> chore: fix lockfile change detection for 23.0

packages/vaadin-themable-mixin/test/lit-setup.js, packages/vaadin-themable-mixin/test/themable-mixin.test.js, packages/vaadin-themable-mixin/vaadin-themable-mixin.js
Current implementation of `finalizeStyles` does not flatten the styles passed as an array e.g. like this:
```js
import { clearButton } from '@vaadin/field-base/src/styles/clear-button-styles.js';
import { fieldShared } from '@vaadin/field-base/src/styles/field-shared-styles.js';
import { inputFieldContainer } from '@vaadin/field-base/src/styles/input-field-container-styles.js';
import { css } from 'lit';
// ... inside a class:
static get styles() {
return [
fieldShared,
inputFieldContainer,
clearButton,
css`
.vaadin-text-area-container {
flex: auto;
}
`,
];
}
```
This PR adds a call to `super.finalizeStyles(styles)` which performs [flattening](https://github.com/lit/lit/blob/7ba356c4795ddf2b2a69e69a4c3f78df1e6b56c5/packages/reactive-element/src/reactive-element.ts#L823-L831) for the …
=> fix: allow passing array of styles with Lit

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js
Fix a copy-pate leftover to eliminate warning about not existing observer:
- Bugfix
=> fix: remove not existing property observer

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.d.ts, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/multi-select-combo-box/test/basic.test.js
Follow-up to #3961, added a missing `loading` property and corresponding state attribute for styling.
- Feature
=> feat: expose loading property and attribute

wtr-utils.js
Update the `web-test-runner` change detection script to use `23.1` as a base branch for Vaadin 23.1
=> chore: update change detection branch to 23.1

packages/component-base/src/unique-id-utils.d.ts, packages/component-base/src/unique-id-utils.js, packages/component-base/test/unique-id-utils.test.js
The PR introduces `generateUniqueId()` and `resetUniqueId()` utilities that cover common logic related to generating ids in components and mixins.
Note, `resetUniqueId()` is useful in snapshot tests as it makes the id generation stable and as a result we can get rid of the necessity to ignore a11y related attributes:
```diff
- const SNAPSHOT_CONFIG = {
-   ignoreAttributes: ['id', 'aria-describedby', 'aria-labelledby', 'for'],
- };
+ beforeEach(() => {
+   resetUniqueId();
+ }
```
=> feat: add utilities for generating unique ids

packages/app-layout/src/vaadin-app-layout.js, packages/app-layout/test/app-layout.test.js
Currently, on mobile devices the drawer is closed on `touchstart` and the following `touchend` event might result in dispatching a `click` event on the clickable element, such as `<button>` behind a backdrop - e.g. placed at the right corner of the navbar.
Up until Vaadin 23, this was apparently handled by Polymer ghost click prevention mechanism that we removed in #3169.
This PR changes the logic to close on `touchend` and adds `event.preventDefault()` call that actually prevents the click.
Fixes https://github.com/vaadin/flow-components/issues/3288
- Bugfix
=> fix: close drawer on touchend and prevent click

packages/context-menu/src/vaadin-contextmenu-event.js, packages/context-menu/test/touch.test.js, packages/grid/src/vaadin-grid-event-context-mixin.js, packages/grid/test/event-context.test.js
This PR addresses a problem that makes `grid.getEventContext()` broken when using `vaadin-contextmenu` event.
Note, this logic is quite fundamental for `vaadin-grid` context-menu feature, as you can see it's used in two places:
- [GridContextMenu](https://github.com/vaadin/flow-components/blob/90f440e15831ce1d6f6def44c91fa273f1d4b751/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js#L1038-L1041)
- [TypeScript example](https://github.com/vaadin/docs/blob/ce9cf34c7a8b95adb16f90fa4b4c1114b91e385f/frontend/demo/component/grid/grid-context-menu.ts#L36-L39)
The actual problem is that `event.composedPath()` returns `[]` (empty array) as soon as you use `setTimeout()`.
This is exactly what we are doing for `touchstart` event by setting timer …
=> fix: make getEventContext() work with context-menu on iOS

packages/combo-box/src/vaadin-combo-box-data-provider-mixin.js, packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/test/basic.test.js
The PR removes the internal use of Polymer API from the combo-box to simplify the logic of observers.
A preparation for #3864
=> refactor: don't use Polymer API internally in combo-box

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/multi-select-combo-box/test/basic.test.js
Copied the logic that is present in `ComboBoxMixin` to make sure it works in `vaadin-multi-select-combo-box`:
https://github.com/vaadin/web-components/blob/9d50b856b3b9a839d3456b066f0bee41293bd281/packages/combo-box/src/vaadin-combo-box-mixin.js#L822-L826
In case of regular combo-box, the `ComboBoxMixin` is applied on top of `InputControlMixin` and overriding works.
This is not the case with `vaadin-multi-select-combo-box` which does not apply mixins in this order.
Fixes #4011
- Bugfix
=> fix: do not fire change event on native input change

packages/combo-box/src/vaadin-combo-box-data-provider-mixin.js, packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/test/lazy-loading.test.js
The PR simplifies the selected item synchronization by combining some conditions for the case when `value` is set before `filteredItems` which can be the case when the data provider has not yet loaded items or external filtering is implemented.
A preparation for https://github.com/vaadin/web-components/issues/3864
=> refactor: simplify selected item sync logic

packages/combo-box/src/vaadin-combo-box-data-provider-mixin.js, packages/combo-box/src/vaadin-combo-box-dropdown.js, packages/combo-box/src/vaadin-combo-box-mixin.js
- Extracted `_isValidValue` from the combo-box mixin class so now it is a plain function.
- Extracted `indexOfLabel` from the combo-box dropdown to the combo-box mixin.
- Renamed `indexOfLabel` with `__getItemIndexByLabel`
- Renamed `_indexOfValue` with `__getItemIndexByValue`
A preparation for https://github.com/vaadin/web-components/issues/3864
=> refactor: extract some methods, improve their naming

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/multi-select-combo-box/test/basic.test.js
Currently, when updating `items` property to empty array, or changing it, the `selectedItems` is not updated.
This PR changes that to filter out the items that are removed and exclude them from `selectedItems`.
- Bugfix
=> fix: update selectedItems when updating items

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/multi-select-combo-box/test/basic.test.js
This reverts commit 0064ec46f0fffd3a7baa5a25731c879ad27f3dba.
Revert the previous PR based on discussion, see #https://github.com/vaadin/web-components/pull/4016#issuecomment-1150974114
- Revert
=> Revert "fix: update selectedItems when updating items (#4016)"

packages/combo-box/src/vaadin-combo-box-mixin.js, packages/multi-select-combo-box/lit.d.ts, packages/multi-select-combo-box/lit.js, packages/multi-select-combo-box/package.json, packages/multi-select-combo-box/src/lit/renderer-directives.d.ts, packages/multi-select-combo-box/src/lit/renderer-directives.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js, packages/multi-select-combo-box/test/lit-renderer-directives.test.js, packages/multi-select-combo-box/test/typings/lit.types.ts
Added the new Lit renderer directive copied from the `comboBoxRenderer`. 
Also, fixed the scroller initialization to be done before it gets attached.
Fixes #3981
- Feature
=> feat: add multi-select-combo-box Lit renderer

packages/combo-box/src/vaadin-combo-box-light.js, packages/combo-box/src/vaadin-combo-box-mixin.d.ts, packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/src/vaadin-combo-box.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/multi-select-combo-box/test/basic.test.js, packages/time-picker/src/vaadin-time-picker-combo-box.js
The PR refactors the combo-box and multi-select-combo-box to get rid of a separate `dropdownItems` concept on top of `filteredItems`.
=> refactor: remove _dropdownItems property

packages/date-picker/src/vaadin-date-picker-overlay-content.js, packages/date-picker/test/keyboard-input.test.js
The default value for `scrollDuration` property was incorrectly set, thus causing the scroll animation to break 🙈 
Fixes #4024
- Bugfix
=> fix: restore broken date-picker scroll duration

packages/field-base/src/pattern-mixin.d.ts, packages/field-base/src/pattern-mixin.js, packages/field-base/test/pattern-mixin.test.js
Added a deprecation warning to be shown when setting `preventInvalidInput` to `true`.
Part of #3837
=> docs: deprecate `preventInvalidInput` property

packages/integer-field/src/vaadin-integer-field.d.ts, packages/integer-field/src/vaadin-integer-field.js, packages/number-field/src/vaadin-number-field.d.ts, packages/number-field/src/vaadin-number-field.js
Updated API docs for numeric fields to fix no longer valid statements about `input-prevented` state attribute.
- Docs
=> docs: update input-prevented attribute docs

packages/checkbox/src/vaadin-checkbox.js, packages/combo-box/test/dom/__snapshots__/combo-box.test.snap.js, packages/crud/test/dom/__snapshots__/crud.test.snap.js, packages/email-field/src/vaadin-email-field.js, packages/email-field/test/dom/__snapshots__/email-field.test.snap.js, packages/field-base/src/field-mixin.js, packages/field-base/src/label-mixin.js, packages/field-base/src/slot-target-controller.js, packages/integer-field/test/dom/__snapshots__/integer-field.test.snap.js, packages/message-input/test/dom/__snapshots__/message-input.test.snap.js, packages/number-field/src/vaadin-number-field.js, packages/number-field/test/dom/__snapshots__/number-field.test.snap.js, packages/password-field/test/dom/__snapshots__/password-field.test.snap.js, packages/radio-group/src/vaadin-radio-button.js, packages/text-area/src/vaadin-text-area.js, packages/text-area/test/dom/__snapshots__/text-area.test.snap.js, packages/text-field/test/dom/__snapshots__/text-field.test.snap.js, packages/time-picker/test/dom/__snapshots__/time-picker.test.snap.js
Currently, some components initialize controllers in `connectedCallback()`, while others use `ready()`. This PR changes that.
Also, moving `addController()` calls to `ready()` is a first step for `LitElement` support through `PolylitMixin`.
This is due to the fact that in `SlotController` we need access to shadow DOM in order to observe a slot:
https://github.com/vaadin/web-components/blob/b4dec66f8a0f540bc4c0b3a16a9d099b954d74a7/packages/component-base/src/slot-controller.js#L137
- Refactor
=> refactor: move initialization to ready() callback

packages/combo-box/src/vaadin-combo-box-data-provider-mixin.js, packages/combo-box/src/vaadin-combo-box-scroller.js, packages/combo-box/test/lazy-loading.test.js
The main goal of the PR is to add a missing `selectedItem` property observer that should trigger the scroller to update whenever `selectedItem` changes. 
There was previously an assumption that when `selectedItem` changes, `focusedIndex` also changes which triggers the scroller to update afterward. However, that could not work when using a data provider and setting an item as selected whose reference is different from the reference of the identical item provided by the data provider. Because the strict comparison is used when identifying the index of the selected item, `focusedIndex` could remain `-1` and thus `focusedIndexObserver` would not be invoked:
https://github.com/vaadin/web-components/blob/ad1ad3d947c605dbe8d50f72e8348ac1de19688e/packages/combo-box/src/vaadin-combo-box-mixin.js#L …
=> fix: render selectedItem as selected when setting it while loading items

.github/workflows/coverage.yml, .github/workflows/integration.yml, .github/workflows/lint.yml, .github/workflows/smoke.yml, .github/workflows/snapshots.yml, .github/workflows/unit-tests.yml, .github/workflows/visual-tests.yml
Disabled caching `node_modules` for now to workaround failures in GitHub Actions.
See https://github.com/actions/setup-node/issues/516
=> chore: disable yarn cache to fix CI builds

packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/src/vaadin-combo-box-scroller.js, packages/combo-box/test/lazy-loading.test.js
The PR prevents a possible item focus reset after the data provider has loaded more items. The item focus preserves when more items are loading but it is reset when the user changes the filter query.
Fixes https://github.com/vaadin/web-components/issues/3864
=> fix: prevent an item focus reset after more items are loaded

packages/select/src/vaadin-select.d.ts, packages/select/src/vaadin-select.js, packages/select/test/dom/__snapshots__/select.test.snap.js
Same as #3492 but for `vaadin-select-value-button`. This also moves `vaadin-select` initialization to `ready()` callback.
- Refactor
=> refactor: use SlotController for value button

packages/combo-box/src/vaadin-combo-box-scroller.js, packages/combo-box/test/external-filtering.test.js
This fixes part of the ITs that failed after upgrading Flow components to 23.2.0-alpha1:
- `ItemCountEstimateIncreaseComboBoxIT`
- `ItemCountCallbackComboBoxIT`
- `ComboBoxLitRendererIT`
- `FilterConverterComboBoxIT`
- Bugfix
=> fix: restore timeout in scroller loading observer

packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/test/basic.test.js
This PR fixes a regression in #3944 that caused Flow component ITs to fail because of dataProvider requesting extra page.
After the refactoring, `max-height` was not set by the time when `scroller.requestContentUpdate()` was called.
- Bugfix
=> fix: set max-height on scroller when pre-opened

packages/combo-box/test/dom/__snapshots__/combo-box.test.snap.js, packages/combo-box/test/dom/combo-box.test.js, packages/email-field/test/dom/__snapshots__/email-field.test.snap.js, packages/email-field/test/dom/email-field.test.js, packages/integer-field/test/dom/__snapshots__/integer-field.test.snap.js, packages/integer-field/test/dom/integer-field.test.js, packages/number-field/test/dom/__snapshots__/number-field.test.snap.js, packages/number-field/test/dom/number-field.test.js, packages/password-field/test/dom/__snapshots__/password-field.test.snap.js, packages/password-field/test/dom/password-field.test.js, packages/select/test/dom/__snapshots__/select.test.snap.js, packages/select/test/dom/select.test.js, packages/text-area/test/dom/__snapshots__/text-area.test.snap.js, packages/text-area/test/dom/text-area.test.js, packages/text-field/test/dom/__snapshots__/text-field.test.snap.js, packages/text-field/test/dom/text-field.test.js
- Re-organized snapshot tests so that there is now a common `host` suite that tests both the host element and slots at the same time.
- Added tests verifying that the error message id is associated with the input when the field is invalid.
=> test: re-organize and add more snapshot tests

packages/combo-box/test/aria.test.js, packages/combo-box/test/basic.test.js, packages/combo-box/test/dom/__snapshots__/combo-box.test.snap.js, packages/combo-box/test/dom/combo-box.test.js
This PR replaces some a11y-related unit tests with snapshot tests.
=> test: replace some combo-box unit tests with snapshot tests

packages/custom-field/src/vaadin-custom-field.d.ts, packages/custom-field/test/typings/custom-field.types.ts
Add the missing type definitions for `<vaadin-custom-field>` "internal-tab" event
=> docs: document custom field internal-tab event

packages/select/src/vaadin-select.js, packages/select/test/select.test.js
When the `vaadin-select` component receives a value which is not a string, it should be able to find the corresponding item anyway. This fix simply convert the new value to string before searching for it. This will also allow Hilla to bind `select`s to boolean and integers.
Fixes #4059
=> fix: accept boolean and numeric item values

packages/grid/src/vaadin-grid-sort-mixin.js, packages/grid/src/vaadin-grid-sorter.js, packages/grid/test/sorting.test.js
This PR is based on a suggestion from https://github.com/vaadin/flow-components/pull/3343#discussion_r897915797.
Note: I simplified the test case as the underlying issue is not specific to moving columns in the DOM.
Fixes https://github.com/vaadin/flow-components/issues/2102
- Bugfix
=> fix: remove disconnected sorters with no parent

packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/test/lazy-loading.test.js
Updated the logic related to opening combo-box dropdown on `input` event to perform a [batched property update](https://polymer-library.polymer-project.org/2.0/docs/devguide/data-system#batched-property-changes).
This avoids an extra request by making sure `this.filter` contains correct input when requesting data-provider.
Fixes #1215
https://user-images.githubusercontent.com/10589913/174742070-480ce3a0-9cfc-43bc-945a-19d50b1f3f28.mp4
https://user-images.githubusercontent.com/10589913/174742052-ca94d594-900a-4968-876b-57ea7080d8e5.mp4
- Bugfix
=> fix: avoid extra request when opened on input

packages/combo-box/test/lazy-loading.test.js
After restoring `setTimeout` in `combo-box-scroller`, we forgot to restore waiting for that `setTimeout` in combo-box tests which made some of them flaky.
A follow-up to https://github.com/vaadin/web-components/pull/4049
=> test: wait for the loading observer in combo-box tests

packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/test/keyboard-input.test.js
Makes `checkValidity` return `false` when user enter invalid date on a `DatePicker`.
Fixes #4079
=> fix: ensure checkValidity returns false when date is invalid

packages/combo-box/src/vaadin-combo-box-data-provider-mixin.js, packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/test/internal-filtering.test.js, packages/combo-box/test/lazy-loading.test.js
A cherry-pick of the following fix to `23.1`:
- https://github.com/vaadin/web-components/pull/4073
Fixes https://github.com/vaadin/flow-components/issues/3321
=> fix: prevent a filter reset on open after filtering when autoOpenDisabled (#4073) (CP: 23.1)

packages/date-picker/src/vaadin-date-picker-light.d.ts, packages/date-picker/src/vaadin-date-picker-light.js, packages/date-picker/src/vaadin-date-picker-mixin.d.ts, packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/test/typings/date-picker.types.ts
This PR extends `date-picker-light` from `ValidateMixin` to add the missing `invalid`, `required` properties and make it possible to get rid of the `validate()` method in `combo-box-mixin`.
Part of #4081
=> fix: add ValidateMixin to date-picker-light

packages/board/package.json, packages/board/src/vaadin-board.js, packages/charts/package.json, packages/charts/src/vaadin-chart.js, packages/component-base/custom_typings/vaadin.d.ts, packages/confirm-dialog/package.json, packages/confirm-dialog/src/vaadin-confirm-dialog.js, packages/cookie-consent/package.json, packages/cookie-consent/src/vaadin-cookie-consent.js, packages/crud/package.json, packages/crud/src/vaadin-crud.js, packages/grid-pro/package.json, packages/grid-pro/src/vaadin-grid-pro.js, packages/map/package.json, packages/map/src/vaadin-map.js, packages/rich-text-editor/package.json, packages/rich-text-editor/src/vaadin-rich-text-editor.js, wtr-utils.js, yarn.lock
License checking is now handled in Flow + Hilla
=> refactor: remove license checker from Pro components

packages/select/src/vaadin-select.d.ts, packages/select/src/vaadin-select.js, packages/select/test/select.test.js, packages/select/test/typings/select.types.ts
- Moved the validatity checks from `validate()` to `checkValidity()`.
- Ensured `checkValidity()` always returns a boolean.
- Added the corresponding unit tests.
Part of #4081
=> fix: ensure checkValidity() returns the correct result

packages/combo-box/src/vaadin-combo-box-light.d.ts, packages/combo-box/src/vaadin-combo-box-light.js, packages/combo-box/src/vaadin-combo-box-mixin.d.ts, packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/test/form-input.test.js, packages/combo-box/test/typings/combo-box.types.ts
This PR extends `combo-box-light` from `ValidateMixin` to make it possible to get rid of the `validate()` method in `combo-box-mixin`.
Part of #4081
=> refactor: add ValidateMixin to combo-box-light

packages/grid/src/vaadin-grid-sort-mixin.d.ts, packages/grid/src/vaadin-grid-sort-mixin.js, packages/grid/test/sorting.test.js, packages/grid/test/typings/grid.types.ts
Added `multiSortPriority` property that can be used to update sorting behavior as follows:
1. Clicking a sorter for a not yet sorted column "appends" it by applying at the end of the existing sorters,
2. Clicking a sorter for an already column sorted does not update order in which columns are sorted.
Fixes #1281
Part of https://github.com/vaadin/platform/issues/3052
Related to https://github.com/vaadin/flow-components/issues/1197
- Feature
=> feat: add property to control multi-sort priority

packages/checkbox-group/test/checkbox-group.test.js, packages/combo-box/test/form-input.test.js, packages/custom-field/test/custom-field.test.js, packages/date-picker/test/form-input.test.js, packages/date-time-picker/test/validation.test.js, packages/email-field/test/email-field.test.js, packages/field-base/src/validate-mixin.d.ts, packages/field-base/src/validate-mixin.js, packages/field-base/test/validate-mixin.test.js, packages/integer-field/test/integer-field.test.js, packages/number-field/test/validation.test.js, packages/password-field/test/password-field.test.js, packages/radio-group/test/radio-group.test.js, packages/select/test/select.test.js, packages/text-area/test/text-area.test.js, packages/text-field/test/text-field.test.js, packages/time-picker/test/form-input.test.js
This PR introduces a `validated` event that will be fired whenever a field is validated.
Part of https://github.com/vaadin/web-components/issues/4081
=> feat: fire a `validated` event on validation

packages/field-base/src/input-constraints-mixin.js, packages/field-base/src/validate-mixin.js, packages/field-base/test/validate-mixin.test.js, packages/number-field/src/vaadin-number-field.js
- Added a protected method `_shouldSetInvalid(invalid)` that determines whether the `invalid` property should be updated to the given `invalid` state (by default: always `true`).
- Added a protected method `_setInvalid(invalid)` that updates the `invalid` property to the given `invalid` state if it passes `_shouldSetInvalid`. This method is supposed to be used by the web components wherever they need to update `invalid` internally instead of manipulating the property directly.
The main purpose of `_shouldSetInvalid` is to make it possible later for Flow to prevent the web components from committing client-side validation success: the final decision on whether a component is valid will be made by the server.
Part of #4081
=> refactor: add methods to make setting invalid overridable

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/multi-select-combo-box/test/accessibility.test.js
Currenty removing a chip with backspace announces "[object Object] removed from selection" when using objects as items. This change fixes the announcement to use the item label.
Updated the announcement tests to use object items.
- Bugfix
=> fix: announce item label when removing chip with keyboard

packages/combo-box/src/vaadin-combo-box-data-provider-mixin.d.ts, packages/combo-box/src/vaadin-combo-box-data-provider-mixin.js, packages/combo-box/test/lazy-loading.test.js
Updated the type definition as requested by https://github.com/vaadin/web-components/issues/4099#issuecomment-1167249564 and to align with corresponding type in `vaadin-grid`:
https://github.com/vaadin/web-components/blob/48e5e39670645eba5b9d0f9be91e29b134b93bf8/packages/grid/src/vaadin-grid-data-provider-mixin.d.ts#L21
Fixes #4099
- Bugfix
=> fix: make ComboBoxDataProviderCallback size optional

packages/grid/src/vaadin-grid.d.ts, packages/grid/src/vaadin-grid.js
Fixed incorrect markup that makes the state attributes table look broken in the API docs:
- Docs
=> docs: fix incorrect markdown in state attributes table

packages/charts/src/vaadin-chart.d.ts, packages/charts/src/vaadin-chart.js
Replaced old links to Vaadin 14 docs with the latest Chart styling guide.
=> docs: update links to chart styling guide

packages/charts/src/vaadin-chart.js, packages/component-base/src/gestures.js, packages/vaadin-themable-mixin/vaadin-themable-mixin.js
This PR simplifies some JS conditions by using `startsWith()`, `endsWith()`.
=> refactor: use modern startsWith(), endsWith()

packages/avatar-group/theme/lumo/vaadin-avatar-group-styles.js
While reviewing #4106, I noticed that Lumo has duplicate custom CSS properties for `small` and `xsmall` variants:
https://github.com/vaadin/web-components/blob/abd49eb4a8076aca7f48ccd9dc554893a7b8124f/packages/avatar-group/theme/lumo/vaadin-avatar-group-styles.js#L15-L17
https://github.com/vaadin/web-components/blob/abd49eb4a8076aca7f48ccd9dc554893a7b8124f/packages/avatar-group/theme/lumo/vaadin-avatar-group-styles.js#L38
https://github.com/vaadin/web-components/blob/abd49eb4a8076aca7f48ccd9dc554893a7b8124f/packages/avatar-group/theme/lumo/vaadin-avatar-group-styles.js#L19-L21
https://github.com/vaadin/web-components/blob/abd49eb4a8076aca7f48ccd9dc554893a7b8124f/packages/avatar-group/theme/lumo/vaadin-avatar-group-styles.js#L44
- Refactor
=> refactor: cleanup duplicate custom CSS properties

packages/integer-field/src/vaadin-integer-field.js, packages/integer-field/test/dom/__snapshots__/integer-field.test.snap.js, packages/integer-field/test/integer-field.test.js, packages/number-field/src/vaadin-number-field.d.ts, packages/number-field/src/vaadin-number-field.js, packages/number-field/test/dom/__snapshots__/number-field.test.snap.js, packages/number-field/test/number-field.test.js, packages/number-field/test/validation.test.js
This PR removes the default value for the `step` property of `number-field` which makes it possible to throw away the custom validation logic entirely relying on the `InputConstraintsMixin` validation logic instead.
**Breaking changes:**
1. The `step` property no longer has a default value and therefore `undefined` and `null` values are now allowed.
3. Setting the `step` property no longer leads to setting the `step` attribute on the `number-field` host.
Related to https://github.com/vaadin/web-components/issues/1224
=> refactor!: remove the default value for step

packages/crud/theme/lumo/vaadin-crud-styles.js
This CSS is no longer needed: it was added to `vaadin-crud` in https://github.com/vaadin/vaadin-crud/pull/59 but then corresponding code has been moved to `vaadin-grid` itself as part of https://github.com/vaadin/vaadin-grid/pull/1446. Let's remove it from `vaadin-crud` theme.
- Refactor
=> refactor: cleanup duplicate cell content style

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.d.ts, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/multi-select-combo-box/test/accessibility.test.js, packages/multi-select-combo-box/test/selecting-items.test.js
The `clear()` method in `vaadin-multi-select-combo-box` is inherited from `InputControlMixin` and not overridden.
Its current behavior is quite confusing: when the MSC has items selected, calling `clear()` does nothing.
Let's update the logic and override this method to make it work same as in regular `vaadin-combo-box`.
- Bugfix
=> fix: clear selection when using `clear()` method

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/multi-select-combo-box/test/basic.test.js
Fixes #4129
Depends on #4140
Created a separate event listener for clear button `touchend` event to call `clear()` on the host element.
The internal combo-box also has a `touchend` listener, but it only clears `<input>` value.
We might simplify this logic in the future as part of #4130 by moving the listener to `InputControlMixin`.
- Bugfix
=> fix: clear selection on clear button touchend

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.d.ts, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/multi-select-combo-box/test/typings/multi-select-combo-box.types.ts
The `value` property in `vaadin-multi-select-combo-box` is inherited from `InputControlMixin` that wraps `InputMixin`.
Currently, it's listed in the [API docs](https://cdn.vaadin.com/vaadin-web-components/23.2.0-alpha3/index.html#/elements/vaadin-multi-select-combo-box) and shown in TS code completion, which might be confusing.
Let's consider removing `value` from public API of the component to make it possible to drop it in the next major.
- Refactor
=> refactor!: remove `value` from API docs and typings

packages/email-field/test/email-field.test.js, packages/field-base/src/input-field-mixin.js, packages/field-base/test/input-field-mixin.test.js, packages/integer-field/test/integer-field.test.js, packages/number-field/test/validation.test.js, packages/password-field/test/password-field.test.js, packages/text-area/test/text-area.test.js, packages/text-field/test/text-field.test.js
The PR prevents the initial validation that could previously take place when the field is initially provided with a non-empty value and is initially marked `invalid`: 
```js
const textField = document.createElement('vaadin-text-field');
textField.value = 'Initial Value';
textField.invalid = true;
document.appendChild(textField);
```
The initial validation is problematic because it fires a `validated` event that may result in an `invalid` state reset on the Flow side, see https://github.com/vaadin/flow-components/pull/3429#issuecomment-1177365424 for a more detailed case.
This PR only fixes the issue for the components that extend `InputFieldMixin`:
Other components will be covered in the next PRs.
=> fix: prevent initial validation when the field is initialized as invalid

packages/checkbox-group/src/vaadin-checkbox-group.js, packages/checkbox-group/test/checkbox-group.test.js
The PR prevents the initial validation that could previously take place when `checkbox-group` is initially provided with a non-empty value and is initially marked `invalid`.
=> fix: prevent initial validation when checkbox-group is initialized as invalid

packages/date-time-picker/src/vaadin-date-time-picker.js
The usage of this method has been dropped in #2782 but the method is still there. Let's remove it.
- Refactor
=> refactor: remove no longer used private method

web-test-runner.config.js
Current glob is wrong, as it also includes themes and Quill build in `vendor` folder, whereas in practice we only need `src` files (including subfolders like `src/lit/*.js`) and root entrypoints to be included. Let's fix this to get more reliable numbers. 
This also allows to increase thresholds, mainly due to Quill build excluded from checking coverage.
=> chore: fix include globs in coverage config

packages/combo-box/src/vaadin-combo-box-mixin.js
The combo-box overlay no longer fires `vaadin-overlay-outside-click` event because the `_outsideClickListener` that [fires it](https://github.com/vaadin/web-components/blob/1cf10c0504a9f531914d8611bf6bc1c27a087af8/packages/vaadin-overlay/src/vaadin-overlay.js#L495) was overridden in #2497 based on my suggestion from https://github.com/vaadin/web-components/pull/2497#pullrequestreview-751218241. So this code can be removed.
- Refactor
=> refactor: remove no longer used event prevention

packages/combo-box/src/vaadin-combo-box-data-provider-mixin.js, packages/combo-box/src/vaadin-combo-box-mixin.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/multi-select-combo-box/test/basic.test.js, packages/time-picker/test/keyboard-navigation.test.js
Fixes #4151
Checking for `activeElement` is necessary in order to avoid relying on `focused` attribute here:
https://github.com/vaadin/web-components/blob/1e3728b378deb126c1f680276509d8b361f55552/packages/combo-box/src/vaadin-combo-box-mixin.js#L839-L842
Unfortunately, we don't currently have a setup to run tests that rely on touch devices, so no test 😕 
This also reverts #3971 as no longer necessary, as `ComboBoxDataProviderMixin` is also updated.
- Bugfix
=> fix: check if input is focused instead of using attribute

packages/time-picker/test/form-input.test.js
This PR adds unit tests verifying that no initial validation happens for `time-picker`.
=> test: make sure no initial validation happens for time-picker

packages/radio-group/src/vaadin-radio-group.js, packages/radio-group/test/radio-group.test.js
The PR prevents the initial validation that could previously take place when `radio-group` is initially provided with a non-empty value and is initially marked `invalid`.
> **Warning**
> I marked the PR as breaking because it changes the default value of the `value` property to an empty string. 
>
> Without this change, it was not possible to distinguish whether the value has been changed manually via the property.
=> fix!: prevent initial validation when radio-group is initialized as invalid

packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/test/combo-box-light.test.js
Originally, the [`keydown` listener](https://github.com/vaadin/vaadin-combo-box/blob/f81a39866e69ea096e5a15f9550fa37d9591f35e/vaadin-combo-box.html#L325-L341) did not set `_closeOnBlurIsPrevented` flag on <kbd>Arrow Down</kbd> or <kbd>Arrow Up</kbd>. This logic was introduced when adding custom input support and `vaadin-combo-box-light` - see https://github.com/vaadin/vaadin-combo-box/pull/254
The reason for it was the fact that pressing <kbd>Arrow Down</kbd> or <kbd>Arrow Up</kbd> on custom toggle button was firing `blur` event when using `<paper-input>` element, as mentioned [here](https://github.com/vaadin/vaadin-combo-box/blob/7aeeef0f38057f895a5718a72209297caaee3a77/vaadin-dropdown-behavior.html#L93-L99). See the recording from 1.x version to see what happened in this case: …
=> refactor: remove no longer needed flag, add tests

packages/date-picker/test/basic.test.js, packages/date-picker/test/common.js, packages/date-picker/test/form-input.test.js, packages/date-picker/test/keyboard-input.test.js
The PR reorganizes the `date-picker` validation unit tests and improves the test coverage. This is to prepare `date-picker` for future refactoring addressing the initial validation.
Preparation for #4150
=> test: reorganize validation tests, improve test coverage

packages/select/src/vaadin-select.js, packages/select/test/select.test.js
The PR prevents the initial validation that could previously take place when `select` was initially provided with a non-empty value.
=> fix: prevent initial validation for select

packages/combo-box/test/form-input.test.js
This PR adds unit tests verifying that no initial validation happens for `combo-box`.
=> test: make sure no initial validation happens for combo-box

packages/date-time-picker/test/validation.test.js
This PR adds unit tests verifying that no initial validation happens for `date-time-picker`.
=> test: make sure no initial validation happens for date-time-picker

packages/select/src/vaadin-select.js, packages/select/test/select.test.js
Taking the `disabled` state into account in `checkValidity()` appears to be pointless because `select` cannot be focused when disabled, so no user interaction should trigger validation. Moreover, no other components rely on `disabled` in their `checkValidity()` methods.
It only makes sense to consider `select` always valid when it is read-only but that will be addressed separately in #4180.
> **Warning**
> The change seems to be minor but I anyway marked it as breaking because `checkValidity()` is a public API. 
Related to https://github.com/vaadin/web-components/issues/4180
=> refactor!: make checkValidity() not take disabled state into account

packages/menu-bar/src/vaadin-menu-bar.d.ts, packages/menu-bar/src/vaadin-menu-bar.js
When adding `disabled` property, we missed to list corresponding state attribute in the API docs. This PR fixes that.
=> docs: add disabled attribute to styling API

packages/menu-bar/src/vaadin-menu-bar.js
This is necessary to make `disabled` property appear in the API docs of `vaadin-menu-bar`:
=> docs: add missing JSDoc annotation for mixin

packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/test/basic.test.js
This is a minor refactoring that aims to ensure `_selectedDate` is `null` any time `value` is empty. Previously, `_selectedDate` could become an empty string in certain cirtumstances which is incorrect given its type `Date`.
Along the way, I also refactored the `minDate` and `maxDate` properties to make them computed which allowed throwing away the crappy generic `_handleDateChange` method completely.
Addresses https://github.com/vaadin/web-components/pull/4169#discussion_r918852836
=> refactor: ensure _selectedDate is null when value is empty

packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/test/form-input.test.js
The PR prevents the initial validation that could previously take place when `date-picker` was initially provided with a non-empty value and no constraints were specified.
=> fix: prevent initial validation for date-picker when no constraints

packages/select/test/select.test.js, packages/select/test/validation.test.js
1. Moved the validation test suites into separate file to align with other component packages, e.g. `number-field`
2. Removed old test for initial validation added in https://github.com/vaadin/vaadin-select/pull/66 - it is no longer needed as it's now covered by new tests added in #4174
- Tests
=> test: reorganize and cleanup validation tests

packages/select/src/vaadin-select.js, packages/select/test/validation.test.js
Fixes #4180
Extracted this from #4198 to keep Git history cleaner.
- Bugfix
=> fix: do not mark select as invalid when readonly

packages/radio-group/test/radio-group.test.js
This PR drops some radio-group unit tests that have been replaced with snapshot tests.
A follow-up to https://github.com/vaadin/web-components/pull/4202
=> test: drop redundant radio-group unit tests

packages/radio-group/src/vaadin-radio-group.js, packages/radio-group/test/dom/__snapshots__/radio-group.test.snap.js, packages/radio-group/test/radio-group.test.js
=> fix: set aria-invalid attribute on the radio-group

packages/field-base/test/field-mixin.test.js
As mentioned in https://github.com/vaadin/web-components/pull/4205#issuecomment-1184595152, some of the removed radio-group unit tests were still needed. 
So I checked the `FieldMixin` tests and at least the test case for removing slotted helper was missing.
I'm not sure if we should restore `radio-group` tests as the actual fix in the #2759 where they were introduced was to rename conflicting `_observer` which is also used in other components e.g. `vaadin-checkbox-group` 🤔 
- Tests
=> test: add test for removing slotted helper

packages/field-base/src/checked-mixin.js, packages/field-base/src/field-mixin.js, packages/field-base/src/input-mixin.js, packages/field-base/src/pattern-mixin.js
Updated some JSDoc annotations for methods in the `field-base` package:
1. Removed `@override` where it's not needed (we only need it in subclasses)
2. Added some missing `@protected`, `@override` and `@param` annotations
3. Fixed copy-paste issue in `FieldMixin` observer: `required` -> `invalid`
=> docs: update JSDoc annotations for methods

packages/checkbox/test/checkbox.test.js, packages/field-base/src/checked-mixin.js, packages/field-base/test/checked-mixin.test.js, packages/radio-group/test/radio-button.test.js
Note: new tests might pass in CI without the change, as in GitHub Actions we test in Playwright on Linux, not MacOS.
Locally they pass though, and I'd like to avoid checking for `isSafari` instead of checking the focused element.
Fixes #4165
- Bugfix
=> fix: focus the input on change event in Safari

packages/time-picker/test/form-input.test.js, packages/time-picker/test/helpers.js, packages/time-picker/test/time-picker.test.js
This PR introduces a `setInputValue` test helper for emulating the user filling in something in the `time-picker` input and makes unit tests use it instead of custom implementations.
=> test: extract a setInputValue helper

packages/avatar/src/vaadin-avatar.d.ts, packages/avatar/src/vaadin-avatar.js, packages/login/src/vaadin-login-mixin.d.ts, packages/login/src/vaadin-login-mixin.js
Aligned the JSDoc comments for `avatar` and `login` with other components e.g. `upload`.
This makes the code snippets representing object structure looks better in API docs.
=> docs: fix i18n property JSDoc formatting

packages/time-picker/test/dom/__snapshots__/time-picker.test.snap.js, packages/time-picker/test/dom/time-picker.test.js, packages/time-picker/test/form-input.test.js
This PR replaces some `time-picker` unit tests with snapshot tests.
=> test: replace some unit tests with snapshot tests

packages/combo-box/src/vaadin-combo-box-mixin.js
Previously, this code was covered by two tests that incorrectly used `selectItem` helper, see #4217.
In fact, the event is always fired on item click, which is only possible when combo-box is opened:
https://github.com/vaadin/web-components/blob/a52a5d29a45ed6ff23a363bd6fb95d78eb7e6165/packages/combo-box/src/vaadin-combo-box-scroller.js#L326-L329
And setting `selectedItem` actually happens when committing value after closing the dropdown:
https://github.com/vaadin/web-components/blob/a52a5d29a45ed6ff23a363bd6fb95d78eb7e6165/packages/combo-box/src/vaadin-combo-box-mixin.js#L887-L890
This behavior is intentional and has been first introduced in https://github.com/vaadin/vaadin-combo-box/pull/785
- Refactor
=> refactor: remove no longer used code

packages/combo-box/test/keyboard.test.js, packages/field-base/test/pattern-mixin.test.js, packages/text-area/test/text-area.test.js
This PR replaces `inputText` helpers with the `sendKeys` API.
=> test: use the sendKeys API instead of inputText helpers

packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/test/basic.test.js
This code was updated in #3944 with the assumption that setting `opened` should trigger sync observer for overlay and render the scroller. However, this is not the case when `opened` is set without items. Restored old logic and added the test.
- Bugfix
=> fix: do not throw when setting opened attribute

packages/date-picker/test/form-input.test.js
This PR improves test coverage of `date-picker` by making some of its validation tests verify that the `invalid` property is updated appropriately after committing values rather than just that `checkValidity()` returns an expected result. In other words, the new version of tests ensures that the validation happens at the correct moment that is **after** the entered value has been committed (= the `value` property has been updated) and thus ensures that the validation uses the new value.
A follow-up to https://github.com/vaadin/web-components/pull/4163
=> test: verify `invalid` is set appropriately when committing values

packages/form-layout/src/vaadin-form-layout.js, packages/form-layout/test/form-layout.test.js
Added flag to distinguish `vaadin-form-item` elements managed by layout from those that have custom `label-position`.
Note: the flag is set on individual item elements which should make it possible to also keep the label position when adding to another layout (which is the case when using Vaadin Designer, although I don't remember if it supports `label-position`).
Fixes #1195
- Bugfix
=> fix: do not remove custom `label-position="top"` attribute

packages/multi-select-combo-box/README.md
Now when `vaadin-multi-select-combo-box` is considered to be ready, let's remove this outdated README note.
=> chore: remove work in progress note from README

packages/combo-box/test/form-input.test.js, packages/combo-box/test/keyboard.test.js
Moved two tests for <kbd>Enter</kbd> key from `form-input.test.js` to `keyboard.test.js` as that file is a better place.
Once this PR and #4229 are merged, we can then remove the test suite to `validation.test.js` as in #4225
- Tests
=> test: move Enter key tests to keyboard suite

packages/date-picker/test/validation.test.js
The name `form-input.test.js` is caused by the fact that originally, validation logic was introduced as part of `<iron-form>` support, see https://github.com/vaadin/vaadin-date-picker/pull/69. Let's align it with other components that use `describe('validation'`.
- Tests
=> test: rename form-input test suite to validation

packages/menu-bar/src/vaadin-menu-bar.js
=> docs: add missing JSDoc annotation for mixin (#4193) (#4194)

packages/date-picker/test/basic.test.js, packages/date-picker/test/keyboard-input.test.js, packages/date-picker/test/validation.test.js
Because of historical reasons, there are many tests in `keyboard-input.test.js` suite that cover validation.
This PR is a first part of moving related tests to `validation.test.js` where they should belong to.
- Tests
=> test: update and cleanup validation tests

packages/combo-box/test/keyboard.test.js
When using Playwright on MacOS to test in WebKit, the `<button>` element can't get focus when pressing <kbd>Tab</kbd> because the corresponding flag in settings is not set https://github.com/microsoft/playwright/issues/2114#issuecomment-625467787. Updated the test to use `<input>` instead.
- Tests
=> test: fix focusable content test on MacOS WebKit

packages/select/src/vaadin-select.js, packages/select/test/select.test.js
We have some logic to call `event.preventDefault()` on `mousedown` in combo-box and date-picker components:
https://github.com/vaadin/web-components/blob/2b0859f55b105278acf722dc25f8f5a5a52bbcc8/packages/date-picker/src/vaadin-date-picker.js#L212-L213
https://github.com/vaadin/web-components/blob/2b0859f55b105278acf722dc25f8f5a5a52bbcc8/packages/combo-box/src/vaadin-combo-box-mixin.js#L826-L827
Adding it to `vaadin-select` to align behavior and restore `focus-ring` if opened with toggle button while keyboard focused.
Fixes #4147
- Bugfix
=> fix: prevent mousedown event for toggle button

packages/combo-box/src/vaadin-combo-box-light.d.ts, packages/combo-box/src/vaadin-combo-box.d.ts, packages/combo-box/test/typings/combo-box.types.ts, packages/grid/src/vaadin-grid.d.ts, packages/grid/test/typings/grid.types.ts, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.d.ts, packages/multi-select-combo-box/test/typings/multi-select-combo-box.types.ts
The `theme` property is missing type definition in the following components:
- `<vaadin-grid>`
- `<vaadin-combo-box>`
- `<vaadin-combo-box-light>`
- `<vaadin-multi-select-combo-box>`
This PR fixes the issue by adding the missing `ThemePropertyMixinClass` to the element type
=> docs: add missing theme property type

packages/grid/theme/lumo/vaadin-grid-styles.js
Related to #4241
The font-size CSS property has been added to the `vaadin-checkbox` Lumo styles in #2746:
https://github.com/vaadin/web-components/blob/4fb709e15e78a2e1d12c7f38e5a28bfa7f028442/packages/checkbox/theme/lumo/vaadin-checkbox-styles.js#L14
So we can now remove these styles from grid to avoid warning when importing grid after the checkbox.
- Refactor
=> refactor: cleanup no longer needed styles

packages/combo-box/src/vaadin-combo-box-light.js, packages/combo-box/src/vaadin-combo-box.js, packages/combo-box/test/dom/__snapshots__/combo-box.test.snap.js, packages/combo-box/test/internal-filtering.test.js, packages/combo-box/test/toggling-dropdown.test.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js, packages/time-picker/src/vaadin-time-picker-combo-box.js
The logic for setting `hidden` attribute on the overlay comes from an old implementation: https://github.com/vaadin/vaadin-combo-box/pull/569. Later when we discovered an issue caused by it in the time-picker https://github.com/vaadin/vaadin-time-picker/issues/58, we changed to set `opened` to `false` - see https://github.com/vaadin/vaadin-combo-box/pull/684 and https://github.com/vaadin/vaadin-combo-box/pull/964. But the old logic was not removed.
In fact, there is no need to set `hidden` as removing `opened` is enough to hide the overlay:
https://github.com/vaadin/web-components/blob/9cd686c08ad9b2d53bfbc561e251720bb0bf7344/packages/vaadin-overlay/src/vaadin-overlay.js#L145-L148
Finally, as you can see here, the logic to set `hidden` and `opened` has some duplicated checks: …
=> refactor: do not set hidden attribute on the overlay

packages/component-base/src/focus-trap-controller.js, packages/component-base/test/focus-trap-controller.test.js
When pressing <kbd>Tab</kbd>, it is expected that `<input>` elements get selected. This does not apply to `<textarea>` elements.
Updated the `FocusTrapController()` to detect which element should gain focus and then call `.select()` if needed.
Fixes Vaadin/flow-components#3488
- Bugfix
=> fix: select an input element when focusing

packages/field-base/src/input-field-mixin.js, packages/field-base/test/input-field-mixin.test.js
Fixes #1395
Updated `InputFieldMixin` to align with other components (e.g. `vaadin-combo-box`, `vaadin-select`, `vaadin-time-picker`).
- Refactor
=> refactor: validate input field on programmatic blur

packages/integer-field/test/validation.test.js, packages/number-field/src/vaadin-number-field.js, packages/number-field/test/validation.test.js
The PR overrides `checkValidity` for `number-field` to force it to check for bad user input before anything else. 
Earlier, `number-field` could stay valid after you have entered something bad in the case there were no constraints specified. This behavior was coming from `InputConstraintsMixin` which doesn't check native validity when no constraints. This is generally correct behavior. The exception is `input[type=number]` fields where the native `checkValidity` also checks for bad input.
Fixes #4258
=> fix: force the validation to check for bad user input

packages/dialog/src/vaadin-dialog.js, packages/dialog/test/header-footer.test.js
Fixes #3629
This is a behavior altering change: it might end up with user-defined styles for `h2` getting applied to header title.
As mentioned in https://github.com/vaadin/web-components/issues/3629#issuecomment-1128818281, it's still possible to provide a custom header without using `headerTitle`.
In order to ensure that CSS defined on `[part='title']` keeps working, I added the `font: inherit !important` rule.
This is necessary because otherwise, the default global styles from Lumo would override the dialog theme:
https://github.com/vaadin/web-components/blob/f227392d2a6d590ed71052c0ab638ff2b38d17e2/packages/vaadin-lumo-styles/typography.js#L59-L60
https://github.com/vaadin/web-components/blob/f227392d2a6d590ed71052c0ab638ff2b38d17e2/packages/vaadin-lumo-styles/typography.js#L70
Using …
=> refactor!: use `h2` element for dialog header title

packages/time-picker/src/vaadin-time-picker.js, packages/time-picker/test/time-picker.test.js, packages/time-picker/test/validation.test.js
Currently, the `_valueChanged` observer always tries to update `<input>` value when `value` is set to empty string.
This shouldn't happen when setting `value` to empty string is done as a result of committing invalid user input.
Looks like adding a flag in this case is the only way to reliably distinguish from case when `value` is cleared by the app logic (e.g.  when pressing "Reset" button to clear all the fields in the form) - in that case the  `<input>` value should be still cleared.
Fixes #4246
- Bugfix
=> fix: keep invalid user input when clearing value

packages/field-base/src/input-mixin.d.ts, packages/field-base/src/input-mixin.js, packages/field-base/test/input-mixin.test.js, packages/time-picker/src/vaadin-time-picker.js
Introduce `__inputValuePopulated` property and `input-value-populated-changed` event which will be used from the Flow counter-part.
Needed for the cases when value is not synced with the flow counter-part because of type differences. For example, in case of date-picker flow counterpart is not notified about inputing arbitrary string `qwerty` therefore it cannot be properly validated.
Event is not documented on purpose as intended for internal use.
Related: https://github.com/vaadin/flow-components/pull/3524.
=> feat: add internal has-input-value-changed event

packages/time-picker/test/combo-box.test.js, packages/time-picker/test/helpers.js, packages/time-picker/test/time-picker.test.js
1. Updated some tests to use `setInputValue()` helper of `fire()` helper
2. Updated one test to use `outsideClick()` helper to makes it more clear 
3. Changed checks for `comboBox.value` to use `inputElement.value`
4. Replaced setting `comboBox.value` with  `setInputValue()` helper
- Tests
=> test: update and improve time-picker user input tests

packages/grid/src/vaadin-grid-multi-sort-priority-append.js, packages/grid/src/vaadin-grid-sort-mixin.js, packages/grid/test/multi-sort-priority.test.js
Fixes #4189
This PR adds a new file that can be imported to enable the new behavior by default when using web component / Hilla.
Note: this file won't be used by the Flow counterpart - there will be a separate PR for Flow instead to handle that.
- Feature
=> feat: add feature flag to control multiSortPriority

packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/test/toggling-dropdown.test.js
Fixes #3363
Tested this using VoiceOver on iOS. With this fix, the focus moves to item, so it can be selected by using double tap.
Check out the screen recording with sound turned on to hear VoiceOver announcements:
https://user-images.githubusercontent.com/10589913/182129731-69a05f12-2ae1-4201-9dc6-8149aea9a4d2.mp4
- Bugfix
=> fix: do not close overlay with iOS VoiceOver

packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/test/toggling-dropdown.test.js
Cherry-pick of #4279 to `23.1` branch. Automated cherry-pick failed due to conflict in import in tests.
- Cherry-pick
=> fix: do not close overlay with iOS VoiceOver (#4279) (CP: 23.1)

packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/test/toggling-dropdown.test.js
Cherry-pick of #4279 to `23.0` branch. Automated cherry-pick failed due to conflict in import in tests.
- Cherry-pick
=> fix: do not close overlay with iOS VoiceOver (#4279) (CP: 23.0)

packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/test/toggling-dropdown.test.js
Cherry-pick of #4279 to `22.0` branch. Automated cherry-pick failed due to conflict in import in tests.
- Cherry-pick
=> fix: do not close overlay with iOS VoiceOver (#4279) (CP: 22.0)

packages/charts/src/vaadin-chart.js, packages/charts/test/exporting.test.js
The chart export was failing with a mostly black export. Added styled-mode attribute to body before a chart export and removed it afterwards. Added the relevant integration test.
Fixes [#3508](https://github.com/vaadin/flow-components/issues/3508)
=> fix: add and remove styled-mode attribute during chart exports

packages/combo-box/src/vaadin-combo-box-light.js, packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/test/combo-box-light.test.js, packages/combo-box/test/item-template.test.js, packages/combo-box/test/lazy-loading.test.js
Fixes #4050
In Vaadin 14, we only had ARIA attributes set on the `input` when using `<vaadin-combo-box>`, see [this code](https://github.com/vaadin/vaadin-combo-box/blob/0e6848c31aae7bb406252240496ef51a5889316b/src/vaadin-combo-box.html#L390).
After changing to use new mixin structure in Vaadin 22, all the ARIA logic was moved to `ComboBoxMixin`.
This PR restores `_nativeInput` getter and overrides it in `<vaadin-combo-box-light>` to detect native `<input>`.
In order to make it work, we need to postpone checking `inputElement` using `afterNextRender()` call.
Otherwise, the slotted `<input>` in case of using `<vaadin-text-field>` would not yet be created.
Note, this is a behavior altering fix as requires users who rely on synchronous presence of `inputElement` to update their tests, …
=> fix: set ARIA attributes on the native input

packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/src/vaadin-date-picker-overlay-content.js, packages/date-picker/test/basic.test.js, packages/date-picker/test/common.js, packages/date-picker/test/keyboard-input.test.js, packages/date-picker/test/keyboard-navigation.test.js
This PR aims to address two problems related to focusing the date element and make it more reliable.
When clicking `vaadin-date-picker` in `fullscreen` mode, it opens and attempts to focus the date immediately.
This logic currently uses a promise that resolves after `requestAnimationFrame()`:
https://github.com/vaadin/web-components/blob/8e74163e2d7a47d43500015297bb81cb14403b18/packages/date-picker/src/vaadin-date-picker-overlay-content.js#L864-L866
However, this is not reliable because in some cases `vaadin-infinite-list` does not create `vaadin-month-calendar` elements by the time when `__tryFocusDate()` is called,  so `focusableDateElement` returns `undefined`.
In this case, trying to focus date element silently fails, so we end up with the following behavior: …
=> refactor: ensure date is rendered before focusing

packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/test/dropdown.test.js
This logic was added in https://github.com/vaadin/vaadin-date-picker/pull/77 as a fix for https://github.com/vaadin/vaadin-date-picker/issues/66. Back in the day, the `vaadin-date-picker` was using `iron-dropdown`, which was not teleported under document body.
Now when we use `vaadin-overlay`, the original clipping issue is no longer applicable. Also, starting from Safari 13, the prefixed [`-webkit-overflow-scrolling`](https://caniuse.com/mdn-css_properties_-webkit-overflow-scrolling) property is no longer supported - see [release notes](https://developer.apple.com/documentation/safari-release-notes/safari-13-release-notes). Let's remove this code.
- Refactor
=> refactor: remove obsolete iOS touch workaround

packages/combo-box/src/vaadin-combo-box-light.js, packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/test/combo-box-light.test.js, packages/combo-box/test/item-template.test.js, packages/combo-box/test/lazy-loading.test.js
Manual cherry-pick of #4295 to `23.1` branch. The automated cherry-pick failed due to conflict in imports in tests.
- Cherry-pick
=> fix: set ARIA attributes on the native input (#4295) (CP: 23.1)

packages/date-picker/src/vaadin-date-picker-overlay-content.js, packages/date-picker/test/keyboard-input.test.js
Fixes #3918
This PR fixes the a11y issue by making sure that keyboard focus stays in `vaadin-date-picker-overlay` when `fullscreen` mode is used. At the same time, `stopPropagation()` call for `keydown` events is removed as no longer needed.
- Bugfix
=> fix: trap focus in the overlay when fullscreen

packages/component-base/src/active-mixin.js, packages/component-base/test/active-mixin.test.js
Using `keyup` listener on the element where the `keydown` was fired is not reliable, because the `keyup` event will not fire on the element that gets hidden by setting `hidden` attribute. Instead, it will fire on the `<body>` element.
Fixes https://github.com/vaadin/flow-components/issues/3552
- Bugfix
=> fix: use global keyup listener to remove active

dev/dialog.html
The `dialog.html` dev page uses wrong import that includes legacy iconset and causes a warning in the console.
Actually, there is no need to import icons separately, as they come with Lumo styles through `common.js` file.
=> chore: remove legacy iconset import from dev page

packages/confirm-dialog/README.md, packages/cookie-consent/README.md, packages/crud/README.md, packages/grid-pro/README.md
Some Pro components packages have been created based on `vaadin-details` and then updated to replace all of the occurrences of `details` which ended up with some weird-looking copy-paste leftovers 🤦‍♂️ 
=> chore: fix copy-paste leftovers in README

packages/confirm-dialog/src/vaadin-confirm-dialog.d.ts, packages/cookie-consent/src/vaadin-cookie-consent.d.ts, packages/crud/src/vaadin-crud-edit-column.d.ts, packages/crud/src/vaadin-crud-edit.d.ts, packages/crud/src/vaadin-crud-form.d.ts, packages/crud/src/vaadin-crud-grid.d.ts, packages/crud/src/vaadin-crud-include-mixin.d.ts, packages/crud/src/vaadin-crud.d.ts
Some Pro components had their `d.ts` files created using a copy-paste from free components, and therefore used the wrong license header mentioning Apache 2.0 instead of CVDL 4.0 license. Updated these to use correct license.
=> chore: fix Pro components types license headers

packages/grid-pro/src/lit/column-renderer-directives.d.ts, packages/grid-pro/src/lit/column-renderer-directives.js, packages/grid-pro/src/vaadin-grid-pro-edit-checkbox.js, packages/grid-pro/src/vaadin-grid-pro-edit-column.d.ts, packages/grid-pro/src/vaadin-grid-pro-edit-column.js, packages/grid-pro/src/vaadin-grid-pro-edit-select.js, packages/grid-pro/src/vaadin-grid-pro-edit-text-field.js, packages/grid-pro/src/vaadin-grid-pro-inline-editing-mixin.d.ts, packages/grid-pro/src/vaadin-grid-pro-inline-editing-mixin.js, packages/grid-pro/src/vaadin-grid-pro.d.ts, packages/grid-pro/src/vaadin-grid-pro.js
The `grid-pro` package was using a different license header format. Changed it to align with other Pro components.
=> chore: align license header with other components

packages/date-picker/test/basic.test.js, packages/date-picker/test/common.js, packages/date-picker/test/keyboard-input.test.js, packages/date-picker/test/keyboard-navigation.test.js
Follow-up to #4296. 
It looks like some newly added tests are flaky, most likely due to animated scroll to date.
Changed `revealDate()` calls to scroll immediately, this should make it more stable.
Also, some other tests were failing on `master` so I made other tweaks to setup.
- Tests
=> test: improve date focus tests to reduce flakiness

packages/field-base/src/helper-controller.d.ts, packages/field-base/src/helper-controller.js, packages/vaadin-charts/src/vaadin-chart-series.d.ts, packages/vaadin-charts/src/vaadin-chart-series.js, packages/vaadin-charts/src/vaadin-chart.d.ts, packages/vaadin-charts/src/vaadin-chart.js, packages/vaadin-charts/theme/lumo/vaadin-chart.js, packages/vaadin-charts/theme/material/vaadin-chart.js, packages/vaadin-charts/theme/vaadin-chart-base-theme.js
The year was changed in #3247 but there are few files still using `2021`, updated those.
=> chore: update year in license headers to 2022

packages/field-base/src/input-mixin.js, packages/field-base/test/input-mixin.test.js
It turns out that `TimePicker` prevents the `change` event on the input element until it loses focus, so it is possible to commit a non-empty value on <kbd>Enter</kbd> but have the `hasInputValue` state not updated. 
This PR makes the `hasInputValue` state update on `input` rather than `change` which ensures `hasInputValue` is synced in the above case as well.
A follow-up to https://github.com/vaadin/web-components/pull/4276
Related to https://github.com/vaadin/flow-components/pull/3515
=> fix: sync the hasInputValue state on input

packages/vaadin-list-mixin/test/list-mixin.test.js, packages/vaadin-list-mixin/vaadin-list-mixin.js
Support list items slotted through a wrapping Web Component.
Related to https://github.com/vaadin/platform/issues/3152
=> fix: assign flattened nodes as list-mixin items

packages/field-highlighter/test/user-tags.test.js, packages/vaadin-list-mixin/test/list-mixin.test.js, packages/vaadin-list-mixin/vaadin-list-mixin.js
Fixes list-mixin keyboard navigation when the list items are slotted through a wrapping Web Component.
Related to https://github.com/vaadin/platform/issues/3152
=> fix: improve how list-mixin finds the focused item

packages/date-picker/src/vaadin-date-picker-light.js, packages/date-picker/src/vaadin-date-picker.js, packages/date-picker/test/validation.test.js
Fixes #4339
The `vaadin-overlay-closing` event was added in #3144 because the `vaadin-overlay-close` doesn't guarantee the overlay will be closed. This is exactly the case with date-picker which prevents closing on click inside of the `<input>`:
https://github.com/vaadin/web-components/blob/9f4a2acfd8caf464056732be729ffa056fbf3656/packages/date-picker/src/vaadin-date-picker.js#L230-L232
Updated to use the correct event, also added a test for not validating on `<input>` click while opened.
- Bugfix
=> fix: use correct event to detect overlay closing

packages/date-picker/src/vaadin-date-picker-light.js, packages/date-picker/src/vaadin-date-picker.js, packages/date-picker/test/form-input.test.js
Manual cherry-pick of #4340 to `23.1` branch. The conflict was caused to the test file renamed on master.
- Cherry-pick
=> fix: use correct event to detect overlay closing (#4340) (CP: 23.1)

packages/combo-box/test/basic.test.js
Updated some combo-box unit tests to use `setInputValue()` and `outsideClick()` helpers.
- Tests
=> test: use helpers for value entering tests

packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/src/vaadin-date-picker.js, packages/date-picker/test/basic.test.js, packages/date-picker/test/common.js, packages/date-picker/test/dropdown.test.js
Fixes #4154
TL;DR: after `focus-ring` is set after focusing with keyboard, only remove it on blur when the overlay is closed.
Currently, the logic for restoring `focus-ring` in the date-picker is broken. The following happens when closing on click:
1. Focus is lost to the `<body>` (in case of outside click) or `<td>` inside of `<vaadin-month-calendar>` (cell click),
2. The `focusout` event is fired on the `<input>` and `_setFocused(false)` removes the `focus-ring` attribute,
3. The [logic](https://github.com/vaadin/web-components/blob/9e022ac3f50fa9a40ab33c0cf0a5fa2a4bc5103b/packages/date-picker/src/vaadin-date-picker.js#L225-L226) trying to set `focus-ring` is called too early, as the focus hasn't been restored to the `<input>` yet,
3. After a timeout, `vaadin-overlay` restores focus, …
=> fix: restore focus-ring when closing on click

packages/date-picker/test/basic.test.js, packages/date-picker/test/dropdown.test.js
1. Moved some tests for clear and toggle buttons to corresponding suites
2. Removed an obsolete fixture for testing the wrapped date-picker 
- Tests
=> test: update and cleanup date-picker tests

packages/date-picker/src/vaadin-date-picker-overlay-content.js, packages/date-picker/test/overlay.test.js
Using `stopPropagation()` was added in https://github.com/vaadin/vaadin-date-picker/pull/278 to prevent re-opening date-picker on selecting date (https://github.com/vaadin/vaadin-date-picker/issues/250). Back in the day, the component was using `iron-dropdown` which was not teleported under `<body>`, so its events like `tap` could bubble from there to `vaadin-date-picker` host element, causing this issue.
Removed this logic as the underlying issue no longer happens after switching to use `vaadin-overlay`.
- Refactor
=> refactor: cleanup obsolete tap event logic

packages/date-picker/src/vaadin-date-picker-overlay-content.js, packages/date-picker/test/overlay.test.js
We shouldn't use custom attributes like `desktop` and `showclear` to toggle hidden state. Let's use `hidden` instead.
Note: the "Clear" button in the `fullscreen` overlay is currently on available in Material theme, but not in Lumo.
- Refactor
=> refactor: use hidden instead of custom attributes

packages/date-picker/src/vaadin-date-picker-mixin.js
Using `stopPropagation()` for `close` and `date-tap` events was added in https://github.com/vaadin/vaadin-date-picker/commit/872df2ce04865e2f0a2f7c95f7e2782bdb9dfc05. Back in the day, `vaadin-date-picker` was using `iron-dropdown` internally, which wasn't teleported to `body`, so these events could bubble.
Now when we have `vaadin-date-picker-overlay-content` teleported, I don't see a problem in bubbling, as these events will not fire on the `vaadin-date-picker` element. Also, we already have `date-selected` event not using `stopPropagation()`.
- Refactor
=> refactor: remove not needed stopPropagation

packages/date-picker/test/basic.test.js, packages/date-picker/test/dropdown.test.js, packages/date-picker/test/validation.test.js
Currently, `basic.test.js` is somewhat bloated, so I moved some tests around to make it a bit cleaner:
1. Moved tests for scrolling to date into `dropdown.test.js`, as they are related to opening the overlay,
2. Moved one test for `min` and `max` to validation suite, as it checks for `invalid-changed` event.
- Tests
=> test: reorganize tests for scrolling to date

packages/date-picker/test/keyboard-input.test.js, packages/date-picker/test/validation.test.js
Moved a few validation-related tests from `keyboard-input.test.js` to `validation.test.js` file.
- Tests
=> test: move validation tests to correct file

packages/date-picker/src/vaadin-date-picker-mixin.js
Simplified logic to fire `change` event after using clears the `<input>` value and then blurs the date-picker.
- Refactor
=> refactor: simplify empty input change logic

packages/map/package.json
We missed to add Lumo and Material dependencies to `@vaadin/map` when implementing themes. This PR fixes it.
- Bugfix
=> fix: add missing Lumo and Material dependencies

packages/map/package.json
Manual cherry-pick of #4355 to `23.1` branch.
- Cherry-pick
=> fix: add missing Lumo and Material dependencies (CP: 23.1)

packages/field-base/test/input-constraints-mixin.test.js
This PR removes `maxlength` constraint unit tests as they duplicate `minlength` ones.
=> test: drop redundant InputConstraintsMixin unit tests
