vaadin/web-components

packages/combo-box/src/vaadin-combo-box-mixin.js, packages/date-picker/src/vaadin-date-picker-mixin.js, packages/field-base/src/input-mixin.d.ts, packages/field-base/src/input-mixin.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/time-picker/src/vaadin-time-picker.js
This PR adds a `_hasValue` getter to `InputMixin` that indicates whether the value is different from the default one. 
This getter is supposed to be overridden in components whose `value` property has a type other than `string`. 
This getter is needed for https://github.com/vaadin/web-components/pull/4359 to make `InputConstraintsMixin` correctly determine if the value is empty in order to prevent `multi-select-combo-box` from being validated on `required` change because it relies on `selectedItems` when computing the presence of value rather than `value`.
=> refactor: add _hasValue getter to InputMixin

packages/multi-select-combo-box/test/basic.test.js, packages/multi-select-combo-box/test/validation.test.js
- Extracted validation tests into a separate file `validation.test.js`
- Added tests ensuring no initial validation happens.
- Added a test ensuring no validation happens on required constraint change. It is needed to ensure [#4359](https://github.com/vaadin/web-components/pull/4359) works well for components whose value property has a type other than `string` or value is represented by other property than `value`, e.g. `selectedItems` in `multi-select-combo-box`.
=> test: improve validation test coverage

packages/field-base/src/input-constraints-mixin.js, packages/field-base/test/input-constraints-mixin.test.js
This PR modifies `InputConstraintsMixin` to run validation on constraint change not only when the component is invalid but also when `value` is present.
> **Warning**
> Behavior altering change
Depends on 
- https://github.com/vaadin/web-components/pull/4363
- https://github.com/vaadin/web-components/pull/4362
Part of #4196
=> refactor!: validate on constraint change when value is present

packages/component-base/src/focus-mixin.js, packages/component-base/src/focus-utils.d.ts, packages/component-base/src/focus-utils.js, packages/component-base/test/focus-utils.test.js
This change is needed for `vaadin-tooltip` which is expected to open on keyboard focus only.
As we are not going to use `FocusMixin` in this component, we need a separate helper for it.
- Refactor
=> refactor: move isKeyboardActive to focus utils

packages/field-base/test/input-constraints-mixin.test.js, packages/text-field/test/text-field.test.js
This PR moves some validation tests from `text-field` to `input-constraints-mixin.test.js` as they make sense for `InputConstraintsMixin` in general.
Part of #4371
=> test: move some validation tests to field-base

packages/time-picker/src/vaadin-time-picker.js, packages/time-picker/test/validation.test.js
The PR declares the properties `max` and `min` as constraints to activate `InputConstraintsMixin`'s logic for them.
Part of #4371
=> refactor(time-picker): declare properties max and min as constraints

packages/email-field/test/email-field.test.js
The PR removes some `email-field` unit tests ensuring the initial `invalid` is not overridden. These tests are redundant because there is already an `initial validation` test suite that determines when the initial validation should happen and when not, which in practice also ensures that `invalid` will not be overridden.
Part of #4371
=> test: remove redundant unit tests

packages/tooltip/src/vaadin-tooltip-controller.d.ts, packages/tooltip/src/vaadin-tooltip-controller.js, packages/tooltip/test/tooltip-controller.test.js
Added `TooltipController` to manage the slotted tooltip. For now, only `target` is supported.
There will be a separate PR adding `text` property and `textGenerator` function.
- Feature
This PR is targeting the feature branch, not `master`.
=> feat: add TooltipController allowing to set target

packages/tooltip/src/vaadin-tooltip.js, packages/tooltip/test/tooltip.test.js
Added event listeners to open and close tooltip overlay.
- Feature
This PR is targeting the feature branch, not `master`.
=> feat: add listeners to open and close tooltip

packages/date-picker/src/vaadin-date-picker-mixin.d.ts, packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/test/typings/date-picker.types.ts
The PR declares the properties `max` and `min` as constraints to let `InputConstraintsMixin` take care of them instead of maintaining custom logic.
Part of https://github.com/vaadin/web-components/issues/4371
=> refactor(date-picker): declare properties `max` and `min` as constraints

dev/tabsheet.html, packages/tabsheet/package.json, packages/tabsheet/src/vaadin-tabsheet.d.ts, packages/tabsheet/src/vaadin-tabsheet.js, packages/tabsheet/test/dom/__snapshots__/tabsheet.test.snap.js, packages/tabsheet/test/dom/tabsheet.test.js, packages/tabsheet/test/tabsheet.test.js, packages/tabsheet/test/typings/tabsheet.types.ts, packages/tabsheet/theme/lumo/vaadin-tabsheet.js, packages/tabsheet/theme/material/vaadin-tabsheet.js
Added `vaadin-tabsheet` element with basic features.
Excluded from this PR (to be submitted separately):
- Themes, theme variants, visual tests
- Loading state and loading indicator
- Feature
This PR is targeting the feature branch, not `master`.
=> feat: add tabsheet with basic features

packages/tooltip/src/vaadin-tooltip.d.ts, packages/tooltip/src/vaadin-tooltip.js, packages/tooltip/test/tooltip.test.js, packages/tooltip/test/typings/tooltip.types.ts
Added `text`, `textGenerator` and `context` (name to be decided) properties to `vaadin-tooltip`.
- Feature
=> feat: add text, textGenerator and context properties

packages/tooltip/src/vaadin-tooltip.js, packages/tooltip/test/dom/__snapshots__/tooltip.test.snap.js
Changed the default appearance of the overlay to not overlap target element.
This will be adjusted later on when adding `position` property.
- Refactor
=> refactor: set no-vertical-overlap to tooltip overlay

packages/tooltip/src/vaadin-tooltip.d.ts, packages/tooltip/src/vaadin-tooltip.js, packages/tooltip/test/tooltip.test.js, packages/tooltip/test/typings/tooltip.types.ts
Added `manual` and `opened` properties to `vaadin-tooltip` based on the prototype.
- Feature
=> feat: add manual and opened tooltip properties

packages/date-time-picker/src/vaadin-date-time-picker.js, packages/date-time-picker/test/validation.test.js
The PR ensures `date-time-picker` is validated on constraint change when it has a value. Since `InputConstraintsMixin` only supports constraints for a single target element, it cannot be used for `date-time-picker`, so I had to come up with a custom implementation.
Part of #4371
=> refactor!: validate on constraint change when field has value

dev/tooltip.html, packages/tooltip/src/vaadin-tooltip-overlay.js, packages/tooltip/src/vaadin-tooltip.d.ts, packages/tooltip/src/vaadin-tooltip.js, packages/tooltip/test/dom/__snapshots__/tooltip.test.snap.js, packages/tooltip/test/dom/tooltip.test.js, packages/tooltip/test/tooltip-position.test.js, packages/tooltip/test/typings/tooltip.types.ts
Added `position` property and corresponding unit tests, also updated snapshot tests to use `position`.
Visual tests will be added in a separate PR on top of this one, together with Lumo and Material themes.
Here is the overview of all the 12 supported `position` property values:
- Feature
- The PR targets `tooltip` feature branch, not `master` branch.
=> feat: add position property to tooltip

packages/date-picker/src/vaadin-date-picker-overlay-content.js, packages/date-picker/theme/lumo/vaadin-date-picker-overlay-content-styles.js, packages/date-picker/theme/material/vaadin-date-picker-overlay-content-styles.js
The `[part='year-toggle-button']::before` pseudo-element was removed in https://github.com/vaadin/vaadin-date-picker/pull/628.
Removed leftover styles that are unused since then, as the pseudo-element does not exist. 
- Refactor
=> refactor: remove no longer used pseudo-element

packages/date-picker/theme/lumo/vaadin-date-picker-overlay-content-styles.js
Removed usage of `@supports` which was added in https://github.com/vaadin/vaadin-lumo-styles/commit/7e67dcfbdb83cb643ba8354d479bb21b6e8e28aa when we still supported IE11.
This is no longer needed as modern browsers support [`mask-image`](https://caniuse.com/mdn-css_properties_mask-image) used for `[part='months']` and `[part='years']`.
- Refactor
=> refactor: cleanup mask-image support detection

packages/custom-field/src/vaadin-custom-field.d.ts, packages/custom-field/src/vaadin-custom-field.js, packages/custom-field/test/keyboard.test.js
The workaround was added in https://github.com/vaadin/vaadin-custom-field/pull/54 to enable using `vaadin-custom-field` in Shadow DOM of the `vaadin-date-time-picker` element. Back then, there was an issue related to <kbd>Shift</kbd> + <kbd>Tab</kbd> (see the `FIXME` comment).
The Chrome bug is now [fixed](https://bugs.chromium.org/p/chromium/issues/detail?id=1014868#c21) so the workaround is no longer needed. The test is also removed, as it tests the workaround.
Also, in Vaadin 22 we changed `vaadin-date-time-picker` to not be based on `vaadin-custom-field` anyways.
- Refactor
=> refactor: remove no longer needed Chrome workaround

packages/field-base/test/validate-mixin.test.js, packages/radio-group/test/radio-group.test.js
Moved some `radio-group` unit tests to `validate-mixin.test.js` as those tests are actually testing `ValidateMixin`.
=> test: move some unit tests to field-base

packages/time-picker/src/vaadin-time-picker.js, packages/time-picker/test/time-picker.test.js
This PR sets the default value for the `time-picker` properties `min` and `max` to an empty string. This is needed to prevent `InputConstraintsMixin` from treating these properties as active constraints by default once we declare them in `static get constraints` which will be done in the next PR. 
And, in general, it is not convenient for the user when `min` and `max` have a non-empty default value because then neither `null` nor an empty string can be used to reset them.
> **Warning**
> A minor breaking change
Extracted from https://github.com/vaadin/web-components/pull/4386
Part of https://github.com/vaadin/web-components/issues/4371
=> refactor!: set an empty string as default value for min and max

packages/combo-box/theme/lumo/vaadin-combo-box-dropdown-styles.js, packages/combo-box/theme/material/vaadin-combo-box-dropdown-styles.js, packages/vaadin-lumo-styles/mixins/loader.d.ts, packages/vaadin-lumo-styles/mixins/loader.js, packages/vaadin-material-styles/mixins/loader.d.ts, packages/vaadin-material-styles/mixins/loader.js
This PR extracts the loading indicator styles used in `<vaadin-combo-box-overlay>` as separate lumo/material mixins so that they can be [reused](https://github.com/vaadin/web-components/commit/3407e98e79d9f90ce50bfe3c176edb01bf93b703) in `<vaadin-tabsheet>`.
Suggested in https://github.com/vaadin/web-components/pull/4391#discussion_r955000311.
=> refactor: extract loader mixin from combo-box styles

packages/tooltip/src/vaadin-tooltip-controller.d.ts, packages/tooltip/src/vaadin-tooltip-controller.js, packages/tooltip/test/tooltip-controller.test.js
Added `context`, `manual` and `opened` properties to `TooltipController` with methods to set them.
Also added two events to update `context` and `opened` for using by `vaadin-grid` integration.
- Feature
=> feat: add more properties to TooltipController

packages/context-menu/test/context.test.js, packages/context-menu/test/integration.test.js, packages/context-menu/test/overlay.test.js, packages/context-menu/test/properties.test.js, packages/context-menu/test/selection.test.js, packages/context-menu/test/touch.test.js, packages/context-menu/test/visual/lumo/context-menu.test.js, packages/context-menu/test/visual/material/context-menu.test.js
Updated unit and visual tests for `vaadin-context-menu` to use `renderer` function instead of `<template>`.
- Tests
=> test: update context-menu tests to use renderer

packages/vaadin-lumo-styles/mixins/loader.js
After the color changes in 23, the contrast between the primary and primary-50pct colors is barely noticeable in the spinner.
Use primary-10pct for the other half instead.
=> Fix: increase contrast between spinner halves

packages/text-field/test/validation.test.js
This PR adds unit tests that ensure initial validation for `text-field` when it has constraints and value. 
Extracted from https://github.com/vaadin/web-components/pull/4386
Part of https://github.com/vaadin/web-components/issues/4371
=> test(text-field): ensure initial validation when the field has constraints and value

packages/tabsheet/src/vaadin-tabsheet.d.ts, packages/tabsheet/src/vaadin-tabsheet.js, packages/tabsheet/test/tabsheet.test.js
Adds the `overflow` attribute to `<vaadin-tabsheet>`
- Feature
This PR is targeting the `feat/tabsheet` feature branch, not `master`.
=> feat: add overflow attribute to tabsheet

packages/tooltip/src/vaadin-tooltip.d.ts, packages/tooltip/src/vaadin-tooltip.js, packages/tooltip/test/helpers.js, packages/tooltip/test/tooltip-timers.test.js, packages/tooltip/test/tooltip.test.js
Added `delay` and `hideDelay` properties to `vaadin-tooltip` based on the prototype.
- Feature
=> feat: add delay and hideDelay to tooltip

packages/email-field/src/vaadin-email-field.js, packages/email-field/test/email-field.test.js
This PR ensures initial validation for `email-field` when it has constraints and value. Unlike other components, in the case of `email-field`, it means that the initial validation will always happen initially when it has value since there is a default pattern constraint. 
In case the user wants to control `invalid` manually, the default pattern can be disabled by providing a custom empty pattern:
```html
<vaadin-email-field value="user@example.com" pattern="" invalid></vaadin-email-field>
```
> **Warning**
> It is a kind of breaking change because manual `invalid` control is no longer possible when the field has a value unless the user disables the default pattern explicitly.
Extracted from https://github.com/vaadin/web-components/pull/4386
Part of …
=> refactor!: ensure initial validation with constraints and value

packages/text-area/test/validation.test.js
This PR adds unit tests that ensure initial validation for `text-area` when it has constraints and value. 
Extracted from https://github.com/vaadin/web-components/pull/4386
Part of https://github.com/vaadin/web-components/issues/4371
=> test: ensure initial validation with constraints and value

packages/tabsheet/package.json, packages/tabsheet/src/vaadin-tabsheet-scroller.js, packages/tabsheet/src/vaadin-tabsheet.js, packages/tabsheet/test/dom/__snapshots__/tabsheet.test.snap.js, packages/tabsheet/theme/lumo/vaadin-tabsheet.js, packages/tabsheet/theme/material/vaadin-tabsheet.js
The scrollable content area of `<vaadin-tabsheet>` should be keyboard focusable. This PR changes the content element to be a `<vaadin-scroller>` extension.
- Refactor
This PR is targeting the `feat/tabsheet` feature branch, not `master`.
=> refactor: use scroller for tabsheet content

packages/tooltip/src/vaadin-tooltip-overlay.js, packages/tooltip/test/dom/__snapshots__/tooltip.test.snap.js, packages/tooltip/test/tooltip.test.js
When using manual mode, currently the tooltip remains visible even if `textGenerator` returns an empty string.
Changed to set `hidden` attribute so that the overlay is visually hidden even though `opened` is still `true`.
- Bugfix
=> fix: hide overlay when tooltip text is cleared

.eslintrc.json, packages/component-base/src/slot-controller.d.ts, packages/component-base/src/slot-controller.js, packages/field-base/src/error-controller.js, packages/field-base/src/helper-controller.js, packages/field-base/src/input-controller.js, packages/field-base/src/label-controller.js, packages/field-base/src/text-area-controller.js
Currently, creating an instance of `SlotController` always generates a unique ID in the constructor.
In practice, this ID is only used by controllers responsible for handling `label`, `helper-text` etc.
Now when we have other controllers e.g. `TooltipController`, this creates problems with snapshots.
Even though the generated ID is actually unused, it still gets reserved, thus increasing the counter.
Updated `SlotController` to add an extra constructor argument to explicitly make this opt-in.
- Refactor
=> refactor: make generating unique controller ID opt-in

packages/component-base/src/polylit-mixin.js, packages/component-base/test/polylit-mixin.test.js, packages/field-base/test/input-constraints-mixin.test.js
Lit invokes `firstUpdated()` before `updated()`, so `ready()` is currently executed before observers. This sometimes leads to race conditions when `ready()` changes properties that are dependencies of observers. See https://github.com/vaadin/web-components/pull/4413#discussion_r957747377 for the real case.
The PR moves the `ready()` call from `firstUpdated()` to the end of `updated()` to guarantee that observers are run before it.
=> fix: invoke ready() only after observers 

packages/tabsheet/package.json
`@vaadin/field-base/src/delegate-state-mixin.js` is used in `vaadin-tabsheet.js`. Add the missing dependency to `@vaadin/field-base`
=> fix: add missing field-base dependency to tabsheet

packages/tooltip/src/vaadin-tooltip-controller.js, packages/tooltip/test/tooltip-controller.test.js
Removed events as they aren't necessary. Instead, it's better to use the controller methods.
- Refactor
=> refactor: remove TooltipController events

packages/date-picker/src/vaadin-date-picker-overlay-content.js, packages/date-picker/theme/lumo/vaadin-date-picker-overlay-content-styles.js, packages/date-picker/theme/material/vaadin-date-picker-overlay-content-styles.js
Using `#fff` in core styles does not bring much value and is problematic when the dark theme is used.
Removed this as it should be theme's responsibility to set the background. Also removed overrides.
- Refactor
=> refactor: do not set overlay content background

packages/date-picker/src/vaadin-date-picker-overlay-content.js, packages/date-picker/theme/lumo/vaadin-date-picker-overlay-content-styles.js, packages/date-picker/theme/material/vaadin-date-picker-overlay-content-styles.js
Removed some styles that are leftovers from `vaadin-date-picker` 2.0 version - see [example](https://cdn.vaadin.com/vaadin-date-picker/2.0.6/demo/#date-picker-basic-demos):
Overlay header (uses `padding-bottom: 40px`):
Year toggle button (uses `position: absolute`):
These styles are not used in Lumo and Material and require overrides. So I think we can just remove them.
- Refactor
=> refactor: cleanup overlay content default styles

packages/tooltip/src/vaadin-tooltip.d.ts, packages/tooltip/src/vaadin-tooltip.js
Added missing API documentation for `vaadin-tooltip` web component.
- Docs
=> docs: add tooltip component API docs

packages/component-base/src/tooltip-controller.d.ts, packages/component-base/src/tooltip-controller.js, packages/component-base/test/tooltip-controller.test.js
Moved the `TooltipController` from the original `tooltip` package to `component-base` package.
This is needed to avoid having dependency on `tooltip` in all components that support it.
Note: while controller unit tests use `vaadin-tooltip`, they do not rely on its internal logic.
So IMO it's ok to not import the tooltip in controller tests, to avoid circular dependency.
- Refactor
=> refactor: move TooltipController to component-base

packages/component-base/src/tooltip-controller.d.ts, packages/component-base/src/tooltip-controller.js, packages/component-base/test/tooltip-controller.test.js
In some components we might want to customize the tooltip position to use non-default value.
Example: in `vaadin-details`, it makes sense to use `bottom-start` for better appearance:
- Feature
=> feat: add setPosition API to TooltipController

packages/component-base/src/tooltip-controller.js, packages/component-base/test/tooltip-controller.test.js
Changed the `TooltipController` to support calling methods before the `vaadin-tooltip` element is added.
Previously, only `target` was correctly assigned in `initCustomNode`. Now this covers all properties.
- Refactor
=> refactor: set properties on lazily added tooltip

wtr-utils.js
Update the `web-test-runner` change detection script to use `23.2` as a base branch for Vaadin 23.2
=> chore: update change detection branch to 23.2

packages/tabsheet/src/vaadin-tabsheet.js, packages/tabsheet/test/tabsheet.test.js
Automatically propagate the `theme` of `<vaadin-tabsheet>` to the slotted `<vaadin-tabs>`
- Feature
This PR is targeting the `feat/tabsheet` feature branch, not `master`.
=> feat: propagate tabsheet theme to the slotted tabs

packages/rich-text-editor/package.json, packages/rich-text-editor/src/vaadin-rich-text-editor.js, packages/rich-text-editor/test/a11y.test.js, packages/rich-text-editor/theme/lumo/vaadin-rich-text-editor.js, packages/rich-text-editor/theme/material/vaadin-rich-text-editor.js
Fixes #1759
Replaced usage `title` for toolbar buttons in `vaadin-rich-text-editor` with tooltips using `vaadin-tooltip`.
- Feature
=> feat: replace toolbar buttons title with tooltips

packages/avatar/src/vaadin-avatar.d.ts, packages/avatar/src/vaadin-avatar.js
Added `@attr` annotation needed for VSCode Lit plugin autocomplete to use correct attribute name.
Currently, it suggests `colorIndex`, while correct suggestions are `.colorIndex` and `color-index`.
=> docs: add missing attribute JSDoc annotation

packages/tabs/src/vaadin-tabs.d.ts, packages/tabs/src/vaadin-tabs.js
Changed the description to be aligned with the README and [component documentation](https://vaadin.com/docs/latest/components/tabs).
Removed mention of "switching between views" as we don't recommend `vaadin-tabs` for app navigation.
=> docs: update vaadin-tabs JSDoc description

dev/button.html, integration/tests/button-tooltip.test.js, packages/app-layout/src/vaadin-drawer-toggle.js, packages/button/src/vaadin-button.d.ts, packages/button/src/vaadin-button.js, packages/button/test/dom/__snapshots__/button.test.snap.js, packages/crud/src/vaadin-crud-edit.js, packages/password-field/src/vaadin-password-field-button.js
Added `vaadin-tooltip` support to `vaadin-button` via `tooltip` slot and `TooltipController`.
Note, because of how `SlotController` works, I had to add `tooltip` slot to all components that extend `Button`.
This means that e.g. `vaadin-drawer-toggle` also gets support for the tooltip, which is probably expected.
- Feature
=> feat: add tooltip support to vaadin-button

packages/grid/src/vaadin-grid.js, packages/grid/test/column-auto-width.test.js
When called after toggling visibility, `recalculateColumnWidths` calculates the new widths before the visibility changes are applied and the columns are rendered again. 
In order to make sure that the changes in visibility are applied before the width calculations, `debouncerHiddenChanged` is flushed when `recalculateColumnWidths` is called.
Fixes https://github.com/vaadin/flow-components/issues/2848
=> fix: handle toggling visibility when recalculating column widths

packages/tooltip/src/vaadin-tooltip.d.ts, packages/tooltip/src/vaadin-tooltip.js, packages/tooltip/test/tooltip.test.js, packages/tooltip/test/typings/tooltip.types.ts
Fixes #4473
Added property to control whether to show the tooltip based on the condition.
Note: this will be also added to `TooltipController` in a separate PR.
- Feature
=> feat: add shouldShow to show tooltip conditionally

packages/date-time-picker/src/vaadin-date-time-picker.js, packages/date-time-picker/test/validation.test.js
This PR prevents `date-time-picker` from being validated when focus is moving inside it, for example, between child pickers.  The field should be only validated when focus moves away.
Fixes #4461
=> fix: do not validate when focus is moving inside the field

packages/component-base/src/tooltip-controller.d.ts, packages/component-base/src/tooltip-controller.js, packages/component-base/test/tooltip-controller.test.js
Follow-up to #4476: added `setShouldShow()` method to `TooltipController` for using by component integrations.
- Feature
=> feat: add setShouldShow to TooltipController

packages/time-picker/test/combo-box.test.js, packages/time-picker/test/keyboard-navigation.test.js, packages/time-picker/test/not-animated-styles.js, packages/time-picker/test/time-picker.test.js
Added missing `not-animated-styles.js` import to ensure the time-picker overlay is closed synchronously in tests.
- Tests
=> test: disable animations in time-picker tests

dev/integer-field.html, dev/number-field.html, integration/tests/component-tooltip.test.js, packages/integer-field/test/dom/__snapshots__/integer-field.test.snap.js, packages/number-field/src/vaadin-number-field.js, packages/number-field/test/dom/__snapshots__/number-field.test.snap.js
Added `vaadin-tooltip` support to `vaadin-number-field` and fields that extend it (`vaadin-integer-field`) via `tooltip` slot and `TooltipController`.
- Feature
=> feat: add tooltip support to number-field based fields

packages/time-picker/src/vaadin-time-picker.d.ts, packages/time-picker/src/vaadin-time-picker.js, packages/time-picker/test/combo-box.test.js, packages/time-picker/test/keyboard-navigation.test.js, packages/time-picker/test/time-picker.test.js, packages/time-picker/test/typings/time-picker.types.ts
Fixes #954
Added missing `opened` property, `open()` and `close()` methods and updated tests to use them.
See https://github.com/vaadin/web-components/issues/954#issuecomment-1211854844 for the rationale behind adding these APIs to the component.
One more reason is adding `vaadin-tooltip` to `vaadin-date-time-picker` where we want to only show the tooltip when both date-picker and time-picker elements have `opened` set to `false` without touching their shadow DOM.
- Feature
=> feat: add opened property, open() and close() methods

packages/date-time-picker/src/vaadin-date-time-picker.js, packages/date-time-picker/test/validation.test.js
This PR cherry-picks the following fix to `23.1`:
- https://github.com/vaadin/web-components/pull/4478
Fixes https://github.com/vaadin/web-components/issues/4461
=> fix: do not validate when focus is moving inside the field (#4478) (CP: 23.1)

packages/date-picker/src/vaadin-date-picker-mixin.d.ts, packages/time-picker/src/vaadin-time-picker.d.ts, packages/time-picker/test/typings/time-picker.types.ts
There is no need to re-declare `validate()` and `checkValidity()` methods as they are declared in `ValidateMixin`.
- Refactor
=> refactor: cleanup validation methods typings

packages/custom-field/src/vaadin-custom-field.d.ts
Same as #4488 but for `vaadin-custom-field` which extends `FieldMixin` and `ValidateMixin`.
- Refactor
=> refactor: cleanup checkValidity typings override

packages/tooltip/src/vaadin-tooltip.js, packages/tooltip/test/tooltip.test.js
Relates to https://github.com/vaadin/web-components/pull/4492#pullrequestreview-1096459113
A new `mouseenter` event may occur on an element even if `mouseleave` hasn't taken place since the last `mouseenter`. The component is already tracking the hover state internally. Use it to determine if a `mouseenter` should be ignored.
- Bugfix
=> fix: do not open a closed tooltip on mouse-enter while hovering

dev/messages.html, integration/package.json, integration/tests/component-tooltip.test.js, packages/message-input/src/vaadin-message-input.d.ts, packages/message-input/src/vaadin-message-input.js, packages/message-input/test/dom/__snapshots__/message-input.test.snap.js, packages/message-input/test/typings/message-input.types.ts
Added `vaadin-tooltip` support to `vaadin-message-input` via `tooltip` slot and `TooltipController`.
- Feature
=> feat: add tooltip support to message-input

packages/tabs/src/vaadin-tab.d.ts, packages/tabs/test/typings/tab.types.ts
Add the missing `ControllerMixin` to `<vaadin-tab>` types
=> docs: add ControllerMixin to tab types

packages/message-list/src/vaadin-message.d.ts, packages/message-list/src/vaadin-message.js
Same as #4440 but for `vaadin-message` camel-case properties.
=> docs: add missing attribute JSDoc annotations

packages/avatar/test/visual/lumo/avatar.test.js, packages/avatar/test/visual/material/avatar.test.js, packages/tooltip/test/not-animated-styles.js, packages/tooltip/test/tooltip-timers.test.js, packages/tooltip/test/tooltip.test.js, packages/tooltip/test/visual/lumo/tooltip.test.js, packages/tooltip/test/visual/material/tooltip.test.js
Added missing `not-animated-styles.js` to make tooltip tests more stable.
- Tests
=> test: disable animations in tooltip tests

packages/confirm-dialog/test/not-animated-styles.js, packages/date-picker/test/not-animated-styles.js, packages/dialog/test/not-animated-styles.js, packages/field-highlighter/test/visual/common.js
There is an inconsistency across `not-animated-styles.js` files: some of them use `moduleId` while others do not.
Removed this config option for consistency: it does not bring any value, and the styles work without it.
- Tests
=> test: remove not necessary moduleId definition

dev/text-area.html, integration/package.json, integration/tests/component-tooltip.test.js, packages/text-area/src/vaadin-text-area.js, packages/text-area/test/dom/__snapshots__/text-area.test.snap.js
Added `vaadin-tooltip` support to `vaadin-text-area` via `tooltip` slot and `TooltipController`.
- Feature
=> feat: add tooltip support to vaadin-text-area

dev/custom-field.html, integration/package.json, integration/tests/component-tooltip.test.js, packages/custom-field/src/vaadin-custom-field.js, packages/custom-field/test/dom/__snapshots__/custom-field.test.snap.js
Added `vaadin-tooltip` support to `vaadin-custom-field` via `tooltip` slot and `TooltipController`.
- Feature
=> feat: add tooltip support to vaadin-custom-field

dev/checkbox-group.html, integration/tests/component-tooltip.test.js, packages/checkbox-group/src/vaadin-checkbox-group.js, packages/checkbox-group/test/dom/__snapshots__/checkbox-group.test.snap.js
Added `vaadin-tooltip` support to `vaadin-checkbox-group` via `tooltip` slot and `TooltipController`.
- Feature
=> feat: add tooltip support to vaadin-checkbox-group

packages/date-picker/src/vaadin-date-picker-mixin.d.ts, packages/date-picker/test/common.js
The usage of `i18n.clear` has been removed in #2532 which is included to Vaadin 22. 
But we forgot to remove corresponding property from the `DatePickerI18n` type.
This change is so small that we can hopefully ship it within a minor version (23.3).
=> fix!: remove unsupported i18n.clear property

packages/time-picker/src/vaadin-time-picker.d.ts
The usage of `i18n.clear` and `i18n.selector` has been removed in #2541 which is included to Vaadin 22. 
But we forgot to remove corresponding properties from the `TimePickerI18n` type.
This change is so small that we can hopefully ship it within a minor version (23.3).
=> fix!: remove no longer supported i18n properties

packages/custom-field/src/vaadin-custom-field.d.ts, packages/custom-field/src/vaadin-custom-field.js
Current API documentation is confusing as it makes an impression that the component supports `disabled` property.
This has been changed by mistake in #2795 when updating `vaadin-custom-field` to use new mixins.
Updated JSDoc to be more aligned with the [original docs](https://github.com/vaadin/vaadin-custom-field/blob/3676aef30dc1ac4843c692e1c6450ddb20619631/src/vaadin-custom-field.html#L78-L79) added in https://github.com/vaadin/vaadin-custom-field/pull/68
=> docs: fix custom-field state attributes API docs

dev/icon.html, integration/package.json, integration/tests/component-tooltip.test.js, packages/icon/src/vaadin-icon.d.ts, packages/icon/src/vaadin-icon.js, packages/icon/test/typings/icon.types.ts
Added `vaadin-tooltip` support to `vaadin-icon` via `tooltip` slot and `TooltipController`.
- Feature
=> feat: add tooltip support to icon

integration/tests/grid-tooltip.test.js, packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js
Fixes https://github.com/vaadin/web-components/issues/4523
=> fix: only show tooltip on keyboard focus if the grid cell is focused

dev/menu-bar.html, integration/package.json, integration/tests/menu-bar-tooltip.test.js, packages/menu-bar/src/vaadin-menu-bar-interactions-mixin.d.ts, packages/menu-bar/src/vaadin-menu-bar-interactions-mixin.js, packages/menu-bar/src/vaadin-menu-bar.d.ts, packages/menu-bar/src/vaadin-menu-bar.js, packages/menu-bar/test/typings/menu-bar.types.ts
Added `vaadin-tooltip` support to `vaadin-menu-bar` via `tooltip` slot and `TooltipController`.
- Feature
=> feat: add tooltip support to menu-bar

packages/tooltip/src/vaadin-tooltip.js, packages/tooltip/test/tooltip.test.js
Fixes #4524
There are actually two fixes in this PR but these are related:
1. Changed to not close tooltip on `focusout` within a field (e.g. `vaadin-password-field` or `vaadin-list-box`),
2. Changed to not re-open tooltip on `focusin` within a field after pressing <kbd>Escape</kbd> to dismiss it.
- Bugfix
=> fix: do not reopen overlay when moving focus within target

packages/tooltip/src/vaadin-tooltip.js, packages/tooltip/test/helpers.js, packages/tooltip/test/tooltip.test.js
Fixes #4502
Based on the implementation from #3590. Here is an example of the new behavior:
https://user-images.githubusercontent.com/10589913/188890662-60a6a030-6668-4b02-858e-be064239c050.mp4
Can be tested using the following HTML:
```html
<div style="width: 300px; height: 300px; overflow: scroll; border: 1px solid black;">
<div style="margin: 600px 0; height: 50px; border: solid 1px red;" tabindex="0" id="test"></div>
</div>
<vaadin-tooltip text="Click to save changes" for="test"></vaadin-tooltip>
```
- Bugfix
=> fix: only show tooltip when target is fully visible

packages/menu-bar/src/vaadin-menu-bar-interactions-mixin.js
Updated `vaadin-menu-bar` to use `once: true` for `vaadin-overlay-open` event listener.
- Refactor
=> refactor: use once for overlay open event listener

packages/accordion/src/vaadin-accordion.d.ts, packages/accordion/src/vaadin-accordion.js
Changed `vaadin-accordion` to use `KeyboardMixin` instead of adding a `keydown` event listener.
This is a preparation step for integration `KeyboardDirectionMixin` that will be added later.
- Refactor
=> refactor: use KeyboardMixin in vaadin-accordion

packages/grid/test/scrolling-mode.test.js
Ignore a flaky test case on Firefox. The test passes fine on Chrome but it randomly keeps failing builds on Firefox for unrelated pull requests. The test is [already ignored on Safari](https://github.com/vaadin/web-components/commit/778e66249c0a1cb9299ad07821aab8aea4c72f9c) for the same reason.
=> test: ignore a flaky test on Firefox

scripts/prepareDocs.js
(cherry picked from commit faa710942d0806e44ad33e9cddda1111625e148c)
=> fix: add missing event declarations to JS API docs (#4537) (CP: 22)

scripts/prepareDocs.js
(cherry picked from commit faa710942d0806e44ad33e9cddda1111625e148c)
=> fix: add missing event declarations to JS API docs (#4537) (CP: 23.1)

packages/combo-box/src/vaadin-combo-box-scroller.js
This PR removes unnecessary checks for the virtualizer's presence from `vaadin-combo-box-scroller` because neither `requestContentUpdate()` nor `scrollIntoView()` can be invoked before a virtualizer instance is created in `ready()`.
=> refactor: remove unnecessary checks for virtualizer's presence

packages/combo-box/src/vaadin-combo-box-scroller.js
There is no sense in returning `index` from `__requestItemByIndex` given that `index` is passed in arguments which means the caller has a reference to it.
=> refactor: do not return index from __requestItemByIndex

packages/menu-bar/src/vaadin-menu-bar-interactions-mixin.d.ts, packages/menu-bar/src/vaadin-menu-bar-interactions-mixin.js
Changed `vaadin-menu-bar` to use `KeyboardMixin` instead of adding a `keydown` event listener.
This is a preparation step for integrating `KeyboardDirectionMixin` that will be added later.
- Refactor
=> refactor: use KeyboardMixin in vaadin-menu-bar

packages/context-menu/src/vaadin-contextmenu-items-mixin.js, packages/crud/src/vaadin-crud.js, packages/field-highlighter/src/fields/vaadin-checkbox-group-observer.js, packages/field-highlighter/src/fields/vaadin-list-box-observer.js, packages/field-highlighter/src/fields/vaadin-radio-group-observer.js, packages/field-highlighter/src/vaadin-user-tags.js, packages/grid-pro/src/vaadin-grid-pro-inline-editing-mixin.js, packages/grid/src/vaadin-grid-column-resizing-mixin.js, packages/grid/src/vaadin-grid-drag-and-drop-mixin.js, packages/grid/src/vaadin-grid-event-context-mixin.js, packages/grid/src/vaadin-grid.js, packages/grid/test/drag-and-drop.test.js, packages/grid/test/scroll-to-index.test.js, packages/menu-bar/src/vaadin-menu-bar-interactions-mixin.js, packages/vaadin-list-mixin/test/list-mixin.test.js, packages/vaadin-overlay/src/vaadin-overlay.js, packages/vaadin-overlay/test/legacy.test.js
Since we no longer support IE11, we can replace `array.filter(...)[0]` pattern with `.find()` (and `.some()`) which is more performant and easier to read.
=> refactor: replace `.filter()` usage with `.find()` and `.some()`

packages/message-list/src/vaadin-message-list.js
Added missing `@private` annotations to `vaadin-message-list` internal methods.
=> chore: add missing JSDoc annotations to methods

packages/component-base/src/keyboard-direction-mixin.d.ts, packages/component-base/src/keyboard-direction-mixin.js, packages/component-base/test/keyboard-direction-mixin.test.js
Added `KeyboardDirectionMixin` that provides some common logic to be used by components:
- `vaadin-list-box` and `vaadin-tabs` (via `ListMixin`)
- `vaadin-accordion`
- `vaadin-menu-bar`
- `vaadin-message-list`
=> feat: add KeyboardDirectionMixin to navigate items

packages/accordion/src/vaadin-accordion.d.ts, packages/accordion/src/vaadin-accordion.js
Updated `vaadin-accordion` to use the newly added `KeyboardDirectionMixin` instead of the custom logic.
- Refactor
=> refactor: use KeyboardDirectionMixin in accordion

packages/message-list/src/vaadin-message-list.d.ts, packages/message-list/src/vaadin-message-list.js, packages/message-list/test/message-list.test.js
Updated `vaadin-message-list` to use the newly added `KeyboardDirectionMixin` instead of the custom logic.
- Refactor
=> refactor: use KeyboardDirectionMixin in message-list

packages/menu-bar/src/vaadin-menu-bar-interactions-mixin.d.ts, packages/menu-bar/src/vaadin-menu-bar-interactions-mixin.js
Updated `vaadin-menu-bar` to use the newly added `KeyboardDirectionMixin` instead of the custom logic.
- Refactor
=> refactor: use KeyboardDirectionMixin in menu-bar

packages/vaadin-list-mixin/test/list-mixin.test.js, packages/vaadin-list-mixin/vaadin-list-mixin.d.ts, packages/vaadin-list-mixin/vaadin-list-mixin.js
Updated `ListMixin` to use the newly added `KeyboardDirectionMixin` instead of the custom logic.
- Refactor
=> refactor: use KeyboardDirectionMixin in list-mixin

packages/grid/src/vaadin-grid.js, packages/grid/test/missing-imports.test.js
Fixes an issue with `grid.requestContentUpdate()` throwing an error if some of the grid's column types have not yet been defined.
- Bugfix
=> fix: do not throw on content update with undefined columns

packages/tooltip/src/vaadin-tooltip-overlay.js, packages/tooltip/src/vaadin-tooltip.d.ts, packages/tooltip/src/vaadin-tooltip.js, packages/tooltip/test/tooltip-offset.test.js, packages/tooltip/test/tooltip.test.js, packages/tooltip/theme/lumo/vaadin-tooltip-styles.js, packages/tooltip/theme/material/vaadin-tooltip-styles.js
Fixes #4530
Added custom CSS properties to control offset for different tooltip positions and updated themes to use them.
This should make it possible for e.g. `vaadin-text-field` with a label to tweak the slotted tooltip offset.
The next step would be to also add corresponding styles, probably to "mixins" folders in Lumo / Material packages.
- Feature
=> feat: add custom CSS properties to define offset

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.d.ts, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/multi-select-combo-box/test/typings/multi-select-combo-box.types.ts
Fixes #4570
Current approach with `::slotted(input:placeholder-shown)` does not work in Safari when using shadow root.
The reason is the fact that the workaround here is always added to the document level:
https://github.com/vaadin/web-components/blob/68d93ffbe63f7d7370123ae23a2febfb175f1de7/packages/input-container/src/vaadin-input-container.js#L126-L128
We should consider using `SlotStylesMixin` instead of keeping that workaround in the `vaadin-input-container.js`.
I will create a separate issue for it because that mixin has to be applied to the actual field components.
This PR is still reasonably small and IMO we can merge it without waiting for the above issue to be fixed.
- Bugfix
=> fix: use correct styles to hide input placeholder

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.d.ts, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/multi-select-combo-box/test/typings/multi-select-combo-box.types.ts
Manual cherry-pick of #4571 to `23.1` branch. 
The merge conflict was caused by `import type` used on master in `.ts` and `.d.ts` files.
- Cherry-pick
=> fix: use correct styles to hide input placeholder (#4571) (CP: 23.1)

packages/tooltip/src/vaadin-tooltip.js, packages/tooltip/test/tooltip-timers.test.js
Extracted from #4567 to make the diff in that PR smaller.
This fixes an issue with the visibility change observer incorrectly calling `_open()` in tests.
Also added some delays to make the tooltip delay and hide delay tests more reliable.
- Bugfix
=> fix: improve target visibility observer logic and tests

packages/tooltip/src/vaadin-tooltip.d.ts, packages/tooltip/src/vaadin-tooltip.js, packages/tooltip/test/tooltip-timers.test.js, packages/tooltip/test/typings/tooltip.types.ts
Fixes #4531
1. Added `focusDelay` property to make it possible to show tooltip on keyboard focus after a delay;
2. Renamed `delay` property  to `hoverDelay`, also renamed `setDefaultDelay` method accordingly;
3. Fixed some edge case with target visibility change observer causing timers tests to randomly fail.
- Feature
=> feat: add focusDelay, change delay to hoverDelay

packages/field-base/src/input-control-mixin.d.ts, packages/field-base/src/input-control-mixin.js, packages/field-base/src/input-field-mixin.d.ts, packages/input-container/src/vaadin-input-container.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/number-field/src/vaadin-number-field.d.ts, packages/number-field/src/vaadin-number-field.js, packages/password-field/src/vaadin-password-field.d.ts, packages/password-field/src/vaadin-password-field.js
Fixes #4572 
Replaced the workaround added in #2710 with `SlotStylesMixin` to inject placeholder styles correctly.
Using `InputControlMixin` for it is the best place as it's used by all the affected field components:
- `vaadin-combo-box`
- `vaadin-date-picker`
- `vaadin-email-field`
- `vaadin-integer-field`
- `vaadin-multi-select-combo-box`
- `vaadin-number-field`
- `vaadin-password-field`
- `vaadin-text-area`
- `vaadin-text-field`
- `vaadin-time-picker`
Also removed extra mixin application from those component where it was already used previously.
- Bugfix
=> fix: inject placeholder styles to correct root node

packages/field-base/src/input-control-mixin.d.ts, packages/field-base/src/input-control-mixin.js, packages/field-base/src/input-field-mixin.d.ts, packages/input-container/src/vaadin-input-container.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/number-field/src/vaadin-number-field.d.ts, packages/number-field/src/vaadin-number-field.js, packages/password-field/src/vaadin-password-field.d.ts, packages/password-field/src/vaadin-password-field.js
Manual cherry-pick of #4577 to `23.1` branch. 
The merge conflict was caused by `import type` used on master in `.d.ts` files.
- Cherry-pick
=> fix: inject placeholder styles to correct root node (#4577) (CP: 23.1)

packages/grid/src/vaadin-grid.js
Fixes #4579
Looks like with `pointerenter` and `pointerdown` events there is no flash, most likely because of different timing:
https://user-images.githubusercontent.com/10589913/189892745-ed959052-b806-4399-8f89-dcad11269f35.mp4
- Refactor
=> refactor: do not show tooltip on iOS and Android

packages/field-base/src/input-control-mixin.d.ts, packages/field-base/src/input-control-mixin.js, packages/field-base/src/input-field-mixin.d.ts, packages/input-container/src/vaadin-input-container.js, packages/number-field/src/vaadin-number-field.d.ts, packages/number-field/src/vaadin-number-field.js, packages/password-field/src/vaadin-password-field.d.ts, packages/password-field/src/vaadin-password-field.js
Manual cherry-pick of #4577 to `22.0` branch with some tweaks (e.g. removed `multi-select-combo-box`).
- Cherry-pick
=> fix: inject placeholder styles to correct root node (#4577) (CP: 22.0)

packages/crud/src/vaadin-crud.js
Updated `vaadin-crud` to use `once: true` for editor `cancel` event listener.
- Refactor
=> refactor: use once for editor cancel event listener

scripts/prepareDocs.js
This PR fixes a minor regression from #4537 which introduced an issue with incorrect events shown in docs:
- Bugfix
=> fix: enforce dash case for event names in docs

packages/tooltip/src/vaadin-tooltip.js, packages/tooltip/test/helpers.js, packages/tooltip/test/tooltip.test.js
This PR addresses the issue discovered in https://github.com/vaadin/web-components/pull/4591#discussion_r970533561.
In some conditions, when overlay is open immediately (zero hover delay), the `mouseenter` event is immediately followed by `mouseleave` event because cursor moves to `vaadin-tooltip-overlay` which causes it to close.
Added logic to prevent `mouseleave` to overlay (and then back to target) from closing the tooltip.
This also allows users to e.g. select the text shown in the tooltip and copy it to clipboard.
Finally, this change makes the tooltip satisfy the [WCAG Criterion 1.14.13](https://www.w3.org/TR/WCAG21/#content-on-hover-or-focus):
> If pointer hover can trigger the additional content, then the pointer can be moved over the additional content without the additional …
=> fix: do not close on mouseleave to tooltip overlay

packages/vaadin-lumo-styles/mixins/required-field.js, packages/vaadin-material-styles/mixins/input-field-shared.js
Added custom offset overrides for field components to compensate `padding-top` set on the host element.
| Before  | After
|-----------------------|-------------------
| ![Screenshot 2022-09-14 at 11 38 08](https://user-images.githubusercontent.com/10589913/190106095-dd077e6e-946a-4723-8c2a-332c58b64944.png) | ![Screenshot 2022-09-14 at 11 37 53](https://user-images.githubusercontent.com/10589913/190106075-a051eab4-cfad-482c-8973-610a97748758.png)
| Before  | After
|-----------------------|-------------------
| ![Screenshot 2022-09-14 at 11 29 15](https://user-images.githubusercontent.com/10589913/190106554-002f4ca1-7f16-4996-87c6-f254f58063f2.png) | ![Screenshot 2022-09-14 at 11 29 01](https://user-images.githubusercontent.com/10589913/190106539-94b251d2-fba0-40d5-8c45-ad1122c2959a.png)
- …
=> fix: customize bottom offset for fields with label

packages/combo-box/src/vaadin-combo-box-scroller.js, packages/combo-box/test/dynamic-size.test.js, packages/combo-box/test/lazy-loading.test.js
This PR makes `combo-box-scroller` request a page asynchronously when it encounters an item placeholder while scrolling. This is needed to prevent an immediate page request and therefore a possible infinite recursion in case the data provider implements page request cancelation logic by invoking data provider page callbacks with an empty array. This is exactly the case for the Flow counterpart that clears page callbacks by [invoking them with an empty array](https://github.com/vaadin/flow-components/blob/e39333b546d606aedc12b8c905fa2a3657cd8d45/vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js#L69-L70) to prevent too many page requests when scrolling fast. Without the current change, the scroller could immediately …
=> fix: request pages asynchronously when scrolling

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/multi-select-combo-box/test/readonly.test.js
The PR disables clearing the data provider cache when `multi-select-combo-box` is read-only. Generally, all the data provider functionality should be disabled while the field is read-only to preserve `filteredItems` as they contain the selected items that are supposed to be shown in the dropdown in that case.
Fixes https://github.com/vaadin/flow-components/issues/3684
=> fix: do not clear data provider cache when readonly

integration/tests/menu-bar-tooltip.test.js, packages/menu-bar/src/vaadin-menu-bar-interactions-mixin.js
Fixes #4599
Added logic to hide tooltip in case when `event.composedPath()` does not contain a menu-bar button.
This can happen especially for `disabled` buttons because they have `pointer-events: none`.
- Bugfix
=> fix: hide tooltip on disabled button mouseover

packages/tooltip/src/vaadin-tooltip-overlay.js, packages/tooltip/src/vaadin-tooltip.js, packages/tooltip/test/tooltip.test.js
Fixes #4609
Added a workaround to ensure `_overlayElement` and `owner` properties on tooltip and overlay are set correctly.
This bug happens because of `ready()` callbacks running in reverse order (child before parent) in Polymer.
- Bugfix
=> fix: do not throw when setting manual and opened

dev/grid.html, dev/menu-bar.html, integration/tests/grid-tooltip.test.js, integration/tests/menu-bar-tooltip.test.js, packages/avatar-group/src/vaadin-avatar-group.js, packages/avatar-group/test/avatar-group.test.js, packages/component-base/src/tooltip-controller.d.ts, packages/component-base/src/tooltip-controller.js, packages/tooltip/src/vaadin-tooltip.d.ts, packages/tooltip/src/vaadin-tooltip.js, packages/tooltip/test/tooltip.test.js, packages/tooltip/test/typings/tooltip.types.ts
Apply the following changes (as agreed in API review):
- Rename `tooltip.textGenerator` to `tooltip.generator`
=> refactor: rename tooltip.textGenerator to generator

dev/menu-bar.html, integration/tests/menu-bar-tooltip.test.js, packages/menu-bar/src/vaadin-menu-bar-interactions-mixin.js, packages/menu-bar/src/vaadin-menu-bar.d.ts, packages/menu-bar/src/vaadin-menu-bar.js, packages/menu-bar/test/typings/menu-bar.types.ts
Apply the following changes (as agreed in the API review):
- add default tooltip generator for menu-bar
- Makes assigning a generator to the `<vaadin-tooltip>` optional
- The default tooltip generator reads the `tooltip` property of a `MenuBarItem`.
- If a custom generator is assigned to the `<vaadin-tooltip>` it will not be overridden by the default generator.
- Feature
=> feat: add default tooltip generator for menu-bar

.github/workflows/coverage.yml, .github/workflows/unit-tests.yml, .github/workflows/verify.yml, .github/workflows/visual-tests.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> chore: add permissions section to GitHub Actions workflows

packages/vaadin-overlay/src/vaadin-overlay-position-mixin.js, packages/vaadin-overlay/test/position-mixin.test.js
Fixes #4604
Added logic to adjust bottom coordinate when it's larger when the viewport. E.g. we have `bottom: 1200px` but after resize, the viweport height is `700px` - in this case we just calculate the diff and update the `bottom` property accordingly.
- Bugfix
Can be tested with the following HTML (use `position="top"` and `margin-top: 200px` for vertical):
```html
<vaadin-button style="margin-left: 200px">
Edit
<vaadin-tooltip slot="tooltip" text="Click to edit" manual position="start"></vaadin-tooltip>
</vaadin-button>
requestAnimationFrame(() => {
document.querySelector('vaadin-tooltip').opened = true;
});
</script>
```
💡 Use "Dock to bottom" / "Dock to right" in DevTools to easily change viewport height / width.
=> fix: reset styles to handle window resize correctly

packages/tooltip/src/vaadin-tooltip.d.ts, packages/tooltip/src/vaadin-tooltip.js, packages/tooltip/test/tooltip.test.js, packages/tooltip/test/typings/tooltip.types.ts
Implemented the [suggestion](https://github.com/orgs/vaadin/discussions/3196#discussioncomment-3687344) about the `shouldShow` function to accept `context` as an optional second argument.
- Feature
=> feat: pass context property value to shouldShow

packages/component-base/src/tooltip-controller.js, packages/component-base/test/tooltip-controller.test.js
As discussed, we would like to set default position for input field components to `top` instead of `bottom`.
However, using `setPosition()` in the `TooltipController` for this would override position set with attribute:
```html
<vaadin-text-field>
<vaadin-tooltip slot="tooltip" text="Other users will see this" position="end"></vaadin-tooltip>
</vaadin-text-field>
```
Changed the `setPosition()` logic to explicitly check for the attribute presence to avoid such cases.
- Bugfix
=> fix: do not override position set with attribute

packages/form-layout/package.json
Added a missing `field-base` dependency to `form-layout`.
https://github.com/vaadin/web-components/blob/2aa5a81aeb07cfbc7f3f2fcc3a8302fc6e398864/packages/form-layout/src/vaadin-form-item.js#L7
=> fix: add missing field-base dependency

packages/component-base/src/dom-utils.d.ts, packages/component-base/src/dom-utils.js, packages/component-base/test/dom-utils.test.js
Added `isEmptyTextNode` helper to check if the node is an empty text (with whitespace `textContent`).
This can be useful for implementing logic such as suggested in https://github.com/vaadin/web-components/pull/4624#discussion_r976103095.
=> feat: add helper function to detect empty text node

packages/app-layout/src/vaadin-drawer-toggle.js, packages/app-layout/test/dom/__snapshots__/drawer-toggle.test.snap.js, packages/app-layout/test/dom/drawer-toggle.test.js, packages/app-layout/test/drawer-toggle.test.js
Fixes #4623
This change is needed to fix the problem that happens when adding slotted content to `vaadin-drawer-toggle`.
This can happen as a side effect of using `slot="tooltip"` adding by https://github.com/vaadin/web-components/pull/4448 (whitespace nodes are added).
- Bugfix
=> fix: add fallback icon to show for slotted whitespace text

packages/grid/src/vaadin-grid-drag-and-drop-mixin.js, packages/grid/test/drag-and-drop.test.js, packages/grid/theme/lumo/vaadin-grid-styles.js, packages/grid/theme/material/vaadin-grid-styles.js
The current vaadin-grid-drag-and-drop-mixin [uses `this._ios`](https://github.com/vaadin/web-components/blob/5ea19bd6d763a3281b8899ae90ec3c80e09fa7b4/packages/grid/src/vaadin-grid-drag-and-drop-mixin.js#L136) to determine whether the [`@vaadin/vaadin-mobile-drag-drop`](https://www.npmjs.com/package/@vaadin/vaadin-mobile-drag-drop) polyfill is in use or not. This effectively means that row drag and drop doesn't currently work (because of [this bug](https://github.com/vaadin/web-components/issues/1603)) with the latest iOS 16 which [supports DnD natively](https://caniuse.com/mdn-html_global_attributes_draggable).
This PR updates the mixin to use feature detection instead
Fixes https://github.com/vaadin/web-components/issues/1603
=> fix: use feature detection for iOS dnd polyfilling

packages/menu-bar/src/vaadin-menu-bar-interactions-mixin.js
Removes obsolete end-aligned / bottom-aligned positioning logic from menu bar. Since the refactoring to use position mixin this method seems unnecessary and actually creates an unintended offset from the position target that is later cleaned up by a delayed repositioning of the position mixin:
https://user-images.githubusercontent.com/357820/192282199-ddaf0765-5705-45d5-b6f3-f26ccad6a286.mov
Similar behavior when using bottom-aligned:
=> refactor: remove obsolete overlay positioning logic from menu bar

packages/checkbox-group/package.json
There is a problem when using `@vaadin/checkbox-group` because of using import from transitive dependency:
```
Error: [vite]: Rollup failed to resolve import "@vaadin/field-base/src/field-mixin.js" from "node_modules/@vaadin/checkbox-group/src/vaadin-checkbox-group.js".
```
The `@vaadin/field-base` is actually installed through `@vaadin/checkbox` but Vite fails to resolve it somehow.
- Bugfix
=> fix: add missing field-base package dependency

packages/checkbox-group/package.json
Same as #4643 but for `23.1` branch.
- Bugfix
=> fix: add missing field-base package dependency (23.1)

packages/checkbox-group/package.json
Same as #4643 but for `23.2` branch.
- Bugfix
=> fix: add missing field-base package dependency (23.2)

packages/upload/src/vaadin-upload.js, packages/upload/test/adding-files.test.js
Fixes the upload accept pattern to escape regex operators that are common in mime types.
Fixes #4372 
- Bugfix
=> fix: escape regex operators in upload accept pattern

packages/date-picker/src/vaadin-month-calendar.js, packages/date-picker/test/basic.test.js, packages/date-picker/test/dom/__snapshots__/month-calendar.test.snap.js, packages/date-picker/test/month-calendar.test.js
This PR adds `aria-hidden` to the cells representing weekdays in order to hide them from assistive technologies as recommended by Tetralogical.
Fixes https://github.com/vaadin/web-components/issues/4313
=> fix: hide weekdays from assistive technologies

packages/tabsheet/README.md
We don't have a dedicated page for `vaadin-tabsheet` component, so I updated the links accordingly.
=> chore: fix docs links in tabsheet README

packages/date-time-picker/src/vaadin-date-time-picker.js
The `date` and `time` parts were removed as part of https://github.com/vaadin/web-components/pull/2782 making  `date-time-picker` use a slotted date-picker and time-picker, but some styles related to those parts have been leftover.
=> refactor: remove unused part styles

packages/tooltip/src/vaadin-tooltip.d.ts, packages/tooltip/src/vaadin-tooltip.js
Updated JSDoc for `focusDelay` property to explicitly mention keyboard focus.
=> docs: clarify opening tooltip on keyboard focus

packages/date-time-picker/src/vaadin-date-time-picker.js
`date-time-picker` sets `pointer-events: all` on its child pickers which results in them reacting to hover when disabled. In the [original PR](https://github.com/vaadin/vaadin-date-time-picker/pull/29), there is not any mention of why `pointer-events` was necessary, nor did I come up with any use case for it, so I believe they can be removed.
Fixes https://github.com/vaadin/web-components/issues/4344
=> fix: do not allow any interaction when disabled

packages/icons/package.json
The PR adds a `assets/**/*` glob to `package.json` to get icon assets published to npm along with other source files.
Fixes #1624
=> feat: publish icon assets to npm

dev/grid.html, integration/tests/grid-tooltip.test.js, packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js, packages/grid/src/vaadin-grid.js
Changed `vaadin-grid` tooltip logic to use the new state controller API added in #4676.
This enables using `focusDelay`, `hoverDelay` and `hideDelay`, as well as global delays.
- Bugfix
=> fix: add support for delay properties to grid tooltip

dev/menu-bar.html, integration/tests/menu-bar-tooltip.test.js, packages/menu-bar/src/vaadin-menu-bar-interactions-mixin.js
Same as #4677 but for `vaadin-menu-bar`.
Changed `vaadin-menu-bar` tooltip logic to use the new state controller API added in #4676.
This enables using `focusDelay`, `hoverDelay` and `hideDelay`, as well as global delays.
- Bugfix
=> fix: add support for delay properties to menu-bar tooltip

packages/vaadin-overlay/src/vaadin-overlay-position-mixin.js, packages/vaadin-overlay/test/position-mixin.test.js
Revert overlay positioning back to https://github.com/vaadin/web-components/pull/4607/commits/e8f5f043c66ff9c228e3d8c3b363d3d773ada1e7
Fixes #4690
=> fix: adjust end property value on viewport resize

packages/component-base/src/virtualizer-iron-list-adapter.js, packages/component-base/test/virtualizer-variable-row-height.test.js
Fixes #4659 
The root problem is somewhere in the iron-list scrolling logic and the problem can be reproduced with `<iron-list>` alone:
https://user-images.githubusercontent.com/1222264/194555782-d0d76e27-6ea9-430b-9b0a-5d03a713b03b.mp4
Since we don't want to modify the iron-list core, it's better to work around the issue in the adapter instead.
=> fix: ensure variable item height virtualizer scrolls to top

packages/app-layout/src/vaadin-app-layout.js, packages/app-layout/test/app-layout.test.js
Adds a resize observer to app layout to recalculate the content offset when the height of the navbar changes.
Fixes https://github.com/vaadin/flow-components/issues/3815
- Bugfix
=> fix: update content offset when navbar height changes

packages/message-input/src/vaadin-message-input.js, packages/message-input/test/message-input.test.js
Added missing styles for `hidden` attribute to `vaadin-message-input`.
- Bugfix
=> fix: add missing hidden styles to message-input

packages/component-base/src/dir-mixin.js, packages/component-base/test/dir-mixin.test.js
When moving an element that extends from `DirMixin` in the DOM, the `DirMixin.disconnectedCallback` can trigger the element's `connectedCallback` before the `disconnectedCallback` has finished (currently reproducable in Chrome, FF). That can cause elements to re-run their initialization logic before their cleanup logic is finished. For example in case of the `AppLayout`, this results in the `connectedCallback` adding several event listeners again, after which the remaining logic in `disconnectedCallback` removes them again, leaving the element in a state where the listeners are not registered. See https://github.com/vaadin/web-components/issues/4682#issuecomment-1273226985.
This change removes the `removeAttribute` call from `DirMixin.disconnectedCallback` that causes the premature …
=> fix: avoid triggering connected callback from disconnected callback

packages/avatar-group/src/vaadin-avatar-group.js, packages/avatar-group/test/avatar-group.test.js, packages/avatar-group/test/visual/lumo/avatar-group.test.js, packages/avatar-group/test/visual/material/avatar-group.test.js
Currently, the `vaadin-avatar-group` does not have a logic to close the overlay on `disconnectedCallback()`.
This causes some problems in tests, like having to call `overlay.close()` manually in `afterEach()`.
Fixed this to align behavior with all the other components that use `vaadin-overlay` extensions internally.
- Bugfix
=> fix: close overflow avatar overlay on detach

packages/avatar-group/src/vaadin-avatar-group.js, packages/avatar-group/test/avatar-group.test.js
Manual cherry-pick of #4724 to `23.1` branch. The conflict was because of lack of the `avatar-size` visual test.
- Cherry-pick
=> fix: close overflow avatar overlay on detach (#4724) (CP: 23.1)

packages/avatar-group/src/vaadin-avatar-group.js, packages/avatar-group/test/avatar-group.test.js
Manual cherry-pick of #4724 to `22.0` branch. The conflict was because of lack of the `avatar-size` visual test.
- Cherry-pick
=> fix: close overflow avatar overlay on detach (#4724) (CP: 22.0)

packages/component-base/src/a11y-announcer.js, packages/component-base/src/active-mixin.js, packages/component-base/test/dir-mixin.test.js
Changed some files in `@vaadin/component-base` package to use relative imports.
- Refactor
This issue was discovered when trying to use `pnpm` instead of `yarn` as it fails to resolve these imports.
=> refactor: use relative imports in component-base

packages/context-menu/package.json, packages/dialog/package.json, packages/multi-select-combo-box/package.json
Added `lit` dev dependency which was missing from some packages that use it for renderer directives tests.
This issue was discovered when trying to use `pnpm` instead of `yarn` as it fails to resolve these imports.
=> chore: add missing Lit dev dependency for tests

packages/password-field/package.json
Currently, `@vaadin/password-field` package imports some transitive dependencies coming from `@vaadin/text-field`.
This PR adds `@vaadin/component-base` and `@vaadin/vaadin-themable-mixin` as direct dependencies.
This issue was discovered when trying to use `pnpm` instead of `yarn` as it fails to resolve these imports.
=> chore: add imported packages to direct dependencies

packages/charts/package.json
Manual cherry-pick of #4728 to `23.1` branch.
- Cherry-pick
=> fix: add missing Lumo and Material dependencies (#4728) (CP: 23.1)

packages/charts/package.json
Manual cherry-pick of #4728 to `23.2` branch.
- Cherry-pick
=> fix: add missing Lumo and Material dependencies (#4728) (CP: 23.2)

packages/vaadin-material-styles/mixins/menu-overlay.js
Changed one file in `@vaadin/vaadin-material-styles` package to use relative import.
- Refactor
This was discovered when trying to use `pnpm` instead of `yarn` as it fails to resolve this import.
=> refactor: use relative import in menu-overlay mixin

packages/button/package.json
Added missing `@vaadin/icon` dev dependency imported in `vaadin-button` visual tests.
This was discovered when trying to use `pnpm` instead of `yarn` as it fails to resolve imports for icon.
=> chore: add missing icon dev dependency used in tests

packages/icon/package.json, packages/input-container/package.json, packages/lit-renderer/package.json
Added missing dev dependencies used in tests, like `@esm-bundle/chai` and `sinon`.
This issue was discovered when trying to use `pnpm` instead of `yarn` as it fails to resolve these imports.
=> chore: add missing dev dependencies used in tests

packages/integer-field/package.json
Added `@vaadin/component-base` dependency to `integer-field` package, as it's used in snapshot tests:
https://github.com/vaadin/web-components/blob/042668ce33a21ebf5cefd3a630b6095ea3a12a66/packages/integer-field/test/dom/integer-field.test.js#L4
This is aligned with `email-field` package that also imports corresponding dependency only in snapshot tests.
This was discovered when trying to use `pnpm` instead of `yarn` as it fails to resolve this dependency.
=> chore: add component-base dependency used in tests

integration/package.json
Added missing `@vaadin/checkbox-group` dependency to `integration-tests` package, as it's used in tooltip tests.
This was discovered when trying to use `pnpm` instead of `yarn` as it fails to resolve this dependency.
=> chore: add missing dependency to integration tests

packages/button/package.json
Missed to update this version while rebasing `24.0` branch. This PR fixes that. 
=> chore: fix dev dependency version after rebasing

packages/date-picker/src/vaadin-date-picker-light.d.ts, packages/date-picker/src/vaadin-date-picker-light.js, packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/src/vaadin-date-picker-overlay.js, packages/date-picker/src/vaadin-date-picker.d.ts, packages/date-picker/src/vaadin-date-picker.js, packages/date-picker/test/common.js, packages/date-picker/test/dom/__snapshots__/date-picker.test.snap.js, packages/date-picker/test/theme-propagation.test.js, packages/date-time-picker/src/vaadin-date-time-picker.js, packages/date-time-picker/test/basic.test.js, packages/date-time-picker/test/validation.test.js
This PR changes the DOM structure of `vaadin-date-picker-overlay`, so it's possibly a breaking change.
The main benefit is being able to style `vaadin-date-picker-overlay-content` using `::part()`.
- Refactor
=> refactor!: move date-picker overlay content to light DOM

packages/menu-bar/src/vaadin-menu-bar-button.js, packages/menu-bar/src/vaadin-menu-bar-buttons-mixin.d.ts, packages/menu-bar/src/vaadin-menu-bar-buttons-mixin.js, packages/menu-bar/src/vaadin-menu-bar-interactions-mixin.js, packages/menu-bar/src/vaadin-menu-bar.d.ts, packages/menu-bar/src/vaadin-menu-bar.js, packages/menu-bar/test/menu-bar.test.js, packages/menu-bar/theme/lumo/vaadin-menu-bar-button-styles.js, packages/menu-bar/theme/lumo/vaadin-menu-bar-styles.js, packages/menu-bar/theme/material/vaadin-menu-bar-button-styles.js, packages/menu-bar/theme/material/vaadin-menu-bar-styles.js
Fixes #4292
Based on the previous prototype: https://github.com/vaadin/web-components/pull/2397/commits/6f44273071412938cad7c713133838ceec2de803
- Breaking change (affects styling)
=> refactor!: move menu-bar buttons to light DOM

packages/grid/src/vaadin-grid-column.js, packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js, packages/grid/src/vaadin-grid-styles.js, packages/grid/src/vaadin-grid.d.ts, packages/grid/src/vaadin-grid.js, packages/grid/test/keyboard-navigation-cell-button.test.js, packages/grid/test/keyboard-navigation.test.js, packages/grid/theme/lumo/vaadin-grid-styles.js, packages/grid/theme/material/vaadin-grid-styles.js
Pre-requisite for #3820
This PR adds a new internal API for `vaadin-grid-column` element to change how its body cells are rendered.
The idea behind the DOM structure is to align with [ARIA example](https://www.w3.org/WAI/ARIA/apg/example-index/grid/dataGrids.html#htmlsourcecode) for data grid with editable cells.
As discovered in #4114, VoiceOver on MacOS does not trigger `focus` events when navigating between `<td>` elements that have `tabindex` attribute. However, in case if an element inside `<td>` has `tabindex`, it gets focused.
So the outcome of this change is being able to keep keyboard focus in sync with VoiceOver cursor, so that pressing <kbd>Enter</kbd> on the editable cell in `vaadin-grid-pro` would start editing for the correct cell.
```html
<td role="gridcell">
<slot …
```
=> feat: add column API to render buttons in cells

packages/date-picker/src/vaadin-infinite-scroller.js, packages/date-picker/test/basic.test.js, packages/date-picker/test/common.js, packages/date-picker/test/overlay.test.js, packages/date-picker/test/scroller.test.js, packages/date-picker/theme/lumo/vaadin-date-picker-overlay-content-styles.js
Some small updates to date-picker and infinite-scroller extracted from #4770:
1. Replaced ES5 leftovers `[].forEach.call` and `Array.prototype.slice.call` with array spread,
2. Replaced legacy Polymer-specific `root` property coming from [Polymer 1](https://polymer-library.polymer-project.org/1.0/docs/devguide/local-dom#dom-api) era with `shadowRoot`,
3. Changed wording to use `slot` instead of `insertionPoint` (which was a [Polymer 1](https://polymer-library.polymer-project.org/1.0/docs/devguide/local-dom#dom-distribution) equivalent),
4. Removed mention of `iron-media-query` from CSS comment (we now use a [different approach](https://github.com/vaadin/web-components/pull/3434)),
5. Added missing JSDoc annotations to all `vaadin-infinite-scroller` properties and methods.
- Refactor
=> refactor: small code style tweaks, add missing JSDoc

packages/avatar/src/vaadin-avatar.js, packages/avatar/test/avatar.test.js
Fixes #4782
Updated `vaadin-avatar` to use the same logic for `role` attribute as in `vaadin-button`.
- Bugfix
=> fix: add support for setting custom role attribute

packages/date-picker/test/basic.test.js, packages/date-picker/test/common.js, packages/date-picker/test/dropdown.test.js, packages/date-picker/test/fullscreen.test.js, packages/date-picker/test/overlay.test.js
Reorganized `vaadin-date-picker` unit tests for better readability:
1. Moved `fullscreen` tests to separate suite and changed to use `setViewport` command,
2. Updated tests for ignoring overlay taps to use fake timers instead of long `setTimeout`,
3. Removed no longer needed `setCancelSyntheticClickEvents(false)` from one test suite,
4. Simplified focus tests to use `document.activeElement` instead of `isFocused` helper,
4. Removed a duplicate toggle button test from the "auto open disabled" test suite.
- Tests
=> test: reorganize and cleanup date-picker tests

packages/component-base/src/virtualizer-iron-list-adapter.js, packages/component-base/test/virtualizer-item-height.test.js
Fixes https://github.com/vaadin/flow-components/issues/3900
The issue was caused by the following sequence:
1. The first time the list renders, everything looks good
2. When the items get refreshed, [virtual-list requests an update from virtualizer
](https://github.com/vaadin/web-components/blob/3d4723a4d2d1f9094fdedcdcd789b9479d8fd5fd/packages/virtual-list/src/vaadin-virtual-list.js#L169)
3. Virtualizer [runs](https://github.com/vaadin/web-components/blob/3d4723a4d2d1f9094fdedcdcd789b9479d8fd5fd/packages/component-base/src/virtualizer-iron-list-adapter.js#L147) the given `updateElement` callback function
4. This causes the `<flow-component-renderer>` to replace its content and the item becomes temporarily empty / to have zero height
5. The `__updateElement` function notices the item …
=> fix: make sure virtualizer clears item placeholder height

packages/date-picker/src/vaadin-date-picker-styles.js, packages/date-picker/src/vaadin-month-calendar.js
Removed some no longer used code from the date-picker.
- Refactor
=> refactor: remove unused code from date-picker

.github/workflows/visual-tests.yml
Updated GitHub action used to upload failed visual test screenshots to the latest version, to get rid of the warning:
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/upload-artifact
=> chore: update actions/upload-artifact to v3

packages/date-picker/src/vaadin-date-picker-mixin.d.ts, packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/test/common.js, packages/date-picker/test/month-calendar.test.js
Follow-up to #4772
Removed `i18n.week` which is no longer used since #3355 where we changed week numbers to be hidden from screen readers, in order to not confuse the user when navigating through the table using the cursor mode.
=> refactor!: remove no longer used i18n.week string

integration/package.json, integration/tests/context-menu-template.test.js, packages/context-menu/package.json
Moved the context-menu `<template>` tests to the `integration-tests` package.
- Tests
=> test: move context-menu template tests to ITs

integration/tests/dialog-date-picker.test.js, packages/date-picker/test/basic.test.js, packages/date-picker/test/common.js, packages/date-picker/test/custom-input.test.js, packages/date-picker/test/dropdown.test.js, packages/date-picker/test/fullscreen.test.js, packages/date-picker/test/keyboard-input.test.js, packages/date-picker/test/keyboard-navigation.test.js, packages/date-picker/test/month-calendar.test.js, packages/date-picker/test/theme-propagation.test.js, packages/date-picker/test/validation.test.js
- Updated date-picker tests to use helpers for better readability.
- Fixed usage of Polymer specific `this.set()` API in `i18n` tests.
- Tests
=> test: update date-picker unit tests to use helpers

integration/tests/grid-tooltip.test.js, packages/grid/src/vaadin-grid-scroll-mixin.js, packages/grid/src/vaadin-grid.js, packages/grid/test/helpers.js
Closes the grid's tooltip when the user starts scrolling to prevent the tooltip overlay from blocking scroll events on the grid. When using keyboard navigation the tooltip is not closed. While scrolling, the tooltip is not opened again on `mouseenter` to avoid the tooltip rapidly opening and closing.
Fixes #4766 
- Bugfix
=> fix: hide tooltip while scrolling

packages/field-base/src/helper-controller.js, packages/field-base/test/field-mixin.test.js
Fixes #4757
Updated `HelperController` to check if a helper node is a valid custom element and if so, consider it a non-empty.
This is a better option than checking for a shadow root presence, because it might not be attached at this point.
- Bugfix
=> fix: consider any custom element a non-empty helper

packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/test/keyboard-input.test.js
Update `_focusedDate` property on date picker also when the overlay is not opened, so that the entered date can be focused when opening the overlay.
Fixes https://github.com/vaadin/flow-components/issues/3826
- Bugfix
=> fix: focus entered date on open with auto-open disabled

packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/test/keyboard-input.test.js
Cherry-pick of #4828  
(cherry picked from commit 6e04c8dbfdaf839275441cd6374b399aa0dcf5b9)
=> fix: focus entered date on open with auto-open disabled (#4828) (CP: 22)

packages/field-highlighter/src/fields/vaadin-date-picker-observer.js, packages/field-highlighter/test/field-components.test.js
Updated logic in the `field-highlighter` to adapt to moving focus to the date-picker overlay content.
This is similar to what has been previously done for `vaadin-date-time-picker` - see this code:
https://github.com/vaadin/web-components/blob/427527c27c4b27822d61fd41d38d7b170134770b/packages/date-time-picker/src/vaadin-date-time-picker.js#L462-L469
Also updated tests to use `async` / `await` and wait for overlay rendering to avoid this error:
```
packages/field-highlighter/test/field-components.test.js:
An error was thrown in a Promise outside a test. Did you forget to await a function or assertion?
TypeError: null is not an object (evaluating 'this.shadowRoot.querySelectorAll')
at focusableDateElement (packages/date-picker/src/vaadin-month-calendar.js:214:31)
at …
```
=> fix: adapt field highlighter to date-picker change

integration/tests/component-tooltip.test.js, packages/tooltip/src/vaadin-tooltip.js, packages/tooltip/test/tooltip.test.js
Ensures that an auto-opened, slotted tooltip closes when another overlay is opened. The tooltip now listens for overlay open events, and closes itself if it is not the last overlay anymore.
Fixes #4737 
Closes #4566
- Bugfix
=> fix: close tooltip when opening another overlay

packages/date-picker/src/vaadin-date-picker.d.ts, packages/date-picker/src/vaadin-date-picker.js, packages/date-picker/src/vaadin-month-calendar.js, packages/date-picker/test/common.js, packages/date-picker/test/dom/__snapshots__/month-calendar.test.snap.js, packages/date-picker/test/fullscreen.test.js, packages/date-picker/test/keyboard-input.test.js, packages/date-picker/test/month-calendar.test.js, packages/date-picker/test/visual/common.js, packages/date-picker/test/wai-aria.test.js, packages/date-picker/theme/lumo/vaadin-month-calendar-styles.js, packages/date-picker/theme/material/vaadin-month-calendar-styles.js
Fixes #4836
Changed state attributes used on the date elements in `vaadin-month-calendar` to use `part` names.
The `disabled` attribute is not removed:  we have tests for disabled date tap that fail without it.
https://github.com/vaadin/web-components/blob/61a03c90b7b60b7dd7cb3042cca4735a2a363932/packages/date-picker/test/month-calendar.test.js#L137
We could probably reduce some selectors complexity by changing it like this:
```diff
-    [part='date'][selected] {
+    [part~='selected'] {
``` 
But maybe we should avoid that as long as the current CSS order works. @jouni WDYT?
=> refactor!: expose date element states as parts names

packages/upload/src/vaadin-upload-icon.js, packages/upload/src/vaadin-upload.d.ts, packages/upload/src/vaadin-upload.js, packages/upload/test/adding-files.test.js, packages/upload/test/dom/__snapshots__/vaadin-upload.test.snap.js, packages/upload/test/dom/vaadin-upload.test.js, packages/upload/test/upload.test.js, packages/upload/test/visual/lumo/upload.test.js, packages/upload/test/visual/material/upload.test.js, packages/upload/theme/lumo/vaadin-upload-styles.js, packages/upload/theme/material/vaadin-upload-styles.js
Fixes #4281
1. Moved `add-button`, `drop-label` and `drop-label-icon` elements to slots using `SlotController`,
2. Created `vaadin-upload-icon` element for default upload icon (so that we can apply styles to it),
3. Removed an extra `<div id="addFiles">` wrapping the button, as it doesn't seem to be needed.
=> refactor!: move button and drop label to light DOM

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/multi-select-combo-box/test/basic.test.js
Make backspace, arrowLeft and arrowRight keys work when overlay is opened or input value is not empty.
Caret anywhere except the start of the text input: 
- backspace removes preceding character
- arrowLeft moves caret to the left
- arrowRight moves caret to the right if there is text
Caret at start text input (whether empty or not):
- backspace focuses last chip
- arrowLeft focuses last chip
- arrowRight moves caret to the right if there is text
Last chip focused:
- backspace removes that item
- arrowLeft focuses preceding chip
- arrowRight  focuses following chip (if last chip: moves caret to the right if there is text, else removes focus from the last chip)
Fixes #4820
=> fix: allow navigating and removing chips while opened

integration/tests/grid-tooltip.test.js, integration/tests/menu-bar-tooltip.test.js
Fixes #4739
There was a problem with some tooltip ITs, especially for grid, because of not waiting for cooldown timers:
```
integration/tests/grid-tooltip.test.js:
❌ tooltip > should use hover delay on cell mouseenter
AssertionError: expected true to be false
-true
+false
at o.<anonymous> (integration/tests/grid-tooltip.test.js:65:33)
❌ tooltip > should use focus delay on cell keyboard focus
AssertionError: expected true to be false
-true
+false
at o.<anonymous> (integration/tests/grid-tooltip.test.js:138:[33](https://github.com/vaadin/web-components/actions/runs/3367852744/jobs/5585856655#step:5:34))
integration/tests/menu-bar-tooltip.test.js:
❌ menu-bar with tooltip > should use hover delay on menu button mouseover
AssertionError: expected true to …
```
=> test: fix tooltip ITs to get rid of delay flakiness

packages/grid/all-imports.d.ts, packages/grid/package.json, packages/grid/test/typings/grid.types.ts
Fixes #4874
Added missing `all-imports.d.ts` file to enable importing  `all-imports.js` in TS without errors.
Also, updated corresponding `all-imports.js` to re-export from root entrypoints.
- Bugfix
=> fix: add missing type definitions for all-imports.js

packages/upload/src/vaadin-upload-file.js, packages/upload/theme/lumo/vaadin-upload-styles.js, packages/upload/theme/material/vaadin-upload-styles.js
Extracted from #4870 so that this change could be separately mentioned in the release notes.
Removed attributes from `vaadin-progress-bar` as they are duplicates of host attributes.
Also, moved corresponding CSS from themes to core styles to avoid duplication.
=> refactor!: remove upload file progress bar attributes

packages/field-base/src/input-mixin.js, packages/field-base/test/input-control-mixin.test.js, packages/field-base/test/input-field-mixin.test.js
1. Updated tests for `InputControlMixin` and `InputFieldMixin` to run with Polymer and Lit,
2. Fixed the `clear()` method to immediately clear `<input>` value to avoid Lit update issue.
- Refactor
=> refactor: add Lit support to input field mixins

packages/upload/src/vaadin-upload-file.js, packages/upload/test/dom/__snapshots__/vaadin-upload-file.test.snap.js, packages/upload/test/dom/__snapshots__/vaadin-upload.test.snap.js, packages/upload/theme/lumo/vaadin-upload-styles.js, packages/upload/theme/material/vaadin-upload-styles.js
Extracted from #4870 so that this change could be separately mentioned in the release notes.
Moved the `vaadin-progress-bar` element to light DOM so it can be styled with global CSS.
=> refactor!: move upload file progress bar to light DOM

packages/upload/test/common.js, packages/upload/test/file-list.test.js, packages/upload/test/upload.test.js
Extracted from #4870. 
Added `removeFile` helper and updated tests to use it instead of calling a private method.
- Tests
=> test: update tests for removing files to use helper

packages/upload/test/keyboard-navigation.test.js, packages/upload/test/visual/lumo/upload.test.js, packages/upload/test/visual/material/upload.test.js
Extracted from #4870. 
Changed to set `files` property, as the new logic might not use `notifyPath` internally.
- Tests
=> test: override files array instead of mutating items

packages/grid/all-imports.d.ts, packages/grid/package.json, packages/grid/test/typings/grid.types.ts
Manual cherry-pick of #4875 to `22.0` branch. The merge conflict was caused by `import type` usage on master.
- Cherry-pick
=> fix: add missing type definitions for all-imports.js (#4875) (CP: 22.0)

packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js, packages/grid/src/vaadin-grid-sort-mixin.d.ts, packages/grid/src/vaadin-grid-sort-mixin.js, packages/grid/src/vaadin-grid-sorter.d.ts, packages/grid/src/vaadin-grid-sorter.js, packages/grid/test/helpers.js, packages/grid/test/keyboard-navigation.test.js, packages/grid/test/sorting.test.js, packages/grid/test/typings/grid.types.ts
Adds a multi-sort mode for Grid where multi-sorting is achieved by shift-clicking column sorters.
Related to vaadin/platform#3378
=> feat: add multiSortOnShiftClick property

packages/upload/src/vaadin-upload-file.js, packages/upload/src/vaadin-upload.js
Closes #2313
This PR improves the file removal logic to get rid of two subsequent list updates described in https://github.com/vaadin/web-components/pull/4870#discussion_r1011927794
Note, both `file-abort` and `file-remove` events are preserved and fired on `vaadin-upload-file`.
We could alternatively consider dropping `file-abort` as suggested by https://github.com/vaadin/web-components/issues/2313#issuecomment-895872666
=> refactor!: remove file immediately after upload abort

packages/upload/src/vaadin-upload-file-list.js, packages/upload/src/vaadin-upload-file.js, packages/upload/src/vaadin-upload.d.ts, packages/upload/src/vaadin-upload.js, packages/upload/test/common.js, packages/upload/test/dom/__snapshots__/vaadin-upload.test.snap.js, packages/upload/test/dom/vaadin-upload-file.test.js, packages/upload/test/file-list.test.js, packages/upload/test/file.test.js, packages/upload/test/keyboard-navigation.test.js, packages/upload/theme/lumo/vaadin-upload-styles.js
1. Created `vaadin-upload-file-list` element to render `vaadin-upload-files` with Lit instead of `dom-repeat`,
2. Moved the file list component to light DOM and changed how files are updated to not use Polymer `.set()`,
3. Changed `vaadin-upload-file` elements to set individual properties in addition to `file` object property. This is needed because we no longer use Polymer-specific `notifyPath()` to trigger rendering on sub property mutation.
Fixes #4282
The fact that `<ul>` and `<li>` are now in different shadow scopes doesn't seem to break a11y.
Screen reader announcements when navigating files with <kbd>Tab</kbd> look the same as previously:
=> refactor!: render upload file elements in light DOM

packages/login/src/vaadin-login-form.js, packages/login/test/login-form.test.js, packages/login/test/login-submit.test.js, packages/login/theme/lumo/vaadin-login-form-styles.js, packages/login/theme/material/vaadin-login-form-styles.js
Removed `part` attribute from the components that are in global scope and can't be styled with `::part()`:
- `vaadin-login-native-form-wrapper`
- `vaadin-login-native-form`
- `vaadin-login-submit`
These are not in Shadow DOM because `vaadin-login-form` disables it using the Polymer protected API:
https://github.com/vaadin/web-components/blob/5004363edf7456af0703d3dc1e75593ca4f76b99/packages/login/src/vaadin-login-form.js#L124-L126
This is equivalent to [implementing `createRenderRoot()`](https://lit.dev/docs/components/shadow-dom/#implementing-createrenderroot) when using LitElement.
=> refactor!: remove parts from elements in global scope

packages/login/src/vaadin-login-mixin.js, packages/login/src/vaadin-login-overlay.js
Removed `notify: true` from some properties that are not modified by the component internally:
- `action`
- `noForgotPassword`
- `i18n`
This affects Flow counterpart as we would need to remove [`@Synchronize`](https://github.com/vaadin/flow-components/blob/d0ffddd50f3e8e6ec6e56d82f13423400ee2e203/vaadin-login-flow-parent/vaadin-login-flow/src/main/java/com/vaadin/flow/component/login/AbstractLogin.java#L100) from `getAction()`.
However, the change is so small that we can probably backport it at least to Vaadin 23.3.
=> refactor!: do not notify properties set from outside

packages/crud/test/typings/crud.types.ts, packages/crud/vaadin-crud-edit-column.d.ts, packages/crud/vaadin-crud-edit-column.js, packages/crud/vaadin-crud-edit.d.ts, packages/crud/vaadin-crud-edit.js
Added the root level entrypoint to make it possible importing public components like this:
```ts
import '@vaadin/crud/vaadin-crud-edit.js';
import '@vaadin/crud/vaadin-crud-edit-column.js';
```
This addresses the following finding from React wrappers:
> Several web-types.json files provide information about files that looks like not supposed to be public. Here they are:
> `@vaadin\crud\src\vaadin-crud-edit.js`
> `@vaadin\crud\src\vaadin-crud-edit-column.js`
Also, this would be aligned with e.g. `@vaadin/grid/vaadin-grid-column.js` available as a separate root level entrypoint, even though the `vaadin-grid-column` web component is actually imported by `vaadin-grid` internally.
- Feature
=> feat: add crud-edit and crud-edit-column entrypoints

packages/login/src/vaadin-login-form.d.ts, packages/login/src/vaadin-login-form.js, packages/login/src/vaadin-login-overlay.d.ts, packages/login/src/vaadin-login-overlay.js, packages/login/test/typings/login.types.ts
Added missing type definitions for custom events that are present in API docs:
These properties are modified by the `vaadin-login-form` so it makes sense to document these events:
https://github.com/vaadin/web-components/blob/993e7a9f46aeadc5eee40fb79740499700f23dd6/packages/login/src/vaadin-login-form.js#L130-L132
https://github.com/vaadin/web-components/blob/993e7a9f46aeadc5eee40fb79740499700f23dd6/packages/login/src/vaadin-login-form.js#L143-L144
Note, setting `error` to `true` is only possible from outside, but maybe we can keep the event.
UPD: also added `description-changed` event because this property is calculated based on `i18n`:
https://github.com/vaadin/web-components/blob/db1460e9e71a9512b5d9b330ff15a84799cb1fa8/packages/login/src/vaadin-login-overlay.js#L156 …
=> fix: add missing types for properties notify events

packages/crud/src/vaadin-crud.d.ts, packages/crud/test/typings/crud.types.ts
~~While we have `CrudEditEvent` currently on `vaadin-crud`, in fact it bubbles from the `vaadin-crud-edit` element.~~
The `index` numeric property was missing from the `event.detail` type of `CrudEditEvent`, so I added it there.
- Bugfix
=> fix: add missing index property to CrudEditEvent

packages/charts/test/typings/chart.types.ts, packages/charts/vaadin-chart-series.d.ts, packages/charts/vaadin-chart-series.js
Added the root level entrypoint to make it possible importing like this:
```ts
import type { ChartSeries } from '@vaadin/charts/vaadin-chart-series.js';
```
This addresses the following finding from React wrappers:
> This component uses the library which has an imperative interface to update the series etc. So for make it declarative, there is a ChartSeries component. However, it doesn't have a place in the package's root, so the algorithm ignores it because considers it private. Could we put it to the root to make sure it is public?
- Feature
=> feat: add root entrypoint for vaadin-chart-series

packages/grid/src/vaadin-grid-row-details-mixin.d.ts, packages/grid/test/typings/grid.types.ts
Fixed the `GridRowDetailsRenderer` to apply the same change that we previously made in #2097 for column renderers.
> Again, the nullability for grid and model seem to be a mistake because Lit doesn't consider it.
- Bugfix
=> fix: make row details renderer arguments required

packages/context-menu/src/vaadin-context-menu.d.ts, packages/context-menu/test/typings/context-menu.types.ts
Fixed the `ContextMenuRenderer` to apply the same change that we previously made in #2097 for grid renderers.
> As in @vaadin/grid, it has nullable model and element in renderer.
- Bugfix
=> fix: make context menu renderer arguments required

packages/dialog/src/vaadin-dialog.d.ts, packages/dialog/test/typings/dialog.types.ts
Fixed the `DialogRenderer` to apply the same change that we previously made in #2097 for grid renderers.
> As in @vaadin/grid, it has nullable element in renderer.
- Bugfix
=> fix: make dialog renderer owner argument required

packages/accordion/src/vaadin-accordion-panel.d.ts, packages/accordion/test/typings/accordion.types.ts
Added missing `AccordionPanelEventMap` with custom type for `opened-changed` event.
While this event is inherited from `Details`, the lack of proper type is a bit inconvenient.
This is different from e.g. `vaadin-email-field` that extends `vaadin-text-field` but has own event map:
https://github.com/vaadin/web-components/blob/993e7a9f46aeadc5eee40fb79740499700f23dd6/packages/email-field/src/vaadin-email-field.d.ts#L38
Let's add this event map so that users don't have to import the event type from `@vaadin/details`.
- Bugfix
=> fix: add missing event map to vaadin-accordion-panel

packages/accordion/src/vaadin-accordion-panel.d.ts, packages/accordion/test/typings/accordion.types.ts
Cherry-pick of #4906 to `23.1` branch. The automated cherry-pick failed due to `import type` usage on master.
- Cherry-pick
=> fix: add missing event map to vaadin-accordion-panel (#4906) (CP: 23.1)

packages/dialog/src/vaadin-dialog.d.ts, packages/dialog/test/typings/dialog.types.ts
Cherry-pick of #4919 to `23.1` branch. The automated cherry-pick failed due to `import type` usage on master.
- Cherry-pick
=> fix: make dialog renderer owner argument required (#4919) (CP: 23.1)

packages/context-menu/src/vaadin-context-menu.d.ts, packages/context-menu/test/typings/context-menu.types.ts
Cherry-pick of #4918 to `23.1` branch. The automated cherry-pick failed due to `import type` usage on master.
- Cherry-pick
=> fix: make context menu renderer arguments required (#4918) (CP: 23.1)

packages/login/src/vaadin-login-form.d.ts, packages/login/src/vaadin-login-form.js, packages/login/src/vaadin-login-overlay.d.ts, packages/login/src/vaadin-login-overlay.js, packages/login/test/typings/login.types.ts
Cherry-pick of #4904 to `23.1` branch. The automated cherry-pick failed due to `import type` usage on master.
- Cherry-pick
=> fix: add missing types for properties notify events (#4904) (CP: 23.1)

packages/notification/src/vaadin-notification.d.ts, packages/notification/test/typings/notification.types.ts
Fixed the `NotificationRenderer` to apply the same change that we previously made in #2097 for grid renderers.
> Looks like a bug because Lit implementation doesn't care about nullability of notification
- Bugfix
=> fix: make notification renderer argument required

packages/notification/src/vaadin-notification.d.ts, packages/notification/test/typings/notification.types.ts
Cherry-pick of #4934 to `23.1` branch. The automated cherry-pick failed due to `import type` usage on master.
- Cherry-pick
=> fix: make notification renderer argument required (#4934) (CP: 23.1)

.gitignore, package.json, packages/vaadin-lumo-styles/.gitignore, packages/vaadin-lumo-styles/package.json, scripts/generateLumoAutoCompleteCss.js
Adds auto-complete support for CSS custom properties and utility classes of the Lumo theme for IntelliJ.
The change adds a script for generating an `auto-complete.css` file in the Lumo theme package that contains all necessary declarations. The CSS file is only intended to support auto-complete, and should not be loaded into an actual HTML page, a comment at the top of the file clarifies its purpose. The file will be included into the NPM package and should thus be picked up by IDEs.
I put the script into the root script folder, but we can also consider moving it into the package. I extended the `yarn analyze` command to run the script, which would be the easiest way without adding additional steps to the CI build.
Auto-complete works as expected in IntelliJ, in VS Code I could not get …
=> feat: add IntelliJ auto-complete support for Lumo theme

packages/login/src/vaadin-login-form-wrapper.js, packages/login/src/vaadin-login-form.js, packages/login/test/dom/__snapshots__/login-form.test.snap.js, packages/login/test/dom/__snapshots__/login-overlay.test.snap.js, packages/login/test/dom/login-form.test.js, packages/login/test/login-form.test.js, packages/login/theme/lumo/vaadin-login-form-wrapper-styles.js, packages/login/theme/lumo/vaadin-login-form-wrapper.js, packages/login/theme/lumo/vaadin-login-form.js, packages/login/theme/material/vaadin-login-form-wrapper-styles.js, packages/login/theme/material/vaadin-login-form-wrapper.js, packages/login/theme/material/vaadin-login-form.js
Moved "forgot password" button to `vaadin-login-form` light DOM, so it can be styled using global CSS.
Fixes #4699
=> refactor!: move forgot password button to light DOM

packages/login/src/vaadin-login-form-wrapper.js
The `vaadin-login-form-wrapper` is an internal component not supposed to be used publicly.
Also, most of the properties defined in `LoginMixin` are not used by this component.
Updated to remove `LoginMixin` and only list `error` and `i18n` properties explicitly.
Also removed usage of `ElementMixin` because this component doesn't need it either.
- Refactor
=> refactor: do not use unnecessary mixins in form wrapper

packages/login/src/vaadin-login-overlay-wrapper.js, packages/login/theme/material/vaadin-login-overlay-styles.js
Updated `vaadin-lofin-overlay-wrapper` to remove usage of `dom-module` which isn't needed.
Changed to use `registerStyles` for CSS and the `html` tag for template, as we do e.g. here:
https://github.com/vaadin/web-components/blob/b2a45ddd6a514b4d2723da9319f56eacab801c45/packages/confirm-dialog/src/vaadin-confirm-dialog-overlay.js#L33-L43
https://github.com/vaadin/web-components/blob/b2a45ddd6a514b4d2723da9319f56eacab801c45/packages/crud/src/vaadin-crud-dialog.js#L51-L55
- Refactor
=> refactor: update login overlay to not use dom-module

packages/login/src/vaadin-login-mixin.d.ts, packages/login/src/vaadin-login-mixin.js, packages/login/src/vaadin-login-overlay.js
After moving "forgot password" button to light DOM, this method is only used in `vaadin-login-overlay`.
Moved it from the `LoginMixin` to this component and marked as private so we can change / remove it.
- Refactor
=> refactor: move private mixin method to login overlay

packages/crud/src/vaadin-crud.js, packages/crud/test/dom/__snapshots__/crud.test.snap.js
This is a small fix to align logic for `theme` attribute propagation with other components that use it.
See the snapshot test update where the weird `theme="undefined"` has been removed 😅 
- Bugfix / Refactor
=> fix: do not set form theme attribute to undefined

packages/avatar-group/src/vaadin-avatar-group.js, packages/component-base/src/slot-controller.js, packages/component-base/test/slot-controller.test.js, packages/date-picker/src/vaadin-date-picker-overlay-content.js, packages/field-base/src/error-controller.js, packages/field-base/src/input-controller.js, packages/field-base/src/label-controller.js, packages/field-base/src/text-area-controller.js, packages/menu-bar/src/vaadin-menu-bar-buttons-mixin.js, packages/message-input/src/vaadin-message-input.js, packages/message-list/src/vaadin-message.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/password-field/src/vaadin-password-field.js, packages/select/src/vaadin-select.js, packages/upload/src/vaadin-upload-file.js, packages/upload/src/vaadin-upload.js
This is a minor breaking change intended to make usage of `SlotController` slightly less verbose.
Originally, the `host` parameter was added when creating `InputController` where it's needed.
However, in most of cases we have a reference to `this` that can be used instead.
Changed the order of `host` and `node`, and removed unused parameter where possible.
=> refactor!: swap SlotController initializer parameters

packages/avatar-group/src/vaadin-avatar-group.js, packages/component-base/src/slot-controller.d.ts, packages/component-base/src/slot-controller.js, packages/component-base/test/slot-controller.test.js, packages/date-picker/src/vaadin-date-picker-overlay-content.js, packages/field-base/src/error-controller.js, packages/field-base/src/helper-controller.js, packages/field-base/src/input-controller.js, packages/field-base/src/label-controller.js, packages/field-base/src/text-area-controller.js, packages/menu-bar/src/vaadin-menu-bar-buttons-mixin.js, packages/message-input/src/vaadin-message-input.js, packages/message-list/src/vaadin-message.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/password-field/src/vaadin-password-field.js, packages/select/src/vaadin-select.js, packages/upload/src/vaadin-upload-file.js, packages/upload/src/vaadin-upload.js
This is a yet another breaking change intended to make usage of `SlotController` slightly less verbose.
1. Replaced the `slotFactory` function with `tagName` string to specify which element to create.
2. Moved remaining arguments `slotInitializer` and `useUniqueId` to a single `config` object.
=> refactor!: restructure SlotController constructor arguments

packages/custom-field/src/vaadin-custom-field.d.ts, packages/custom-field/src/vaadin-custom-field.js, packages/custom-field/test/custom-field.test.js
Replaces the `i18n` object of `vaadin-custom-field` with root properties for specifying a custom parser and formatter. Based on the changes from https://github.com/vaadin/web-components/pull/4956.
Closes https://github.com/vaadin/web-components/issues/831
- Refactoring
=> refactor!: replace custom field i18n object with parseValue, formatValue properties

packages/confirm-dialog/src/vaadin-confirm-dialog.d.ts, packages/confirm-dialog/src/vaadin-confirm-dialog.js
Same as #4955 but for `vaadin-confirm-dialog`:
1. Replaced usage of `SlotMixin` with `SlotController`,
2. Removed usage of buttons single property observers,
3. Simplified logic to not use `FlattenedNodesObserver`.
- Refactor
=> refactor: replace SlotMixin with controller in confirm-dialog

packages/crud/src/vaadin-crud.js, packages/crud/test/dom/__snapshots__/crud.test.snap.js
Currently, the `vaadin-crud` sets `id` attribute on the slotted "Save", "Cancel" and "Delete" buttons.
All of these are using very common strings, and there is a risk of conflicts. Let's remove them.
=> refactor!: remove ID attribute from slotted buttons

packages/crud/src/vaadin-crud.d.ts, packages/crud/src/vaadin-crud.js
Extracted from #4959. These buttons were missing from the list of slots, let's add them.
=> docs: add slots for editor buttons to JSDoc

packages/crud/src/vaadin-crud.d.ts, packages/crud/src/vaadin-crud.js, packages/crud/test/crud-buttons.test.js, packages/crud/test/crud-editor.test.js, packages/crud/test/crud.test.js, packages/crud/test/dom/__snapshots__/crud.test.snap.js
Fixes #4940
Updated the "New item" button in `vaadin-crud` to use its own dedicated slot, instead of "toolbar" slot in combination with `new-item` attribute. This would be aligned with other button slots, and should generally make things easier.
Note, the [docs example](https://github.com/vaadin/docs/blob/419e2e36c864991c53753426e2c2914731b9feb0/frontend/demo/component/crud/crud-toolbar.ts#L37-L46) using `vaadin-horizontal-layout` will need to be updated. I don't see a big problem as`toolbar` part is already a flex container, so users could apply `::part()` selector e.g. to set spacing between toolbar items.
Also, we might want to add `setNewButton()` API to Flow component (in addition to existing `setToolbar()` API).
=> refactor!: move vaadin-crud new item button to light DOM

packages/field-base/src/error-controller.js, packages/field-base/src/label-mixin.js
1. Fixed `LabelMixin` to use correct mixin in `@mixes` annotation,
2. Fixed copy-paste leftovers in `ErrorController` comments.
=> docs: fix incorrect mixin and controller JSDoc

packages/component-base/src/slot-controller.d.ts, packages/component-base/src/slot-controller.js, packages/component-base/test/slot-controller.test.js
Updated `SlotController` config, added an option to opt-out from observing slot changes.
This would be useful for components where slotted content is not supposed to change.
For example, `vaadin-date-picker-overlay-content` with its scrollers and buttons.
=> feat: add option to disable observing slot changes

packages/date-time-picker/src/vaadin-date-time-picker.d.ts, packages/date-time-picker/src/vaadin-date-time-picker.js, packages/date-time-picker/test/i18n.test.js, packages/date-time-picker/test/properties.test.js
Updated `vaadin-date-time-picker` to use `SlotController` instead of `SlotMixin`.
This is the last component where the mixin is used, so we will be able to remove it.
- Refactor
=> refactor: use SlotController in date-time-picker

packages/crud/src/vaadin-crud-grid.js, packages/crud/test/dom/__snapshots__/crud.test.snap.js, packages/grid/src/vaadin-grid-filter-column.js, packages/grid/src/vaadin-grid-filter.d.ts, packages/grid/src/vaadin-grid-filter.js, packages/grid/test/filtering.test.js
Fixes #1495
1. Changed `vaadin-grid-filter` to use default slot instead of the named `slot="filter"`,
2. Updated to use `SlotController` to move the default `vaadin-text-field` to light DOM.
Note, the `vaadin-grid-filter-column` already renders the text field in filter light DOM.
So this PR also makes these two components produce consistent DOM structure.
=> refactor!: move grid filter text field to light DOM

packages/select/src/vaadin-select.d.ts, packages/select/test/typings/select.types.ts
Fixed the `DialogRenderer` to apply the same change that we previously made in #2097 for grid renderers.
>As in @vaadin/notification, the renderer definition accepts an undefined original element.
- Bugfix
=> fix: make select renderer owner argument required

packages/date-picker/src/vaadin-date-picker-overlay-content.js
Updated `vaadin-date-picker-overlay-content` slot controllers to not observe slot changes.
The overlay content is only created once and users can't provide custom slotted elements.
- Refactor
=> refactor: do not observe overlay content slot changes

packages/select/src/vaadin-select.d.ts, packages/select/test/typings/select.types.ts
Cherry-pick of #4981 to `23.1` branch. 
The automated cherry-pick failed due to `validated` event types present on master but missing in `23.1`.
- Cherry-pick
=> fix: make select renderer owner argument required (#4981) (CP: 23.1)

packages/date-time-picker/src/vaadin-date-time-picker.js
Setting properties in these observers is no longer needed after #4971 where I updated observers for individual properties (especially `disabled`, `readonly`, `required`, `autoOpenDisabled`) to also run when pickers are changed:
https://github.com/vaadin/web-components/blob/f3d5b8641e85a0a4328afa1f5e1f4e022951a6a3/packages/date-time-picker/src/vaadin-date-time-picker.js#L379-L384
- Refactor
=> refactor: remove logic covered by individual observers

packages/form-layout/src/vaadin-form-layout.d.ts, packages/form-layout/src/vaadin-form-layout.js, packages/form-layout/test/form-layout.test.js
Removed deprecated `updateStyles()` method from `vaadin-form-layout`.
=> refactor!: remove deprecated updateStyles method

packages/crud/src/vaadin-crud.js, packages/crud/test/crud.test.js
This PR fixes a regression from #4948 where the logic was changed, see also https://github.com/vaadin/web-components/pull/4948#discussion_r1017777791
Check out [`customGridDoesNotReactToThemeVariantChanges`](https://github.com/vaadin/flow-components/blob/d0ffddd50f3e8e6ec6e56d82f13423400ee2e203/vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/test/java/com/vaadin/flow/component/crud/tests/CustomGridIT.java#L65) IT that fails with 24.0.0-alpha3.
- Bugfix
=> fix: do not propagate theme attribute to custom grid

packages/checkbox-group/test/validation.test.js
Fixed a finding from #5002 to ensure the checkboxes in the group are rendered correctly.
- Tests
=> test: update validation tests to use correct markup

packages/checkbox/src/vaadin-checkbox.js, packages/checkbox/test/checkbox.test.js, packages/checkbox/test/dom/__snapshots__/checkbox.test.snap.js
Removed default `<slot>` support from `vaadin-checkbox`.
=> refactor!: remove deprecated default slot support (checkbox)

packages/avatar-group/src/vaadin-avatar-group.js, packages/component-base/src/dir-mixin.d.ts, packages/component-base/src/dir-mixin.js, packages/context-menu/src/vaadin-contextmenu-items-mixin.d.ts, packages/context-menu/src/vaadin-contextmenu-items-mixin.js, packages/date-picker/src/vaadin-date-picker-overlay-content.js, packages/grid/src/vaadin-grid-column-resizing-mixin.js, packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js, packages/grid/src/vaadin-grid.js, packages/menu-bar/src/vaadin-menu-bar-buttons-mixin.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/overlay/src/vaadin-overlay-position-mixin.js, packages/radio-group/src/vaadin-radio-group.js, packages/split-layout/src/vaadin-split-layout.js, packages/tabs/src/vaadin-tabs.js
Moved `__isRTL` getter to `DirMixin` to reduce code duplication in components that use this mixin.
Also removed `attributeChangedCallback()` from `vaadin-grid`, it's not needed since #2396.
- Refactor
=> refactor: move private RTL direction getter to DirMixin

packages/combo-box/test/typings/combo-box.types.ts, packages/grid/test/typings/grid.types.ts, packages/multi-select-combo-box/test/typings/multi-select-combo-box.types.ts, packages/vaadin-themable-mixin/test/theme-property-mixin.test.js, packages/vaadin-themable-mixin/vaadin-theme-property-mixin.d.ts, packages/vaadin-themable-mixin/vaadin-theme-property-mixin.js
Removed `theme` property, which was previously deprecated. See #3529 for background.
=> refactor!: remove theme property in favor of attribute

packages/grid/src/vaadin-grid.d.ts, packages/grid/src/vaadin-grid.js
1. Updated the state attributes JSDoc formatting to make it more readable,
2. Added missing `frozen-to-end` and `first-frozen-to-end` attributes.
=> docs: format attributes table, add frozen-to-end

packages/grid/src/vaadin-grid.d.ts, packages/grid/src/vaadin-grid.js
Manual cherry-pick of #5015 to `23.1` branch. 
The conflict was caused by #4117 not cherry-picked to that branch previously.
=> docs: format attributes table, add frozen-to-end (#5015) (CP: 23.1)

packages/button/theme/lumo/vaadin-button-styles.js, packages/button/theme/material/vaadin-button-styles.js, packages/input-container/theme/lumo/vaadin-input-container-styles.js, packages/item/theme/lumo/vaadin-item-styles.js, packages/menu-bar/theme/lumo/vaadin-menu-bar-item-styles.js, packages/menu-bar/theme/material/vaadin-menu-bar-item-styles.js, packages/tabs/theme/lumo/vaadin-tab-styles.js, packages/tabs/theme/material/vaadin-tab-styles.js, packages/text-area/theme/lumo/vaadin-text-area-styles.js, packages/vaadin-lumo-styles/badge.js, packages/vaadin-lumo-styles/mixins/input-field-shared.js
We no longer support `iron-icon`, so let's remove related styles from components. Some of these styles were removed when adding `vaadin-icon` but then we agreed to restore those in #2399. Now it's time to finally drop them.
=> refactor!: remove no longer supported iron-icon styles

packages/grid/src/vaadin-grid-data-provider-mixin.js, packages/grid/src/vaadin-grid-styling-mixin.js, packages/grid/src/vaadin-grid.js
Added `@private` annotation to some methods that were missing it.
=> docs: add missing private JSDoc annotations

packages/button/src/vaadin-button.js, packages/button/test/dom/__snapshots__/button.test.snap.js
Fixes #2924
See https://github.com/vaadin/web-components/issues/2924#issuecomment-1319655434 for a confirmation by @knoobie that this approach works in NVDA.
Given that prefix and suffix are not announced in [field components](https://vaadin.com/docs/latest/components/text-field/#prefix-and-suffix) and are typically used for icons (or supplementary content, e.g. `$` currency sign in case of the money field), let's change `vaadin-button` to work the same way.
- Bugfix
=> fix: set aria-hidden="true" on prefix and suffix

packages/grid/test/accessibility.test.js, packages/grid/test/array-data-provider.test.js, packages/grid/test/basic.test.js, packages/grid/test/column-resizing.test.js, packages/grid/test/data-provider.test.js, packages/grid/test/dynamic-item-size.test.js, packages/grid/test/event-context.test.js, packages/grid/test/filtering.test.js, packages/grid/test/frozen-columns.test.js, packages/grid/test/hidden-grid.test.js, packages/grid/test/physical-count.test.js, packages/grid/test/resizing.test.js, packages/grid/test/row-height.test.js, packages/grid/test/scroll-to-index.test.js, packages/grid/test/scrolling-mode.test.js, packages/grid/test/sorting.test.js, packages/grid/test/tree-toggle.test.js
Updated most of the grid unit tests to replace `<template>` with `path` / `header` or `renderer`.
There are still some test suites that would require more effort, so let's handle them later.
- Tests
=> test: update grid tests to use renderers instead of templates

.github/workflows/coverage.yml, .github/workflows/lint.yml, .github/workflows/smoke.yml, .github/workflows/snapshots.yml, .github/workflows/unit-tests.yml, .github/workflows/visual-tests.yml
Manual cherry-pick of #4693 to `22.0` branch which is still maintained. Needed to avoid warning:
- Cherry-pick
=> chore: update GitHub Actions to latest versions (#4693) (CP: 22.0)

packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js, packages/grid/src/vaadin-grid-styles.js
Fixed a regression from #4969 related to `pointer-events` issues when using `GridContextMenu` in Flow.
Note, this prevents an error from being thrown but doesn't fix the original issue from https://github.com/vaadin/web-components/pull/4969#discussion_r1019992767
UPD: the commit added by Tomi improves the PR so now it should be in good shape.
- Bugfix
=> fix: do not set pointer events on rows and cells

packages/grid/src/vaadin-grid-a11y-mixin.js, packages/grid/src/vaadin-grid-column-reordering-mixin.js, packages/grid/src/vaadin-grid-data-provider-mixin.js, packages/grid/src/vaadin-grid-drag-and-drop-mixin.js, packages/grid/src/vaadin-grid-helpers.js, packages/grid/src/vaadin-grid-row-details-mixin.js, packages/grid/src/vaadin-grid-styling-mixin.js, packages/grid/src/vaadin-grid.js
While working on #5020, I noticed that we use `Array.from(row.children)` and `[...row.children]` in grid quite a lot.
Created a small helper function to make the code a bit cleaner and updated a couple of occurrences to use it.
- Refactor
=> refactor: use helper function to iterate DOM children

.eslintrc.json, package.json, yarn.lock
Sometimes I tend to push commits containing `it.only` debugging leftovers. Added a plugin to catch these.
=> chore: add eslint-plugin-no-only-tests to ESLint config

packages/grid/src/vaadin-grid-data-provider-mixin.js, packages/grid/src/vaadin-grid-drag-and-drop-mixin.js, packages/grid/src/vaadin-grid-helpers.js, packages/grid/src/vaadin-grid.js, packages/grid/test/basic.test.js, packages/grid/test/dom/__snapshots__/grid.test.snap.js, packages/grid/test/dom/grid.test.js
While working on #5067, I found an issue: some cell parts are reset when setting `hidden` on the column element.
In particular, the following part names related to various row states are currently affected by this problem:
- `first-row-cell` 
- `even-row-cell` 
- `last-row-cell` 
- `odd-row-cell`
- `drag-disabled-row-cell`
- `drop-disabled-row-cell`
- `selected-row-cell`
- `expanded-row-cell`
- `details-opened-row-cell`
Previously, this wasn't a problem as `<tr>` element is always there. Now we need to also update `<td>` elements.
- Bugfix
=> fix: update parts when toggling column visibility

packages/component-base/src/slot-controller.js, packages/component-base/test/slot-controller.test.js
Fixed an issue with empty text nodes causing an element to be removed from the default slot.
This is currently the case with `vaadin-grid-filter`, see [internal Slack thread](https://vaadin.slack.com/archives/C3TGRP4HY/p1669190392554569?thread_ts=1669104945.546699&cid=C3TGRP4HY).
- Bugfix
=> fix: ignore empty text nodes passed to default slot

packages/grid/test/filtering.test.js
Based on #5072
Updated tests for `vaadin-grid-filter` to verify the fix for `SlotController` (without the fix, two tests would fail).
Also changed to use fake timers instead of waiting for `_debouncerFilterChanged` or calling `flush()`manually.
- Tests
=> test: update grid filter tests to use LitElement

packages/vaadin-lumo-styles/typography.js
The initial implementation of Lumo was problematic from the start, as we set the font-size of the `html` element and therefore redefined the root em `rem` size.
We should instead target the `body` element, and preserve the `16px` default root em size.
Remove the use of the deprecated `--lumo-font-size` custom property as well.
=> fix!: don't override root em

packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/test/keyboard-input.test.js, packages/date-picker/test/validation.test.js
By default, the date picker clears the value when trying to commit an invalid input. This fix applies the same behavior when using `auto-open-disabled`.
Fixes https://github.com/vaadin/web-components/issues/5066
- Bugfix
=> fix: clear value when committing invalid input

packages/grid/src/vaadin-grid-sorter.js, packages/grid/test/sorting.test.js
Fixes https://github.com/vaadin/flow-components/issues/4170
In the case of clicking a `<vaadin-select>` (wrapped inside a `<vaadin-grid-sorter>`), the native focus is moved right away inside the select overlay
https://user-images.githubusercontent.com/1222264/204773246-fd4c4f6c-5c84-42ea-af1d-734b164ad0da.mp4
...so [the existing check that reacts on internal focusable clicks](https://github.com/vaadin/web-components/blob/c37e4da6a1afa4c78371bba121373f62458e69cf/packages/grid/src/vaadin-grid-sorter.js#L227-L231) didn't stop the event from being consumed by the sorter. 
This PR fixes the issue by adding another check which stops the processing in case something else has already canceled the event.
Bugfix
=> fix: ignore sorter click if event is canceled

packages/crud/src/vaadin-crud.d.ts, packages/crud/src/vaadin-crud.js
Changed `vaadin-crud` basic example to not use Polymer specific syntax (passing array as using a JSON attribute).
=> docs: remove Polymer specific demo from API docs

packages/component-base/src/slot-controller.d.ts, packages/component-base/src/slot-controller.js
Added missing JSDoc comments to some methods in `SlotController` those names are not self-explanatory.
Also fixed a few remaining mentions of the `slot factory` as it has been replaced with tag name for V24.
=> docs: clarify and extend SlotController methods JSDoc

packages/field-base/src/input-mixin.d.ts, packages/field-base/src/input-mixin.js, packages/number-field/src/vaadin-number-field.js, packages/number-field/test/number-field.test.js
Native [type=number] inputs don't update their value when you are entering input that the browser is unable to parse e.g. `--5` which results in `_hasInputValue` not being updated either. To work this out, the PR modifies the computation of `_hasInputValue` for `number-field` so that it would additionally check for bad input based on the native `validity.badInput` property and then update `_hasInputValue` accordingly.
Related to https://github.com/vaadin/flow-components/pull/4272
Part of https://github.com/vaadin/platform/issues/3066.
=> fix: check for bad input when updating _hasInputValue

packages/field-base/src/input-mixin.d.ts, packages/field-base/src/input-mixin.js, packages/number-field/src/vaadin-number-field.js, packages/number-field/test/number-field.test.js
This PR cherry-picks the following fix to the `23.3` branch:
- https://github.com/vaadin/web-components/pull/5092
=> fix: check for bad input when updating _hasInputValue (CP: 23.3) (#5092)

packages/component-base/src/slot-observe-controller.d.ts, packages/component-base/src/slot-observe-controller.js, packages/field-base/src/field-mixin.js, packages/field-base/src/helper-controller.js, packages/field-base/src/label-controller.js, packages/field-base/src/label-mixin.js, packages/field-base/src/labelled-input-controller.js
Extracted some logic from `LabelController` and `HelperController` that is responsible for observing node mutations.
This is a pre-requisite for handling ARIA attributes on the slotted content planned to be done in #5093.
Note: unit tests for the new controller are missing, but we don't have them for `LabelController` and `HelperController` either as those are supposed to be used in combination with respective mixins, and are covered by their tests.
- Refactor
=> refactor: move slotted node observing to separate controller

packages/date-picker/src/vaadin-date-picker-mixin.d.ts
During DX tests for the reference date one tester ended up exploring the TS interface for the date picker I18N object, however as it had no JSDoc it was not clear in which format to configure the date. In order to solve this they would have had to backtrack to the `i18n` property of the date picker and check the docs there.
We thought that it would be useful if the interface itself would be documented as well. The downside here is that for future changes this is an exception to our regular pattern of just copying docs between component JSDoc and TS definitions of the component itself, requiring further changes on a nested type that does not exist in the JS module.
=> docs: add JSDoc to DatePickerI18n interface

README.md
Replace the old admonition with a new nicer looking admonition. GitHub now has nice admonitions for warning and note messages. Here's a preview:
> **Note**
> Body text
> **Warning**
> Body text
Here's the syntax:
```markdown
> **Note**
> Body text
```
I'm not fixing an issue with this PR.
=> chore: use nice note admonition in readme

packages/grid/src/vaadin-grid.js, packages/grid/test/column-auto-width.test.js
When using `auto-size` in combination with column groups the performance of the grid decreases significantly. The reason for that is that `__getDistributedWidth` runs `__getIntrinsicWidth` several times for nested columns when measuring a group:
https://github.com/vaadin/web-components/blob/542c8e1991444e0ca97be8a54bff0fe2785698fc/packages/grid/src/vaadin-grid.js#L627-L629
https://github.com/vaadin/web-components/blob/542c8e1991444e0ca97be8a54bff0fe2785698fc/packages/grid/src/vaadin-grid.js#L638-L641
This change adds a cache that gets populated with the intrinsic width of columns after they have been measured, so that they don't need to be measured again. The cache is reset when `recalculateColumnWidths` is called again.
Testing this with the grid benchmark tests in `flow-components`, …
=> perf: improve grid column group auto-width performance

packages/grid/src/vaadin-grid-column.js, packages/grid/src/vaadin-grid.js, packages/grid/test/column-groups.test.js, packages/grid/test/dom/__snapshots__/grid.test.snap.js
Reduces the number of calls to the `grid.__updateHeaderFooterRowVisibility` function on init by utilizing a debouncer.
On the `grid-performance.html` dev page, with a 200-column grid
- the number of calls to the function dropped from 800 to 2
- the initial render time dropped by roughly 10% (with a single body row).
The performance improvement isn't as dramatic for grids that have fewer columns.
=> perf: reduce grid updateHeaderFooterRowVisibility call count

packages/grid/src/vaadin-grid-column-reordering-mixin.js, packages/grid/src/vaadin-grid-column.js, packages/grid/src/vaadin-grid-scroll-mixin.js, packages/grid/src/vaadin-grid.js, packages/grid/test/column-reordering.test.js, packages/grid/test/column-resizing.test.js, packages/grid/test/frozen-columns.test.js, packages/grid/test/helpers.js
Reduces the number of calls to the `grid._updateFrozenColumn` function on init by utilizing a debouncer.
On the `grid-performance.html` dev page, with a 200-column grid
- the number of calls to the function dropped from 4420 to 1
- the initial render time dropped by roughly 10% (with a single body row).
The performance improvement isn't as dramatic for grids that have fewer columns.
The PR also includes cleanup for the [previous related PR](https://github.com/vaadin/web-components/pull/5128)
=> refactor: reduce grid updateFrozenColumn call count

dev/confirm-dialog.html, packages/confirm-dialog/src/vaadin-confirm-dialog.d.ts, packages/confirm-dialog/src/vaadin-confirm-dialog.js, packages/confirm-dialog/test/confirm-dialog.test.js, packages/confirm-dialog/test/visual/lumo/confirm-dialog.test.js, packages/confirm-dialog/test/visual/material/confirm-dialog.test.js, packages/crud/src/vaadin-crud.js, packages/crud/test/dom/__snapshots__/crud.test.snap.js
The following properties for confirm dialog were renamed:
- `reject` -> `rejectButtonVisible`
- `cancel` -> `cancelButtonVisible`
This is a breaking change.
Fixes #597
=> refactor!: rename cancel and reject properties of confirm dialog

README.md
I believe these commands don't work anymore, as the old packages have been removed.
=> fix: readme test commands

packages/upload/src/vaadin-upload.js, packages/upload/test/adding-files.test.js, packages/upload/test/slots.test.js
Fixes #5137
1. Added logic and tests to ensure custom "Add" button and drop label text is not modified by the upload,
2. Refactored corresponding slot controllers: added an option to mark node as default using `_isDefault`.
- Bugfix
=> fix: only modify text for default slotted elements

packages/vaadin-lumo-styles/color.d.ts, packages/vaadin-lumo-styles/color.js
I assume this legacy style sheet is no longer needed, and has been deprecated for a while now. I don't know if the deprecation has been communicated in any way to users, so I’m not entirely sure we can remove it in v24.
=> refactor!: remove `colorLegacy` module from Lumo

integration/tests/component-tooltip.test.js, integration/tests/grid-tooltip.test.js, integration/tests/menu-bar-tooltip.test.js, packages/tooltip/src/vaadin-tooltip.js, packages/tooltip/test/tooltip-offset.test.js, packages/tooltip/test/tooltip-position.test.js, packages/tooltip/test/tooltip-timers.test.js, packages/tooltip/test/tooltip.test.js, packages/tooltip/test/visual/lumo/tooltip.test.js, packages/tooltip/test/visual/material/tooltip.test.js
1. Changed default delay from `0` that was in the original implementation to `500` as [discussed](https://github.com/orgs/vaadin/discussions/3196#discussioncomment-3422422),
2. Updated tests for `vaadin-tooltip` and integration tests for the components supporting it.
See also internal [Slack discussion](https://vaadin.slack.com/archives/C3TGRP4HY/p1671700930626079?thread_ts=1671694071.536389&cid=C3TGRP4HY) where this was raised.
=> fix!: change default tooltip delay from 0 to 500ms

packages/avatar/test/visual/lumo/avatar.test.js, packages/avatar/test/visual/material/avatar.test.js
Follow-up for https://github.com/vaadin/web-components/pull/5156
There seems to be a failing test case in avatar currently
=> test: update avatar visual tests tooltip delay

packages/number-field/src/vaadin-number-field.js
Follow-up from #5440 - fixed a typo in the `[step-buttons-visible]` CSS selector.
Note, there is no need to backport this to `23.3` as in #5141 the selector is correct (I fixed it while backporting).
- Bugfix
=> fix: remove extra bracket from number field CSS selector

packages/grid/src/vaadin-grid.js, packages/grid/test/basic.test.js
There's currently a [call to `virtualizer.update()` in Grid](https://github.com/vaadin/web-components/blob/5bdf21ca061e9b2dd0ff30451ec68e638c359c47/packages/grid/src/vaadin-grid.js#L543) which takes place whenever the effective size changes. This call causes duplicate row updates/renderer invocations when the grid is rendered the first time and it gets an initial effective size assigned:
This PR changes the logic only to request a content update on effective size change for rows that actually require it:
=> refactor: avoid an unnecessary content update on grid init

integration/tests/overlay-focus-trap.test.js, packages/overlay/package.json, packages/overlay/test/focus-trap.test.js, packages/overlay/test/overlay.test.js, packages/overlay/test/restore-focus.test.js
Some updates to `vaadin-overlay` tests intended to get rid of duplicate tests and to speed up the builds:
1. Split `focus-trap.test.js` in two suites, the one with Vaadin components is moved to `integration` package;
2. Removed duplicate suites added in https://github.com/vaadin/vaadin-overlay/pull/76/commits/a2c4a1dad4043d3d1f9d005d54e4962e74c667c4 - related "scope" logic is [removed](https://github.com/vaadin/web-components/pull/4753) in V24;
3. Updated other test suites in the `overlay` package to use `input` instead of the `vaadin-text-field` element;
4. Replaced `<template>` and extra custom elements with `renderer` and `div` with a shadow root, respectively.
- Tests
=> test: cleanup and simplify overlay focus trap tests

integration/tests/overlay-template.test.js, packages/overlay/package.json, packages/overlay/test/animations.test.js, packages/overlay/test/helpers.js, packages/overlay/test/multiple.test.js, packages/overlay/test/overlay.test.js, packages/overlay/test/position-mixin-listeners.test.js, packages/overlay/test/position-mixin.test.js, packages/overlay/test/restore-focus.test.js
1. Moved `vaadin-overlay` tests for using `<template>` to the `integration` package, as for other components.
2. Updated remaining tests to use `renderer` and removed `@vaadin/polymer-legacy-adapter` dev dependency.
- Tests
=> test: update overlay unit tests to use renderer

packages/grid/test/basic.test.js, packages/grid/theme/lumo/vaadin-grid-styles.js, packages/grid/theme/material/vaadin-grid-styles.js
Updated themes and tests to use grid row parts instead of state attributes like `first`, `last` and `odd`.
Note, some states are still used especially `dragstart` and `dragover` - we might changes these later.
UPD: the reason why I decided to not change `dragover` from attribute to part is because it would mean having to replace single attribute with multiple parts e.g. `dragover-above-row`, `dragover-below-row`, `dragover-on-top-row`.
- Refactor
=> refactor: use row parts instead of states in themes

packages/field-base/src/input-field-mixin.js, packages/field-base/test/input-field-mixin.test.js, packages/login/test/dom/__snapshots__/login-form.test.snap.js, packages/login/test/dom/__snapshots__/login-overlay.test.snap.js
Fixes https://github.com/vaadin/flow-components/issues/4452
Added `reflectToAttribute: true` to fix a Chrome specific issue where setting `autocapitalize` attribute does not set corresponding property and it remains `undefined` so the delegation observer fails to set it on the `<input>`.
This only affects `autocapitalize` - two other properties work fine, so I didn't add `reflectToAttribute` there.
While I don't really like inconsistency, this is the cleanest fix that I was able to come up with 🤷‍♂️ 
See https://github.com/vaadin/flow-components/issues/4452#issuecomment-1366514219
- Bugfix
=> fix: propagate autocapitalize attribute in Chrome

packages/field-base/src/input-field-mixin.js, packages/field-base/test/input-field-mixin.test.js, packages/login/test/dom/__snapshots__/login-form.test.snap.js, packages/login/test/dom/__snapshots__/login-overlay.test.snap.js
Manual cherry-pick of #5175 to `23.3` branch. 
The automated cherry-pick failed because of conflicts was caused by snapshots and lack of Lit tests on this branch.
- Cherry-pick
=> fix: propagate autocapitalize attribute in Chrome (#5175) (CP: 23.3)

packages/field-base/src/input-field-mixin.js, packages/field-base/test/input-field-mixin.test.js
Manual cherry-pick of #5175 to `22.0` branch. 
The automated cherry-pick failed because of conflicts lack of Lit tests on this branch, as well as login snapshots.
- Cherry-pick
=> fix: propagate autocapitalize attribute in Chrome (#5175) (CP: 22.0)

packages/accordion/src/vaadin-accordion-panel.js, packages/details/src/vaadin-details.js
This PR improves API documentation for `vaadin-details` and `vaadin-accordion-panel`, see comparison below.
Added missing `DetailsMixin` with `opened` property.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
Added JSDoc for all the mixins - this is needed because `AccordionPanel` no longer extends `Details`.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
=> docs: fix details and accordion-panel mixins JSDoc

packages/field-base/src/input-constraints-mixin.d.ts, packages/field-base/src/pattern-mixin.d.ts
For some reason, most likely due to copy-paste, `DisabledMixin` is used in typings of mixins that don't apply it internally.
Updated `PatternMixin` and `InputConstraintsMixin` types accordingly. This doesn't affect actual components.
=> docs: remove incorrect usage of DisabledMixin types

packages/crud/src/vaadin-crud-form.js, packages/crud/src/vaadin-crud-grid.js, packages/crud/src/vaadin-crud-helpers.d.ts, packages/crud/src/vaadin-crud-helpers.js, packages/crud/src/vaadin-crud-include-mixin.js, packages/crud/src/vaadin-crud.js, packages/crud/test/crud-form.test.js, packages/crud/test/crud-grid.test.js, packages/crud/test/crud.test.js
Moved some common methods to `vaadin-crud-helpers.js` (file name chosen to align with `vaadin-grid-helpers.js`).
Also updated unit tests to actually use these helpers, rather than calling private methods of components 🙈 
Related to #5184 - some changes in this PR include removal of `||=` syntax to ensure `polymer-analyzer` doesn't fail.
- Refactor
=> refactor: extract duplicate internal methods to helpers

packages/confirm-dialog/src/vaadin-confirm-dialog-overlay.js, packages/confirm-dialog/src/vaadin-confirm-dialog.js, packages/confirm-dialog/test/confirm-dialog.test.js
Closes #430
Changed the logic needed by the Flow counterpart to set [width](https://github.com/vaadin/flow-components/blob/e729f10c3c7c451862110a6dae5a0afb94031727/vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialog.java#L125) and [height](https://github.com/vaadin/flow-components/blob/e729f10c3c7c451862110a6dae5a0afb94031727/vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialog.java#L148).
Replaced private methods with properties (marked as protected for now).
We could consider making these properties private in a separate PR.
- Refactor
=> refactor!: improve logic for setting overlay dimensions

packages/confirm-dialog/src/vaadin-confirm-dialog-overlay.js, packages/confirm-dialog/test/confirm-dialog.test.js
Follow-up to #5187. The logic added in that PR causes the following CSS properties to be set by default:
```
--_vaadin-confirm-dialog-content-height: undefined;
--_vaadin-confirm-dialog-content-width: undefined;
```
While it works as these values are ignored by CSS, let's fix this to avoid setting such falsy values.    
- Refactor
=> refactor: reset style property when setting empty value

packages/accordion/src/vaadin-accordion-panel.js
The `_collapsible` property usage was removed in #5109 but the property itself is still there. Let's remove it.
- Refactor
=> refactor: remove no longer used protected property

packages/accordion/src/vaadin-accordion-panel.js, packages/details/src/vaadin-details.js
Extracted from #5164 to make that PR diff smaller, as this change makes sense on its own:
- Controllers are now created in `constructor` as e.g. in mixins,
- Controllers are added in the correct order in `ready` callback.
- Refactor
=> refactor: reorganize controllers initialization logic

packages/grid/src/vaadin-grid.js
- Replaced usage of `||=` with default parameters and updated one method invocation,
- Removed obsolete `eslint-disable` comment: our config allows up to 5 parameters.
- Refactor
=> refactor: use default parameters in update row method

packages/date-picker/src/vaadin-date-picker-mixin.js
Updated the date-picker overlay opened listener to simplify the logic. 
Also replaced usage of `||=` with a separate variable, see #5184.
- Refactor
=> refactor: simplify logic for setting initial position

packages/date-picker/src/vaadin-date-picker-overlay-content.js
Updated `vaadin-date-picker-overlay-content` logic to simplify some methods. 
Also replaced one usage of `||=` with a separate condition, see #5184.
- Refactor
=> refactor: simplify moving focus between dates logic

packages/field-base/src/label-controller.js
Removed the `initNode` override from `LabelController` because it's not needed:
- `updateDefaultNode` is called in `setLabel` after the default `<label>` is created;
- `observeNode` is also triggered from `restoreDefaultNode` called by `setLabel`.
The method was added in the initial version of the controller, but then I refactored it.
- Refactor
=> refactor: remove not needed override in LabelController

packages/accordion/src/vaadin-accordion-panel.js, packages/component-base/src/slot-child-observe-controller.d.ts, packages/component-base/src/slot-child-observe-controller.js, packages/details/src/content-controller.d.ts, packages/details/src/content-controller.js, packages/field-base/src/error-controller.d.ts, packages/field-base/src/error-controller.js, packages/field-base/src/helper-controller.d.ts, packages/field-base/src/helper-controller.js, packages/field-base/src/label-controller.d.ts, packages/field-base/src/label-controller.js
As discussed with @vursen internally, this controller is named incorrectly: it doesn't observe the `<slot>` element itself (that is actually handled by `SlotController`), but the child node added to it. Renamed it to make this clear.
- Refactor
=> refactor: rename SlotObserveController to clarify its goal

packages/accordion/src/vaadin-accordion-heading.js, packages/accordion/src/vaadin-accordion-panel.js, packages/accordion/src/vaadin-accordion.js, packages/accordion/test/accordion.test.js, packages/details/src/vaadin-details-mixin.d.ts, packages/details/src/vaadin-details-mixin.js, packages/details/src/vaadin-details.js, packages/details/test/details.test.js
- Removed usage of `_toggleElement` which is different in case of `vaadin-details` and `vaadin-accordion-panel`;
- Moved logic related to setting `aria-expanded` from `DetailsMixin` to these components that set it differently;
- Removed usage of waiting for Shadow DOM of `vaadin-accordion-heading` inside of `vaadin-accordion-panel`.
- Refactor
=> refactor: simplify details and accordion toggle logic

dev/accordion.html, dev/details.html, packages/accordion/src/vaadin-accordion-panel.d.ts, packages/accordion/src/vaadin-accordion-panel.js, packages/accordion/test/accordion-panel.test.js, packages/details/src/summary-controller.d.ts, packages/details/src/summary-controller.js, packages/details/src/vaadin-details-mixin.js, packages/details/src/vaadin-details.d.ts, packages/details/src/vaadin-details.js, packages/details/test/details.test.js, packages/details/test/dom/__snapshots__/details.test.snap.js
Fixes #5077
1. Added `summary` property to `vaadin-details` and `vaadin-acordion-panel` components as an alternative to slot,
2. Updated the `DetailsMixin` to add `ContentController` for setting `_contentElements` to reduce code duplication,
3. Simplified the logic for setting content ARIA attributes to use observers (each components uses its own observer),
4. Added missing tests for `vaadin-accordion-panel`, updated some tests to use both `summary` property and slot.
- Feature
=> feat: add summary property to details and accordion panel

packages/charts/src/vaadin-chart.js, packages/component-base/src/element-mixin.js, packages/component-base/src/iron-list-core.js, packages/component-base/src/polylit-mixin.js, packages/component-base/src/virtualizer-iron-list-adapter.js, packages/date-picker/src/vaadin-date-picker-overlay-content.js, packages/date-picker/test/common.js, packages/date-time-picker/src/vaadin-date-time-picker.js, packages/grid/src/vaadin-grid-column-group.js, packages/grid/src/vaadin-grid-column-reordering-mixin.js, packages/grid/src/vaadin-grid.js, packages/icon/src/vaadin-iconset.js, packages/polymer-legacy-adapter/src/style-modules.js, packages/polymer-legacy-adapter/src/template-renderer.js, packages/tabsheet/src/vaadin-tabsheet.js, packages/time-picker/src/vaadin-time-picker.js, packages/upload/src/vaadin-upload.js
This PR fixes a regression from #5133 that caused API docs to contain internal Polymer properties and methods:
- alpha6: https://cdn.vaadin.com/vaadin-web-components/24.0.0-alpha6/
- alpha7: https://cdn.vaadin.com/vaadin-web-components/24.0.0-alpha7/
The problem seems to be caused by the fact that `polymer-analyzer` fails to parse JS using `||=` syntax.
So it uses `ElementMixin` from Polymer instead of the `ElementMixin` from `@vaadin/component-base`.
=> refactor: avoid logical assignment operator to not break API docs

packages/vaadin-lumo-styles/version.js, packages/vaadin-material-styles/version.js
These internal classes should't appear in the API docs, but at least `Lumo` gets listed there, see [24.0.0-alpha8](https://cdn.vaadin.com/vaadin-web-components/24.0.0-alpha8/#/elements/vaadin-lumo-styles) docs.
Added missing JSDoc annotation to clarify the purpose of these elements and exclude them from API.
=> docs: add private JSDoc annotation to theme classes

packages/integer-field/test/validation.test.js, packages/number-field/src/vaadin-number-field.js, packages/number-field/test/validation.test.js
The PR ensures NumberField and IntegerField revalidate after the user has removed bad input.
> **Warning**
> This is an altering behavior change. The manually set `invalid` flag can get removed once anything triggers number fields to revalidate, even if the developer didn't add any constraints.
Part of https://github.com/vaadin/web-components/issues/5138
=> fix!: revalidate number fields after bad input is removed

packages/component-base/src/overlay-class-mixin.d.ts, packages/component-base/src/overlay-class-mixin.js, packages/component-base/test/overlay-class-mixin.test.js
Related to #5121
- Feature
- Implementation is largely copied from Lit [`classMap`](https://github.com/lit/lit/blob/main/packages/lit-html/src/directives/class-map.ts) directive;
- Tests are also inspired by the [`classMap`](https://github.com/lit/lit/blob/main/packages/lit-html/src/test/directives/class-map_test.ts) directive unit tests.
=> feat: add OverlayClassMixin to forward CSS class names

packages/integer-field/test/validation.test.js, packages/number-field/src/vaadin-number-field.js, packages/number-field/test/validation.test.js
The PR cherry-picks the following fixes to `23.2`:
- https://github.com/vaadin/web-components/pull/5206
> **Warning**
> This is an altering behavior change. The manually set `invalid` flag can get removed once anything triggers number fields to revalidate, even if the developer didn't add any constraints. However, we still do this change because it is actually a proper fix for the bug.
> **Note**
> No conflicts were reported. I had to perform this cherry-pick manually because I added the target label to the original PR too late.
Fixes https://github.com/vaadin/web-components/issues/5138
=> fix!: revalidate number fields after bad input is removed (#5138) (CP: 23.2)

packages/combo-box/src/vaadin-combo-box.d.ts, packages/combo-box/src/vaadin-combo-box.js
Updated the code example in `vaadin-combo-box` JSDoc to use example from the dev page with `fetch`.
This fixes the VS Code syntax highlighting which for some reason is broken with the current example:
Also refactored the code snippet to ensure it's fully visible in the API docs without scrolling horizontally:
=> docs: use fetch in combo-box dataProvider example

packages/context-menu/src/vaadin-context-menu.js, packages/context-menu/test/items.test.js, packages/context-menu/test/renderer.test.js
Updated `requestContentUpdate()` method in `vaadin-context-menu` to apply missing checks that should be there.
Here are relevant conditions that we have in other components, namely `vaadin-notification` and `vaadin-select`:
https://github.com/vaadin/web-components/blob/3c55d6117bb7d378c45098c68516f5ba1efeaf95/packages/notification/src/vaadin-notification.js#L400-L403
https://github.com/vaadin/web-components/blob/3c55d6117bb7d378c45098c68516f5ba1efeaf95/packages/select/src/vaadin-select.js#L369-L372
- Bugfix
=> fix: do not throw on requestContentUpdate before attach

packages/context-menu/test/lit-renderer-directives.test.js
Updated Lit renderer directive tests to improve HTML literals formatting and get rid of the `lit-analyzer` warning:
```
(parameter) content: any
Type 'DirectiveResult<{ prototype: any; new(_partInfo: ChildPartInfo | AttributePartInfo | ElementPartInfo) => Directive; }> | null' is not a Lit 2 directive'lit-plugin(no-incompatible-type-binding)(2304)
```
- Tests
=> test: improve context-menu Lit renderer tests formatting

packages/date-picker/src/vaadin-infinite-scroller.js, packages/date-picker/test/dom/__snapshots__/date-picker.test.snap.js, packages/date-picker/test/dom/date-picker.test.js
- Updated the infinite scroller used by `vaadin-date-picker` to generate unique ID using our helpers,
- Added basic and `theme` attribute propagation snapshot tests for `vaadin-date-picker-overlay`.
- Refactor + Tests
This is a pre-requisite for adding `overlayClass` as I'm going to cover it with a snapshot test too.
=> refactor: use unique ID in scroller, add snapshot tests

packages/menu-bar/test/dom/__snapshots__/menu-bar.test.snap.js, packages/menu-bar/test/dom/menu-bar.test.js
Added snapshot tests to `vaadin-menu-bar`. This is a pre-requisite for adding `overlayClass` property. 
- Tests
=> test: add missing snapshot tests to vaadin-menu-bar

packages/menu-bar/src/vaadin-menu-bar.d.ts, packages/menu-bar/src/vaadin-menu-bar.js, packages/menu-bar/test/dom/__snapshots__/menu-bar.test.snap.js, packages/menu-bar/test/dom/menu-bar.test.js, packages/menu-bar/test/typings/menu-bar.types.ts
Based on #5207
- Feature
As the `vaadin-menu-bar` doesn't have its own overlay, I decided not to use `OverlayClassMixin` here.
Instead, the property is defined separately with an appropriate JSDoc and propagated to sub-menu.
=> feat: add overlayClass property to vaadin-menu-bar

packages/avatar-group/test/typings/avatar-group.types.ts
Added missing type definition tests for `avatar-group` package. 
This will be needed when adding `overlayClass` property.
- Tests
=> test: add missing typings tests to vaadin-avatar-group

packages/avatar-group/test/dom/__snapshots__/avatar-group.test.snap.js, packages/avatar-group/test/dom/avatar-group.test.js
Added missing overlay snapshot tests for `vaadin-avatar-group`. 
This will be needed when adding `overlayClass` property.
- Tests
=> test: add missing avatar-group overlay snapshot tests

packages/combo-box/src/vaadin-combo-box-scroller.js, packages/combo-box/test/dom/__snapshots__/combo-box.test.snap.js, packages/time-picker/test/dom/__snapshots__/time-picker.test.snap.js
Currently, `aria-setsize` is set on the container with `role="listbox"`.  This is not correct and instead should be placed on each item along with `aria-posinset`.  In addition, the value for the set size currently used is incorrectly 0 when a `dataProvider` is used.
Fixes #3255
=> fix[combo-box]: Correct aria-setsize placement on scroller

packages/combo-box/src/vaadin-combo-box-scroller.js, packages/combo-box/test/aria.test.js, packages/time-picker/test/aria.test.js
Manual cherry-pick of #5254 to `22.0` branch.
Note, there are no snapshot tests in this branch, so I had to modify the commit and adjust unit tests accordingly.
- Cherry-pick
=> fix: set aria-setsize attribute on items instead of the scroller (#5254) (CP: 22.0)

packages/message-input/src/vaadin-message-input.js
Fixes #5258
Added `@event` to make sure this event is picked up by `polymer-analyzer` and ends up in `web-types.json`.
=> docs: add missing JSDoc annotation for the submit event

packages/grid/src/vaadin-grid-active-item-mixin.js, packages/grid/test/keyboard-navigation.test.js
When entering from cell navigation mode to interaction mode (by pressing enter), `<vaadin-grid>` Web Component tries to automatically focus the first element (within the cell) it considers focusable.
https://user-images.githubusercontent.com/1222264/211284364-ed8a3259-e356-49b3-a964-6aede75cb970.mp4
The current logic erroneously considers `<label>` and `<input style="visibility: hidden">` elements as focusable. This PR fixes the issue.
Addresses https://github.com/vaadin/flow-components/pull/4483#discussion_r1064383335
=> fix: do not consider label and hidden elements focusable

packages/grid/src/vaadin-grid-active-item-mixin.js, packages/grid/src/vaadin-grid-tree-toggle.js, packages/grid/test/renderers.test.js, packages/grid/test/tree-toggle.test.js
Fixes a regression caused by https://github.com/vaadin/web-components/pull/5263
- Clicking a `<label>` element inside a grid cell shouldn't affect the active item.
- Clicking a `<label>` inside a `<vaadin-grid-tree-toggle>` shouldn't toggle the expanded item
Before:
https://user-images.githubusercontent.com/1222264/211525821-ed3959f0-cc20-4436-9fb7-fa4d78a90be2.mp4
After:
https://user-images.githubusercontent.com/1222264/211525857-42f5a975-49d4-4784-b95c-52b2e7afd2c3.mp4
- Bugfix
=> fix: ignore label clicks in grid cells

packages/notification/test/not-animated-styles.js, packages/notification/test/visual/lumo/notification.test.js, packages/notification/test/visual/material/notification.test.js
Looks like #5253 introduced some flakiness to `vaadin-notification` visual tests. 
This PR disables animations that have a risk of causing this flakiness.
- Tests
=> test: disable animation in notification visual tests

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.d.ts, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/multi-select-combo-box/test/dom/__snapshots__/multi-select-combo-box.test.snap.js, packages/multi-select-combo-box/test/dom/multi-select-combo-box.test.js, packages/multi-select-combo-box/test/typings/multi-select-combo-box.types.ts
Based on #5207
- Feature
As the overlay in placed in a nested shadow root, I decided not to use `OverlayClassMixin` in this case.
Instead, the property is defined separately with an appropriate JSDoc and propagated to combo-box.
=> feat: add overlayClass property to vaadin-multi-select-combo-box

packages/date-time-picker/src/vaadin-date-time-picker.d.ts, packages/date-time-picker/src/vaadin-date-time-picker.js, packages/date-time-picker/test/dom/__snapshots__/date-time-picker.test.snap.js, packages/date-time-picker/test/dom/date-time-picker.test.js, packages/date-time-picker/test/typings/date-time-picker.types.ts
Based on #5207
- Feature
As the date-time-picker doesn't have own overlay, I decided not to use `OverlayClassMixin` in this case.
Instead, the property is defined separately with an appropriate JSDoc and propagated to pickers.
=> feat: add overlayClass property to vaadin-date-time-picker

packages/checkbox/theme/lumo/vaadin-checkbox-styles.js, packages/checkbox/theme/material/vaadin-checkbox-styles.js, packages/radio-group/theme/lumo/vaadin-radio-button-styles.js, packages/radio-group/theme/material/vaadin-radio-button-styles.js, packages/vaadin-lumo-styles/style.js, packages/vaadin-material-styles/style.d.ts, packages/vaadin-material-styles/style.js
Follow-up to #5288. 
As discussed internally, defaults for component specific custom CSS properties should be placed in themes.
This is needed in order to make it possible for users to override them globally, or on the separate element.
- Refactor
=> refactor: move component properties defaults to themes

dev/grid-performance.html
Update `grid-performance.html` dev page to not include `<vaadin-text-field>`s. This is to fully focus on `<vaadin-grid>` performance on the page without having the `<vaadin-text-field>` instances distort the metrics. Also increased the column count from 200 to 400.
=> chore: remove text-field from grid performance dev page

packages/button/test/button.test.js
- Updated `vaadin-button` unit tests to use `button` variable name instead of the `element`;
- Added `nextRender()` for easier debugging and to reduce changes during Lit conversion;
- Changed tests for keyboard events to use `spy.firstCall` for getting an event reference.
- Tests
=> test: update button unit tests, wait for fixture render

packages/progress-bar/test/progress-bar.test.js
- Updated `vaadin-progress-bar` unit tests to move all the test suites under a parent suite;
- Added "custom element definition" test suite to align with other components that have it;
- Added `nextRender()` for easier debugging and to reduce changes during Lit conversion;
- Changed tests to import `src` version of the component instead of the Lumo styled one;
- Tests
=> test: update progress-bar tests, wait for fixture render

packages/time-picker/src/vaadin-time-picker.js, packages/time-picker/test/time-picker.test.js
For `time-picker`, a value that that was out of range was updated to conform to min and max constraints. In order to align this behaviour with `date-picker`, this PR makes sure that the value is not updated even if it is invalid.
This is a breaking change.
Fixes #4182
=> fix!: do not adjust values that are out of allowed range

packages/dialog/test/dom/__snapshots__/dialog.test.snap.js, packages/dialog/test/dom/dialog.test.js, packages/dialog/test/typings/dialog.types.ts
Added missing snapshot tests to `vaadin-dialog` for testing overlay DOM. Also extended typings tests.
This is done in preparation for adding `OverlayClassMixin` which will be also covered by these tests.
- Tests
=> test: add missing dialog snapshots and types tests

packages/dialog/src/vaadin-dialog-overlay.js
Removed the workaround for Safari 13 as the problem was fixed later, and we support Safari 15+ in Vaadin 24.
Here is the original bug: https://github.com/vaadin/vaadin-dialog-flow/issues/207#issuecomment-662386853
Related PRs in `vaadin-dialog` web component from 2020:
- https://github.com/vaadin/vaadin-dialog/pull/182
- https://github.com/vaadin/vaadin-dialog/pull/186
- Refactor
Can be tested with the following HTML snippet in the dialog dev page:
```html
<vaadin-dialog modeless resizable opened>
<template>
<vaadin-text-area value="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in …
```
=> refactor: remove no longer needed Safari 13 workaround

packages/grid/src/vaadin-grid-sort-mixin.js, packages/grid/src/vaadin-grid-sorter.d.ts, packages/grid/src/vaadin-grid-sorter.js, packages/grid/test/sorting.test.js, packages/grid/test/typings/grid.types.ts
Add a flag in the `sorter-changed` event to allow the sorting mechanism to detect whether the event was triggered by a user interaction with the sorter or something else (eg. changing `sorter.direction`).
Currently, if `multiSortOnShiftClick` was enabled, it wasn't possible to programmatically do a multi-sorting on the grid.
Fixes https://github.com/vaadin/flow-components/issues/4362
=> fix: allow programmatically multi-sorting if multiSortOnShiftClick is enabled

packages/confirm-dialog/test/dom/__snapshots__/confirm-dialog.test.snap.js, packages/confirm-dialog/test/dom/confirm-dialog.test.js, packages/confirm-dialog/test/typings/confirm-dialog.types.ts
Same as #5308 but for `vaadin-confirm-dialog`.
Added missing snapshot tests to `vaadin-confirm-dialog` for testing overlay DOM. Also extended typings tests.
This is done in preparation for adding `OverlayClassMixin` which will be also covered by these tests.
- Tests
=> test: add missing confirm-dialog snapshots and types tests

packages/login/src/vaadin-login-overlay.js
Updated `vaadin-login-overlay` to avoid removing listeners and adding them back, it's actually not needed.
These events are guaranteed to only fire if the overlay is attached and its `_last` getter returns `true`:
https://github.com/vaadin/web-components/blob/120b978fb0e1a1fd0c1ffad2472387cbb58e4e0f/packages/overlay/src/vaadin-overlay.js#L429-L431
https://github.com/vaadin/web-components/blob/120b978fb0e1a1fd0c1ffad2472387cbb58e4e0f/packages/overlay/src/vaadin-overlay.js#L452-L454
Also changed `connectedCallback()` and `disconnectedCallback()` to check `opened` on the host element.
- Refactor
=> refactor: simplify logic to change login overlay opened

packages/confirm-dialog/src/vaadin-confirm-dialog.d.ts, packages/confirm-dialog/src/vaadin-confirm-dialog.js, packages/confirm-dialog/test/dom/__snapshots__/confirm-dialog.test.snap.js, packages/confirm-dialog/test/dom/confirm-dialog.test.js, packages/confirm-dialog/test/typings/confirm-dialog.types.ts
Related to https://github.com/vaadin/web-components/issues/5121
Based on #5207
- Feature
As the overlay in placed in a nested shadow root, I decided not to use `OverlayClassMixin` in this case.
Instead, the property is defined separately with an appropriate JSDoc and propagated to the dialog.
=> feat: add overlayClass property to vaadin-confirm-dialog

packages/notification/test/dom/__snapshots__/notification.test.snap.js, packages/notification/test/dom/notification.test.js, packages/notification/test/typings/notification.types.ts
Added missing snapshot tests to `vaadin-notification` for testing card DOM. Also extended typings tests.
This is done in preparation for adding `OverlayClassMixin` which will be also covered by these tests.
- Tests
=> test: add missing notification snapshots and types tests

packages/input-container/src/vaadin-input-container.js, packages/input-container/theme/lumo/vaadin-input-container-styles.js, packages/vaadin-lumo-styles/style.js
Related to #2954
Originally inspired by https://github.com/vaadin/web-components/pull/5251#pullrequestreview-1240365133
These individual properties would enable us to implement the filled Material text field:
- Feature
=> feat: add custom CSS properties for field border-radius

packages/checkbox/src/vaadin-checkbox.js, packages/checkbox/test/dom/__snapshots__/checkbox.test.snap.js
Added `aria-hidden` attribute to ensure the `::before` pseudo-element is not announced by screen readers.
See https://github.com/vaadin/web-components/pull/5288#discussion_r1068047861 for the discussion around the checkmark icon where this solution was proposed.
- Refactor
=> refactor: set aria-hidden attribute on the checkbox part

packages/radio-group/src/vaadin-radio-button.js, packages/radio-group/test/dom/__snapshots__/radio-button.test.snap.js
Same as #5322 but for `vaadin-radio-button` which also has `::before` pseudo-element that we don't need to announce.
- Refactor
=> refactor: set aria-hidden attribute on the radio part

packages/accordion/src/vaadin-accordion-heading.d.ts
This `@fires` annotation is clearly a copy-paste: in `vaadin-accordion-heading`, the `opened` property does not notify.
=> docs: remove incorrect JSDoc from vaadin-accordion-heading

packages/button/test/typings/button.types.ts
We missed to add tests to the `button` package because it didn't have any event types. Let's add them now.
- Tests
=> test: add missing TS definitions tests to vaadin-button

packages/icons/gulpfile.cjs, packages/icons/test/visual/vaadin-iconset.test.js, packages/icons/vaadin-iconset.js
Extracted from #5334.
This is technically a breaking change - for example, I had to update visual tests to use a different import.
In fact, this line shoudn't be there: the `vaadin-iconset` does not require importing `vaadin-icon`.
For anyone who wants to import both, there is still `vaadin-icons.js` entrypoint that does it.
Ideally, we would remove that entrypoint altogether, but we missed to deprecate it in V23 😕 
Also, this is how Lumo iconset is organized. So let's consider changing it here for consistency.
Refactor
=> refactor!: remove vaadin-icon import from vaadin-iconset.js

packages/context-menu/src/vaadin-context-menu-item.d.ts, packages/context-menu/src/vaadin-context-menu-item.js, packages/context-menu/src/vaadin-context-menu-list-box.d.ts, packages/context-menu/src/vaadin-context-menu-list-box.js, packages/context-menu/src/vaadin-contextmenu-items-mixin.d.ts, packages/context-menu/src/vaadin-contextmenu-items-mixin.js
Pre-requisite for #3010
Moved the components used by `vaadin-context-menu` to separate files, like it's done e.g. in `vaadin-select` package.
- Refactor
=> refactor: move item and list-box extensions to separate files

packages/grid-pro/src/vaadin-grid-pro-edit-column.js, packages/grid-pro/test/lit.test.js
This PR makes grid-pro run the column renderer on `_removeEditor(cell, _model)` only for the given cell instead of for all the cells on the same row.
Fixes https://github.com/vaadin/flow-components/issues/4562
Why the issue above occurred with the previous implementation:
When entering edit mode for a cell while another cell editor was open...
1. To clear the old editor, `renderer` was run for each cell on the same row where the editor was, even the new edit cell
2. An `editModeRenderer` was run for the new edit cell
A `ComponentRenderer` was used as the `renderer` in phase 1 for the new edit cell which should be fine. However, the updated implementation of `ComponentRenderer` uses Lit's `until` directive, which renders asynchronously once the given promise resolves. By the time that …
=> fix: do not update the whole row when removing grid-pro editor

README.md
Since Vaadin 24, support for Safari 14 is dropped. All iOS devices can be upgraded from Safari 14 to 15.
This enables us to use certain modern features in our web components and themes, especially:
- [Shadow root `delegatesFocus`](https://caniuse.com/mdn-api_shadowroot_delegatesfocus) API which we already use in [`vaadin-accordion`](https://github.com/vaadin/web-components/blob/e1d75d23b4e783575caef2c35fa89bd7f8a73a86/packages/accordion/src/vaadin-accordion-heading.js#L109) in V24,
- [CSS Logical Properties](https://caniuse.com/css-logical-props) - including shorthands and logical border radius properties.
=> chore: update minimally supported Safari version to 15

packages/context-menu/src/vaadin-context-menu-overlay.js, packages/context-menu/src/vaadin-contextmenu-items-mixin.d.ts, packages/context-menu/src/vaadin-contextmenu-items-mixin.js, packages/menu-bar/src/vaadin-menu-bar-overlay.js, packages/menu-bar/src/vaadin-menu-bar-submenu.js, packages/menu-bar/src/vaadin-menu-bar.d.ts, packages/menu-bar/src/vaadin-menu-bar.js, packages/menu-bar/test/dom/__snapshots__/menu-bar.test.snap.js, packages/menu-bar/theme/lumo/vaadin-menu-bar-overlay-styles.js, packages/menu-bar/theme/material/vaadin-menu-bar-overlay-styles.js
Part of #3010
Updated `vaadin-menu-bar` to use `_tagNamePrefix` for the overlay. It will be also used for items, see #5339
This is also what we do e.g. with `vaadin-time-picker-overlay` that extends `vaadin-combo-box-overlay`.
- Refactor
=> refactor!: update menu-bar to use vaadin-menu-bar-overlay

packages/context-menu/theme/lumo/vaadin-context-menu-list-box-styles.js, packages/context-menu/theme/lumo/vaadin-context-menu-styles.js, packages/context-menu/theme/lumo/vaadin-context-menu.js, packages/context-menu/theme/material/vaadin-context-menu-list-box-styles.js, packages/context-menu/theme/material/vaadin-context-menu-styles.js, packages/context-menu/theme/material/vaadin-context-menu.js
Same as #5359 but for `vaadin-context-menu-list-box`. 
Pre-requisite for #5354
=> feat: export context-menu list-box styles as CSS literals

packages/menu-bar/test/not-animated-styles.js
Follow-up from #5353 where I forgot to change the tag name in `not-animated-styles` JS module.
- Tests
=> test: update not-animated-styles to use new overlay

packages/context-menu/theme/lumo/vaadin-context-menu-item-styles.js, packages/context-menu/theme/lumo/vaadin-context-menu-styles.js, packages/context-menu/theme/lumo/vaadin-context-menu.js, packages/context-menu/theme/material/vaadin-context-menu-item-styles.js, packages/context-menu/theme/material/vaadin-context-menu-styles.js, packages/context-menu/theme/material/vaadin-context-menu.js
Same as #5359 but for `vaadin-context-menu-item`. 
Pre-requisite for #5354
=> feat: export context-menu item styles as CSS literals

packages/crud/test/helpers.js, packages/grid-pro/test/helpers.js, packages/grid/test/helpers.js
Remove the separate `flushGrid` helpers from `grid-pro` and `crud`, and re-export the helper from `grid` instead.
=> test: share flushGrid test helper between grid, grid-pro and crud

packages/context-menu/src/vaadin-contextmenu-items-mixin.js, packages/menu-bar/src/vaadin-menu-bar-button.js, packages/menu-bar/src/vaadin-menu-bar-item.js, packages/menu-bar/src/vaadin-menu-bar-mixin.js, packages/menu-bar/src/vaadin-menu-bar-submenu.js, packages/menu-bar/src/vaadin-menu-bar.d.ts, packages/menu-bar/src/vaadin-menu-bar.js, packages/menu-bar/test/dom/__snapshots__/menu-bar.test.snap.js, packages/menu-bar/test/dom/menu-bar.test.js, packages/menu-bar/test/menu-bar.test.js, packages/menu-bar/test/sub-menu.test.js, packages/menu-bar/test/visual/lumo/menu-bar.test.js, packages/menu-bar/test/visual/material/menu-bar.test.js, packages/menu-bar/theme/lumo/vaadin-menu-bar-button-styles.js, packages/menu-bar/theme/lumo/vaadin-menu-bar-item-styles.js, packages/menu-bar/theme/material/vaadin-menu-bar-button-styles.js, packages/menu-bar/theme/material/vaadin-menu-bar-item-styles.js
Fixes #3010
Based on #5353 and `_tagNamePrefix` API added in that PR.
Depends on #5354 which includes changes for the list-box.
- Refactor
=> refactor!: update menu-bar to use vaadin-menu-bar-item

packages/combo-box/src/vaadin-combo-box-item-mixin.d.ts, packages/combo-box/src/vaadin-combo-box-item-mixin.js, packages/combo-box/src/vaadin-combo-box-item.d.ts, packages/combo-box/src/vaadin-combo-box-item.js, packages/combo-box/src/vaadin-combo-box-mixin.d.ts, packages/combo-box/test/typings/combo-box.types.ts
Part of #5358
1. Created `ComboBoxItemMixin` to be used by `vaadin-time-picker-item` and `vaadin-multi-select-combo-box-item`,
2. Added missing type definitions for `vaadin-combo-box-item` element and corresponding tests to the typings folder.
- Refactor
=> refactor: extract vaadin-combo-box-item logic to the mixin

dev/select.html, packages/select/src/vaadin-select-item.d.ts, packages/select/src/vaadin-select-item.js, packages/select/test/dom/__snapshots__/select.test.snap.js, packages/select/test/typings/select.types.ts, packages/select/test/visual/lumo/select.test.js, packages/select/test/visual/material/select.test.js, packages/select/theme/lumo/vaadin-select-styles.js, packages/select/theme/lumo/vaadin-select.js, packages/select/theme/material/vaadin-select-styles.js, packages/select/theme/material/vaadin-select.js
Same as #5366 but for `vaadin-select-item`. Note, I also added TS definitions for consistency.
=> refactor!: make vaadin-select-item not extend vaadin-item

packages/context-menu/test/helpers.js, packages/context-menu/test/items.test.js
Extracted several context-menu test helpers into `helpers.js` in order to reuse them later in:
- `items.test.js`
- `items-theme.test.js`
- `items-class.test.js`
=> test: extract common context-menu test helpers

packages/combo-box/theme/lumo/vaadin-combo-box-item-styles.js, packages/combo-box/theme/material/vaadin-combo-box-item-styles.js, packages/time-picker/src/vaadin-time-picker-item.d.ts, packages/time-picker/src/vaadin-time-picker-item.js, packages/time-picker/test/typings/time-picker.types.ts, packages/time-picker/theme/lumo/vaadin-time-picker-styles.js, packages/time-picker/theme/material/vaadin-time-picker-styles.js
Note, I also added missing type definitions for consistency with other item elements.
- Refactor
=> refactor!: make time-picker item not extend combo-box item

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-item.d.ts, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-item.js, packages/multi-select-combo-box/test/typings/multi-select-combo-box.types.ts, packages/multi-select-combo-box/theme/lumo/vaadin-multi-select-combo-box-styles.js, packages/multi-select-combo-box/theme/lumo/vaadin-multi-select-combo-box.js, packages/multi-select-combo-box/theme/material/vaadin-multi-select-combo-box-styles.js, packages/multi-select-combo-box/theme/material/vaadin-multi-select-combo-box.js
Same as #5381 but for `vaadin-multi-select-combo-box-item` element.
Note, I also added missing type definitions for consistency with other item elements.
- Refactor
=> refactor!: make multi-select-combo-box item not extend item

packages/context-menu/src/vaadin-context-menu-overlay.d.ts, packages/context-menu/src/vaadin-context-menu-overlay.js, packages/context-menu/src/vaadin-menu-overlay-mixin.d.ts, packages/context-menu/src/vaadin-menu-overlay-mixin.js, packages/context-menu/src/vaadin-menu-overlay-styles.d.ts, packages/context-menu/src/vaadin-menu-overlay-styles.js, packages/context-menu/theme/lumo/vaadin-context-menu-overlay-styles.js, packages/context-menu/theme/lumo/vaadin-context-menu.js, packages/context-menu/theme/material/vaadin-context-menu-overlay-styles.js, packages/context-menu/theme/material/vaadin-context-menu.js, packages/menu-bar/src/vaadin-menu-bar-overlay.d.ts, packages/menu-bar/src/vaadin-menu-bar-overlay.js, packages/menu-bar/theme/lumo/vaadin-menu-bar-overlay-styles.js, packages/menu-bar/theme/lumo/vaadin-menu-bar.js, packages/menu-bar/theme/material/vaadin-menu-bar-overlay-styles.js, packages/menu-bar/theme/material/vaadin-menu-bar.js
Related to #5358
Follow-up to #5353 where the `vaadin-menu-bar-overlay` was added.
- Refactor
=> refactor: extract shared menu overlay logic to the mixin

packages/grid-pro/theme/lumo/vaadin-grid-pro-styles.js
Fixes #5395
Changed to use `[tabindex]` attribute which applies to focusable elements in shadow DOM.
These are either cells or buttons depending on whether Mac OS is used, see #4260
- Bugfix
=> fix: use correct selector for highlight-read-only-cells theme

packages/confirm-dialog/src/vaadin-confirm-dialog-overlay.js, packages/confirm-dialog/src/vaadin-confirm-dialog.js, packages/overlay/src/vaadin-overlay.d.ts, packages/overlay/src/vaadin-overlay.js, packages/overlay/test/overlay.test.js
This PR adds another event to `vaadin-overlay` so now it looks as follows:
- `vaadin-overlay-close` - fired when the overlay is about to close, can be canceled
- `vaadin-overlay-closing` - fired when closing started, before the animation runs
- `vaadin-overlay-closed` - fired after the overlay closing has completed (NEW)
=> feat: dispatch an event after overlay closing completed

packages/combo-box/src/vaadin-combo-box-overlay.js, packages/overlay/src/vaadin-overlay.d.ts, packages/overlay/src/vaadin-overlay.js
Related to #5393 - this is an alternative approach to avoid overriding the event listener and to keep it private.
- Refactor / internal feature
=> refactor: add internal protected method for outside click

packages/combo-box/src/vaadin-combo-box-overlay-mixin.d.ts, packages/combo-box/src/vaadin-combo-box-overlay-mixin.js, packages/combo-box/src/vaadin-combo-box-overlay.d.ts, packages/combo-box/src/vaadin-combo-box-overlay.js, packages/combo-box/theme/lumo/vaadin-combo-box-light.js, packages/combo-box/theme/lumo/vaadin-combo-box-overlay-styles.js, packages/combo-box/theme/lumo/vaadin-combo-box.js, packages/combo-box/theme/material/vaadin-combo-box-light.js, packages/combo-box/theme/material/vaadin-combo-box-overlay-styles.js, packages/combo-box/theme/material/vaadin-combo-box.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-overlay.d.ts, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-overlay.js, packages/multi-select-combo-box/theme/lumo/vaadin-multi-select-combo-box-styles.js, packages/multi-select-combo-box/theme/lumo/vaadin-multi-select-combo-box.js, packages/multi-select-combo-box/theme/material/vaadin-multi-select-combo-box-styles.js, packages/multi-select-combo-box/theme/material/vaadin-multi-select-combo-box.js, packages/time-picker/src/vaadin-time-picker-overlay.d.ts, packages/time-picker/src/vaadin-time-picker-overlay.js, packages/time-picker/theme/lumo/vaadin-time-picker-styles.js, packages/time-picker/theme/lumo/vaadin-time-picker.js, packages/time-picker/theme/material/vaadin-time-picker-styles.js, packages/time-picker/theme/material/vaadin-time-picker.js
Related to #5358
Same as #5391 but for the following components:
- `vaadin-combo-box-overlay`
- `vaadin-time-picker-overlay`
- `vaadin-multi-select-combo-box-overlay`
This PR decouples `TimePickerOverlay` and `MultiSelectComboBoxOverlay` by making them use shared mixin.
Also, theme files have been updated to export `css` tagged literals that are used by all of these components.
=> refactor!: extract shared combo-box overlay logic to mixin

packages/avatar-group/src/vaadin-avatar-group.js, packages/item/src/vaadin-item.js, packages/item/test/dom/__snapshots__/item.test.snap.js, packages/item/test/dom/item.test.js, packages/list-box/src/vaadin-list-box.js, packages/list-box/src/vaadin-multi-select-list-mixin.js, packages/list-box/test/dom/__snapshots__/list-box.test.snap.js, packages/list-box/test/dom/list-box.test.js, packages/list-box/test/list-box.test.js, packages/list-box/test/multi-select-list-mixin.test.js, packages/select/src/vaadin-select.js, packages/select/test/dom/__snapshots__/select.test.snap.js
Fixes #154
Fixes #5378
1. Changed the default `role` attribute for `vaadin-list-box` element from `list` to `listbox`;
2. Updated the `vaadin-item` to set `role="option"` instead of expecting the list-box to set it;
3. Added missing logic to toggle `aria-multiselectable` attribute to `MultiSelectListMixin`;
4. Updated `vaadin-avatar-group` and `vaadin-select` that use list-box and item accordingly;
5. Fixed `vaadin-select` to remove `role` attribute and `aria-selected` from the cloned item;
6. Added missing snapshot tests for the item and list-box, removed some existing unit tests.
Two announcements: "not selected" for the item and "selected" for the list-box:
New behavior (after) - didn't check the old one:
Nnew behavior (after) - didn't check the old one:
=> fix!: set correct role attribute on the list-box and item

packages/grid/test/helpers.js, packages/grid/test/scrolling-mode.test.js
Remove the manual invocation of `_afterScroll` from the `flushGrid` test helper function.
The helper should only flush active debouncers and observers. Forcing an `_afterScroll` when a "scroll" event may not have taken place could even lead to false positives in the tests.
=> test: remove flushGrid manual afterScroll invocation

packages/grid/src/vaadin-grid-scroll-mixin.js
Move the expensive `overflow` attribute calculation inside `_updateOverflow` to only be executed once the debouncer actually flushes.
On the `grid-performance.html` test page init, this reduced the number of times the calculation was executed from 8 to 1.
Refactor / Performance enhancement
=> refactor: calculate grid overflow in debouncer callback

packages/combo-box/src/vaadin-combo-box-scroller.js, packages/combo-box/test/aria.test.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-scroller.js, packages/time-picker/test/aria.test.js
Fixes #720
This PR fixes an issue found by @vursen while looking into the `vaadin-list-box` fix for `aria-selected` state.
For some historical reasons, we originally tried to announce focused item change by updating this attribute.
At least in VoiceOver this causes duplicate announcements: both the input text and item are announced.
Now when the `<input>` element is placed in light DOM and linked with the overlay, let's fix this logic.
- Bugfix
Both selected and not selected states are announced 🎉 
Note, VoiceOver + Safari has known issues that don't seem to be affected by this PR: #2748
Selected item is not announced. This problem also exists on master, I think it's because of focus not moving to the item.
This seems to be the same as #163 - we can't really do anything about it, without …
=> fix: set aria-selected on selected item, not the focused one

packages/avatar-group/src/vaadin-avatar-group-menu-item.d.ts, packages/avatar-group/src/vaadin-avatar-group-menu-item.js, packages/avatar-group/src/vaadin-avatar-group-menu.d.ts, packages/avatar-group/src/vaadin-avatar-group-menu.js, packages/avatar-group/src/vaadin-avatar-group.d.ts, packages/avatar-group/src/vaadin-avatar-group.js, packages/avatar-group/test/avatar-group.test.js, packages/avatar-group/test/dom/__snapshots__/avatar-group.test.snap.js, packages/avatar-group/theme/lumo/vaadin-avatar-group-styles.js, packages/avatar-group/theme/lumo/vaadin-avatar-group.js, packages/avatar-group/theme/material/vaadin-avatar-group-styles.js, packages/avatar-group/theme/material/vaadin-avatar-group.js
Part of #5358
This change is basically same as the following PRs, but for `vaadin-avatar-group`:
- https://github.com/vaadin/web-components/pull/5339
- https://github.com/vaadin/web-components/pull/5354
Apart from not using list-box and item extensions, the main change is related to ARIA roles.
The `role="listbox"` was chosen just as a result of copying the code from `vaadin-select`.
However, actually the [Menu Button](https://www.w3.org/WAI/ARIA/apg/patterns/menubutton/) pattern is a better fit in this case - see [example](https://www.w3.org/WAI/ARIA/apg/example-index/menu-button/menu-button-actions.html).
I thought now would be the perfect time to make this relatively small behavior altering change.
- `<vaaadin-avatar-group-list-box role="listbox">`
- `<vaadin-item …
=> refactor!: update avatar-group to use custom menu and item

packages/context-menu/src/vaadin-context-menu-item.d.ts, packages/context-menu/src/vaadin-context-menu-list-box.d.ts
Somehow I missed to export new classes from TS definitions (so that they can be used by user's TS code).
Other components like `vaadin-select-item` have these. Let's also add them to context-menu elements.
=> docs: export item and list-box types for context-menu

packages/menu-bar/src/vaadin-menu-bar-item.d.ts, packages/menu-bar/src/vaadin-menu-bar-list-box.d.ts, packages/menu-bar/test/typings/menu-bar.types.ts
As we now provide TS definitions for item / list-box elements in other components, let's add them here also.
=> docs: add missing menu-bar item and list-box typings

packages/context-menu/src/vaadin-context-menu-overlay.d.ts, packages/menu-bar/src/vaadin-menu-bar-overlay.d.ts, packages/select/src/vaadin-select-item.d.ts, packages/select/src/vaadin-select-list-box.d.ts
These JSDoc annotations don't make any sense in `.d.ts` files and they seem to be a copy-paste from `.js` files.
We still need them in actual JS classes though, in order to hide corresponding elements from the API docs.
=> docs: remove not needed JSDoc annotations from types

packages/grid-pro/test/typings/grid-pro.types.ts, packages/grid/src/vaadin-grid-active-item-mixin.d.ts, packages/grid/src/vaadin-grid.d.ts, packages/grid/test/typings/grid.types.ts
Fixes #5387
Updated `activeItem` typings to support both `null` and `undefined` as our components set both:
https://github.com/vaadin/web-components/blob/7420679a2609ab464d2ea42300aa98846276cfea/packages/crud/src/vaadin-crud.js#L1136
https://github.com/vaadin/web-components/blob/7420679a2609ab464d2ea42300aa98846276cfea/packages/grid/src/vaadin-grid-active-item-mixin.js#L42
Also, updated the type for `active-item-changed` event detail object accordingly, as reported in the issue.
- Bugfix
=> fix: allow undefined in activeItem and corresponding event [skip ci]

packages/grid/src/vaadin-grid-column-reordering-mixin.js, packages/grid/test/column-reordering.test.js
Stop the active column reordering process if a "contextmenu" event occurs on a desktop device.
Fixes https://github.com/vaadin/flow-components/issues/4623
Bugfix
=> fix: stop grid column reordering on contextmenu event

packages/grid/test/helpers.js, packages/grid/test/scroll-to-index.test.js
Was [working on removing](https://github.com/vaadin/web-components/commit/819ce51355a5e1b041460066c448441312699317) the `"vaadin-grid-appear"` animation and came up with a case where it's actually necessary. Added the missing test case so the animation doesn't get accidentally removed.
Test
=> test: add a test for scrolling to grid index before unhiding

packages/combo-box/src/vaadin-combo-box-overlay.js, packages/combo-box/test/overlay-position.test.js, packages/overlay/src/vaadin-overlay-position-mixin.d.ts, packages/overlay/src/vaadin-overlay-position-mixin.js, packages/overlay/test/position-mixin.test.js, packages/overlay/test/typings/overlay.types.ts
Since the `<combo-box>` overlay has no intrinsic height, `PositionMixin` had it always aligned below the input field on open.
A new property was added for the `PositionMixin` to cover this case (defining required vertical space for overlays that have no intrinsic height of their own). A default value for the property was assigned to the `<vaadin-combo-box-overlay>` to fix the issue.
Fixes https://github.com/vaadin/flow-components/issues/2820
Bugfix
=> fix: add required vertical space for combo-box overlay

.eslintrc.json, packages/component-base/src/async.d.ts, packages/component-base/src/polylit-mixin.d.ts, packages/polymer-legacy-adapter/test/fixtures/mock-component.js, packages/polymer-legacy-adapter/test/fixtures/mock-list.js
The PR enables and fixes the following rules:
Part of https://github.com/vaadin/eslint-config-vaadin/issues/35
=> refactor: enable more ESLint rules, fix related errors

packages/button/theme/lumo/vaadin-button-styles.js
Using utf-8 characters provide no benefit but can break file serving when you have encoding issues in your setup
=> chore: Avoid utf-8 characters in code

packages/grid/test/light-dom-observing.test.js
Remove the use of `<template>` in the `<vaadin-grid>` `light-dom-observing.test.js` tests.
Additionally:
- refactored the old test file to be less unreadable
- removed the tests that were basically testing Polymer `<dom-repeat>` (there are existing cases that test modifications in the column set)
- Tests
=> test: update grid light-dom-observing tests to not use templates

packages/tabs/test/visual/lumo/tabs.test.js, packages/tabs/test/visual/material/tabs.test.js, packages/tabs/test/visual/not-animated-styles.js, packages/tabsheet/test/visual/lumo/tabsheet.test.js, packages/tabsheet/test/visual/material/tabsheet.test.js
Some visual tests for `vaadin-tabs` started to fail after recent upgrade to Chrome 108, which apparently loads faster:
```
packages/tabs/test/visual/lumo/tabs.test.js:
❌ tabs > scroll > horizontal > rtl > selected
Error: Visual diff failed. New screenshot is 0.09% different.
See diff for details: /home/runner/work/web-components/web-components/packages/tabs/test/visual/lumo/screenshots/tabs/failed/rtl-horizontal-scroll-diff.png
at async o.<anonymous> (packages/tabs/test/visual/lumo/tabs.test.js:170:15)
❌ tabs > scroll > vertical > ltr > selected
Error: Visual diff failed. New screenshot is 0.17% different.
See diff for details: /home/runner/work/web-components/web-components/packages/tabs/test/visual/lumo/screenshots/tabs/failed/ltr-vertical-scroll-diff.png
at async o.<anonymous> …
```
=> test: disable animations in tabs and tabsheet visual tests

packages/accordion/src/vaadin-accordion-heading.d.ts, packages/accordion/src/vaadin-accordion-heading.js, packages/accordion/src/vaadin-accordion.d.ts, packages/accordion/src/vaadin-accordion.js, packages/charts/src/vaadin-chart-series.d.ts, packages/charts/src/vaadin-chart-series.js, packages/checkbox-group/src/vaadin-checkbox-group.d.ts, packages/checkbox-group/src/vaadin-checkbox-group.js, packages/combo-box/src/vaadin-combo-box-mixin.d.ts, packages/component-base/src/focus-mixin.js, packages/component-base/src/focus-utils.js, packages/context-menu/src/vaadin-context-menu.d.ts, packages/context-menu/src/vaadin-context-menu.js, packages/form-layout/src/vaadin-form-layout.js, packages/grid/src/vaadin-grid-column-group.js, packages/grid/src/vaadin-grid-column-reordering-mixin.js, packages/grid/src/vaadin-grid-data-provider-mixin.js, packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js, packages/grid/src/vaadin-grid-row-details-mixin.js, packages/grid/src/vaadin-grid.d.ts, packages/grid/src/vaadin-grid.js, packages/overlay/src/vaadin-overlay.d.ts, packages/overlay/src/vaadin-overlay.js, packages/select/src/vaadin-select.d.ts, packages/select/src/vaadin-select.js, packages/vaadin-themable-mixin/vaadin-theme-property-mixin.d.ts, packages/vaadin-themable-mixin/vaadin-theme-property-mixin.js, wtr-utils.js
Related to https://github.com/vaadin/web-components/pull/5439#issuecomment-1416832060
Note: this PR only changes JS comments, there are still other UTF-8 entities in CSS to handle separately.
=> docs: remove non-ASCII characters from JSDoc and comments

packages/tabs/src/vaadin-tabs.js
Part of #5453
Updated `vaadin-tabs` internal parts to use unicode entities for these icons:
- Refactor
Can be tested with the following HTML in the dev page:
```html
import '@vaadin/tabs/src/vaadin-tabs.js';
</script>
<vaadin-tabs style="max-width: 100%; width: 200px">
<vaadin-tab>Analytics</vaadin-tab>
<vaadin-tab>Customers</vaadin-tab>
<vaadin-tab>Dashboards</vaadin-tab>
<vaadin-tab>Documents</vaadin-tab>
<vaadin-tab>Orders</vaadin-tab>
</vaadin-tabs>
```
=> refactor: use Unicode entities for forward and back buttons

packages/menu-bar/src/vaadin-menu-bar-mixin.js
Part of #5453
The `vaadin-menu-bar` uses [middle dot](https://www.compart.com/en/unicode/U+00B7) to render "ellipsis". Updated to use HTML entity for it.
- Refactor
=> refactor: use HTML entity for the menu-bar overflow button

packages/map/src/vaadin-map.js
Part of #5453
The following icons are used:
- https://www.compart.com/en/unicode/U+2013
- https://www.compart.com/en/unicode/U+25B8
- https://www.compart.com/en/unicode/U+2139
- https://www.compart.com/en/unicode/U+2191
- https://www.compart.com/en/unicode/U+2922
- https://www.compart.com/en/unicode/U+00D7
- https://www.compart.com/en/unicode/U+25BE
- https://www.compart.com/en/unicode/U+25B4
- Refactor
=> refactor: update map styles to use Unicode entities for icons

packages/component-base/src/list-mixin.d.ts, packages/component-base/src/list-mixin.js, packages/component-base/test/list-mixin.test.js
Related to #5301
Made some tweaks to the mixin in addition to tests: especially, declared `disabled` in `static get properties()`.
This is needed to ensure `PolylitMixin` handles this property (apparently, Polymer did it automatically).
Note: there is no need to use `DisabledMixin` because we don't set `aria-disabled` on the `listbox` / `tabs`.
- Refactor
=> refactor: add LitElement support and tests to ListMixin

packages/grid/test/column-groups.test.js, packages/grid/test/helpers.js, packages/grid/test/light-dom-observing.test.js
Remove the use of `<template>` in the `<vaadin-grid>` `column-groups.test.js` tests.
Tests
=> test: update grid column-groups tests to not use templates

packages/avatar/src/vaadin-avatar.js
Part of #5453
Changed to use the [original approach](https://github.com/vaadin/vaadin-avatar/blob/63a6c7855be3c1f79ec9a1552577c1303829d46f/src/vaadin-avatar.html#L73) that was there before Polymer 3 conversion.
- Refactor
=> refactor: replace user icon with corresponding Unicode entity

packages/charts/src/vaadin-chart.d.ts, packages/charts/src/vaadin-chart.js
Part of #5453
We shouldn't have these code examples in API docs: instead, the website has to be updated.
For now, let's just remove them, as there are links pointing to Highcharts API docs anyway.
=> docs: remove RTL code example with arabic characters from JSDoc

packages/grid/test/selection.test.js
Remove the use of `<template>` in the `<vaadin-grid>` `selection.test.js` tests.
Tests
=> test: update selection tests to not use templates

wtr-utils.js
Update the `web-test-runner` change detection script to use `24.0` as a base branch for Vaadin 24.0
=> chore: update change detection branch to 24.0

packages/dialog/test/dialog.test.js, packages/dialog/test/draggable-resizable.test.js
Remove the use of `<template>` in the `<vaadin-dialog>` tests.
Tests
=> test: update dialog tests to not use templates

packages/component-base/test/resize-mixin.test.js
Cherry-pick of #5347 to `23.3` branch - let's see if tests still fail in Chrome with this change.
- Tests
=> test: wait for animation frame to fix flaky ResizeMixin tests (#5347) (CP: 23.3)

packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/test/keyboard.test.js
Fixes propagation of enter keydown events after filtered items have been reset.
Fixes https://github.com/vaadin/flow-components/issues/3727
- Bugfix
=> fix: allow propagating enter key event after selecting value

packages/component-base/test/resize-mixin.test.js
Cherry-pick of #5347 to `23.2` branch - let's see if tests still fail in Chrome with this change.
- Tests
=> test: wait for animation frame to fix flaky ResizeMixin tests (#5347) (CP: 23.2)

packages/notification/test/animation.test.js, packages/notification/test/multiple.test.js, packages/notification/test/notification.test.js, packages/notification/test/renderer.test.js
Remove the use of `<template>` in the `<vaadin-notification>` tests.
Tests
=> test: update notification tests to not use templates

integration/tests/dialog-template.test.js, integration/tests/grid-pro-edit-column-template.test.js, integration/tests/grid-templates.test.js, integration/tests/notification-template.test.js, integration/tests/virtual-list-template.test.js, packages/dialog/package.json, packages/dialog/test/renderer.test.js, packages/grid-pro/package.json, packages/grid/package.json, packages/grid/test/visual/lumo/grid.test.js, packages/grid/test/visual/material/grid.test.js, packages/notification/package.json, packages/virtual-list/package.json
- Move the remaining `<template>` API tests from the component packages to `integration`.
- Remove the dependency on `polymer-legacy-adapter` from the component packages
Tests
=> test: move template tests to integration

packages/field-base/src/input-control-mixin.js
The current `InputFieldMixin.__clear()` method is easy to confuse with `InputMixin.clear()` and vice versa. The difference is that the `__clear()` method calls `clear()` but also dispatches input and change events. I believe it is better to name it something like `_onClearAction()` and make it protected so we can re-use it later in other components as well.
=> refactor: rename __clear() to _onClearAction()

packages/context-menu/src/vaadin-contextmenu-items-mixin.js, packages/context-menu/test/dom/__snapshots__/context-menu.test.snap.js, packages/context-menu/test/helpers.js
As we no longer use extensions of `vaadin-item` in V24, this logic has to be adjusted accordingly.
Also, setting `aria-expanded` attribute only makes sense for elements with `role="menuitem"`.
- Refactor
=> fix: do not check for extending Item when setting ARIA attribute

packages/combo-box/src/vaadin-combo-box.d.ts, packages/combo-box/test/typings/combo-box.types.ts, packages/date-picker/test/typings/date-picker.types.ts, packages/field-base/src/clear-button-mixin.d.ts, packages/field-base/src/clear-button-mixin.js, packages/field-base/src/input-control-mixin.d.ts, packages/field-base/src/input-control-mixin.js, packages/field-base/src/input-field-mixin.d.ts, packages/field-base/test/clear-button-mixin.test.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.d.ts, packages/multi-select-combo-box/test/typings/multi-select-combo-box.types.ts, packages/time-picker/test/typings/time-picker.types.ts
The PR extracts the clear button logic from `InputControlMixin` into a `ClearButtonMixin` for the sake of separation of concerns.
> **Note**
> It seems we had such a mixin in the past but we apparently removed it due to a Firefox memory issue. Let's hope we don't run into it again.
=> refactor: extract clear button related logic to ClearButtonMixin

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js
The `clear()` method override is unnecessary. The original `InputMixin.clear()` method already clears the input element's value. It is apparently a leftover from some early refactorings.
=> refactor: remove a unnecessary clear() method override

packages/text-field/package.json, packages/text-field/src/vaadin-text-field-mixin.d.ts, packages/text-field/src/vaadin-text-field-mixin.js, packages/text-field/src/vaadin-text-field.d.ts, packages/text-field/src/vaadin-text-field.js
1. Extracted logic into `TextFieldMixin` (we actually had such a mixin in Vaadin 14, but changed it in Vaadin 22),
2. Removed usage of `PatternMixin` and inlined its logic to keep all the constraints related properties together.
- Refactor
=> refactor: extract text-field logic to reusable TextFieldMixin

packages/text-area/package.json, packages/text-area/src/vaadin-text-area-mixin.d.ts, packages/text-area/src/vaadin-text-area-mixin.js, packages/text-area/src/vaadin-text-area.d.ts, packages/text-area/src/vaadin-text-area.js
1. Extracted logic into `TexAreaMixin` (we actually had a similar mixin in Vaadin 14, but changed it in Vaadin 22),
2. Removed usage of `PatternMixin` and inlined its logic to keep all the constraints related properties together.
- Refactor
=> refactor: extract text-area logic to reusable TextAreaMixin

packages/text-area/package.json, packages/text-area/src/vaadin-text-area-styles.d.ts, packages/text-area/src/vaadin-text-area-styles.js, packages/text-area/src/vaadin-text-area.js
Moved styles from the component's template to `css` literal that could be also used by the Lit version.
- Refactor
=> refactor: extract text-area styles to reusable css literal

packages/number-field/package.json, packages/number-field/src/vaadin-number-field-mixin.d.ts, packages/number-field/src/vaadin-number-field-mixin.js, packages/number-field/src/vaadin-number-field.d.ts, packages/number-field/src/vaadin-number-field.js
1. Extracted logic into `TexAreaMixin` (we actually had a similar mixin in Vaadin 14, but changed it in Vaadin 22),
2. Renamed some listeners / methods that are used in the component template and marked them as protected.
- Refactor
=> refactor: extract number-field logic to reusable NumberFieldMixin

packages/text-field/test/text-field.test.js, packages/text-field/test/validation.test.js
1. Added `nextRender()` after calling `fixtureSync()` - this makes tests easier to debug as the element is rendered,
2. Added `nextFrame()` after setting properties - this makes our unit tests forwards-compatible with `LitElement`.
- Tests
=> test: update text-field tests to allow async property updates

packages/text-area/test/text-area.test.js, packages/text-area/test/validation.test.js
1. Added `nextRender()` after calling `fixtureSync()` - this makes tests easier to debug as the element is rendered,
2. Added `nextFrame()` after setting properties - this makes our unit tests forwards-compatible with `LitElement`.
- Tests
=> test: update text-area tests to allow async property updates

packages/number-field/package.json, packages/number-field/src/vaadin-number-field-styles.d.ts, packages/number-field/src/vaadin-number-field-styles.js, packages/number-field/src/vaadin-number-field.js
Moved styles from the component's template to `css` literal that could be also used by the Lit version.
- Refactor
=> refactor: extract number-field styles to reusable css literal

packages/number-field/test/number-field.test.js, packages/number-field/test/validation.test.js
1. Added `nextRender()` after calling `fixtureSync()` - this makes tests easier to debug as the element is rendered,
2. Added `nextFrame()` after setting properties - this makes our unit tests forwards-compatible with `LitElement`.
- Tests
=> test: update number-field tests to allow async updates

packages/email-field/test/email-field.test.js
1. Added `nextRender()` after calling `fixtureSync()` - this makes tests easier to debug as the element is rendered,
2. Added `nextFrame()` after setting properties - this makes our unit tests forwards-compatible with `LitElement`.
- Tests
=> test: update email-field tests to allow async updates

packages/text-field/package.json, packages/text-field/src/vaadin-lit-text-field.d.ts, packages/text-field/src/vaadin-lit-text-field.js, packages/text-field/test/text-field-lit.test.js, packages/text-field/test/text-field-polymer.test.js, packages/text-field/test/text-field.common.js, packages/text-field/test/validation-lit.test.js, packages/text-field/test/validation-polymer.test.js, packages/text-field/test/validation.common.js
1. Created a version of `vaadin-text-field` web component using `LitElement` base class,
- Experiment
=> experiment: add LitElement based version of vaadin-text-field

packages/text-area/package.json, packages/text-area/src/vaadin-lit-text-area.d.ts, packages/text-area/src/vaadin-lit-text-area.js, packages/text-area/test/text-area-lit.test.js, packages/text-area/test/text-area-polymer.test.js, packages/text-area/test/text-area.common.js, packages/text-area/test/validation-lit.test.js, packages/text-area/test/validation-polymer.test.js, packages/text-area/test/validation.common.js
1. Created a version of `vaadin-text-area` web component using `LitElement` base class,
- Experiment
=> experiment: add LitElement based version of vaadin-text-area

packages/number-field/package.json, packages/number-field/src/vaadin-lit-number-field.d.ts, packages/number-field/src/vaadin-lit-number-field.js, packages/number-field/test/number-field-lit.test.js, packages/number-field/test/number-field-polymer.test.js, packages/number-field/test/number-field.common.js, packages/number-field/test/validation-lit.test.js, packages/number-field/test/validation-polymer.test.js, packages/number-field/test/validation.common.js
1. Created a version of `vaadin-number-field` web component using `LitElement` base class,
- Experiment
=> experiment: add Lit based version of vaadin-number-field

packages/button/package.json, packages/button/src/vaadin-button-base.d.ts, packages/button/src/vaadin-button-base.js, packages/button/src/vaadin-button.js, packages/crud/src/vaadin-crud-edit.js
Refactored `html` and `css` literals to be placed in `vaadin-button-base.js` as prototyped in #5301 
- Refactor
=> refactor: extract button template and reusable css literal

packages/email-field/package.json, packages/email-field/src/vaadin-lit-email-field.d.ts, packages/email-field/src/vaadin-lit-email-field.js, packages/email-field/test/email-field-lit.test.js, packages/email-field/test/email-field-polymer.test.js, packages/email-field/test/email-field.common.js
1. Created a version of `vaadin-email-field` web component using `LitElement` base class,
- Experiment
=> experiment: add Lit based version of vaadin-email-field

packages/button/package.json, packages/button/src/vaadin-button-mixin.js, packages/button/src/vaadin-lit-button.d.ts, packages/button/src/vaadin-lit-button.js, packages/button/test/button-lit.test.js, packages/button/test/button-polymer.test.js, packages/button/test/button.common.js
1. Created a version of `vaadin-buttond` web component using `LitElement` base class,
- Experiment
=> experiment: add Lit based version of vaadin-button

scripts/generateReleaseNotes.js
This change is needed to list our recently merged Lit experiments as a separate category in the release notes.
- `number-field`
- [⧉](https://github.com/vaadin/web-components/commit/2bfe689) Add Lit based version of vaadin-number-field ([#5541](https://github.com/vaadin/web-components/pull/5541))
- `text-area`
- [⧉](https://github.com/vaadin/web-components/commit/dc920c1) Add Lit based version of vaadin-text-area ([#5539](https://github.com/vaadin/web-components/pull/5539))
- `text-field`
- [⧉](https://github.com/vaadin/web-components/commit/f8e274a) Add Lit based version of vaadin-text-field ([#5538](https://github.com/vaadin/web-components/pull/5538))
=> chore: update release notes script to list experiments

packages/progress-bar/package.json, packages/progress-bar/src/vaadin-progress-bar-styles.d.ts, packages/progress-bar/src/vaadin-progress-bar-styles.js, packages/progress-bar/src/vaadin-progress-bar.js
Same as #5544 but for `vaadin-progress-bar`.
- Refactor
=> refactor: extract progress-bar styles to reusable css literal

packages/progress-bar/package.json, packages/progress-bar/src/vaadin-lit-progress-bar.d.ts, packages/progress-bar/src/vaadin-lit-progress-bar.js, packages/progress-bar/test/progress-bar-lit.test.js, packages/progress-bar/test/progress-bar-polymer.test.js, packages/progress-bar/test/progress-bar.common.js
Depends on #5557
1. Created a version of `vaadin-progress-bar` web component using `LitElement` base class,
- Experiment
=> experiment: add Lit based version of vaadin-progress-bar

packages/checkbox/package.json, packages/checkbox/src/vaadin-checkbox-styles.d.ts, packages/checkbox/src/vaadin-checkbox-styles.js, packages/checkbox/src/vaadin-checkbox.js
Same as #5557 but for `vaadin-checkbox`.
- Refactor
=> refactor: extract checkbox styles to reusable css literal

packages/checkbox/src/vaadin-checkbox.d.ts, packages/checkbox/src/vaadin-checkbox.js
Rephrased confusing note regarding `::part(checkbox)`. Also, simplified the state attributes table.
=> docs: improve JSDoc for checkbox stylable parts and states

packages/checkbox/package.json, packages/checkbox/src/vaadin-lit-checkbox.d.ts, packages/checkbox/src/vaadin-lit-checkbox.js, packages/checkbox/test/checkbox-lit.test.js, packages/checkbox/test/checkbox-polymer.test.js, packages/checkbox/test/checkbox.common.js
Depends on #5557
1. Created a version of `vaadin-checkbox` web component using `LitElement` base class,
- Experiment
=> experiment: add Lit based version of vaadin-checkbox

packages/context-menu/src/vaadin-context-menu.d.ts, packages/context-menu/src/vaadin-context-menu.js, packages/context-menu/src/vaadin-contextmenu-items-mixin.js, packages/menu-bar/src/vaadin-menu-bar-submenu.js
Follow-up to #5570. 
This PR adds `_modeless` property to avoid relying on sub-menu Shadow DOM being rendered synchronously.
- Refactor
=> refactor: simplify logic, set modeless state using property

packages/app-layout/src/vaadin-drawer-toggle.js
Fixing a regression found after restructuring `vaadin-button` to support Lit version. Here's a similar fix in `vaadin-crud`:
https://github.com/vaadin/web-components/blob/53a3bec2c5326ef3b6054cbd6cf2ec728e5db58c/packages/crud/src/vaadin-crud-edit.js#L15-L27
- Bugfix
=> fix: use registerStyles for vaadin-drawer-toggle core styles

packages/combo-box/src/vaadin-combo-box-light.js, packages/combo-box/src/vaadin-combo-box-mixin.d.ts, packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/test/selecting-items.test.js, packages/date-picker/src/vaadin-date-picker-light.js, packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/test/validation.test.js, packages/field-base/src/input-mixin.d.ts, packages/field-base/src/input-mixin.js
The PR gathers input element value setters and getters from the components and moves them to `InputMixin`. Collecting them all in one single place will make it possible to fix updating `_hasInputValue` for all the components at once afterward.
Part of #5410
=> refactor: move input value getters and setters to InputMixin

packages/menu-bar/package.json, packages/multi-select-combo-box/package.json, packages/text-field/package.json, packages/time-picker/package.json, packages/upload/package.json
Discovered a few missing direct dependencies when updating `pnpm` experimental branch:
```
Error while transforming packages/time-picker/theme/lumo/vaadin-time-picker.js: Could not resolve import "@vaadin/overlay/theme/lumo/vaadin-overlay.js".
5 |  */
6 | import '@vaadin/input-container/theme/lumo/vaadin-input-container.js';
>  7 | import '@vaadin/overlay/theme/lumo/vaadin-overlay.js';
|        ^
8 | import './vaadin-time-picker-styles.js';
9 | import '../../src/vaadin-time-picker.js';
10 |
Error while transforming packages/text-field/src/vaadin-lit-text-field.js: Could not resolve import "lit".
5 |  */
6 | import '@vaadin/input-container/src/vaadin-input-container.js';
>  7 | import { css, html, LitElement } from 'lit';
|                                       ^
8 | import { ElementMixin …
```
=> fix: add missing direct npm dependencies to package.json

packages/menu-bar/package.json, packages/multi-select-combo-box/package.json, packages/text-field/package.json, packages/time-picker/package.json, packages/upload/package.json
Manual cherry-pick of #5594 to `24.0` branch to make web components `pnpm` compatible.
- Bugfix
=> fix: add missing direct npm dependencies to package.json (CP: 24.0)

packages/menu-bar/package.json, packages/multi-select-combo-box/package.json, packages/time-picker/package.json
Manual cherry-pick of #5596 to `24.0` with adding remaining dependencies on `@vaadin/item` and `@vaadin/list-box`.
- Cherry-pick
=> fix: add missing direct npm dependencies to package.json (#5596) (CP: 24.0)

packages/date-time-picker/theme/lumo/vaadin-date-time-picker-styles.js, packages/input-container/src/vaadin-input-container.js, packages/input-container/theme/lumo/vaadin-input-container-styles.js, packages/vaadin-lumo-styles/style.js
As discussed, let's rename the CSS property to align with the part name, which is `::part(input-field)`.
=> refactor!: rename CSS property for input-field border radius

packages/field-base/src/input-mixin.js, packages/field-base/test/input-mixin.test.js
The PR resets `_hasInputValue` to false on programmatic value clear so that Flow won't treat the empty value as bad input. It also mentions in the JSDoc that `_hasInputValue` only indicates true if the input has been entered by the *user*. Ideally, given the way the property works, it should be renamed to `_hasUserInput` but we decided not to change that in the scope of this issue.
> **Note**
>  There will be more PRs like this one. They will cover other cases where the input value can be changed programmatically.
Part of https://github.com/vaadin/web-components/issues/5410
=> fix: reset _hasInputValue on programmatic value clear

DEVELOPMENT.md
Incorrect command to run snapshot tests in Development.MD
=> chore: fix the command used to run snapshot tests

integration/tests/dialog-date-picker.test.js, packages/date-picker/test/basic.test.js, packages/date-picker/test/custom-input.test.js, packages/date-picker/test/dropdown.test.js, packages/date-picker/test/fullscreen.test.js, packages/date-picker/test/helpers.js, packages/date-picker/test/keyboard-input.test.js, packages/date-picker/test/keyboard-navigation.test.js, packages/date-picker/test/theme-propagation.test.js, packages/date-picker/test/wai-aria.test.js
Renames `datepicker` to `datePicker` in tests for the sake of consistency.
=> test: rename datepicker to datePicker

packages/grid/src/vaadin-grid-column-group.js, packages/grid/src/vaadin-grid-dynamic-columns-mixin.js, packages/grid/test/column-groups.test.js, packages/grid/test/helpers.js
Fixes https://github.com/vaadin/flow-components/issues/4565
This PR debounces the `_updateColumnTree` function that got called unnecessarily often when column groups were used.
The change has a 6% impact on the `rendertime` metric in the [Grid benchmark tests](https://bender.vaadin.com/buildConfiguration/Flow_Components_BenchmarkTests_Grid?mode=builds).
=> refactor: reduce grid updateColumnTree call count

packages/menu-bar/src/vaadin-menu-bar-buttons-mixin.js, packages/menu-bar/test/menu-bar.test.js
Manual cherry-pick of #5610 to `23.3` branch.
There was a conflict due to `vaadin-menu-bar-list-box` tag name and merging two mixins into a single one in 24.0.
- Cherry-pick
=> fix: reset item attributes when teleporting from the sub-menu (#5610) (CP: 23.3)

packages/a11y-base/src/aria-modal-controller.d.ts, packages/a11y-base/src/aria-modal-controller.js, packages/a11y-base/test/aria-modal-controller.test.js
This PR is a version of #5603 adding a new controller that extends `FocusTrapController`.
The name is inspired by [`@react-aria/aria-modal-polyfill`](https://github.com/adobe/react-spectrum/pull/709) and native [`<dialog>`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement).
=> feat: add AriaModalController to handle modal dialogs behavior

packages/date-time-picker/src/vaadin-date-time-picker.js, packages/date-time-picker/test/i18n.test.js
The related Flow component issue: [4667](https://github.com/vaadin/flow-components/issues/4667)
In v23.3, i18n can be incorrectly updated before the component is ready. This is due to `FlattenedNodesObserver` being flushed prematurely, and the listeners being invoked while the component is not ready. In v24, the slotted components are handled in a different way, therefore this behaviour is not observed. 
This PR moves the observer initialization logic to after when the date picker and time pickers are already set and the component is ready. This way, the initial i18n update will not override the correct i18n.
Related to https://github.com/vaadin/flow-components/pull/4706
=> fix: init the DOM observer in ready() instead of constructor()

packages/date-time-picker/test/i18n.test.js
Add the test from the [v23.3 PR](https://github.com/vaadin/web-components/pull/5604) to v24 as well.
See related [issue](https://github.com/vaadin/flow-components/pull/4706)
=> refactor: add i18n test from v23.3 fix to v24

packages/date-picker/test/basic.test.js, packages/date-picker/test/custom-input.test.js, packages/date-picker/test/dropdown.test.js, packages/date-picker/test/keyboard-input.test.js, packages/date-picker/test/validation.test.js, packages/date-picker/test/wai-aria.test.js
This PR aims to ensure that tests opening `vaadin-date-picker-overlay` wait for `vaadin-overlay-open` event.
It's actually a pre-requisite for #4314 as we need to ensure `hideOthers()` isn't called during fixture teardown.
- Tests
=> test: update date-picker unit tests to wait for overlay open

packages/a11y-base/src/aria-modal-controller.js, packages/a11y-base/test/aria-modal-controller.test.js
I missed to remove these leftovers from the original implementation before merging 😕 
- Refactor
=> refactor: remove unused imports from AriaModalController

packages/grid/src/vaadin-grid-styles.js, packages/grid/test/resizing.test.js
This change makes a `<vaadin-grid>` with `allRowsVisible` enabled to respect CSS `max-height`.
Fixes https://github.com/vaadin/web-components/issues/2150
https://user-images.githubusercontent.com/1222264/215733339-bded13bb-94ab-487c-9d1f-8a5c2eed83a1.mp4
Bugfix
=> fix: make grid with all rows visible respect max height

packages/time-picker/test/events.test.js, packages/time-picker/test/time-picker.test.js
Following up on https://github.com/vaadin/web-components/pull/5625#discussion_r1122183915, the PR moves the `change`  event tests to a separate `events.test.js` file.
=> test: move the change event tests to a separate file

packages/time-picker/src/vaadin-time-picker-combo-box.js, packages/time-picker/src/vaadin-time-picker.js, packages/time-picker/test/events.test.js
- Synchronized time-picker's `_hasInputValue` property with one of the internal combo-box. 
- Ensured the internal combo-box's `_hasInputValue` gets updated when the input element's value is changed programmatically.
Part of #5410
=> fix: update _hasInputValue on programmatic input change

packages/grid/src/vaadin-grid-drag-and-drop-mixin.js, packages/grid/src/vaadin-grid-helpers.js, packages/grid/src/vaadin-grid.js, packages/grid/test/drag-and-drop.test.js
When the user is dragging over a grid which is set in `between`, `on-top-or-between` or `on-top` drop mode, then the rows and cells `dragover` attribute is automatically set with an appropriate value (one of `above`, `on-top`, `below`). In addition the `part` attribute is enriched with an appropriate part (`dragover-on-top-row`, `dragover-above-row`, `dragover-below-row` etc.)
The problem before this fix was that as the user was dragging over the row, only the `dragover` attribute was updated correctly, but the `part` attribute was not properly cleared when the dragover value changed. So, for example,  when dragover changed from `above` to `below`, the row had both parts `dragover-above-row`, `dragover-below-row` and not only `dragover-below-row` part. 
The fix introduces another helper …
=> fix: clear dragover row and cell parts on dragover change

packages/grid/src/vaadin-grid-data-provider-mixin.js, packages/grid/test/data-provider.test.js
This change improves how a data provider callback is processed in `vaadin-grid-data-provider-mixin`. It makes sure that the cache gets fully updated with all synchronously available data before actually rendering the grid rows. The updated data provider causes significantly fewer row rendering cycles when hierarchical data is applied to the grid.
This will be followed by a related PR to `flow-component`.
=> refactor: avoid unnecessary render cycles in the data provider callback

packages/date-picker/src/vaadin-date-picker-mixin.js, packages/field-base/src/input-mixin.js
The PR documents and simplifies the `hasInputValue` workaround in `date-picker` that was introduced in #5625.
Part of #5410
=> refactor: simplify _hasInputValue workaround, improve JSDoc

packages/charts/src/helpers.js, packages/charts/test/private-api.test.js
The `inflateFunctions` function currently does not handle functions in arrays, which causes the export buttons to break. 
This is a regression introduced by a previous [fix](https://github.com/vaadin/web-components/pull/5080). This PR updates the logic so that the objects inside arrays are also fed into the function again. 
Fixes #[4696](https://github.com/vaadin/flow-components/issues/4696)
=> fix: inflate functions in arrays

packages/combo-box/src/vaadin-combo-box-light.js, packages/combo-box/src/vaadin-combo-box-mixin.d.ts, packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/test/selecting-items.test.js, packages/date-picker/src/vaadin-date-picker-light.js, packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/test/validation.test.js, packages/field-base/src/input-mixin.d.ts, packages/field-base/src/input-mixin.js
The PR cherry-picks the following improvement to `24.0`:
- https://github.com/vaadin/web-components/pull/5586
Part of https://github.com/vaadin/web-components/issues/5410
=> refactor: move input value getters and setters to InputMixin (#5586) (CP: 24.0)

packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/test/events.test.js, packages/field-base/src/input-mixin.js
The PR cherry-picks the following fixes to `24.0`:
- #5625
- #5645
Part of https://github.com/vaadin/web-components/issues/5410
=> fix: reset _hasInputValue on programmatic input change (#5625) (CP: 24.0)

packages/time-picker/src/vaadin-time-picker-combo-box.js, packages/time-picker/src/vaadin-time-picker.js, packages/time-picker/test/events.test.js
The PR cherry-picks the following fixes to `24.0`:
- #5638
Part of https://github.com/vaadin/web-components/issues/5410
=> fix: update _hasInputValue on programmatic input change (#5638) (CP: 24.0)

packages/upload/src/vaadin-upload.js, packages/upload/test/adding-files.test.js
Currently, the extensions that contain multiple dots (like .tar.gz) are rejected by `Upload` even if the extension is provided through they should be accepted. This PR changes the way the matchers work. The current approach is extracting an extension from a file name and searching for exact matches. With the changes, it will be checked whether the file name ends with one of the provided extensions.
Fixes #[4777](https://github.com/vaadin/flow-components/issues/4777)
=> fix: make extension patterns match the end of the file name

packages/component-base/src/virtualizer-iron-list-adapter.js, packages/component-base/test/virtualizer.test.js
Changing the virtualizer's `size` should never cause element updates if the size change doesn't affect any visible elements. There's actually a [test case](https://github.com/vaadin/web-components/blob/3224d4e1760babd894391ce6ce7e6f08ed467669/packages/component-base/test/virtualizer.test.js#L187) for it also, but it failed to catch the case where the user might have scrolled the virtualizer manually before the size change.
The current size change implementation always [invokes](https://github.com/vaadin/web-components/blob/3224d4e1760babd894391ce6ce7e6f08ed467669/packages/component-base/src/virtualizer-iron-list-adapter.js#L266-L268) the `_itemsChanged` in `iron-list-core`, which in turn would reset the scroll position to 0. To mitigate this, there is a mechanism, based on …
=> refactor: avoid unnecessary re-renders on virtualizer size change

packages/upload/src/vaadin-upload.js, packages/upload/test/adding-files.test.js
Cherry-pick of [5652](https://github.com/vaadin/web-components/pull/5652) to v23.3.
Fixes #[4777](https://github.com/vaadin/flow-components/issues/4777)
=> fix: make extension patterns match the end of the file name (#5652) (CP: 23.3)

packages/vaadin-lumo-styles/badge-global.js, packages/vaadin-lumo-styles/color-global.js, packages/vaadin-lumo-styles/color.js, packages/vaadin-lumo-styles/global.js, packages/vaadin-lumo-styles/sizing.js, packages/vaadin-lumo-styles/spacing.js, packages/vaadin-lumo-styles/style.js, packages/vaadin-lumo-styles/test/visual/badge.test.js, packages/vaadin-lumo-styles/typography-global.js, packages/vaadin-lumo-styles/typography.js, packages/vaadin-lumo-styles/user-colors.js, packages/vaadin-lumo-styles/utility-global.js
This ensures the styles do not override any application styles
=> fix: Register Lumo global styles before other styles

packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/test/dropdown.test.js
Back-ports [5670](https://github.com/vaadin/web-components/pull/5670) to v23.3.
Fixes #5640
=> fix: commit focused date on outside click (#5670) (CP: 23.3)

packages/tooltip/src/vaadin-tooltip.js, packages/tooltip/test/tooltip.test.js
`vaadin-tooltip` uses an `IntersectionObserver` to watch for the target _full_ visibility. If the user scrolls the page in a way that the target of the tooltip is only partially visible (or not visible at all), the tooltip overlay - if previously shown - is automatically hidden too. This helps to prevent a situation when we would show a tooltip for an element which is not visible.
Issue #5667 reported buggy behaviour of this mechanism when rendering tooltips using lit $repeat directive. However, further investigation showed that it's a more general problem, and the buggy behaviour is observed when you are simply _moving_ elements from place to place (which is what $repeat internally does) - but it's buggy only in Chromium based browsers. 
Even though all involved elements always stay in …
=> fix: process all intersection observer event entries

packages/component-base/src/async.js
Replace the mechanism based on `MutationObserver` with native `queueMicrotask` in async.microtask
=> refactor: replace MutationObserver with native queueMicrotask

packages/tooltip/src/vaadin-tooltip.js, packages/tooltip/test/tooltip.test.js
Back-ports https://github.com/vaadin/web-components/pull/5674 to v24.0
Fixes https://github.com/vaadin/web-components/issues/5423
There was a conflict in imports in vaadin-tooltip.js file
=> fix: defer resolution of tooltip target (#5674) (CP: 24.0)

packages/grid/src/vaadin-grid-data-provider-mixin.js
The PR slightly simplifies the grid data provider mixin by making it use `_getVisibleRows()` instead of `iterateChildren()`.
=> refactor: use _getVisibleRows() when iterating visible rows

packages/a11y-base/src/aria-id-reference.d.ts, packages/a11y-base/src/aria-id-reference.js, packages/a11y-base/src/field-aria-controller.js, packages/a11y-base/test/aria-id-reference.test.js, packages/component-base/src/dom-utils.d.ts, packages/component-base/src/dom-utils.js
Continuation of #5622
These helpers allow custom or generated ID references to be used for `aria-labelledby` and `aria-describedby`. This is needed to make it possible to set custom values to `aria-label`, `aria-labelledby`, and `aria-describedy`.
There are 3 helper functions created:
- The `setAriaIDReference ` functions take a 4th optional parameter `fromUser`, which is used to tell apart if the ID reference is being set from the default behavior (for instance, `aria-labellebdy` set when the `label` attribute changes) or from the user of the component to change the default value to a custom one.
- The `removeAriaIDReference` functions store the current attribute value and remove it. The main usage is for removing `aria-labelledby` to let setting `aria-label`, without losing the previous …
=> feat: add helpers for setting ID references to aria- attributes

.idea/workspace.xml, packages/notification/src/vaadin-notification.js, packages/notification/test/notification.test.js
As a [solution](https://github.com/vaadin/web-components/pull/3830) to a previous [issue](https://github.com/vaadin/web-components/issues/3823), notification is closed on detach. But in cases where there are changes in the children of the parent element, notification can be detached and immediately get reattached. In those cases, the notification should stay open without flickering. This PR wraps the execution of close on detach in a microtask. This way, if the notification is still attached at that point, the closing operation will not be executed.
Fixes #5665
=> fix: close notification on detach only if not immediately reattached

packages/a11y-base/src/aria-id-reference.js, packages/a11y-base/test/aria-id-reference.test.js
Fix an issue where calling `removeAriaIDReference` followed by `restoreGeneratedAriaIDReference` would prevent any generated ID reference from being set because the presence of `Set` on the targets map makes `setAriaIDReference` assume that the user is still controlling the attribute.
The map entry should be deleted after `restoreGeneratedAriaIDReference` is called to fix this issue.
=> fix: aria id reference should be set after remove/restore are called

packages/accordion/test/accordion.test.js, packages/details/src/collapsible-mixin.js, packages/details/test/details.test.js
The `vaadin-detail` component summary can also contain elements or other components, like this:
```
<vaadin-details>
<vaadin-details-summary slot="summary">
<div>Summary<div>
</vaadin-details-summary>
<div>Content</div>
</vaadin-details>
```
There is even flow API for it. The unit tests for `vaadin-details` and `vaadin-accordion` did not cover such usecase.
I've added tests for this usecase and then fixed the referenced issue -> when the summary contained child elements, then clicks on this child elemens did not cause the detail to open/close. The click event is now processed not only when the `focusElement` is clicked, but also when any of it's children is clicked. 
Fixes vaadin/flow-components#4795
=> fix: open detail when summary child components clicked

packages/time-picker/src/vaadin-time-picker.js, packages/time-picker/test/time-picker.test.js
The PR prevents `time-picker` from setting `__keepInvalidInput` when the `value` property doesn't change. This in turn prevents the value property observer from mistakenly preserving bad input on the possible next value property change.
Fixes #5695
=> fix: do not preserve bad input on value property change

packages/grid/src/vaadin-grid.js
Debounce the tasks scheduled to be run after virtualizer requests new rows from the grid.
The change has a 6% impact on the `rendertime` metric in the [Grid benchmark tests](https://bender.vaadin.com/buildConfiguration/Flow_Components_BenchmarkTests_Grid?mode=builds).
=> refactor: debounce tasks ran after creating grid rows

packages/a11y-base/src/focus-utils.d.ts, packages/a11y-base/src/focus-utils.js, packages/a11y-base/test/focus-utils.test.js
Extracted this function to focus utils in order to have it properly tested without relying on implicit overlay unit tests:
https://github.com/vaadin/web-components/blob/4065e6c5f3525ce77ae425c6147a390ef59c9c08/packages/overlay/src/vaadin-overlay.js#L754-L762
Note, this helper [also exists](https://github.com/ing-bank/lion/blob/d938e464b499bf48460829be0eeba596a41bd724/packages/ui/components/overlays/src/utils/get-deep-active-element.js#L8) in Lion Web Components (our libraries are similar and we copy each other's homework).
Furthermore, newly added unit tests are actually adapted from [Lion overlays utils tests](https://github.com/ing-bank/lion/blob/d938e464b499bf48460829be0eeba596a41bd724/packages/ui/components/overlays/test/utils-tests/active-element.test.js#L5) with a few small tweaks. …
=> feat: add getDeepActiveElement helper to focus utils

packages/component-base/src/virtualizer-iron-list-adapter.js
Move the Virtualizer's item placeholder assignment logic from `__updateElement`, where it was run for each element individually right after an update, to a separate function which runs the same logic for multiple elements after a batch update.
The change has a 35% impact on the `verticalscrollframetime` metric in the [Grid benchmark tests](https://bender.vaadin.com/buildConfiguration/Flow_Components_BenchmarkTests_Grid?mode=builds).
=> refactor: batch run virtualizer placeholder updates

packages/combo-box/test/lazy-loading.test.js, packages/component-base/src/virtualizer-iron-list-adapter.js, packages/component-base/test/virtualizer-item-height.test.js, packages/grid/test/filtering.test.js
On init, Virtualizer creates item elements in batches until the visible viewport (plus some extra buffer) has been covered. By default, this happens in multiple rounds of creating, adding, and measuring in batches of a few items.
Each round is quite expensive due to the forced layout required for measuring the resulting item height. This PR overrides the `_increasePoolIfNeeded` function from `iron-list-core` and makes it try to create the remaining items in a single batch after the first few items have been created.
The change has a 26% impact on the `rendertime` and 19% impact on the `expandedrendertime` metrics in the [Grid benchmark tests](https://bender.vaadin.com/buildConfiguration/Flow_Components_BenchmarkTests_Grid?mode=builds).
=> refactor: minimize virtualizer item create rounds

packages/combo-box/src/vaadin-combo-box-scroller.js, packages/combo-box/test/lit.test.js, packages/virtual-list/src/vaadin-virtual-list.js
CP of #5714 to 23.3
There were merge conflicts -> `vaadin-multi-select-combo-box` and `vaadin-time-picker` scrollers do not have their own styles in 23.3 but rather inherit styles from ComboBoxScroller - so the fix was needed only there
=> fix: explicitly set relative positioning on scroll containers (#5714) (CP: 23.3)

packages/confirm-dialog/theme/lumo/vaadin-confirm-dialog-styles.js, packages/crud/theme/lumo/vaadin-crud-styles.js, packages/vaadin-lumo-styles/typography.js
In Vaadin 24.0 [heading margins were set to zero](https://github.com/vaadin/web-components/issues/4595). However, this affected not only vertical margins but also horizontal ones. This caused issues in some of the components, fixed by adding `!important` to the right places (see [this PR](https://github.com/vaadin/web-components/pull/5329)).
However, additional places where this is causing issues appeared, like placing a heading in a `vaadin-from-layout`.
@rolfsmeds suggested the following solution:
> Come to think of it, by far the simplest solution would be to replace `margin:0;` on the headings with `margin-block-start:0; margin-block-end:0;` to set the vertical margins to 0 without affecting horizontal margins.
So this PR is introducing it. This also removed the need to have those …
=> fix: set only vertical margins of headings to zero

packages/grid/src/vaadin-grid-styles.js, packages/grid/test/basic.test.js
Fixes https://github.com/vaadin/web-components/issues/1544
Now that we have the grid benchmark tests in place, it was possible to measure the impact of using `opacity: 0` vs `visibility: hidden` in this case.
The change has a 16% impact on the `verticalscrollframetime` metric in the [Grid benchmark tests](https://bender.vaadin.com/buildConfiguration/Flow_Components_BenchmarkTests_Grid?mode=builds).
=> refactor: use visibility to hide loading grid cells

packages/button/src/vaadin-button-base.js, packages/checkbox/src/vaadin-checkbox-styles.js, packages/context-menu/src/vaadin-menu-overlay-styles.js, packages/date-picker/src/vaadin-date-picker-overlay.js, packages/date-picker/src/vaadin-month-calendar.js, packages/dialog/src/vaadin-dialog-overlay.js, packages/field-base/src/styles/field-shared-styles.js, packages/grid/src/vaadin-grid-styles.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/notification/src/vaadin-notification.js, packages/progress-bar/src/vaadin-progress-bar-styles.js, packages/radio-group/src/vaadin-radio-button.js, packages/rich-text-editor/src/vaadin-rich-text-editor-toolbar-styles.js, packages/select/src/vaadin-select-overlay.js, packages/split-layout/src/vaadin-split-layout.js, packages/tabs/src/vaadin-tab.js, packages/tabs/theme/lumo/vaadin-tab-styles.js, packages/tooltip/src/vaadin-tooltip-overlay.js
CSS adjustments in various components for improved `forced-colors` mode (e.g. Windows High Contrast Mode) support. The adjustments primarily consist of applying `outline`s to various elements. All adjustments are scoped in `@media(forced-colors:active)` blocks, or apply the `forced-color-adjust: none;` mechanism, and thus have no effect outside of `forced-colors` mode.
Fixes #5060
=> feat: forced colors support

packages/grid/src/vaadin-grid-data-provider-mixin.js, packages/grid/test/data-provider.test.js, packages/grid/test/row-details.test.js, packages/grid/test/scroll-to-index.test.js
There is an `__updateVisibleRows()` method that updates grid rows' content and the related a11y attributes. The custom implementations based on `this._getVisibleRows().forEach(...)` can be replaced with it.
=> refactor: use __updateVisibleRows() instead of a custom implementation

packages/grid/src/vaadin-grid-data-provider-mixin.js, packages/grid/test/data-provider.test.js, packages/grid/test/row-details.test.js, packages/grid/test/scroll-to-index.test.js
This reverts commit b16f960e73943529c60dd327d0a9a5075cf113e2.
The changes done #5733 introduced some issues that causes a series of test failures as can be seen in [the PR](https://github.com/vaadin/flow-components/pull/4927) updating the WC version in the Flow Components.
For instance, in [this test](https://github.com/vaadin/flow-components/blob/fb3089cd8dbb1b7559fbcad0aaa9a4cec7bd6fc3/vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridMultiSelectionColumnPageIT.java#L186), the Grid is stuck in a infinite loop.
=> Revert "refactor: update rows with __updateVisibleRows() when receiving a page (#5733)"

packages/vaadin-material-styles/color-global.js, packages/vaadin-material-styles/typography-global.js
This is so we can remove https://github.com/vaadin/flow-components/blob/main/vaadin-material-theme-flow-parent/vaadin-material-theme-flow/src/main/resources/META-INF/resources/frontend/material-includes.ts
=> chore: Add global imports for Material

packages/number-field/src/vaadin-number-field-mixin.d.ts, packages/number-field/test/typings/number-field.types.ts, packages/text-area/src/vaadin-text-area-mixin.d.ts, packages/text-area/test/typings/text-area.types.ts, packages/text-field/src/vaadin-text-field-mixin.d.ts, packages/text-field/test/typings/text-field.types.ts
The `clearButtonVisible` property of the text-field and derivatives was missing the TypeScript definition. Using the property resulted in TypeScript error in Hilla / React as a result, although the JS works in the browser. This change exposes the propery by exposing the corresponding `ClearButtonMixinClass` mixin typings for the affected components.
Fixes vaadin/react-components#69
=> fix: TypeScript typings for clearButtonVisible prop in field components

packages/number-field/src/vaadin-number-field-mixin.d.ts, packages/number-field/test/typings/number-field.types.ts, packages/text-area/src/vaadin-text-area-mixin.d.ts, packages/text-area/test/typings/text-area.types.ts, packages/text-field/src/vaadin-text-field-mixin.d.ts, packages/text-field/test/typings/text-field.types.ts
Cherry-pick of https://github.com/vaadin/web-components/pull/5754
=> fix: TypeScript typings for clearButtonVisible prop in field components (CP: 24.0)

packages/app-layout/src/vaadin-app-layout.js, packages/app-layout/test/app-layout.test.js
The problem here is that when using `app-layout` on mobile (or when emulating in Chrome dev tools using touch-optimized desktop view), the bottom navigation bar is always visible, although it has no content in it. Such behaviour is seen as buggy and unexpected.
@rolfsmeds suggested ([in this comment](https://github.com/vaadin/flow-components/issues/4878#issuecomment-1488939615)) modifying the bottom navbar CSS, so it's able to collapse to zero height when empty. However, I'd propose a slightly different solution in this PR: there is a javascript code which ensures that the **top** navbar is hidden when it has no content. I'd suggest, for consistency's sake, doing the same for the bottom navbar - hide it when it has no content regardles of the touch-optimization mode. This would also keep …
=> fix: hide bottom navbar when it's empty

packages/a11y-base/src/field-aria-controller.js, packages/field-base/src/field-mixin.js, packages/field-base/test/field-mixin.test.js
Allow the user to set `accessibleNameRef` before an element implementing `FieldMixin` is attached to the page.
=> fix: allow setting accessibleNameRef before attaching

dev/side-nav.html, packages/side-nav/src/vaadin-side-nav-item.js
This PR would solve the issue that the `side-nav-item` is clickable (and redirects to "empty string") when `path` attribute is not set on `side-nav-item`. 
`ifDefined` Lit directive makes sure, that:
* if the `path` is non-empty, then `href` attribute is set using it's value
* if the `path` is undefined (default value), then `href` attribute is completely omitted from the `a` tag
=> fix: omit href when it's empty

packages/confirm-dialog/src/vaadin-confirm-dialog.js, packages/confirm-dialog/test/confirm-dialog.test.js, packages/confirm-dialog/test/dom/__snapshots__/confirm-dialog.test.snap.js, packages/crud/test/dom/__snapshots__/crud.test.snap.js
This PR aims to enhance the announcement behavior for Confirm Dialog by changing a couple of things:
- Modfify Confirm Dialog's overlay role from `dialog` to `alertdialog`
- Set `aria-describedby` in the overlay to point to the elements inside the default slot.
- Each element provided by the user is wrapped in a `<div>` element
- The wrapper receives a generated id 
- The wrapper is styled with `display: contents` to allow the children elements behave as expected.
Also:
- Tests to check the behavior have been added
- Snapshots updated to reflect the new tree
Part of #4684
=> feat(confirm-dialog): add `aria-describedby` and `role=alertdialog`

packages/context-menu/src/vaadin-context-menu.js, packages/context-menu/test/context.test.js
Currently the context menu just closes when it is disconnected from the DOM, and does not reopen when it is connected again. This can be a problem with how the Dialog works now in 24, as it first adds all children to the host element, and then the renderer function moves them to the overlay. As part of moving to the overlay, the context menu becomes disconnected, and closes itself. This assumes that the Flow context menu auto-adds itself to the Dialog when it is opened, when adding the context menu manually the problem does not occur.
This change makes the context menu open again when it is connected to the DOM again. This is adapted from a similar change done for dialogs: https://github.com/vaadin/web-components/pull/3648
Fixes https://github.com/vaadin/flow-components/issues/4896
- …
=> fix: restore context menu opened state when moving within DOM

packages/a11y-base/src/field-aria-controller.js, packages/field-base/src/field-mixin.js, packages/field-base/test/field-mixin.test.js
The changes on #5770 make it possible to set `accessibleNameRef` before attaching the element. However, it introduced another issue when `accessibleNameRef` is removed, then the generated one is.
This is due to an early return added in the `__labelChanged` method in `field-mixin`:
https://github.com/vaadin/web-components/blob/03fbf19d6338bce8545c2c75ac2964a0ce140a53/packages/field-base/src/field-mixin.js#L146-L148
Instead, this change removes the early exit and allows the default label to be set and change `setTarget` in `field-aria-controller` to first set the default label id and then check if a custom id exists to replace the former with the latter, storing it on the process.
=> fix: store generated labelledby on attach

packages/a11y-base/test/list-mixin.test.js
Related to https://github.com/vaadin/web-components/issues/3154
Looks like in the latest version of Web Test Runner, the version of Mocha has been updated so the above issue started to manifest in some cases where we missed to use spread or `Array.from()`. This PR aims to address this problem.
- Test
=> test: make children a proper array before iterating

packages/a11y-base/src/focus-utils.js, packages/a11y-base/test/focus-utils.test.js
Keyboard navigation for tab bar is currently broken when the element is within the app layout's drawer. The cause is the following check which incorrectly identifies all tabs as hidden:
https://github.com/vaadin/web-components/blob/7a9fbf11acabb7fb103c7f09e3318c50d2e1e6cd/packages/a11y-base/src/focus-utils.js#L148-L153
The problem is that `offsetParent` is also null if the element is using fixed positioning. It can also be null for nested elements in a container with fixed positioning, such as for the tabs being in the app layouts drawer.
This change adds an additional check to verify that items have no client size which would be another indicator that `display: none` is being used in the hierarchy.
Fixes https://github.com/vaadin/web-components/issues/5706
- Bugfix
=> fix: keyboard navigation when using position fixed

packages/side-nav/src/vaadin-side-nav-item.d.ts, packages/side-nav/src/vaadin-side-nav-item.js, packages/side-nav/src/vaadin-side-nav.d.ts, packages/side-nav/src/vaadin-side-nav.js, packages/side-nav/test/side-nav-item.test.js, packages/side-nav/test/side-nav.test.js, packages/side-nav/test/typings/side-nav.types.ts
The Flow API has `setExpanded()` method to have the ability to programmatically expand/collapse SideNav and SideNavItems (if they have a hierarchical structure). There is also `isExpanded()` method on both components to check the expanded state. However, this method does not return the correct state if the user clicks on the expand/collapse button in the browser. The state of the client property _is not_ synchronized back to the server.
This PR solves this issue together with https://github.com/vaadin/flow-components/pull/5007
I've checked the other components how they do it, namely `vaadin-details` or `vaadin-accordion` (both have `opened` properties, which are being synchronized to the server).
The fix is to produce the events on the client when the given property changes (by using …
=> fix: synchronize expanded/collapsed state to server

packages/vaadin-lumo-styles/mixins/required-field.js
Adds a top-padding, and respective negative margin, to input field labels to prevent diacritics from being cut off.
Decided to go with the top padding solution based on the reasoning here: https://github.com/vaadin/web-components/pull/5501#issuecomment-1521433948
Fixes #5386
- Bugfix
=> fix: prevent diacritics from being cut off

packages/date-time-picker/src/vaadin-date-time-picker.d.ts, packages/date-time-picker/src/vaadin-date-time-picker.js, packages/date-time-picker/test/dom/__snapshots__/date-time-picker.test.snap.js, packages/date-time-picker/test/i18n.test.js
Add two new properties `dateLabel` and `timeLabel` to the `i18n` object ultimately used to set the `aria-label` attribute on each field, through the `accessible-name` API.
The values are concatenated with one of the following properties (if defined)
- accessible-name; or
- label
Part of https://github.com/vaadin/flow-components/issues/4719
=> feat: add dateLabel/timeLabel props to i18n object

packages/app-layout/src/vaadin-app-layout.js, packages/app-layout/theme/material/vaadin-app-layout-styles.js, packages/app-layout/theme/material/vaadin-drawer-toggle-styles.js
I tried to minimize the changes to remove the more specific selectors only, but there are a few other changes like removing `left`/`right` to `inset-inline` when the value being set was the same.
- remove most of selectors using `[dir="rtl"]`
- as there's translate logical function , the selectors for RTL could not be removed
Part of #2141
=> refactor: [app-layout] use CSS logical props

packages/side-nav/theme/lumo/vaadin-side-nav-item.js
The Lumo styles are not applied for `vaadin-nav-side-item` when used from Flow.
The reason for this is that Flow generates the `generated-flow-imports.js` with the following content:
You can see that only Lumo import for the `vaadin-nav-side` is generated for flow. It's true that this import registers styles also for `vaadin-nav-side-item`, however it seems that the order of things is the trouble here: the styles are registered _after_ the `vaadin-nav-side-item` was defined, which means that the styles are not used.
This PR fixes this by creating another file in the `theme/lumo` directory named `vaadin-side-nav-item.js`. This ensures that the file is detected by Flow while generating `generated-flow-imports.js` and the Lumo theme file is imported there instead of the `src` bare version. …
=> chore: add Lumo style file for side-nav-item

packages/list-box/package.json
Added the missing `@open-wc/dedupe-mixin` dependency to `list-box` to fix TypeScript compilation errors in user projects.
Fixes https://github.com/vaadin/web-components/issues/5780
=> fix: add missing dedupe-mixin dependency

packages/a11y-base/src/field-aria-controller.js, packages/a11y-base/test/field-aria-controller.test.js, packages/checkbox-group/test/dom/__snapshots__/checkbox-group.test.snap.js, packages/custom-field/test/dom/__snapshots__/custom-field.test.snap.js, packages/date-time-picker/test/aria.test.js, packages/date-time-picker/test/dom/__snapshots__/date-time-picker.test.snap.js, packages/field-base/test/field-mixin.test.js, packages/radio-group/test/dom/__snapshots__/radio-group.test.snap.js
As both **JAWS** and **NVDA** announce `aria-describedby` correctly, and only **VoiceOver** cannot do so, we'll revert to using `aria-describedby` for content that is not semantically part of the label.
Otherwise, we would have to refactor tooltips to use `aria-labelledby` and introduce a hidden element for invisible aria-labels. Furthermore, concatenating labels, descriptions, validation errors, and tooltips into the label results in extremely verbose announcements.
We see this as choosing the less bad (and less complex) of two bad options.
=> refactor!: use aria-describedby for group field components

packages/select/src/vaadin-select.js
The method was added by mistake in cb419f5bd28be028ddea7bda3691d310f32f4475 and it was part of a prototype of the feature but it's not currently used anywhere.
=> refactor: remove unused method in select

packages/confirm-dialog/src/vaadin-confirm-dialog.js
Optional chaining is not supported by Polymer Analyzer, which means no component docs -> web types -> React wrappers can be generated.
=> refactor: remove optional chaining from confirm-dialog

packages/side-nav/LICENSE, packages/side-nav/README.md, packages/side-nav/package.json, packages/side-nav/src/vaadin-side-nav-item.d.ts, packages/side-nav/src/vaadin-side-nav-item.js, packages/side-nav/src/vaadin-side-nav.d.ts, packages/side-nav/src/vaadin-side-nav.js
Some minor improvements and fixes for findings from the original PR review.
- Refactor
=> refactor: minor code style improvements and cleanup

packages/overlay/test/restore-focus.test.js
The PR restructures the overlay focus restoration tests in preparation for adding focus-ring tests in https://github.com/vaadin/web-components/pull/5839
> **Note**
> When reviewing, I suggest enabling the "Hide whitespace" option to miminize the diff.
=> test: restructure focus restoration tests

packages/vaadin-lumo-styles/badge.js, packages/vaadin-lumo-styles/color.js, packages/vaadin-lumo-styles/utilities/background.js, packages/vaadin-lumo-styles/utilities/border.js, packages/vaadin-lumo-styles/utilities/typography.js
Adds warning colors to Lumo, including utility classes and badge styles.
Fixes #1655
=> feat: Lumo warning colors

packages/overlay/src/vaadin-overlay.js, packages/overlay/test/restore-focus.test.js
The PR extracts the overlay's focus restoration logic into individual methods `__storeFocus` and `__restoreFocus` in preparation for #5839 where the logic will be improved to restore the `focus-ring` attribute as well.
=> refactor: extract focus restoration logic into individual methods

packages/text-area/test/dom/__snapshots__/text-area.test.snap.js, packages/text-area/test/dom/text-area.test.js
Updated `text-area` package to exclude inline `style` attribute that currently causes snapshots to fail:
```
packages/text-area/test/dom/text-area.test.js:
❌ vaadin-text-area > shadow > default
AssertionError: Snapshot vaadin-text-area shadow default does not match the saved snapshot on disk
</span>
</div>
<vaadin-input-container
part="input-field"
-    style="--_text-area-vertical-scroll-position: 0px;"
+    style="--_text-area-vertical-scroll-position:0px;"
>
<slot
name="prefix"
slot="prefix"
```
- Tests
- Scroll position logic is covered by unit tests
- Visual appearance is covered by visual tests
=> test: exclude internal custom CSS property from snapshots

packages/overlay/test/restore-focus.test.js
The PR enables `focus-trap` in the focus restoration tests which allows getting rid of some manual focus manipulations. It also adds an explicit unit test making sure focus is restored in the case it was moved to body while the overlay was open.
Preparation for #5839
=> test: simplify and enhance focus restoration tests

packages/menu-bar/src/vaadin-menu-bar-mixin.js, packages/menu-bar/test/menu-bar.test.js
In v23, the parent element of menu bar buttons was the container div without a static position. After the refactoring made during the transition to v24, the direct parent element became the menu bar itself, which has a static position. This led the `offsetLeft` being calculated relative to the ancestors of the menu bar, which broke the overflow calculation. 
This PR updates the overflow calculation to use the difference between `boundingClientRect.left` of the button and the container. 
Fixes #5807
=> fix: compute offsetLeft using boundingClientRect

packages/icon/src/vaadin-icon.js, packages/icon/src/vaadin-iconset.d.ts, packages/icon/src/vaadin-iconset.js, packages/icon/test/icon.test.js
Fixes #5847
The solution is almost the same as in #4002 except the fact that we don't have public API for the default attribute value.
- Bugfix
While we extend the return type of the `Iconset.getIconSvg()` API, this is kind of internal feature needed to fix a bug.
=> fix: allow setting custom preserveAspectRatio attribute

packages/login/src/vaadin-login-form.js, packages/login/test/login-form.test.js
Replace `input.validate()` with `input.checkValidity()` to check whether the following field is valid or not to prevent it from being marked as invalid when, for instance, the user is focused on the username field hits <kbd>Enter</kbd> and focus is moved to the password field.
- Bugfix
=> fix: check validity on next input in login-form

packages/notification/theme/lumo/vaadin-notification-styles.js
Adds a warning theme variant to vaadin-notification
Fixes #4110
=> feat: add Notification warning variant

packages/overlay/src/vaadin-overlay.js, packages/overlay/test/restore-focus.test.js
The PR includes a fix for `overlay` to restore not only focus but also the `focus-ring` attribute on overlay close when `restoreFocusOnClose` is enabled.
Part of https://github.com/vaadin/web-components/issues/139
=> fix: restore focus-ring attribute on overlay close

packages/context-menu/src/vaadin-contextmenu-items-mixin.js, packages/context-menu/test/items.test.js
Close the last opened sub-menu on Escape instead of closing the root menu.
This change is done to align with [ARIA Authoring Practices Guide (APG) for Menu / Menu Bar](https://www.w3.org/WAI/ARIA/apg/patterns/menu/) where it's described as the following:
> Escape: Close the menu that contains focus and return focus to the element or context, e.g., menu button or parent menuitem, from _which the menu was opened_.
Fixes #4768
- Bugfix
=> fix: close top-most open menu on Escape

packages/dialog/package.json, packages/dialog/src/vaadin-dialog.js, packages/dialog/test/dialog.test.js, packages/dialog/test/dom/__snapshots__/dialog.test.snap.js
The PR enables the overlay logic to restore focus on dialog close.
Fixes https://github.com/vaadin/web-components/issues/139
=> fix: restore focus on dialog close

packages/overlay/src/vaadin-overlay-focus-mixin.d.ts, packages/overlay/src/vaadin-overlay-focus-mixin.js, packages/overlay/src/vaadin-overlay.d.ts, packages/overlay/src/vaadin-overlay.js
Follow-up to #5839
Extracted most of the focus handling logic to `OverlayFocusMixin` used by `Overlay` itself.
- Refactor
=> refactor: extract overlay focus logic to separate mixin

packages/overlay/src/vaadin-overlay-focus-mixin.js, packages/overlay/test/focus-trap.test.js
Related to #92
Here's a PR that adds usage of `AriaModalController` introduced in #5611 to `OverlayFocusMixin`.
-  Refactor / bugfix
Implementing this change took so long because of my personal matters. Glad that it's done now.
=> refactor: set aria-hidden on elements outside modal overlay

packages/dialog/test/dialog.test.js, packages/grid/test/frozen-columns.test.js, packages/grid/test/keyboard-navigation.test.js, packages/overlay/test/restore-focus.test.js
It's better to prefer `getDeepActiveElement` over `isElementFocused` in test assertions where possible because the former will log an actual focused element if the test fails, which can be helpful information for the further investigation.
=> test: prefer getDeepActiveElement in assertions

wtr-utils.js
Update the web-test-runner change detection script to use `24.1` as a base branch for Vaadin 24.1
=> chore: update change detection to 24.1

packages/overlay/src/vaadin-overlay-stack-mixin.d.ts, packages/overlay/src/vaadin-overlay-stack-mixin.js, packages/overlay/src/vaadin-overlay.d.ts, packages/overlay/src/vaadin-overlay.js
Fixes #5717
Related to #5716
This PR gets us one step closer to Lit migration by decoupling attached instances from the `Overlay` class.
- Refactor
=> refactor: extract overlay instances logic to new mixin

packages/component-base/src/slot-controller.js, packages/component-base/test/slot-controller.test.js
`SlotController` currently removes previously added custom elements whenever a new element is added. While that is OK if the slot may only contain a single element, or only contains the default node when multiple elements are allowed, that is an issue if the slot may contain multiple elements and already has custom elements assigned. In that case previously added elements are just removed.
This changes the logic to only remove:
- the previous node in single mode
- the default node in multiple mode
I also updated the logic for calculating the current nodes in multiple mode to reflect that. I feel that the logic is still incomplete though, as the `nodes` array (as well as the `node` property) is never updated when removing elements. Then again I'm not sure if I understand the controller …
=> fix: keep previously added custom elements

packages/component-base/src/virtualizer-iron-list-adapter.js, packages/component-base/test/virtualizer.test.js
`IronListAdapter` adds an additional `hidden` and `__lastUpdatedIndex` to items. That state is not properly updated when reducing the `size` while the container is invisible because `IronList` does not re-render / update in that case. That leads to the adapter not re-rendering items when the size is increased again, showing stale data.
This change explicitly updates the `hidden` and `__lastUpdatedIndex` state when `size` changes and the container is invisible, so that items are properly re-rendered when increasing the size again.
Fixes https://github.com/vaadin/flow-components/issues/4937
- Bugfix
=> fix: update hidden state when virtualizer container is invisible

packages/grid/src/vaadin-grid.js, packages/grid/test/column-auto-width.test.js
When adding an existing grid to a split layout, auto-width columns can be collapsed to zero width. The cause is that elements are usually added to split layout without setting a slot name, as split layout applies the slot names automatically after elements have been added. When grid is added to the DOM, it immediately recalculates column widths, which results in a width of zero, as the grid is not assigned to a slot yet and is thus invisible.
This change adds a check for whether the grid is hidden, and in that case defers column width calculation to the resize observer, which should be triggered when the grid becomes visible again (width changes from zero to whatever width the container provides).
Fixes https://github.com/vaadin/flow-components/issues/4747
- Bugfix
=> fix: prevent column width calculation when grid is not visible

packages/grid/src/vaadin-grid.js, packages/grid/test/column-auto-width.test.js
Cherry-pick of #5876 
Some changes were necessary:
- ResizeObserver needs to observe `this.$.table` instead of `this.$.footer`, same as in `main`
- Focus utils need to be imported from `component-base` instead of `a11y-base`
=> fix: prevent column width calculation when grid is not visible (#5876) (CP: 24.0)

packages/overlay/src/vaadin-overlay-focus-mixin.d.ts, packages/overlay/src/vaadin-overlay-focus-mixin.js
The PR extracts the logic, which checks if the overlay is allowed to restore focus on close, into an individual protected method `_shouldRestoreFocus` to allow potential overrides.
Part of https://github.com/vaadin/web-components/pull/5881
Related to https://github.com/vaadin/web-components/issues/137
=> refactor: extract _shouldRestoreFocus(), make it protected

packages/overlay/src/vaadin-overlay-focus-mixin.d.ts, packages/overlay/src/vaadin-overlay-focus-mixin.js, packages/overlay/src/vaadin-overlay.js
The PR moves the `_deepContains` method to `OverlayFocusMixin` where it's actually used and makes it protected to allow potential overrides.
Part of https://github.com/vaadin/web-components/pull/5881
Related to https://github.com/vaadin/web-components/issues/137
=> refactor: move _deepContains() to OverlayFocusMixin as protected

packages/component-base/src/dom-utils.d.ts, packages/component-base/src/dom-utils.js, packages/component-base/test/dom-utils.test.js
The standard `node.closest(selector)` is limited to searching for the closest element within the scope of the node's shadow root. The PR introduces a `getClosestElement(selector, node)` helper that allows finding elements across the boundaries of the node's shadow root.
Part of https://github.com/vaadin/web-components/pull/5881
Related to https://github.com/vaadin/web-components/issues/137
=> feat: add a getClosestElement helper

packages/scroller/theme/lumo/vaadin-scroller-styles.js
=> refactor: update scroller overflow indicators to use inset

packages/login/theme/lumo/vaadin-login-overlay-styles.js, packages/login/theme/material/vaadin-login-overlay-styles.js
=> refactor: update login overlay wrapper styles to use inset

packages/input-container/theme/lumo/vaadin-input-container-styles.js
=> refactor: update input container Lumo styles to use inset

packages/crud/src/vaadin-crud-dialog.js
=> refactor: update CRUD dialog fullscreen styles to use inset

packages/dialog/src/vaadin-dialog-resizable-mixin.js
=> refactor: update dialog resizer edge styles to use inset

packages/split-layout/theme/lumo/vaadin-split-layout-styles.js
=> refactor: update small and minimal Lumo splitter to use inset

packages/tabs/theme/material/vaadin-tab-styles.js
=> refactor: update Material tab pseudo element to use inset

packages/button/theme/lumo/vaadin-button-styles.js
=> refactor: update Material button pseudo element to use inset

packages/context-menu/src/vaadin-menu-overlay-mixin.d.ts, packages/context-menu/src/vaadin-menu-overlay-mixin.js, packages/context-menu/test/a11y.test.js, packages/context-menu/test/helpers.js, packages/overlay/src/vaadin-overlay-focus-mixin.js
The PR enables the overlay logic to restore focus on context menu close.
Depends on 
- https://github.com/vaadin/web-components/pull/5895
- https://github.com/vaadin/web-components/pull/5896
- https://github.com/vaadin/web-components/pull/5897
Fixes https://github.com/vaadin/web-components/issues/137, https://github.com/vaadin/web-components/issues/292
=> fix: restore focus on context menu overlay close

packages/rich-text-editor/package.json, packages/rich-text-editor/src/vaadin-rich-text-editor.js, packages/rich-text-editor/test/a11y.test.js
Make pressing <kbd>Esc</kbd> temporarily remove default bindings for the <kbd>Tab</kbd>, so users can press <kbd>Tab</kbd> to move focus to the next element on the page, therefore preventing `<vaadin-rich-text-editor>` to become a focus trap. Pressing <kbd>Esc</kbd>  followed by  <kbd>Shit+Tab</kbd> moves the focus to the first toolbar button, which is the same current behavior.
The <kbd>Tab</kbd> default bindings are restored by typing another character or when the editor loses focus.
Part of #1674
=> fix: allow to remove focus from RTE on Escape + Tab

packages/component-base/src/virtualizer-iron-list-adapter.js, packages/grid/test/hidden-grid.test.js
Grid can currently lose its scroll position if it receives a scroll event when it is hidden. That seems to the case in tabsheet, where switching to an unloaded tab panel shows a loading indicator and changes the flex properties of the content container, which at least in Firefox triggers a scroll event on grids in hidden tab panels.
This change updates `IronListAdapter` to ignore scroll events if its scroll target is not visible.
Fixes https://github.com/vaadin/web-components/issues/5796
- Bugfix
=> fix: do not reset scroll position when hiding grid

packages/overlay/test/helpers.js, packages/overlay/test/restore-focus.test.js
The PR improves the overlay's focus restoration tests to assert that focus restores synchronously on overlay close except when an overlay closes on outside click. When clicking outside, Firefox and Safari force focus to move to the body element and retain it there until the next event loop iteration, so focus needs to be restored asynchronously but only in this particular case.
The target code fragment:
https://github.com/vaadin/web-components/blob/f437f56dc36b53b997caf2b0f6f2a94b2083fdf8/packages/overlay/src/vaadin-overlay-focus-mixin.js#L162-L170
Follows up to #5881
=> test: assert synchronous focus restoration except when outside click

packages/confirm-dialog/test/confirm-dialog.test.js
After adding `aria-hidden` logic to `vaadin-overlay` focus trap, we now have to wait for the overlay to fully open.
This PR addresses following console errors for `vaadin-confirm-dialog` unit tests:
```
$ yarn test --group confirm-dialog
yarn run v1.22.19
$ web-test-runner --group confirm-dialog
packages/confirm-dialog/test/confirm-dialog.test.js:
Chrome: |██████████████████████████████| 1/1 test files | 68 passed, 0 failed
Finished running tests in 1.5s, all tests passed! 🎉
```
- Tests
=> test: add missing await to confirm-dialog tests

packages/message-list/test/dom/__snapshots__/message.test.snap.js, packages/message-list/test/dom/message.test.js, packages/text-area/test/dom/__snapshots__/text-area.test.snap.js, packages/text-area/test/dom/text-area.test.js, packages/upload/test/dom/__snapshots__/vaadin-upload-file.test.snap.js, packages/upload/test/dom/vaadin-upload-file.test.js
- Remove inline styles from textarea snapshots, adapted from https://github.com/vaadin/web-components/pull/5853
- Remove inline styles from upload snapshots, adapted from https://github.com/vaadin/web-components/pull/5856
- Remove inline styles from message snapshots
=> test: fix snapshots for inline styles (23.3)

packages/crud/src/vaadin-crud.js
While working on #5928, I noticed that logic in `vaadin-crud` is different from other places where we check whether the event was prevented by calling `event.preventDefault()` in the listener. So I thought it would be nice to align it.
- Refactor
=> refactor: check for event.defaultPrevented in CRUD events

packages/avatar/test/avatar.test.js, packages/tooltip/src/vaadin-tooltip.js, packages/tooltip/test/tooltip.test.js
Currently a tooltip is only shown when its target is fully visible. That is an issue with avatar for example, which uses a negative margin that can pull it out of its scroll container if put right at the edge of it. It can also be confusing that a tooltip doesn't show for an element where only a single pixel is scrolled outside of the view.
This change makes tooltips show if their target is partially visible (even just a single pixel). I considered using some magic number between 0 and 1 for the threshold, but again it could be confusing why tooltips show / hide based on different scroll positions, even though the element is effectively visible for the user.
Fixes https://github.com/vaadin/flow-components/issues/5105
- Bugfix
=> fix: show tooltips when target is partially visible

packages/dialog/test/draggable-resizable.test.js, packages/dialog/test/header-footer.test.js
Same as #5920 but for `vaadin-dialog` - this PR addresses the following console errors:
```
packages/dialog/test/header-footer.test.js:
```
```
packages/dialog/test/draggable-resizable.test.js:
```
- Tests
=> test: update dialog unit tests, add missing await

packages/app-layout/src/vaadin-app-layout.js, packages/app-layout/test/keyboard-mobile.test.js
Related to https://github.com/vaadin/web-components/issues/92
Similar to #5870 but for `vaadin-app-layout`
- Refactor / bugfix
=> refactor: set aria-hidden on elements outside overlay drawer

packages/crud/src/vaadin-crud.js
These JSDoc parameters appear to be copy-paste leftovers. Let's fix them/.
=> docs: fix incorrect JSDoc params for private methods

packages/email-field/test/email-field.common.js
Related to #5938
For some reasons, this email check didn't fail in CI when I first updated the WTR version, but now it does fail.
Let's exclude it for now, and then consider investigating further (hopefully a new Chrome version fixes it).
```
packages/email-field/test/email-field-lit.test.js:
❌ email-field > default > invalid email addresses > should treat email@example as invalid
AssertionError: expected false to be true
-false
+true
at n.<anonymous> (packages/email-field/test/email-field.common.js:59:43)
packages/email-field/test/email-field-polymer.test.js:
❌ email-field > default > invalid email addresses > should treat email@example as invalid
AssertionError: expected false to be true
-false
+true
at n.<anonymous> …
```
=> test: comment out email causing test failure in Chrome

packages/field-base/test/pattern-mixin.test.js
Related to #5938
For some reasons, this email check didn't fail in CI when I first updated the WTR version, but now it does fail.
Let's skip it for now, and then consider investigating further (hopefully a new Chrome version fixes it).
```
packages/field-base/test/pattern-mixin.test.js:
❌ PatternMixin + Polymer > pattern > should fail validation when value mismatches JavaScript-specific regular expression
AssertionError: expected true to be false
-true
+false
at n.<anonymous> (packages/field-base/test/pattern-mixin.test.js:171:44)
❌ PatternMixin + Lit > pattern > should fail validation when value mismatches JavaScript-specific regular expression
AssertionError: expected true to be false
-true
+false
at n.<anonymous> …
```
=> test: skip unicode pattern test failing with latest Chrome

packages/crud/src/vaadin-crud.js, packages/crud/test/crud-buttons.test.js
Related to https://github.com/vaadin/web-components/issues/5946#issuecomment-1580847416 - see code example there.
Similar to #5146 that introduced `_isDefault` flags to `vaadin-upload` slot controllers for using by Flow counterpart.
This PR makes it possible for the `vaadin-crud` web component users to actually pass custom slotted button elements.
1. Slotted button text content always overridden based on the corresponding `i18n` property
2. Slotted button `theme` attribute was always set to use the value defined by the controller
1. When setting `_isDefault` property on the slotted button, `vaadin-crud` behaves as before
2. Otherwise, neither text content nor `theme` attribute aren't changed so user can set them
=> fix!: only modify text content for default slotted buttons

packages/grid/src/vaadin-grid-data-provider-mixin.js, packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js, packages/grid/src/vaadin-grid.js, packages/grid/test/column-rendering.test.js
The PR renames `getVisibleRows()` to `getRenderedRows()` to avoid potential confusion with methods like `getFirstVisibleItem` that retrieves rendered rows that are specifically in the viewport.
Part of https://github.com/vaadin/web-components/pull/5898
=> refactor: rename getVisibleRows() to getRenderedRows()

packages/menu-bar/test/a11y.test.js, packages/menu-bar/test/helpers.js
Backports the following PRs to `24.1`:
- #5892
Related to https://github.com/vaadin/web-components/issues/137
=> test: ensure focus is restored on menu-bar overlay close (#5892) (CP: 24.1)

packages/a11y-base/index.d.ts, packages/a11y-base/index.js, packages/a11y-base/src/focus-restoration-controller.d.ts, packages/a11y-base/src/focus-restoration-controller.js, packages/a11y-base/test/focus-restoration-controller.test.js, packages/crud/src/vaadin-crud-grid.js, packages/crud/src/vaadin-crud.js, packages/crud/test/a11y.test.js, packages/crud/test/helpers.js, packages/overlay/src/vaadin-overlay-focus-mixin.d.ts, packages/overlay/src/vaadin-overlay-focus-mixin.js, packages/overlay/src/vaadin-overlay.js, packages/overlay/test/restore-focus.test.js
Backports the following PRs to `24.1`:
- #5898
- https://github.com/vaadin/web-components/pull/5951
- https://github.com/vaadin/web-components/pull/5949
Depends on 
- https://github.com/vaadin/web-components/pull/5971
Fixes https://github.com/vaadin/web-components/issues/138
=> fix: restore focus on crud editor close (#5898) (CP: 24.1)

packages/side-nav/test/side-nav-item.test.js
Reorganized tests for `vaadin-side-nav-item` in order to make them more readable:
1. Moved all the individual test suites to be placed under the single root suite,
2. Removed a few tests that seem to be duplicates (e.g. checking for `expanded`)
3. Changed to use shorter variables e.g. `item`, not `passiveItemWithChildren`
- Tests
=> test: restructure and simplify side-nav-item unit tests

packages/side-nav/src/vaadin-side-nav-base-styles.js, packages/side-nav/src/vaadin-side-nav-item.js, packages/side-nav/test/dom/__snapshots__/side-nav-item.test.snap.js, packages/side-nav/test/side-nav-item.test.js
Depends on #5968
This PR changes the `render()` method to avoid performing `querySelector()` on each call.
Instead, I added `SlotController` which observes slot as necessary and stores DOM nodes.
- Refactor
=> refactor: replace querySelector in render with controller

packages/side-nav/src/vaadin-side-nav-base-styles.js, packages/side-nav/src/vaadin-side-nav-item.js, packages/side-nav/src/vaadin-side-nav.js, packages/side-nav/test/dom/__snapshots__/side-nav-item.test.snap.js, packages/side-nav/test/dom/__snapshots__/side-nav.test.snap.js
Fixes #5821
Added `<ul>` elements placed around the `<slot>` in `vaadin-side-nav` and `vaadin-side-nav-item`
- Refactor
Below are screen reader test results:
=> refactor: use list element instead of role on the slot

packages/side-nav/src/vaadin-side-nav-base-styles.js, packages/side-nav/src/vaadin-side-nav.d.ts, packages/side-nav/src/vaadin-side-nav.js, packages/side-nav/test/accessibility.test.js, packages/side-nav/test/dom/__snapshots__/side-nav.test.snap.js, packages/side-nav/test/side-nav.test.js, packages/side-nav/theme/lumo/vaadin-side-nav-styles.js
Closes #5809
Related to https://github.com/vaadin/web-components/issues/5809#issuecomment-1587086297
Replaced usage of `<details>` and `<summary>` elements with a mechanism similar to `vaadin-accordion-panel`:
1. Added logic to delegate focus to `<button>` in shadow DOM using `delegatesFocus: true` in shadow root options;
2. Added `FocusMixin` and implement `_shouldSetFocus()` to set `focused` and `focus-ring` attributes appropriately;
3. Adjusted Lumo theme accordingly, especially styles for the toggle button (for now copied from `vaadin-details`);
4. Added missing tests for `label` element ID and for the newly added logic to handle focus and related attributes.
- Refactor / behavior altering change
Tested in VoiceOver and it works the same as before:
=> refactor!: replace details with custom collapsible, add tests

packages/side-nav/src/vaadin-side-nav-base-styles.js, packages/side-nav/src/vaadin-side-nav-item.js, packages/side-nav/test/dom/__snapshots__/side-nav-item.test.snap.js, packages/side-nav/theme/lumo/vaadin-side-nav-item-styles.js
Extracted from #5991
1. Renamed `item` part to `link` which is more semantically correct,
2. Updated theme to use `[part]` selector instead of the `<a>` tag
As `vaadin-side-nav` is still behind the feature flag, this is OK to release in minor.
=> refactor!: rename anchor item part to link, update Lumo to use it

packages/side-nav/src/vaadin-side-nav-base-styles.js, packages/side-nav/src/vaadin-side-nav-item.d.ts, packages/side-nav/src/vaadin-side-nav-item.js, packages/side-nav/theme/lumo/vaadin-side-nav-item.js, packages/side-nav/theme/lumo/vaadin-side-nav.js, packages/side-nav/theme/material/vaadin-side-nav.js
Updates years on license dates for Side Nav classes. First introduced in Side Nav route alias feature [PR](https://github.com/vaadin/web-components/pull/5974).
=> chore: update license dates

packages/side-nav/src/vaadin-side-nav.js, packages/side-nav/test/dom/__snapshots__/side-nav.test.snap.js, packages/side-nav/theme/lumo/vaadin-side-nav-styles.js
Follow-up to #5978
Currently there are two similar part names that aren't named consistently:
https://github.com/vaadin/web-components/blob/316e453ce2b49eb18a20b241dcbda25e51afbe5a/packages/side-nav/src/vaadin-side-nav.js#L125
https://github.com/vaadin/web-components/blob/316e453ce2b49eb18a20b241dcbda25e51afbe5a/packages/side-nav/src/vaadin-side-nav-item.js#L190-L191
Let's use `toggle-button` which is also aligned with `vaadin-combo-box` and other overlay components.
- Refactor
=> refactor: rename side-nav toggle part to align with the item

packages/side-nav/src/vaadin-side-nav-base-styles.js
Follow-up to #5975
As you can see in that PR, `<ul>` element was added to two components.
These styles are leftovers as I forgot to remove them. Let's fix this now.
- Refactor
=> refactor: remove no longer needed children slot styles

packages/confirm-dialog/test/confirm-dialog.test.js, packages/dialog/src/vaadin-dialog.js, packages/dialog/test/dialog.test.js
Currently `vaadin-dialog` closes its overlay when it is removed from the DOM and opens it again when being added to the DOM again. When just moving the dialog within the DOM that results in two additional `opened-changed` events being fired. That in turn is problematic when using nested dialogs in Flow, where all elements are first added to the dialog root element, and then moved to the overlay by the dialog render function. In that case every dialog that is added to another dialog will effectively dispatch three opened changed events (1 initial, 2 from being moved within DOM).
Arguably a dialog should not dispatch these events when just being moved within the DOM. This PR changes the dialog to use a timeout to detect whether it was just moved within the DOM or actually removed, and only …
=> fix: avoid opened changed events when moving dialog within DOM

packages/confirm-dialog/test/confirm-dialog.test.js, packages/dialog/src/vaadin-dialog.js, packages/dialog/test/dialog.test.js
Cherry-pick of https://github.com/vaadin/web-components/pull/5995
=> fix: avoid opened changed events when moving dialog within DOM (CP: 24.0)

packages/side-nav/src/vaadin-side-nav-item.js, packages/side-nav/test/dom/__snapshots__/side-nav-item.test.snap.js, packages/side-nav/test/side-nav-item.test.js, packages/side-nav/theme/lumo/vaadin-side-nav-item-styles.js
Related to #5814
1. Moved `<button>` element outside the `<a>` element in `vaadin-side-nav-item`
2. Added extra wrapper with `part="content"` (name inspired by `vaadin-item` etc)
3. Added logic to catch click event on the `part="content"` and forward it to button
- Refactor, behavior altering changee
=> refactor!: move button outside the anchor, add content part

packages/component-base/src/url-utils.d.ts, packages/component-base/src/url-utils.js, packages/component-base/test/url-utils.test.js
Extracts and adds `url-utils` first introduced in Side Nav route alias feature [PR](https://github.com/vaadin/web-components/pull/5974). 
Related to [5141](url)
=> feat: add url utils

packages/side-nav/test/side-nav-item.test.js
This PR removes 2 side nav item tests that are already covered by snapshot tests.
=> test: remove tests covered in snapshot tests

packages/email-field/test/email-field.common.js
This is a cherry-pick of the email field pattern workaround to unlock `24.1` branch builds in Chrome.
- Tests
=> test: comment out email causing test failure in Chrome (#5957) (CP: 24.1)

packages/grid/src/vaadin-grid-a11y-mixin.js, packages/grid/src/vaadin-grid-drag-and-drop-mixin.js, packages/grid/src/vaadin-grid-helpers.js, packages/grid/src/vaadin-grid-styling-mixin.js, packages/grid/src/vaadin-grid.js, packages/grid/test/column-rendering.test.js
This PR fixes an issue specific to using grid lazy column rendering mode where some body row cells would not have their attributes updated due to being temporarily detached from the row. The issue occurs because some grid [utility methods](https://github.com/vaadin/web-components/blob/c459396942620baea42b57c76e5d75391d8ad048/packages/grid/src/vaadin-grid-helpers.js#L12-L22) relied on the DOM state to obtain cells of a row and this wasn't taken into account when the lazy column rendering feature was implemented.
The change includes one new utility method for specifically iterating over row cells (`iterateRowCells `), taking into account that some of the row cells may not be physically attached to the row. An existing utility method (`getBodyRowCells`) was also modified to take into account …
=> fix: use cached references to iterate cells instead of DOM state

packages/email-field/test/email-field.common.js
This is a cherry-pick of the email field pattern workaround to unlock `24.0` branch builds in Chrome.
- Tests
=> test: comment out email causing test failure in Chrome (#5957) (CP: 24.0)

packages/grid/src/vaadin-grid-helpers.js, packages/grid/src/vaadin-grid.js
Follow-up for https://github.com/vaadin/web-components/pull/6011
The [`getBodyRowCells`](https://github.com/vaadin/web-components/blob/0061f02f6ac82397481cd5e821d58032b19cc12f/packages/grid/src/vaadin-grid-helpers.js#L12) grid helper gets called *a lot* during init and especially while scrolling.
This PR makes grid cache the body row cells when they're being created. The cached references can then be passed as such from the `getBodyRowCells` helper instead of having to perform excess [computation](https://github.com/vaadin/web-components/blob/0061f02f6ac82397481cd5e821d58032b19cc12f/packages/grid/src/vaadin-grid-helpers.js#L17-L19) or [querying](https://github.com/vaadin/web-components/blob/0061f02f6ac82397481cd5e821d58032b19cc12f/packages/grid/src/vaadin-grid-helpers.js#L42) for the …
=> refactor: cache body row cells

packages/side-nav/src/vaadin-side-nav-item.d.ts, packages/side-nav/src/vaadin-side-nav-item.js, packages/side-nav/src/vaadin-side-nav.d.ts, packages/side-nav/src/vaadin-side-nav.js
While I added shadow parts in #6002, I missed to add state attributes. This PR fixes that.
=> docs: add side-nav and side-nav-item state attributes

packages/grid/src/vaadin-grid-scroll-mixin.js, packages/grid/src/vaadin-grid.js, packages/grid/test/scroll-restoration.test.js
In Firefox, when switching the visibility between two grids, the browser tries to restore the scroll position of the grid that was made visible again, which results in some issues: the scroll position for the first grid always being reset to zero, and the scroll position of the second grid is being synchronized to the scroll position of the first grid.
This change adds a manual scroll position restoration specifically for Firefox, which memorizes the scroll position when the user scrolls, and then restores the last memorized position when a grid is made visible again.
Fixes https://github.com/vaadin/web-components/issues/5796
- Bugfix
=> fix: manually restore scroll position for grid in Firefox

packages/grid/src/vaadin-grid-scroll-mixin.js, packages/grid/test/scroll-restoration.test.js
=> fix: manually restore scroll position for grid in Firefox (#6022) (CP: 23.3)

packages/grid/src/vaadin-grid-scroll-mixin.js, packages/grid/test/scroll-restoration.test.js
=> fix: manually restore scroll position for grid in Firefox (#6022) (CP: 24.0)

packages/side-nav/theme/lumo/vaadin-side-nav-item-styles.js
Fixes #5915
Changed links with `href` attribute to use `cursor: pointer` as suggested in the issue.
Note, `<a>` elements without `href` are still using `var(--lumo-clickable-cursor)`.
- Bugfix
=> fix: use pointer cursor for vaadin-side-nav-item links

packages/side-nav/src/vaadin-side-nav-base-styles.js, packages/side-nav/theme/lumo/vaadin-side-nav-item-styles.js
Updated the `toggle-button` part of the `vaadin-side-nav-item` to use the Lumo button mixin.
Note, `width` and `height` are still needed because the icon size has to be 30px, not 24px.
- Refactor
=> refactor: cleanup side-nav item toggle styles, use mixin

packages/side-nav/src/vaadin-side-nav-children-controller.d.ts, packages/side-nav/src/vaadin-side-nav-children-controller.js, packages/side-nav/src/vaadin-side-nav-item.js
This controller might be used by `vaadin-side-nav`, e.g. it will be needed in #6014 to propagate `i18n` to items.
- Refactor
=> refactor: extract ChildrenController to separate file

packages/tooltip/src/vaadin-tooltip.js, packages/tooltip/test/tooltip-timers.test.js
It seems that individual tooltip timer tests can cause the global tooltip warmup/cooldown state get stuck, so that for subsequent tests the tooltip is identified as warmed up and shown immediately.
This adds an internal function for resetting the tooltip state and uses that for tearing down tests.
This should fix the following flaky test:
```
packages/tooltip/test/tooltip-timers.test.js:
❌ timers > warmup and cooldown > should not open on mouseleave during the initial warm up hover delay
AssertionError: expected true to be falsy
at o.<anonymous> (packages/tooltip/test/tooltip-timers.test.js:527:43)
```
=> test: properly reset global tooltip state

packages/overlay/src/vaadin-overlay.d.ts, packages/overlay/src/vaadin-overlay.js
Added missing `@mixes` annotation for `OverlayStackMixin` and updated `.d.ts` file accordingly.
=> docs: fix vaadin-overlay mixins types, add missing JSDoc

.github/workflows/visual-tests.yml
Use the `nick-fields/retry` Github Action to automatically re-try failed visual tests. The action is configured with:
- Max attempts: 3
- Timeout per attempt: 5 mins
- Wait between attempts: 60 seconds
Below is an example log of the action. I intentionally changed a CSS property in `vaadin-avatar` so that tests would fail. However right in the first two attempts it runs into timeout errors with SauceLabs, showcasing how the retry action is useful:
- In the first attempt the retry action stops the attempt after 5 mins as that is the configured timeout for the action
- In the second attempt only some tests time out, others complete - the attempt still fails as not all tests were run
- In the third attempt all tests are run, some of them failing due to the changed CSS property. After the …
=> test: automatically retry visual tests in CI

packages/email-field/src/vaadin-email-field.js, packages/email-field/src/vaadin-lit-email-field.js, packages/email-field/test/email-field.common.js, packages/field-base/test/pattern-mixin.test.js
According to https://bugs.chromium.org/p/chromium/issues/detail?id=1412729#c55, Chrome changed the way how Regex are interpreted, which now requires to escape certain characters in character groups.
Fixes https://github.com/vaadin/web-components/issues/5959
Fixes https://github.com/vaadin/web-components/issues/5938
- Bugfix
=> fix: properly escape email pattern

.github/workflows/visual-tests.yml
When making a change that affects a lot of packages (e.g. to `components-base`), then visual tests take a lot longer than 5 minutes. This increases the timeout to 20 minutes.
=> test: increase visual test workflow timeout

packages/crud/src/vaadin-crud-grid.js, packages/crud/src/vaadin-crud.js, packages/crud/test/a11y.test.js, packages/grid/src/vaadin-grid.js
https://github.com/vaadin/web-components/pull/5898 introduced a regression by adding several methods to `vaadin-crud-grid`, which are not available when using a slotted grid, causing runtime errors. This change moves the methods to `vaadin-grid` and extends the focus restoration tests to cover slotted grids.
Fixes https://github.com/vaadin/web-components/issues/6036
- Bugfix
=> fix: make focus restoration work with slotted grid

packages/side-nav/src/vaadin-side-nav-item.d.ts, packages/side-nav/src/vaadin-side-nav-item.js, packages/side-nav/test/dom/__snapshots__/side-nav-item.test.snap.js, packages/side-nav/test/dom/side-nav-item.test.js, packages/side-nav/test/side-nav-item.test.js, packages/side-nav/test/typings/side-nav.types.ts, packages/side-nav/theme/lumo/vaadin-side-nav-item-styles.js
Closes #5963
Renamed `active` to `current` so that we could use `active` attribute for styling an item pressed by mouse.
This would make API aligned with other clickable components e.g. `vaadin-item`, `vaadin-button` etc.
=> refactor!: rename side-nav item active property to current

packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/test/basic.test.js, packages/combo-box/test/external-filtering.test.js, packages/combo-box/test/keyboard.test.js, packages/combo-box/test/lazy-loading.test.js, packages/combo-box/test/scrolling.test.js, packages/time-picker/test/combo-box.test.js, packages/time-picker/test/time-picker.test.js
CP from #6055
There are more changes here because some functions/imports needed to be deleted after some tests were removed in the original PR as they were not being used anymore.
=> fix!: don't focus selected item on combo-box open (#6055) (CP: 23.3)

packages/side-nav/src/vaadin-side-nav-base-styles.js, packages/side-nav/theme/lumo/vaadin-side-nav-item-styles.js
1. Moved some CSS from Lumo theme to `src` as it will be needed for the Material theme,
2. Removed no longer used `position: relative` from the `<a>` element without `href`,
3. Added missing `:host([hidden])` CSS to the `<vaadin-side-nav-item>` base styles.
- Refactor
=> refactor: extend side-nav item src styles, add hidden attribute

packages/a11y-base/src/delegate-focus-mixin.js, packages/a11y-base/test/delegate-focus-mixin.test.js
The PR ensures that `setFocused()` of `DelegateFocusMixin` is only invoked when the focus event is triggered by `focusElement`. Components can have multiple focusable elements, e.g. an input element and a custom button in a suffix slot. Previously, `setFocused(false)` could be also invoked on a focusout triggered by an element other the `focusElement`, which led to unexpected validation in certain components.
Fixes https://github.com/vaadin/flow-components/issues/5136
=> fix: invoke setFocused only on events triggered by focusElement

packages/side-nav/src/vaadin-side-nav-children-mixin.d.ts, packages/side-nav/src/vaadin-side-nav-item.js, packages/side-nav/test/navigation.test.js
Fixes https://github.com/vaadin/flow-components/issues/5092
1. Updated the logic to only set `this.current` when the item actually has children (instead of `true`).
2. Added some basic navigation tests to cover the `popstate` logic (that was previously not tested).
- Bugfix
=> fix: set expanded attribute correctly, add navigation unit tests

packages/side-nav/src/vaadin-side-nav-item.js, packages/side-nav/test/dom/__snapshots__/side-nav-item.test.snap.js
This PR removes unused attribute `child-current` from side nav item.
=> refactor: remove unused attribute from side nav item

packages/side-nav/src/vaadin-side-nav-item.d.ts, packages/side-nav/src/vaadin-side-nav-item.js, packages/side-nav/test/dom/__snapshots__/side-nav-item.test.snap.js, packages/side-nav/test/side-nav-item.test.js
This PR updates the type of `pathAliases` property to be a non-null array of strings.
=> refactor: use array for path aliases

integration/package.json, integration/tests/notification-tooltip.test.js, packages/tooltip/src/vaadin-tooltip-overlay.js
Currently tooltips are always shown below notifications:
- Tooltip overlays use a z-index of `200` via the default `vaadin-overlay` styles: https://github.com/vaadin/web-components/blob/90992ed3d323e723ffa2d42d896465bf770d866d/packages/overlay/src/vaadin-overlay.js#L85
- Notifications use a z-index of `1000`: https://github.com/vaadin/web-components/blob/90992ed3d323e723ffa2d42d896465bf770d866d/packages/notification/src/vaadin-notification.js#L30
This increases the z-index for tooltips to be larger than the one for notifications.
Fixes https://github.com/vaadin/web-components/issues/5748
- Bugfix
=> fix: display tooltips over notifications

packages/date-picker/test/helpers.js, packages/date-picker/test/validation.test.js
Improved date-picker tests to make them a bit more readable. Also, removed a few unused imports.
- Tests
=> test: make tests more readable, extract input variable

packages/component-base/src/slot-child-observe-controller.js, packages/field-base/test/field-mixin.test.js
Fixes #5648
The issue with not adding `aria-labelledby` was related to the fact that ID was not set on default `label`.
As it turned out, there was an incorrect check for `multiple` mode in `SlotChildObserveController`.
- Bugfix
Can be tested using the following code example (click the button and observe `input` attributes):
```html
<vaadin-text-field label="Default label"></vaadin-text-field>
<button>Remove label</button>
import '@vaadin/text-field';
const label = document.createElement('label');
label.id = 'custom-id';
label.textContent = 'Custom label';
label.setAttribute('slot', 'label');
document.querySelector('vaadin-text-field').appendChild(label);
const button = document.querySelector('button');
button.addEventListener('click', () => {
label.remove();
}); …
```
=> fix: update aria-labelledby when restoring default label

packages/side-nav/src/vaadin-side-nav-item.js, packages/side-nav/test/dom/__snapshots__/side-nav-item.test.snap.js
Currently, `vaadin-side-nav` sets `aria-hidden` on the `<ul>` element, but `vaadin-side-nav-item` does not:
https://github.com/vaadin/web-components/blob/b8378bd2267728e172012bcb2ea45c3e5a6e590a/packages/side-nav/src/vaadin-side-nav.js#L160
https://github.com/vaadin/web-components/blob/b8378bd2267728e172012bcb2ea45c3e5a6e590a/packages/side-nav/src/vaadin-side-nav-item.js#L205
This PR aligns the DOM structure to add missing `aria-hidden` attribute depending on the `expanded` property.
- Refactor
=> refactor: set aria-hidden on the side-nav-item nested list

packages/overlay/test/focus-trap.test.js, packages/overlay/test/multiple.test.js, packages/overlay/test/restore-focus.test.js
Some adjustments to `vaadni-overlay` unit tests with adding missing `await` based on my Lit conversion research:
- `focus-trap.test.js`
- `multiple.test.js`
- `restore-focus.test.js`
- Tests
=> test: add missing await to vaadin-overlay unit tests

packages/app-layout/src/vaadin-app-layout.js, packages/app-layout/test/app-layout.test.js
Fixes #5123
Added a flag to distinguish the resize caused by drawer click and to prevent disabling animation in this case.
- Bugfix
=> fix: animate primary drawer open and close transition

packages/grid/src/vaadin-grid-data-provider-mixin.js
It turns out that the grid items has been internally stored as an object. This traces back to the early stages of the grid. While there seems to be no significant performance difference between objects and arrays in JS, objects lack such methods as `push`, `splice`, etc, which it could be good to have in some situations. In general, I believe it would be more natural for the items to be an array since they are ordered.
=> refactor: store items as an array instead of an object

packages/combo-box/src/vaadin-combo-box-light.js
It seems unnecessary to clear `combo-box-light` on change events generated by the clear button, as clearing already happens on clear button click. 
For the record, the related change handler was introduced during the slotted input refactoring ([link](https://github.com/vaadin/web-components/commit/f5c2ec5f4fd36bb1fd6cee372382099ddf30d9b7#diff-7b3209e8e6ef17cdad592230144268dfec125c16d28f8d39878ab92224bcd223R185-R191)) and, apparently, it became redundant at some point later.
=> refactor: do not clear combo-box-light on change from clear button

packages/side-nav/src/vaadin-side-nav-base-styles.js
These styles are there since the [first iteration](https://github.com/vaadin/vcf-nav/commit/92256a9a3ace52a242accd7b6d07b926d3289ddb) of `vcf-nav` and they aren't used anywhere e.g. by Lumo theme.
Note, we do need `::before` pseudo element for the arrow icon, but the `::after` element is unused.
- Refactor
=> refactor: cleanup no longer used pseudo element styles

packages/grid/src/vaadin-grid-data-provider-mixin.js
The PR aims to simplify `DataProviderMixin` of the grid component by changing it to use the `splice()` method for adding items to a cache, instead of adding them one by one. This will align the implementation with the combo-box:
https://github.com/vaadin/web-components/blob/facf47bd7d91dbee72b873adb41930c899706099/packages/combo-box/src/vaadin-combo-box-data-provider-mixin.js#L185-L187
Note, the `splice()` method has a limitation on the max number of items you can add in one batch, which is approximately 100 000. However, such large page sizes seem unlikely, especially considering that they will result in significant performance degradation.
Depends on 
- https://github.com/vaadin/web-components/pull/6093
=> refactor: use splice() instead of adding items one by one

packages/menu-bar/src/vaadin-menu-bar-mixin.js, packages/menu-bar/test/menu-bar.test.js
Fixes #4683
Added logic to check if there is at least one `vaadin-menu-bar-button` with `tabindex="0"` and if not, set the attribute.
- Bugfix
=> fix: set tabindex on remaining button after updating overflow

packages/app-layout/src/vaadin-app-layout.js, packages/app-layout/test/app-layout.test.js
Extracts part of the changes done in #5831.
Make the `keydown` listener originally added to the `<div part="drawer" />` element become global by adding it to the `window` object, so the drawer can be closed with <kbd>Esc</kbd> in case the focus moves out it.
Part of #123
=> refator: move Esc  keydown listener to window

packages/field-base/src/clear-button-mixin.js, packages/field-base/test/clear-button-mixin.test.js, packages/field-base/test/input-control-mixin.test.js
Make the behavior of clicking the clear button to be aligned with how `<vaadin-combo-box>` works.
This change:
- adds a `touchstart` listener that prevent default, and clears the input element, **BUT** does not focus it
- adds a `mousedown` listener that prevents default, focuses the input element, **AND** clears it
- keep a click listener that does the same `mousedown` behavior, mostly used for programmatic clicks on the button
These changes also fix the issue described in https://github.com/vaadin/flow-components/issues/5137, since it prevents the `focusout` event and the editor won't close after clicking the clear button.
Fixes #4130
Part of https://github.com/vaadin/flow-components/issues/5137
=> fix!: align how clear button works with combo box behavior

packages/date-picker/test/basic.test.js, packages/date-picker/test/events.test.js, packages/date-picker/test/validation.test.js, packages/date-time-picker/test/basic.test.js
This PR adds missing `await` after `setInputValue` (which actually opens the overlay) to avoid these warnings:
```
packages/date-picker/test/validation.test.js:
Error: [object HTMLInputElement] is not contained inside [object HTMLBodyElement]. Skip setting aria-hidden.
Error: [object HTMLInputElement] is not contained inside [object HTMLBodyElement]. Skip setting aria-hidden.
Error: [object HTMLInputElement] is not contained inside [object HTMLBodyElement]. Skip setting aria-hidden.
Error: [object HTMLElement] is not contained inside [object HTMLBodyElement]. Skip …
```
=> test: add missing await to prevent aria-hidden warnings

packages/overlay/test/animated-styles.js, packages/overlay/test/animations.test.js
1. Updated `animation.test.js` and added some missing `await` in preparation for Lit conversion;
2. Moved styles to separate file to make sure they are registered before custom element is defined.
- Tests
=> test: update overlay animation tests, add missing await

.stylelintrc, package.json, packages/context-menu/theme/lumo/vaadin-context-menu-overlay-styles.js, packages/date-picker/theme/material/vaadin-date-picker-overlay-styles.js, packages/select/theme/lumo/vaadin-select-styles.js, yarn.lock
There's a new release of Stylelint, let's consider upgrading to it. We'll also need a new config 😅 
```
$ stylelint packages/**/src/*.js packages/**/theme/**/*-styles.js
Deprecation warnings:
- The "at-rule-name-case" rule is deprecated.
- The "at-rule-name-newline-after" rule is deprecated.
- The "at-rule-semicolon-space-before" rule is deprecated.
- The "at-rule-name-space-after" rule is deprecated.
- The "at-rule-semicolon-newline-after" rule is deprecated.
- The "block-closing-brace-empty-line-before" rule is deprecated.
- The "block-closing-brace-newline-after" rule is deprecated.
- The "block-closing-brace-newline-before" rule is deprecated.
- The "block-closing-brace-space-after" rule is deprecated.
- The "block-closing-brace-space-before" rule is deprecated.
- The …
```
=> chore: update Stylelint to 15.0, deduplicate yarn.lock

packages/overlay/src/vaadin-overlay-styles.js, packages/overlay/src/vaadin-overlay.js
Moved the `vaadin-overlay` styles from its `<template>` to the reusable `css` literal. 
This will make Lit conversion easier and allow us to decouple overlay extensions.
- Refactor
=> refactor: extract overlay base styles to reusable css literal

packages/date-picker/test/basic.test.js, packages/date-picker/test/events.test.js, packages/date-picker/test/validation.test.js, packages/date-time-picker/test/basic.test.js
Manual cherry-pick of #6119 to `24.1` branch. The merge conflict was caused by renamed variable in some tests.
- Cherry-pick
=> test: add missing await to prevent aria-hidden warnings (#6119) (CP: 24.1)

packages/field-base/src/input-control-mixin.js, packages/field-base/test/input-control-mixin.test.js
CP from #6100.
I had to manually copy the changes because the `clear-button-mixin` was introduced after V23.
=> fix!: align how clear button works with combo-box behavior (#6100) (CP: 23.3)

packages/grid/src/vaadin-grid-data-provider-mixin.js
Reverts #6092. 
This change caused quite a lot of test failures on the Flow component side, which requires more thorough investigation.
=> Revert "refactor: use splice() instead of adding items one by one (#6092)"

packages/combo-box/src/vaadin-combo-box-overlay.d.ts, packages/combo-box/src/vaadin-combo-box-overlay.js, packages/combo-box/theme/lumo/vaadin-combo-box-overlay-styles.js, packages/combo-box/theme/material/vaadin-combo-box-overlay-styles.js
Fixes #1697
Part of #5718
Updated `vaadin-combo-box-overlay` to use `OverlayMixin` and styles exposed as `css` literal.
At the same time, this component no longer imports `vaadin-overlay` so it doesn't get defined.
- Refactor
=> refactor!: update combo-box overlay to not extend vaadin-overlay

packages/date-picker/src/vaadin-date-picker-overlay.js, packages/date-picker/theme/lumo/vaadin-date-picker-overlay-styles.js, packages/date-picker/theme/material/vaadin-date-picker-overlay-styles.js
Part of #5718
Updated `vaadin-date-picker-overlay` to use `OverlayMixin` and styles exposed as `css` literal.
At the same time, this component no longer imports `vaadin-overlay` so it doesn't get defined.
- Refactor
=> refactor!: update date-picker overlay to not extend vaadin-overlay

packages/time-picker/src/vaadin-time-picker-overlay.d.ts, packages/time-picker/src/vaadin-time-picker-overlay.js, packages/time-picker/theme/lumo/vaadin-time-picker.js, packages/time-picker/theme/material/vaadin-time-picker.js
Part of #5718
Updated `vaadin-time-picker-overlay` to use `OverlayMixin` and styles exposed as `css` literal.
At the same time, this component no longer imports `vaadin-overlay` so it doesn't get defined.
- Refactor
=> refactor!: update time-picker overlay to not extend vaadin-overlay

packages/select/src/vaadin-select-overlay.js, packages/select/theme/lumo/vaadin-select.js, packages/select/theme/material/vaadin-select.js
Part of #5718
Updated `vaadin-select-overlay` to use `OverlayMixin` and styles exposed as `css` literal.
- Refactor
=> refactor!: update select overlay to not extend vaadin-overlay

packages/crud/src/vaadin-crud-dialog.js, packages/crud/theme/lumo/vaadin-crud-styles.js, packages/crud/theme/material/vaadin-crud-styles.js
Part of #5718
Same as #6141 but for `vaadin-crud`.
Updated `vaadin-crud-dialog-overlay` to use `OverlayMixin` and styles exposed as `css` literal.
- Refactor
=> refactor!: update crud dialog overlay to not extend dialog overlay

packages/grid/src/vaadin-grid-selection-column-base-mixin.d.ts, packages/grid/src/vaadin-grid-selection-column-base-mixin.js, packages/grid/src/vaadin-grid-selection-column.d.ts, packages/grid/src/vaadin-grid-selection-column.js, packages/grid/test/typings/grid.types.ts
Extracts a mixin with basic grid selection column functionality in order to reuse common logic in the custom column element of the Flow component, and to be able to reuse the upcoming lasso selection feature. The common functionality mostly includes property definitions and column rendering logic. The mixin provides protected methods that need to be implemented by the respective column elements in order to change the selection state.
The respective changes for the Flow component can be found here: https://github.com/vaadin/flow-components/compare/main...refactor/grid_selection_column_reuse
As for the upcoming lasso selection feature, in order to reuse that in the Flow component, it could either be implemented in the new base mixin, or in a separate mixin class (preferrable IMO).
Part of …
=> refactor: extract grid selection column base mixin

packages/confirm-dialog/test/confirm-dialog.test.js
Updated `vaadin-confirm-dialog` unit tests to pass with `lit/dialog` branch where the LitElement version is prototyped.
- Tests
=> test: update confirm-dialog tests, add missing await

packages/context-menu/src/vaadin-context-menu-overlay.js, packages/context-menu/theme/lumo/vaadin-context-menu.js, packages/context-menu/theme/material/vaadin-context-menu.js
Part of #5718
Updated `vaadin-context-menu-overlay` to use `OverlayMixin` and styles exposed as `css` literal.
- Refactor
=> refactor!: update context-menu overlay to not extend vaadin-overlay

packages/password-field/src/vaadin-password-field.js, packages/password-field/test/password-field.test.js
Fixes https://github.com/vaadin/flow-components/issues/4932
Currently, preventing `touchend` also causes the `focusout` to be prevented and that suppresses `change` event.
This PR fixes that by storing a value at the moment of the last `change` event and dispatching `change` manually. 
- Bugfix
=> fix: ensure change event is fired on blur after prevented mousedown

packages/password-field/src/vaadin-password-field.js, packages/password-field/test/password-field.test.js
Manual cherry-pick of #6150 to the `23.3` branch. There was a merge conflict due to `constructor()` ordering.
- Cherry-pick
=> fix: dispatch change event on blur after prevented mousedown (#6150) (CP: 23.3)

packages/a11y-base/test/list-mixin.test.js, packages/component-base/test/delegate-state-mixin.test.js, packages/component-base/test/dir-mixin.test.js, packages/component-base/test/overlay-class-mixin.test.js, packages/field-base/test/clear-button-mixin.test.js, packages/field-base/test/field-mixin.test.js, packages/field-base/test/input-constraints-mixin.test.js, packages/field-base/test/input-control-mixin.test.js, packages/field-base/test/input-field-mixin.test.js, packages/field-base/test/input-mixin.test.js, packages/field-base/test/label-mixin.test.js, packages/field-base/test/pattern-mixin.test.js, packages/field-base/test/validate-mixin.test.js
Updated tests for mixins to replace `nextFrame()` with `nextUpdate()` where it makes sense.
Otherwise changed to use `nextRender()` - especially for tests with DOM manipulation.
- Tests
=> test: update mixins tests to use nextUpdate helper

packages/dialog/test/dialog.test.js, packages/dialog/test/draggable-resizable.test.js, packages/dialog/test/header-footer.test.js, packages/dialog/test/renderer.test.js
Added missing `await` to ensure property updates are correctly handled with Lit.
Check out [`lit/dialog`](https://github.com/vaadin/web-components/compare/lit/dialog) branch for the actual implementation  using LitElement.
- Tests
=> test: update dialog tests to pass with the Lit based version

packages/combo-box/test/validation.test.js
- Extracted the "required" tests into an individual test suite.
- Added a test to verify that `combo-box` validates on blur.
Part of #6146
=> test: restructure validation tests, improve test coverage

packages/crud/test/dom/__snapshots__/crud.test.snap.js, packages/crud/test/dom/crud.test.js
Turns out `nextFrame()` isn't enough for `vaadin-crud` to finish rendering, so I updated the test to use `nextRender()`.
- Tests
=> test: update CRUD snapshot tests to use nextRender helper

packages/combo-box/src/vaadin-combo-box-light.d.ts, packages/combo-box/src/vaadin-combo-box-light.js, packages/combo-box/src/vaadin-combo-box-mixin.d.ts, packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/src/vaadin-combo-box.js, packages/combo-box/test/combo-box-light-validation.test.js, packages/combo-box/test/lazy-loading.test.js, packages/combo-box/test/validation.test.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js
Fixes an issue where `<combo-box required>` didn't get invalidated after entering an invalid value and subsequently clicking outside. The issue occurred because `combo-box` triggered validation before reverting user input and from the perspective of the HTML constraint validation, it appeared as if `combo-box` had a value.
Along the way, the PR fixes `combo-box-light` not getting validated on blur and also adds the `focused` attribute for it.
Fixes https://github.com/vaadin/web-components/issues/6164
=> fix: ensure user input is reverted before validation on blur

packages/crud/src/vaadin-crud.js, packages/crud/test/a11y.test.js
This PR fixes an issue introduced in https://github.com/vaadin/web-components/pull/3108 where I incorrectly used two different names: `__editorAriaLabel` as a property passed in the template, and `__dialogAriaLabel` as a property storing the actual label. From now on, a single property will be used.
- Bugfix
=> fix: use correct property to set CRUD dialog aria-label

packages/crud/src/vaadin-crud-dialog.js, packages/crud/src/vaadin-crud.js
Extracted from #6162
This change is needed to get the component work with Lit, where nested elements aren't yet rendered by the time when the observer is called. In this case, `fullscreen` property is passed to `vaadin-crud-dialog` instead of accessing its DOM.
Also, I updated internal elements of `vaadin-crud` to use `static get is()` as we do that in other components.
- Refactor
=> refactor: pass fullscreen property to vaadin-crud overlay

packages/dialog/src/vaadin-dialog-base-mixin.d.ts, packages/dialog/src/vaadin-dialog-base-mixin.js, packages/dialog/src/vaadin-dialog.d.ts, packages/dialog/src/vaadin-dialog.js
Currently, converting `vaadin-dialog` and depending components to LitElement is a bit complicated.
This PR aims to decouple extensions e.g. to make `vaadin-crud-dialog` still on Polymer for now.
We could achieve that by not extending `vaadin-dialog` and using `DialogBaseMixin` instead.
- Refactor
=> refactor: extract basic dialog logic to separate mixin

packages/confirm-dialog/src/vaadin-confirm-dialog-overlay.js
Depends on #6165
Updated `vaadin-confirm-dialog` to not extend `vaadin-dialog` internally and use `DialogBaseMixin`.
This change enables us to convert these two components to Lit independently from each other.
- Refactor
=> refactor: update confirm-dialog to not use dialog extension

packages/grid/src/vaadin-grid-column.d.ts, packages/grid/src/vaadin-grid-column.js, packages/grid/test/accessibility.test.js, packages/grid/test/column.test.js, packages/grid/test/typings/grid.types.ts
I had an older [PR](https://github.com/vaadin/web-components/pull/5843), which was fulfilling an older version of Acceptance Criteria (https://github.com/vaadin/web-components/issues/5321). 
Through the PR review and testing (thanks to  @tomivirkki ). Tomi find out that this approach is not working properly for Safari VoiceOver, also we found out that it was creating a different (bold) style for the marked cells (which could cause further problems, more info in the previous PR)
Then we had chats and **discussions** with **@rolfsmeds, and @tomivirkki** (after Tomi thorough testing it as well), and we settled that the new approach is to only use  `role="rowheader"`
- The new Acceptance Criteria ( https://github.com/vaadin/web-components/issues/5321) is describing the new idea.
- The other …
=> feat: add rowHeader property to vaadin-grid-column for screen readers

packages/crud/src/vaadin-crud-dialog.js
Depends on #6165
Same as #6166 but for `vaadin-crud`.
Updated `vaadin-crud-dialog` to not extend `vaadin-dialog` internally and use `DialogBaseMixin`.
This change enables us to convert these two components to Lit independently from each other.
- Refactor
=> refactor: update crud-dialog to not use dialog extension

packages/avatar-group/src/vaadin-avatar-group-overlay.js, packages/avatar-group/theme/lumo/vaadin-avatar-group.js, packages/avatar-group/theme/material/vaadin-avatar-group.js
Part of #5718
Updated `vaadin-avatar-group-overlay` to use `OverlayMixin` and styles exposed as `css` literal.
- Refactor
=> refactor!: update avatar-group overlay to not extend vaadin-overlay

packages/avatar/test/avatar.test.js
Adds necessary awaits so that avatar tests will pass with a Lit version of the component.
Also includes the removal of a test, as mentioned in #6181
=> test: make avatar tests wait for updates

packages/avatar/package.json, packages/avatar/src/vaadin-avatar.d.ts, packages/avatar/src/vaadin-lit-avatar.d.ts, packages/avatar/src/vaadin-lit-avatar.js, packages/avatar/test/avatar-lit.test.js, packages/avatar/test/avatar-polymer.test.js, packages/avatar/test/avatar.common.js
Adds a `LitElement` based version of `vaadin-avatar`.
**Disclaimer:** This is considered an experiment that is not published to NPM, there is no ETA in which version it will be shipped.
- Experiment
=> experiment: add LitElement based version of vaadin-avatar

packages/dialog/src/vaadin-dialog-overlay-mixin.d.ts, packages/dialog/src/vaadin-dialog-overlay-mixin.js, packages/dialog/src/vaadin-dialog-overlay.d.ts, packages/dialog/src/vaadin-dialog-overlay.js
Part of #5718
Pre-requisite for #6183
1. Changed `vaadin-dialog-overlay` to not extend `Overlay` and use `OverlayMixin` instead,
2. Moved logic to `DialogOverlayMixin` so that we can create a LitElement based version.
- Refactor
=> refactor: restructure dialog overlay, extract logic to mixin

integration/tests/dialog-accordion.test.js, integration/tests/dialog-combo-box.test.js, integration/tests/dialog-grid-pro.test.js, integration/tests/dialog-template.test.js, packages/dialog/test/visual/lumo/dialog.test.js, packages/dialog/test/visual/material/dialog.test.js
Extracted from #6183
Updated visual tests and integration tests to pass with LitElement based version of `vaadin-dialog`.
- Tests
=> test: update dialog visual and integration tests to use await

packages/dialog/src/vaadin-dialog-overlay-mixin.d.ts, packages/dialog/src/vaadin-dialog-overlay.d.ts
See https://github.com/vaadin/web-components/pull/6187#discussion_r1266763947
- Refactor
=> refactor: move setBounds() and getBounds() types to the mixin

packages/dialog/package.json, packages/dialog/src/vaadin-dialog-draggable-mixin.js, packages/dialog/src/vaadin-dialog-resizable-mixin.js, packages/dialog/src/vaadin-lit-dialog-overlay.d.ts, packages/dialog/src/vaadin-lit-dialog-overlay.js, packages/dialog/src/vaadin-lit-dialog.d.ts, packages/dialog/src/vaadin-lit-dialog.js, packages/dialog/test/dialog-lit.test.js, packages/dialog/test/dialog-polymer.test.js, packages/dialog/test/dialog.common.js, packages/dialog/test/draggable-resizable-lit.test.js, packages/dialog/test/draggable-resizable-polymer.test.js, packages/dialog/test/draggable-resizable.common.js, packages/dialog/test/header-footer-lit.test.js, packages/dialog/test/header-footer-polymer.test.js, packages/dialog/test/header-footer.common.js, packages/dialog/test/lit-renderer-directives-lit.test.js, packages/dialog/test/lit-renderer-directives-polymer.test.js, packages/dialog/test/lit-renderer-directives.common.js, packages/dialog/test/renderer-lit.test.js, packages/dialog/test/renderer-polymer.test.js, packages/dialog/test/renderer.common.js
Added a `LitElement` based version of `vaadin-dialog`.
- Experiment
This is considered an experiment that is not published to npm, there is no ETA in which version it will be shipped.
=> experiment: add LitElement based version of vaadin-dialog

packages/combo-box/src/vaadin-combo-box-light.js, packages/combo-box/src/vaadin-combo-box-mixin.d.ts, packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/src/vaadin-combo-box.js, packages/combo-box/test/combo-box-light-validation.test.js, packages/combo-box/test/validation.test.js
The PR ensures combo-box's validation is triggered before the `change` event, aligning it with the behavior of other field components. Additionally, this fixes another bug where validation wasn't run at all when pressing Enter or clicking the clear button, despite a change event being fired immediately in that case.
A follow-up to https://github.com/vaadin/web-components/issues/6164
Part of https://github.com/vaadin/web-components/issues/6146
=> fix: ensure validation is triggered before change event

packages/combo-box/src/vaadin-combo-box-light.js, packages/combo-box/src/vaadin-combo-box-mixin.d.ts, packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/src/vaadin-combo-box.js, packages/combo-box/test/combo-box-light-validation.test.js, packages/combo-box/test/validation.test.js, packages/time-picker/src/vaadin-time-picker.js, packages/time-picker/test/validation.test.js
The PR refactors `time-picker` to prevent duplicate validation when blurring with an uncommitted value.
Depends on
- https://github.com/vaadin/web-components/pull/6180
Part of https://github.com/vaadin/web-components/issues/6146
=> fix: prevent duplicate validation on blur
