vaadin/web-components

.github/workflows/chrome.yml
.github/workflows/firefox.yml
.github/workflows/webkit.yml
README.md
web-test-runner-firefox.config.js
web-test-runner-webkit.config.js
web-test-runner.config.js
wtr-utils.js

Run tests for packages changed since master

---

scripts/updateVersion.js

Same as https://github.com/vaadin/magi-cli/pull/132

Improve regex for version update script

---

packages/vaadin-details/src/vaadin-details.js
packages/vaadin-details/test/details.test.js

- Add `aria-controls` attr to toggle button
- Change content part to `<section>` element
- Add `id` attr to content part
- Add `aria-controls` and id attr tests
Fixes vaadin/vaadin-details#38

A11y Improvements

---

packages/vaadin-app-layout/vaadin-app-layout.d.ts
packages/vaadin-charts/src/vaadin-chart-series.d.ts
packages/vaadin-cookie-consent/vaadin-cookie-consent.d.ts

Hotfix for a problem mentioned in #181

fix: update incorrect imports in typings

---

packages/vaadin-app-layout/src/vaadin-app-layout.d.ts
packages/vaadin-app-layout/src/vaadin-app-layout.js
packages/vaadin-app-layout/test/app-layout.test.js

Fixes vaadin/vaadin-app-layout#140

Close the drawer when in overlay mode and a Vaadin router navigation happens

---

README.md

I missed to document this part while creating the actual visual tests 😞

chore: document visual tests in README

---

packages/vaadin-messages/README.md

Same PR as https://github.com/vaadin/vaadin-messages/pull/69/

Fix: Update README demo and API links in vaadin-messages

---

packages/vaadin-grid/src/vaadin-grid-data-provider-mixin.js
packages/vaadin-grid/src/vaadin-grid-row-details-mixin.js
packages/vaadin-grid/src/vaadin-grid-selection-mixin.js
packages/vaadin-grid/test/selection.test.js
packages/vaadin-list-mixin/vaadin-multi-select-list-mixin.js
packages/vaadin-upload/src/vaadin-upload.js

Fixes https://github.com/vaadin/web-components/issues/197

fix!: remove internal polymer array mutation use

---

README.md

As discussed internally, I documented the steps needed to bump a new major in the monorepo.

chore: document bumping a new major

---

packages/vaadin-combo-box/test/visual/lumo/combo-box.test.js
packages/vaadin-combo-box/test/visual/material/combo-box.test.js
packages/vaadin-confirm-dialog/test/visual/lumo/confirm-dialog.test.js
packages/vaadin-confirm-dialog/test/visual/material/confirm-dialog.test.js
packages/vaadin-context-menu/test/visual/lumo/context-menu.test.js
packages/vaadin-context-menu/test/visual/material/context-menu.test.js
packages/vaadin-date-picker/test/visual/lumo/date-picker.test.js
packages/vaadin-date-picker/test/visual/material/date-picker.test.js
packages/vaadin-grid-pro/test/visual/lumo/grid-pro.test.js
packages/vaadin-grid-pro/test/visual/material/grid-pro.test.js
packages/vaadin-menu-bar/test/visual/lumo/menu-bar.test.js
packages/vaadin-menu-bar/test/visual/material/menu-bar.test.js

Added the existing style modules for disabling animations in tests to the visual tests. This hopefully removes some of the "flakiness" in the visual tests.

test: disable animations in visual tests

---

packages/vaadin-messages/src/vaadin-message-list.d.ts
packages/vaadin-messages/src/vaadin-message-list.js

The docs of this property seemed incorrect, probably because of some copy-paste mistake.

fix: vaadin-message-list items property docs

---

packages/vaadin-messages/src/vaadin-message-list.d.ts
packages/vaadin-messages/src/vaadin-message-list.js
packages/vaadin-messages/test/message-list.test.js

This is the first step towards highlighting your own messages:
https://github.com/vaadin/collaboration-engine/issues/30

feat: add theme property to vaadin-message-list items

---

packages/vaadin-notification/src/vaadin-notification.js
packages/vaadin-notification/test/notification.test.js

This PR aims to address #380 in the `20.0` branch.
Fixes #380

fix: remove ID attribute from notification card (#380) (CP: 20.0)

---

packages/vaadin-combo-box/src/vaadin-combo-box-mixin.js
packages/vaadin-combo-box/test/lazy-loading.test.js
web-test-runner.config.js

cherry-pick: vaadin/vaadin-combo-box#1006
Fixes: vaadin/flow-components#915

fix: Make dataprovider filtering case-insensitive (#1007)

---

packages/vaadin-accordion/test/accordion.test.js
packages/vaadin-app-layout/test/app-layout.test.js
packages/vaadin-avatar/test/avatar-group.test.js
packages/vaadin-avatar/test/avatar.test.js
packages/vaadin-board/test/basic.test.js
packages/vaadin-button/test/button.test.js
packages/vaadin-charts/test/chart-element.test.js
packages/vaadin-confirm-dialog/test/confirm-dialog.test.js
packages/vaadin-cookie-consent/test/cookie-consent.test.js
packages/vaadin-date-time-picker/test/basic.test.js
packages/vaadin-details/test/details.test.js
packages/vaadin-dialog/test/dialog.test.js
packages/vaadin-item/test/item.test.js
packages/vaadin-login/test/login-form.test.js
packages/vaadin-menu-bar/test/menu-bar.test.js
packages/vaadin-messages/test/message-input.test.js
packages/vaadin-messages/test/message-list.test.js
packages/vaadin-messages/test/message.test.js
packages/vaadin-ordered-layout/test/horizontal-layout.js
packages/vaadin-ordered-layout/test/scroller.test.js
packages/vaadin-ordered-layout/test/vertical-layout.test.js
packages/vaadin-progress-bar/test/progress-bar.test.js
packages/vaadin-rich-text-editor/test/basic.test.js
packages/vaadin-tabs/test/tabs.test.js

Manual cherry-pick of #1999 to `20.0` branch.

test: fix version regex to allow RC (#1999) (CP: 20.0)

---

wtr-utils.js

Follow up from: #2074 
Filters also need to be applied if lockfile changed.

chore: fix test runner filtering when lockfile has changes

---

packages/vaadin-icon/src/vaadin-icon.js
packages/vaadin-icon/test/icon.test.js

fix: make icon inherit currentColor as the fill color

---

packages/vaadin-grid/src/vaadin-grid-styles.js
packages/vaadin-grid/src/vaadin-grid.d.ts
packages/vaadin-grid/src/vaadin-grid.js
packages/vaadin-grid/test/resizing.test.js

related to: vaadin/flow-components#1009

feat!: remove heightByRows property in favor of allRowsVisible

---

packages/vaadin-icon/src/vaadin-icon.js
packages/vaadin-icon/src/vaadin-iconset.js
packages/vaadin-icon/test/icon.test.js

Fixes https://github.com/vaadin/web-components/issues/2119

fix: re-apply icon once the set is registered

---

packages/vaadin-virtual-list/src/vaadin-virtual-list.d.ts
packages/vaadin-virtual-list/test/typings/virtual-list.types.ts

Make virtual list types generic
Closes https://github.com/vaadin/web-components/issues/405

feat: allow passing specific item type to virtual list types

---

packages/vaadin-lumo-styles/utilities/sizing.js

Request from Jonte to remove classes that do not work as intended. He might work on re-adding them when he has more time.

chore: remove Lumo utility classes not working as intended

---

packages/vaadin-avatar/src/vaadin-avatar.js

fix: Remove z-index from avatar color outline

---

packages/vaadin-combo-box/src/vaadin-combo-box-dropdown.js
packages/vaadin-combo-box/test/overlay-position.test.js

fix: horizontally align combo-box overlay

---

packages/vaadin-text-field/src/vaadin-text-area.js

The code was removed by #2143 but this part was still there. Let's remove it too.
- Refactor

chore: remove no longer needed check for Safari

---

README.md

Update README file with instructions for the next version bump.

chore: update README with instructions to bump to v23 [skip ci]

---

packages/field-base/test/input-field-mixin.test.js

Added missing test for https://github.com/vaadin/web-components/pull/2353/commits/e48ba7065f3160c8aeff57c37dde271c9ae505ab
- Tests

test: add missing test for value warning

---

packages/vaadin-menu-bar/src/vaadin-menu-bar-buttons-mixin.js

This was a leftover from an incorrect fix supposed to handle the review comment. The test will be added later.

fix: set disabled button properly

---

dev/button.html
dev/icon.html
package.json

chore: add a start script and dev pages

---

dev/combo-box.html

Adding a `dev` page to make it easier to develop combo-box.

chore: add a dev page for combo-box

---

packages/text-area/theme/lumo/vaadin-text-area-styles.js

Fixes typo in selector that was introduced in the recent refactoring.

chore: fix textarea iron-icon selector

---

scripts/generateReleaseNotes.js

- taken package without `vaadin-` prefix
- remove commit message body
- group the commit based on components
fixes #2378

chore: fix issues with the release notes script

---

packages/select/src/vaadin-select.d.ts
packages/select/test/typings/select.types.ts

This is a regression which wasn't noticed and covered by tests 😕  
- Bugfix

fix: update typings to use correct export

---

packages/vaadin-combo-box/test/aria.test.js
packages/vaadin-combo-box/test/basic.test.js
packages/vaadin-combo-box/test/combo-box-light.test.js
packages/vaadin-combo-box/test/dynamic-size.test.js
packages/vaadin-combo-box/test/filtering.test.js
packages/vaadin-combo-box/test/form-input.test.js
packages/vaadin-combo-box/test/helpers.js
packages/vaadin-combo-box/test/item-renderer.test.js
packages/vaadin-combo-box/test/item-template.test.js
packages/vaadin-combo-box/test/keyboard.test.js
packages/vaadin-combo-box/test/lazy-loading.test.js
packages/vaadin-combo-box/test/lit.test.js
packages/vaadin-combo-box/test/object-values.test.js
packages/vaadin-combo-box/test/overlay-position.test.js
packages/vaadin-combo-box/test/scrolling.test.js
packages/vaadin-combo-box/test/selecting-items.test.js
packages/vaadin-combo-box/test/toggling-dropdown.test.js

This PR aims to simplify reviewing the following combo-box PRs by updating most of the tests separately.
1. Moved all the new test helpers from #2467
2. Applied some other tweaks from #2293

test: refactor combo-box tests, add new helpers

---

index.html
packages/vaadin-combo-box/src/vaadin-combo-box-data-provider-mixin.js
packages/vaadin-grid/src/vaadin-grid-selection-column.js
packages/vaadin-grid/test/drag-and-drop.test.js
packages/vaadin-grid/test/row-height.test.js
packages/vaadin-menu-bar/test/sub-menu.test.js
packages/vaadin-split-layout/src/vaadin-split-layout.js
packages/vaadin-upload/test/common.js
scripts/generateReleaseNotes.js

This fixes most of the issues reported by Sonar.

chore: fix most of sonar code style warnings

---

dev/email-field.html
dev/number-field.html
dev/password-field.html
dev/text-area.html

Added pages for all the new field components.

chore: add dev pages for new input fields

---

dev/date-picker.html
dev/date-time-picker.html
dev/time-picker.html

Added dev pages for `vaadin-date-picker`, `vaadin-time-picker` and `vaadin-date-time-picker`.

chore: add date and time pickers dev pages

---

packages/vaadin-virtual-list/package.json
packages/vaadin-virtual-list/src/vaadin-virtual-list.d.ts
packages/vaadin-virtual-list/src/vaadin-virtual-list.js
packages/vaadin-virtual-list/test/virtual-list.test.js

fixes https://github.com/vaadin/web-components/issues/2484

feat: add requestContentUpdate API to virtual list

---

dev/checkbox.html

Added dev page for `vaadin-checkbox`.

chore: add checkbox dev page

---

packages/field-base/package.json
packages/select/package.json
packages/vaadin-combo-box/package.json
packages/vaadin-grid-pro/package.json
packages/vaadin-grid/package.json
packages/vaadin-icon/package.json
packages/vaadin-notification/package.json
packages/vaadin-overlay/package.json
packages/vaadin-themable-mixin/package.json
packages/vaadin-virtual-list/package.json
yarn.lock

1. Updated `lit` dependency to use 2.0.0 stable release 🎉 
2. Changed `vaadin-notification` to have `lit` under `dependencies`.

feat: update Lit to 2.0.0 stable release

---

packages/vaadin-combo-box/package.json
packages/vaadin-grid-pro/package.json
packages/vaadin-grid/package.json
packages/vaadin-icon/package.json
packages/vaadin-notification/package.json
packages/vaadin-overlay/package.json
packages/vaadin-select/package.json
packages/vaadin-themable-mixin/package.json
packages/vaadin-virtual-list/package.json
yarn.lock

Updated `lit` dependency to use 2.0.0 stable release 🎉 

feat: update Lit to 2.0.0 stable release (21.0)

---

packages/vaadin-rich-text-editor/src/vaadin-rich-text-editor-styles.js
packages/vaadin-rich-text-editor/src/vaadin-rich-text-editor.js

refactor: use registerStyles instead of include for rte styles

---

packages/vaadin-rich-text-editor/test/basic.test.js

test: skip flaky formatting test in Firefox

---

packages/vaadin-text-field/src/vaadin-text-field-mixin.d.ts
packages/vaadin-text-field/src/vaadin-text-field-mixin.js
packages/vaadin-text-field/src/vaadin-text-field.js

refactor: use registerStyles instead of include for text-field styles

---

packages/vaadin-grid/src/vaadin-grid-drag-and-drop-mixin.js
packages/vaadin-grid/test/drag-and-drop.test.js

Fixes #2648 
For some reason `this.updateStyles` no longer worked as expected. Changed to use native `style.setProperty` instead.

fix: use style.setProperty in favour of updateStyles

---

dev/radio-group.html

Added a dev page for the radio-group.

chore: add dev page for radio-group

---

packages/vaadin-date-picker/package.json

Restore the missing `package.json` file in `packages/vaadin-date-picker`

fix: restore package.json in vaadin-date-picker

---

packages/vaadin-combo-box/src/vaadin-combo-box-mixin.js
packages/vaadin-combo-box/test/keyboard.test.js

fix: clear combo-box value on esc

---

packages/radio-group/test/radio-group.test.js

Some changes from #2641 that are not directly related to the PR and can be applied separately.
- Tests

test: simplify radio-group unit tests

---

dev/radio-group.html
packages/field-base/src/slot-target-mixin.js
packages/field-base/test/slot-label-mixin.test.js
packages/field-base/test/slot-target-mixin.test.js

Fixes #2709
- [ X] Bugfix
- [ X] I have read the contribution guide: https://vaadin.com/docs-beta/latest/guide/contributing/overview/
- [X ] I have added a description following the guideline.
- [X ] The issue is created in the corresponding repository and I have referenced it.
- [X ] I have added tests to ensure my change is effective and works as intended.

fix: do not override slot target content with whitespace nodes

---

dev/text-field.html

I missed to add this page while moving text-field to the new base class. So here it is.

chore: add dev page for text-field

---

dev/accordion.html
dev/details.html

Added dev pages for details and accordion to test them locally.

chore: add details and accordion dev pages

---

packages/vaadin-select/src/vaadin-select.js
packages/vaadin-select/test/renderer.test.js

Manual cherry-pick of the fix for `vaadin-select` #2956
- Bugfix

fix: ensure correct menuElement reference (#2956) (CP: 21.0)

---

packages/vaadin-grid/src/vaadin-grid-drag-and-drop-mixin.js
packages/vaadin-grid/test/drag-and-drop.test.js

fix: disable row drag and drop while loading (#2957)

---

packages/select/theme/lumo/vaadin-select-styles.js

Changed the cursor and refactored CSS a bit to reduce unnecessary selector complexity.
Fixes #2965
- Bugfix

fix: use --lumo-clickable-cursor, refactor styles

---

dev/grid-pro.html

I had to create this while testing some keydown events changes in #2976 

chore: add dev page for grid-pro

---

dev/context-menu.html

I've used this for testing #2917

chore: add dev page for context-menu

---

wtr-utils.js

From now on, we will continue developing Vaadin 22 in the `22.0` branch and switch master to 23 in a separate PR.

chore: update change detection branch to 22.0

---

packages/vaadin-grid/src/vaadin-grid-selection-column.js
packages/vaadin-grid/test/selection.test.js

fix: get filtered grid root items from the data provider (#3021)

---

dev/index.html
package.json
web-dev-server.config.js
web-test-runner.config.js

Minor dev page improvements:
- Hide index.html from the listing
- Make dev page listing work on `/dev`(without `/index.html`)
- Make dev page listing work on `yarn debug`

chore: dev pages improvements

---

packages/grid/src/vaadin-grid.js
packages/grid/test/column-auto-width.test.js

fix(grid): consider all headers/footers when calculating columns width

---

README.md

1. Changed the tests badge to use the Coverage build which runs all the components on master,
2. Updated the Discord badge to align with those placed in READMEs of individual components.
Fixes # (issue)

chore: update status badges in README

---

packages/combo-box/src/vaadin-combo-box.d.ts
packages/combo-box/src/vaadin-combo-box.js

docs: improve JSDoc, remove Polymer-specific parts

---

packages/vaadin-grid/src/vaadin-grid.js
packages/vaadin-grid/test/column-auto-width.test.js

fix: consider all headers and footers when calculating column width (#2964)

---

packages/combo-box/src/vaadin-combo-box-dropdown.js
packages/combo-box/src/vaadin-combo-box-mixin.js
packages/component-base/src/browser-utils.js
packages/context-menu/src/vaadin-device-detector.js
packages/dialog/src/vaadin-dialog-draggable-mixin.js
packages/grid/src/vaadin-grid.js
packages/upload/src/vaadin-upload.js

Inspired by [React Aria](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/utils/src/platform.ts) utils.

feat: add helpers to detect iOS devices and touch

---

packages/combo-box/src/vaadin-combo-box-light.d.ts
packages/combo-box/src/vaadin-combo-box.d.ts
packages/combo-box/test/typings/combo-box.types.ts

Manual cherry-pick of #3082 to `22.0` branch.
- Bugfix

fix: add missing combo-box mixin classes (#3082) (CP: 22.0)

---

packages/grid/src/vaadin-grid.d.ts
packages/grid/src/vaadin-grid.js

Some cleanup in the old jsdocs examples

chore: update grid jsdocs to use fetch in the data provider

---

dev/select.html
packages/select/src/vaadin-select.js
packages/select/test/select.test.js

fix: restore select focus on fullscreen dropdown close

---

packages/vaadin-select/src/vaadin-select.js
packages/vaadin-select/test/select.test.js

fix: restore select focus on fullscreen dropdown close (#3120)

---

dev/confirm-dialog.html

Added missing dev page for `vaadin-confirm-dialog`.

chore: add confirm-dialog dev page

---

README.md

Same as #2271 but for preparing Vaadin 24 when the time comes.

chore: update README with instructions to bump to v24

---

packages/date-time-picker/src/vaadin-date-time-picker.js
packages/date-time-picker/test/basic.test.js

Manual cherry-pick pf #3153 to `22.0` branch.

fix: remove generated pickers when adding custom pickers (#3153)

---

packages/component-base/src/slot-controller.d.ts
packages/component-base/src/slot-controller.js
packages/component-base/test/slot-controller.test.js

Added `FlattenedNodesObserver` to manage slotted nodes, for using in #3181 and #3185

refactor: add observer logic to SlotController

---

packages/menu-bar/package.json
packages/menu-bar/src/vaadin-menu-bar-buttons-mixin.js
packages/menu-bar/src/vaadin-menu-bar-interactions-mixin.d.ts
packages/menu-bar/src/vaadin-menu-bar-interactions-mixin.js
packages/menu-bar/test/menu-bar.test.js

refactor: remove iron-resizable-behavior from menu-bar

---

dev/tabs.html
packages/tabs/package.json
packages/tabs/src/vaadin-tabs.js
packages/tabs/test/tabs.test.js
packages/tabs/test/visual/lumo/tabs.test.js
packages/tabs/test/visual/material/tabs.test.js

refactor: remove iron-resizable-behavior from tabs

---

packages/crud/src/vaadin-crud-form.js
packages/form-layout/package.json
packages/form-layout/src/vaadin-form-layout.d.ts
packages/form-layout/src/vaadin-form-layout.js
packages/form-layout/test/form-layout.test.js

refactor: remove iron-resizable-behavior from form-layout

---

.eslintrc.json
packages/board/src/vaadin-board-row.js
packages/charts/src/vaadin-chart.js
packages/combo-box/test/lazy-loading.test.js
packages/component-base/src/async.js
packages/component-base/src/iron-list-core.js
packages/component-base/test/virtualizer.test.js
packages/date-picker/src/vaadin-date-picker-overlay-content.js
packages/grid/src/vaadin-grid-data-provider-mixin.js
packages/grid/src/vaadin-grid-helpers.js
packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js
packages/grid/test/selection.test.js
packages/message-list/src/vaadin-message-list.js
packages/notification/test/statichelper.test.js
packages/polymer-legacy-adapter/src/style-modules.js
packages/rich-text-editor/src/vaadin-rich-text-editor.js
packages/upload/test/common.js
packages/upload/test/mock-http-request.js
packages/upload/test/upload.test.js
packages/vaadin-overlay/test/focus-trap.test.js
packages/vaadin-themable-mixin/test/register-styles.test.js
scripts/generateReleaseNotes.js

The PR adds more ESLint rules as proposed in #2987.
Part of #2987
Related to https://github.com/vaadin/eslint-config-vaadin/issues/16#issuecomment-961779712.

refactor: add more rules to ESLint config, fix warnings

---

packages/board/package.json
packages/board/src/vaadin-board-row.d.ts
packages/board/src/vaadin-board-row.js
packages/board/src/vaadin-board.d.ts
packages/board/src/vaadin-board.js
packages/board/test/common.js
packages/board/test/redraw.test.js
packages/board/test/size.test.js

refactor: remove iron-resizable-behavior from board

---

packages/time-picker/src/vaadin-time-picker-dropdown.js
packages/time-picker/src/vaadin-time-picker-scroller.js

I noticed these copy-paste leftovers while working on `MultiSelectComboBox`. Let's fix them.

chore: update JSDoc to extend correct classes

---

packages/password-field/src/vaadin-password-field.js
packages/password-field/test/password-field.test.js

fix: do not override i18n with hardcoded aria-label

---

packages/crud/src/vaadin-crud.d.ts
packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js
packages/grid/src/vaadin-grid-selection-column.js
packages/grid/test/scroll-to-index.test.js
packages/polymer-legacy-adapter/src/template-renderer-templatizer.js
packages/vaadin-list-mixin/vaadin-list-mixin.js
packages/vaadin-overlay/src/vaadin-overlay.js
packages/vaadin-themable-mixin/test/register-styles.test.js
packages/vaadin-themable-mixin/vaadin-themable-mixin.js

Fixed a couple of typos found by `cspell` (CLI version of VS Code Spell Checker plugin).

chore: fix typos detected by cspell

---

packages/field-base/src/field-mixin.js
packages/field-base/src/helper-controller.d.ts
packages/field-base/src/helper-controller.js
packages/field-base/test/field-mixin.test.js
packages/select/test/accessibility.test.js

Manual cherry-pick of #3185 to 22.0
- Cherry-pick

refactor: extract helper logic to HelperController (#3185) (CP: 22.0)

---

dev/custom-field.html

Dev page adapted from the a11y playground with some ARIA attributes.

chore: add custom-field dev page

---

packages/grid/src/vaadin-grid-column.js
packages/grid/test/column.test.js

Fixes https://github.com/vaadin/flow-components/issues/2489
(possibly also https://github.com/vaadin/flow-components/issues/2288)

fix: ensure cell is connected before rendering

---

packages/grid/src/vaadin-grid.js
packages/grid/test/column-auto-width.test.js

fix: flush virtualizer before measuring column auto-width

---

packages/combo-box/src/vaadin-combo-box-mixin.js
packages/combo-box/src/vaadin-combo-box-scroller.js
packages/combo-box/test/selecting-items.test.js

Related to https://github.com/vaadin/flow-components/issues/2222
This is a fix suggested by https://github.com/vaadin/flow-components/pull/2529#discussion_r787436127
https://user-images.githubusercontent.com/1222264/150087951-78e3bcd8-01ef-4471-beb7-99cce5ef7c7e.mp4
- Bugfix

fix: update items on clear button click

---

packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js
packages/grid/test/keyboard-navigation.test.js

fix: restore focused element reference on size change

---

dev/checkbox-group.html
packages/checkbox/src/vaadin-checkbox.js
packages/checkbox/test/checkbox.test.js

Same as #3327 but for `vaadin-checkbox`.
- Bugfix

fix: extend clickable area to handle clicks as expected

---

packages/date-picker/src/vaadin-date-picker-overlay-content.js
packages/date-picker/test/wai-aria.test.js

fix: set aria-hidden on year scroller container

---

packages/grid/src/vaadin-grid-row-details-mixin.js
packages/grid/test/row-details.test.js

Fixes https://github.com/vaadin/flow-components/issues/2534

fix: update details cell visibility when details renderer set

---

packages/combo-box/src/vaadin-combo-box.js
packages/date-picker/src/vaadin-date-picker.js
packages/email-field/test/dom/__snapshots__/email-field.test.snap.js
packages/integer-field/test/dom/__snapshots__/integer-field.test.snap.js
packages/number-field/src/vaadin-number-field.js
packages/number-field/test/dom/__snapshots__/number-field.test.snap.js
packages/password-field/test/dom/__snapshots__/password-field.test.snap.js
packages/select/src/vaadin-select.js
packages/select/test/dom/__snapshots__/select.test.snap.js
packages/text-area/src/vaadin-text-area.js
packages/text-area/test/dom/__snapshots__/text-area.test.snap.js
packages/text-field/src/vaadin-text-field.js
packages/text-field/test/dom/__snapshots__/text-field.test.snap.js
packages/time-picker/src/vaadin-time-picker.js

fix: add aria-hidden to clear and toggle buttons

---

packages/combo-box/src/vaadin-combo-box.js
packages/date-picker/src/vaadin-date-picker.js
packages/email-field/test/dom/__snapshots__/email-field.test.snap.js
packages/integer-field/test/dom/__snapshots__/integer-field.test.snap.js
packages/number-field/src/vaadin-number-field.js
packages/number-field/test/dom/__snapshots__/number-field.test.snap.js
packages/password-field/test/dom/__snapshots__/password-field.test.snap.js
packages/select/src/vaadin-select.js
packages/select/test/dom/__snapshots__/select.test.snap.js
packages/text-area/src/vaadin-text-area.js
packages/text-area/test/dom/__snapshots__/text-area.test.snap.js
packages/text-field/src/vaadin-text-field.js
packages/text-field/test/dom/__snapshots__/text-field.test.snap.js
packages/time-picker/src/vaadin-time-picker.js

Cherry-pick https://github.com/vaadin/web-components/pull/3375 for Vaadin 22

fix: add aria-hidden to clear and toggle buttons (#3375)

---

packages/date-picker/src/vaadin-month-calendar.js
packages/date-picker/test/month-calendar.test.js
packages/date-picker/test/wai-aria.test.js

Restored logic which was incorrectly removed in #3355
- Refactor

refactor: restore calendar date aria-label attribute

---

packages/vaadin-lumo-styles/test/autoload.js
packages/vaadin-material-styles/test/autoload.js

Added "autoload" helpers for using in visual tests. We can consider making them public later.
Related to #3234
- Tests

test: add autoload helpers to Lumo and Material

---

web-dev-server.config.js

Before:
https://user-images.githubusercontent.com/1222264/152515854-38aa235e-c29a-4741-bf93-53793ff8b69f.mp4
After:
https://user-images.githubusercontent.com/1222264/152515864-4a5455a5-e62a-42bb-a34f-aad08e9519e9.mp4

chore: prevent fouc on dev pages

---

packages/split-layout/src/vaadin-split-layout.js
packages/split-layout/test/split-layout.test.js

Cherry-pick of #3396 to `22.0` branch.
- Cherry-pick

fix: cleanup slot attribute on removed nodes (CP: 22.0) (#3396)

---

packages/date-picker/src/vaadin-date-picker.js
packages/date-picker/test/basic.test.js

Cherry-pick of #3398 to `22.0` branch.
- Cherry-pick

fix: prevent input blur on calendar icon click (CP: 22.0) (#3398)

---

packages/field-base/test/validate-mixin.test.js

Added some missing tests for `reflectToAttribute` copied from e27cad84934924254c3adefcc9c55e5acf92a6de
- Tests

test: add tests for reflecting properties

---

packages/map/src/vaadin-map.js

Add license check for `Map`.
Fixes https://github.com/vaadin/flow-components/issues/2505

[map] feat: add license checker to maps

---

packages/vaadin-lumo-styles/utilities/accessibility.js
packages/vaadin-lumo-styles/utilities/background.js
packages/vaadin-lumo-styles/utilities/border.js
packages/vaadin-lumo-styles/utilities/flexbox-grid.js
packages/vaadin-lumo-styles/utilities/layout.js
packages/vaadin-lumo-styles/utilities/shadows.js
packages/vaadin-lumo-styles/utilities/sizing.js
packages/vaadin-lumo-styles/utilities/spacing.js
packages/vaadin-lumo-styles/utilities/typography.js
packages/vaadin-lumo-styles/utility.js

fix: add missing .js extension to utilities

---

packages/select/package.json
packages/select/src/vaadin-select.js
packages/select/test/dom/__snapshots__/select.test.snap.js

Replaced `iron-media-query` with `MediaQueryController`.
Depends on #3426
- Refactor

refactor: remove iron-media-query from select

---

packages/crud/package.json
packages/crud/src/vaadin-crud.d.ts
packages/crud/src/vaadin-crud.js
packages/crud/test/dom/__snapshots__/crud.test.snap.js

Replaced `iron-media-query` with `MediaQueryController`.
Depends on #3426
- Refactor

refactor: remove iron-media-query from crud

---

packages/grid/src/vaadin-grid.js

Follow-up from #3445, missed that during self-review 😕 
- Refactor / internal fix

refactor: add missing .js extension to mixin

---

packages/component-base/src/slot-controller.js
packages/email-field/test/dom/__snapshots__/email-field.test.snap.js
packages/field-base/src/error-controller.d.ts
packages/field-base/src/error-controller.js
packages/field-base/src/field-mixin.js
packages/field-base/test/field-mixin.test.js
packages/integer-field/test/dom/__snapshots__/integer-field.test.snap.js
packages/message-input/test/dom/__snapshots__/message-input.test.snap.js
packages/number-field/test/dom/__snapshots__/number-field.test.snap.js
packages/password-field/src/vaadin-password-field.d.ts
packages/password-field/src/vaadin-password-field.js
packages/password-field/test/dom/__snapshots__/password-field.test.snap.js
packages/select/test/dom/__snapshots__/select.test.snap.js
packages/text-area/test/dom/__snapshots__/text-area.test.snap.js
packages/text-field/test/dom/__snapshots__/text-field.test.snap.js

Manual cherry-pick of #3270 to `22.0` branch for making it easier to backport fixes in the future.
- Cherry-pick

refactor: move errorMessage logic to ErrorController (#3270) (CP: 22.0)

---

packages/select/src/vaadin-select.js
packages/select/test/renderer.test.js

Manual cherry-pick of #3412 to `22.0` branch.
- Cherry-pick

fix: handle list-box set before renderer (#3412) (CP: 22.0)

---

packages/grid/src/vaadin-grid-data-provider-mixin.d.ts
packages/grid/src/vaadin-grid-data-provider-mixin.js
packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js
packages/grid/src/vaadin-grid-tree-column.d.ts
packages/grid/src/vaadin-grid-tree-column.js
packages/grid/test/accessibility.test.js
packages/grid/test/data-provider.test.js
packages/grid/test/scroll-to-index.test.js
packages/grid/test/tree-toggle.test.js
packages/grid/test/typings/grid.types.ts

feat: add itemHasChildrenPath property

---

packages/combo-box/src/vaadin-combo-box-mixin.js
packages/combo-box/test/basic.test.js

Cherry-pick of #3485 to `22.0` branch where the original (incorrect) fix was previously picked.
- Cherry-pick

fix: check last custom value on focusout (#3485) (CP: 22.0)

---

dev/dialog.html

Added missing dev page for `vaadin-dialog`.

chore: add dev page for dialog

---

packages/map/package.json
yarn.lock

Remove snapshot version from dependency.

refactor: bump OL version to 6.13.0

---

packages/checkbox/test/checkbox.test.js
packages/checkbox/test/dom/__snapshots__/checkbox.test.snap.js
packages/checkbox/test/dom/checkbox.test.js

Added missing snapshot tests for `vaadin-checkbox`.
- Tests

test: add snapshot tests for checkbox

---

packages/checkbox-group/test/checkbox-group.test.js
packages/checkbox-group/test/dom/__snapshots__/checkbox-group.test.snap.js
packages/checkbox-group/test/dom/checkbox-group.test.js

Added missing snapshot tests for `vaadin-checkbox`.
- Tests

test: add snapshot tests for checkbox-group

---

packages/radio-group/test/dom/__snapshots__/radio-button.test.snap.js
packages/radio-group/test/dom/__snapshots__/radio-group.test.snap.js
packages/radio-group/test/dom/radio-button.test.js
packages/radio-group/test/dom/radio-group.test.js
packages/radio-group/test/radio-button.test.js
packages/radio-group/test/radio-group.test.js

Added missing snapshot tests for `vaadin-radio-group`.
- Tests

test: add snapshot tests for radio-group

---

packages/combo-box/test/basic.test.js
packages/combo-box/test/dom/__snapshots__/combo-box.test.snap.js
packages/combo-box/test/dom/combo-box.test.js

Added missing snapshot tests for `vaadin-combo-box`.
- Tests

test: add snapshot tests for combo-box

---

packages/time-picker/test/dom/__snapshots__/time-picker.test.snap.js
packages/time-picker/test/dom/time-picker.test.js
packages/time-picker/test/time-picker.test.js

Added missing snapshot tests for `vaadin-time-picker`.
- Tests

test: add snapshot tests for time-picker

---

packages/crud/src/vaadin-crud.js
packages/crud/test/crud.test.js

Fixes: https://github.com/vaadin/web-components/issues/3532

fix: do not fail when saving a new item when using dataProvider

---

packages/crud/src/vaadin-crud.js
packages/crud/test/crud.test.js

Fixes: https://github.com/vaadin/web-components/issues/3557

fix: update dataProvider when grid is set

---

packages/crud/src/vaadin-crud.js
packages/crud/test/crud.test.js

Cherry-pick of #3558 
(cherry picked from commit 4f086bea4c74111b009f234b34ecb3b696c7478b)

fix: update dataProvider when grid is set (#3558) (CP: 22)

---

packages/component-base/src/polylit-mixin.d.ts
packages/component-base/src/polylit-mixin.js
packages/component-base/test/polylit-mixin.test.js

A mixin to support various PolymerElement APIs with LitElement based components. Intended for internal purposes.
This PR includes some additional features on top of the initial implementation from https://github.com/web-padawan/polylit

feat: add polylit-mixin

---

packages/dialog/src/vaadin-dialog.js
packages/dialog/test/header-footer.test.js

fix: handle renderers set before adding to DOM

---

packages/crud/src/vaadin-crud.js

Here is a part of the refactoring that I extracted from #3667 in order to get a smaller diff there.

refactor: align naming of event handlers and observers

---

packages/crud/src/vaadin-crud.js

This PR cherry-picks the following refactoring to 23.0:
- https://github.com/vaadin/web-components/pull/3676

refactor: align naming of event handlers and observers (#3676) (CP: 23.0)

---

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-chip.js
packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-container.js
packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.d.ts
packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js
packages/multi-select-combo-box/test/basic.test.js
packages/multi-select-combo-box/theme/lumo/vaadin-multi-select-combo-box-chip-styles.js
packages/multi-select-combo-box/theme/material/vaadin-multi-select-combo-box-chip-styles.js

Fixes #3630
Note: visual tests will be done in a separate PR after this PR is merged and theme is reviewed.
For reviewers: run `npm start` and check out the dev page http://localhost:8000/dev/multi-select-combo-box.html
- Feature

feat: show overflow chip if chips do not fit

---

.eslintrc.json
packages/charts/src/vaadin-chart.js
packages/checkbox-group/test/checkbox-group.test.js
packages/combo-box/test/lazy-loading.test.js
packages/component-base/src/iron-list-core.js
packages/context-menu/test/touch.test.js
packages/crud/src/vaadin-crud-grid.js
packages/date-picker/test/common.js
packages/grid/src/vaadin-grid-column-resizing-mixin.js
packages/grid/src/vaadin-grid-scroll-mixin.js
packages/grid/test/class-name-generator.test.js
packages/grid/test/column-auto-width.test.js
packages/icons/gulpfile.js
packages/number-field/test/number-field.test.js
packages/rich-text-editor/gulpfile.js
packages/time-picker/test/time-picker.test.js
packages/upload/test/mock-http-request.js
packages/upload/test/upload.test.js
packages/vaadin-lumo-styles/gulpfile.js
packages/vaadin-material-styles/gulpfile.js
packages/vaadin-overlay/test/focus-trap.test.js
scripts/updateVersion.js

The PR adds the following rules to the project's ESLint config:
Part of https://github.com/vaadin/eslint-config-vaadin/issues/16

refactor: add more rules to ESLint config, fix warnings (4) 

---

.eslintrc.json
packages/combo-box/test/keyboard.test.js
packages/component-base/src/iron-list-core.js
packages/cookie-consent/src/vaadin-cookie-consent.js
packages/custom-field/test/custom-field.test.js
packages/date-picker/src/vaadin-date-picker-helper.js
packages/date-picker/src/vaadin-date-picker-mixin.js
packages/date-picker/src/vaadin-date-picker-overlay-content.js
packages/date-picker/src/vaadin-infinite-scroller.js
packages/date-picker/src/vaadin-month-calendar.js
packages/date-picker/test/basic.test.js
packages/date-picker/test/common.js
packages/date-picker/test/overlay.test.js
packages/date-picker/test/wai-aria.test.js
packages/date-time-picker/test/basic.test.js
packages/form-layout/test/form-layout.test.js
packages/list-box/src/vaadin-list-box.js
packages/login/test/login-form.test.js
packages/notification/test/notification.test.js
packages/number-field/test/number-field.test.js
packages/rich-text-editor/test/basic.test.js
packages/split-layout/src/vaadin-split-layout.js
packages/split-layout/test/split-layout.test.js
packages/time-picker/src/vaadin-time-picker.js
packages/time-picker/test/combo-box.test.js
packages/upload/src/vaadin-upload.js
packages/upload/test/common.js
packages/upload/test/mock-http-request.js
packages/upload/test/upload.test.js
packages/vaadin-overlay/src/vaadin-overlay.js

The PR adds the following rules to the project's ESLint config:
Part of https://github.com/vaadin/eslint-config-vaadin/issues/16

refactor: add more rules to ESLint config, fix warnings (2)

---

.eslintrc.json
packages/component-base/custom_typings/vaadin.d.ts
packages/component-base/src/async.d.ts
packages/component-base/src/gestures.d.ts
packages/date-picker/src/vaadin-date-picker-mixin.d.ts
packages/grid/src/vaadin-grid.d.ts
packages/time-picker/src/vaadin-time-picker.d.ts
packages/upload/src/vaadin-upload.d.ts

The PR adds the following rules to the project's ESLint config:
Part of https://github.com/vaadin/eslint-config-vaadin/issues/16

refactor: add more rules to ESLint config, fix warnings (3)

---

packages/grid-pro/src/vaadin-grid-pro.d.ts
packages/grid-pro/test/typings/grid-pro.types.ts

Updated the type definitions for two events that were previously incorrect.
Fixes #3815
- Bugfix

fix: update event types to use correct detail object

---

packages/grid/src/vaadin-grid-column-group.js
packages/grid/test/column-group.test.js

fix: prevent overriding column hidden state when attaching column group (#3805) (CP: 23)

---

packages/menu-bar/src/vaadin-menu-bar-buttons-mixin.js

Manual cherry-pick of #3826 to `22.0`
- Cherry-pick

refactor: extract method for updating overflow (#3826) (CP: 22.0)

---

dev/notification.html
packages/notification/src/vaadin-notification.js
packages/notification/test/notification.test.js

Fixes #3823 
Related to https://github.com/vaadin/flow-components/issues/3085

fix: close a notification on detach

---

dev/notification.html
packages/notification/src/vaadin-notification.js
packages/notification/test/notification.test.js

fix: close a notification on detach (#3830) (CP: 23.0)

---

packages/grid/src/vaadin-grid-selection-mixin.js

Cherry-pick of #3845 to `23.0` branch.
- Cherry-pick

refactor: improve performance of checking if item is selected (#3845) (CP: 23.0)

---

packages/grid/src/vaadin-grid-selection-mixin.js

Cherry-pick of #3845 to `22.0` branch.
- Cherry-pick

refactor: improve performance of checking if item is selected (#3845) (CP: 22.0)

---

packages/date-picker/test/custom-input.test.js

Updated unit tests for `vaadin-date-picker-light` to use helpers and remove some manual tweaks.
- Tests

test: simplify date-picker-light unit tests

---

packages/date-picker/package.json
packages/date-picker/src/vaadin-date-picker-mixin.js
packages/date-picker/src/vaadin-date-picker-overlay-content.js
packages/date-picker/test/dialog.test.js

Manual cherry-pick of #3872 for `23.0` branch. Automated cherry-pick failed due to version in `package.json` diff.
- Cherry-pick

fix: do not close dialog when closing date-picker (#3872) (CP: 23.0)

---

packages/combo-box/test/lazy-loading.test.js

Fixes a flaky test that fails quite often locally.

chore: fix flaky lazy loading scrolling test

---

packages/component-base/test/virtualizer-scrolling.test.js

Relates to https://github.com/vaadin/web-components/issues/3862
Add the attached test case from the issue description

test: add a missing virtualizer test case

---

packages/date-picker/src/vaadin-date-picker-mixin.js
packages/date-picker/test/basic.test.js

Manual cherry-pick of #3913 to `23.0` branch.
- Cherry-pick

fix: update incorrect fullscreen mode focus logic (#3913) (CP: 23.0)

---

packages/field-highlighter/src/vaadin-user-tags.js
packages/field-highlighter/test/field-highlighter.test.js

This PR is a manual cherry-pick of the following fix to `23.0`:
- https://github.com/vaadin/web-components/pull/3891

fix: remove not relevant user tags when replacing users (#3891) (CP: 23.0)

---

integration/tests/dialog-combo-box.test.js

Added missing tests to ensure pressing <kbd>Esc</kbd> does not close dialog when handled by `vaadin-combo-box`.
- Test

test: add more tests for combo-box in dialog

---

integration/package.json
integration/tests/dialog-multi-select-combo-box.test.js

Added tests to ensure pressing <kbd>Esc</kbd> does not close dialog when handled by `vaadin-multi-select-combo-box`.
- Test

test: add tests for multi-select-combo-box in dialog

---

packages/field-base/src/field-mixin.d.ts
packages/field-base/src/field-mixin.js
packages/field-base/src/label-mixin.d.ts

Cleanup some logic that is no longer relevant after mixins refactoring done in #3181, #3185 and #3270.
- Refactor

refactor: cleanup removed API from typings

---

packages/field-highlighter/test/field-highlighter.test.js
packages/field-highlighter/test/user-tags.test.js

The PR extracts the `user-tags` related tests into a separate file and cleans up the existing field-highlighter tests along the way.
A preparation for #3950

test: extract user-tags related tests

---

packages/field-highlighter/src/vaadin-user-tags.js
packages/field-highlighter/test/user-tags.test.js

A manual cherry-pick of the following test improvement:
- https://github.com/vaadin/web-components/pull/3966
> **Note**
> Conflicts were due to not capitalized comments on the `23.0` branch.

test: speed up field highlighter unit tests (#3966) (CP: 23.0) 

---

packages/combo-box/test/typings/combo-box.types.ts
packages/date-picker/test/typings/date-picker.types.ts
packages/field-base/src/input-control-mixin.d.ts
packages/field-base/src/input-control-mixin.js
packages/field-base/src/input-field-mixin.js
packages/field-base/test/input-control-mixin.test.js
packages/field-base/test/input-field-mixin.test.js
packages/integer-field/src/vaadin-integer-field.js

feat: add public allowedCharPattern property

---

packages/field-base/test/field-mixin.test.js
packages/field-base/test/label-mixin.test.js

Added `LitElement` test suites for `LabelMixin` and `FieldMixin`.
- Tests

test: add label and field mixins Lit tests

---

packages/date-picker/test/basic.test.js
packages/date-picker/test/dom/__snapshots__/date-picker.test.snap.js
packages/date-picker/test/dom/__snapshots__/month-calendar.test.snap.js
packages/date-picker/test/dom/date-picker.test.js
packages/date-picker/test/dom/month-calendar.test.js
packages/date-picker/test/wai-aria.test.js

This PR replaces some date-picker unit tests with snapshot tests.

test: replace some date-picker unit tests with snapshot tests

---

packages/select/test/accessibility.test.js
packages/select/test/dom/__snapshots__/select.test.snap.js
packages/select/test/dom/select.test.js

This PR replaces some select unit tests with snapshot tests.

test: replace some select unit tests with snapshot tests

---

packages/combo-box/test/combo-box-light.test.js
packages/combo-box/test/form-input.test.js
packages/combo-box/test/helpers.js
packages/combo-box/test/toggling-dropdown.test.js

This PR is a pushover cleanup of the combo-box test helpers.

test: clean up combo-box test helpers

---

dev/combo-box.html

We often need to test `dataProvider` API as it's what Flow component uses. Let's add an example to dev page.

chore: update combo-box dev page to use dataProvider

---

packages/combo-box/src/vaadin-combo-box.d.ts
packages/combo-box/src/vaadin-combo-box.js
packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.d.ts
packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js

Document the overlay width custom property for `<vaadin-combo-box>` and `<vaadin-multi-select-combo-box>`.

docs: combo box overlay width custom property

---

packages/combo-box/src/vaadin-combo-box-mixin.js
packages/combo-box/test/object-values.test.js

Fixes #1292
This was prototyped at https://github.com/vaadin/vaadin-combo-box/commit/3659464ae76879634d458e0da9611d10eef30b02 but for some reason I didn't make a PR for it back then 😕 
- Bugfix

fix: set correct input value with allowCustomValue

---

packages/combo-box/src/vaadin-combo-box-mixin.js
packages/combo-box/test/object-values.test.js

Cherry-pick of #4082 to `23.1` branch.
- Cherry-pick

fix: set correct input value with allowCustomValue (#4082) (CP: 23.1)

---

packages/number-field/test/dom/__snapshots__/number-field.test.snap.js
packages/number-field/test/dom/number-field.test.js
packages/number-field/test/number-field.test.js

This PR replaces some `number-field` unit tests with snapshot tests.

test: replace some unit tests with snapshot tests

---

packages/avatar-group/src/vaadin-avatar-group.js
packages/combo-box/src/vaadin-combo-box-mixin.js
packages/crud/src/vaadin-crud-grid.js
packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js

Fixed a couple of JSDoc comments that have incorrect formatting.
- Docs

docs: fix incorrect JSDoc comments formatting

---

packages/date-time-picker/src/vaadin-date-time-picker.js
packages/rich-text-editor/src/vaadin-rich-text-editor.js

These two comments are leftovers from V14 versions where we used a different test runner. Let's update them.

chore: use correct syntax for coverage comments

---

packages/combo-box/src/vaadin-combo-box-mixin.d.ts

These methods have been removed in #4092 but are still present in the typings. Let's remove them from there.
- Refactor

refactor: cleanup removed methods from typings

---

packages/field-base/src/field-aria-controller.js
packages/select/src/vaadin-select.d.ts
packages/select/src/vaadin-select.js
packages/select/test/accessibility.test.js
packages/select/test/dom/__snapshots__/select.test.snap.js

Manual cherry-pick of #4197 to `23.1` branch. Adjusted logic, added unit test to avoid backporting snapshot tests.
- Cherry-pick

fix: improve setting ARIA attributes for select (#4197) (CP: 23.1)

---

packages/combo-box/test/dom/__snapshots__/combo-box.test.snap.js
packages/combo-box/test/dom/combo-box.test.js
packages/combo-box/test/form-input.test.js

Added missing snapshot tests for `disabled`, `readonly` and `required` states and removed corresponding unit tests.
- Tests

test: replace some unit tests with snapshots

---

packages/form-layout/src/vaadin-form-layout.js
packages/form-layout/test/form-layout.test.js

fix: do not remove custom top label-position (#4211) (#4226)

---

packages/time-picker/src/vaadin-time-picker.js
packages/time-picker/test/form-input.test.js

fix: do not throw error with incorrect value attribute (#4176) (#4178)

---

packages/menu-bar/src/vaadin-menu-bar.d.ts
packages/menu-bar/src/vaadin-menu-bar.js

docs: add disabled attribute to styling API (#4191) (#4192)

---

packages/field-base/src/field-aria-controller.js
packages/select/src/vaadin-select.d.ts
packages/select/src/vaadin-select.js
packages/select/test/accessibility.test.js
packages/select/test/dom/__snapshots__/select.test.snap.js

fix: improve setting ARIA attributes for select (#4197) (#4208)

---

packages/combo-box/src/vaadin-combo-box-mixin.js

Follow-up to #4249 
In that PR I removed all the places where this method was used, but forgot to remove the method itself 🤦‍♂️ 
- Refactor

refactor: remove no longer used private method

---

packages/grid/src/vaadin-grid-sort-mixin.d.ts
packages/grid/src/vaadin-grid-sort-mixin.js
packages/grid/test/sorting.test.js

Changed the API for setting the default `multiSortPriority` to align with the Flow counterpart.
- Feature

feat: use static setDefaultMultiSortPriority

---

packages/combo-box/test/toggling-dropdown.test.js

Removed a few no longer relevant tests, updated to use helpers.
- Tests

test: cleanup combo-box dropdown tests

---

dev/tooltip.html

Added a dev page for testing `vaadin-tooltip` in the browser.

chore: add dev page for vaadin-tooltip

---

CONTRIBUTING.md
README.md

Updated contribution guideline links to use the correct URL.

chore: update contribution guideline links

---

README.md

Updated the instructions in README on how to make a new version bump based on the recent example.

chore: update docs for making a version bump

---

dev/checkbox.html
integration/package.json
integration/tests/checkbox-tooltip.test.js
packages/checkbox/src/vaadin-checkbox.js
packages/checkbox/test/dom/__snapshots__/checkbox.test.snap.js

Added `vaadin-tooltip` support to `vaadin-checkbox` via `tooltip` slot and `TooltipController`.
- Feature

feat: add tooltip support to vaadin-checkbox

---

dev/select.html
integration/tests/component-tooltip.test.js
packages/select/src/vaadin-select.js
packages/select/test/dom/__snapshots__/select.test.snap.js

Added `vaadin-tooltip` support to `vaadin-select` via `tooltip` slot and `TooltipController`.
- Feature

feat: add tooltip support to select

---

dev/combo-box.html
integration/tests/component-tooltip.test.js
packages/combo-box/src/vaadin-combo-box.js
packages/combo-box/test/dom/__snapshots__/combo-box.test.snap.js

Added `vaadin-tooltip` support to `vaadin-combo-box` via `tooltip` slot and `TooltipController`.
- Feature

feat: add tooltip support to vaadin-combo-box

---

dev/radio-group.html
integration/tests/component-tooltip.test.js
packages/radio-group/src/vaadin-radio-group.js
packages/radio-group/test/dom/__snapshots__/radio-group.test.snap.js

Added `vaadin-tooltip` support to `vaadin-radio-group` via `tooltip` slot and `TooltipController`.
- Feature

feat: add tooltip support to vaadin-radio-group

---

packages/date-picker/src/vaadin-date-picker-mixin.d.ts
packages/time-picker/src/vaadin-time-picker.d.ts
packages/time-picker/test/typings/time-picker.types.ts

Manual cherry-pick of #4488 to `23.2` branch (the conflict was caused by #4493 added on master).
- Cherry-pick

refactor: cleanup validation methods typings (#4488) (CP: 23.2)

---

dev/map.html

As suggested in https://github.com/vaadin/web-components/pull/4519/files#r964598055

chore: remove import for enable on map dev page

---

dev/list-box.html
dev/map.html
integration/package.json
integration/tests/component-tooltip.test.js
packages/list-box/src/vaadin-list-box.js

Added `vaadin-tooltip` support to `vaadin-list-box` via `tooltip` slot and `TooltipController`.
- Feature

feat: add tooltip support to list-box

---

packages/grid/src/vaadin-grid-column-reordering-mixin.js

Apply some coding style improvements in the grid's reordering mixin.
The changes were left out of https://github.com/vaadin/web-components/pull/4534 in order to keep the fix PR as simple as possible

refactor: grid reordering mixin coding style improvements

---

packages/combo-box/src/vaadin-combo-box-scroller.js
packages/combo-box/test/dynamic-size.test.js
packages/combo-box/test/lazy-loading.test.js

This PR cherry-picks the following commits to `23.2`:
- https://github.com/vaadin/web-components/pull/4551
- https://github.com/vaadin/web-components/pull/4561
Fixes https://github.com/vaadin/flow-components/issues/3553

fix: request pages asynchronously when scrolling (#4561) (CP: 23.2)

---

dev/menu-bar.html

Clean up menu-bar tooltip use on the dev page

chore: update menu-bar tooltip use on the dev page

---

packages/combo-box/src/vaadin-combo-box-scroller.js
packages/combo-box/test/dynamic-size.test.js
packages/combo-box/test/lazy-loading.test.js

This PR cherry-picks the following commits to `23.1`:
- https://github.com/vaadin/web-components/pull/4551
- https://github.com/vaadin/web-components/pull/4561
- https://github.com/vaadin/web-components/pull/4036 (without changes to `vaadin-combo-box-data-provider.js`)
Fixes https://github.com/vaadin/flow-components/issues/3553

fix: request pages asynchronously when scrolling (#4561) (CP: 23.1)

---

packages/checkbox-group/package.json

Same as #4643 but for `22.0` branch.
- Bugfix

fix: add missing field-base package dependency

---

packages/tooltip/src/vaadin-tooltip.js
packages/tooltip/test/tooltip.test.js

fix: make sure tooltip closes on disconnect

---

integration/tests/component-tooltip.test.js
packages/component-base/src/tooltip-controller.d.ts
packages/component-base/src/tooltip-controller.js
packages/component-base/test/tooltip-controller.test.js
packages/tooltip/src/vaadin-tooltip.js
packages/tooltip/test/tooltip-position.test.js

fix: do not override position in the controller

---

packages/grid/test/column-auto-width.test.js
packages/grid/theme/lumo/vaadin-grid-tree-toggle-styles.js

Fixes https://github.com/vaadin/flow-components/issues/3607

fix: use translate instead of margin for tree toggle

---

packages/date-picker/src/vaadin-month-calendar.js
packages/date-picker/test/basic.test.js
packages/date-picker/test/month-calendar.test.js

The PR cherry-picks the following fixes to `23.1`:
- https://github.com/vaadin/web-components/pull/4658
Fixes https://github.com/vaadin/web-components/pull/4658

fix: hide weekdays from assistive technologies (CP: 23.1) (#4658)

---

packages/tooltip/src/vaadin-tooltip.js

Related to #4640
Extracted some logic related to opening / closing a tooltip to the dedicated `TooltipStateController`.
The idea behind this change is to call `open()` and `close()` methods when using manual tooltip.
This would enable an opt-in delays support, without explicitly enabling them for `manual` mode.
Note: there will be separate PRs for `vaadin-grid` and `vaadin-menu-bar` based on this one.
- Refactor

refactor: extract opened state logic to controller

---

packages/vaadin-overlay/src/vaadin-overlay-position-mixin.js
packages/vaadin-overlay/test/position-mixin-listeners.test.js

Fixes https://github.com/vaadin/web-components/issues/4688

fix: do not update position on scroll events inside the overlay

---

.github/workflows/coverage.yml
.github/workflows/unit-tests.yml
.github/workflows/verify.yml
.github/workflows/visual-tests.yml

Updated `actions/checkout` and `actions/setup-node` to latest version (v3).

chore: update GitHub Actions to latest versions

---

packages/message-list/src/vaadin-message-list.d.ts
packages/message-list/src/vaadin-message-list.js
packages/message-list/test/dom/__snapshots__/message-list.test.snap.js
packages/message-list/test/dom/message-list.test.js
packages/message-list/test/message-list.test.js
packages/message-list/test/visual/lumo/message-list.test.js
packages/message-list/test/visual/material/message-list.test.js
packages/message-list/theme/material/vaadin-message-list-styles.js

Fixes #4289
- Breaking change (affects styling)

refactor!: move vaadin-message elements to light DOM

---

wtr-utils.js

Update the `web-test-runner` change detection script to use `23.3` as a base branch for Vaadin 23.3

chore: update change detection branch to 23.3

---

wtr-utils.js

Update the `web-test-runner` change detection script to use `master` as a base branch for Vaadin 24 alpha.

chore: update change detection branch to master

---

integration/tests/dialog-date-picker.test.js
packages/date-picker/src/vaadin-date-picker-overlay-content.js
packages/date-picker/src/vaadin-date-picker.d.ts
packages/date-picker/src/vaadin-date-picker.js
packages/date-picker/test/basic.test.js
packages/date-picker/test/keyboard-input.test.js
packages/date-picker/test/overlay.test.js
packages/date-picker/theme/lumo/vaadin-date-picker-overlay-content-styles.js
packages/date-picker/theme/material/vaadin-date-picker-overlay-content-styles.js

Fixes #4708
- Breaking change (affects styling)

refactor!: move Today and Cancel buttons to light DOM

---

packages/date-picker/src/vaadin-date-picker-overlay-content.js
packages/date-picker/theme/material/vaadin-date-picker-overlay-content-styles.js

Removed some unused code discovered while working on #4770 to make that PR smaller.
- Refactor

refactor: remove no longer used code from date-picker

---

packages/avatar/src/vaadin-avatar.js
packages/avatar/test/avatar.test.js

Cherry-pick of #4783 to `23.2` branch.
- Cherry-pick

fix: add support for setting custom role attribute (#4783) (CP: 23.2)

---

packages/avatar/src/vaadin-avatar.js
packages/avatar/test/avatar.test.js

Cherry-pick of #4783 to `23.1` branch.
- Cherry-pick

fix: add support for setting custom role attribute (#4783) (CP: 23.1)

---

README.md

Updated the README with instructions on how to configure Vite to use local web components.

chore: add Vite usage instructions to README

---

packages/date-picker/test/custom-input.test.js
packages/date-picker/test/dropdown.test.js
packages/date-picker/test/month-calendar.test.js
packages/date-picker/test/overlay.test.js
packages/date-picker/test/theme-propagation.test.js

Some updates to `vaadin-date-picker` unit tests based on incomplete prototype branch with a Lit version.
- Tests

test: update and cleanup date-picker tests

---

packages/date-picker/src/vaadin-date-picker-helper.d.ts
packages/date-picker/src/vaadin-date-picker-helper.js
packages/date-picker/src/vaadin-date-picker-mixin.d.ts
packages/date-picker/src/vaadin-date-picker-mixin.js
packages/date-picker/test/basic.test.js
packages/date-picker/test/keyboard-input.test.js
packages/date-time-picker/src/vaadin-date-time-picker.js

Cherry-picked [4792](https://github.com/vaadin/web-components/pull/4792) to `23.3`.
Enhancement related to [1107](https://github.com/vaadin/flow-components/issues/1107).
Flow component part pending.

1107 - date picker parsing web component cherry pick

---

packages/component-base/test/resize-mixin.test.js

Updated `ResizeMixin` tests to use `onceInvoked` helper that we generally use to wait for resize observer.
This change aims to stabilize some of these tests that became flaky with the latest Playwright WebKit:
```
packages/component-base/test/resize-mixin.test.js:
❌ resize-mixin > observe parent > light DOM > should notify parent element resize
Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
at createTimeoutError (node_modules/@web/test-runner-mocha/dist/autorun.js:1:243204)
at node_modules/@web/test-runner-mocha/dist/autorun.js:1:257230
❌ resize-mixin > observe parent > shadow DOM > should notify shadow host resize
Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; …
```

test: use onceInvoked helper in ResizeMixin tests

---

integration/tests/combo-box-template.test.js
integration/tests/fixtures/mock-combo-box-light-template-wrapper.js
integration/tests/fixtures/mock-combo-box-template-wrapper.js
packages/combo-box/package.json
packages/combo-box/test/combo-box-light.test.js
packages/combo-box/test/item-renderer.test.js

Moved the combo-box`<template>` tests to the `integration-tests` package.
- Tests

test: move combo-box item template tests to ITs

---

dev/login-form.html
dev/login-overlay.html

Added missing dev pages for `vaadin-login-overlay` and `vaadin-login-form` components.

chore: add login-overlay and login-form dev pages

---

packages/login/src/vaadin-login-form.d.ts
packages/login/src/vaadin-login-form.js

Removed some code that was needed for older browsers, including `event.keyCode` and iOS workaround.
Also fixed duplicate line for `error-message-description` container in the stylable parts table.
- Refactor

refactor: cleanup no longer needed login-form code

---

packages/login/test/dom/__snapshots__/login-form.test.snap.js
packages/login/test/dom/__snapshots__/login-overlay.test.snap.js
packages/login/test/dom/login-form.test.js
packages/login/test/dom/login-overlay.test.js
packages/login/test/login-form.test.js

Added missing snapshot tests, and removed some unit tests that are now covered by snapshots.
- Test

test: add login overlay and form snapshot tests

---

packages/crud/src/vaadin-crud.js

Updated `vaadin-crud` to use `SlotController` instead of `SlotMixin` to align with other components.
This also makes the code slightly cleaner by not using single property observers for buttons.
- Refactor

refactor: replace SlotMixin with controller in CRUD

---

packages/grid/theme/lumo/vaadin-grid.js

Removed some imports present in other files, to make Lumo grid entrypoint aligned with Material.
- Refactor

refactor: cleanup duplicate imports for Lumo modules

---

packages/grid/src/vaadin-grid-drag-and-drop-mixin.js

Replaced usage of Polymer specific `updateStyles()` method with native `this.style.setProperty()`.
- Refactor

refactor: remove usage of updateStyles from grid

---

packages/component-base/src/slot-controller.d.ts
packages/component-base/src/slot-controller.js
packages/component-base/test/slot-controller.test.js

feat: add multiple nodes support to SlotController

---

packages/confirm-dialog/src/vaadin-confirm-dialog.js
packages/confirm-dialog/test/confirm-dialog.test.js

fix: support teleporting multiple message elements

---

packages/list-box/test/typings/list-box.types.ts
packages/vaadin-list-mixin/vaadin-multi-select-list-mixin.d.ts

Fix for a finding reported at https://github.com/vaadin/web-components/issues/4900#issuecomment-1316723167
- Bugfix

fix: update MultiSelectListMixin type definitions

---

packages/login/src/vaadin-login-form.js
packages/login/test/dom/__snapshots__/login-form.test.snap.js
packages/login/test/dom/__snapshots__/login-overlay.test.snap.js
packages/login/test/dom/login-form.test.js
packages/login/test/dom/login-overlay.test.js

Manual cherry-pick of #5036 to `23.1` branch with adding missing snapshot tests for `login` package.
- Cherry-pick

fix: add autocomplete="username" to user name field (#5036) (CP: 23.1)

---

packages/login/src/vaadin-login-form.js
packages/login/test/dom/__snapshots__/login-form.test.snap.js
packages/login/test/dom/__snapshots__/login-overlay.test.snap.js
packages/login/test/dom/login-form.test.js
packages/login/test/dom/login-overlay.test.js

Manual cherry-pick of #5036 to `23.2` branch with adding missing snapshot tests for `login` package.
- Cherry-pick

fix: add autocomplete="username" to user name field (#5036) (CP: 23.2)

---

packages/date-picker/src/vaadin-date-picker-mixin.js
packages/date-picker/test/keyboard-input.test.js
packages/date-picker/test/validation.test.js

Cherry-pick of #5076 
(cherry picked from commit d6f871f2e694aa08748481d32ae9c7f6ba2e6b20)

fix: clear value when committing invalid value (#5076) (CP: 23.3)

---

packages/accordion/src/vaadin-accordion-panel.js
packages/accordion/test/dom/__snapshots__/accordion-panel.test.snap.js
packages/accordion/test/dom/accordion-panel.test.js

Follow-up to #5093 with some changes that I missed to include to that PR. Also, added snapshot tests.
- Refactor

refactor: align accordion panel with details, add tests

---

packages/field-base/src/error-controller.js
packages/field-base/src/field-mixin.js

Updated `ErrorController` to use the new controller added in #5104 and simplify the logic.
- Refactor

refactor: update ErrorController to use SlotObserveController

---

packages/date-picker/src/vaadin-date-picker-mixin.d.ts

Cherry pick of #5112
(cherry picked from commit 1ab9eb24adee762f85c2e02de1566bbdca12c391)

docs: add JSDoc to DatePickerI18n interface (#5112) (CP: 23.3)

---

dev/grid-performance.html

Add a dev page for measuring grid render time and FPS while scrolling

chore: add grid performance dev page

---

packages/grid/src/vaadin-grid-column.js
packages/grid/src/vaadin-grid.js
packages/grid/test/column-groups.test.js

Manually cherry-pick #5128 to 23.3

refactor: reduce grid updateHeaderFooterRowVisibility call count (#5128)

---

packages/grid/src/vaadin-grid-column-reordering-mixin.js
packages/grid/src/vaadin-grid-column.js
packages/grid/src/vaadin-grid-scroll-mixin.js
packages/grid/src/vaadin-grid.js
packages/grid/test/column-reordering.test.js
packages/grid/test/column-resizing.test.js
packages/grid/test/frozen-columns.test.js
packages/grid/test/helpers.js

Manually cherry-pick https://github.com/vaadin/web-components/pull/5130 to 23.3

refactor: reduce grid updateFrozenColumn call count (#5130)

---

integration/tests/dialog-grid-pro.test.js
packages/context-menu/test/items.test.js
packages/date-picker/test/common.js
packages/field-highlighter/test/field-components.test.js
packages/grid-pro/test/edit-column-type.test.js
packages/grid-pro/test/edit-column.test.js
packages/grid-pro/test/grid-pro.test.js
packages/grid/test/basic.test.js
packages/grid/test/missing-imports.test.js
packages/login/test/login-submit.test.js
packages/menu-bar/test/sub-menu.test.js
packages/rich-text-editor/test/a11y.test.js
packages/select/test/renderer.test.js
packages/vaadin-themable-mixin/test/register-styles.test.js

The PR fixes the errors reported by the `no-unused-expressions` rule in tests.

test: fix no-unused-expressions rule in tests

---

packages/grid/src/vaadin-grid-column.js
packages/grid/test/column.test.js

Fixes https://github.com/vaadin/flow-components/issues/4429
Bugfix

fix: check cell parent before debouncing

---

packages/grid/src/vaadin-grid-active-item-mixin.js
packages/grid/test/renderers.test.js

Fixes [#4363](https://github.com/vaadin/flow-components/issues/4363) for `23.3` branch by backporting the check from master branch, see https://github.com/vaadin/flow-components/issues/4363#issuecomment-1355454087
- Bugfix

fix: use correct check for part attribute value (23.3)

---

packages/tabsheet/src/vaadin-tabsheet.js
packages/tabsheet/test/tabsheet.test.js

Fixes https://github.com/vaadin/flow-components/issues/4418
Bugfix

fix: support appending tabs in tabsheet lazily

---

packages/field-base/src/error-controller.d.ts
packages/field-base/src/helper-controller.d.ts
packages/field-base/src/label-controller.d.ts

Fixed type definitions for controllers updated in following PRs:
- #5104
- #5105

docs: update controllers types to use SlotObserveController

---

packages/accordion/src/vaadin-accordion-panel.js
packages/accordion/test/dom/__snapshots__/accordion-panel.test.snap.js
packages/details/src/content-controller.d.ts
packages/details/src/content-controller.js
packages/details/src/vaadin-details-mixin.js
packages/details/src/vaadin-details.js
packages/details/test/dom/__snapshots__/details.test.snap.js

Extracted from #5164 to make diff in that PR smaller.
The controller was duplicate, let's wry it only once.
- Refactor

refactor: extract ContentController to separate file

---

dev/app-layout.html
packages/app-layout/theme/lumo/vaadin-app-layout-styles.js
packages/app-layout/theme/lumo/vaadin-drawer-toggle-styles.js

I forgot to check the “touch optimized” mode in #5150.

fix: App Layout touch optimized navbar Lumo styles

---

packages/details/src/summary-controller.d.ts

This typo slipped in as part of #5164 🙈 
- Docs

docs: fix typo in SummaryController type definition

---

packages/select/src/vaadin-select.d.ts
packages/select/src/vaadin-select.js
packages/select/test/dom/__snapshots__/select.test.snap.js
packages/select/test/dom/select.test.js
packages/select/test/typings/select.types.ts

feat: add overlayClass property to vaadin-select

---

packages/tooltip/src/vaadin-tooltip.d.ts
packages/tooltip/src/vaadin-tooltip.js
packages/tooltip/test/dom/__snapshots__/tooltip.test.snap.js
packages/tooltip/test/dom/tooltip.test.js
packages/tooltip/test/typings/tooltip.types.ts

feat: add overlayClass property to vaadin-tooltip

---

packages/combo-box/src/vaadin-combo-box-mixin.d.ts
packages/combo-box/src/vaadin-combo-box-mixin.js
packages/combo-box/src/vaadin-combo-box.d.ts
packages/combo-box/src/vaadin-combo-box.js
packages/combo-box/test/dom/__snapshots__/combo-box.test.snap.js
packages/combo-box/test/dom/combo-box.test.js
packages/combo-box/test/typings/combo-box.types.ts

feat: add overlayClass property to vaadin-combo-box

---

packages/context-menu/src/vaadin-context-menu.js

Removed some obsolete listeners on the overlay shadow root, added because of ShadyDOM polyfill.
- Refactor

refactor: cleanup outdated context-menu listeners logic

---

packages/avatar-group/src/vaadin-avatar-group.d.ts
packages/avatar-group/src/vaadin-avatar-group.js
packages/avatar-group/test/dom/__snapshots__/avatar-group.test.snap.js
packages/avatar-group/test/dom/avatar-group.test.js
packages/avatar-group/test/typings/avatar-group.types.ts

feat: add overlayClass property to vaadin-avatar-group

---

packages/combo-box/src/vaadin-combo-box-scroller.js
packages/combo-box/test/dom/__snapshots__/combo-box.test.snap.js
packages/time-picker/test/dom/__snapshots__/time-picker.test.snap.js

Manual cherry-pick of #5254 to `23.2` branch.
- Cherry-pick

fix: set aria-setsize attribute on items instead of the scroller (#5254) (CP: 23.2)

---

packages/combo-box/src/vaadin-combo-box-scroller.js
packages/combo-box/test/dom/__snapshots__/combo-box.test.snap.js
packages/time-picker/test/dom/__snapshots__/time-picker.test.snap.js

Manual cherry-pick of #5254 to `23.3` branch.
- Cherry-pick

fix: set aria-setsize attribute on items instead of the scroller (#5254) (CP: 23.3)

---

dev/input-container.html

Added dev page for `vaadin-input-container` component.

chore: add dev page for vaadin-input-container

---

packages/charts/src/vaadin-chart.d.ts
packages/charts/src/vaadin-chart.js
packages/charts/test/chart-properties.test.js

This PR adds Highcharts annotations support to the web component.
Related to Flow component [PR](https://github.com/vaadin/flow-components/pull/4481)
Partially fixes #[1446](https://github.com/vaadin/flow-components/issues/1446)

feat: add highcharts annotations support to charts

---

packages/date-time-picker/test/dom/__snapshots__/date-time-picker.test.snap.js
packages/date-time-picker/test/dom/date-time-picker.test.js

Extracted from #5251. 
The `vaadin-date-time-picker` was missing some snapshot tests, so I added them.
- Tests

test: improve vaadin-date-time-picker snapshot tests

---

packages/multi-select-combo-box/test/dom/__snapshots__/multi-select-combo-box.test.snap.js
packages/multi-select-combo-box/test/dom/multi-select-combo-box.test.js

The `vaadin-multi-select-combo-box` was missing some snapshot tests, so I added them.
This will be needed for adding `overlayClass` property, which is tested with snapshots.
- Tests

test: improve vaadin-multi-select-combo-box snapshots

---

dev/progress-bar.html

This component was lacking a dev page, so I added it.

chore: add dev page for vaadin-progress-bar

---

packages/dialog/src/vaadin-dialog.d.ts
packages/dialog/src/vaadin-dialog.js
packages/dialog/test/dom/__snapshots__/dialog.test.snap.js
packages/dialog/test/dom/dialog.test.js
packages/dialog/test/typings/dialog.types.ts

Related to https://github.com/vaadin/web-components/issues/5121
Depends on https://github.com/vaadin/web-components/pull/5308
- Feature

feat: add overlayClass property to vaadin-dialog

---

packages/checkbox/theme/lumo/vaadin-checkbox-styles.js
packages/checkbox/theme/material/vaadin-checkbox-styles.js
packages/radio-group/theme/lumo/vaadin-radio-button-styles.js
packages/radio-group/theme/material/vaadin-radio-button-styles.js
packages/vaadin-lumo-styles/style.js
packages/vaadin-material-styles/style.js

Follow-up to #5295
This change is needed to avoid breaking custom themes.
- Refactor

refactor: make globals opt-in for backwards compatibility

---

packages/login/src/vaadin-login-overlay.d.ts
packages/login/src/vaadin-login-overlay.js
packages/login/test/dom/__snapshots__/login-overlay.test.snap.js
packages/login/test/dom/login-overlay.test.js
packages/login/test/typings/login.types.ts

Related to https://github.com/vaadin/web-components/issues/5121
Based on #5207
- Feature

feat: add overlayClass property to vaadin-login-overlay

---

packages/notification/src/vaadin-notification.d.ts
packages/notification/src/vaadin-notification.js
packages/notification/test/dom/__snapshots__/notification.test.snap.js
packages/notification/test/dom/notification.test.js
packages/notification/test/typings/notification.types.ts

Related to https://github.com/vaadin/web-components/issues/5121
Based on #5207
Depends on #5318
- Feature

feat: add overlayClass property to vaadin-notification

---

PULL_REQUEST_TEMPLATE.md

Add new checkbox to the PR template.

chore: add new checkbox to the PR template

---

packages/combo-box/src/vaadin-combo-box-scroller.js
packages/combo-box/test/polymer.test.js

Fixes https://github.com/vaadin/web-components/issues/5326
Bugfix

fix: do not throw when combo-box is templatized

---

packages/component-base/test/resize-mixin.test.js

Fix resize-mixin tests that started failing on their own on `master`

test: fix flaky resize-mixin tests

---

packages/list-box/theme/lumo/vaadin-list-box-styles.js
packages/list-box/theme/material/vaadin-list-box-styles.js

feat: export list-box theme styles as CSS tagged literals

---

packages/context-menu/src/vaadin-contextmenu-items-mixin.js
packages/menu-bar/src/vaadin-menu-bar-list-box.js
packages/menu-bar/src/vaadin-menu-bar-submenu.js
packages/menu-bar/src/vaadin-menu-bar.d.ts
packages/menu-bar/src/vaadin-menu-bar.js
packages/menu-bar/test/dom/__snapshots__/menu-bar.test.snap.js
packages/menu-bar/test/menu-bar.test.js
packages/menu-bar/theme/lumo/vaadin-menu-bar-list-box-styles.js
packages/menu-bar/theme/lumo/vaadin-menu-bar.js
packages/menu-bar/theme/material/vaadin-menu-bar-list-box-styles.js
packages/menu-bar/theme/material/vaadin-menu-bar.js

Part of #3010
Based on #5353 and `_tagNamePrefix` API added in that PR.
- Refactor

refactor!: update menu-bar to use vaadin-menu-bar-list-box

---

packages/context-menu/src/vaadin-context-menu-item.d.ts
packages/context-menu/src/vaadin-context-menu-item.js
packages/context-menu/test/typings/context-menu.types.ts
packages/context-menu/theme/lumo/vaadin-context-menu-item-styles.js
packages/context-menu/theme/lumo/vaadin-context-menu.js
packages/context-menu/theme/material/vaadin-context-menu-item-styles.js
packages/context-menu/theme/material/vaadin-context-menu.js

refactor!: make vaadin-context-menu-item not extend vaadin-item

---

packages/context-menu/src/vaadin-context-menu-list-box.d.ts
packages/context-menu/src/vaadin-context-menu-list-box.js
packages/context-menu/test/typings/context-menu.types.ts
packages/context-menu/test/visual/lumo/context-menu.test.js
packages/context-menu/test/visual/material/context-menu.test.js
packages/context-menu/theme/lumo/vaadin-context-menu-list-box-styles.js
packages/context-menu/theme/lumo/vaadin-context-menu.js
packages/context-menu/theme/material/vaadin-context-menu-list-box-styles.js
packages/context-menu/theme/material/vaadin-context-menu.js

refactor!: make vaadin-context-menu-list-box not extend list-box

---

packages/context-menu/test/items-theme.test.js
packages/context-menu/test/items.test.js

Extracts theme propagation tests to improve the readability of `items.test.js`.
> **Note**
> Remember to enable the `Hide whitespace` option to reduce the diff.

test: extract theme propagation tests

---

packages/select/src/vaadin-select-list-box.d.ts
packages/select/src/vaadin-select-list-box.js
packages/select/test/typings/select.types.ts
packages/select/theme/lumo/vaadin-select-styles.js
packages/select/theme/lumo/vaadin-select.js
packages/select/theme/material/vaadin-select-styles.js
packages/select/theme/material/vaadin-select.js

Same as #5367 but for `vaadin-select-list-box`. Note, I also added TS definitions for consistency.

refactor!: make vaadin-select-list-box not extend list-box

---

packages/context-menu/src/vaadin-context-menu.d.ts
packages/context-menu/src/vaadin-context-menu.js
packages/context-menu/src/vaadin-contextmenu-items-mixin.d.ts
packages/context-menu/src/vaadin-contextmenu-items-mixin.js

Fixes indents in JSDoc code examples.
Extracted from #5380

chore: format JSDoc code examples

---

packages/overlay/src/vaadin-overlay.d.ts
packages/overlay/src/vaadin-overlay.js

Based on https://github.com/vaadin/web-components/pull/5393#discussion_r1086622729

docs: update JSDoc and typings, mark some methods as private

---

packages/avatar-group/src/vaadin-avatar-group.js
packages/item/src/vaadin-item.js
packages/item/test/dom/__snapshots__/item.test.snap.js
packages/item/test/dom/item.test.js
packages/list-box/src/vaadin-list-box.js
packages/list-box/test/dom/__snapshots__/list-box.test.snap.js
packages/list-box/test/dom/list-box.test.js
packages/list-box/test/list-box.test.js
packages/menu-bar/test/dom/__snapshots__/menu-bar.test.snap.js
packages/select/src/vaadin-select.js
packages/select/test/dom/__snapshots__/select.test.snap.js
packages/vaadin-list-mixin/test/list-mixin.test.js
packages/vaadin-list-mixin/vaadin-multi-select-list-mixin.js

Manual cherry-pick of #5401 to 23.3 branch.
- Cherry-pick

fix!: set correct role attribute on the list-box and item (#5401) (CP: 23.3)

---

packages/avatar-group/src/vaadin-avatar-group.js
packages/item/src/vaadin-item.js
packages/item/test/dom/__snapshots__/item.test.snap.js
packages/item/test/dom/item.test.js
packages/list-box/src/vaadin-list-box.js
packages/list-box/test/dom/__snapshots__/list-box.test.snap.js
packages/list-box/test/dom/list-box.test.js
packages/list-box/test/list-box.test.js
packages/menu-bar/test/dom/__snapshots__/menu-bar.test.snap.js
packages/select/src/vaadin-select.js
packages/select/test/dom/__snapshots__/select.test.snap.js
packages/vaadin-list-mixin/test/list-mixin.test.js
packages/vaadin-list-mixin/vaadin-multi-select-list-mixin.js

Manual cherry-pick of #5401 to 23.2 branch.
- Cherry-pick

fix!: set correct role attribute on the list-box and item (#5401) (CP: 23.2)

---

packages/combo-box/src/vaadin-combo-box-overlay.js
packages/combo-box/test/overlay-position.test.js
packages/overlay/src/vaadin-overlay-position-mixin.d.ts
packages/overlay/src/vaadin-overlay-position-mixin.js
packages/overlay/test/position-mixin.test.js
packages/overlay/test/typings/overlay.types.ts

Manual cherry-pick of #5432 to 23.3 branch.
- Cherry-pick

fix: add required vertical space for combo-box overlay (#5432)

---

packages/date-picker/theme/lumo/vaadin-date-picker-year-styles.js
packages/form-layout/theme/lumo/vaadin-form-item-styles.js
packages/vaadin-lumo-styles/mixins/required-field.js

refactor: replace bullet with corresponding Unicode entity

---

packages/crud/theme/material/vaadin-crud-styles.js

refactor: replace edit icon with corresponding Unicode entity

---

packages/grid/test/column-group.test.js
packages/grid/test/column.test.js

Remove the use of `<template>` in the `<vaadin-grid>` `column.test.js` and `column-group.test.js` tests.
Tests

test: update grid column and column-group tests to not use templates

---

packages/rich-text-editor/src/vaadin-rich-text-editor-toolbar-styles.js

refactor: replace quote icon with corresponding Unicode entity

---

packages/field-base/src/styles/clear-button-styles.js

refactor: replace clear icon with corresponding Unicode entity

---

packages/number-field/src/vaadin-number-field.js

refactor: replace minus icon with corresponding Unicode entity

---

packages/grid/test/row-details.test.js

Remove the use of `<template>` in the `<vaadin-grid>` `row-details.test.js` tests.
Tests

test: update grid row details tests to not use templates

---

packages/grid-pro/test/edit-column-renderer.test.js
packages/grid-pro/test/edit-column-type.test.js
packages/grid-pro/test/edit-column.test.js
packages/grid-pro/test/grid-pro.test.js
packages/grid-pro/test/keyboard-navigation.test.js

Remove the use of `<template>` in the `<vaadin-grid-pro>` tests.
Tests

test: update grid-pro tests to not use templates

---

packages/field-base/test/slot-styles-mixin.test.js

This PR fixes one of the tests that fail with the latest Playwright, see https://github.com/vaadin/web-components/issues/4846#issuecomment-1420855409
- Tests

test: fix SlotStylesMixin tests in Firefox, add LitElement tests

---

packages/text-area/test/text-area.test.js

Fixed two tests that fail with the recent Playwright, see https://github.com/vaadin/web-components/pull/5495
- Tests

test: update text-area tests to pass in latest Firefox

---

packages/button/src/vaadin-button-base.d.ts

Follow-up to #5551. 
These were renamed when creating a separate PR from #5301 but I missed to update typings 🙈 
- Refactor / fix

refactor: fix incorrect exports in the new button base

---

packages/checkbox/package.json
packages/checkbox/src/vaadin-checkbox-mixin.d.ts
packages/checkbox/src/vaadin-checkbox-mixin.js
packages/checkbox/src/vaadin-checkbox.js

Same as #5520 but for `vaadin-checkbox`.
- Refactor

refactor: extract checkbox logic to reusable CheckboxMixin

---

packages/context-menu/src/vaadin-contextmenu-items-mixin.js

Refactored a huge method (118 lines of code) to make the logic cleaner. Also, added some comments.
- Refactor

refactor: simplify and split context-menu ItemsMixin logic

---

packages/a11y-base/src/aria-hidden.js
packages/a11y-base/test/aria-hidden.test.js

This PR fixes a few corner cases that I missed to cover while converting TS source code to JS.
- Bugfix

fix: improve aria-hidden error handling, add missing tests

---

packages/date-picker/src/vaadin-date-picker-mixin.js
packages/date-picker/test/wai-aria.test.js

Fixes #4314
- Accessibility enhancement

feat: set aria-hidden on other elements on overlay opening

---

packages/tooltip/src/vaadin-tooltip.js
packages/tooltip/test/tooltip.test.js

Back-ports https://github.com/vaadin/web-components/pull/5668 to v24.0
Fixes https://github.com/vaadin/web-components/issues/5667

fix: process all intersection observer event entries (#5668) (CP: 24.0)

---

.editorconfig
.gitattributes
.gitignore
.prettierrc
scripts/buildWebtypes.js
wtr-utils.js

CP to 23.3
There was a conflict in wtr-utils.js -> another branch is compared there than on main

chore: allow windows developers to work with this repo without hassle (#5686) (CP: 23.3)

---

packages/details/src/vaadin-details.d.ts
packages/details/src/vaadin-details.js

The PR removes no longer existing parts from the JSDoc.
A follow-up to https://github.com/vaadin/web-components/pull/5093

docs: remove no longer existing parts from JSDoc

---

packages/menu-bar/src/vaadin-menu-bar-buttons-mixin.js
packages/menu-bar/test/menu-bar.test.js

fix: keep custom class name for overflow menu items

---

packages/menu-bar/test/menu-bar.test.js

test: add test for menu items keeping custom class name

---

packages/details/README.md

chore: fix a typo in the vaadin-details component README.md

---

dev/icon.html

Added missing example of creating a custom iconset based on the internal discussion.

chore: add custom iconset example to icon dev page

---

packages/login/src/vaadin-login-mixin.d.ts
packages/login/src/vaadin-login-mixin.js

Adds new properties to the JSDoc.

docs: document new login error message props

---

packages/notification/theme/material/vaadin-notification-styles.js

refactor: update notification Material theme to use inset

---

packages/component-base/src/virtualizer-iron-list-adapter.js
packages/grid/test/hidden-grid.test.js

fix: do not reset scroll position when hiding grid (#5899) (CP: 23.3)

---

packages/a11y-base/src/aria-modal-controller.d.ts
packages/a11y-base/src/aria-modal-controller.js
packages/a11y-base/test/aria-modal-controller.test.js

Pre-requisite for #5943
See https://github.com/vaadin/web-components/pull/5943#discussion_r1218024306
- Refactor

refactor: allow to pass callback to AriaModalController

---

packages/crud/src/vaadin-crud.js
packages/crud/test/crud-buttons.test.js

fix!: only modify text content for default slotted buttons (#5955) (CP: 24.1)

---

packages/overlay/test/renderer.test.js

Some adjustments to `renderer.test.js` based on my Lit conversion research.
- Tests

test: refactor and simplify vaadin-overlay renderer tests

---

packages/email-field/src/vaadin-email-field.js
packages/email-field/src/vaadin-lit-email-field.js
packages/email-field/test/email-field.common.js
packages/field-base/test/pattern-mixin.test.js

Cherry-pick of https://github.com/vaadin/web-components/pull/6046

fix: properly escape email pattern (#6046) (CP: 24.1)

---

packages/email-field/src/vaadin-email-field.js
packages/field-base/test/pattern-mixin.test.js

Cherry-pick of https://github.com/vaadin/web-components/pull/6046

fix: properly escape email pattern (#6046) (CP: 23.3)

---

packages/email-field/src/vaadin-email-field.js
packages/email-field/src/vaadin-lit-email-field.js
packages/email-field/test/email-field.common.js
packages/field-base/test/pattern-mixin.test.js

Cherry-pick of https://github.com/vaadin/web-components/pull/6046

fix: properly escape email pattern (#6046) (CP: 24.0)

---

integration/package.json
integration/tests/notification-tooltip.test.js
packages/tooltip/src/vaadin-tooltip-overlay.js

fix: display tooltips over notifications (#6074) (CP: 24.1)

---

packages/grid/src/vaadin-grid-styles.js
packages/grid/theme/lumo/vaadin-grid-styles.js
packages/grid/theme/material/vaadin-grid-styles.js

Updated styles to fix warning reported by Stylelint 15.
- Refactor

refactor: update grid styles to use inset shorthand

---

packages/field-highlighter/src/vaadin-field-outline.js
packages/field-highlighter/theme/lumo/vaadin-field-outline-styles.js

Updated styles to fix warning reported by Stylelint 15.
- Refactor

refactor: update field highlighter styles to use inset shorthand

---

packages/overlay/test/basic.test.js

1. Renamed `overlay.test.js` to `basic.test.js` and added some missing `await` in preparation for Lit conversion;
2. Removed the "wrapped overlay" suite added by https://github.com/vaadin/vaadin-overlay/commit/9da2f48db2a991b14bc60f979854823989aaa121 which is no longer needed since https://github.com/vaadin/vaadin-overlay/pull/140/commits/a7e6a86c71f9a680c3a5d7f64ea4483009685b0c where exit modal state timing was changed (and is using private API).
- Tests

test: cleanup basic overlay test suite, add missing await

---

packages/field-base/src/clear-button-mixin.js
packages/field-base/test/clear-button-mixin.test.js
packages/field-base/test/input-control-mixin.test.js

fix!: align how clear button works with combo-box behavior (#6100) (CP: 24.0)

---

packages/select/test/select.test.js

Small improvements to `vaadin-select` unit tests extracted from the experimental [Lit conversion](https://github.com/vaadin/web-components/compare/lit/select) branch.
- Tests

test: simplify and cleanup vaadin-select unit tests

---

packages/avatar/src/vaadin-avatar-mixin.d.ts
packages/avatar/src/vaadin-avatar-mixin.js
packages/avatar/src/vaadin-avatar-styles.js
packages/avatar/src/vaadin-avatar.d.ts
packages/avatar/src/vaadin-avatar.js
packages/avatar/test/avatar.test.js

Extracts base avatar logic into a mixin that can be reused for a Lit version of the component. Also extracts styles into a reusable module.
- Refactoring

refactor: extract base avatar logic into mixin

---

packages/select/src/vaadin-select-value-button-styles.js
packages/select/src/vaadin-select-value-button.js

refactor: extract select value button styles to css literal

---

packages/component-base/src/controller-mixin.js
packages/component-base/test/controller-mixin.test.js

Related to https://github.com/vaadin/web-components/pull/6195#discussion_r1267845097
- Refactor

refactor: do not override LitElement methods in ControllerMixin

---

packages/details/src/vaadin-details-base-mixin.d.ts
packages/details/src/vaadin-details-base-mixin.js
packages/details/src/vaadin-details.d.ts
packages/details/src/vaadin-details.js

Similar to #6195 but for `vaadin-details`.
- Refactor

refactor: extract base vaadin-details logic to reusable mixin

---

packages/details/test/details.test.js

Updated `vaadin-details` unit tests to pass with `LitElement` based version of the component.
- Tests

test: update details unit tests to wait for next update

---

packages/component-base/src/slot-controller.js
packages/component-base/src/slot-observer.d.ts
packages/component-base/src/slot-observer.js
packages/component-base/test/slot-observer.test.js

feat: add SlotObserver and update SlotController to use it

---

packages/app-layout/src/vaadin-app-layout.js
packages/app-layout/src/vaadin-drawer-toggle.js
packages/app-layout/test/app-layout.test.js
packages/app-layout/test/drawer-toggle.test.js

Replaced usage of `FlattenedNodesObserver` with vanilla `slotchange` event.
- Refactor

refactor: update app-layout and drawer-toggle to use slotchange

---

packages/split-layout/src/vaadin-split-layout-styles.d.ts
packages/split-layout/src/vaadin-split-layout-styles.js
packages/split-layout/src/vaadin-split-layout.js

refactor: extract split-layout styles to reusable css literal

---

packages/split-layout/package.json
packages/split-layout/src/vaadin-split-layout-mixin.d.ts
packages/split-layout/src/vaadin-split-layout-mixin.js
packages/split-layout/src/vaadin-split-layout.d.ts
packages/split-layout/src/vaadin-split-layout.js

refactor: extract vaadin-split-layout logic to reusable mixin

---

packages/a11y-base/src/list-mixin.js
packages/accordion/src/vaadin-accordion.js
packages/checkbox-group/src/vaadin-checkbox-group.js
packages/component-base/test/slot-observer.test.js
packages/radio-group/src/vaadin-radio-group.js
packages/select/test/renderer.common.js
packages/tabsheet/src/vaadin-tabsheet.js

Depends on #6218
Replaced `FlattenedNodesObserver` with the newly added `SlotObserver` in several components.
- Refactor

refactor: update to use SlotObserver for handling slot changes

---

packages/combo-box/test/validation.test.js
packages/multi-select-combo-box/test/helpers.js
packages/multi-select-combo-box/test/validation.test.js
packages/time-picker/test/validation.test.js

The PR improves test coverage of the blur validation functionality in `combo-box`, `time-picker` and `multi-select-combo-box`.
Part of #6146

test: improve test coverage of blur validation

---

packages/form-layout/src/vaadin-form-layout.js

Related to #6206
This PR replaces `FlattenedNodesObserver` with `MutationObserver` with `{ childList: true }` to track adding elements to `vaadin-form-layout` (and then observe `colspan` attribute changes on them using a separate observer). 
- Refactor

refactor: update form-layout to use MutationObserver for children

---

packages/date-picker/src/vaadin-date-picker-mixin.js
packages/date-picker/test/events.test.js
packages/date-picker/test/validation.test.js

The PR simplifies the date-picker's value change logic on blur.
Part of #6146

refactor: simplify value change logic on blur

---

packages/crud/test/crud-buttons.test.js
packages/crud/test/crud-editor.test.js
packages/crud/test/crud.test.js
packages/crud/test/dom/__snapshots__/crud.test.snap.js
packages/crud/test/dom/crud.test.js

test: update CRUD tests to use desktop breakpoint by default

---

packages/custom-field/test/custom-field.test.js

Related to https://github.com/vaadin/web-components/issues/6235
- Tests

test: update custom-field unit tests, add missing await

---

packages/component-base/src/overflow-controller.js
packages/component-base/test/overflow-controller.test.js

Replaced `FlattenedNodesObserver` with the native `MutationObserver` to handle nodes adding / removal.
- Refactor

refactor: update OverflowController to use MutationObserver

---

packages/select/test/validation.common.js

The PR improves test coverage of select's validation functionality.
Part of #6146

test: improve validation test coverage

---

packages/select/test/validation.common.js

Extracts the required constraint tests into an individual test suite, as it's done in other similar components.
Part of #6146

test: extract required constraint tests into individual test suite

---

packages/login/src/vaadin-login-form-wrapper-styles.d.ts
packages/login/src/vaadin-login-form-wrapper-styles.js
packages/login/src/vaadin-login-form-wrapper.js
packages/login/src/vaadin-login-overlay-wrapper-styles.d.ts
packages/login/src/vaadin-login-overlay-wrapper-styles.js
packages/login/src/vaadin-login-overlay-wrapper.js

Extracted `css` tagged literals to be reused by Polymer and Lit versions.
- Refactor

refactor: extract login overlay and form styles css literals

---

packages/login/test/login-form-wrapper-styles.js
packages/login/test/login-form.test.js
packages/login/test/login-overlay.test.js
packages/login/test/login-submit.test.js

Updated `vaadin-login-overlay` and `vaadin-login-form` tests to pass with LitElement based versions.
- Tests

test: update login overlay and form tests, add missing await

---

packages/details/theme/lumo/vaadin-details-summary.js
packages/details/theme/lumo/vaadin-details.js
packages/details/theme/material/vaadin-details-summary.js
packages/details/theme/material/vaadin-details.js
packages/details/vaadin-details-summary.d.ts
packages/details/vaadin-details-summary.js

feat: add root level entrypoint for vaadin-details-summary

---

packages/accordion/theme/lumo/vaadin-accordion-heading.js
packages/accordion/theme/lumo/vaadin-accordion-panel.js
packages/accordion/theme/material/vaadin-accordion-heading.js
packages/accordion/theme/material/vaadin-accordion-panel.js
packages/accordion/vaadin-accordion-heading.d.ts
packages/accordion/vaadin-accordion-heading.js

feat: add root level entrypoint for vaadin-accordion-heading

---

packages/date-picker/package.json
packages/date-picker/src/vaadin-date-picker-overlay-styles.js
packages/date-picker/src/vaadin-lit-date-picker-overlay.js
packages/date-picker/src/vaadin-lit-date-picker.js

experiment: add LitElement version of date-picker overlay

---

packages/custom-field/package.json
packages/custom-field/src/vaadin-lit-custom-field.d.ts
packages/custom-field/src/vaadin-lit-custom-field.js
packages/custom-field/test/custom-field-lit.test.js
packages/custom-field/test/custom-field-polymer.test.js
packages/custom-field/test/custom-field.common.js
packages/custom-field/test/keyboard-lit.test.js
packages/custom-field/test/keyboard-polymer.test.js
packages/custom-field/test/keyboard.common.js
packages/custom-field/test/slot-wrapper-lit.test.js
packages/custom-field/test/slot-wrapper-polymer.test.js
packages/custom-field/test/slot-wrapper.common.js

experiment: add LitElement based version of vaadin-custom-field

---

packages/login/package.json
packages/login/src/vaadin-lit-login-form-wrapper.js
packages/login/src/vaadin-lit-login-form.d.ts
packages/login/src/vaadin-lit-login-form.js
packages/login/src/vaadin-lit-login-overlay-wrapper.js
packages/login/src/vaadin-lit-login-overlay.d.ts
packages/login/src/vaadin-lit-login-overlay.js
packages/login/src/vaadin-login-form-mixin.js
packages/login/src/vaadin-login-overlay-mixin.js
packages/login/test/dom/login-form.test.js
packages/login/test/login-form-lit.test.js
packages/login/test/login-form-polymer.test.js
packages/login/test/login-form.common.js
packages/login/test/login-overlay-lit.test.js
packages/login/test/login-overlay-polymer.test.js
packages/login/test/login-overlay.common.js
packages/login/test/login-submit-lit.test.js
packages/login/test/login-submit-polymer.test.js
packages/login/test/login-submit.common.js

experiment: add LitElement versions of login overlay and form

---

packages/custom-field/test/custom-field.common.js
packages/custom-field/test/helpers.js
packages/custom-field/test/slot-wrapper.common.js
packages/custom-field/test/validation.test.js

The PR cleans up custom-field's validation tests and also improves test coverage of the validation functionality.
Part of #6146

test: clean up validation tests, improve test coverage

---

packages/upload/package.json
packages/upload/src/vaadin-lit-upload-file-list.js
packages/upload/src/vaadin-lit-upload-icon.js
packages/upload/src/vaadin-lit-upload.d.ts
packages/upload/src/vaadin-lit-upload.js
packages/upload/src/vaadin-upload-mixin.js
packages/upload/test/a11y-lit.test.js
packages/upload/test/a11y-polymer.test.js
packages/upload/test/a11y.common.js
packages/upload/test/adding-files-lit.test.js
packages/upload/test/adding-files-polymer.test.js
packages/upload/test/adding-files.common.js
packages/upload/test/file-list-lit.test.js
packages/upload/test/file-list-polymer.test.js
packages/upload/test/file-list.common.js
packages/upload/test/keyboard-navigation-lit.test.js
packages/upload/test/keyboard-navigation-polymer.test.js
packages/upload/test/keyboard-navigation.common.js
packages/upload/test/slots-lit.test.js
packages/upload/test/slots-polymer.test.js
packages/upload/test/slots.common.js
packages/upload/test/upload-lit.test.js
packages/upload/test/upload-polymer.test.js
packages/upload/test/upload.common.js

experiment: add LitElement version of vaadin-upload

---

packages/combo-box/test/keyboard.test.js
packages/combo-box/test/scrolling.test.js

Removed some test helpers that are no longer used.
- Tests

test: cleanup combo-box tests, remove not used helpers

---

integration/tests/component-tooltip.test.js
packages/combo-box/src/vaadin-combo-box.js
packages/date-picker/src/vaadin-date-picker.js
packages/date-picker/src/vaadin-lit-date-picker.js
packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js
packages/number-field/src/vaadin-lit-number-field.js
packages/number-field/src/vaadin-number-field.js
packages/select/src/vaadin-select-base-mixin.js
packages/text-area/src/vaadin-lit-text-area.js
packages/text-area/src/vaadin-text-area.js
packages/text-field/src/vaadin-lit-text-field.js
packages/text-field/src/vaadin-text-field.js
packages/time-picker/src/vaadin-time-picker.js

Fixes #6287
Depends on #6320
- Refactor

refactor: set correct ariaTarget on the input fields tooltip

---

packages/accordion/test/accordion-panel.test.js
packages/details/src/collapsible-mixin.js
packages/details/test/details.common.js

fix: prevent toggling opened state on click when disabled

---

packages/date-picker/src/vaadin-date-picker-mixin.js

The PR simplifies date-picker's parsing and formatting logic.

refactor: simplify parsing and formatting logic

---

package.json
yarn.lock

Updated only these dev dependencies to see if the lint step passes as expected.

chore: update ESLint and TypeScript to latest versions

---

packages/map/LICENSE

Follow-up to #6346 
I missed to include `vaadin-map` to the previous PR, let's update it now 🙈 
- License

chore: update LICENSE file for vaadin-map package

---

packages/select/src/vaadin-select-base-mixin.d.ts
packages/select/test/typings/select.types.ts

fix: add missing mixins to SelectBaseMixin types

---

packages/accordion/test/accordion-panel.test.js
packages/details/src/collapsible-mixin.js
packages/details/test/details.common.js

fix: do not toggle opened state on summary anchor click

---

packages/number-field/test/number-field.common.js
packages/number-field/test/value-control-buttons-lit.test.js
packages/number-field/test/value-control-buttons-polymer.test.js
packages/number-field/test/value-control-buttons.common.js

The PR extracts the tests for the value control buttons into an individual test file, making space for future tests in `number-field.test.js`.
Part of #6158

test: extract value control buttons tests into individual file

---

packages/time-picker/src/vaadin-time-picker.js
packages/time-picker/test/validation.test.js

fix: do not fire change event for time-picker bad input

---

packages/multi-select-combo-box/test/selecting-items.test.js

While working on #6372 it was noticed that we are missing some tests in this component. Let's fix that.
- Test

test: add missing test for selecting with autoOpenDisabled

---

packages/button/src/vaadin-button-mixin.js
packages/button/test/button.common.js

Fixes https://github.com/vaadin/flow/issues/14190
Fixes https://github.com/vaadin/flow/issues/14187

fix: do not click on Enter and Space when using key modifiers

---

packages/time-picker/src/vaadin-time-picker.js
packages/time-picker/test/events.test.js

The PR cherry-picks the following fixes to `24.1`:
- https://github.com/vaadin/web-components/pull/6396/
- https://github.com/vaadin/web-components/pull/6420

fix: do not fire change event if the value has not changed (#6396) (CP: 24.1)

---

integration/package.json
integration/tests/confirm-dialog-fields.test.js
packages/confirm-dialog/src/vaadin-confirm-dialog.js

Cherry-pick of #6443 to `24.1` branch.
- Cherry-pick

fix: wrap nodes correctly to ensure proper initialization (#6443) (CP: 24.1)

---

packages/icon/test/icon-font.test.js

Fix a broken icon test case.
Tests

test: fix a broken icon test case

---

packages/upload/src/vaadin-upload-mixin.js

See https://github.com/vaadin/web-components/pull/6460#pullrequestreview-1617337284
- Refactor

refactor: remove sync flag from maxFilesReached property

---

packages/cookie-consent/src/vaadin-cookie-consent.js
packages/cookie-consent/test/cookie-consent.test.js

fix: remove hardcoded aria-label attributes from links (#6492) (CP: 23.3)

---

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.d.ts
packages/multi-select-combo-box/test/typings/multi-select-combo-box.types.ts

Added missing event reported at https://github.com/vaadin/web-components/issues/4900#issuecomment-1512927512
- Feature

feat: add multi-select-combo-box opened-changed event type

---

packages/rich-text-editor/src/vaadin-rich-text-editor.js
packages/rich-text-editor/test/a11y.test.js

fix: toolbar should have role="toolbar" for better screen reader support

---

dev/split-layout.html
packages/split-layout/theme/lumo/vaadin-split-layout-styles.js

Small cleaning of styles at the same time as I try to fix the misaligned Split Layout handle for the “small” variant. Adds the “small” and ”minimal” variants to the dev test page.
Fixes #6252

fix: adjust handle alignment for small and minimal, cleanup styles

---

wtr-utils.js

Update the `web-test-runner` change detection script to use `24.2` as a base branch for Vaadin 24.2

chore: update change detection branch to 24.2

---

packages/vaadin-lumo-styles/typography-global.js

fix: remove "false" from lumo typography global styles

---

packages/component-base/src/data-provider-controller/cache.d.ts
packages/component-base/src/data-provider-controller/cache.js
packages/component-base/src/data-provider-controller/data-provider-controller.d.ts
packages/component-base/src/data-provider-controller/helpers.d.ts
packages/component-base/test/typings/data-provider-controller.types.ts
packages/component-base/test/typings/data-provider-controller/cache.types.ts
packages/component-base/test/typings/data-provider-controller/data-provider-controller.types.ts
packages/grid/src/vaadin-grid-data-provider-mixin.d.ts

Adds TypeScript declarations for the data provider controller.
Follow-up to #5961

feat: add TS declarations for data provider controller

---

packages/confirm-dialog/src/vaadin-confirm-dialog.js
packages/confirm-dialog/test/dom/__snapshots__/confirm-dialog.test.snap.js

Cherry-pick of #6540 to `24.2` branch.
- Cherry-pick

fix: add vaadin-button src import to unstyled confirm-dialog (#6540) (CP: 24.2)

---

packages/checkbox/src/vaadin-checkbox.js

fix: unset input width/height to avoid issue with UA styles (#6550) (CP: 23.3)

---

wtr-utils.js

Same as https://github.com/vaadin/web-components/pull/6530 but for integration tests
Part of https://github.com/vaadin/components-team-tasks/issues/613

chore: config integration tests to retry on failure

---

packages/tooltip/package.json
packages/tooltip/src/vaadin-lit-tooltip-overlay.js
packages/tooltip/src/vaadin-lit-tooltip.d.ts
packages/tooltip/src/vaadin-lit-tooltip.js
packages/tooltip/src/vaadin-tooltip-mixin.js
packages/tooltip/test/position-styles.js
packages/tooltip/test/tooltip-lit.test.js
packages/tooltip/test/tooltip-offset-lit.test.js
packages/tooltip/test/tooltip-offset-polymer.test.js
packages/tooltip/test/tooltip-offset.common.js
packages/tooltip/test/tooltip-polymer.test.js
packages/tooltip/test/tooltip-position-lit.test.js
packages/tooltip/test/tooltip-position-polymer.test.js
packages/tooltip/test/tooltip-position.common.js
packages/tooltip/test/tooltip-timers-lit.test.js
packages/tooltip/test/tooltip-timers-polymer.test.js
packages/tooltip/test/tooltip-timers.common.js
packages/tooltip/test/tooltip.common.js

experiment: add LitElement based version of vaadin-tooltip

---

packages/confirm-dialog/theme/lumo/vaadin-confirm-dialog-styles.js
packages/confirm-dialog/theme/material/vaadin-confirm-dialog-styles.js

Fix for the finding from https://github.com/vaadin/web-components/pull/6539#discussion_r1340101606
- Refactor

refactor: add button styles imports to confirm-dialog styles

---

packages/confirm-dialog/package.json
packages/confirm-dialog/src/vaadin-confirm-dialog-mixin.js
packages/confirm-dialog/src/vaadin-lit-confirm-dialog-overlay.js
packages/confirm-dialog/src/vaadin-lit-confirm-dialog.d.ts
packages/confirm-dialog/src/vaadin-lit-confirm-dialog.js
packages/confirm-dialog/test/confirm-dialog-lit.test.js
packages/confirm-dialog/test/confirm-dialog-polymer.test.js
packages/confirm-dialog/test/confirm-dialog.common.js

experiment: add LitElement based version of vaadin-confirm-dialog

---

.github/ISSUE_TEMPLATE/bug-report.yml

Related `flow-components` PR: https://github.com/vaadin/flow-components/pull/5522

chore: improve bug report template

---

packages/component-base/src/data-provider-controller/data-provider-controller.js
packages/component-base/test/data-provider-controller-cache.test.js
packages/component-base/test/data-provider-controller-data-loading.test.js
packages/component-base/test/data-provider-controller-events.test.js
packages/component-base/test/data-provider-controller.test.js

The PR contains unit tests for `DataProviderController`. 
Follow-up to #5961

test: add unit tests for DataProviderController

---

packages/input-container/package.json
packages/input-container/src/vaadin-lit-input-container.js
packages/input-container/test/input-container-lit.test.js
packages/input-container/test/input-container-polymer.test.js
packages/input-container/test/input-container.common.js

Added the `vaadin-input-container` version based on LitElement.
- Experiment

experiment: add LitElement based version of vaadin-input-container

---

packages/date-picker/src/vaadin-date-picker-mixin.js

The PR simplifies date-picker's value commit logic. Now that its test coverage has been improved, such changes should hopefully be safe.

refactor: simplify value commit logic

---

packages/date-picker/src/vaadin-date-picker-mixin.js

The PR renames a few internal methods to better reflect the fact that they trigger a value commit:
- `_selectDate` renamed to `__commitDate`
- `_selectParsedOrFocusedDate` renamed to `__commitParsedOrFocusedDate`
Part of https://github.com/vaadin/flow-components/issues/5537

refactor: rename some internal methods related to value commit

---

packages/component-base/src/define.js
packages/component-base/src/element-mixin.js
packages/component-base/test/define.test.js
packages/component-base/test/element-mixin.test.js
packages/field-highlighter/src/vaadin-field-highlighter.js
packages/polymer-legacy-adapter/src/template-renderer-templatizer.js
packages/vaadin-lumo-styles/version.js
packages/vaadin-material-styles/version.js
scripts/updateVersion.js

Updated the code to not repeat same version in multiple files.
- Refactor

refactor: specify version in define.js instead of getters

---

packages/rich-text-editor/package.json
packages/rich-text-editor/src/vaadin-lit-rich-text-editor.d.ts
packages/rich-text-editor/src/vaadin-lit-rich-text-editor.js
packages/rich-text-editor/src/vaadin-rich-text-editor-mixin.js
packages/rich-text-editor/test/a11y-lit.test.js
packages/rich-text-editor/test/a11y-polymer.test.js
packages/rich-text-editor/test/a11y.common.js
packages/rich-text-editor/test/auto-grow-lit.test.js
packages/rich-text-editor/test/auto-grow-polymer.test.js
packages/rich-text-editor/test/auto-grow.common.js
packages/rich-text-editor/test/basic-lit.test.js
packages/rich-text-editor/test/basic-polymer.test.js
packages/rich-text-editor/test/basic.common.js

Added a `LitElement` based version of `vaadin-rich-text-editor` web component.
- Experiment

experiment: add LitElement based version of rich-text-editor

---

packages/button/src/vaadin-button-mixin.js
packages/button/test/button.common.js

Manual cherry-pick of #6404 to `24.1` branch.
- Cherry-pick

fix: do not click on Enter and Space when using key modifiers (#6404) (CP: 24.1)

---

packages/select/src/vaadin-select-base-mixin.d.ts
packages/select/src/vaadin-select-base-mixin.js
packages/select/src/vaadin-select.d.ts
packages/select/src/vaadin-select.js
packages/select/test/items.common.js
packages/select/test/typings/select.types.ts

feat: add className property for adding CSS classes to items

---

packages/grid/src/vaadin-grid-column.js
packages/grid/src/vaadin-grid.js
packages/grid/test/grid-wrapper.test.js

fix: make auto-width and text-align usable in custom slot (#6602) (CP: 24.1)

---

packages/grid/src/vaadin-grid-data-provider-mixin.js
packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js
packages/grid/test/keyboard-navigation.test.js

Manual cherry-pick of #6618 to `24.1`

fix: defer grid cell-focus event with lazy data provider (#6618)

---

packages/grid/src/vaadin-grid-column.js
packages/grid/src/vaadin-grid.js
packages/grid/test/grid-wrapper.test.js

fix: make auto-width and text-align usable in custom slot (#6602) (CP: 23.3)

---

packages/combo-box/src/vaadin-combo-box-item.js
packages/combo-box/test/item-renderer.test.js

Manually cherry-pick #6638 to `23.3`

fix: make sure unhidden combo-box items get re-rendered (#6638)

---

packages/grid/theme/lumo/vaadin-grid-styles.js
packages/grid/theme/material/vaadin-grid-styles.js

Part of #5636
See https://github.com/vaadin/web-components/issues/5636#issuecomment-1761159685
- Feature

feat: add custom CSS property to configure cell padding

---

packages/grid/src/vaadin-grid.js
packages/grid/test/renderers.test.js

Manually cherry-pick #6648 to `23.3`

fix: update grid header and footer on column tree change (#6648)

---

packages/checkbox/theme/lumo/vaadin-checkbox-styles.js
packages/vaadin-lumo-styles/style.js

feat: add new Lumo custom CSS properties to checkbox

---

packages/radio-group/theme/lumo/vaadin-radio-button-styles.js
packages/vaadin-lumo-styles/style.js

feat: add new Lumo custom CSS properties to radio-button

---

packages/radio-group/package.json
packages/radio-group/src/vaadin-lit-radio-button.d.ts
packages/radio-group/src/vaadin-lit-radio-button.js
packages/radio-group/src/vaadin-lit-radio-group.d.ts
packages/radio-group/src/vaadin-lit-radio-group.js
packages/radio-group/src/vaadin-radio-group.js
packages/radio-group/test/radio-button-lit.test.js
packages/radio-group/test/radio-button-polymer.test.js
packages/radio-group/test/radio-button.common.js
packages/radio-group/test/radio-group-keyboard-navigation-lit.test.js
packages/radio-group/test/radio-group-keyboard-navigation-polymer.test.js
packages/radio-group/test/radio-group-keyboard-navigation.common.js
packages/radio-group/test/radio-group-lit.test.js
packages/radio-group/test/radio-group-polymer.test.js
packages/radio-group/test/radio-group.common.js
packages/radio-group/test/validation-lit.test.js
packages/radio-group/test/validation-polymer.test.js
packages/radio-group/test/validation.common.js

Added LitElement based version of `vaadin-radio-button` and `vaadin-radio-group`.
- Experiment

experiment: add LitElement based version of radio-group

---

packages/combo-box/src/vaadin-combo-box-mixin.js
packages/combo-box/test/object-values.test.js

Fixes https://github.com/vaadin/web-components/issues/6587
Bugfix

fix: support items with duplicate labels in combo-box

---

packages/vaadin-lumo-styles/utilities/background.js
packages/vaadin-lumo-styles/utilities/border.js
packages/vaadin-lumo-styles/utilities/filter.js
packages/vaadin-lumo-styles/utilities/flexbox-grid.js
packages/vaadin-lumo-styles/utilities/layout.js
packages/vaadin-lumo-styles/utilities/shadow.js
packages/vaadin-lumo-styles/utilities/shadows.js
packages/vaadin-lumo-styles/utilities/spacing.js
packages/vaadin-lumo-styles/utilities/transition.js
packages/vaadin-lumo-styles/utilities/typography.js
packages/vaadin-lumo-styles/utility.js

New utility classes for setting line-clamp, negative margins, positions (top, right/end, bottom, left/start), dashed borders, etc. These are recreated in a lot of client projects, and commonly used building blocks.
Fixes # (N/A)

Updated Utility classes (e.g. line clamps, negative margins, positions, dashed borders)

---

packages/context-menu/src/vaadin-contextmenu-items-mixin.js
packages/context-menu/test/items.test.js

Fixes https://github.com/vaadin/flow-components/issues/5653
- Bugfix

fix: do not throw when item with keepOpen is after hr

---

wtr-utils.js

Updated the `wtr-utils.js` script to correctly detect changes for `23.4` branch.

chore: update WTR change detection branch to 23.4

---

packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js
packages/grid/test/keyboard-navigation.test.js

Manually cherry-pick #6731 to `23.3`

fix: check if grid focus target is in viewport (#6731)

---

packages/side-nav/src/vaadin-side-nav.js
packages/side-nav/test/accessibility.test.js
packages/side-nav/test/dom/__snapshots__/side-nav.test.snap.js

Fixes #6708
- Refactor / a11y fix

refactor: do not use button in not collapsible side-nav

---

dev/grid-pro.html
packages/grid-pro/package.json
packages/grid-pro/src/vaadin-grid-pro-edit-column-mixin.js
packages/grid-pro/src/vaadin-grid-pro-inline-editing-mixin.js
packages/grid-pro/src/vaadin-lit-grid-pro-edit-checkbox.js
packages/grid-pro/src/vaadin-lit-grid-pro-edit-column.js
packages/grid-pro/src/vaadin-lit-grid-pro-edit-select.js
packages/grid-pro/src/vaadin-lit-grid-pro-edit-text-field.js
packages/grid-pro/src/vaadin-lit-grid-pro.js
packages/grid-pro/test/edit-column-lit.test.js
packages/grid-pro/test/edit-column-renderer-lit.test.js
packages/grid-pro/test/edit-column-renderer.common.js
packages/grid-pro/test/edit-column-type-lit.test.js
packages/grid-pro/test/edit-column-type.common.js
packages/grid-pro/test/edit-column.common.js
packages/grid-pro/test/grid-pro-lit.test.js
packages/grid-pro/test/grid-pro.common.js
packages/grid-pro/test/helpers.js
packages/grid-pro/test/keyboard-navigation-lit.test.js
packages/grid-pro/test/keyboard-navigation.common.js
packages/grid-pro/test/lit-lit.test.js
packages/grid-pro/test/lit-renderer-directives-lit.test.js
packages/grid-pro/theme/lumo/vaadin-grid-pro-edit-select.js
packages/grid-pro/theme/lumo/vaadin-lit-grid-pro-edit-checkbox.js
packages/grid-pro/theme/lumo/vaadin-lit-grid-pro-edit-column.js
packages/grid-pro/theme/lumo/vaadin-lit-grid-pro-edit-select.js
packages/grid-pro/theme/lumo/vaadin-lit-grid-pro-edit-text-field.js
packages/grid-pro/theme/lumo/vaadin-lit-grid-pro.js

Add LitElement-based version of vaadin-grid-pro.
To keep this PR as small as possible, root-level imports and TS types were excluded. Separate PRs will be created for them later.
Experiment

experiment: add LitElement based version of vaadin-grid-pro

---

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js
packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.d.ts
packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js
packages/multi-select-combo-box/test/selecting-items.test.js
packages/multi-select-combo-box/test/typings/multi-select-combo-box.types.ts

refactor: rename groupSelectedItems to selectedItemsOnTop

---

packages/component-base/src/url-utils.d.ts
packages/component-base/src/url-utils.js
packages/component-base/test/url-utils.test.js

Fixes https://github.com/vaadin/flow-components/issues/5675
- Bugfix

fix: check origin when matching paths for external URLs

---

packages/checkbox/package.json
packages/checkbox/theme/lumo/vaadin-lit-checkbox.js
packages/checkbox/theme/material/vaadin-lit-checkbox.js
packages/checkbox/vaadin-lit-checkbox.d.ts
packages/checkbox/vaadin-lit-checkbox.js

Add imports for the LitElement-based checkbox

experiment: add imports for LitElement-based checkbox

---

packages/button/package.json
packages/button/theme/lumo/vaadin-lit-button.js
packages/button/theme/material/vaadin-lit-button.js
packages/button/vaadin-lit-button.d.ts
packages/button/vaadin-lit-button.js

Add imports for the LitElement-based button

experiment: add imports for LitElement-based button

---

packages/select/package.json
packages/select/theme/lumo/vaadin-lit-select.js
packages/select/theme/material/vaadin-lit-select.js
packages/select/vaadin-lit-select.d.ts
packages/select/vaadin-lit-select.js

Add imports for the LitElement-based select

experiment: add imports for LitElement-based select

---

packages/text-field/package.json
packages/text-field/theme/lumo/vaadin-lit-text-field.js
packages/text-field/theme/material/vaadin-lit-text-field.js
packages/text-field/vaadin-lit-text-field.d.ts
packages/text-field/vaadin-lit-text-field.js

Add imports for the LitElement-based text-field

experiment: add imports for LitElement-based text-field

---

packages/side-nav/src/vaadin-side-nav.js
packages/side-nav/test/accessibility.test.js
packages/side-nav/test/dom/__snapshots__/side-nav.test.snap.js

Cherry-pick of #6738 to `24.2` branch.
- Cherry-pick

refactor: do not use button in not collapsible side-nav (#6738) (CP: 24.2)

---

packages/rich-text-editor/package.json
packages/rich-text-editor/theme/lumo/vaadin-lit-rich-text-editor.js
packages/rich-text-editor/theme/material/vaadin-lit-rich-text-editor.js
packages/rich-text-editor/vaadin-lit-rich-text-editor.d.ts
packages/rich-text-editor/vaadin-lit-rich-text-editor.js

Add imports for the LitElement-based rich-text-editor

experiment: add imports for LitElement-based rich-text-editor

---

packages/confirm-dialog/package.json
packages/confirm-dialog/theme/lumo/vaadin-lit-confirm-dialog.js
packages/confirm-dialog/theme/material/vaadin-lit-confirm-dialog.js
packages/confirm-dialog/vaadin-lit-confirm-dialog.d.ts
packages/confirm-dialog/vaadin-lit-confirm-dialog.js

Add imports for the LitElement-based confirm-dialog

experiment: add imports for LitElement-based confirm-dialog

---

packages/tooltip/package.json
packages/tooltip/theme/lumo/vaadin-lit-tooltip.js
packages/tooltip/theme/material/vaadin-lit-tooltip.js
packages/tooltip/vaadin-lit-tooltip.d.ts
packages/tooltip/vaadin-lit-tooltip.js

Add imports for the LitElement-based tooltip

experiment: add imports for LitElement-based tooltip

---

packages/button/package.json
packages/checkbox/package.json
packages/confirm-dialog/package.json
packages/dialog/package.json
packages/grid-pro/package.json
packages/grid/package.json
packages/input-container/package.json
packages/overlay/package.json
packages/rich-text-editor/package.json
packages/select/package.json
packages/text-field/package.json
packages/tooltip/package.json

This change will enable publishing a set of experimental LitElement-based components:
- button
- checkbox
- confirm-dialog
- dialog
- grid
- grid-pro
- rich-text-editor
- select
- text-field
- tooltip

experiment: enable publishing a set of LitElement based components

---

packages/tabs/package.json
packages/tabs/src/vaadin-tab-mixin.d.ts
packages/tabs/src/vaadin-tab-mixin.js
packages/tabs/src/vaadin-tab.js
packages/tabs/src/vaadin-tabs-mixin.d.ts
packages/tabs/src/vaadin-tabs-mixin.js
packages/tabs/src/vaadin-tabs.d.ts
packages/tabs/src/vaadin-tabs.js

Extracted `vaadin-tab` and `vaadin-tabs` logic into mixins for reusing by LitElement version.
- Refactor

refactor: extract vaadin-tab and vaadin-tabs mixins

---

packages/grid/src/vaadin-grid-mixin.js
packages/grid/test/column-auto-width.test.js

Manually cherry-pick #6815 to `24.2`

fix: measure grid column auto-width from column cell (#6815)

---

packages/text-area/src/vaadin-text-area.js
packages/text-area/test/text-area.test.js

Manually cherry-pick #6840 to `23.3`

fix: update text-area height on resize (#6840)

---

packages/a11y-base/src/focus-utils.d.ts
packages/a11y-base/src/focus-utils.js
packages/a11y-base/test/focus-utils.test.js
packages/overlay/src/vaadin-overlay.js
packages/overlay/test/overlay.test.js

Manual cherry-pick of #6850 to `24.1` branch.
- Cherry-pick

fix: focus the closest focusable on overlay mousedown (#6850) (CP: 24.1)

---

packages/component-base/src/focus-utils.d.ts
packages/component-base/src/focus-utils.js
packages/component-base/test/focus-utils.test.js
packages/overlay/src/vaadin-overlay.js
packages/overlay/test/overlay.test.js

Manual cherry-pick of #6850 to `23.4` branch.
- Cherry-pick

fix: focus the closest focusable on overlay mousedown (#6850) (CP: 23.4)

---

packages/component-base/src/focus-utils.d.ts
packages/component-base/src/focus-utils.js
packages/component-base/test/focus-utils.test.js
packages/overlay/src/vaadin-overlay.js
packages/overlay/test/overlay.test.js

Manual cherry-pick of #6850 to `23.3` branch.
- Cherry-pick

fix: focus the closest focusable on overlay mousedown (#6850) (CP: 23.3)

---

packages/number-field/src/vaadin-number-field-mixin.js
packages/number-field/test/value-control-buttons.common.js

Fixes #6857
- Bugfix
https://github.com/vaadin/web-components/assets/10589913/41b262c2-72eb-440f-9680-c67b700eba1c
https://github.com/vaadin/web-components/assets/10589913/de1ca33b-b017-485b-a755-7395818b54ed

fix: do not change value on step buttons touch scroll

---

packages/number-field/src/vaadin-number-field-mixin.js
packages/number-field/test/number-field.common.js

Manual cherry-pick of #6859 to `24.1` branch.
- Cherry-pick

fix: do not change value on step buttons touch scroll (#6859) (CP: 24.1)

---

packages/number-field/src/vaadin-number-field.js
packages/number-field/test/number-field.test.js

Manual cherry-pick of #6859 to `23.4` branch.
- Cherry-pick

fix: do not change value on step buttons touch scroll (#6859) (CP: 23.4)

---

packages/number-field/src/vaadin-number-field.js
packages/number-field/test/number-field.test.js

Manual cherry-pick of #6859 to `23.3` branch.
- Cherry-pick

fix: do not change value on step buttons touch scroll (#6859) (CP: 23.3)

---

packages/rich-text-editor/src/vaadin-rich-text-editor.js
packages/rich-text-editor/test/basic.test.js

Manually cherry-pick #6871 to `24.1`

fix: cache pending html value for unattached rte (#6871)

---

dev/virtual-list.html
packages/virtual-list/package.json
packages/virtual-list/src/vaadin-lit-virtual-list.d.ts
packages/virtual-list/src/vaadin-lit-virtual-list.js
packages/virtual-list/src/vaadin-virtual-list-mixin.js
packages/virtual-list/test/lit-lit.test.js
packages/virtual-list/test/lit-renderer-directives-lit.test.js
packages/virtual-list/test/lit.common.js
packages/virtual-list/test/virtual-list-lit.test.js
packages/virtual-list/theme/lumo/vaadin-lit-virtual-list.js
packages/virtual-list/theme/material/vaadin-lit-virtual-list.js
packages/virtual-list/vaadin-lit-virtual-list.d.ts
packages/virtual-list/vaadin-lit-virtual-list.js

Added an experimental version of `vaadin-virtual-list` based on LitElement.
- Experiment

experiment: add LitElement based version of virtual-list

---

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-chip.js

refactor: remove button role from chip remove button element

---

packages/overlay/src/vaadin-overlay.js
packages/overlay/test/overlay.test.js

Manual cherry-pick of #6887 to `23.4` branch.
- Cherry-pick

fix: focus overlay on mouseup when focus moves to body (#6887) (CP: 23.4)

---

packages/overlay/src/vaadin-overlay.js
packages/overlay/test/overlay.test.js

Manual cherry-pick of #6887 to `23.3` branch.
- Cherry-pick

fix: focus overlay on mouseup when focus moves to body (#6887) (CP: 23.3)

---

wtr-utils.js

Update the `web-test-runner` change detection script to use `24.3` as a base branch for Vaadin 24.4

chore: update change detection branch to 24.3

---

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js
packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js

The PR simplifies the readonly logic of `multi-select-combo-box` by leveraging the `_setDropdownItems` API.

refactor: simplify readonly logic

---

packages/accordion/package.json
packages/accordion/src/vaadin-lit-accordion-heading.d.ts
packages/accordion/src/vaadin-lit-accordion-heading.js
packages/accordion/src/vaadin-lit-accordion-panel.d.ts
packages/accordion/src/vaadin-lit-accordion-panel.js
packages/accordion/src/vaadin-lit-accordion.d.ts
packages/accordion/src/vaadin-lit-accordion.js
packages/accordion/test/accordion-lit.test.js
packages/accordion/test/accordion-panel-lit.test.js
packages/accordion/test/accordion-panel-polymer.test.js
packages/accordion/test/accordion-panel.common.js
packages/accordion/test/accordion-polymer.test.js
packages/accordion/test/accordion.common.js

Added an experimental version of `vaadin-accordion` based on LitElement.
- Experiment

experiment: add LitElement based version of vaadin-accordion

---

packages/tabsheet/package.json
packages/tabsheet/src/vaadin-tabsheet-mixin.d.ts
packages/tabsheet/src/vaadin-tabsheet-mixin.js
packages/tabsheet/src/vaadin-tabsheet.d.ts
packages/tabsheet/src/vaadin-tabsheet.js
packages/tabsheet/test/typings/tabsheet.types.ts

Extracted reusable mixin for `vaadin-tabsheet` to be used by LitElement version.
- Refactor

refactor: extract tabsheet-mixin

---

packages/item/test/item-mixin.test.js

Changed `ItemMixin` test file to run both Polymer and Lit based tests.
- Test

test: run ItemMixin tests with both Polymer and Lit

---

packages/date-picker/test/value-commit-lit.test.js

Updated Lit unit test file to use theme entrypoint added in #6801.
- Test

test: simplify imports in Lit date-picker value commit test

---

packages/field-base/src/checked-mixin.js

Removed an unused import.
- Refactor

refactor: remove unused helper import from CheckedMixin

---

packages/grid/src/vaadin-grid-mixin.js
packages/grid/test/column-auto-width.common.js

fix: wait for defined columns before measuring auto-width

---

dev/password-field.html
packages/password-field/package.json
packages/password-field/src/vaadin-lit-password-field-button.js
packages/password-field/src/vaadin-lit-password-field.d.ts
packages/password-field/src/vaadin-lit-password-field.js
packages/password-field/src/vaadin-password-field-mixin.js
packages/password-field/test/password-field-lit.test.js
packages/password-field/test/password-field-polymer.test.js
packages/password-field/test/password-field.common.js
packages/password-field/test/validation-lit.test.js
packages/password-field/test/validation-polymer.test.js
packages/password-field/test/validation.common.js
packages/password-field/theme/lumo/vaadin-lit-password-field.js
packages/password-field/theme/material/vaadin-lit-password-field.js
packages/password-field/vaadin-lit-password-field.d.ts
packages/password-field/vaadin-lit-password-field.js
packages/text-field/src/vaadin-lit-text-field.js

Depends on #7004 
Depends on #7007
Added `LitElement` based version of `vaadin-password-field` web component.
- Experiment

experiment: add LitElement based version of password-field

---

packages/login/package.json
packages/login/src/vaadin-lit-login-form.js
packages/login/theme/lumo/vaadin-lit-login-form.js
packages/login/theme/lumo/vaadin-lit-login-overlay.js
packages/login/theme/material/vaadin-lit-login-form.js
packages/login/theme/material/vaadin-lit-login-overlay.js
packages/login/vaadin-lit-login-form.d.ts
packages/login/vaadin-lit-login-form.js
packages/login/vaadin-lit-login-overlay.d.ts
packages/login/vaadin-lit-login-overlay.js

Depends on #7008
- Added Lit import files (root level and theme folders)
- Removed `vaadin-lit` excludes from `package.json`
- Updated login form to use Lit based dependencies
- Experiment

experiment: prepare LitElement based login for publishing

---

packages/list-box/test/multi-select-list-mixin.test.js

Updated `MultiSelectListMixin` tests to also run with LitElement.
- Tests

test: run MultiSelectListMixin with Polymer and Lit

---

packages/integer-field/test/integer-field.test.js
packages/number-field/src/vaadin-number-field-mixin.js
packages/number-field/test/number-field.common.js
packages/number-field/test/value-control-buttons.common.js

Cherry-pick of #6984
(cherry picked from commit 53e69e739c76f645a03c094130a111510740291c)
Fixes https://github.com/vaadin/flow-components/issues/5937

fix: fire input event on input element on increment/decrement (#6984) (CP: 24.3)

---

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js

Manual cherry-pick of #7157 to `24.3` branch.
- Cherry-pick

docs: add missing annotation for custom-value-set event (#7157) (CP: 24.3)

---

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js

Manual cherry-pick of #7157 to `23.4` branch.
- Cherry-pick

docs: add missing annotation for custom-value-set event (#7157) (CP: 23.4)

---

packages/grid/src/vaadin-grid.js
packages/grid/test/column-auto-width.test.js

A manual cherry-pick of the following fix to 23.4:
- #7165
Fixes https://github.com/vaadin/flow-components/issues/5813

fix: delay column width recalculation until all rows have index (#7165) (CP: 23.4)

---

packages/grid/src/vaadin-grid-mixin.js
packages/grid/src/vaadin-grid-selection-column-base-mixin.js
packages/grid/test/selection.test.js

Manual cherry-pick of #7178 to `24.2` branch.
- Cherry-pick

fix: toggle checkbox on selection column cell Space key (#7178) (CP: 24.2)

---

packages/grid/src/vaadin-grid-tree-toggle-mixin.js
packages/grid/test/tree-toggle.common.js

Manual cherry-pick of https://github.com/vaadin/web-components/pull/7184.
Fixes #7163

fix: add click listener in constructor to ensure listener order (CP: 24.3)

---

packages/context-menu/src/vaadin-contextmenu-items-mixin.js
packages/context-menu/test/items.test.js
packages/menu-bar/test/sub-menu.test.js

Manual cherry-pick of #7203 to `23.4` branch.
- Cherry-pick

fix: reset tabindex to -1 when initializing menu item (#7203) (CP: 23.4)

---

packages/grid/src/vaadin-grid-tree-toggle.js
packages/grid/test/tree-toggle.test.js

Manual cherry-pick of https://github.com/vaadin/web-components/pull/7184.
Fixes #7163

fix: add click listener in constructor to ensure listener order (CP: 24.2)

---

packages/component-base/src/virtualizer-iron-list-adapter.js

The PR makes the virtualizer's logic slightly more readable by extracting a `_maxVirtualIndexOffset` getter.

refactor: extract _maxVirtualIndexOffset getter

---

packages/rich-text-editor/src/vaadin-rich-text-editor.js
packages/rich-text-editor/test/basic.test.js

Manual cherry-pick of #7250 to `23.4` branch.
- Cherry-pick

fix: fire change event on hyperlink edit, update test timings (#7250) (CP: 23.4)

---

packages/context-menu/test/properties.test.js
packages/crud/test/crud-buttons.test.js
packages/crud/test/crud.test.js
packages/date-time-picker/test/properties.test.js
packages/dialog/test/header-footer.test.js
packages/login/test/login-overlay.test.js
packages/overlay/src/vaadin-overlay.js
packages/overlay/test/focus-trap.test.js

Manual cherry-pick of #7246 to `23.4` branch with focus-trap tests updated accordingly.
- Cherry-pick

fix: set display none on overlay part to fix Safari 17.4 issue (#7246) (CP: 23.4)

---

integration/tests/component-relayout-page.test.js
packages/combo-box/src/vaadin-combo-box-scroller-mixin.js

Part of #7271
Depends on #7311 
- Bugfix

fix: postpone virtualizer creation until overlay is opened

---

packages/icon/package.json
packages/icon/src/vaadin-icon-mixin.d.ts
packages/icon/src/vaadin-icon-mixin.js
packages/icon/src/vaadin-icon-styles.js
packages/icon/src/vaadin-icon.d.ts
packages/icon/src/vaadin-icon.js
packages/icon/src/vaadin-iconset-mixin.d.ts
packages/icon/src/vaadin-iconset-mixin.js
packages/icon/src/vaadin-iconset.d.ts
packages/icon/src/vaadin-lit-icon.d.ts
packages/icon/src/vaadin-lit-icon.js
packages/icon/src/vaadin-lit-iconset.d.ts
packages/icon/src/vaadin-lit-iconset.js
packages/icon/test/icon-font-lit.test.js
packages/icon/test/icon-font-polymer.test.js
packages/icon/test/icon-font.common.js
packages/icon/test/icon-lit.test.js
packages/icon/test/icon-polymer.test.js
packages/icon/test/icon.common.js
packages/icon/test/iconset-lit.test.js
packages/icon/test/iconset-polymer.test.js
packages/icon/test/iconset.common.js
packages/icon/theme/lumo/vaadin-lit-icon.js
packages/icon/theme/material/vaadin-lit-icon.js
packages/icon/vaadin-lit-icon.d.ts
packages/icon/vaadin-lit-icon.js
packages/icon/vaadin-lit-iconset.d.ts
packages/icon/vaadin-lit-iconset.js

Added `LitElement` based version of `vaadin-icon` and `vaadin-iconset`.
- Experiment

experiment: add LitElement based version of icon

---

packages/integer-field/package.json
packages/integer-field/src/vaadin-lit-integer-field.d.ts
packages/integer-field/src/vaadin-lit-integer-field.js
packages/integer-field/test/integer-field-lit.test.js
packages/integer-field/test/integer-field-polymer.test.js
packages/integer-field/test/integer-field.common.js
packages/integer-field/test/validation-lit.test.js
packages/integer-field/test/validation-polymer.test.js
packages/integer-field/test/validation.common.js
packages/integer-field/test/value-commit-lit.test.js
packages/integer-field/test/value-commit-polymer.test.js
packages/integer-field/test/value-commit.common.js

Added `vaadin-integer-field` version based on Lit.
- Experiment

experiment: add LitElement based version of integer-field

---

packages/grid-pro/src/vaadin-grid-pro-edit-column-mixin.js
packages/grid-pro/src/vaadin-grid-pro-inline-editing-mixin.js
packages/grid-pro/test/edit-column.common.js

fix: exit edit mode when a cell becomes non-editable

---

wtr-utils.js

Update the `web-test-runner` change detection script to use `24.4` as a base branch for Vaadin 24.4

chore: update change detection branch for 24.4

---

packages/icon/LICENSE

Added missing LICENSE file with Apache 2.0 license.

chore: add missing LICENSE file to the icon package

---

packages/popover/LICENSE
packages/popover/README.md
packages/popover/package.json
packages/popover/src/vaadin-popover.d.ts
packages/popover/src/vaadin-popover.js
packages/popover/test/basic.test.js
packages/popover/theme/lumo/vaadin-popover.js
packages/popover/theme/material/vaadin-popover.js
packages/popover/vaadin-popover.d.ts
packages/popover/vaadin-popover.js

Part of https://github.com/vaadin/platform/issues/5271
Initialized basic structure of `@vaadin/popover` package. The actual code will be added in separate PRs.
- Feature

feat: create popover package with a dummy custom element

---

packages/overlay/src/vaadin-overlay-position-mixin.js
packages/overlay/src/vaadin-overlay-utils.d.ts
packages/overlay/src/vaadin-overlay-utils.js
packages/overlay/test/position-mixin-listeners.test.js

Fixes #7424
Based on https://github.com/samthor/viz-observer (not the latest beta version but the implementation from [Floating UI](https://github.com/floating-ui/floating-ui/blob/58ed16968a044c65bedbfb1e6d639131da347ee1/packages/dom/src/autoUpdate.ts#L45)).
- Feature

feat: observe target move on the page and update position

---

packages/combo-box/test/data-provider.common.js

The PR reorganizes the data provider test suites to make them slightly more readable by removing excessive nesting where possible. It's recommended to review these changes with "Hide whitespace" enabled for more concise diff.

test: reorganize data provider tests for better readability

---

packages/combo-box/test/data-provider-filtering-lit.test.js
packages/combo-box/test/data-provider-filtering-polymer.test.js
packages/combo-box/test/data-provider-filtering.common.js
packages/combo-box/test/data-provider.common.js

The PR extracts tests that are related to filtering from `data-provider` to a separate `data-provider-filtering` file to make the `data-provider` file lighter.

test: extract data provider filtering tests

---

packages/side-nav/src/vaadin-side-nav-item.js
packages/side-nav/test/navigation.test.js

vaadin-navigated is fired after navigation has taken place

fix: Use navigated event

---

packages/button/theme/lumo/vaadin-button-styles.js

The purpose of this PR is to add modifiability to vaadin-button. The original motivator was issue #6386 where a notification ancestor would need to modify the focus-ring on buttons to provide sufficient contrast against theme variants.
Related PR: #7488

refactor: add private variables for focus ring gap

---

packages/vaadin-lumo-styles/badge.js

fix: only apply icon styles to direct badge child (#7510) (CP: 23.5)

---

packages/component-base/test/data-provider-controller-cache.test.js
packages/component-base/test/data-provider-controller-placeholder.test.js
packages/component-base/test/data-provider-controller.test.js

The PR adds test coverage for the new logic that was added to DataProviderController in #7044.
Follow-up to #7044

test: improve test coverage for DataProviderController

---

package.json
yarn.lock

chore: update Stylelint dev dependency to v16

---

dev/dashboard.html
packages/dashboard/LICENSE
packages/dashboard/README.md
packages/dashboard/package.json
packages/dashboard/src/vaadin-dashboard-widget.d.ts
packages/dashboard/src/vaadin-dashboard-widget.js
packages/dashboard/src/vaadin-dashboard.d.ts
packages/dashboard/src/vaadin-dashboard.js
packages/dashboard/test/dashboard.test.ts
packages/dashboard/theme/lumo/vaadin-dashboard-widget.js
packages/dashboard/theme/lumo/vaadin-dashboard.js
packages/dashboard/theme/material/vaadin-dashboard-widget.js
packages/dashboard/theme/material/vaadin-dashboard.js
packages/dashboard/vaadin-dashboard-widget.d.ts
packages/dashboard/vaadin-dashboard-widget.js
packages/dashboard/vaadin-dashboard.d.ts
packages/dashboard/vaadin-dashboard.js

Fixes https://github.com/orgs/vaadin/projects/70/views/1?pane=issue&itemId=74589753
Initialized basic structure of `@vaadin/dashboard` package. The actual code will be added in separate PRs.
- Feature

feat: create dashboard package

---

packages/dashboard/src/vaadin-dashboard-section.js
packages/dashboard/src/vaadin-dashboard.js

Rename `<vaadin-dashboard-cell>` to `<vaadin-dashboard-widget-wrapper>` as agreed.
Refactor

refactor: rename vaadin-dashboard-widget-wrapper

---

packages/tooltip/src/vaadin-tooltip-mixin.js
packages/tooltip/test/tooltip-timers.common.js

fix: allow setting individual tooltip delays to 0

---

packages/popover/src/vaadin-popover.js
packages/popover/test/timers.test.js

Same as #7707 but for `vaadin-popover`.
- Bugfix

fix: allow setting individual popover delays to 0

---

packages/menu-bar/src/vaadin-menu-bar-mixin.js
packages/tooltip/src/vaadin-tooltip-mixin.js
packages/tooltip/test/tooltip.common.js

fix: do not close manual tooltip on target mousedown

---

packages/horizontal-layout/README.md
packages/vertical-layout/README.md

Updated "live demo" links that were outdated since horizontal and vertical layout now have their own pages.

docs: use correct vaadin.com links in layouts READMEs

---

packages/form-layout/package.json
packages/form-layout/src/vaadin-form-layout.js
packages/form-layout/test/form-layout.test.js

Fixes https://github.com/vaadin/flow-components/issues/6614
Similar to #5840 but for `vaadin-form-layout`
- Bugfix

fix: do not update form-layout when it is not visible

---

wtr-utils.js

Update the `web-test-runner` change detection script to use `24.5` as a base branch for Vaadin 24.5

chore: update change detection branch to 24.5

---

integration/tests/define.test.js
packages/component-base/src/define.d.ts
packages/component-base/src/define.js

Cherry-pick of #7813 to `24.4` branch.
- Cherry-pick

fix: always define custom element class version getter (#7813) (CP: 24.4)

---

packages/component-base/src/define.d.ts
packages/component-base/src/define.js
test/integration/define.test.js

Cherry-pick of #7813 to `24.5` branch.
- Cherry-pick

fix: always define custom element class version getter (#7813) (CP: 24.5)

---

package.json
packages/component-base/src/async.d.ts
packages/grid-pro/src/vaadin-grid-pro.d.ts
packages/grid/src/vaadin-grid-column-group.d.ts
packages/grid/src/vaadin-grid-column-mixin.d.ts
packages/virtual-list/src/vaadin-virtual-list.d.ts
yarn.lock

Updated `eslint-config-vaadin` and fixed a few warnings reported by new rules.

chore: update eslint-config-vaadin to latest version

---

integration/tests/grid-pro-custom-editor.test.js
packages/grid-pro/src/vaadin-grid-pro-inline-editing-mixin.js
packages/grid-pro/test/edit-column-lit.test.js
packages/grid-pro/test/edit-column-polymer.test.js
packages/grid-pro/test/edit-column.common.js
packages/grid-pro/test/keyboard-navigation.common.js

Manual cherry-pick of #7822 to `24.4` branch (the automated one failed due to merge conflicts in test imports).
- Cherry-pick

fix: wait for editor focusout on Tab to get updated value (#7822) (CP: 24.4)

---

packages/item/package.json
packages/item/src/vaadin-lit-item.d.ts
packages/item/src/vaadin-lit-item.js
packages/item/test/item-lit.test.js
packages/item/test/item-polymer.test.js
packages/item/test/item.common.js

Added Lit based version of `vaadin-item` (note, the `ItemMixin` already has tests running with Lit).
- Experiment

experiment: add Lit based version of vaadin-item

---

packages/scroller/package.json
packages/scroller/src/vaadin-scroller-mixin.d.ts
packages/scroller/src/vaadin-scroller-mixin.js
packages/scroller/src/vaadin-scroller.d.ts
packages/scroller/src/vaadin-scroller.js

Pre-requisite for creating Lit based version of `vaadin-scroller` web component.
- Refactor

refactor: extract common scroller logic to reusable mixin

---

integration/tests/grid-pro-custom-editor.test.js
packages/grid-pro/src/vaadin-grid-pro-inline-editing-mixin.js
packages/grid-pro/test/edit-column.test.js
packages/grid-pro/test/keyboard-navigation.test.js

Manual cherry-pick of #7822 to `23.5` branch as requested.
- Cherry-pick

fix: wait for editor focusout on Tab to get updated value (#7822) (CP: 23.5)

---

packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js

Cherry-picks #7977 to 24.5. 
There were no conflicts. I had to manually backport because I added the target label too late.

refactor: clean up keyboard navigation mixin (#7977) (CP: 24.5)

---

packages/form-layout/src/vaadin-form-layout.js
packages/form-layout/test/form-layout.test.js

Manual cherry-pick of #7988 to `24.4` branch.
- Cherry-pick

fix: update form-layout when its parent becomes visible (#7988) (CP: 24.4)

---

packages/component-base/src/virtualizer-iron-list-adapter.js
packages/component-base/test/virtualizer-variable-row-height.test.js

Back-port of [# (7987)](https://github.com/vaadin/web-components/pull/7987)

fix: preserve large items when new items are added (#7987) (CP: 24.5)

---

packages/component-base/src/virtualizer-iron-list-adapter.js
packages/component-base/test/virtualizer-variable-row-height.test.js

Back-port of [# (7987)](https://github.com/vaadin/web-components/pull/7987)

fix: preserve large items when new items are added (#7987) (CP: 23.5)

---

packages/custom-field/src/vaadin-custom-field-mixin.js
packages/custom-field/test/custom-field.common.js
packages/custom-field/test/validation.common.js

fix: clear input values when setting value property to null

---

packages/grid/src/vaadin-grid-mixin.js
packages/grid/src/vaadin-grid.d.ts
packages/grid/src/vaadin-grid.js
packages/grid/test/selectable-provider.common.js

Part of https://github.com/vaadin/web-components/issues/1947

feat: add part names to non-selectable rows / cells

---

packages/custom-field/src/vaadin-custom-field-mixin.js
packages/custom-field/test/custom-field.common.js
packages/custom-field/test/validation.test.js

Manual cherry-pick of #8017 to `24.4` branch.
- Cherry-pick

fix: clear input values when setting value property to null (#8017) (CP: 24.4)

---

packages/upload/src/vaadin-upload-mixin.d.ts
packages/upload/src/vaadin-upload-mixin.js

Aligns the API docs with the actual default values, especially since the API docs mention that those are the defaults.

docs: update default values in upload i18n

---

packages/avatar/package.json
packages/avatar/theme/lumo/vaadin-lit-avatar.js
packages/avatar/theme/material/vaadin-lit-avatar.js
packages/avatar/vaadin-lit-avatar.d.ts
packages/avatar/vaadin-lit-avatar.js

experiment: prepare LitElement based avatar for publishing

---

packages/checkbox-group/package.json
packages/checkbox-group/theme/lumo/vaadin-lit-checkbox-group.js
packages/checkbox-group/theme/material/vaadin-lit-checkbox-group.js
packages/checkbox-group/vaadin-lit-checkbox-group.d.ts
packages/checkbox-group/vaadin-lit-checkbox-group.js

experiment: prepare LitElement based checkbox-group for publishing

---

packages/context-menu/package.json
packages/context-menu/vaadin-lit-context-menu.d.ts
packages/context-menu/vaadin-lit-context-menu.js

- Added root level import files
- Lumo and Material entrypoints were already added earlier
- Experiment

experiment: prepare LitElement based context-menu for publishing

---

packages/custom-field/package.json
packages/custom-field/theme/lumo/vaadin-lit-custom-field.js
packages/custom-field/theme/material/vaadin-lit-custom-field.js
packages/custom-field/vaadin-lit-custom-field.d.ts
packages/custom-field/vaadin-lit-custom-field.js

experiment: prepare LitElement based custom-field for publishing

---

packages/details/package.json
packages/details/src/vaadin-lit-details.js
packages/details/theme/lumo/vaadin-lit-details-summary.js
packages/details/theme/lumo/vaadin-lit-details.js
packages/details/theme/material/vaadin-lit-details-summary.js
packages/details/theme/material/vaadin-lit-details.js
packages/details/vaadin-lit-details-summary.d.ts
packages/details/vaadin-lit-details-summary.js
packages/details/vaadin-lit-details.d.ts
packages/details/vaadin-lit-details.js

experiment: prepare LitElement based details for publishing

---

packages/email-field/package.json
packages/email-field/theme/lumo/vaadin-lit-email-field.js
packages/email-field/theme/material/vaadin-lit-email-field.js
packages/email-field/vaadin-lit-email-field.d.ts
packages/email-field/vaadin-lit-email-field.js

experiment: prepare LitElement based email-field for publishing

---

packages/item/package.json
packages/item/theme/lumo/vaadin-lit-item.js
packages/item/theme/material/vaadin-lit-item.js
packages/item/vaadin-lit-item.d.ts
packages/item/vaadin-lit-item.js

- Added missing `lit` dependency to package.json
- Experiment

experiment: prepare LitElement based item for publishing

---

packages/menu-bar/package.json
packages/menu-bar/src/vaadin-lit-menu-bar.js
packages/menu-bar/vaadin-lit-menu-bar.d.ts
packages/menu-bar/vaadin-lit-menu-bar.js

- Added root entrypoints (Lumo & Material already exist)
- Experiment

experiment: prepare LitElement based menu-bar for publishing

---

packages/number-field/package.json
packages/number-field/theme/lumo/vaadin-lit-number-field.js
packages/number-field/theme/material/vaadin-lit-number-field.js
packages/number-field/vaadin-lit-number-field.d.ts
packages/number-field/vaadin-lit-number-field.js

experiment: prepare LitElement based number-field for publishing

---

packages/progress-bar/package.json
packages/progress-bar/theme/lumo/vaadin-lit-progress-bar.js
packages/progress-bar/theme/material/vaadin-lit-progress-bar.js
packages/progress-bar/vaadin-lit-progress-bar.d.ts
packages/progress-bar/vaadin-lit-progress-bar.js

experiment: prepare LitElement based progress-bar for publishing

---

packages/radio-group/package.json
packages/radio-group/theme/lumo/vaadin-lit-radio-button.js
packages/radio-group/theme/lumo/vaadin-lit-radio-group.js
packages/radio-group/theme/material/vaadin-lit-radio-button.js
packages/radio-group/theme/material/vaadin-lit-radio-group.js
packages/radio-group/vaadin-lit-radio-button.d.ts
packages/radio-group/vaadin-lit-radio-button.js
packages/radio-group/vaadin-lit-radio-group.d.ts
packages/radio-group/vaadin-lit-radio-group.js

experiment: prepare LitElement based radio-group for publishing

---

packages/scroller/package.json
packages/scroller/theme/lumo/vaadin-lit-scroller.js
packages/scroller/theme/material/vaadin-lit-scroller.js
packages/scroller/vaadin-lit-scroller.d.ts
packages/scroller/vaadin-lit-scroller.js

experiment: prepare LitElement based scroller for publishing

---

packages/split-layout/package.json
packages/split-layout/theme/lumo/vaadin-lit-split-layout.js
packages/split-layout/theme/material/vaadin-lit-split-layout.js
packages/split-layout/vaadin-lit-split-layout.d.ts
packages/split-layout/vaadin-lit-split-layout.js

experiment: prepare LitElement based split-layout for publishing

---

packages/tabs/package.json
packages/tabs/vaadin-lit-tab.d.ts
packages/tabs/vaadin-lit-tab.js
packages/tabs/vaadin-lit-tabs.d.ts
packages/tabs/vaadin-lit-tabs.js

- Added root entrypoints (Lumo & Material already exist)
- Experiment

experiment: prepare LitElement based tabs for publishing

---

packages/text-area/package.json
packages/text-area/theme/lumo/vaadin-lit-text-area.js
packages/text-area/theme/material/vaadin-lit-text-area.js
packages/text-area/vaadin-lit-text-area.d.ts
packages/text-area/vaadin-lit-text-area.js

experiment: prepare LitElement based text-area for publishing

---

packages/upload/package.json
packages/upload/theme/lumo/vaadin-lit-upload.js
packages/upload/theme/lumo/vaadin-upload-styles.js
packages/upload/theme/material/vaadin-lit-upload.js
packages/upload/theme/material/vaadin-upload-styles.js
packages/upload/vaadin-lit-upload.d.ts
packages/upload/vaadin-lit-upload.js

experiment: prepare LitElement based upload for publishing

---

packages/login/package.json
packages/login/src/vaadin-login-form-mixin.js
packages/login/test/login-submit-lit.test.js
packages/login/test/login-submit-polymer.test.js
packages/login/test/login-submit.common.js

The PR prevents unchecked checkboxes from being included in login form submissions.
Fixes https://github.com/vaadin/web-components/issues/7981

fix: exclude unchecked checkboxes from login form submissions

---

packages/login/package.json
packages/login/src/vaadin-login-form-mixin.js
packages/login/test/login-submit-lit.test.js
packages/login/test/login-submit-polymer.test.js
packages/login/test/login-submit.common.js

Cherry-picks #8068 to 24.4 branch. The merge conflict was caused by version difference in `package.json`.
Fixes https://github.com/vaadin/web-components/issues/7981

fix: exclude unchecked checkboxes from login form submissions (#8068) (CP: 24.4)

---

packages/login/package.json
packages/login/src/vaadin-login-form-mixin.js
packages/login/test/login-submit-lit.test.js
packages/login/test/login-submit-polymer.test.js
packages/login/test/login-submit.common.js

Cherry-picks #8068 to 24.5 branch. The merge conflict was caused by version difference in `package.json`.
Fixes https://github.com/vaadin/web-components/issues/7981

fix: exclude unchecked checkboxes from login form submissions (#8068) (CP: 24.5)

---

packages/integer-field/package.json
packages/integer-field/theme/lumo/vaadin-lit-integer-field.js
packages/integer-field/theme/material/vaadin-lit-integer-field.js
packages/integer-field/vaadin-lit-integer-field.d.ts
packages/integer-field/vaadin-lit-integer-field.js

experiment: prepare LitElement based integer-field for publishing

---

packages/vertical-layout/package.json
packages/vertical-layout/src/vaadin-lit-vertical-layout.d.ts
packages/vertical-layout/src/vaadin-lit-vertical-layout.js
packages/vertical-layout/test/vertical-layout-lit.test.js
packages/vertical-layout/test/vertical-layout-polymer.test.js
packages/vertical-layout/test/vertical-layout.common.js
packages/vertical-layout/theme/lumo/vaadin-lit-vertical-layout.js
packages/vertical-layout/theme/material/vaadin-lit-vertical-layout.js
packages/vertical-layout/vaadin-lit-vertical-layout.d.ts
packages/vertical-layout/vaadin-lit-vertical-layout.js

Added Lit based version of `vaadin-vertical-layout`.
- Experiment

experiment: add Lit based version of vaadin-vertical-layout

---

packages/time-picker/package.json

Follow-up to #8080, I missed to add these dependencies in that PR 🙈 

chore: add missing Lit and dedupe-mixin dependencies to time-picker

---

packages/notification/package.json
packages/notification/src/vaadin-notification-mixin.d.ts
packages/notification/src/vaadin-notification-mixin.js
packages/notification/src/vaadin-notification-styles.js
packages/notification/src/vaadin-notification.d.ts
packages/notification/src/vaadin-notification.js

Extracted most of `vaadin-notification` logic into `NotificationMixin` for reusing in Lit based version.
- Refactor

refactor: extract notification logic into reusable mixin

---

packages/radio-group/src/vaadin-radio-group-mixin.d.ts
packages/radio-group/src/vaadin-radio-group-mixin.js
packages/radio-group/test/radio-group.common.js
packages/radio-group/test/typings/radio-button.types.ts

feat: add name property to radio-group and propagate it to radio buttons

---

packages/grid/src/vaadin-grid-mixin.js
packages/grid/test/hidden-grid.common.js

Manual cherry-pick of #8102 to `24.4` branch.
- Cherry-pick

fix: ensure grid has tabbable elements after it becomes visible (#8102) (CP: 24.4)

---

packages/virtual-list/package.json

The component already has Lit entrypoints, so we just need to remove exclusions from `package.json`.
- Experiment

experiment: prepare LitElement based virtual-list for publishing

---

packages/upload/test/adding-files.common.js

- Test for attributes instead of internal properties
- Added missing tests for drag effect

test: improve upload drag drop tests

---

packages/avatar-group/src/vaadin-avatar-group-mixin.js
packages/avatar-group/src/vaadin-avatar-group.js
packages/avatar-group/src/vaadin-lit-avatar-group-menu-item.js
packages/avatar-group/src/vaadin-lit-avatar-group-menu.js
packages/avatar-group/src/vaadin-lit-avatar-group-overlay.js
packages/avatar-group/src/vaadin-lit-avatar-group.d.ts
packages/avatar-group/src/vaadin-lit-avatar-group.js
packages/avatar-group/test/avatar-group-lit.test.js
packages/avatar-group/test/avatar-group-polymer.test.js
packages/avatar-group/test/avatar-group.common.js
packages/avatar-group/theme/lumo/vaadin-lit-avatar-group.js
packages/avatar-group/theme/material/vaadin-lit-avatar-group.js
packages/avatar-group/vaadin-lit-avatar-group.d.ts
packages/avatar-group/vaadin-lit-avatar-group.js

Depends on #8145 and #8148
- Experiment

experiment: add LitElement based version of avatar-group

---

packages/grid-pro/test/keyboard-navigation.common.js

Remove accidental console.log from grid-pro test
Chore

chore: remove accidental console.log from grid-pro test

---

packages/grid-pro/src/vaadin-grid-pro-inline-editing-mixin.js
packages/grid-pro/test/keyboard-navigation.common.js
packages/grid-pro/theme/lumo/vaadin-grid-pro-styles.js

Manually cherry-pick #8156 to `24.3`

feat: grid-pro loading editor state (#8156) (CP: 24.3)

---

dev/dashboard-layout.html
dev/dashboard.html
packages/dashboard/src/vaadin-dashboard-button.js
packages/dashboard/src/vaadin-dashboard-layout.js
packages/dashboard/src/vaadin-dashboard-section.js
packages/dashboard/src/vaadin-dashboard-widget.js
packages/dashboard/src/vaadin-dashboard.js
packages/dashboard/test/helpers.ts

Add `dashboardComponent` feature flag
Chore

chore: add dashboard feature flag

---

packages/card/README.md
packages/dashboard/README.md

Mention Dashboard being experimental in readme.
Chore

chore: add dashboard feature flag mention in readme

---

packages/dashboard/theme/lumo/vaadin-dashboard-widget-styles.js

Use new Lumo handle [icons](https://github.com/vaadin/web-components/pull/8163) in Dashboard widget
Refactor / UX

refactor: use new handle icons in dashboard widget

---

packages/dashboard/src/vaadin-dashboard-styles.js
packages/dashboard/src/vaadin-dashboard-widget.js
packages/dashboard/test/helpers.ts
packages/dashboard/theme/lumo/vaadin-dashboard-widget-styles.js

Prefer part names over ids in dashboard selectors
Part of https://github.com/vaadin/web-components/issues/8137
Refactor

refactor: prefer part names over ids in dashboard selectors

---

packages/dashboard/theme/lumo/vaadin-dashboard-widget-styles.js

Update dashboard resize mode icons
Depends on https://github.com/vaadin/web-components/pull/8190
Refactor

refactor: update dashboard resize mode icons

---

packages/date-picker/src/vaadin-date-picker-mixin.js
packages/date-picker/test/fullscreen.common.js

Changed `autoOpenDisabled` to align with other properties and trigger update synchronously.
- Refactor

refactor: make autoOpenDisabled property use sync: true

---

packages/message-list/package.json
packages/message-list/src/vaadin-message-list-mixin.d.ts
packages/message-list/src/vaadin-message-list-mixin.js
packages/message-list/src/vaadin-message-list.d.ts
packages/message-list/src/vaadin-message-list.js
packages/message-list/src/vaadin-message-mixin.d.ts
packages/message-list/src/vaadin-message-mixin.js
packages/message-list/src/vaadin-message.d.ts
packages/message-list/src/vaadin-message.js

Extracted `vaadin-message` and `vaadin-message-list` logic into mixins to be reused by Lit based version.
- Refactor

refactor: extract message and message-list logic into mixins

---

packages/message-list/src/vaadin-lit-message-list.d.ts
packages/message-list/src/vaadin-lit-message-list.js
packages/message-list/src/vaadin-lit-message.d.ts
packages/message-list/src/vaadin-lit-message.js
packages/message-list/src/vaadin-message-list-mixin.js
packages/message-list/test/message-list-lit.test.js
packages/message-list/test/message-list-polymer.test.js
packages/message-list/test/message-list.common.js
packages/message-list/test/message-lit.test.js
packages/message-list/test/message-polymer.test.js
packages/message-list/test/message.common.js
packages/message-list/theme/lumo/vaadin-lit-message-list.js
packages/message-list/theme/lumo/vaadin-lit-message.js
packages/message-list/theme/material/vaadin-lit-message-list.js
packages/message-list/theme/material/vaadin-lit-message.js
packages/message-list/vaadin-lit-message-list.d.ts
packages/message-list/vaadin-lit-message-list.js
packages/message-list/vaadin-lit-message.d.ts
packages/message-list/vaadin-lit-message.js

Added Lit based version of `vaadin-message` and `vaadin-message-list`.
- Experiment

experiment: add LitElement based version of message-list

---

packages/tooltip/src/vaadin-tooltip-overlay-styles.js
packages/tooltip/test/visual/lumo/tooltip.test.js
packages/tooltip/test/visual/material/tooltip.test.js

Fixes vaadin/flow-components#6865

refactor!: set white-space: pre-wrap on the tooltip content

---

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js
packages/multi-select-combo-box/test/selecting-items.test.js

Manual cherry-pick of #8301 to `24.5` branch.
- Cherry-pick

fix: prevent unselecting committed value on outside click (#8301) (CP: 24.5)

---

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js
packages/multi-select-combo-box/test/selecting-items.test.js

Extracted from #8301 to cherry-pick relevant fix also to 24.4 branch.
- Cherry-pick

fix: clear internal combo-box correctly with allowCustomValue (CP: 24.4)

---

packages/grid/src/vaadin-grid-selection-column-base-mixin.js
packages/grid/test/selection.common.js

Manual cherry-pick of #8317 to branch 24.5.

fix: prevent recurring selection attempts during drag selection (#8317) (CP: 24.5)

---

packages/dashboard/src/vaadin-dashboard.d.ts
packages/dashboard/test/typings/dashboard.types.ts

Adds missing dashboard section type to dashboard events that can also occur for sections.

fix: add missing section type to dashboard events

---

packages/date-picker/src/vaadin-lit-month-calendar.js
packages/horizontal-layout/src/vaadin-lit-horizontal-layout.d.ts
packages/icon/src/vaadin-lit-icon.d.ts
packages/icon/src/vaadin-lit-iconset.d.ts
packages/vertical-layout/src/vaadin-lit-vertical-layout.d.ts

Fix year in lit-based files license header
Chore

chore: fix year in license headers

---

packages/virtual-list/src/vaadin-virtual-list-mixin.d.ts
packages/virtual-list/src/vaadin-virtual-list-mixin.js

Improve virtual list item accessible name generator docs
Docs

docs: improve virtual list item accessible name generator docs

---

packages/custom-field/src/vaadin-custom-field-mixin.js
packages/custom-field/test/validation.test.js

Manual cherry-pick of #8012 to `24.4` branch.
- Cherry-pick

fix: prevent possible errors when inputs property is not set (#8012) (CP: 24.4)

---

packages/crud/src/vaadin-crud.js
packages/crud/test/crud-buttons.test.js

Manual cherry-pick of #8372 to `24.4` branch.
- Cherry-pick

fix: teleport CRUD form to overlay if some buttons are not set (#8372) (CP: 24.4)

---

packages/app-layout/test/app-layout.test.js
packages/app-layout/test/not-animated-styles.js
packages/avatar-group/test/avatar-group.test.js
packages/board/test/helpers.js
packages/board/test/redraw.test.js
packages/charts/test/chart-element.test.js
packages/component-base/test/overflow-controller.test.js
packages/component-base/test/resize-mixin.test.js
packages/dialog/test/header-footer.common.js
packages/form-layout/test/form-layout.test.js
packages/grid/test/column-groups.common.js
packages/grid/test/column-rendering.common.js
packages/grid/test/frozen-columns.common.js
packages/grid/test/helpers.js
packages/grid/test/resizing.common.js
packages/grid/test/scrolling-mode.common.js
packages/icon/test/icon-font.common.js
packages/menu-bar/test/overflow.common.js
packages/multi-select-combo-box/test/chips.test.js
packages/tabs/test/tabs.common.js
packages/text-area/test/text-area.common.js

Cherry-picks #8387 to branch 24.5
Conflicts:
- `packages/app-layout/test/app-layout.test.js` (import declarations difference)
- `packages/multi-select-combo-box/test/chips.test.js` (import declarations difference)

test: replace onceResized with nextResize (#8387) (CP: 24.5)

---

dev/avatar.html

Currently we only have dev page for `vaadin-avatar-group`. This PR adds one for `vaadin-avatar` too.

chore: add dev page for standalone avatar

---

packages/board/package.json
packages/board/src/vaadin-board-row-mixin.d.ts
packages/board/src/vaadin-board-row-mixin.js
packages/board/src/vaadin-board-row.d.ts
packages/board/src/vaadin-board-row.js

Extracted `vaadin-board-row` logic into mixin to be reused by the Lit version.
- Refactor

refactor: extract board row logic into reusable mixin

---

packages/map/package.json
packages/map/src/vaadin-lit-map.d.ts
packages/map/src/vaadin-lit-map.js
packages/map/test/map-lit.test.js
packages/map/test/map-polymer.test.js
packages/map/test/map.common.js
packages/map/test/styles-lit.test.js
packages/map/test/styles-polymer.test.js
packages/map/test/styles.common.js
packages/map/theme/lumo/vaadin-lit-map.js
packages/map/theme/material/vaadin-lit-map.js
packages/map/vaadin-lit-map.d.ts
packages/map/vaadin-lit-map.js

Added an experimental version of `vaadin-map` based on LitElement.
- Experiment

experiment: add LitElement based version of vaadin-map

---

packages/field-highlighter/src/vaadin-field-highlighter-styles.js
packages/field-highlighter/src/vaadin-field-outline.js
packages/field-highlighter/src/vaadin-user-tag.js
packages/field-highlighter/src/vaadin-user-tags-overlay.js
packages/field-highlighter/src/vaadin-user-tags.js

Make field highlighter's internal components base on `LitElement`
Refactor

refactor: use LitElement for field highlighter internal elements

---

packages/crud/package.json
packages/form-layout/package.json

Added `lit` as a direct dependency to `crud` and `form-layout` packages to align with other components.

chore: add missing lit dependency to package.json files

---

packages/combo-box/src/vaadin-combo-box-mixin.js

Updated `change` event JSDoc annotation to align with other components and also the one defined here:
https://github.com/vaadin/web-components/blob/9a0030dd2976053cd6a9681c83686514287a260e/packages/combo-box/src/vaadin-combo-box.js#L141

docs: align JSDoc annotation for combo-box change event

---

wtr-utils.js

Extended the set of filtered warnings to suppress those that are related to Lit dev mode.

chore: suppress Lit related console warnings in tests

---

packages/a11y-base/test/focus-trap-controller.test.js
packages/app-layout/test/helpers.js
packages/checkbox-group/test/checkbox-group.common.js
packages/checkbox-group/test/validation.common.js
packages/checkbox/test/validation.common.js
packages/component-base/test/virtualizer-reorder-elements.test.js
packages/context-menu/test/a11y.common.js
packages/dashboard/test/dashboard-keyboard.test.ts
packages/date-picker/test/fullscreen.common.js
packages/date-picker/test/keyboard-input.common.js
packages/date-picker/test/keyboard-navigation.common.js
packages/date-time-picker/test/validation.common.js
packages/field-highlighter/test/field-components.test.js
packages/grid-pro/test/edit-column.common.js
packages/grid-pro/test/keyboard-navigation.common.js
packages/grid/test/disabled.common.js
packages/grid/test/keyboard-interaction-mode.common.js
packages/menu-bar/test/menu-bar.common.js
packages/menu-bar/test/sub-menu.common.js
packages/password-field/test/password-field.common.js
packages/popover/test/a11y.test.js
packages/radio-group/test/radio-group.common.js
packages/radio-group/test/validation.common.js
packages/rich-text-editor/test/a11y.common.js
packages/upload/test/file.common.js
test/integration/dialog-accordion.test.js
test/integration/dialog-date-picker.test.js
test/integration/grid-pro-custom-editor.test.js
test/test-runner-commands/index.js

test: add shortcut for pressing multiple keys simultaneously (#8536) (CP: 24.6)

---

packages/form-layout/test/form-layout.test.js

The PR refactors FormLayout tests to avoid relying on implementation details.
Part of #8583

test: refactor tests to avoid relying on implementation details

---

packages/form-layout/src/vaadin-form-layout.js

refactor: use _onResize instead of IntersectionObserver (#8620) (CP: 24.6)

---

package.json
yarn.lock

Upgraded `playwright` version to latest to see if tests pass.

chore: upgrade playwright version to ^1.50

---

packages/vaadin-material-styles/version.js
wtr-utils.js

Related to #8580
- Deprecation

chore: add deprecation warning to Material theme

---

packages/vaadin-lumo-styles/utilities/transition.js

Fixes the transition utility classes. Also adds 2 new Lumo properties for controlling the timing function and duration.

feat: update transition utility classes, add custom CSS properties

---

packages/icons/gulpfile.cjs
packages/rich-text-editor/gulpfile.cjs
packages/vaadin-lumo-styles/gulpfile.cjs
packages/vaadin-material-styles/gulpfile.cjs
test/integration/notification-overlay.test.js

When testing the new version of `eslint-config-vaadin`, I found some warnings. This PR fixes them.

chore: fix eslint warnings reported with new config version

---

packages/text-area/test/text-area.test.js
packages/text-area/test/typings/text-area.types.ts

Same as #8715 but for `vaadin-text-area` (see the above PR description for clarification).
- Test

test: cleanup text-area unit tests covered by mixins tests

---

packages/form-layout/test/form-layout-auto-responsive.test.js
packages/form-layout/test/helpers.js
test/integration/dialog-form-layout.test.js
test/integration/horizontal-layout-form-layout.test.js

Extracts the `assertFormLayoutGrid` test helper to improve code reusability.
Part of #8687

test: extract assertFormLayoutGrid test helper

---

packages/form-layout/test/form-layout-auto-responsive.test.js
test/integration/dialog-form-layout.test.js
test/integration/horizontal-layout-form-layout.test.js

Rewrites FormLayout autoResponsive tests in a more concise manner.
Part of #8687

test: make autoResponsive tests more concise

---

wtr-utils.js

Update the web-test-runner change detection script to use 24.7 as a base branch for Vaadin 24.7

chore: update change detection branch to 24.7

---

packages/app-layout/src/vaadin-app-layout-mixin.d.ts
packages/avatar-group/src/vaadin-avatar-group-mixin.d.ts
packages/avatar/src/vaadin-avatar-mixin.d.ts
packages/component-base/src/i18n-mixin.d.ts
packages/crud/src/vaadin-crud-mixin.d.ts
packages/dashboard/src/vaadin-dashboard.d.ts

Cherry-pick of https://github.com/vaadin/web-components/pull/8797

fix: properly handle functions in partial I18N types (CP: 24.7)

---

packages/date-time-picker/test/visual/common.js

Cherry-pick of #8581 to `24.6` branch.
- Cherry-pick

test: correctly apply CSS in date-time-picker visual test (#8581) (CP: 24.6)

---

packages/master-detail-layout/src/vaadin-master-detail-layout.js
packages/master-detail-layout/test/master-detail-layout.test.js
packages/master-detail-layout/test/overlay-mode.test.js

Updated the mode detection logic in preparation for implementing animated transitions.
- Refactor

refactor: preserve mode when adding or removing details

---

packages/master-detail-layout/src/vaadin-master-detail-layout.js
packages/master-detail-layout/test/aria.test.js

feat: add role and ARIA attributes to master-detail-layout

---

dev/master-detail-layout.html
packages/master-detail-layout/src/vaadin-master-detail-layout-transition-styles.js

Added transition styles for vertical orientation (copied existing ones and changed to use `translateY` for now).
- Feature

feat: add vertical transition styles to master-detail-layout

---

packages/menu-bar/src/vaadin-menu-bar-mixin.js
packages/menu-bar/test/menu-bar.test.js
packages/menu-bar/test/overflow.test.js
packages/menu-bar/test/sub-menu.test.js

This reverts commit ddeb5dce91b28b266d5bdee5fdfba0177971debf.
Reverted since the PR causes issue with disappearing items in Flow counterpart. I'll investigate this further later.
- Revert

Revert "refactor: use Lit for rendering menu-bar buttons (#8829)"

---

packages/master-detail-layout/LICENSE

I missed to add this file in the initial PR with the package setup.

chore: add missing LICENSE file to master-detail-layout

---

packages/master-detail-layout/src/vaadin-master-detail-layout-transition-styles.js
packages/master-detail-layout/src/vaadin-master-detail-layout.d.ts
packages/master-detail-layout/src/vaadin-master-detail-layout.js

Part of https://github.com/vaadin/web-components/issues/8812
Added custom CSS property (needs to be set globally) to control MDL transition duration.
- Featur

feat: add transition duration custom property to master-detail-layout

---

packages/component-base/src/slot-styles-mixin.js

fix: use array instead of object in slotStyles by default

---

packages/button/src/vaadin-button-base.js
packages/component-base/src/style-props.js
packages/field-base/src/styles/field-shared-styles.js
packages/input-container/src/vaadin-input-container-styles.js

Fix the forced colors mode for button and text field.

Base styles forced colors

---

packages/multi-select-combo-box/test/accessibility.test.js
packages/multi-select-combo-box/test/chips.test.js
packages/multi-select-combo-box/test/lit-renderer-directives.test.js
packages/multi-select-combo-box/test/multi-select-combo-box-test-styles.js
packages/multi-select-combo-box/test/readonly.test.js
packages/multi-select-combo-box/test/selecting-items.test.js
packages/multi-select-combo-box/test/validation.test.js

Added a subset of Lumo to ensure chips tests pass and updated tests to use `src` entrypoint.
- Test

test: update multi-select-combo-box tests to use src version

---

packages/grid-pro/test/edit-column-renderer.test.js
packages/grid-pro/test/edit-column-type.test.js
packages/grid-pro/test/edit-column.test.js
packages/grid-pro/test/grid-pro.test.js
packages/grid-pro/test/keyboard-navigation.test.js
packages/grid-pro/test/lit-renderer-directives.test.js
packages/grid-pro/test/lit.test.js

Updated `vaadin-grid-pro` unit tests to use unstyled component.
- Test

test: update grid-pro unit tests to use unstyled component

---

packages/vaadin-lumo-styles/global.css
packages/vaadin-lumo-styles/lumo.css
packages/vaadin-lumo-styles/package.json
packages/vaadin-lumo-styles/props.css
packages/vaadin-lumo-styles/src/global/badge.css
packages/vaadin-lumo-styles/src/global/color.css
packages/vaadin-lumo-styles/src/global/style.css
packages/vaadin-lumo-styles/src/global/typography.css
packages/vaadin-lumo-styles/src/props/color.css
packages/vaadin-lumo-styles/src/props/icons.css
packages/vaadin-lumo-styles/src/props/sizing.css
packages/vaadin-lumo-styles/src/props/spacing.css
packages/vaadin-lumo-styles/src/props/style.css
packages/vaadin-lumo-styles/src/props/typography.css
web-dev-server.config.js
wtr-utils.js

refactor: port core Lumo styles to CSS files

---

rollup.config.js

chore: update rollup.config.js to use ES modules

---

wtr-utils.js

Optimizes PR checks by running only visual tests that meet one of the following conditions:
- The test has been migrated to use Lumo CSS files (i.e. it imports a CSS file)
- The test has been directly modified

chore: only run visual tests that import CSS files or changed directly

---

packages/input-container/src/vaadin-lit-input-container.js
packages/input-container/test/visual/lumo/input-container.test.js
packages/vaadin-lumo-styles/components.css
packages/vaadin-lumo-styles/components/input-container.css
packages/vaadin-lumo-styles/global.css
packages/vaadin-lumo-styles/lumo.css
packages/vaadin-lumo-styles/src/components/input-container.css

refactor: port input-container Lumo styles to CSS files

---

web-dev-server.config.js
wtr-utils.js

This should help to detect issues with possible Lit methods overrides like the one fixed in #9103.

chore: use Lit in development mode in dev pages and tests

---

packages/overlay/test/animations.test.js
packages/overlay/test/restore-focus.test.js

Updated `vaadin-overlay` unit tests to replace Polymer based helper elements with vanilla custom elements.
- Test

test: use vanilla custom elements in vaadin-overlay tests

---

packages/checkbox-group/test/visual/common.js
packages/checkbox/test/visual/common.js
packages/combo-box/test/visual/common.js
packages/custom-field/test/visual/common.js
packages/date-picker/test/visual/common.js
packages/date-time-picker/test/visual/common.js
packages/login/test/visual/common.js
packages/multi-select-combo-box/test/visual/common.js
packages/number-field/test/visual/common.js
packages/password-field/test/visual/common.js
packages/password-field/test/visual/lumo/password-field.test.js
packages/password-field/test/visual/material/password-field.test.js
packages/radio-group/test/visual/common.js
packages/select/test/visual/common.js
packages/text-area/test/visual/common.js
packages/text-field/test/visual/common.js
packages/time-picker/test/visual/common.js

Animations were not disabled on label, helper text, and required indicator which caused random visual test failures.
Part of #9082

test: disable animation on label, helper, required indicator

---

packages/grid-pro/test/edit-column-renderer.test.js

Replaced Polymer based custom editor element in custom editor test with a vanilla custom element.
- Test

test: replace Polymer based fixture element in grid-pro tests

---

packages/details/src/vaadin-lit-details-summary.js
packages/details/src/vaadin-lit-details.js
packages/details/test/visual/lumo/details.test.js
packages/vaadin-lumo-styles/components.css
packages/vaadin-lumo-styles/components/details-summary.css
packages/vaadin-lumo-styles/components/details.css
packages/vaadin-lumo-styles/src/components/details-summary.css
packages/vaadin-lumo-styles/src/components/details.css

refactor: port details Lumo styles to CSS files

---

packages/button/src/vaadin-button-base-styles.js
packages/component-base/src/style-props.js
packages/details/src/vaadin-details-summary-base-styles.js
packages/field-base/src/styles/button-base-styles.js
packages/field-base/src/styles/field-base-styles.js
packages/input-container/src/vaadin-input-container-base-styles.js
packages/item/src/vaadin-item-base-styles.js
packages/password-field/src/vaadin-password-field-button-base-styles.js

Cherry-pick of https://github.com/vaadin/web-components/pull/9187 to `main` branch.
- Experiment

experiment: add cursor properties for interactive elements

---

packages/select/src/vaadin-select-base-styles.js

Cherry-pick of https://github.com/vaadin/web-components/pull/9183 to `main` branch.
- Experiment

experiment: update select base styles for focus outline

---

.stylelintrc
package.json

Enables stylelint for `*.css` files.
Part of #9082

chore: enable stylelint for css files

---

packages/text-area/src/vaadin-text-area-mixin.js
packages/text-area/test/text-area.test.js

fix: include border width in max-height calculation

---

dev/context-menu.html
dev/grid-pro.html
dev/grid.html
dev/virtual-list.html

We no longer have Lit entrypoints so their mentions should be removed.

chore: remove commented Lit based imports from dev pages

---

DEVELOPMENT.md

Fixed the description of `updateVersion.js` script. Also updated version numbers.

chore: update DEVELOPMENT.md, remove mention of Material

---

wtr-utils.js

Update the web-test-runner change detection script to use 24.8 as a base branch for Vaadin 24.8

chore: update change detection branch to 24.8

---

scripts/check-releases.js

Remove 24.5 as it's no longer maintained.

chore: drop 24.5 from release check

---

dev/dashboard-layout.html
dev/dashboard.html
packages/dashboard/README.md
packages/dashboard/src/vaadin-dashboard-button.js
packages/dashboard/src/vaadin-dashboard-layout.js
packages/dashboard/src/vaadin-dashboard-section.js
packages/dashboard/src/vaadin-dashboard-widget.js
packages/dashboard/src/vaadin-dashboard.js
packages/dashboard/test/helpers.ts

Removes the feature flag from `vaadin-dashboard` in 24.8.

chore: remove dashboard feature flag

---

dev/avatar-group.html

add dev page example for max-items-visible

---

dev/select.html
packages/select/src/vaadin-select-item.js
packages/select/src/vaadin-select-list-box.js
packages/select/src/vaadin-select-overlay.js
packages/select/src/vaadin-select-value-button.js
packages/select/src/vaadin-select.js
packages/select/test/visual/lumo/select.test.js
packages/vaadin-lumo-styles/components.css
packages/vaadin-lumo-styles/components/select.css
packages/vaadin-lumo-styles/mixins/input-field-shared.js
packages/vaadin-lumo-styles/src/components/select-overlay.css
packages/vaadin-lumo-styles/src/components/select-value-button.css
packages/vaadin-lumo-styles/src/components/select.css
packages/vaadin-lumo-styles/src/mixins/base-layer-reset.css
packages/vaadin-themable-mixin/css-injection-mixin.js

feat: port select Lumo styles to CSS files

---

packages/context-menu/src/vaadin-context-menu-mixin.js
packages/context-menu/test/overlay.test.js
packages/menu-bar/test/sub-menu.test.js

fix: hide context-menu overlay until rendered (#9329) (CP: 24.8)

---

packages/avatar-group/src/vaadin-avatar-group-mixin.js

We already use Lit for rendering avatars in the group, let's also use it for `vaadin-avatar-group-overlay`.
- Refactor

refactor: update avatar-group overlay to be rendered using Lit

---

dev/checkbox-group.html
dev/checkbox.html
dev/radio-group.html
packages/checkbox-group/src/vaadin-checkbox-group.js
packages/checkbox-group/test/visual/lumo/checkbox-group.test.js
packages/checkbox/src/vaadin-checkbox.js
packages/checkbox/test/visual/lumo/checkbox.test.js
packages/radio-group/src/vaadin-radio-button.js
packages/radio-group/src/vaadin-radio-group.js
packages/radio-group/test/visual/lumo/radio-button.test.js
packages/radio-group/test/visual/lumo/radio-group.test.js
packages/vaadin-lumo-styles/components.css
packages/vaadin-lumo-styles/components/checkbox-group.css
packages/vaadin-lumo-styles/components/checkbox.css
packages/vaadin-lumo-styles/components/radio-button.css
packages/vaadin-lumo-styles/components/radio-group.css
packages/vaadin-lumo-styles/src/components/checkbox-group.css
packages/vaadin-lumo-styles/src/components/checkbox.css
packages/vaadin-lumo-styles/src/components/radio-button.css
packages/vaadin-lumo-styles/src/components/radio-group.css
packages/vaadin-lumo-styles/src/mixins/checkable-field.css
packages/vaadin-lumo-styles/src/mixins/checkable.css
packages/vaadin-lumo-styles/src/mixins/group-field.css

feat: port checkbox and radio button Lumo styles to CSS files

---

dev/tooltip.html
packages/tooltip/src/vaadin-tooltip-overlay.js
packages/tooltip/src/vaadin-tooltip.js
packages/tooltip/test/visual/lumo/tooltip.test.js
packages/vaadin-lumo-styles/components.css
packages/vaadin-lumo-styles/components/tooltip.css
packages/vaadin-lumo-styles/src/components/tooltip-overlay.css
wtr-utils.js

feat: port tooltip Lumo styles to CSS files

---

dev/notification.html
packages/notification/src/vaadin-notification.js
packages/notification/test/visual/lumo/notification.test.js
packages/vaadin-lumo-styles/components.css
packages/vaadin-lumo-styles/components/notification.css
packages/vaadin-lumo-styles/src/components/notification-card.css
packages/vaadin-lumo-styles/src/components/notification-container.css
packages/vaadin-themable-mixin/css-injection-mixin.js
wtr-utils.js

feat: port notification Lumo styles to CSS files

---

dev/split-layout.html
packages/split-layout/src/vaadin-split-layout.js
packages/split-layout/test/visual/lumo/split-layout.test.js
packages/vaadin-lumo-styles/components.css
packages/vaadin-lumo-styles/components/split-layout.css
packages/vaadin-lumo-styles/src/components/split-layout.css

feat: port split-layout Lumo styles to CSS files

---

wtr-utils.js

Allow filtering integration test files using `--glob`.
- Internal

chore: support glob parameter with integration tests

---

packages/overlay/src/vaadin-overlay-stack-mixin.js
packages/popover/src/vaadin-popover.js
test/integration/popover-tooltip.test.js

fix: allow popover to close while tooltip is open (#9397) (CP: 24.8)

---

packages/crud/src/styles/vaadin-crud-dialog-overlay-styles.d.ts
packages/crud/src/styles/vaadin-crud-dialog-overlay-styles.js
packages/crud/src/styles/vaadin-crud-styles.d.ts
packages/crud/src/styles/vaadin-crud-styles.js
packages/crud/src/vaadin-crud-dialog.js
packages/crud/src/vaadin-crud.js

Extracted `crud` core styles into separate file in `styles` folder.
- Refactor

refactor: extract crud core CSS to styles folder

---

packages/form-layout/src/styles/vaadin-form-item-styles.d.ts
packages/form-layout/src/styles/vaadin-form-item-styles.js
packages/form-layout/src/styles/vaadin-form-layout-styles.d.ts
packages/form-layout/src/styles/vaadin-form-layout-styles.js
packages/form-layout/src/styles/vaadin-form-row-styles.d.ts
packages/form-layout/src/styles/vaadin-form-row-styles.js
packages/form-layout/src/vaadin-form-item.js
packages/form-layout/src/vaadin-form-layout-mixin.js
packages/form-layout/src/vaadin-form-layout.js
packages/form-layout/src/vaadin-form-row.js

Extracted `form-layout` core styles into separate file in `styles` folder.
- Refactor

refactor: extract form-layout core CSS to styles folder

---

packages/vertical-layout/src/styles/vaadin-vertical-layout-styles.d.ts
packages/vertical-layout/src/styles/vaadin-vertical-layout-styles.js
packages/vertical-layout/src/vaadin-vertical-layout.js

Extracted `vertical-layout` core styles into separate file in `styles` folder.
- Refactor

refactor: extract vertical-layout core CSS to styles folder

---

packages/horizontal-layout/src/styles/vaadin-horizontal-layout-styles.d.ts
packages/horizontal-layout/src/styles/vaadin-horizontal-layout-styles.js
packages/horizontal-layout/src/vaadin-horizontal-layout.js

Extracted `horizontal-layout` core styles into separate file in `styles` folder.
- Refactor

refactor: extract horizontal-layout core CSS to styles folder

---

packages/notification/src/styles/vaadin-notification-card-styles.d.ts
packages/notification/src/styles/vaadin-notification-card-styles.js
packages/notification/src/styles/vaadin-notification-container-styles.d.ts
packages/notification/src/styles/vaadin-notification-container-styles.js
packages/notification/src/vaadin-notification.js

Extracted `notification` core styles into separate file in `styles` folder.
- Refactor

refactor: extract notification core CSS to styles folder

---

dev/tabs.html
packages/tabs/src/vaadin-tab.js
packages/tabs/src/vaadin-tabs.js
packages/tabs/test/visual/lumo/tabs.test.js
packages/vaadin-lumo-styles/components.css
packages/vaadin-lumo-styles/components/tab.css
packages/vaadin-lumo-styles/components/tabs.css
packages/vaadin-lumo-styles/src/components/tab.css
packages/vaadin-lumo-styles/src/components/tabs.css

feat: port tabs Lumo styles to CSS files

---

dev/map.html
packages/map/src/vaadin-map.js
packages/map/test/visual/lumo/map.test.js
packages/vaadin-lumo-styles/components.css
packages/vaadin-lumo-styles/components/map.css
packages/vaadin-lumo-styles/src/components/map.css

feat: port map Lumo styles to CSS files

---

dev/messages.html
packages/message-input/src/vaadin-message-input.js
packages/message-input/test/visual/lumo/message-input.test.js
packages/message-list/src/vaadin-message.js
packages/message-list/test/visual/lumo/message-list.test.js
packages/message-list/test/visual/lumo/message.test.js
packages/vaadin-lumo-styles/components.css
packages/vaadin-lumo-styles/components/message-input.css
packages/vaadin-lumo-styles/components/message-list.css
packages/vaadin-lumo-styles/components/message.css
packages/vaadin-lumo-styles/src/components/message-input.css
packages/vaadin-lumo-styles/src/components/message.css

feat: port message component Lumo styles to CSS files

---

dev/app-layout.html
packages/app-layout/src/vaadin-app-layout.js
packages/app-layout/src/vaadin-drawer-toggle.js
packages/app-layout/test/visual/lumo/app-layout.test.js
packages/vaadin-lumo-styles/components.css
packages/vaadin-lumo-styles/components/app-layout.css
packages/vaadin-lumo-styles/components/drawer-toggle.css
packages/vaadin-lumo-styles/src/components/app-layout.css
packages/vaadin-lumo-styles/src/components/drawer-toggle.css

feat: port app-layout Lumo styles to CSS files

---

dev/grid-pro.html
packages/grid-pro/test/visual/lumo/grid-pro.test.js
packages/vaadin-lumo-styles/components.css
packages/vaadin-lumo-styles/components/grid-pro-edit-column.css
packages/vaadin-lumo-styles/components/grid-pro.css
packages/vaadin-lumo-styles/src/components/grid-pro-edit-select.css
packages/vaadin-lumo-styles/src/components/grid-pro.css
packages/vaadin-lumo-styles/src/mixins/grid-pro-editor.css

Depends on
- https://github.com/vaadin/web-components/pull/9520

feat: port grid-pro Lumo styles to CSS files

---

dev/select.html

Follow-up to #9567 - fixed some incorrect code, sorry about the hassle 🙈 

chore: fix incorrect condition in select dev page

---

dev/progress-bar.html

Adds controls for state and theme selection for the `progress-bar` element.

chore: improve progress-bar dev page

---

dev/multi-select-combo-box.html

Adds controls for toggling features and states for the `multi-select-combo-box` element.

chore: improve MSCB dev page

---

packages/master-detail-layout/src/vaadin-master-detail-layout.js
packages/master-detail-layout/test/visual/lumo/master-detail-layout.test.js
packages/vaadin-lumo-styles/components.css
packages/vaadin-lumo-styles/components/master-detail-layout.css
packages/vaadin-lumo-styles/src/components/master-detail-layout.css

Depends on 
- https://github.com/vaadin/web-components/pull/9604
Part of #9082

feat: port master-detail-layout Lumo styles to CSS files

---

packages/tabsheet/src/vaadin-tabsheet.js
packages/tabsheet/test/visual/lumo/tabsheet.test.js
packages/vaadin-lumo-styles/components.css
packages/vaadin-lumo-styles/components/tabsheet.css
packages/vaadin-lumo-styles/src/components/tabsheet.css

Depends on 
- https://github.com/vaadin/web-components/pull/9524
Part of #9082

feat: port tabsheet Lumo styles to CSS files

---

packages/menu-bar/src/vaadin-menu-bar-mixin.js
packages/menu-bar/test/dom/__snapshots__/menu-bar.test.snap.js
packages/menu-bar/test/dom/menu-bar.test.js
packages/menu-bar/test/overflow.test.js
packages/menu-bar/test/visual/lumo/menu-bar.test.js
packages/menu-bar/test/visual/material/menu-bar.test.js
test/integration/dialog-menu-bar.test.js

Manual cherry-pick of #9618 to `24.8` branch.
- Cherry-pick

fix!: debounce updating overflow to improve performance (#9618) (CP: 24.8)

---

packages/vaadin-lumo-styles/src/utilities/accessibility.css
packages/vaadin-lumo-styles/src/utilities/background.css
packages/vaadin-lumo-styles/src/utilities/border.css
packages/vaadin-lumo-styles/src/utilities/filter.css
packages/vaadin-lumo-styles/src/utilities/flexbox-grid.css
packages/vaadin-lumo-styles/src/utilities/layout.css
packages/vaadin-lumo-styles/src/utilities/shadows.css
packages/vaadin-lumo-styles/src/utilities/sizing.css
packages/vaadin-lumo-styles/src/utilities/spacing.css
packages/vaadin-lumo-styles/src/utilities/transition.css
packages/vaadin-lumo-styles/src/utilities/typography.css
packages/vaadin-lumo-styles/utility.css

feat: port class utility Lumo styles to CSS files

---

packages/notification/src/vaadin-notification-mixin.js
packages/overlay/src/vaadin-overlay-mixin.js
packages/overlay/src/vaadin-overlay-stack-mixin.js

Fixes https://github.com/vaadin/web-components/issues/9700
- Refactor

refactor: update overlay stack logic to not rely on body children

---

packages/avatar-group/src/styles/vaadin-avatar-group-base-styles.js
packages/avatar-group/src/styles/vaadin-avatar-group-core-styles.js
packages/avatar-group/src/vaadin-avatar-group-mixin.js
packages/avatar-group/src/vaadin-avatar-group-overlay.js
packages/avatar-group/src/vaadin-avatar-group.d.ts
packages/avatar-group/src/vaadin-avatar-group.js
packages/avatar-group/test/avatar-group.test.js
packages/avatar-group/test/dom/__snapshots__/avatar-group.test.snap.js
packages/vaadin-lumo-styles/src/components/avatar-group.css

Fixes https://github.com/vaadin/web-components/issues/9730
Depends on https://github.com/vaadin/web-components/pull/9753

refactor!: update avatar-group overlay to use native popover

---

packages/select/src/vaadin-select-base-mixin.js
packages/select/src/vaadin-select-overlay-mixin.js
packages/select/src/vaadin-select.js
packages/select/test/validation.test.js

Attempt to simplify the focus handling changes in https://github.com/vaadin/web-components/pull/9751.
- Refactor

refactor: cleanup focus handling changes

---

packages/popover/src/vaadin-popover-overlay.js
packages/popover/test/basic.test.js

Cherry-pick of #9826 to `24.8` branch.
- Cherry-pick

fix: save focus if target is set while popover is open (#9826) (CP: 24.8)

---

packages/tabsheet/src/styles/vaadin-tabsheet-base-styles.js
packages/tabsheet/test/visual/base/tabsheet.test.js
packages/tabsheet/test/visual/lumo/tabsheet.test.js
packages/tabsheet/theme/lumo/vaadin-tabsheet-styles.js
packages/vaadin-lumo-styles/src/components/tabsheet.css

Same as https://github.com/vaadin/web-components/pull/6689 and https://github.com/vaadin/web-components/pull/9845 but for `vaadin-tabsheet`.
- Bugfix

fix: enforce zero padding on tabsheet no-padding theme variant

---

packages/login/src/vaadin-login-overlay-mixin.js
packages/login/src/vaadin-login-overlay.d.ts
packages/login/src/vaadin-login-overlay.js
packages/login/test/login-overlay.test.js
packages/login/test/typings/login.types.ts

Fixes https://github.com/vaadin/web-components/issues/9871
- Feature

feat: fire closed event after closing animation has finished

---

wtr-utils.js

Changed to use same detection logic as for Lumo, so that we can test only changed packages.

chore: update web-test-runner config for base styles packages

---

packages/dialog/test/draggable-resizable-styles.js
packages/dialog/test/draggable-resizable.test.js

Fixed test styles intended to reset some opinionated defaults from base styles.
- Test

test: update dialog test styles to work with native popover

---

packages/progress-bar/test/dom/__snapshots__/progress-bar.test.snap.js
packages/progress-bar/test/dom/progress-bar.test.js

Added snapshot tests to `vaadin-progress-bar`.
- Test

test: add missing snapshot tests to progress-bar

---

packages/split-layout/test/dom/__snapshots__/split-layout.test.snap.js
packages/split-layout/test/dom/split-layout.test.js

Added snapshot tests to `vaadin-split-layout`.
- Test

test: add missing snapshot tests to split-layout

---

packages/dashboard/test/dom/__snapshots__/dashboard-button.test.snap.js
packages/dashboard/test/dom/__snapshots__/dashboard-layout.test.snap.js
packages/dashboard/test/dom/__snapshots__/dashboard-section.test.snap.js
packages/dashboard/test/dom/__snapshots__/dashboard-widget.test.snap.js
packages/dashboard/test/dom/__snapshots__/dashboard.test.snap.js
packages/dashboard/test/dom/dashboard-button.test.ts
packages/dashboard/test/dom/dashboard-layout.test.ts
packages/dashboard/test/dom/dashboard-section.test.ts
packages/dashboard/test/dom/dashboard-widget.test.ts
packages/dashboard/test/dom/dashboard.test.ts
web-test-runner-snapshots.config.js

Added snapshot tests to `vaadin-dashboard` and its internal components.
Also updated WTR config to allow writing snapshot tests in `.ts` files.
- Test

test: add missing snapshot tests to dashboard

---

packages/vaadin-lumo-styles/src/components/checkbox.css
packages/vaadin-lumo-styles/src/components/date-picker-overlay.css
packages/vaadin-lumo-styles/src/components/menu-bar-button.css

Improved some incorrect formatting in CSS files.

chore: fix some incorrect formatting in Lumo CSS files

---

packages/confirm-dialog/src/vaadin-confirm-dialog-mixin.d.ts
packages/confirm-dialog/src/vaadin-confirm-dialog-mixin.js
packages/dialog/src/vaadin-dialog-base-mixin.d.ts
packages/dialog/src/vaadin-dialog-base-mixin.js
packages/dialog/src/vaadin-dialog-renderer-mixin.d.ts
packages/dialog/src/vaadin-dialog-renderer-mixin.js
packages/dialog/src/vaadin-dialog-size-mixin.d.ts
packages/dialog/src/vaadin-dialog-size-mixin.js

Replaced some mentions of overlay to align with https://github.com/vaadin/web-components/pull/9983
- Docs

docs: replace mentions of overlay in dialog and confirm-dialog

---

packages/tabsheet/src/vaadin-lit-tabsheet.js
packages/tabsheet/src/vaadin-tabsheet.js
packages/tabsheet/test/tabsheet.test.js

Cherry-pick of https://github.com/vaadin/web-components/pull/10002

fix: enforce tabsheet panels to be hidden (CP: 24.8)

---

.github/workflows/gh-pages.yml

Added GitHub actions workflow to publish dev pages from `aura` branch.

chore: add GitHub Actions workflow to publish dev pages

---

packages/dashboard/src/vaadin-dashboard-widget.js
packages/dashboard/src/widget-resize-controller.js

Manual cherry-pick of #10033 to `24.9` branch.
- Cherry-pick

fix: do not set touch-action: none on dashboard to allow scroll (#10033) (CP: 24.9)

---

packages/dashboard/src/vaadin-dashboard-widget.js
packages/dashboard/src/widget-resize-controller.js

Manual cherry-pick of #10033 to `24.8` branch.
- Cherry-pick

fix: do not set touch-action: none on dashboard to allow scroll (#10033) (CP: 24.8)

---

packages/side-nav/src/vaadin-side-nav-item.js
packages/side-nav/test/dom/__snapshots__/side-nav-item.test.snap.js
test/integration/package.json
test/integration/side-nav-item-tooltip.test.js

Part of https://github.com/vaadin/flow-components/issues/7615
Manual cherry-pick of #10008 to `24.9` branch.
- Cherry-pick

feat: add tooltip support to vaadin-side-nav-item (#10008) (CP: 24.9)

---

test/integration/grid-pro-custom-editor.test.js

Manual cherry-pick of the following PRs:
- #9673 
- #10023
- Cherry-pick

test: improve flaky grid-pro custom editor integration test (CP: 24.9)

---

packages/app-layout/src/styles/vaadin-app-layout-base-styles.js
packages/avatar/src/styles/vaadin-avatar-base-styles.js
packages/item/src/styles/vaadin-item-base-styles.js
packages/master-detail-layout/src/styles/vaadin-master-detail-layout-base-styles.js

Extracted from #9958
- Refactor

refactor: add forced colors mode adjustments to base styles

---

packages/button/src/styles/vaadin-button-base-styles.js
packages/date-picker/src/styles/vaadin-date-picker-overlay-content-base-styles.js
packages/password-field/src/styles/vaadin-password-field-button-base-styles.js

Extracted from https://github.com/vaadin/web-components/pull/9958
- Refactor

refactor: update button border and tertiary variant base styles

---

packages/component-base/src/polylit-mixin.js

Follow-up to #9923
This code is no longer needed, I just missed to remove it in the previous PR.
- Refactor

refactor: remove no longer needed PolylitMixin teleportation logic

---

packages/overlay/src/vaadin-overlay-position-mixin.js
packages/overlay/test/position-mixin.test.js

Fixes https://github.com/vaadin/web-components/issues/10106
- Refactor

refactor: reset overlay position when positionTarget is removed

---

packages/charts/src/vaadin-chart-mixin.js

Add a workaround to address an issue found while testing the flow component integration tests, where a chart with drilldown enabled doesn't work as expected in some cases.
Tests affected by this issue:
- [ColumnWithLazyMultiLevelDrilldownIT#test](https://github.com/vaadin/flow-components/blob/b3ba6f370d74ea70eabd68f0cb164da81146695b/vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/ColumnWithLazyMultiLevelDrilldownIT.java#L31)
- [ColumnWithLazyMultiLevelDrilldownCallbackTestsIT#test](https://github.com/vaadin/flow-components/blob/b3ba6f370d74ea70eabd68f0cb164da81146695b/vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/ColumnWithLazyMultiLevelDrilldownCallback …

fix: add workaround for checking correct target element

---

dev/side-nav.html

They end up clashing with both Lumo and Aura.

chore: remove custom badge styles from side-nav dev page

---

scripts/buildWebtypes.js

Added `aura` to the list of packages that shouldn't have web types.

chore: exclude aura package from web-types script

---

dev/aura.html
dev/aura/badge.css
dev/card.html
packages/aura/aura.css
packages/aura/src/components/avatar.css
packages/aura/src/components/card.css
packages/aura/src/components/dialog.css
packages/aura/src/components/grid.css
packages/aura/src/components/notification.css
packages/aura/src/surface.css

feat: aura theme for avatar, card, dialog, grid, notification

---

packages/dialog/src/styles/vaadin-dialog-overlay-base-styles.js

Aligned `vaadin-dialog` base styles with `vaadin-popover` in terms of fallback values.
- Refactor

refactor: update dialog custom CSS properties fallback values

---

.gitignore
package.json
packages/aura/package.json
packages/aura/postcss.config.js
packages/vaadin-lumo-styles/package.json
packages/vaadin-lumo-styles/postcss.config.js
yarn.lock

Provides bundled / minified versions of `lumo.css` / `utility.css` for Lumo, and `aura.css` for Aura.
- Feature

feat: provide minified distribution of themes

---

package.json

Manual cherry-pick of #10225 to `24.8` branch.
Modified `release:themes` to generate Lumo autocomplete and build theme typings.
- Cherry-pick

chore: add separate release scripts (#10225) (CP: 24.8)

---

package.json

Manual cherry-pick of #10225 to `23.6` branch.
Modified `release:themes` to generate Lumo autocomplete (there is no theme typings in V23).
- Cherry-pick

chore: add separate release scripts (#10225) (CP: 23.6)

---

wtr-utils.js

This should prevent WTR failures in PRs where tests aren't supposed to run e.g. https://github.com/vaadin/web-components/pull/10235 and https://github.com/vaadin/web-components/pull/10233

chore: update change detection branch to 22.1

---

packages/aura/src/components/input-container.css

Use the dedicated text color property.

fix: use red text color to ensure proper contrast
