packages/avatar-group/src/vaadin-avatar-group-overlay.js
packages/date-picker/src/vaadin-date-picker-overlay.js

These components incorrectly have `@extends Overlay` which is no longer true. Let's update them.

docs: fix incorrect JSDoc after overlay mixins refactoring

---

packages/login/src/vaadin-login-overlay-wrapper.js
packages/login/theme/lumo/vaadin-login-overlay-styles.js
packages/login/theme/lumo/vaadin-login-overlay.js
packages/login/theme/material/vaadin-login-overlay.js

Part of #5718
Updated `vaadin-login-overlay-wrapper` to use `OverlayMixin` and styles as `css` literal.
- Refactor / Breaking change

refactor!: update login overlay to not extend vaadin-overlay

---

packages/menu-bar/src/vaadin-menu-bar-overlay.d.ts
packages/menu-bar/src/vaadin-menu-bar-overlay.js
packages/menu-bar/theme/lumo/vaadin-menu-bar.js
packages/menu-bar/theme/material/vaadin-menu-bar.js

Part of #5718
Updated `vaadin-menu-bar-overlay` to use `OverlayMixin` and styles as `css` literal.
- Refactor / Breaking change

refactor!: update menu-bar overlay to not extend vaadin-overlay

---

packages/field-highlighter/src/vaadin-user-tags-overlay.js
packages/field-highlighter/theme/lumo/vaadin-user-tags-styles.js
packages/field-highlighter/theme/lumo/vaadin-user-tags.js
packages/field-highlighter/theme/material/vaadin-user-tags-styles.js
packages/field-highlighter/theme/material/vaadin-user-tags.js

Part of #5718
Updated `vaadin-user-tags-wrapper` to use `OverlayMixin` and styles as `css` literal.
- Refactor / Breaking change

refactor!: update user-tags overlay to not extend vaadin-overlay

---

packages/custom-field/src/vaadin-custom-field.js

Related to https://github.com/vaadin/web-components/issues/6206
There is no need in `FlattenedNodesObserver` in case of `vaadin-custom-field` as we can use native `slotchange` event.
In Vaadin 14, we had to use this API because of IE11 and ShadyDOM polyfill, but we don't have this limitation anymore.
- Refactor

refactor: replace FlattenedNodesObserver with slotchange event

---

packages/a11y-base/src/list-mixin.js
packages/component-base/src/dom-utils.d.ts
packages/component-base/src/dom-utils.js
packages/component-base/test/dom-utils.test.js
packages/custom-field/src/vaadin-custom-field.js

Related to https://github.com/vaadin/web-components/issues/6206
This helper is actually copied from `vaadin-custom-field` and is a bit different from the one provided by [Polymer itself](https://github.com/Polymer/polymer/blob/1e8b246d01ea99adba305ea04c45d26da31f68f1/lib/utils/flattened-nodes-observer.js#L85).
IMO we can use this version as long as it suits our needs - see `vaadin-custom-field` and `ListMixin` tests.

feat: add getFlattenedElements helper to get slotted elements

---

packages/radio-group/test/dom/__snapshots__/radio-group.test.snap.js
packages/radio-group/test/dom/radio-button.test.js
packages/radio-group/test/dom/radio-group.test.js

While looking into replacing `FlattenedNodesObserver`, I noticed that related logic isn't covered by snapshots.
This PR fixes that. Also, removed some copy-paste leftovers from `vaadin-checkbox` snapshot tests.
- Tests

test: update radio-group snapshot tests to cover name attribute

---

packages/grid/test/helpers.js

Currently the `getBodyCellContent` grid test helper uses the index of rows in the DOM, which can return cells in the wrong row if the virtualizer has reassigned rows due to scrolling for example. This changes the helper to look up rows based on their virtual index.

test: make getBodyCellContent helper use virtual row index

---

packages/component-base/src/slot-observer.js
packages/component-base/test/slot-observer.test.js

Turns out we need to defer `SlotObserver` initial call until the microtask to ensure `children` have been upgraded.
This change makes the behavior aligned with `FlattenedNodesObserver`, including the way how `flush()` works.
Note, this change in particular fixes `vaadin-accordion` ITs failing in #6217 where `vaadin-accordion-panel` elements are not yet upgraded by the time when `ready()` callback is called for the `vaadin-accordion` itself.
- Refactor

refactor: schedule SlotObserver calls using queueMicrotask

---

packages/details/package.json
packages/details/src/vaadin-lit-details-summary.d.ts
packages/details/src/vaadin-lit-details-summary.js
packages/details/src/vaadin-lit-details.d.ts
packages/details/src/vaadin-lit-details.js
packages/details/test/details-list.test.js
packages/details/test/details-polymer.test.js
packages/details/test/details.common.js

Added `LitElement` based version of `vaadin-details` web component.
- Experiment
Same as other Lit experiments, this is not supposed to be published to npm.

experiment: add LitElement based version of vaadin-details

---

packages/split-layout/src/vaadin-split-layout.js

Related to #6206
While `vaadin-split-layout` has slots, it's enough to observe light DOM `children` changes without `slotchange`.
So in this case, I decided to use native `MutationObserver` that is [also used](https://github.com/Polymer/polymer/blob/1e8b246d01ea99adba305ea04c45d26da31f68f1/lib/utils/flattened-nodes-observer.js#L160) by `FlattenedNodesObserver`.
- Refactor

refactor: update split-layout to use MutationObserver for children

---

packages/split-layout/package.json
packages/split-layout/src/vaadin-lit-split-layout.d.ts
packages/split-layout/src/vaadin-lit-split-layout.js
packages/split-layout/test/split-layout-lit.test.js
packages/split-layout/test/split-layout-polymer.test.js
packages/split-layout/test/split-layout.common.js

Closes #6221
Added `LitElement` based version of `vaadin-split-layout` web component.
- Experiment
Same as other Lit experiments, this is not supposed to be published to npm.

experiment: add LitElement based version of vaadin-split-layout

---

packages/date-picker/test/keyboard-input.test.js
packages/date-picker/test/validation.test.js

The PR consolidates date-picker's unit tests related to validation on blur into a single file `validation.test.js`.
Part of #6146

test: move blur validation tests into a single file

---

packages/component-base/src/slot-observer.d.ts
packages/component-base/src/slot-observer.js
packages/component-base/test/slot-observer.test.js

This PR adds missing `connect()` and `disconnect()` methods from the `FlattenedNodesObserver` class.
They are needed in some cases where we disconnect the observer e.g. in case of `vaadin-chart:
https://github.com/vaadin/web-components/blob/b380caa150b40a72cc22f94d00d0adbfa29aceac/packages/charts/src/vaadin-chart.js#L897
https://github.com/vaadin/web-components/blob/b380caa150b40a72cc22f94d00d0adbfa29aceac/packages/charts/src/vaadin-chart.js#L1047-L1052
- Refactor / internal feature

refactor: update SlotObserver, add connect and disconnect

---

packages/crud/src/vaadin-crud-controllers.d.ts
packages/crud/src/vaadin-crud-controllers.js
packages/crud/src/vaadin-crud.js
packages/crud/test/crud.test.js
packages/crud/test/dom/__snapshots__/crud.test.snap.js

Related to #6206 
Replaced `FlattenedNodesObserver` with slot controllers for `form` and `grid` slots to handle corresponding `_form` and `_grid` properties. We actually already had controllers for these, they just had to be updated accordingly.
- Refactor

refactor: use slot controllers to handle CRUD grid and form

---

packages/custom-field/src/vaadin-custom-field-mixin.js
packages/custom-field/test/slot-wrapper.test.js

The fix adds a new `MutationObserver` that handles all the effective children of `vaadin-custom-field` excluding inputs.
- Bugfix

fix: observe DOM changes to fix wrapping inputs regression

---

packages/overlay/package.json
packages/overlay/src/vaadin-lit-overlay.d.ts
packages/overlay/src/vaadin-lit-overlay.js
packages/overlay/test/animations-lit.test.js
packages/overlay/test/animations-polymer.test.js
packages/overlay/test/animations.common.js
packages/overlay/test/basic-lit.test.js
packages/overlay/test/basic-polymer.test.js
packages/overlay/test/basic.common.js
packages/overlay/test/focus-trap-lit.test.js
packages/overlay/test/focus-trap-polymer.test.js
packages/overlay/test/focus-trap.common.js
packages/overlay/test/interactions-lit.test.js
packages/overlay/test/interactions-polymer.test.js
packages/overlay/test/interactions.common.js
packages/overlay/test/multiple-lit.test.js
packages/overlay/test/multiple-polymer.test.js
packages/overlay/test/multiple.common.js
packages/overlay/test/renderer-lit.test.js
packages/overlay/test/renderer-polymer.test.js
packages/overlay/test/renderer.common.js
packages/overlay/test/restore-focus-lit.test.js
packages/overlay/test/restore-focus-polymer.test.js
packages/overlay/test/restore-focus.common.js

1. Created a version of `vaadin-overlay` web component using `LitElement` base class,
2. Updated most of existing unit test suites to cover both Polymer and Lit based versions,
- Experiment
This PR can be considered a PoC. There is no ETA on when we actually decide to proceed.

experiment: add LitElement based version of vaadin-overlay

---

packages/component-base/src/polylit-mixin.js
packages/component-base/test/polylit-mixin.test.js

Currently, `PolylitMixin` throws when using [`createRenderRoot()`](https://lit.dev/docs/components/shadow-dom/#implementing-createrenderroot) because it assumes presence of `shadowRoot`.
Updated it to use `renderRoot` instead, so that `LitElement` returns appropriate node to get ID map from.
- Bugfix

fix: support using ID map when implementing createRenderRoot

---

packages/login/src/vaadin-login-form-mixin.d.ts
packages/login/src/vaadin-login-form-mixin.js
packages/login/src/vaadin-login-form.d.ts
packages/login/src/vaadin-login-form.js
packages/login/src/vaadin-login-overlay-mixin.d.ts
packages/login/src/vaadin-login-overlay-mixin.js
packages/login/src/vaadin-login-overlay.d.ts
packages/login/src/vaadin-login-overlay.js

Added `LoginOverlayMixin` and `LoginFormMixin` to be used by Polymer and Lit versions of corresponding components.
- Refactor

refactor: extract login overlay and form reusable mixins

---

packages/select/src/vaadin-select-base-mixin.js
packages/select/test/select.common.js
packages/select/test/validation.common.js

Previously, when selecting an item in `select`, the validation was triggered several times before a change event was fired: 
1. Once on opened property change:
https://github.com/vaadin/web-components/blob/09aee177f728181ddc83888af17a9a79b4d273b7/packages/select/src/vaadin-select-base-mixin.js#L259-L264
2. Once on value property change:
https://github.com/vaadin/web-components/blob/09aee177f728181ddc83888af17a9a79b4d273b7/packages/select/src/vaadin-select-base-mixin.js#L508-L511
However, in all these cases, validation was triggered before the `value-changed` event. 
The PR ensures the `value-changed => validated => change` sequence to align `select` with other components, which trigger validation after `value-changed`.
Part of #6146

fix: ensure validation between value-changed and change events

---

packages/component-base/src/polylit-mixin.js
packages/component-base/test/polylit-mixin.test.js

Added a new property config option `sync: true` to enforce immediate updates via [`performUpdate()`](https://lit.dev/docs/components/lifecycle/#performupdate) call.
This should simplify migration of complex components to Lit, by potentially reducing changes to tests.
UPD: initial rendering is still asynchronous, as we rely on [`hasUpdated`](https://lit.dev/docs/components/lifecycle/#hasupdated) property. Further updates are sync.

feat: add option to enforce synchronous Lit property update

---

packages/a11y-base/src/delegate-focus-mixin.js
packages/date-picker/test/fullscreen.test.js
packages/field-base/test/input-field-mixin.test.js
packages/select/test/validation.common.js

The PR prevents duplicate validation on programmatic blur for components extending `DelegateFocusMixin`. 
The extra validation was caused by an explicit `setFocused(false)` in `DelegateFocusMixin.blur()`, which was called despite `inputElement.blur()` triggering `focusout` that already led to `setFocused(false)`.
Part of https://github.com/vaadin/web-components/issues/6146

fix: prevent duplicate validation on programmatic blur

---

packages/date-picker/test/basic.test.js
packages/date-picker/test/dropdown.test.js
packages/date-picker/test/fullscreen.test.js
packages/date-picker/test/keyboard-navigation.test.js
packages/date-picker/test/validation.test.js

Updated `vaadin-date-picker` unit tests to add missing `nextRender()` needed for `LitElement` based version.
- Tests

test: update date-picker unit tests, add missing await

---

packages/date-picker/src/vaadin-date-picker-month-scroller.js
packages/date-picker/src/vaadin-date-picker-year-scroller.js
packages/date-picker/src/vaadin-infinite-scroller.js
packages/date-picker/test/scroller.test.js

While experimenting with `vaadin-date-picker` Lit conversion, I noticed that scrollers actually don't need `LitElement`.
They have very little logic and rely on synchronous rendering, which can be easily done with plain `HTMLElement`.
- Refactor

refactor: update date-picker infinite scroller to not use Polymer

---

packages/date-picker/src/vaadin-date-picker-mixin.js

Updated multi-property observers in `DatePickerMixin` so that they work with `LitElement` and `PolylitMixin`.
We do not support setting partial `i18n` so these observers could just check that `i18n` object is defined.
- Refactor

refactor: update observers to not use i18n object sub-property

---

packages/date-picker/src/vaadin-month-calendar.js

Similar to #6267 but for `vaadin-month-calendar`.
This PR updates one observer, computed `_days` property and a few template data bindings to use `i18n`.
- Refactor

refactor: update month calendar to not use sub-properties

---

packages/date-picker/test/dropdown.test.js
packages/date-picker/test/keyboard-input.test.js
packages/date-picker/test/validation.test.js

This PR fixes most of tests that started to fail after converting `vaadin-date-picker-overlay` component to `LitElement`.
Note, while we can add `sync: true` to most of properties in `DatePickerMixin`, opening / closing overlay is still async.
- Tests

test: update date-picker tests to support async overlay

---

packages/date-picker/src/vaadin-date-picker-overlay-content-styles.js
packages/date-picker/src/vaadin-date-picker-overlay-content.js
packages/date-picker/src/vaadin-date-picker-styles.js
packages/date-picker/src/vaadin-date-picker.js
packages/date-picker/src/vaadin-month-calendar-styles.js
packages/date-picker/src/vaadin-month-calendar.js

This is a pre-requisite for creating `vaadin-date-picker` version based on `LitElement`.
- Refactor

refactor: extract date-picker styles to reusable css literals

---

packages/date-picker/package.json
packages/date-picker/src/vaadin-date-picker-mixin.js
packages/date-picker/src/vaadin-date-picker-overlay-content-mixin.js
packages/date-picker/src/vaadin-infinite-scroller.js
packages/date-picker/src/vaadin-lit-date-picker-overlay-content.js
packages/date-picker/test/overlay-content-lit.test.js
packages/date-picker/test/overlay-content-polymer.test.js
packages/date-picker/test/overlay-content.common.js

1. Created `DatePickerOverlayContentMixin` to be used by both versions,
2. Added `vaadin-lit-date-picker-overlay-content` using the new mixin,
3. Modified `overlay.test.js` to run for both Polymer and Lit versions.
- Experiment

experiment: add Lit version of date-picker overlay content

---

packages/date-picker/package.json
packages/date-picker/src/vaadin-date-picker-overlay-content-mixin.js
packages/date-picker/src/vaadin-infinite-scroller.js
packages/date-picker/src/vaadin-lit-date-picker-overlay-content.js
packages/date-picker/src/vaadin-lit-month-calendar.js
packages/date-picker/src/vaadin-month-calendar-mixin.js
packages/date-picker/src/vaadin-month-calendar.js
packages/date-picker/test/month-calendar-lit.test.js
packages/date-picker/test/month-calendar-polymer.test.js
packages/date-picker/test/month-calendar.common.js
packages/date-time-picker/test/dom/__snapshots__/date-time-picker.test.snap.js

Depends on #6273
1. Created `MonthCalendarMixin` and `vaadin-lit-month-calendar` component,
3. Modified `month-calendar.test.js` to run for both Polymer and Lit versions.
- Experiment

experiment: add Lit version of date-picker month calendar

---

packages/date-picker/package.json
packages/date-picker/src/vaadin-date-picker-mixin.js
packages/date-picker/src/vaadin-lit-date-picker.js
packages/date-picker/test/basic-lit.test.js
packages/date-picker/test/basic-polymer.test.js
packages/date-picker/test/basic.common.js
packages/date-picker/test/dropdown-lit.test.js
packages/date-picker/test/dropdown-polymer.test.js
packages/date-picker/test/dropdown.common.js
packages/date-picker/test/events-lit.test.js
packages/date-picker/test/events-polymer.test.js
packages/date-picker/test/events.common.js
packages/date-picker/test/fullscreen-lit.test.js
packages/date-picker/test/fullscreen-polymer.test.js
packages/date-picker/test/fullscreen.common.js
packages/date-picker/test/keyboard-input-lit.test.js
packages/date-picker/test/keyboard-input-polymer.test.js
packages/date-picker/test/keyboard-input.common.js
packages/date-picker/test/keyboard-navigation-lit.test.js
packages/date-picker/test/keyboard-navigation-polymer.test.js
packages/date-picker/test/keyboard-navigation.common.js
packages/date-picker/test/theme-propagation-lit.test.js
packages/date-picker/test/theme-propagation-polymer.test.js
packages/date-picker/test/theme-propagation.common.js
packages/date-picker/test/validation-lit-test.js
packages/date-picker/test/validation-pollymer.test.js
packages/date-picker/test/validation.common.js
packages/date-picker/test/wai-aria-lit.test.js
packages/date-picker/test/wai-aria-polymer.test.js
packages/date-picker/test/wai-aria.common.js

Added `vaadin-date-picker` version based on `LitElement` and updated tests to cover both versions.
- Experiment
There are still `vaadin-date-picker-overlay` using Polymer, and I'm going to cover it in a separate PR.

experiment: add LitElement version of vaadin-date-picker

---

packages/upload/package.json
packages/upload/src/vaadin-upload-file-mixin.d.ts
packages/upload/src/vaadin-upload-file-mixin.js
packages/upload/src/vaadin-upload-file.d.ts
packages/upload/src/vaadin-upload-file.js
packages/upload/test/typings/upload-file.types.ts

1. Created `UploadFileMixin` to be used by Polymer and Lit versions of `vaadin-upload-file`,
2. Added missing `vaadin-upload-file` type definitions with corresponding tests.
- Refactor

refactor: extract upload-file logic to the mixin, add typings

---

packages/upload/src/vaadin-upload-file-list-mixin.js
packages/upload/src/vaadin-upload-file-list.js

Same as #6281 but for `vaadin-upload-file-list`. 
No typings added for now since this is an internal component.
- Refactor

refactor: extract vaadin-upload-file-list logic to the mixin

---

packages/upload/package.json
packages/upload/src/vaadin-lit-upload-file.js
packages/upload/src/vaadin-upload-file-styles.d.ts
packages/upload/src/vaadin-upload-file-styles.js
packages/upload/src/vaadin-upload-file.js
packages/upload/test/file-lit.test.js
packages/upload/test/file-polymer.test.js
packages/upload/test/file.common.js

Extracted `vaadin-upload-file` styles to separate CSS literal and created a `LitElement` based version of it.
Note: `vaadin-upload` and `vaadin-upload-file-list` components will be covered in a separate PR.
- Experiment

experiment: add LitElement version of vaadin-upload-file

---

packages/date-picker/test/keyboard-input-lit.test.js
packages/date-picker/test/keyboard-input-polymer.test.js

This fixes the following test that started to fail after the recent LitElement experimental PRs:
```
packages/date-picker/test/keyboard-input-lit.test.js:
❌ keyboard > overlay opened > should move focus back to the input on calendar date tap
AssertionError: expected false to be true
-false
+true
at Ka.<anonymous> (packages/date-picker/test/keyboard-input.common.js:218:35)
packages/date-picker/test/keyboard-input-polymer.test.js:
❌ keyboard > overlay opened > should move focus back to the input on calendar date tap
AssertionError: expected false to be true
-false
+true
at Ka.<anonymous> (packages/date-picker/test/keyboard-input.common.js:218:35)
```
The reason why the test started to fail was that unstyled version caused scroll, and that set …

test: restore date-picker Lumo styles to fix date-tap test

---

packages/custom-field/src/vaadin-custom-field.d.ts
packages/custom-field/src/vaadin-custom-field.js
packages/custom-field/test/typings/custom-field.types.ts
packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.d.ts
packages/multi-select-combo-box/test/typings/multi-select-combo-box.types.ts
packages/radio-group/src/vaadin-radio-button.d.ts
packages/radio-group/src/vaadin-radio-button.js
packages/radio-group/test/typings/radio-button.types.ts

These components have `dirty` property, but missing the types for the corresponding event.
- Bugfix / documentation

fix: add missing dirty-changed event typings and JSDoc

---

packages/checkbox/src/vaadin-checkbox-mixin.js
packages/checkbox/test/checkbox.common.js
packages/field-base/src/checked-mixin.js
packages/field-base/test/checked-mixin.test.js

I've missed adding a dirty state implementation for `radio-button` in https://github.com/vaadin/web-components/pull/6160. The dirty state of this component doesn't affect anything because the component doesn't support validation. It's there for the sake of consistency.
The component automatically becomes dirty once the user triggers a change event. Additionally, the component can be manually marked as dirty by setting the property to `true`.
Part of #6146

feat: add dirty state implementation for radio-button

---

packages/combo-box/src/vaadin-combo-box-mixin.js
packages/combo-box/src/vaadin-combo-box-scroller-mixin.js
packages/component-base/src/path-utils.d.ts
packages/component-base/src/path-utils.js
packages/component-base/src/polylit-mixin.js
packages/component-base/test/path-utils.test.js
packages/grid/src/vaadin-grid-column.js
packages/grid/src/vaadin-grid-data-provider-mixin.js
packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js
packages/grid/src/vaadin-grid-tree-column.js

Updated to use custom `get()` and `set()` implementation instead of `this.get()` that we still have.
This is needed for LitElement based versions of `vaadin-combo-box` and `vaadin-time-picker`.
- Refactor

refactor: move path utils to separate file and use them

---

packages/side-nav/src/vaadin-side-nav-item.js
packages/side-nav/test/dom/__snapshots__/side-nav-item.test.snap.js

Fixes #6310
Previously, `tabindex` was set to `0` unless the item was disabled. 
This PR changes the behavior to take `path` into account as expected.
- Bugfix

fix: set tabindex -1 on the link without href attribute

---

packages/side-nav/src/vaadin-side-nav-item.js
packages/side-nav/src/vaadin-side-nav.js
packages/side-nav/test/dom/__snapshots__/side-nav-item.test.snap.js
packages/side-nav/test/dom/__snapshots__/side-nav.test.snap.js

Closes #6311
Note, it's actually unclear to me whether this fix is needed - see https://github.com/vaadin/web-components/issues/6311#issuecomment-1669486093
- Bugfix

fix: restore list role attribute on side-nav and item lists

---

packages/component-base/src/tooltip-controller.d.ts
packages/component-base/src/tooltip-controller.js
packages/component-base/test/tooltip-controller.test.js
packages/tooltip/src/vaadin-tooltip.d.ts
packages/tooltip/src/vaadin-tooltip.js
packages/tooltip/test/tooltip.test.js
packages/tooltip/test/typings/tooltip.types.ts

Related to #6287
In case of input field components, we want the tooltip to be shown on top of the element including label, so `target` is set to the `vaadin-text-field` itself. However, `aria-describedby` element needs to be set on the `<input>` element itself.
This PR adds missing API to allow configuring where to set `aria-describedby` attribute.
- Feature
We could just check if the component has its own `ariaTarget` (the one that comes from `FieldMixin`) and use that to set the attribute. This would allow us to avoid adding new API at this point. However, that solution doesn't sound nice to me as it makes `vaadin-tooltip` coupled with the underlying implementation details of field components.

feat: add ariaTarget property for setting aria-describedby

---

packages/icon/src/vaadin-icon.d.ts
packages/icon/src/vaadin-icon.js
packages/icon/test/icon.test.js

Reflect `icon` property of a `<vaadin-icon>` as an attribute.
Fixes #6301 
Bugfix

fix: reflect icon as an attribute

---

packages/tooltip/src/vaadin-tooltip.js
packages/tooltip/test/tooltip-timers.test.js

Fixes #6316
- Bugfix
Use `vaadin-button` dev page for testing:
https://github.com/vaadin/web-components/assets/10589913/0c249465-e29b-4c58-b042-4dbafd6f235c
https://github.com/vaadin/web-components/assets/10589913/d419d261-6340-45bd-8d4d-0aa64c037920

fix: prevent closing the tooltip on overlay mouseenter

---

packages/accordion/test/accordion-panel.test.js
packages/details/src/collapsible-mixin.js
packages/details/test/details.test.js

Manual cherry-pick of #6331 to 24.0 branch.
- Cherry-pick

fix: prevent toggling opened state on click when disabled (#6331)

---

packages/accordion/test/accordion-panel.test.js
packages/details/src/collapsible-mixin.js
packages/details/test/details.test.js

Manual cherry-pick of #6331 to 24.1 branch.
- Cherry-pick

fix: prevent toggling opened state on click when disabled (CP: 24.1)

---

packages/date-picker/src/vaadin-date-picker-mixin.js

The PR inlines `_userInputValueChanged()` into `_onInput()` to remove unnecessary method abstraction.

refactor: remove unnecessary method abstraction

---

packages/login/src/vaadin-login-form.js
packages/login/test/dom/login-form.test.js
packages/login/test/login-form.test.js
packages/login/test/login-overlay.test.js

Introduces a delay to the login form autofocus logic, which aligns it with how other components implement autofocus via `DelegateFocusMixin`. This resolves an issue with Vaadin Router, where the element would otherwise validate itself due to a focus out event being caused by the router moving the element within the DOM, immediately after the element has been added initially.
This fix is not necessary in `main`, where a delay has already been added as part of the Lit migration: https://github.com/vaadin/web-components/blob/7c43f3608b306bfff0b58802179e5175739f665c/packages/login/src/vaadin-login-form-mixin.js#L23-L24
Fixes https://github.com/vaadin/flow-components/issues/5266
- Bugfix

fix: introduce delay to login form autofocus (24.1)

---

packages/date-picker/src/vaadin-date-picker-mixin.js

Removes the obsolete change dispatch logic from the `_onChange()` override.  Long time ago, the date-picker had the corresponding `__dispatchChange` check in the blur listener ([PR](https://github.com/vaadin/web-components/pull/2532)):
https://github.com/vaadin/web-components/blob/e67a1a10d00ab5a949c2880e041854a28d096c51/packages/vaadin-date-picker/src/vaadin-date-picker-mixin.js#L410-L414
This check was eventually removed, so scheduling a change dispatch isn't necessary anymore.

refactor: remove obsolete change dispatch logic

---

packages/select/src/vaadin-lit-select-item.js
packages/select/src/vaadin-select-base-mixin.js
packages/select/test/keyboard-lit.test.js
packages/select/test/keyboard-polymer.test.js
packages/select/test/keyboard.common.js
packages/select/test/select.common.js

Fixes #6337
Added a new `keyboard` test suite which covers selected item attributes.
I'm not exactly sure what was the change that introduced the regression. 
However, I feel like explicit removal of all the attributes still makes sense.
- Bugfix

fix: reset selected item attributes, add keyboard tests

---

packages/date-picker/src/vaadin-date-picker-mixin.js
packages/date-picker/test/validation.common.js

The PR ensures that the `validated` event is fired between `value-changed` and `change` events to align `date-picker` with the other components in this aspect.
> **Warning**
> As a consequence, the invalid state may be still outdated in `value-changed` event listeners. The updated invalid state is available in `change` event listeners anyway. This behavior is in line with the majority of components.
Part of https://github.com/vaadin/web-components/issues/6324

refactor!: ensure validation between value-changed and change events

---

packages/details/src/vaadin-details-base-mixin.d.ts
packages/details/test/typings/details.types.ts

Related to https://github.com/vaadin/web-components/issues/6352
This fixes a regression in `vaadin-details` types that I accidentally introduced while creating `DetailsBaseMixin`.
- Bugfix

fix: add missing mixins to DetailsBaseMixin types

---

packages/details/src/vaadin-details.js
packages/details/test/details.test.js

Manual cherry-pick of #6354 to `23.3` branch that has a totally different DOM structure.
- Cherry-pick

fix: do not toggle opened state on summary anchor click (CP: 23.3)

---

packages/confirm-dialog/src/vaadin-confirm-dialog-overlay.js
packages/confirm-dialog/test/confirm-dialog.test.js

Fixes https://github.com/vaadin/flow-components/issues/5277
Unlike `vaadin-dialog`, the slot in `vaadin-confirm-dialog` is named `header` and not `header-content`, so [this CSS](https://github.com/vaadin/web-components/blob/7072364960f0f5be719b41ae6bbd8f3750bd8fe8/packages/dialog/src/vaadin-dialog-styles.js#L24-L29) does not apply. This PR adds corresponding styles to `vaadin-confirm-dialog-overlay`.
- Bugfix

fix: reset pointer-events: none for header slot children

---

packages/confirm-dialog/src/vaadin-confirm-dialog-overlay.js
packages/confirm-dialog/test/confirm-dialog.test.js

Manual cherry-pick of #6357 to `24.1` branch.
- Cherry-pick

fix: reset pointer-events: none for header slot children (#6357) (CP: 24.1)

---

packages/confirm-dialog/src/vaadin-confirm-dialog-overlay.js
packages/confirm-dialog/test/confirm-dialog.test.js

Manual cherry-pick of #6357 to `24.0` branch.
- Cherry-pick

fix: reset pointer-events: none for header slot children (#6357) (CP: 24.0)

---

packages/confirm-dialog/src/vaadin-confirm-dialog-overlay.js
packages/confirm-dialog/test/confirm-dialog.test.js

Manual cherry-pick of #6357 to `23.3` branch.
- Cherry-pick

fix: reset pointer-events: none for header slot children (#6357) (CP: 23.3)

---

packages/date-picker/src/vaadin-date-picker-mixin.js
packages/date-picker/test/keyboard-input.common.js

Part of #5436
Same as #6363 but for `vaadin-date-picker`.
This PR changes the logic so that `validate()` is not called in `opened` set to `false` by pressing <kbd>Esc</kbd>.
- Refactor
- On outside click, `validate()` is still called. We could consider removing it too, but preferably in a separate PR
- When <kbd>Esc</kbd> is used to clear value when closed and `clearButtonVisible` set to `true`, `validate()` is still called

refactor!: do not validate when closing on Escape press

---

packages/combo-box/test/internal-filtering.test.js
packages/combo-box/test/selecting-items.test.js

Updated some of the unit tests to use `outsideClick()` helper instead of calling `close()` method.
This is done in order to better emulate the actual user behavior in case of filtering / item selection.
- Test

test: update combo-box tests to close using outsideClick

---

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js
packages/multi-select-combo-box/test/readonly.test.js

Currently, pressing <kbd>Esc</kbd> in readonly `vaadin-multi-select-combo-box` clears the selection. This PR fixes that.
- Bugfix

fix: do not clear selected items on Escape when readonly

---

packages/time-picker/src/vaadin-time-picker.js
packages/time-picker/test/events.test.js
packages/time-picker/test/keyboard-navigation.test.js

Related to #6347
This PR changes the logic of Arrow Up and Arrow Down keys to make it consistent:
Currently, there is a `change` event introduced as per https://github.com/vaadin/vaadin-time-picker/pull/110#pullrequestreview-244190551
At the same time, there is no `value-changed` event as the value doesn't change.
This is quite an old (5 years) decision from the initial version, see https://github.com/vaadin/vaadin-time-picker/pull/29#issuecomment-391421671
> Value should not be changing on arrows to follow the same behaviour logic as combo-box has: it's not selecting/changing the value on arrows. Discussed with Jouni.
The `value` property is updated when pressing arrow keys with no dropdown, followed by the `change` event.
- Bugfix

fix: update time-picker value on arrow up and down key

---

packages/time-picker/src/vaadin-time-picker.js
packages/time-picker/test/events.test.js

Fixes #6347 
This PR addresses finding from https://github.com/vaadin/web-components/issues/6347#issuecomment-1686439630
- Bugfix

fix: do not fire change event if the value has not changed

---

dev/icon.html
packages/icon/src/vaadin-icon.d.ts
packages/icon/src/vaadin-icon.js
packages/icon/test/icon-font.test.js
packages/icon/test/test-icon-font.js
packages/icon/test/typings/icon.types.ts
packages/icon/test/visual/icon.common.js

Adds `font` property to `<vaadin-icon>`. The property can be used to assign `<vaadin-icon>` class names that icon libraries typically ship with their font icons.
The following HTML page can be used to try out the feature with some popular icon libraries:
```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Icon</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">   
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
<link …
```

feat: add font property to icon

---

dev/cookie-consent.html
packages/cookie-consent/src/vaadin-cookie-consent.js
packages/cookie-consent/test/cookie-consent.test.js

Override the `messagelink` ("message with link") html in cookie consent configuration to remove the role attribute from the learn more link
Fixes #6308

fix: remove button role from link in Cookie Consent

---

packages/integer-field/test/integer-field.test.js
packages/number-field/src/vaadin-number-field-mixin.js
packages/number-field/test/number-field.common.js

The PR prevents default browser behavior for wheel events on the number-field's input element when it's focused. More precisely, this prevents the browser from attempting to increment or decrement the value when the mouse wheel is used within the input element.
> **Warning**
> This is a behavior altering change. 
> **Warning**
>  The change also prevents page scrolling when the pointer is positioned over the field and the field is focused. This issue will be resolved when switching the number field from `[type=number]` to `[type=text]` ([ticket](https://github.com/vaadin/web-components/issues/3102)).
Fixes #6158, https://github.com/vaadin/web-components/issues/919

fix!: prevent default for wheel events on focused input element

---

packages/select/src/vaadin-lit-select.js
packages/select/src/vaadin-select.js
packages/select/test/select.common.js

This ensures that the sr-only element is always placed inside the select element
Fixes #6300

fix: set vaadin-select position to relative

---

packages/icon/src/vaadin-icon.js
packages/icon/test/icon-font.test.js

The container queries fallback mechanism in `<vaadin-icon>` only needs to be used with font icons. In the case of working with SVG icons, it doesn't need to do anything.
This PR changes the logic so that the heavy lifting of the fallback mechanism is only active when font icons are used (either `font` or `char` property is set).
Part of https://github.com/vaadin/web-components/issues/6212
- Bugfix (performance)

fix: only use container queries fallback with font icons

---

packages/time-picker/src/vaadin-time-picker.js
packages/time-picker/test/keyboard-navigation.test.js
packages/time-picker/test/time-picker.test.js

The PR updates `time-picker` to reject steps that the custom formatter cannot represent. When setting such a step, the component now displays a warning and restores the previous step.
> **Warning**
> It's a behavior altering change, as keyboard stepping no longer works for such steps.
Fixes https://github.com/vaadin/web-components/issues/6397

refactor!: reject steps incompatible with formatter, show a warning

---

packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js
packages/grid/test/keyboard-navigation.test.js

When focusing on the grid by clicking on the horizontal scroll or tabbing between the focusable elements of the grid, it always scrolls back to the start of the grid. 
This PR updates the focus target prediction logic in order to prevent scrolling to the start of the row. If the target focusable is tied to a column that is not visible:
- find the first visible column
- update the target based on the type of the focusable (header, body, or footer)
Fixes #6405

fix: do not scroll to the first column on focus

---

packages/time-picker/src/vaadin-time-picker.js
packages/time-picker/test/events.test.js

The PR fixes the regression where `time-picker` didn't fire a `change` event when its value changed to an empty string due to a bad input commit attempt.
Fixes #6417

fix: fire change event when value changes to empty string due to bad input

---

packages/time-picker/src/vaadin-time-picker.js
packages/time-picker/test/events.test.js

The PR fixes the regression introduced in https://github.com/vaadin/web-components/pull/6408 which caused the change event not to be fired when `step` >= 1.

fix: fire change event on arrow keys when step >= 1

---

packages/time-picker/src/vaadin-time-picker.js
packages/time-picker/test/validation.test.js

The PR ensures `time-picker` validates when pressing <kbd>ArrowUp</kbd> / <kbd>ArrowDown</kbd> to increase / decrease the time. Validation is expected because there is a change event in that case.

fix: validate on arrow keys when field has step

---

packages/a11y-base/src/aria-hidden.js
packages/a11y-base/test/aria-hidden.test.js

Fixes #6410
This PR changes the logic to unwrap shadow host recursively until we get an element contained in `<body>`.
Original library only unwraps it once - see https://github.com/theKashey/aria-hidden/commit/3dd2b665330362366a6712553097aec564398400 for the implementation.
UPD: the second commit in the PR changes the above behavior to consider elements in shadow root.
This is done in order to allow `aria-hidden` to be set on the shadow root target's sibling elements.
- Bugfix

fix: correctly handle aria-hidden with nested shadow roots

---

packages/time-picker/src/vaadin-time-picker.js
packages/time-picker/test/keyboard-navigation.test.js
packages/time-picker/test/time-picker.test.js

The PR reverts #6408 because the heuristic that was used there to detect incompatible steps isn't 100% reliable. For example, the parser can return `0` as milliseconds even though the formatter doesn't display them.
Related to https://github.com/vaadin/web-components/issues/6397

revert: "refactor!: reject steps incompatible with formatter" (#6408)

---

packages/time-picker/src/vaadin-time-picker.js
packages/time-picker/test/validation.test.js

The PR ensures that there is only one `value-changed` when adjusting the value with arrow keys. 
Previously, several value changes could take place when `step` >= 1 sec. With such steps, the `__onArrowPressWithStep` method updated the value property always appending `.000` to the end whereas the following `__comboBoxValueChanged` always removed that part, which resulted in two value changes.

fix: ensure only one value change on arrow key press

---

packages/rich-text-editor/src/vaadin-rich-text-editor.js
packages/rich-text-editor/test/basic.test.js

Fixes: https://github.com/vaadin/web-components/issues/6435

fix: Remove empty spans used by Quill internally from htmlValue

---

packages/rich-text-editor/src/vaadin-rich-text-editor.js
packages/rich-text-editor/test/basic.test.js

Cherry-pick of #6434 to `23.3` branch. There was a merge conflict due to `u` flag in the RegExp on main branch.
- Cherry-pick

fix: remove empty spans used by Quill from htmlValue (#6434) (CP: 23.3)

---

packages/login/src/vaadin-lit-login-form.js
packages/login/src/vaadin-login-form-mixin.js
packages/login/src/vaadin-login-form.js
packages/login/src/vaadin-login-overlay.d.ts
packages/login/test/login-submit.common.js
packages/login/test/typings/login.types.ts

Depends on #6403
This PR adds the following improvements to `vaadin-login-form`:
1. Store custom fields and collect values from them on `submit()` call,
2. Add `custom` object to the `login` event detail with these values,
3. Append custom fields values with the `<form>` using [`formdata`](https://web.dev/more-capable-form-controls/#event-based-api).
- Feature

feat: submit custom login fields values as part of the form

---

packages/icon/src/vaadin-icon-font-size-mixin.d.ts
packages/icon/src/vaadin-icon-font-size-mixin.js
packages/icon/src/vaadin-icon.d.ts
packages/icon/src/vaadin-icon.js

This PR moves all logic related to the `<vaadin-icon>`'s Container Queries [fallback](https://github.com/vaadin/web-components/blob/main/packages/icon/src/vaadin-icon.js#L391-L393) to a separate mixin.
Once Safari 15 is no longer on the list of supported browsers (all supported browsers have CSS CQ), everything related to the fallback can be cleaned up by removing the mixin.
Refactor

refactor: move font icon size fallback to a mixin

---

packages/time-picker/test/events.test.js
packages/time-picker/test/time-picker.test.js
packages/time-picker/test/validation.test.js
packages/time-picker/test/value-commit.test.js

The idea is to create a test file that would collect all the tests related to the user committing a value. Currently, such tests are scattered across different places, making it difficult to know what might cause the value to change and feel confident about the test coverage when refactoring something.
The new tests aim to cover all main scenarios where the user commits a value using actions like blur, outside click, Enter or Escape.
Part of https://github.com/vaadin/web-components/issues/6426
```
value-commit.test.js
│
├── default
├── parsable input entered
├── parsable input committed
│   └── input cleared with Backspace
├── unparsable input entered
├── unparsable input commited
│   └── input cleared with Backspace
├── value set programmatically
│   ├── default
│   ├── parsable input …
```

test: improve test coverage for value commit scenarios

---

integration/package.json
integration/tests/confirm-dialog-fields.test.js
packages/confirm-dialog/src/vaadin-confirm-dialog.js

Fixes https://github.com/vaadin/flow-components/issues/5412
This PR changes the order of `appendChild()` calls to ensure `ready()` is called as expected.
The actual issue is related to how `vaadin-confirm-dialog` moves elements added to it:
1. The `<vaadin-checkbox>` element is added to the dialog,
2. The element is then [wrapped](https://github.com/vaadin/web-components/blob/57c1bd640dd037db9188cfdb1c04856df64addb1/packages/confirm-dialog/src/vaadin-confirm-dialog.js#L362) with the `<div>` element,
3. On open, the element is then [teleported](https://github.com/vaadin/web-components/blob/57c1bd640dd037db9188cfdb1c04856df64addb1/packages/confirm-dialog/src/vaadin-confirm-dialog.js#L412) to the overlay.
I don't think we can easily change the confirm-dialog logic, so I came up with a …

fix: wrap nodes correctly to ensure proper initialization

---

packages/side-nav/src/vaadin-side-nav-item.d.ts
packages/side-nav/src/vaadin-side-nav-item.js
packages/side-nav/src/vaadin-side-nav.d.ts
packages/side-nav/src/vaadin-side-nav.js
packages/side-nav/test/typings/side-nav.types.ts

The `SideNav` component being built on `LitElement` is a technical detail. Currently, it [exposes API from `LitElement`](https://cdn.vaadin.com/vaadin-web-components/24.2.0-alpha11/#/elements/vaadin-side-nav#methods) which is not desired.
This PR changes the parent type of `SideNav` and `SideNavItem` to `HTMLElement`, which aligns them with other Vaadin web components.

fix: do not expose LitElement API from SideNav

---

packages/grid/src/vaadin-grid-dynamic-columns-mixin.js
packages/grid/test/lit.test.js

Fixes #6112
Added a check to ensure `cell` is not `undefined` which can happen when removing a column.
- Bugfix
Without the fix, the newly added test fails due to `TypeError` - this isn't ideal but does the job:
```
packages/grid/test/lit.test.js:
TypeError: Cannot read properties of undefined (reading '_content')
at packages/grid/src/vaadin-grid-dynamic-columns-mixin.js:115:51
at Array.filter (<anonymous>)
at filterNotConnected (packages/grid/src/vaadin-grid-dynamic-columns-mixin.js:115:29)
at Array.filter (<anonymous>)
at Grid.<anonymous> (packages/grid/src/vaadin-grid-dynamic-columns-mixin.js:117:46)
at FlattenedNodesObserver.flush (node_modules/@polymer/polymer/lib/utils/flattened-nodes-observer.js:281:21)
at FlattenedNodesObserver._processMutations …
```

fix: do not throw when removing sort column after sorting

---

packages/date-picker/test/value-commit-lit.test.js
packages/date-picker/test/value-commit-polymer.test.js

Use themed `<vaadin-date-picker>` in the value-commit tests. This fixes the current test failures in `main` branch.
Tests

test: use themed date picker in the tests

---

packages/icon/src/vaadin-icon.js
packages/icon/test/icon-font.test.js

It appears that if your font family name contains spaces and numbers (for example "Font Awesome 6 Free"), `element.style.fontFamily = fontFamily` does nothing. See https://stackoverflow.com/questions/8951584/assigning-a-css-fontfamily-ending-with-a-number. This PR fixes the issue by wrapping the font family name in single quotes.
Bugfix

fix: wrap icon font family in quotes

---

packages/context-menu/src/vaadin-context-menu.d.ts
packages/context-menu/src/vaadin-context-menu.js
packages/context-menu/src/vaadin-contextmenu-items-mixin.d.ts
packages/context-menu/src/vaadin-contextmenu-items-mixin.js
packages/context-menu/test/items.test.js
packages/menu-bar/src/vaadin-menu-bar-mixin.js

Fixes https://github.com/vaadin/web-components/issues/1005
The contribution provides a way to keep menu opened on item selection by introducing `keepOpen` property.
On item selection with `keepOpen` property will not be closed and the items will be updated (via `requestContentUpdate`)

feat: keep menu bar open on item selection

---

dev/icon.html
packages/icon/src/vaadin-icon-font-size-mixin.js
packages/icon/src/vaadin-icon.d.ts
packages/icon/src/vaadin-icon.js
packages/icon/test/icon-font.test.js
packages/icon/test/typings/icon.types.ts
packages/icon/test/visual/icon.common.js

As a follow-up of the `<vaadin-icon>` font icon support DX test results, we decided to split the `icon.char`, which currently accepts either a code point or a ligature, into separate `char` and `ligature` properties.
Since `char` can no longer be a ligature name, the updated `char` property now also supports unprefixed code points (like "ea0e").
Before:
```html
<vaadin-icon font-family="lumo-icons" char="&#xea0e;"></vaadin-icon>
<vaadin-icon font-family="Material Icons" char="face"></vaadin-icon>
```
After:
```html
<vaadin-icon font-family="lumo-icons" char="ea0e"></vaadin-icon>
<vaadin-icon font-family="Material Icons" ligature="face"></vaadin-icon>
```
Feature

feat: split char into ligature and char

---

packages/component-base/src/polylit-mixin.js
packages/component-base/test/polylit-mixin.test.js

Handle synchronous read-only properties in polylit-mixin
Bugfix

fix: handle synchronous read-only properties in polylit-mixin

---

packages/component-base/src/polylit-mixin.js
packages/component-base/test/polylit-mixin.test.js

This is a finding from the `vaadin-context-menu` Lit conversion research.
- Bugfix

fix: allow to set default value for readOnly property

---

packages/login/src/vaadin-lit-login-form-wrapper.js
packages/login/src/vaadin-lit-login-overlay.js
packages/login/src/vaadin-login-form-mixin.js
packages/login/src/vaadin-login-form-wrapper.js
packages/login/src/vaadin-login-overlay-mixin.js
packages/login/src/vaadin-login-overlay.js
packages/login/test/dom/__snapshots__/login-form.test.snap.js
packages/login/test/login-overlay.common.js
packages/login/test/login-submit.common.js
packages/login/test/visual/lumo/login-overlay.test.js
packages/login/test/visual/material/login-overlay.test.js

As discussed internally, we are going to use `getCustomFormArea()` for Java API, so let's align the slot name with it.
- Refactor

refactor!: rename overlay custom-fields slot to custom-form-area

---

packages/icon/src/vaadin-icon-font-size-mixin.js
packages/icon/src/vaadin-icon.d.ts
packages/icon/src/vaadin-icon.js
packages/icon/test/icon-font.test.js
packages/icon/test/typings/icon.types.ts
packages/icon/test/visual/icon.common.js

As a follow-up of the `<vaadin-icon>` font icon support DX test results, we decided to rename the `icon.font` as `icon.iconClass`
Before:
```html
<vaadin-icon font="fa-solid fa-user"></vaadin-icon>
```
After:
```html
<vaadin-icon icon-class="fa-solid fa-user"></vaadin-icon>
```
Refactor

refactor: rename icon.font to icon.iconClass

---

packages/icon/src/vaadin-icon.js

Popular icon collections, like Font Awesome and Material Icons, apply [font-smoothing](https://github.com/FortAwesome/Font-Awesome/blob/6.x/css/all.css#L19-L20) to font icons when used with the built-in class names.
If you use font icons with `fontFamily` and `char`, font-smoothing CSS does not get applied to the icons automatically. This PR adds default styles to ensure consistent font smoothing for all icons.

chore: add default icon font smoothing

---

packages/component-base/src/tooltip-controller.js
packages/component-base/test/tooltip-controller.test.js

In some cases, we might want to handle `vaadin-tooltip` node lazily (e.g. `vaadin-checkbox` inside of `vaadin-checkbox-group`). Currently there is no API for that. This PR adds the `tooltip-changed` event on the `TooltipController`.
- Internal feature.

feat: dispatch an event when tooltip is added or removed

---

integration/tests/checkbox-group-tooltip.test.js
packages/checkbox-group/src/vaadin-checkbox-group.js

Part of #6286
Here are the outcomes of testing in screen readers.
https://github.com/vaadin/web-components/assets/10589913/4148e3fd-b039-42bf-91b7-e390ff1e9636

fix!: link every checkbox in a group with the tooltip overlay

---

packages/number-field/src/vaadin-number-field-mixin.js
packages/number-field/test/validation.common.js

The PR ensures `number-field` runs validation when the value change is triggered by <kbd>ArrowUp</kbd> or <kbd>ArrowDown</kbd>.
Fixes #6430

fix: validate on value change triggered by arrow key

---

packages/number-field/src/vaadin-number-field.js
packages/number-field/test/validation.test.js

A cherry-pick of #6476 to `23.3`.
Fixes https://github.com/vaadin/web-components/issues/6430

fix: validate on value change triggered by arrow key (#6476) (CP: 23.3)

---

packages/icon/src/vaadin-icon.d.ts
packages/icon/src/vaadin-icon.js
packages/icon/test/icon.test.js

The new `symbol` property enables passing the symbol identifier separated from the src value, which enables defining icons based on sprites that are not only restricted to format `/path/to/file.svg#symbol-id`, but also if the src is defined as a data object (`data:image/svg+xml...`).

feat: add symbol property to icon

---

packages/a11y-base/test/focus-utils.test.js
packages/board/test/redraw.test.js
packages/combo-box/test/dirty-state.test.js
packages/combo-box/test/lit.test.js
packages/component-base/test/slot-controller.test.js
packages/custom-field/test/custom-field.common.js
packages/date-picker/test/dirty-state.test.js
packages/date-time-picker/test/dirty-state.test.js
packages/field-base/test/checked-mixin.test.js
packages/field-base/test/field-mixin.test.js
packages/grid/test/column-groups.test.js
packages/grid/test/column-rendering.test.js
packages/grid/test/hidden-grid.test.js
packages/grid/test/light-dom-observing.test.js
packages/icon/test/icon-font.test.js
packages/menu-bar/test/a11y.test.js
packages/multi-select-combo-box/test/dirty-state.test.js
packages/multi-select-combo-box/test/selecting-items.test.js
packages/select/test/accessibility.common.js
packages/select/test/dirty-state.common.js
packages/select/test/select.common.js
packages/side-nav/test/side-nav-item.test.js
packages/tabs/test/scroll.test.js
packages/time-picker/test/dirty-state.test.js
packages/time-picker/test/events.test.js
packages/time-picker/test/time-picker.test.js
packages/tooltip/test/tooltip-timers.test.js

Fixed errors for `require-await` rule which is enabled in the latest version of `eslint-config-vaadin`.

chore: fix ESLint errors for require-await rule in tests

---

integration/tests/component-tooltip.test.js
packages/checkbox/src/vaadin-checkbox.js
packages/checkbox/src/vaadin-lit-checkbox.js

Follow-up to #6321
The `vaadin-checkbox` component also uses `<input>` element, so `aria-describedby` should be set on it.
- Bugfix

fix: set correct ariaTarget for the checkbox tooltip

---

packages/checkbox/test/checkbox.common.js
packages/field-base/src/input-mixin.js
packages/number-field/test/validation.common.js
packages/number-field/test/value-commit-lit.test.js
packages/number-field/test/value-commit-polymer.test.js
packages/number-field/test/value-commit.common.js

The PR ensures that the Lit version of `number-field` dispatches events in the same sequences as the Polymer version when committing a value:
1. `value-changed`
2. `validated`
3. `change`
Follow-up to https://github.com/vaadin/web-components/pull/6429

fix: ensure correct event sequence on value commit in Lit version

---

packages/cookie-consent/src/vaadin-cookie-consent.js
packages/cookie-consent/test/cookie-consent.test.js

fix: remove hardcoded aria-labels from the `learn more` and `dismiss` links

---

packages/cookie-consent/src/vaadin-cookie-consent.js
packages/cookie-consent/test/cookie-consent.test.js

fix: remove hardcoded aria-label attributes from links (#6492) (CP: 24.1)

---

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.d.ts
packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js

Follow-up to #6495. 
Added missing `@fires` annotation for `opened-changed` and also for `dirty-changed` events.

docs: add missing fires JSDoc annotations for events

---

packages/rich-text-editor/src/vaadin-rich-text-editor.js
packages/rich-text-editor/test/basic.test.js

Quill uses `eventemitter3` internally which has a `removeAllListeners()` method, however, there are still some listeners present in the Quill's `Emitter` class that needs to be cleaned up.
Fixes #6480

fix: clean up listeners in quill editor when the rich-text-editor is detached

---

integration/tests/checkbox-group-tooltip.test.js
integration/tests/radio-group-tooltip.test.js
packages/tooltip/src/vaadin-tooltip.d.ts
packages/tooltip/src/vaadin-tooltip.js
packages/tooltip/test/dom/__snapshots__/tooltip.test.snap.js
packages/tooltip/test/dom/tooltip.test.js
packages/tooltip/test/tooltip.test.js

Fixes #6380
Updated `vaadin-tooltip` to create a nested hidden element instead of using the `vaadin-tooltip-overlay` for screen reader announcement. This ensures the target and its accessible label element are in the same DOM scope.
The new element is implicitly hidden due to the fact that `vaadin-tooltip` uses `display: none` but it [still works](https://www.tpgi.com/short-note-on-aria-labelledby-and-aria-describedby/):
> It is important to note that by design, hiding the content (using CSS display:none or visibility:hidden or the HTML [hidden attribute](https://www.w3.org/TR/html51/editing.html#the-hidden-attribute)) of the element(s) referenced by these attributes does not stop the content from being used to provide the name/description.

refactor!: use separate element for tooltip announcements

---

packages/rich-text-editor/src/vaadin-rich-text-editor.js
packages/rich-text-editor/test/basic.test.js

This reverts commit 58d48e469204f7aa2d20d8d01ec49ec428249145.
The PR turned out to cause issue in the Flow counterpart so we need to revert it until we find a better fix.
- Revert

Revert "fix: clean up Quill listeners on detach and re-create on reattach (#6489)"

---

packages/rich-text-editor/src/vaadin-rich-text-editor.js
packages/rich-text-editor/test/basic.test.js

This reverts commit 35f641d5860fdccbfbbf57fb1f9de60dac22a391.
Same as #6502 but for `24.1` branch.
- Revert

Revert "fix: clean up Quill listeners on detach and re-create on reattach (#6489) (#6497)"

---

packages/rich-text-editor/src/vaadin-rich-text-editor.js
packages/rich-text-editor/test/basic.test.js

This reverts commit 4dd6ee5ca5baa6123f2a96a723e58581a9f0b2cb.
Same as #6502 but for `23.3` branch.
- Revert

Revert "fix: clean up listeners in quill editor when the rich-text-editor is detached (#6489) (#6498)"

---

packages/icon/src/vaadin-icon.js
packages/icon/test/icon.test.js

This PR updates `<vaadin-icon>` to cache the fetch to a URL provided as `src`. This is to prevent making multiple requests to the same URL unnecessarily.
Before:
After:
Refactor

refactor: cache icon src fetch results

---

packages/rich-text-editor/src/vaadin-rich-text-editor.js
packages/rich-text-editor/test/basic.test.js

Fixes https://github.com/vaadin/web-components/issues/6480
Same as #6489 but with a fix to flush the value debouncer in `disconnectedCallback()`.
- Bugfix

fix: re-initialize Quill on detach and re-attach and keep htmlValue

---

packages/rich-text-editor/src/vaadin-rich-text-editor.js

Fixes #6369
Added a workaround from https://github.com/quilljs/quill/issues/2096#issuecomment-399576957
No tests as the issue can be only tested manually 😕 
- Bugfix

fix: workaround disappearing text on spellcheck suggestion

---

integration/tests/define.test.js
packages/component-base/src/define.js

Log a warning when components are loaded twice and an error if different versions of the component is loaded
Fixes #6508

refactor: prevent duplicate custom element definition errors

---

packages/component-base/src/data-provider-controller/cache.js
packages/component-base/src/data-provider-controller/data-provider-controller.js
packages/component-base/src/data-provider-controller/helpers.js
packages/grid/src/vaadin-grid-data-provider-mixin.d.ts
packages/grid/src/vaadin-grid-data-provider-mixin.js
packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js
packages/grid/src/vaadin-grid-mixin.js
packages/grid/test/column.test.js
packages/grid/test/data-provider.test.js
packages/grid/test/filtering.test.js
packages/grid/test/resizing.test.js
packages/grid/test/row-details.test.js
packages/grid/test/selection.test.js
packages/polymer-legacy-adapter/test/grid-body.test.js
packages/polymer-legacy-adapter/test/grid-row-details.test.js

The PR extracts the grid data provider functionality into a controller in order to separate concerns, thereby reducing cognitive load, making testing easier, and potentially allowing reusing it in other components such as `combo-box`. In the future, the controller can provide some additional methods or events to be used on the Flow connector side without having to make them public web component API.
**TODO:**

refactor: extract grid data provider functionality into a controller

---

packages/tooltip/test/tooltip-offset.test.js
packages/tooltip/test/tooltip-position.test.js

This PR updates some (not all) the `vaadin-tooltip` unit tests to add missing `await`.
I'm going to cover more tests in following PRs as part of `LitElement` conversion preparation.
- Tests

test: update tooltip unit tests, add missing await

---

packages/button/src/vaadin-button-mixin.js
packages/button/test/button.test.js

Cherry-pick of https://github.com/vaadin/web-components/pull/6404.
Related BFPs specified used version as 23.1.

fix: do not click on Enter and Space when using key modifiers (CP: #6404)

---

packages/tooltip/src/vaadin-tooltip-overlay-styles.d.ts
packages/tooltip/src/vaadin-tooltip-overlay-styles.js
packages/tooltip/src/vaadin-tooltip-overlay.js

Extracted CSS used by `vaadin-tooltip-overlay` to separate file in preparation for adding LitElement version.
- Refactor

refactor: extract tooltip overlay styles to reusable css literal

---

wtr-utils.js

Configure Mocha to retry failed tests 2 more times by using the `retries` setting in the web-test-runner configuration object.
Not closing https://github.com/vaadin/components-team-tasks/issues/613 because we may want to use the rerun option in GitHub actions if this change is not enough.
Part of https://github.com/vaadin/components-team-tasks/issues/613

chore: config tests to retry on failure

---

packages/text-field/src/vaadin-text-field-mixin.d.ts

Changed `TexFieldMixinClass` to `TextFieldMixinClass` (missing `t` letter added).
As nobody noticed this since Vaadin 22, I hope this change is small enough to land in a minor 🙈 
- Bugfix

fix: fix typo in TextFieldMixinClass class name type definition

---

packages/context-menu/src/vaadin-contextmenu-items-mixin.js

This is a finding from `vaadin-context-menu` Lit conversion. 
Using `ready()` means adding the listener after initial render which breaks some tests due to timings change.
Also, it's a general practie to initialize event listeners in the `constructor()` so let's follow it here.
- Refactor

refactor: move items-outside-click listener to the constructor

---

packages/grid/src/vaadin-grid-sorter-mixin.d.ts
packages/grid/src/vaadin-grid-sorter-mixin.js
packages/grid/src/vaadin-grid-sorter.d.ts
packages/grid/src/vaadin-grid-sorter.js

Extracted grid sorter mixin to be used by the LitElement version to be added later
Refactor

refactor: extract vaadin-grid-sorter logic into a reusable mixin

---

packages/context-menu/src/vaadin-context-menu.js
packages/context-menu/src/vaadin-contextmenu-items-mixin.js

This change is needed in preparation for `vaadin-context-menu` Lit conversion.
There will be separate Lit based versions of item and list-box elements, and they shouldn't be imported by the mixin.
- Refactor

refactor: move item and list-box imports to the context-menu

---

packages/combo-box/test/lazy-loading.test.js

Try to stabilize a test that randomly fails on Firefox (CI + locally)

test: add timeout to stabilize a flaky combo-box test

---

packages/checkbox/src/vaadin-checkbox-styles.js

In iOS Safari, the user agent styles define width and height to the input of type checkbox which makes it not take the whole size of the visual checkbox area. In this case, it becomes hard to touch on the checkbox because the misalignment.
Fixes https://github.com/vaadin/flow-components/issues/5190

fix: unset input width/height to avoid issue with UA styles

---

packages/grid/src/vaadin-grid-filter-element-mixin.d.ts
packages/grid/src/vaadin-grid-filter-element-mixin.js
packages/grid/src/vaadin-grid-filter.d.ts
packages/grid/src/vaadin-grid-filter.js

Extracted grid filter element mixin to be used by the LitElement version to be added later.
The new mixin file is named `vaadin-grid-filter-element-mixin.js` because `vaadin-grid-filter-mixin.js` already exists.
Refactor

refactor: extract vaadin-grid-filter logic into a reusable mixin

---

packages/component-base/src/data-provider-controller/cache.d.ts
packages/component-base/src/data-provider-controller/cache.js
packages/component-base/src/data-provider-controller/data-provider-controller.js
packages/component-base/test/typings/data-provider-controller/cache.types.ts
packages/grid/src/vaadin-grid-data-provider-mixin.js
packages/grid/test/deprecated-api.test.js

The PR restores and deprecates the old grid cache API after it's been removed in #5961.

refactor: restore and deprecate old grid cache API

---

packages/component-base/src/data-provider-controller/cache.d.ts
packages/component-base/src/data-provider-controller/cache.js
packages/component-base/src/data-provider-controller/data-provider-controller.d.ts
packages/component-base/src/data-provider-controller/data-provider-controller.js
packages/component-base/src/data-provider-controller/helpers.js
packages/component-base/test/typings/data-provider-controller/cache.types.ts
packages/component-base/test/typings/data-provider-controller/data-provider-controller.types.ts
packages/crud/src/vaadin-crud.js
packages/grid/src/vaadin-grid-array-data-provider-mixin.js
packages/grid/src/vaadin-grid-data-provider-mixin.js
packages/grid/src/vaadin-grid-drag-and-drop-mixin.js
packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js
packages/grid/src/vaadin-grid-mixin.js
packages/grid/src/vaadin-grid-scroll-mixin.js
packages/grid/test/data-provider.common.js
packages/grid/test/deprecated-api.test.js

The PR deprecates `effectiveSize` and introduces `flatSize` as a replacement in Grid and DataProviderController.
Follow-up to #5961

refactor: deprecate effectiveSize in favor of flatSize

---

packages/rich-text-editor/src/vaadin-rich-text-editor-styles.js
packages/rich-text-editor/src/vaadin-rich-text-editor.js

While most of `vaadin-rich-text-editor` styles already use `css` literals, there is still a `<style>` tag in the template.
This PR makes it aligned to use `css` literal consistently in preparation for LitElement based version.
- Refactor

refactor: extract rich-text-editor styles to css literal

---

packages/input-container/src/vaadin-input-container-mixin.js
packages/input-container/src/vaadin-input-container.js

In order to get some components 100% Lit based, we need to create `vaadin-input-container` version using Lit.
This PR extracts logic into reusable mixin. There will be other PR for styles.
- Refactor

refactor: extract input-container logic into reusable mixin

---

packages/date-picker/src/vaadin-lit-date-picker.js
packages/number-field/src/vaadin-lit-number-field.js
packages/select/src/vaadin-lit-select.js
packages/text-area/src/vaadin-lit-text-area.js
packages/text-field/src/vaadin-lit-text-field.js

Follow-up to #6576
Updated LitElement based versions of field components to use Lit version of `vaadin-input-container`.
- Refactor

refactor: update Lit versions to use new input-container

---

packages/component-base/src/virtualizer-iron-list-adapter.js
packages/component-base/test/virtualizer-item-height.test.js

Make the virtualizer retry scrolling to an index on the next round of element updates in case there are placeholder items in the DOM after scrollToIndex.
This change is a prerequisite to finishing https://github.com/vaadin/flow-components/pull/5037 without having to work around the issue in the connector.
Bugfix

fix: make virtualizer with placeholders retry scroll to index

---

dev/grid.html
packages/grid/src/vaadin-grid-selection-column.d.ts
packages/grid/src/vaadin-grid-selection-column.js
packages/grid/test/helpers.js
packages/grid/test/selection.test.js

Cherry-pick of https://github.com/vaadin/web-components/pull/6243 to 23.3

feat: add drag selection to grid (CP: #6243)

---

packages/grid/src/vaadin-grid-tree-toggle-mixin.d.ts
packages/grid/src/vaadin-grid-tree-toggle-mixin.js
packages/grid/src/vaadin-grid-tree-toggle.d.ts
packages/grid/src/vaadin-grid-tree-toggle.js

Extracted grid tree toggle logic to a mixin to be used by the LitElement version to be added later.
Refactor

refactor: extract grid tree toggle logic to a separate mixin

---

packages/field-base/src/input-controller.js
packages/field-base/test/input-controller.test.js

Fixes #6224
Fixes #6598
This PR fixes an issue in Safari with `change` event not getting fired for clearing initial value set with attribute.
See https://github.com/vaadin/web-components/issues/6224#issuecomment-1649665757 for the HTML snippet that I used to reproduce and debug this issue.
- Bugfix

fix: set initial value using property to ensure change is fired

---

packages/grid/src/vaadin-grid-filter-column-mixin.d.ts
packages/grid/src/vaadin-grid-filter-column-mixin.js
packages/grid/src/vaadin-grid-filter-column.d.ts
packages/grid/src/vaadin-grid-filter-column.js
packages/grid/src/vaadin-grid-selection-column-mixin.d.ts
packages/grid/src/vaadin-grid-selection-column-mixin.js
packages/grid/src/vaadin-grid-selection-column.d.ts
packages/grid/src/vaadin-grid-selection-column.js
packages/grid/src/vaadin-grid-sort-column-mixin.d.ts
packages/grid/src/vaadin-grid-sort-column-mixin.js
packages/grid/src/vaadin-grid-sort-column.d.ts
packages/grid/src/vaadin-grid-sort-column.js
packages/grid/src/vaadin-grid-tree-column-mixin.d.ts
packages/grid/src/vaadin-grid-tree-column.d.ts

Extracted the logic of the rest of the grid utility columns to mixins to be used by the LitElement version to be added later.
Refactor

refactor: extract grid utility columns logic to separate mixins

---

packages/accordion/src/vaadin-accordion-heading-styles.d.ts
packages/accordion/src/vaadin-accordion-heading-styles.js
packages/accordion/src/vaadin-accordion-heading.js
packages/accordion/src/vaadin-accordion-panel-styles.d.ts
packages/accordion/src/vaadin-accordion-panel-styles.js
packages/accordion/src/vaadin-accordion-panel.js

Extracted CSS to reusable tagged literals for using by the LitElement version of `vaadin-accordion`.
- Refactor

refactor: extract panel and heading styles to css literals

---

packages/grid/src/vaadin-grid-data-provider-mixin.js
packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js
packages/grid/test/keyboard-navigation.common.js

This change makes the grid wait for the `loading` state to finish before dispatching a "cell-focus" event. This is needed to make sure the event context includes up-to-date item data when dealing with lazily loading data providers.
Fixes https://github.com/vaadin/flow-components/issues/5528
Bugfix

fix: defer grid cell-focus event with lazy data provider

---

packages/grid/src/vaadin-grid-data-provider-mixin.js
packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js
packages/grid/test/keyboard-navigation.test.js

Manual cherry-pick of #6618 to `24.2`

fix: defer grid cell-focus event with lazy data provider (#6618)

---

packages/context-menu/src/vaadin-context-menu.d.ts
packages/context-menu/src/vaadin-context-menu.js
packages/context-menu/src/vaadin-contextmenu-items-mixin.d.ts
packages/context-menu/src/vaadin-contextmenu-items-mixin.js
packages/context-menu/test/dom/__snapshots__/context-menu.test.snap.js
packages/context-menu/test/dom/context-menu.test.js

Introduces a `className` property that can be used for adding CSS classes to context menu items via the `items` array.
Fixes https://github.com/vaadin/web-components/issues/5341

feat: add a className property for adding CSS classes to items

---

packages/message-list/test/typings/message-list.types.ts

We missed to add typings tests to the `message-list` package. This PR fixes that.
- Tests

test: add missing typings tests for message and message-list

---

packages/select/src/vaadin-select.d.ts
packages/select/src/vaadin-select.js

> ⚠️  This PR is targeting `23.3` branch.
We got a request to override `keydown` listener in `vaadin-select` to not open on <kbd>Enter</kbd>.
Currently, it isn't possible because of the fact that corresponding event listener uses `.bind(this)`
This PR updates the component to use `KeyboardMixin` instead, as we generally do in other components.
It's already done in Vaadin 24 as part of the bigger `vaadin-select-value-button` refactoring in https://github.com/vaadin/web-components/pull/5215
See the internal Slack discussion: https://vaadin.slack.com/archives/C3TGRP4HY/p1696848138596359
- Refactor

refactor: use KeyboardMixin to handle select keydown events

---

packages/grid/src/vaadin-grid-column-mixin.d.ts
packages/grid/src/vaadin-grid-column-mixin.js
packages/grid/test/styling.common.js
packages/grid/test/typings/grid.types.ts

Add `headerPartName` and  `footerPartName` properties to `ColumnBaseMixinClass`.
Part of https://github.com/vaadin/web-components/issues/1434
Feature

feat: grid column header and footer part names

---

packages/message-list/src/vaadin-message-list.d.ts
packages/message-list/src/vaadin-message-list.js
packages/message-list/test/dom/__snapshots__/message-list.test.snap.js
packages/message-list/test/dom/message-list.test.js
packages/message-list/test/typings/message-list.types.ts

Fixes #5335
Same as #6617 but for `vaadin-message-list`.
Note: typing test to be added once #6627 is merged.
- Feature

feat: add className property for adding CSS classes to messages

---

packages/login/src/vaadin-lit-login-overlay-wrapper.js

The issue was found when bumping `lit` to 3.0, see #6630 
- Bugfix

fix: use correct hidden attribute syntax in Lit version

---

packages/context-menu/src/vaadin-contextmenu-items-mixin.js

Backported the change that was included in #6241 together with adding `keepOpen` (24.2) to the `24.1` branch.
- UX improvement / bugfix
https://github.com/vaadin/web-components/assets/10589913/71ae0130-11e4-498d-bdb7-9e273707c59a
https://github.com/vaadin/web-components/assets/10589913/b1a3a980-4a79-4975-af32-3b5db9cf25e7

fix: prevent selected item checkmark icon from flashing (24.1)

---

packages/time-picker/src/vaadin-time-picker.d.ts
packages/time-picker/src/vaadin-time-picker.js
packages/time-picker/test/value-commit.test.js

The PR introduces a new event `unparsable-change` to `time-picker`. This event is fired when the user attempts to commit or clear input that the component has failed to parse as a time. This event is intended as a supplement to the change event, which means it will be fired only when there is no change event.
Here is a table that illustrates which event is fired based on the nature of the value change:
| Value change                | Event             | Note
|:-----------------------|:------------------|:-------|
| empty => parsable      | change            | |
| empty => unparsable    | unparsable-change | |
| parsable => empty      | change            | |
| parsable => parsable   | change            | |
| parsable => unparsable | change            | The value property changes to an …

feat(time-picker): add unparsable-change event

---

packages/combo-box/src/vaadin-combo-box-item-mixin.js
packages/combo-box/test/item-renderer.test.js

Fixes https://github.com/vaadin/flow-components/issues/1304
When the Virtualizer's size gets reduced to a value smaller than the number of elements it currently manages, it simply hides the excess elements instead of removing them from the DOM. When this happens, it's possible that an element that represents some item gets hidden, while another element continues representing the same item.
This can happen, for example, with a combo box when you filter the list of options. Consider the following scenario:
1. Initial combo-box dropdown content with three elements representing three items:
| ComboBox | 
|----|
| AA |
| BB |
| CC |
2. Filter the combo box with "B". Now we are left with just 1 visible element that represents item BB. The other elements are hidden and not updated.
| ComboBox | …

fix: make sure unhidden combo-box items get re-rendered

---

packages/date-picker/src/vaadin-date-picker-mixin.js
packages/date-picker/src/vaadin-date-picker.d.ts
packages/date-picker/src/vaadin-date-picker.js
packages/date-picker/test/value-commit-auto-open-disabled.common.js
packages/date-picker/test/value-commit.common.js

The PR introduces a new event `unparsable-change` to `date-picker`. This event is fired when the user attempts to commit or clear input that the component has failed to parse as a date. This event is intended as a supplement to the change event, which means it will be fired only when there is no change event.
Here is a table that illustrates which event is fired based on the nature of the value change:
| Value change                | Event             | Note
|:-----------------------|:------------------|:-------|
| empty => parsable      | change            | |
| empty => unparsable    | unparsable-change | |
| parsable => empty      | change            | |
| parsable => parsable   | change            | |
| parsable => unparsable | change            | The value property changes to an …

feat(date-picker): add unparsable-change event

---

packages/field-base/src/clear-button-mixin.js
packages/integer-field/src/vaadin-integer-field.d.ts
packages/integer-field/src/vaadin-integer-field.js
packages/integer-field/test/value-commit.test.js
packages/number-field/src/vaadin-number-field-mixin.js
packages/number-field/src/vaadin-number-field.d.ts
packages/number-field/src/vaadin-number-field.js
packages/number-field/test/value-commit.common.js

The PR introduces a new event `unparsable-change` to `number-field` and `integer-field`. This event is fired when the user attempts to commit or clear input that the component has failed to parse as a number. This event is intended as a supplement to the change event, which means it will be fired only when there is no change event.
Here is a table that illustrates which event is fired based on the nature of the value change:
| Value change                | Event             | Note
|:-----------------------|:------------------|:-------|
| empty => parsable      | change            | |
| empty => unparsable  | unparsable-change | |
| parsable => empty      | change            | |
| parsable => parsable   | change            | |
| parsable => unparsable | change            | The value …

feat(number-field): add unparsable-change event

---

packages/grid/theme/lumo/vaadin-grid-styles.js

Part of #5636
- Refactor
This change aligns the approach with the one used by Material theme:
https://github.com/vaadin/web-components/blob/7db27ec8e087537e1b2d19a1cecf3906833eceac/packages/grid/theme/material/vaadin-grid-styles.js#L33-L39

refactor: move Lumo font-size and font-weight styles to cells

---

packages/rich-text-editor/src/vaadin-rich-text-editor-mixin.js
packages/rich-text-editor/test/basic.common.js

Prevent `<vaadin-rich-text-editor>` from trimming whitespace on delta conversion.
Part of https://github.com/vaadin/flow-components/issues/5533
Bugfix

fix: prevent rte from trimming whitespace on delta conversion

---

packages/rich-text-editor/src/vaadin-rich-text-editor-mixin.js
packages/rich-text-editor/test/basic.common.js

Fixes a regression from https://github.com/vaadin/web-components/pull/6651 where temporarily replacing all space characters in the HTML before delta conversion might change the semantics of the original HTML:
Example:
```html
<pre spellcheck="false">code\n</pre>
```
would become invalid in case the space between the tag name and the attribute was replaced.
```html
<pre__VAADIN_RICH_TEXT_EDITOR_SPACEspellcheck="false">code\n</pre>
```
This PR fixes the issue by making the logic not replace all space characters (` `) in the HTML but only double-spaces (`  `).
Bugfix

fix: only replace double spaces on rte delta conversion

---

packages/grid/theme/lumo/vaadin-grid-styles.js

Part of #5636
This change makes it possible to customize `cursor` property e.g. like this:
```css
vaadin-grid::part(header-cell) {
cursor: pointer;
}
```
- Refactor

refactor: make cell content inherit cursor from the cell

---

packages/grid/src/vaadin-grid-mixin.js
packages/grid/test/renderers.common.js

Run header and footer renderers after grid column tree update. This ensures that header/footer content updates for a hidden column are applied when the column becomes visible again.
Fixes https://github.com/vaadin/flow-components/issues/5516
Bugfix

fix: update grid header and footer on column tree update

---

dev/assets/circle-check.svg
dev/assets/info-circle.svg
dev/icon.html
packages/icon/src/vaadin-icon.js
packages/icon/test/icon.test.js

Several icon libraries configure the fill and stroke on the root SVG element, which is currently not respected by vaadin-icon. This change copies the `fill`, `stroke`, `stroke-width`, `stroke-linecap` and `stroke-linejoin` attributes from the source SVG to the one used internally by vaadin-icon.
Fixes https://github.com/vaadin/web-components/issues/6644

fix: make vaadin-icon respect fill and stroke from source icon

---

dev/focus-ring.html
packages/avatar/src/vaadin-avatar-styles.js
packages/avatar/theme/lumo/vaadin-avatar-styles.js
packages/button/theme/lumo/vaadin-button-styles.js
packages/checkbox/theme/lumo/vaadin-checkbox-styles.js
packages/combo-box/theme/lumo/vaadin-combo-box-item-styles.js
packages/crud/theme/lumo/vaadin-crud-styles.js
packages/date-picker/theme/lumo/vaadin-month-calendar-styles.js
packages/details/theme/lumo/vaadin-details-styles.js
packages/grid-pro/theme/lumo/vaadin-grid-pro-editor-styles.js
packages/grid-pro/theme/lumo/vaadin-grid-pro-styles.js
packages/grid/theme/lumo/vaadin-grid-styles.js
packages/item/theme/lumo/vaadin-item-styles.js
packages/map/theme/lumo/vaadin-map-styles.js
packages/message-list/theme/lumo/vaadin-message-styles.js
packages/radio-group/theme/lumo/vaadin-radio-button-styles.js
packages/rich-text-editor/theme/lumo/vaadin-rich-text-editor-styles.js
packages/scroller/theme/lumo/vaadin-scroller-styles.js
packages/side-nav/theme/lumo/vaadin-side-nav-item-styles.js
packages/side-nav/theme/lumo/vaadin-side-nav-styles.js
packages/tabs/theme/lumo/vaadin-tab-styles.js
packages/upload/theme/lumo/vaadin-upload-styles.js
packages/vaadin-lumo-styles/mixins/input-field-shared.js
packages/vaadin-lumo-styles/style.js

feat: add Lumo custom CSS properties to set focus-ring

---

packages/rich-text-editor/src/vaadin-rich-text-editor.js
packages/rich-text-editor/test/basic.test.js

Cherry-pick #6651 to `24.2`
Also includes fixes: #6652 and #6661

fix: prevent rte from trimming whitespace on delta conversion (#6651)

---

packages/input-container/theme/lumo/vaadin-input-container-styles.js
packages/select/theme/lumo/vaadin-select-styles.js
packages/vaadin-lumo-styles/mixins/input-field-shared.js
packages/vaadin-lumo-styles/style.js

Part of #2954
- Feature
- `--vaadin-input-field-value-color`
- `--vaadin-input-field-value-font-size`
- `--vaadin-input-field-value-font-weight`
- `--vaadin-text-input-field-height`
- `--vaadin-text-input-field-placeholder-color`
- `--vaadin-text-input-field-readonly-border`

feat: add Lumo text input field custom CSS properties

---

packages/grid-pro/test/edit-column.test.js

This test change fixes a `<vaadin-grid-pro>` test case which [started failing](https://github.com/vaadin/web-components/pull/6664) on Webkit recently for no apparent reason.
The test failure isn't due to a component bug because manually pressing (shift-)tab works just fine, also on Safari.
Tests

test: fix a grid pro test case

---

packages/checkbox/theme/lumo/vaadin-checkbox-styles.js
packages/date-picker/theme/lumo/vaadin-month-calendar-styles.js
packages/grid/theme/lumo/vaadin-grid-sorter-styles.js
packages/item/theme/lumo/vaadin-item-styles.js
packages/multi-select-combo-box/theme/lumo/vaadin-multi-select-combo-box-styles.js
packages/radio-group/theme/lumo/vaadin-radio-button-styles.js
packages/rich-text-editor/theme/lumo/vaadin-rich-text-editor-styles.js
packages/side-nav/theme/lumo/vaadin-side-nav-item-styles.js
packages/tabs/theme/lumo/vaadin-tab-styles.js
packages/vaadin-lumo-styles/style.js

Part of #2954
- Feature
- `--vaadin-selection-color` 
- `--vaadin-selection-color-text`

feat: add Lumo selection colors custom CSS properties

---

packages/vaadin-lumo-styles/mixins/input-field-shared.js
packages/vaadin-lumo-styles/mixins/required-field.js
packages/vaadin-lumo-styles/style.js

Part of #2954
- Feature
- `--vaadin-input-field-label-color`
- `--vaadin-input-field-focused-label-color`
- `--vaadin-input-field-hovered-label-color`
- `--vaadin-input-field-label-font-size`
- `--vaadin-input-field-label-font-weight`

feat: add Lumo custom properties for input field label

---

packages/vaadin-lumo-styles/mixins/helper.js
packages/vaadin-lumo-styles/mixins/required-field.js
packages/vaadin-lumo-styles/style.js

Part of #2954
- Feature
- `--vaadin-input-field-helper-color`
- `--vaadin-input-field-helper-font-size`
- `--vaadin-input-field-helper-font-weight`
- `--vaadin-input-field-helper-spacing`
- `--vaadin-input-field-error-color`
- `--vaadin-input-field-error-font-size`
- `--vaadin-input-field-error-font-weight`

feat: add helper text and error message CSS properties

---

packages/grid/src/vaadin-grid-mixin.js

Remove a Firefox workaround that's no longer necessary

chore: remove old ff workaround from vaadin-grid-mixin

---

packages/radio-group/src/vaadin-radio-button-styles.d.ts
packages/radio-group/src/vaadin-radio-button-styles.js
packages/radio-group/src/vaadin-radio-button.js
packages/radio-group/src/vaadin-radio-group-styles.d.ts
packages/radio-group/src/vaadin-radio-group-styles.js
packages/radio-group/src/vaadin-radio-group.js

Extracted `vaadin-radio-button` and `vaadin-radio-group` CSS into tagged literals for reusing by Lit based version.
- Refactorr

refactor: extract radio button and group styles literals

---

packages/grid/src/vaadin-grid-a11y-mixin.js
packages/grid/src/vaadin-grid-array-data-provider-mixin.js
packages/grid/src/vaadin-grid-column-mixin.js
packages/grid/src/vaadin-grid-mixin.js
packages/grid/src/vaadin-grid-row-details-mixin.js
packages/grid/src/vaadin-grid-selection-mixin.js
packages/grid/test/array-data-provider.common.js
packages/grid/test/selection.common.js

This PR removed wildcards from complex observes in all grid modules. It's a prerequisite for the LitElement migration.
Refactor

refactor: remove wildcards from complex observers in grid

---

packages/grid/src/vaadin-grid-styles.js
packages/grid/src/vaadin-grid.js

Do not automatically register styles in grid core styles file (`src/vaadin-grid-styles.js`). Instead, export the styles and register them in `src/vaadin-grid.js`. This is to enable the LitElement-based grid to return the core styles from `static styles`.
Refactor

refactor: register grid core styles in vaadin-grid

---

packages/component-base/src/virtualizer-iron-list-adapter.js

Related to https://github.com/vaadin/flow-components/issues/5595
This change fixes the issue described in https://github.com/vaadin/flow-components/issues/5595#issuecomment-1770278913
Despite numerous attempts, I couldn't produce a test case for the change in `web-components`. It's possible that the issue only occurs in `flow-components` due to the grid functionality overrides in the connector, but not sure.
Before:
After:
Bugfix

fix: flush virtualizer until physical count stabilizes

---

packages/grid/src/vaadin-grid-column-group-mixin.js
packages/grid/src/vaadin-grid-dynamic-columns-mixin.js
packages/grid/src/vaadin-grid-helpers.js
packages/grid/test/column-observer.test.js
packages/grid/test/light-dom-observing.common.js

Replace the Polymer helper `FlattenedNodesObserver` in `<vaadin-grid>` with a built-in `ColumnObserver` helper.
Refactor

refactor: replace flattened nodes observer with grid column observer

---

packages/rich-text-editor/src/vaadin-rich-text-editor-mixin.js
packages/rich-text-editor/test/basic.common.js

Add a new `toolbar-button-pressed` part name depending on the state of the toolbar button to allow styling of the active state.
Fixes #6248

feat: add toolbar-button-pressed part value to active buttons

---

packages/combo-box/src/vaadin-combo-box-mixin.js
packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js
packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.d.ts
packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js
packages/multi-select-combo-box/test/helpers.js
packages/multi-select-combo-box/test/selecting-items.test.js
packages/multi-select-combo-box/test/typings/multi-select-combo-box.types.ts

Part of #4185
Added `groupSelectedItems` property that affects how `vaadin-multi-select-combo-box` overlay items are shown.
- Internal `_topGroup` property is used to store selected items. This property is only updated when the overlay is closed, so that selecting or deselecting an item doesn't move it in the overlay immediately.
- Re-introduced `_dropdownItems` property previously removed in #4019 to easily distinguish items that are actually shown in the dropdown vs `filteredItems` array, and prevent mutating it.
- Feature

feat: add property to group selected overlay items at the top

---

packages/app-layout/src/vaadin-app-layout.js

Adds the `--vaadin-app-layout-drawer-width` to be used as the value to be set as width to the drawer part of the App Layout. 
Fixes #950

feat: add --vaadin-app-layout-drawer-width CSS property

---

packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js
packages/grid/src/vaadin-grid-mixin.js
packages/grid/src/vaadin-grid.d.ts
packages/grid/src/vaadin-grid.js
packages/grid/test/data-provider.common.js

Add `collapsed-row` and `collapsed-row-cell` part names to rows and cells that can be expanded but are currently collapsed.
Fixes #1872

feat: add collapsed-row/cell part name to expandable rows

---

packages/rich-text-editor/src/vaadin-rich-text-editor.d.ts
packages/rich-text-editor/src/vaadin-rich-text-editor.js

Add missing entries for the `toolbar-button-pressed` part name to the part listing in docs.

docs: add toolbar-button-pressed entry in parts list

---

packages/app-layout/src/vaadin-app-layout.js
packages/app-layout/test/app-layout.test.js

Set the value of the `--_vaadin-app-layout-drawer-width` CSS property to `0` if there's no child of the drawer slot attached.
Make sure to remove the property when the drawer has any children.
Fixes #6699

fix: define drawer width private prop based on child count

---

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.d.ts
packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js
packages/multi-select-combo-box/test/chips.test.js

Fixes #4821
Added `--vaadin-multi-select-combo-box-chip-min-width` custom CSS property with the default value of 50px, which allows to fit one letter plus ellipsis, while also keeping enough space for the `<input>` element and clear button.
- Feature

feat: always show at least last selected item as a chip

---

packages/combo-box/src/vaadin-combo-box-mixin.js
packages/combo-box/test/object-values.test.js

Manually cherry-pick #6704 to `24.2`

fix: support items with duplicate labels in combo-box (#6704)

---

packages/input-container/theme/lumo/vaadin-input-container-styles.js
packages/select/theme/lumo/vaadin-select-styles.js
packages/vaadin-lumo-styles/mixins/input-field-shared.js
packages/vaadin-lumo-styles/style.js

Part of #2954
- Feature
- `--vaadin-input-field-background`
- `--vaadin-input-field-invalid-background`
- `--vaadin-input-field-hover-highlight`
- `--vaadin-input-field-invalid-hover-highlight`
- `--vaadin-input-field-hover-highlight-opacity`
- `--vaadin-input-field-icon-color`
- `--vaadin-input-field-icon-size`

feat: add new input field CSS custom properties, align naming

---

packages/custom-field/src/vaadin-custom-field.d.ts
packages/custom-field/src/vaadin-custom-field.js
packages/custom-field/test/dom/__snapshots__/custom-field.test.snap.js

Add `input-wrapper` part name to the input wrapper elements in `<vaadin-custom-field>`
Fixes #4263

feat: add part  in custom-field

---

packages/cookie-consent/src/vaadin-cookie-consent.js
packages/cookie-consent/test/cookie-consent.test.js

Add an observer to cookie consent that makes the component re-initialize on property changes.
Fixes https://github.com/vaadin/react-components/issues/80
Bugfix

fix: support dynamic changes to cookie consent properties

---

packages/grid/src/vaadin-grid-selection-column-base-mixin.d.ts
packages/grid/src/vaadin-grid-selection-column-base-mixin.js
packages/grid/src/vaadin-grid-selection-column.d.ts
packages/grid/src/vaadin-grid-selection-column.js
packages/grid/test/typings/grid.types.ts

Cherry pick of #6143 to 23.3.
This cherry pick is needed to complete the flow side backport of #6543 (adding the selection column base mixin avoids having duplicate code in flow part).

refactor: extract grid selection column base mixin (CP:23.3 #6143)

---

packages/checkbox/theme/lumo/vaadin-checkbox-styles.js
packages/vaadin-lumo-styles/style.js

Fixed a typo in the recently added custom CSS property: `intermediate` -> `indeterminate`.
- Bugfix

fix: use correct indeterminate checkmark property name

---

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js
packages/multi-select-combo-box/test/selecting-items.test.js

Implemented this requirement from the original issue: https://github.com/vaadin/web-components/issues/4185
> When filtering is active (i.e. the filter field is non-empty), this top-grouping of selected items should not be used.
Previously, top group was shown also with `filter` set, but with selected items not on the first page it wouldn't work. 
This problem was originally discussed in #6717 but I decided to extract it into separate PR.
- Bugfix

fix: do not show selected items on top when filter applied

---

packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js
packages/grid/src/vaadin-grid-scroll-mixin.js
packages/grid/test/keyboard-navigation.common.js

Fixes https://github.com/vaadin/web-components/issues/6724
Fixes https://github.com/vaadin/hilla/issues/1641
The issue was caused by keyboard navigation mixin [calling](https://github.com/vaadin/web-components/blob/9691021289293b040a850d2b3bbca5ea4cabcc4e/packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js#L694) `__isColumnInViewport` without taking into account that the focus target could be a header/footer cell of a column group whereas the helper function only supports columns.
This PR adds a new helper `__isHorizontallyInViewport` to check if the given element is horizontally inside the viewport and updates the logic in keyboard navigation mixin to use it instead.
Bugfix

fix: check if grid focus target is in viewport

---

packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js
packages/grid/test/keyboard-navigation.test.js

Manually cherry-pick https://github.com/vaadin/web-components/pull/6731 to `23.4`

fix: check if grid focus target is in viewport (#6731)

---

packages/button/theme/lumo/vaadin-button-styles.js
packages/vaadin-lumo-styles/style.js

Based on DX findings, having two separate padding properties for `vaadin-button` is rather confusing, because "tertiary" variant only has single property. Let's combine these into `--vaadin-button-padding` shorthand for consistency.
- Refactor

refactor: combine new vaadin-button padding properties

---

packages/grid-pro/package.json
packages/grid-pro/src/vaadin-grid-pro-edit-select.js
packages/grid-pro/test/edit-column-type.test.js

Make `<vaadin-grid-pro>`'s built-in select editor use the `items` API instead of `renderer`.
This change simplifies the implementation and fixes the select overlay to use the correct tag names: `<vaadin-item>` -> `<vaadin-select-item>`, `<vaadin-list-box>` -> `<vaadin-select-list-box>`, 
Refactor

refactor: use items api in grid-pro edit select

---

packages/grid-pro/test/edit-column-polymer.test.js
packages/grid-pro/test/edit-column-renderer-polymer.test.js
packages/grid-pro/test/edit-column-renderer.common.js
packages/grid-pro/test/edit-column-type-polymer.test.js
packages/grid-pro/test/edit-column-type.common.js
packages/grid-pro/test/edit-column.common.js
packages/grid-pro/test/grid-pro-polymer.test.js
packages/grid-pro/test/grid-pro.common.js
packages/grid-pro/test/keyboard-navigation-polymer.test.js
packages/grid-pro/test/keyboard-navigation.common.js
packages/grid-pro/test/lit-polymer.test.js
packages/grid-pro/test/lit-renderer-directives-polymer.test.js
packages/grid-pro/test/lit-renderer-directives.common.js
packages/grid-pro/test/lit.common.js

In preparation for implementing the Lit-based grid-pro, split the current test files into two parts. The common part is a copy of the old test file with the grid imports removed where the `-polymer.test.js` files include imports for the Polymer-based grid-pro.
Any timing changes required by the Lit migration are excluded from this PR.
Tests

test: split grid pro tests into common and import files

---

packages/combo-box/src/vaadin-combo-box-overlay-mixin.js
packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js
packages/multi-select-combo-box/test/chips.test.js

Fixes #6755
Note: this issue is only reproducible when `allChipsVisible` is `true`, so we don't have to backport this fix.
- Bugfix

fix: update overlay width when selected items change

---

packages/grid-pro/src/vaadin-grid-pro-edit-select-mixin.js
packages/grid-pro/src/vaadin-grid-pro-edit-select.js

Extract the `<vaadin-grid-pro-edit-select>` logic to a separate mixin to be used by the LitElement version later.
Refactor

refactor: extract grid pro edit select logic to a separate mixin

---

packages/login/theme/lumo/vaadin-login-overlay-styles.js

Fixes #6647
- Bugfix
The issue is fixed since 24.2 as part of https://github.com/vaadin/web-components/pull/6204.

fix: use correct moduleId for login overlay Lumo styles (24.1)

---

packages/grid-pro/theme/lumo/vaadin-grid-pro-edit-select.js
packages/grid-pro/theme/material/vaadin-grid-pro-edit-select.js

Follow up for https://github.com/vaadin/web-components/pull/6747
Remove no longer necessary style imports for `vaadin-item` and `vaadin-list-box`

chore: remove item and list box style imports from grid pro

---

packages/combo-box/src/vaadin-combo-box-mixin.js
packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js
packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.d.ts
packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js
packages/multi-select-combo-box/test/helpers.js
packages/multi-select-combo-box/test/selecting-items.test.js
packages/multi-select-combo-box/test/typings/multi-select-combo-box.types.ts

This is a PR to backport `groupSelectedItems` property to `23.4` branch. It includes the following PRs:
- #6685
- #6717
- #6723
- #6754
- Featrue cherry-pick

feat: add property to group selected overlay items at the top (#6685) (CP: 23.4)

---

packages/side-nav/src/vaadin-side-nav-item.js
packages/side-nav/test/dom/__snapshots__/side-nav-item.test.snap.js
packages/side-nav/test/dom/side-nav-item.test.js

Fixes #5667
As discussed internally, setting `path` to an empty string should be considered a non-empty path.
Updated the logic to only set `tabindex="-1"` when `path` contains `null` or `undefined` value.
- Bugfix

fix: make link focusable when path is an empty string

---

packages/date-picker/test/keyboard-input.common.js
packages/date-picker/test/validation.common.js

Avoid date-picker test cases using a `Date` breaking on different time zones. See https://github.com/vaadin/web-components/pull/6603#discussion_r1389464356
Tests

test: mitigate timezone related date-picker test issues

---

dev/grid-pro.html
packages/grid-pro/test/typings/lit-grid-pro.types.ts
packages/grid-pro/theme/material/vaadin-lit-grid-pro-edit-checkbox.js
packages/grid-pro/theme/material/vaadin-lit-grid-pro-edit-column.js
packages/grid-pro/theme/material/vaadin-lit-grid-pro-edit-select.js
packages/grid-pro/theme/material/vaadin-lit-grid-pro-edit-text-field.js
packages/grid-pro/theme/material/vaadin-lit-grid-pro.js
packages/grid-pro/vaadin-lit-grid-pro-edit-column.d.ts
packages/grid-pro/vaadin-lit-grid-pro-edit-column.js
packages/grid-pro/vaadin-lit-grid-pro.d.ts
packages/grid-pro/vaadin-lit-grid-pro.js

Add files to import the LitElement-based grid-pro
- root level
- example: `import '@vaadin/grid-pro/vaadin-lit-grid-pro.js';`
- lumo
- example: `import '@vaadin/grid-pro/theme/lumo/vaadin-lit-grid-pro.js';`
- material
- example: `import '@vaadin/grid-pro/theme/material/vaadin-lit-grid-pro.js';`
Also, add `lit-grid-pro.types.ts` to make sure the types are aligned with those of the PolymerElement-based grid-pro.

experiment: add imports for lit grid-pro

---

packages/checkbox-group/test/dom/__snapshots__/checkbox-group.test.snap.js
packages/checkbox/src/vaadin-checkbox-mixin.js
packages/checkbox/test/checkbox.common.js
packages/checkbox/test/dom/__snapshots__/checkbox.test.snap.js
packages/field-base/src/checked-mixin.js
packages/field-base/test/checked-mixin.test.js
packages/grid-pro/src/vaadin-grid-pro-edit-column-mixin.js
packages/radio-group/src/vaadin-radio-button-mixin.js
packages/radio-group/test/dom/__snapshots__/radio-button.test.snap.js
packages/radio-group/test/dom/__snapshots__/radio-group.test.snap.js
packages/radio-group/test/radio-button.common.js

The PR fixes the issue where `checkbox` and `radio-button` lost focus on click in Safari. The issue is fixed by adding a `[tabindex=0]` attribute to the input elements of the mentioned components.
Fixes #6756

fix: do not lose focus on click in Safari

---

packages/checkbox-group/test/dom/__snapshots__/checkbox-group.test.snap.js
packages/checkbox/src/vaadin-checkbox-mixin.js
packages/checkbox/test/checkbox.common.js
packages/checkbox/test/dom/__snapshots__/checkbox.test.snap.js
packages/field-base/src/checked-mixin.js
packages/field-base/test/checked-mixin.test.js
packages/radio-group/src/vaadin-radio-button.js
packages/radio-group/test/dom/__snapshots__/radio-button.test.snap.js
packages/radio-group/test/dom/__snapshots__/radio-group.test.snap.js
packages/radio-group/test/radio-button.test.js

A cherry-pick of the following fix to `24.2`:
- #6780
The automatic cherry-pick failed because there is no `vaadin-radio-button-mixin.js` on `24.2`.
Fixes https://github.com/vaadin/web-components/issues/6756

fix: do not lose focus on click in Safari (#6780) (CP: 24.2)

---

packages/checkbox-group/test/dom/__snapshots__/checkbox-group.test.snap.js
packages/checkbox/src/vaadin-checkbox-mixin.js
packages/checkbox/test/checkbox.common.js
packages/checkbox/test/dom/__snapshots__/checkbox.test.snap.js
packages/field-base/src/checked-mixin.js
packages/field-base/test/checked-mixin.test.js
packages/radio-group/src/vaadin-radio-button.js
packages/radio-group/test/dom/__snapshots__/radio-button.test.snap.js
packages/radio-group/test/dom/__snapshots__/radio-group.test.snap.js
packages/radio-group/test/radio-button.test.js

A cherry-pick of the following fix to `24.1`:
- #6780
The automatic cherry-pick failed because there is no `vaadin-radio-button-mixin.js` on `24.1`.
Fixes https://github.com/vaadin/web-components/issues/6756

fix: do not lose focus on click in Safari (#6780) (CP: 24.1)

---

packages/component-base/src/virtualizer-iron-list-adapter.js
packages/grid/test/resizing.common.js

Fixes a regression originating from https://github.com/vaadin/web-components/pull/5650 that manifests as a pre-expanded tree grid with allRowsVisible not displaying all rows until scrolling the content:
https://github.com/vaadin/web-components/assets/1222264/2f93b246-75d9-453d-8812-5a01a807d5f0
Bugfix

fix: update virtualizer scroller size before size change

---

packages/a11y-base/src/list-mixin.js
packages/a11y-base/test/list-mixin.test.js

Fixes #6581
Same as #2815 but for `ListMixin` (which also applies to opened `vaadin-select`).
- Bugfix

fix: support non-latin chars in list-mixin keyboard search

---

packages/date-picker/package.json
packages/date-picker/src/vaadin-date-picker-year-mixin.js
packages/date-picker/src/vaadin-lit-date-picker-overlay-content.js
packages/date-picker/src/vaadin-lit-date-picker-year.js
packages/date-picker/theme/lumo/vaadin-date-picker-overlay-content-styles.js
packages/date-picker/theme/lumo/vaadin-lit-date-picker.js
packages/date-picker/theme/material/vaadin-date-picker-overlay-content-styles.js
packages/date-picker/theme/material/vaadin-lit-date-picker.js
packages/date-picker/vaadin-lit-date-picker-light.d.ts
packages/date-picker/vaadin-lit-date-picker-light.js
packages/date-picker/vaadin-lit-date-picker.d.ts
packages/date-picker/vaadin-lit-date-picker.js

Prepare LitElement-based date-picker for release:
- Add the import files
- Split `vaadin-date-picker-year.js` into a shared mixin and add the LitElement-counterpart

experiment: prepare LitElement based date-picker for publishing

---

packages/vaadin-list-mixin/test/list-mixin.test.js
packages/vaadin-list-mixin/vaadin-list-mixin.js

Manual cherry-pick of #6798 to 23.4 branch.
- Cherry-pick

fix: support non-latin chars in list-mixin keyboard search (#6798) (CP: 23.4)

---

packages/tabs/src/vaadin-tab-styles.d.ts
packages/tabs/src/vaadin-tab-styles.js
packages/tabs/src/vaadin-tab.js
packages/tabs/src/vaadin-tabs-styles.d.ts
packages/tabs/src/vaadin-tabs-styles.js
packages/tabs/src/vaadin-tabs.js

Extracted `vaadin-tab` and `vaadin-tabs` styles to `css` literals for reusing by LitElement based version.
- Refactor

refactor: extract tabs styles to reusable css literals

---

packages/grid/src/vaadin-grid-selection-column-base-mixin.js

For some reason, the version of the grid drag selection feature cherry-picked to 23 isn't identical to that on the `main` branch in that it calls `this._grid.selectItem` where it should call `this._selectItem`.
Due to this difference, the feature [doesn't work](https://teamcity.vaadin.com/buildConfiguration/VaadinFlowComponents_PullRequestValidation/209438) with the Flow counterpart.
Bugfix

fix: call correct functions on grid drag select

---

packages/grid-pro/src/vaadin-lit-grid-pro-edit-checkbox.js
packages/grid-pro/src/vaadin-lit-grid-pro-edit-column.js
packages/grid-pro/src/vaadin-lit-grid-pro-edit-select.js
packages/grid-pro/src/vaadin-lit-grid-pro-edit-text-field.js
packages/grid-pro/src/vaadin-lit-grid-pro.js

This note is a copy-paste from elsewhere but in case of `vaadin-grid-pro` it refers to the wrong license.

chore: remove incorrect license note from Lit grid-pro JSDoc

---

packages/virtual-list/src/vaadin-virtual-list-styles.d.ts
packages/virtual-list/src/vaadin-virtual-list-styles.js
packages/virtual-list/src/vaadin-virtual-list.js

Extracted `vaadin-virtual-list` styles to `css` literals for reusing by LitElement based version.
- Refactor

refactor: extract virtual-list styles to reusable css literals

---

packages/component-base/src/data-provider-controller/data-provider-controller.js
packages/component-base/test/data-provider-controller.test.js
packages/grid/src/vaadin-grid-data-provider-mixin.js

DataProviderController currently maintains the root size in two different places at the same time: controller instance and root cache instance. This approach was chosen because `grid` requires the root cache to be always initialized with the last size that was set by the developer via the grid's `size` property rather than the last size that was received from the data provider, see https://github.com/vaadin/web-components/pull/5961#discussion_r1305666570. However, as I recently discovered, `combo-box` requires completely opposite.
So, to lighten the controller's functionality, this PR proposes: 
- dropping the controller's own size property and making the controller always initialize the root cache with the last size received from the data provider (default behavior)
- considering it the …

refactor: maintain root size only at the cache level

---

packages/vaadin-list-mixin/test/list-mixin.test.js
packages/vaadin-list-mixin/vaadin-list-mixin.js

Manual cherry-pick of #6798 to 23.3 branch.
- Cherry-pick

fix: support non-latin chars in list-mixin keyboard search (#6798) (CP: 23.3)

---

dev/virtual-list.html
packages/virtual-list/package.json
packages/virtual-list/src/vaadin-virtual-list-mixin.d.ts
packages/virtual-list/src/vaadin-virtual-list-mixin.js
packages/virtual-list/src/vaadin-virtual-list.d.ts
packages/virtual-list/src/vaadin-virtual-list.js
packages/virtual-list/test/lit-polymer.test.js
packages/virtual-list/test/lit-renderer-directives-polymer.test.js
packages/virtual-list/test/lit-renderer-directives.common.js
packages/virtual-list/test/lit.common.js
packages/virtual-list/test/typings/virtual-list.types.ts
packages/virtual-list/test/virtual-list-polymer.test.js
packages/virtual-list/test/virtual-list.common.js

- Extracted `vaadin-virtual-list` logic into a mixin for reusing by LitElement version.
- Split the test cases into `.common.js` and `-polymer.test.js` files
- Refactor

refactor: extract vaadin-virtual-list-mixin and split tests

---

packages/confirm-dialog/src/vaadin-lit-confirm-dialog.js

Fix opened-changed listener binding in confirm-dialog. 
Fixes the following error:
Bugfix

fix: fix opened-changed listener binding in confirm-dialog

---

packages/grid/src/vaadin-grid-mixin.js
packages/grid/test/column-auto-width.common.js

The width for a grid column using `autoWidth` is currently measured from the cell content element (regression from https://github.com/vaadin/web-components/pull/5623). This is problematic since it doesn't take into account styling applied to the column cells, which could affect the total column width.
This PR fixes the issue by having auto-width measured from the cell element instead of the cell content element.
Fixes https://github.com/vaadin/flow-components/issues/5599
Bugfix

fix: measure grid column auto-width from column cell

---

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js
packages/multi-select-combo-box/test/readonly.test.js

Fixes https://github.com/vaadin/flow-components/issues/4533
The issue with extra empty items shown in the dropdown was caused by filling `filteredItems` with placeholders:
https://github.com/vaadin/web-components/blob/85f5712eab50425d1eeaa161bc1d9611c60c0a00/packages/combo-box/src/vaadin-combo-box-data-provider-mixin.js#L243-L247
This wasn't caught as we didn't have a test for `size` property in the web component (Flow connector uses it).
- Bugfix
Backporting will likely require a different fix, as we I added `_dropdownItems` recently for 24.3 MSCB features.

fix: ensure only selected items are shown when readonly

---

packages/combo-box/src/vaadin-combo-box-mixin.js
packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js
packages/multi-select-combo-box/test/readonly.test.js

Manual cherry-pick of #6814 to `24.1` branch. 
This also partially reverts #4019 and restores `_dropdownItems`.
- Cherry-pick

fix: ensure only selected items are shown when readonly (#6814) (CP: 24.1)

---

packages/list-box/src/vaadin-multi-select-list-mixin.js
packages/list-box/test/multi-select-list-mixin.test.js

Fixes https://github.com/vaadin/flow-components/issues/5056
This PR aligns two observers in mixins used by `vaadin-list-box` so that they both use `disabled`:
https://github.com/vaadin/web-components/blob/bda453714f5ed8a4ad72efe168efb6a208116c88/packages/a11y-base/src/list-mixin.js#L94
https://github.com/vaadin/web-components/blob/bda453714f5ed8a4ad72efe168efb6a208116c88/packages/list-box/src/vaadin-multi-select-list-mixin.js#L42
When trying the original issue in the Flow counterpart, I noticed that `selected` is first set to `true` on the `vaadin-item` in `MultiSelectListMixin`, and then it is reset back to `false` by [`ListMixin`](https://github.com/vaadin/web-components/blob/bda453714f5ed8a4ad72efe168efb6a208116c88/packages/a11y-base/src/list-mixin.js#L171-L174), as `selected` property …

fix: do not reset selected items when disabled set to false

---

packages/vaadin-list-mixin/test/list-mixin.test.js
packages/vaadin-list-mixin/vaadin-multi-select-list-mixin.js

Manual cherry-pick of #6822 to `23.4` branch where we still have `vaadin-list-mixin` package.
- Cherry-pick

fix: do not reset selected items when disabled set to false (#6822) (CP: 23.4)

---

packages/component-base/src/virtualizer-iron-list-adapter.js
packages/grid/test/resizing.common.js

Follow-up for https://github.com/vaadin/web-components/pull/6795
The previous fix failed to cover a case where the pre-expanded grid has no header. This PR fixes the issue.
https://github.com/vaadin/web-components/assets/1222264/89de9558-4fb9-4b9b-b7d5-094738205c3f
Bugfix

fix: render virtualizer after size change

---

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js
packages/multi-select-combo-box/test/selecting-items.test.js

Fixes #6835
Updated to use the same logic as in `_isItemSelected` by `vaadin-multi-select-combo-box-scroller`:
https://github.com/vaadin/web-components/blob/04fe7d4adb3f6fec0563f90d47bc3b633ec833d1/packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-scroller.js#L75
This way we don't need to pass both `itemValuePath` and `itemIdPath`. Using `itemIdPath` is enough.
- Bugfix

fix: align check used to detect if the item is selected

---

packages/text-area/src/vaadin-text-area-mixin.js
packages/text-area/test/text-area.common.js

Fixes https://github.com/vaadin/web-components/issues/1138
Before:
https://github.com/vaadin/web-components/assets/1222264/6cf67863-e6b2-4ef9-b37f-ee6cbf5c06d9
After:
https://github.com/vaadin/web-components/assets/1222264/63a66dde-c7e3-4fa2-b8d3-81e1c03c142f
Bugfix

fix: update text-area height on resize

---

packages/grid/src/vaadin-grid-data-provider-mixin.js
packages/grid/test/data-provider.common.js

Fixes https://github.com/vaadin/web-components/issues/6849
If the grid has physical row elements and its cache gets cleared, updating the physical rows would automatically result in a new data request being made for the pages in the current viewport. If the grid has no rows (yet) however, a data request needs to be made manually. There is a [check](https://github.com/vaadin/web-components/blob/a197041861e1bbf8d3e966d893648f5dd462b036/packages/grid/src/vaadin-grid-data-provider-mixin.js#L372-L374) for this condition in the `clearCache` function.
It's possible for the grid to end up in a state where its flat size doesn't equal the virtualizer's size. This can happen if `clearCache` is called after flat size is set but before the value gets …

fix: manually load first page if grid virtualizer is empty

---

packages/date-time-picker/src/vaadin-date-time-picker.js
packages/date-time-picker/test/properties.test.js

Fixes https://github.com/vaadin/flow-components/issues/1976 for `23.3` branch.
Based on the web component observers changes from the following PRs:
- https://github.com/vaadin/web-components/pull/4971
- https://github.com/vaadin/web-components/pull/4987
- Bugfix

fix: align propagating initial date-time-picker properties (23.3)

---

integration/tests/context-menu-template.test.js
packages/context-menu/src/vaadin-context-menu-mixin.js
packages/context-menu/src/vaadin-context-menu.js
packages/context-menu/src/vaadin-contextmenu-items-mixin.js
packages/context-menu/test/dom/__snapshots__/context-menu.test.snap.js
packages/menu-bar/src/vaadin-menu-bar-mixin.js
packages/menu-bar/src/vaadin-menu-bar-submenu.js
packages/menu-bar/test/dom/__snapshots__/menu-bar.test.snap.js
packages/menu-bar/test/visual/material/menu-bar.test.js

Fixes #5990
Changed to create `vaadin-context-menu-overlay` in the `constructor()` instead of using the template.
This way we ensure `_overlayElement` is available before `ready()` to make observers work properly. 
- Refactor

refactor!: do not set ID attribute on the menu overlay

---

packages/rich-text-editor/src/vaadin-rich-text-editor-mixin.js
packages/rich-text-editor/test/basic.common.js

Avoid an error when setting html value for an unattached rich text editor
Fixes https://github.com/vaadin/flow-components/issues/4551
Bugfic

fix: cache pending html value for unattached rte

---

packages/app-layout/src/vaadin-app-layout.js
packages/app-layout/test/app-layout.test.js

Use the drawer actual size to define the offset size used for the content area in the app-layout.
This change brings back the functionality that was removed as part of the new drawer width CSS variable. As the drawer width can be defined in different ways (eg. `vaadin-app-layout::part(drawer) {width: 100px;}`), we can't rely only on the CSS variable to define the offset value.
- fix: use drawer effecive size for content offset
- test: add test checking that offset uses the right size

fix: use drawer actual size in the offset

---

packages/upload/src/vaadin-upload-mixin.js
packages/upload/test/a11y.common.js

The way `file-reject` event is [defined](https://github.com/vaadin/web-components/blob/main/packages/upload/src/vaadin-upload.d.ts#L17) is not aligned with how it is announced. The corresponding test also is a false negative since it creates the event with the structure used in announcing.
This PR fixes the announcement and the test based on the actual event structure.
One thing to note is the extra error in the event is unnecessary as `UploadFile` already contains a property for error. This is also not aligned with how the other events are structured. Updating `UploadFileRejectEvent` would be a breaking change, therefore can be considered for the future.

fix: announce file reject correctly

---

.github/workflows/coverage.yml
.github/workflows/unit-tests.yml
.github/workflows/verify.yml
.github/workflows/visual-tests.yml

Bump node version for github workflows as suggested in https://github.com/vaadin/web-components/pull/6889#pullrequestreview-1759441822

chore: bump node version for github workflows

---

packages/overlay/src/vaadin-overlay-position-mixin.js
packages/overlay/test/position-mixin-lit.js
packages/overlay/test/position-mixin-lit.test.js
packages/overlay/test/position-mixin-polymer.js
packages/overlay/test/position-mixin-polymer.test.js
packages/overlay/test/position-mixin-styles.js
packages/overlay/test/position-mixin.common.js

Extracted from #6467. 
This change is needed for `vaadin-context-menu-overlay` Lit based version to properly update position.
- Refactor

refactor: make PositionMixin properties sync, add Lit tests

---

packages/context-menu/test/a11y-polymer.test.js
packages/context-menu/test/a11y.common.js
packages/context-menu/test/context-polymer.test.js
packages/context-menu/test/context.common.js
packages/context-menu/test/integration-polymer.test.js
packages/context-menu/test/integration.common.js
packages/context-menu/test/items-polymer.test.js
packages/context-menu/test/items-theme-polymer.test.js
packages/context-menu/test/items-theme.common.js
packages/context-menu/test/items.common.js
packages/context-menu/test/lit-renderer-directive-polymer.test.js
packages/context-menu/test/lit-renderer-directives.common.js
packages/context-menu/test/overlay-polymer.test.js
packages/context-menu/test/overlay.common.js
packages/context-menu/test/properties-polymer.test.js
packages/context-menu/test/properties.common.js
packages/context-menu/test/renderer-polymer.test.js
packages/context-menu/test/renderer.common.js
packages/context-menu/test/selection-polymer.test.js
packages/context-menu/test/selection.common.js
packages/context-menu/test/touch-polymer.test.js
packages/context-menu/test/touch.common.js

Same as #6564 but for `vaadin-context-menu`.
In preparation for implementing the Lit-based context-menu, split the current test files into two parts. The common part is a copy of the old test file with the component imports removed where the `-polymer.test.js` files include imports for the Polymer-based component. Any timing changes required by the Lit migration are excluded from this PR.
- Tests

test: split context-menu tests into common and import files

---

packages/menu-bar/src/vaadin-menu-bar-submenu.js

Follow-up to #6870
In the above PR the logic was changed to create overlay in the constructor, but I missed to update this template.
- Refactor

refactor: remove vaadin-menu-bar-overlay from template

---

packages/menu-bar/src/vaadin-menu-bar-mixin.d.ts
packages/menu-bar/src/vaadin-menu-bar-mixin.js
packages/menu-bar/src/vaadin-menu-bar.d.ts
packages/menu-bar/src/vaadin-menu-bar.js

Moved some logic from `vaadin-menu-bar` to the `MenuBarMixin` for reusing by Lit based version.
- Refactor

refactor: move logic from vaadin-menu-bar to the mixin

---

packages/menu-bar/src/vaadin-menu-bar-mixin.js
packages/menu-bar/test/sub-menu.test.js

Updated `MenuBarMixin` to not use Polymer-specific `items.splices`. Also, combined two observers into one.

refactor: remove Polymer splice support for menu items

---

packages/overlay/src/vaadin-overlay-mixin.js
packages/overlay/test/interactions.common.js

Part of https://github.com/vaadin/flow-components/issues/5507
This is an alternative solution to the underlying problem of unwanted `focusout` event in Chrome.
As `focusout` fires before `mouseup`, at that point we can check which element has focus.
- Bugfix

fix: focus overlay on mouseup when focus moves to body

---

packages/overlay/src/vaadin-overlay.js
packages/overlay/test/overlay.test.js

Manual cherry-pick of #6887 to `24.1` branch.
- Cherry-pick

fix: focus overlay on mouseup when focus moves to body (#6887) (CP: 24.1)

---

packages/item/src/vaadin-item.d.ts
packages/item/src/vaadin-item.js

Fixes https://github.com/vaadin/react-components/issues/147
We are using the `label` attribute in `vaadin-select` to get the item label, but it's currently not documented:
https://github.com/vaadin/web-components/blob/25bb2617a12ecdfcacc188fe3d4c16c62a5f0033/packages/select/src/vaadin-select-base-mixin.js#L408
This change adds the `label` property to `vaadin-item` API docs (and also `web-types.json`):

docs: add label property JSDoc annotation to vaadin-item

---

packages/combo-box/src/vaadin-combo-box-mixin.d.ts

Part of https://github.com/vaadin/react-components/issues/162 - needed to hide method from IntelliJ completion:
Removed `_revertInputValue()` from `ComboBoxMixin` typings. The only reason it's where is probably the fact that this method is called by `vaadin-combo-box-light`. All the other protected methods aren't present in typings anyway.
- Refactor

refactor: remove protected method from combo-box typings

---

packages/avatar-group/src/vaadin-avatar-group.d.ts

Part of https://github.com/vaadin/react-components/issues/162 - needed to hide property from IntelliJ completion:
The `_avatars` property in the JS file is marked as private and is not supposed to be used from outside the component.
- Refactor

refactor: remove private property from avatar-group typings

---

packages/a11y-base/src/list-mixin.d.ts
packages/a11y-base/src/list-mixin.js
packages/list-box/test/list-box.test.js

Part of https://github.com/vaadin/react-components/issues/162 - needed to hide property from IntelliJ completion:
This was added in https://github.com/vaadin/vaadin-list-mixin/pull/15 but I was unable to figure out if we ever used it.

refactor: remove unused internal mixin detection property

---

packages/details/src/vaadin-details-summary.js
packages/details/src/vaadin-lit-details-summary.js

We missed to add `export` for the JS class in `vaadin-details-summary` which breaks the React wrapper:
```
Uncaught SyntaxError: The requested module '/@fs/Users/serhii/vaadin/react-components/node_modules/.vite/deps/@vaadin_details_vaadin-details-summary__js.js?v=9c5ddbf1' does not provide an export named 'DetailsSummary' (at DetailsSummary.ts:2:10)
```
- Bugfix

fix: add missing export for DetailsSummary component class

---

packages/crud/src/vaadin-crud-edit.js

Same as #6929 but for `vaadin-crud-edit` component.
We missed to add `export` for the JS class in `vaadin-details-summary` which breaks the React wrapper:
```
Uncaught SyntaxError: The requested module '/@fs/Users/serhii/vaadin/react-components/node_modules/.vite/deps/@vaadin_crud_vaadin-crud-edit__js.js?v=561c48f7' does not provide an export named 'CrudEdit' (at CrudEdit.ts:2:10)
```
- Bugfix

fix: add missing export for CrudEdit component class

---

packages/crud/src/vaadin-crud-edit.js

Manual cherry-pick of #6930 to `23.3` branch. The merge conflict was caused by `defineCustomElement` on `main`.
- Cherry-pick

fix: add missing export for CrudEdit component class (#6930) (CP: 23.3)

---

packages/crud/src/vaadin-crud-edit.js

Manual cherry-pick of #6930 to `24.1` branch. The merge conflict was caused by `defineCustomElement` on `main`.
- Cherry-pick

fix: add missing export for CrudEdit component class (#6930) (CP: 24.1)

---

packages/tabsheet/src/vaadin-tabsheet.d.ts

Currently, `vaadin-tabsheet` uses `PolymerElement` in type definitions causing the code completion to look like this:
Updated to use `HTMLElement` instead, same as it's done in all the other web components type definitions.
- Bugfix

fix: update vaadin-tabsheet type to extend HTMLElement

---

packages/side-nav/package.json

Trying to use `@vaadin/side-nav` package in a Vite app currently throws an error due to missing dependency:
```
✘ [ERROR] Could not resolve "@vaadin/a11y-base/src/disabled-mixin.js"
node_modules/@vaadin/side-nav/src/vaadin-side-nav-item.js:8:30:
8 │ import { DisabledMixin } from '@vaadin/a11y-base/src/disabled-mixin.js';
╵                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
✘ [ERROR] Could not resolve "@vaadin/a11y-base/src/styles/sr-only-styles.js"
node_modules/@vaadin/side-nav/src/vaadin-side-nav-item.js:9:33:
9 │ import { screenReaderOnly } from '@vaadin/a11y-base/src/styles/sr-only-styles.js';
╵                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
- Bugfix

fix: add missing a11y-base dependency to side-nav

---

packages/side-nav/package.json

Same as #6944 but for `24.2` where `vaadin-side-nav` was first introduced as stable.
- Bugfix

fix: add missing a11y-base dependency to side-nav (24.2)

---

packages/accordion/package.json
packages/avatar/package.json
packages/confirm-dialog/package.json
packages/custom-field/package.json
packages/date-picker/package.json
packages/details/package.json
packages/input-container/package.json
packages/login/package.json
packages/radio-group/package.json
packages/rich-text-editor/package.json
packages/tabs/package.json

Some packages with Lit based version are missing the `lit` direct dependency.
While it's available through `@vaadin/vaadin-themable-mixin`, there are errors when using Skypack CDN:

chore: add missing Lit direct dependency

---

packages/component-base/src/controller-mixin.d.ts

This pull request addresses an inconsistency in the `ControllerMixin` API. The `addController` and `removeController` functions are currently [labeled as protected in JSDoc](https://github.com/vaadin/web-components/blob/713c37a239d9230774eddc10436c7587a1de09d1/packages/component-base/src/controller-mixin.js#L61), which makes them appear as protected on the API [documentation generated with Polymer Analyzer](https://cdn.vaadin.com/vaadin-web-components/24.3.0-rc1/#/elements/vaadin-avatar-group#method-addController).
However, in the TypeScript definition, they are [not marked as protected](https://github.com/vaadin/web-components/blob/713c37a239d9230774eddc10436c7587a1de09d1/packages/component-base/src/controller-mixin.d.ts#L22), which makes them public properties for the generated React …

fix: align controller-mixin TS API visibility

---

packages/side-nav/src/vaadin-side-nav.js

Usage of `ifDefined` was removed in #6738 but I missed to remove this directive import.
- Refactor

refactor: remove unused ifDefined import from side-nav

---

packages/component-base/test/slot-styles-mixin.test.js

This mixin was moved from `@vaadin/field-base` in #6393 and the imports in tests weren't updated.
- Test

test: use relative imports in SlotStylesMixin tests

---

packages/upload/src/vaadin-upload-mixin.d.ts

Fixes https://github.com/vaadin/react-components/issues/73
The `held` property is set on the `file` instance but missing from the corresponding type. This PR adds it.
https://github.com/vaadin/web-components/blob/1f34ad0c959f91ceb505b4264c0f9cb67d50d566/packages/upload/src/vaadin-upload-mixin.js#L819
- Bugfix

fix: add missing held property to UploadFile type

---

packages/split-layout/src/vaadin-split-layout.js
packages/split-layout/test/split-layout.test.js

Manual CP from #6938 to V24.1 and older

fix: allow defining slots in split-layout (#6938) (CP: 24.1)

---

packages/component-base/src/delegate-state-mixin.d.ts

Similar to #6917
Updated `stateTarget` property in `DelegateStateMixin` to be marked as protected. 
It actually has corresponding JSDoc, but is marked as public in `.d.ts`.
This change is needed to hide this property from VSCode / IntelliJ autocomplete:
- Refactor

refactor: make stateTarget property in typings as protected

---

packages/crud/src/vaadin-crud.d.ts

Updated `_fields` property in `Crud` to be marked as protected. 
It actually has corresponding JSDoc, but is public in `.d.ts`.
https://github.com/vaadin/web-components/blob/d3c22c6003f3507e1c6ff4fa5487d5971191e65a/packages/crud/src/vaadin-crud.js#L677-L682
- Refactor

refactor: mark _fields property in typings as protected

---

packages/grid/src/vaadin-grid-sort-mixin.js
packages/grid/src/vaadin-grid-sorter-mixin.js
packages/grid/test/sorting.common.js

The PR updates the grid sorting logic so that it excludes hidden columns from sorting and includes them when they are shown again.
Precedes:
- https://github.com/vaadin/flow-components/pull/5817
Part of https://github.com/vaadin/flow-components/issues/5513

fix!: exclude hidden columns from sorting (24.4)

---

packages/component-base/src/data-provider-controller/data-provider-controller.js
packages/component-base/test/data-provider-controller-data-callbacks.test.js
packages/grid/test/drag-and-drop.common.js

The PR adds a check to DataProviderController to ignore data from callbacks that have been already invoked once before.
Fixes https://github.com/vaadin/web-components/issues/6584

fix: ignore data from re-invoked callbacks

---

packages/accordion/package.json
packages/accordion/src/vaadin-accordion-mixin.d.ts
packages/accordion/src/vaadin-accordion-mixin.js
packages/accordion/src/vaadin-accordion-panel-mixin.d.ts
packages/accordion/src/vaadin-accordion-panel-mixin.js
packages/accordion/src/vaadin-accordion-panel.d.ts
packages/accordion/src/vaadin-accordion-panel.js
packages/accordion/src/vaadin-accordion.d.ts
packages/accordion/src/vaadin-accordion.js
packages/accordion/test/typings/accordion.types.ts

Extracted reusable mixin for `vaadin-accordion` and `vaadin-accordion-panel` to be used by LitElement version.
- Refactor

refactor: extract accordion and accordion-panel mixins

---

packages/combo-box/src/vaadin-combo-box-mixin.js
packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js

Following up on https://github.com/vaadin/web-components/pull/6685, this PR refactors `combo-box` to calculate the initially focused index based on `_dropdownItems` instead of `filteredItems`. This aligns it with the arrow navigation logic which calculates the focused index based on `_dropdownItems`. The previous version hasn't caused real issues because `multi-select-combo-box`, which overrides `_setDropdownItems`, doesn't currently shuffle items when a filter is applied.

refactor: calculate initially focused index based on _dropdownItems

---

packages/grid/src/vaadin-grid-sort-mixin.js

The PR simplifies the grid sort mixin by replacing verbose constructions with modern JavaScript syntax.
Related to https://github.com/vaadin/flow-components/issues/5513

refactor: simplify grid sort mixin with modern JS syntax

---

packages/grid/src/vaadin-grid-array-data-provider-mixin.js
packages/grid/test/filtering.common.js
packages/grid/test/sorting.common.js

The PR decreases the number of array data provider calls to one for filtering and sorting operations. This is achieved by removing `_filters` and `_sorters` from dependencies of `ArrayDataProviderMixin`'s observer.
A follow-up to https://github.com/vaadin/web-components/pull/6981#discussion_r1430074919

refactor: decrease array data provider calls when filtering or sorting

---

packages/tabsheet/src/vaadin-tabsheet.d.ts
packages/tabsheet/test/typings/tabsheet.types.ts

Fixes https://github.com/vaadin/react-components/issues/189
For some reason, the order of the mixins matters in this case and if `ThemableMixin` is not used as the very first one, the component type ends up not extending `ThemePropertyMixinClass`.
Also removed `DelegateStateMixin` from `TabSheet` because it gets inherited from `TabSheetMixin`
Bugfix

fix: make tabsheet type extend themable mixin

---

packages/grid/src/vaadin-grid-styling-mixin.d.ts

There is no `GridPartCellGenerator` type, the correct one is `GridCellPartNameGenerator`.

docs: fix incorrect type name in deprecation notice

---

packages/integer-field/test/integer-field.test.js
packages/number-field/src/vaadin-number-field-mixin.js
packages/number-field/test/number-field.common.js
packages/number-field/test/value-control-buttons.common.js

The PR ensures that an `input` event is fired on number fields' input element when the user increments or decrements the value by clicking on a stepper button or pressing an arrow key. This aligns the web component's behavior with the native `input[type=number]` behavior that does fire `input` on stepper button click.
Fixes https://github.com/vaadin/flow-components/issues/5863

fix: fire input event on input element on increment/decrement

---

integration/tests/context-menu-date-picker.test.js
packages/date-picker/src/vaadin-date-picker-mixin.js
packages/date-picker/test/dropdown.common.js

Currently, the event is propagated on date picker overlay click. This leads to problems as a possible context menu or popup that contains the date picker is also closed. A similar problem in combo box is [handled](https://github.com/vaadin/web-components/blob/main/packages/combo-box/src/vaadin-combo-box-scroller-mixin.js#L132) by stopping click event propagation on the scroller. This PR applies the same logic to the overlay content. Note that this also fixes the issue with the date time picker.
NOTE: It should be back-ported to the relevant versions for the BFP request.
Fixes #6986

fix: stop propagation of click events on overlay

---

integration/tests/context-menu-date-picker.test.js
packages/date-picker/src/vaadin-date-picker-mixin.js

Back-port of #6987 to v23.4 and v23.3.
The test has 2 extra functions since the helper class does not exist in v23.
Fixes #6986

fix: stop propagation of click events on overlay (#6987)

---

packages/rich-text-editor/src/vaadin-rich-text-editor-mixin.js
packages/rich-text-editor/test/basic.common.js

The PR ensures  that `rich-text-editor` doesn't throw `Cannot read properties of undefined (reading 'getModule')` exception when the `dir` attribute is set initially.
Fixes #6946

fix: do not throw when dir attribute is set initially

---

packages/context-menu/src/vaadin-context-menu-overlay.d.ts

Follow-up to #6145 
I missed to update typings when updating `vaadin-context-menu-overlay` to not extend `Overlay`. This PR fixes that.
- Typings fix

fix: use correct mixins in context-menu overlay typings

---

packages/confirm-dialog/theme/lumo/vaadin-confirm-dialog.js
packages/confirm-dialog/theme/lumo/vaadin-lit-confirm-dialog.js
packages/confirm-dialog/theme/material/vaadin-confirm-dialog.js
packages/confirm-dialog/theme/material/vaadin-lit-confirm-dialog.js
packages/crud/src/vaadin-crud.js
packages/crud/theme/lumo/vaadin-crud.js
packages/crud/theme/material/vaadin-crud.js

This is a follow-up to the following PRs:
- #6166
- #6167
There is no need to define `vaadin-dialog` as a side-effect of importing `vaadin-confirm-dialog` or `vaadin-crud`.
- Refactor

refactor: remove dialog imports from confirm-dialog and crud

---

packages/multi-select-combo-box/package.json

The `@vaadin/multi-select-combo-box` package is missing `"type": "module"` entry added in #3280. Let's fix this.

chore: add missing type: module entry to package.json

---

packages/dialog/theme/lumo/vaadin-dialog.js
packages/dialog/theme/lumo/vaadin-lit-dialog.js
packages/dialog/theme/material/vaadin-dialog.js
packages/dialog/theme/material/vaadin-lit-dialog.js

Follow-up to #6184
These theme imports were added in #3888 but they are no longer needed as we now updated individual components to no longer extend `vaadin-overlay` (in fact, this generic component will become unused once #7002 is merged).
- Refactor

refactor: remove no longer needed overlay imports from dialog

---

packages/context-menu/package.json
packages/dialog/package.json
packages/grid-pro/package.json
packages/grid/package.json
packages/overlay/package.json
packages/select/package.json
packages/virtual-list/package.json

Components that have Lit based versions should have Lit in `"dependencies"`, not `"devDependencies"`.
Note: some components in this PR aren't yet published to npm. Also, `lit` comes with `ThemableMixin`.
But IMO it's better to have a direct dependency for consistency with other component packages.

chore: move Lit from dev dependencies to dependencies

---

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-overlay.d.ts
packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-overlay.js
packages/multi-select-combo-box/theme/lumo/vaadin-multi-select-combo-box.js
packages/multi-select-combo-box/theme/material/vaadin-multi-select-combo-box.js

Same as #6134 but for `vaadin-multi-select-combo-box`.
Part of https://github.com/vaadin/web-components/issues/5718
Updated `vaadin-multi-select-combo-box-overlay` to align with the `vaadin-combo-box-overlay`.
As a result, this component no longer imports `vaadin-overlay` so it doesn't get defined.
- Refactor (behavior altering change)

refactor!: update MSCB overlay to not extend vaadin-overlay

---

packages/password-field/src/vaadin-password-field-button.js

Changed `vaadin-password-field-button` to use `ButtonMixin` and `buttonStyles` CSS literal.
This eliminates the need for having `<slot name="tooltip">` which was there just to prevent throwing an error.
Also, from now on CSS applied to `vaadin-button` won't accidentally affect `vaadin-password-field-button`.
- Refactor / behavior altering change.

refactor!: update password-field button to not extend button

---

packages/app-layout/package.json
packages/app-layout/src/vaadin-drawer-toggle-styles.d.ts
packages/app-layout/src/vaadin-drawer-toggle-styles.js
packages/app-layout/src/vaadin-drawer-toggle.d.ts
packages/app-layout/src/vaadin-drawer-toggle.js
packages/app-layout/test/dom/__snapshots__/drawer-toggle.test.snap.js

Same as #7004 but for `vaadin-drawer-toggle` component.
Changed to use `ButtonMixin` and `buttonStyles` CSS literal instead of extending `Button` class.
This eliminates the need for having `<slot name="tooltip">` which was there just to prevent throwing an error.
Also, from now on custom CSS applied to `vaadin-button` won't accidentally affect `vaadin-drawer-toggle`.
- Refactor / behavior altering change.

refactor!: update drawer-toggle to not extend button

---

packages/menu-bar/src/vaadin-menu-bar-submenu.js

Updated `vaadin-menu-bar-submenu` class to use mixins instead of extending `vaadin-context-menu`.
This removes a side-effect of defining `vaadin-context-menu` when importing `vaadin-menu-bar`.
- Refactor / behavior altering change

refactor!: update menu-bar submenu to not extend context-menu

---

packages/number-field/src/vaadin-number-field.d.ts

This mixin import is unused since #5522 where the `NumberFieldMixin` was introduced.

docs: remove unused InputFieldMixin import from typings

---

packages/a11y-base/src/active-mixin.js

Currently, `ActiveMixin` applies `DirMixin` but is lacking `@mixes` annotation. As a result, components using `ActiveMixin` such as `vaadin-accordion-heading` don't have `disabled` property in [API docs](https://cdn.vaadin.com/vaadin-web-components/24.3.2/#/elements/AccordionHeading#properties). This PR fixes that.

docs: add missing mixes annotations to ActiveMixin JSDoc

---

packages/login/src/vaadin-login-overlay-wrapper.js

Follow-up to #6204
I missed to update JSDoc for this element when changing to not extend `vaadin-overlay`. This PR fixes that.

docs: use correct mixins in vaadin-login-overlay JSDoc

---

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-overlay.js

Follow-up to #7002 
I missed to update JSDoc for this element. This PR fixes that.

docs: use mixins in multi-select-combo-box-overlay JSDoc

---

packages/grid/src/vaadin-grid-selection-column-base-mixin.d.ts
packages/grid/src/vaadin-grid-selection-column-mixin.js

Follow-up to #6610 
- Added missing `@mixes` annotation to make `GridSelectionColumnBaseMixin` properties such as `autoSelect`, `selectAll` etc correctly shown in [API docs](https://cdn.vaadin.com/vaadin-web-components/24.3.2/#/elements/vaadin-grid-selection-column) of `vaadin-grid-selection-column` web component,
- Removed incorrect `@polymerMixin` annotation from `.d.ts` file (these are only needed in `.js` files).

docs: fix vaadin-grid-selection-column JSDoc annotations

---

packages/item/src/vaadin-item-mixin.js

Currently, `ItemMixin` applies `DisabledMixin` but is lacking `@mixes` annotation. This PR fixes that.

docs: add missing mixes annotations to ItemMixin JSDoc

---

packages/a11y-base/src/field-aria-controller.js

Importing these helpers using `@vaadin/a11y-base` is not needed, because they are located in the same package.
- Refactor

refactor: use relative imports for ID reference helpers

---

scripts/buildWebtypes.js

Just noticed that empty `web-types.json` and `web-types.lit.json` are created for this package. This PR fixes that.

chore: exclude a11y-base package from web-types generation

---

packages/overlay/package.json
packages/tabs/package.json
packages/tabsheet/package.json

Some `package.json` entries were not updated when moving packages. This PR fixes that.

chore: fix wrong directory paths in package.json files

---

packages/crud/src/vaadin-crud.d.ts
packages/crud/test/typings/crud.types.ts

Currently, when using `Constructor<CrudElement>` there is a TS compilation error:
```
error TS2314: Generic type 'Crud<Item>' requires 1 type argument(s).
```
This PR makes `Crud` class aligned with `Grid` and `GridPro` to mitigate this.
In general, nothing changes since `GridDefaultItem` is just an alias to `any`.
Note: this PR is needed for my ongoing lazy React components prototype.
- Refactor

refactor: align Crud generic type with Grid and GridPro

---

packages/avatar/package.json
packages/icon/package.json
packages/side-nav/package.json

Added missing `@open-wc/dedupe-mixin` dependency to some components that import `Constructor` type from there.

chore: add missing dedupe-mixin dependency used in typings

---

packages/avatar/package.json
packages/icon/package.json
packages/side-nav/package.json

Manual cherry-pick of #7037 to `24.3` branch.
- Cherry-pick

chore: add missing dedupe-mixin dependency used in typings (#7037) (CP: 24.3)

---

packages/tooltip/src/vaadin-lit-tooltip.js

Using `@customElement` in Lit based component JSDoc makes `vaadin-tooltip` show up in [API docs](https://cdn.vaadin.com/vaadin-web-components/24.3.2/) navigation twice:
Removed this annotation to only have Polymer based version shown in the navigation.

docs: remove customElement JSDoc from Lit based tooltip

---

packages/component-base/src/polylit-mixin.js
packages/component-base/test/polylit-mixin.test.js

Added a simplified version of the [`setProperties()`](https://github.com/Polymer/polymer/blob/1e8b246d01ea99adba305ea04c45d26da31f68f1/lib/mixins/property-effects.js#L1846-L1857) method available in `PolymerElement` for batching updates.
This is a pre-requisite for converting `vaadin-combo-box` to Lit, as this component relies on this method logic.
Note: I didn't bother to implement `setReadOnly` flag as we don't use it, and to keep the code cleaner.

feat: add setProperties() method to PolylitMixin

---

packages/overlay/src/vaadin-overlay-position-mixin.js
packages/overlay/test/position-mixin.common.js

Currently, when using `PositionMixin` with Lit, there is an issue related to the order of observers. As they are run by `PolylitMixin` in the same order in which they are provided in the array, this might cause the following error:
```
?wtr-test-file=%2Fpackages%2Foverlay%2Ftest%2Fposition-mixin-lit.test.js%3Fwtr-manual-session%3Dtrue:151 TypeError: Cannot read properties of undefined (reading 'bottom')
at PositionedOverlay.__shouldAlignStart (vaadin-overlay-position-mixin.js:305:89)
at PositionedOverlay.__shouldAlignStartVertically (vaadin-overlay-position-mixin.js:291:19)
at PositionedOverlay._updatePosition (vaadin-overlay-position-mixin.js:220:47)
at PositionedOverlay.__positionSettingsChanged (vaadin-overlay-position-mixin.js:201:12)
at polylit-mixin.js:249:25
at Map.forEach …
```

fix: check for margins object when trying to set overlay position

---

packages/confirm-dialog/theme/lumo/vaadin-confirm-dialog-styles.js
packages/confirm-dialog/theme/lumo/vaadin-lit-confirm-dialog.js
packages/confirm-dialog/theme/material/vaadin-confirm-dialog-styles.js
packages/confirm-dialog/theme/material/vaadin-lit-confirm-dialog.js

Follow-up to #6569
Updated themed Lit entrypoints of `vaadin-confirm-dialog` to import corresponding Lit based `vaadin-button` theme files added in #6773. This makes Lit versions aligned with the corresponding Polymer based theme entrypoints.
- Refactor

refactor: simplify button imports in confirm-dialog themes

---

packages/grid/src/vaadin-grid-mixin.js
packages/grid/src/vaadin-grid-styles.js
packages/grid/test/column-auto-width.common.js

When calculating the auto-width of the grid column, the cells of the column are temporarily set to have `width: auto` ([in here](https://github.com/vaadin/web-components/blob/70c0d989a0d4224b3ecbe17da0d9b3e7ef3c42d2/packages/grid/src/vaadin-grid-mixin.js#L426)). This helps to fully expand the cell content and therefore gives a chance to measure the real total width of the cell content. This number is then taken into account when calculating the auto-width. Once the calculation is done, the original `width` of the cell is restored.
For the `vaadin-grid-pro-edit-column`, this mechanism didn't work correctly, because this column wraps the cell's slot with an additional div (aka wrapping-div) because of accessibility reasons - using the [focusButtonMode …

fix: measure auto-width correctly for focusButtonMode columns

---

packages/grid/theme/lumo/vaadin-grid-styles.js
packages/grid/theme/lumo/vaadin-lit-grid-filter.js
packages/grid/theme/lumo/vaadin-lit-grid-selection-column.js
packages/grid/theme/material/vaadin-lit-grid-filter.js
packages/grid/theme/material/vaadin-lit-grid-selection-column.js

Lit imports for `vaadin-grid` were added in #6730, before we added corresponding imports to `vaadin-checkbox` in #6774 and `vaadin-text-field` in #6784, respectively. This PR updates Lit grid to use these newly added entrypoints.
- Refactor

refactor: update grid theme files to use new Lit imports

---

dev/multi-select-combo-box.html
packages/combo-box/src/vaadin-combo-box-mixin.js
packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js
packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.d.ts
packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js
packages/multi-select-combo-box/test/selecting-items.test.js

Adds a `keepFilter` option to `<vaadin-multi-select-combo-box>` that allows to keep the filter value after selecting an item.
Some notes regarding the behavior:
- Filter is preserved when selecting items using either mouse or keyboard
- Input value is restored to the filter after selecting items using keyboard. Selecting items using keyboard overrides the input value with the item label so this needs to be reverted.
- The filter is cleared when:
- Closing the overlay either due to focus out or canceling input with Escape
- Adding a custom value
- Trying to commit a non-existing value. Might be better UX to keep the filter, but I left it out due to complexity, and it seems like an edge-case.
Closes https://github.com/vaadin/web-components/issues/5930

feat: add keepFilter option

---

packages/grid/src/vaadin-grid-scroll-mixin.d.ts

The `columnRendering` property was lacking `@attr` annotation in typings, needed for VSCode Lit plugin to show docs:

docs: add missing attr JSDoc annotation to typings

---

packages/grid/src/vaadin-grid-column-mixin.js
packages/grid/test/column-rendering.common.js

When there are invisible rows and there is a renderer change, the grid column also renders the cells in those invisible rows. This PR adds a check that prevents this unnecessary render.
Fixes #7071

fix: do not render cell for invisible rows

---

packages/combo-box/src/vaadin-combo-box-mixin.js
packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js
packages/multi-select-combo-box/test/selecting-items.test.js

Fixes MSBC to not reset the filter + input value when pressing Enter while the input value does not match any option. That is how the regular combo-box works, and it improves the UX as the user doesn't lose their filter, for example if they try to add a custom value even though that is not allowed.
Clearing the filter is probably a regression (I assume it's unintentional) from https://github.com/vaadin/web-components/pull/6372, as such it also realigns the behavior with the v23 MSCB.
- Bugfix

fix: preserve filter when committing an invalid option

---

packages/text-field/src/vaadin-lit-text-field.js
packages/text-field/src/vaadin-text-field.js

This CSS was added in #2274. Later on, we fixed `vaadin-input-container` to set `flex-grow: 0` in #2612 so that all input fields behave the same in this regard. So this style block is no longer needed and can be removed.
- Refactor

refactor: remove no longer needed flex-grow CSS override

---

packages/combo-box/src/vaadin-combo-box-mixin.js
packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js
packages/multi-select-combo-box/test/selecting-items.test.js

fix: preserve filter when committing an invalid option (#7072) (CP: 24.3)

---

packages/combo-box/src/vaadin-combo-box-mixin.js
packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js
packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.d.ts
packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js
packages/multi-select-combo-box/test/selecting-items.test.js

feat: add keepFilter option (#7063) (CP: 23.4)

---

packages/login/theme/lumo/vaadin-login-overlay-styles.js
packages/login/theme/material/vaadin-login-overlay-styles.js

Currently, some style modules (color and typography) are being registered twice. This PR fixes that.
https://github.com/vaadin/web-components/blob/366fd72fd12312b0202558fe7ff8b6026b100577/packages/login/theme/lumo/vaadin-login-form-wrapper-styles.js#L86-L88
https://github.com/vaadin/web-components/blob/366fd72fd12312b0202558fe7ff8b6026b100577/packages/login/theme/lumo/vaadin-login-overlay-styles.js#L196-L198
https://github.com/vaadin/web-components/blob/366fd72fd12312b0202558fe7ff8b6026b100577/packages/login/theme/material/vaadin-login-form-wrapper-styles.js#L100-L102
https://github.com/vaadin/web-components/blob/366fd72fd12312b0202558fe7ff8b6026b100577/packages/login/theme/material/vaadin-login-overlay-styles.js#L350
- Refactor

refactor: do not register login form wrapper styles twice

---

.eslintignore
.gitignore
package.json
scripts/buildThemeTypings.sh
tsconfig.build.json

Fixes #7073
Added a script that does the following:
1. Renames all`.js` files in theme folders to `.ts`
2. Runs `tsc` to generates `.d.ts` files for them
3. Restores `.js` files back and removes `.ts`
Also added `.d.ts` files to `.gitignore` so we don't commit them.
- Feature

feat: add script to build type definitions for theme folders

---

packages/form-layout/src/vaadin-form-layout.d.ts
packages/form-layout/src/vaadin-form-layout.js
packages/form-layout/test/form-layout.test.js

Related to https://github.com/vaadin/react-components/issues/70#issuecomment-1892023308
Added `data-colspan` for usage in React, in order to provide better DX compared to current `{...{ colspan: 2 }}`.
- Feature

feat: support using data-colspan attribute to set colspan

---

packages/grid/test/typings/grid.types.ts
packages/grid/test/typings/lit-grid.types.ts
packages/grid/vaadin-grid.d.ts
packages/grid/vaadin-grid.js
packages/grid/vaadin-lit-grid.d.ts
packages/grid/vaadin-lit-grid.js

We need this minor breaking change for React components, see https://github.com/vaadin/react-components/pull/221#discussion_r1455091782 and older workaround in https://github.com/vaadin/react-components/pull/89. From now on, TS users should import `GridColumn` related types from `vaadnin-grid-column.js` instead of `vaadin-grid.js` - this will help us to avoid conflicting namespaces problem.

refactor!: remove column re-exports from grid root entrypoint

---

packages/side-nav/src/vaadin-side-nav-item.d.ts
packages/side-nav/src/vaadin-side-nav-item.js
packages/side-nav/test/side-nav-item.test.js

Make it possible to define a `target` attribute to forward its value to the internal anchor element present in the `<vaadin-side-nav-item>` component.
Part of vaadin/flow-components#5091

feat: add target property to side-nav-item

---

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js
packages/multi-select-combo-box/test/basic.test.js

Disables the clear button logic from `vaadin-combo-box-mixin`, which clears the filter input when pressing the clear button. Instead, only the MSCB clear button logic is executed, which only clears the selection.
The bug actually only occurs on the first touch event, and not on subsequent ones. The root cause is that on the first clear, `selectedItem` is changed from `undefined` to `null`, which runs the respective change logic that also resets the input. Ideally `selectedItem` would be initialized with `null`, so the change would never happen. However, doing so results in a lot of test failures. I guess it would require additional changes to handle the initial Polymer change event then, but if someone has an idea feel free to make suggestions.
Fixes …

fix: avoid clearing filter when pressing clear button on mobile

---

packages/grid/src/vaadin-grid-mixin.js
packages/grid/test/column-rendering.common.js

In some cases, like changing a column's `hidden` state, the `_updateRow` method in `GridMixin` is called. In that scenario, when `columnRendering` is defined as `lazy`, the sizer cells that are not visible in the viewport are not appended to the `caption#sizer` element. When that happens, the logic that checks whether a column is within the viewport or not can not work as expected.
This change ensures that sizer cells are always appended, even for columns that are outside of the viewport.
Fixes #7051

fix: ensure to append sizer cell of columns outside the viewport

---

packages/menu-bar/src/vaadin-menu-bar-mixin.d.ts
packages/menu-bar/src/vaadin-menu-bar-mixin.js
packages/menu-bar/test/overflow.test.js
packages/menu-bar/test/sub-menu.test.js

Allows to close a menu bar programmatically. This closes any open sub-menu, either from a regular button or from the overflow button, including any nested sub-menus.
Part of https://github.com/vaadin/web-components/issues/728
Part of https://github.com/vaadin/flow-components/issues/5742
- Feature

feat: close menu-bar programmatically

---

packages/rich-text-editor/src/vaadin-rich-text-editor-mixin.js
packages/rich-text-editor/test/basic.common.js

RTE contains logic to remove Quill-specific CSS classes from the HTML value, however the current logic simply removes any occurence of `ql-*`, even within HTML text content. That means typing something like `mysql-connector-j` gets shortened to `mys`.
This changes the regex to only look for occurences in `class="..."` attributes.
Ideally we could work with the actual DOM (by cloning the editor node) and `classList` here, but that would require some testing regarding the performance impact as this runs on every value change.
Fixes https://github.com/vaadin/web-components/issues/7093

fix: avoid removing ql-* from HTML content

---

packages/combo-box/theme/lumo/vaadin-combo-box-item-styles.js
packages/item/theme/lumo/vaadin-item-styles.js
packages/item/theme/material/vaadin-item-styles.js

Show focus ring for items on mobile devices. `vaadin-item` and `vaadin-combo-box-item` were the only two instances where the focus ring was not applied due to a media query, for other components the focus ring is already visible on mobile devices as well when using keyboard navigation.
Fixes #7056
- Bugfix

fix: show focus ring for items on mobile

---

packages/menu-bar/src/vaadin-menu-bar-button.js
packages/menu-bar/src/vaadin-menu-bar-mixin.js
packages/menu-bar/test/sub-menu.test.js

In a Menu Bar Button, an Enter or Space key press is handled in the same way as a click. This behaviour is inherited from Button. The expected click behaviour (just opening the submenu) does not fit the Enter and Space key presses, since the first submenu item is not focused. 
This PR overrides `_onKeyDown` Menu Bar Button to leave the handling of Enter and Space (the default active keys for a button) to Menu Bar. This way, the behaviour can be customized to also focus on the first item.
Fixes #4861

fix: implement enter and space handlers instead of button click

---

packages/combo-box/src/vaadin-combo-box-scroller-mixin.js
packages/component-base/src/virtualizer-iron-list-adapter.js
packages/component-base/test/virtualizer-reorder-elements.test.js
packages/grid/src/vaadin-grid-scroll-mixin.js
packages/grid/test/keyboard-navigation.common.js
packages/virtual-list/src/vaadin-virtual-list-mixin.js

As suggested in https://github.com/vaadin/web-components/issues/4280#issuecomment-1923607349, this PR enhances virtualizer to make sure the next/previous element is synchronously available when navigating the items with keyboard (tabbing focusable content).
For example. the buttons in the following example can be tabbed through after the change:
```html
import '@vaadin/virtual-list';
const items = Array.from({ length: 100 }).map((_, i) => {
return { label: `Item ${i}` };
});
const renderer = (root, _, { item }) => {
root.innerHTML = `<button>${item.label}</button>`;
};
const list = document.querySelector('vaadin-virtual-list');
list.items = items;
list.renderer = renderer;
</script>
<vaadin-virtual-list style="height: 200px"></vaadin-virtual-list>
``` …

fix: make sure virtualizer has next focusable element

---

packages/charts/src/vaadin-chart.js

fix: mokeypatch Pointer.onDocumentMouseMove method (#7118)

---

packages/side-nav/src/vaadin-side-nav-item.js
packages/side-nav/src/vaadin-side-nav.d.ts
packages/side-nav/src/vaadin-side-nav.js
packages/side-nav/test/navigation-callback.test.js
packages/side-nav/test/navigation.test.js
packages/side-nav/test/typings/side-nav.types.ts

This PR adds `onNavigate` and `location` properties to `<vaadin-side-nav>`. The properties can be used to integrate the component with a client-side router.
Example usage with React router:
```jsx
import { SideNav, SideNavItem } from "@vaadin/react-components";
import { useNavigate, useLocation } from "react-router";
function SideNavigation() {
const navigate = useNavigate();
const location = useLocation();
return (
<SideNav onNavigate={({ path }) => navigate(path)} location={location}>
<SideNavItem path="contacts">Contacts</SideNavItem>
<SideNavItem path="hello">Hello</SideNavItem>
</SideNav>
);
}
```
Fixes https://github.com/vaadin/web-components/issues/6468
Note: Once [navigation API](https://caniuse.com/mdn-api_navigation) is available in all supported browsers, we can update …

feat: add side-nav router integration API

---

packages/component-base/src/virtualizer-iron-list-adapter.js
packages/component-base/test/virtualizer-item-height.test.js

When a virtualizer item is a placeholder, it should be visually hidden to avoid unnecessary jumpiness.
Fixes https://github.com/vaadin/react-components/issues/88
Fixes https://github.com/vaadin/web-components/issues/5982
Bugfix

fix: visually hide virtualizer placeholders

---

packages/component-base/src/url-utils.d.ts
packages/component-base/src/url-utils.js
packages/component-base/test/url-utils.test.js
packages/side-nav/src/vaadin-side-nav-item.d.ts
packages/side-nav/src/vaadin-side-nav-item.js
packages/side-nav/test/dom/side-nav-item.test.js
packages/side-nav/test/side-nav-item.test.js

The PR adds new logic to side-nav to match query params when determining highlighted items. A side-nav item is highlighted if the browser URL has the same base origin, the same path, and at least contains all the query parameters from the item's path.
Here is a table that illustrates which browser URLs would match which item URLs with the new logic:
| Item URL ➡️ <br>Browser URL ⬇️ | `/products` | `/products?c=socks` | `/products?c=` | `/products?c=socks&c=pants` | `/products?socks` |
| ---- | ---- | ---- | ---- | ---- | ---- |
| `/products` | ✅ | ❌ | ❌ | ❌ | ❌ |
| `/products?c=socks` | ✅ | ✅ | ❌ | ❌ | ❌ |
| `/products?c=pants` | ✅ | ❌ | ❌ | ❌ | ❌ |
| `/products?c=` | ✅ | ❌ | ✅ | ❌ | ❌ |
| `/products?c=socks&item=5` | ✅ | ✅ | ❌ | ❌ | ❌ |
| `/products?item=5&c=socks` | ✅ | ✅ | ❌ | ❌ | ❌ | …

feat!: match query params when determining higlighted items

---

packages/combo-box/src/vaadin-combo-box-mixin.js
packages/combo-box/test/toggling-dropdown.test.js

As described in #4148, currently the logic for restoring focus-ring does not work as expected so it can be removed.
The only case for this logic is outside click. On item click, <kbd>Esc</kbd> or <kbd>Enter</kbd> key the `<input>` doesn't lose focus.
The logic was added in https://github.com/vaadin/vaadin-combo-box/pull/599. However, latest V14 version also seems to have the issue.
Note: I quickly tried to apply the fix for a similar issue in the `vaadin-date-picker` - #4341. However, it causes a bunch of tests to fail, apparently due to validation not run on outside click with that approach (or maybe I just got it wrong).
For now, the test about outside click contains `FIXME` with a commented line, to be fixed later.
- Refactor / tests

refactor: remove not working logic, reorganize focus tests

---

packages/combo-box/src/vaadin-combo-box-light-mixin.d.ts
packages/combo-box/src/vaadin-combo-box-light-mixin.js
packages/combo-box/src/vaadin-combo-box-light.d.ts
packages/combo-box/src/vaadin-combo-box-light.js
packages/combo-box/test/typings/combo-box.types.ts

Extracted logic from `vaadin-combo-box-light` to `ComboBoxLightMixin` for reusing by the Lit based version.
- Refactor

refactor: extract combo-box-light logic to reusable mixin

---

packages/grid/src/vaadin-grid-data-provider-mixin.js
packages/grid/test/data-provider.common.js

Check for `this.__virtualizer` in grid's `clearCache` before accessing it. It's possible for it to not exist if the grid hasn't yet been attached.
Bugfix

fix: do not throw when clearing cache of an unattached grid

---

wtr-utils.js

An `execSync` call in wtr-utils keeps [failing](https://github.com/vaadin/web-components/runs/21972193519) SonarCloud code analysis. Ignore the line.
Chore

chore: ignore sonar for execSync in wtr-utils

---

packages/tabs/test/not-animated-styles.js
packages/tabs/test/scroll.test.js

Fixes #6812
Updated scrollable tabs tests to actually check that every tab is visible at some point while scrolling using buttons.
The new assertion using `getBoundingClientRect()` is rather complicated but I was unable to find a better way 🤷‍♂️ 
- Tests

test: refactor scrollable tabs tests to check for visible tabs

---

packages/date-time-picker/src/vaadin-date-time-picker.js
packages/date-time-picker/test/properties.test.js

Fixes #7153 
Note, the original property definition without default value comes from https://github.com/vaadin/vaadin-date-time-picker/pull/18 which was probably just an oversight (especially as that PR didn't contain `i18n` implementation).
The fix works because it passes a non-`undefined` value to this function:
https://github.com/vaadin/web-components/blob/08f04ee30c2048ed537cc56b2526b6d915af18d0/packages/date-picker/src/vaadin-month-calendar-mixin.js#L193-L196
Which is then used to render short day names in the month calendar:
https://github.com/vaadin/web-components/blob/08f04ee30c2048ed537cc56b2526b6d915af18d0/packages/date-picker/src/vaadin-month-calendar.js#L37-L41
- Bugfix

fix: set date-time-picker showWeekNumbers to false by default

---

packages/radio-group/test/dom/__snapshots__/radio-button.test.snap.js
packages/radio-group/test/dom/radio-button.test.js
packages/radio-group/test/radio-button.common.js

These tests were added in #2572. Since then, we added snapshot tests in #3520 and they cover `has-label` attribute.
No other components have dedicated tests for `has-label`, and corresponding logic is covered by `LabelMixin` tests.
- Test

test: remove has-label attribute tests from radio-button

---

packages/text-area/src/vaadin-text-area-mixin.d.ts
packages/text-area/src/vaadin-text-area-mixin.js
packages/text-area/test/text-area.common.js
packages/text-area/test/typings/text-area.types.ts

The PR introduces `scrollToStart` and `scrollToEnd` methods for the text-area component.
Followed by:
- https://github.com/vaadin/flow-components/pull/6041
Fixes https://github.com/vaadin/flow-components/issues/6042

feat: add scrollToStart and scrollToEnd API for text-area

---

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js

Related to https://github.com/vaadin/react-components/issues/238
This is needed to ensure that `custom-value-set` event is listed in `web-types.json`:
```
"events": [
{
"name": "validated",
"description": "Fired whenever the field is validated."
},
{
"name": "change",
"description": "Fired when the user commits a value change."
},
{
"name": "custom-value-set",
"description": "Fired when the user sets a custom value."
},
```
The `web-types.json` file is in turn used by React wrappers generator, see https://github.com/vaadin/react-components/issues/238#issuecomment-1970625835.
Note: in `vaadin-combo-box` the corresponding annotation is inherited from `ComboBoxMixin`.
- Documentation / bugfix

docs: add missing annotation for custom-value-set event

---

packages/component-base/src/virtualizer-iron-list-adapter.js

The PR reverts #6684 as I found in my [investigation](https://github.com/vaadin/flow-components/issues/5813#issuecomment-1971434398) that it has no impact on the issue (or not anymore) and the [related integration test](https://github.com/vaadin/flow-components/pull/5621) passes without it. The issue will be fixed by https://github.com/vaadin/web-components/pull/7165 instead.

Revert "fix: flush virtualizer until physical count stabilizes (#6684)"

---

packages/grid/src/vaadin-grid-mixin.js
packages/grid/test/column-auto-width.common.js

The PR prevents too early column width recalculation during the grid's initialization when some row elements don't have an index property yet. This can happen if the recalculation is triggered as a result of the data provider responding synchronously to a page request created in the middle of the virtualizer update loop. In this case, rows after the one that triggered the page request may not have an index property yet. The lack of index prevents `_onDataProviderPageReceived` from requesting children for these rows, resulting in the loading state being set to `false` and the recalculation beginning before all the data is actually loaded. Note, rows without index get updated in later iterations of the virtualizer update loop, so the grid eventually reaches a stable state.
> [!NOTE]
> The …

fix: delay column width recalculation until all rows have index

---

packages/input-container/theme/lumo/vaadin-input-container-styles.js

Fixes #7126
Can be tested with the dev page by setting the custom CSS property:
```html
<vaadin-text-field style="--vaadin-input-field-height: 30px"></vaadin-text-field>
```
- Bugfix

fix: use correct custom CSS property for input field height

---

packages/grid/src/vaadin-grid.js
packages/grid/test/column-auto-width.test.js

A manual cherry-pick of the following fix to 23.3:
- #7165
Fixes https://github.com/vaadin/flow-components/issues/5813

fix: delay column width recalculation until all rows have index (#7165) (CP: 23.3)

---

packages/grid/src/vaadin-grid-data-provider-mixin.js

Making sure that the row's index doesn't exceed the flat size before requesting data for that row seems unnecessary, as (1) grid nowadays hides rows synchronously on flat size change, and (2) `_getItem` is only called for rows received from `_getRenderedRows` which throws away hidden rows.

refactor: remove unnecessary check from DataProviderMixin

---

packages/combo-box/test/basic.common.js
packages/combo-box/test/interactions.common.js
packages/combo-box/test/selecting-items.common.js

Currently, clear button tests are scattered across several files, especially `basic.test.js` and `selecting-items.test.js`
Some of them are duplicating, e.g. check for not opening overlay on clear button click. This PR unifies those tests.
- Test

test: combine clear-button tests into single suite

---

packages/crud/src/vaadin-crud-controllers.js
packages/crud/src/vaadin-crud.js
packages/crud/test/crud-buttons.test.js

Part of https://github.com/vaadin/flow-components/issues/6080
This PR adds a flag that can be set by the Flow counterpart in the `Crud` constructor like this:
```java
getElement().setProperty("_noDefaultButtons", true);
```
As a result, the web component will not create default buttons and expect the server to provide them.
To do this, we set `tagName` in `SlotController` constructor to `null` (see e.g. `HelperController`).
- Bugfix

fix: allow to prevent creating default slotted buttons

---

packages/side-nav/src/vaadin-side-nav-item.js
packages/side-nav/test/side-nav-item.test.js

This PR expands the parent side nav items when an item is set `current`. The expanding is done recursively, starting from the root level.
Fixes #7182

feat: expand parent items when item is set current

---

packages/grid/src/vaadin-grid-tree-toggle-mixin.js
packages/grid/test/tree-toggle.common.js

The toggle click listener was being added in `ready()`, which caused it to not be the first to be invoked in the listener order. This caused the `expanded` state to be updated after the external click listeners were invoked, which rendered any operation based on the `expanded` state at that point to be incorrect. 
This PR moves adding the internal toggle click listener to the constructor. This ensures that the internal click listener is the first within the listener order.
Fixes #7163

fix: add click listener in constructor to ensure listener order

---

packages/checkbox/src/vaadin-checkbox.d.ts
packages/checkbox/test/typings/checkbox.types.ts

When extracting `CheckboxMixin` in #5563, I missed to update `vaadin-checkbox.d.ts` to use it. This PR fixes that.
- Documentation / typings fix

docs: update vaadin-checkbox typings to use correct mixin

---

packages/context-menu/src/vaadin-contextmenu-items-mixin.js
packages/context-menu/test/items.common.js
packages/menu-bar/test/sub-menu.common.js

Fixes #7202
This change ensures that items on sub-menu reopening do not preserve old `tabindex` attribute value. Previously, using `item.text` the items were re-generated and list-box reset their tabindex, but with `item.component` it didn't happen.
Also related to #924 which requested resetting focus in list-box specifically for `vaadin-context-menu`:
> This would at least help when used inside vaadin-context-menu, where the common case is that when the menu opens the focus should be on the first item in the menu.
- Bugfix

fix: reset tabindex to -1 when initializing menu item

---

packages/crud/src/vaadin-crud-controllers.js
packages/crud/test/crud-buttons.test.js

Fixes https://github.com/vaadin/flow-components/issues/6123
Added a check to detect if button has `theme` attribute set and if so, do not override it by the default one.
- Bugfix

fix: do not override theme attribute set on slotted buttons

---

README.md

The current link points to the page that says that it has moved. This PR fixes that.
Also replaced no longer working [chat link](https://vaad.in/chat) with the Forum.

chore: fix contributing guide and chat links in README

---

packages/select/README.md
packages/side-nav/README.md

The `vaadin-select` had incorrect `@vaadin/vaadin-select` npm version badge in README (the one that refers to Vaadin 23), and `vaadin-side-nav` was apparently copied from there by mistake. This PR fixes that.

chore: fix incorrect npm version badges in READMEs

---

packages/tabsheet/src/vaadin-tabsheet-mixin.js
packages/tabsheet/test/tabsheet.test.js

Fixes https://github.com/vaadin/flow-components/issues/6072
Here's the code example to reproduce the issue and test the fix:
```html
<vaadin-tabsheet>
<vaadin-tabs slot="tabs">
<vaadin-tab>Tab 1</vaadin-tab>
<vaadin-tab>Tab 2</vaadin-tab>
</vaadin-tabs>
<div tab="tab-1">Panel 1</div>
<div tab="tab-2">Panel 2</div>
</vaadin-tabsheet>
```
Put this to dev page and try to set `id` on the first `vaadin-tab` to `tab-1`.
- Bugfix
Initially, I was thinking about adding a warning for `vaadin-tab` elements without `id` attribute set. However, Flow does not set `id` attribute when using `setVisible(false)` and it's by design, so in this case the warning would be redundant.
This fix can be also considered as "feature", as it also adds an option to un-link tab with panel by setting `id` to `null`.

fix: observe tabs ID attribute changes and update panels

---

packages/tabsheet/src/vaadin-tabsheet.js
packages/tabsheet/test/tabsheet.test.js

Manual cherry-pick of #7201 to `24.3` branch (where the `TabSheetMixin` doesn't exist).
- Cherry-pick

fix: observe tabs ID attribute changes and update panels (#7201) (CP: 24.3)

---

dev/virtualizer.html
packages/component-base/src/virtualizer-iron-list-adapter.js
packages/component-base/test/virtualizer-unlimited-size.test.js
packages/component-base/test/virtualizer.test.js
packages/grid/test/basic.common.js

The PR reverts #5650 due to several regressions mentioned below, and also adds tests that should prevent such regressions in the future.
Fixes https://github.com/vaadin/web-components/issues/7079
Fixes https://github.com/vaadin/web-components/issues/7186
Fixes https://github.com/vaadin/web-components/issues/7160

Revert "refactor: avoid unnecessary re-renders on virtualizer size change (#5650)"

---

packages/a11y-base/src/keyboard-direction-mixin.js
packages/a11y-base/src/list-mixin.js
packages/a11y-base/test/list-mixin.test.js
packages/context-menu/test/items.common.js
packages/menu-bar/test/sub-menu.common.js

Fixes #7228
The logic in `focus()` method of `ListMixin` is problematic since it focuses first item without checking if it's disabled.
Updated to use logic from `KeyboardDirectionMixin` and added `vaadin-context-menu` and `vaadin-menu-bar` tests.
- Bugfix
Setting `tabindex` to `-1` on all the items is done since #7203 which was a fix for #7202. While that issue could be fixed in a different way, IMO the approach used in this PR was correct. The current PR should be a proper fix for #7142.

fix: focus first non-disabled item if all items have tabindex -1

---

packages/side-nav/src/vaadin-side-nav-item.d.ts
packages/side-nav/src/vaadin-side-nav-item.js
packages/side-nav/src/vaadin-side-nav.js
packages/side-nav/test/navigation-callback.test.js
packages/side-nav/test/side-nav-item.test.js

Allows to exclude side nav items from client-side routing. This effectively allows the Flow component to control whether the item participates in client-side routing in Vaadin apps. For integration with other client-side routers, the `onNavigate` hook is not called for items that have router-ignore enabled.
Part of https://github.com/vaadin/flow-components/issues/5189
-  Feature

feat: add router-ignore API to side nav item

---

packages/message-list/src/vaadin-message-list.js
packages/message-list/test/message-list.test.js

Fixes #6544
Currently, `vaadin-message-list` re-renders `vaadin-message` items using Lit `render` function and that discards slotted `vaadin-avatar` elements created by `SlotController`. Updated to include `vaadin-avatar` to the Lit template.
- Bugfix

fix: render message avatars with Lit to keep them on items update

---

packages/grid-pro/test/keyboard-navigation.common.js

The test setup doesn't work properly at the moment as drag and drop for Grid Pro is broken as mentioned in #7229. The test passes in CI, but fails locally. Let's disable it for now.
Should be restored as part of https://github.com/vaadin/web-components/issues/7229

test: disable invalid test

---

packages/rich-text-editor/src/vaadin-rich-text-editor-mixin.js
packages/rich-text-editor/test/basic.common.js

Fixes #7249
When adding link, the `change` event was not fired by `vaadin-rich-text-editor`. Here's what happened:
- editor gets focus as a result of `this._editor.format('link', link, SOURCE.USER)`,
- the editor content `focus` event listener calls `_cleanToolbarState()` immediately,
- in `value` change observer, no change event due to the toolbar in "default" state.
Added a check for `_linkEditing` (which corresponds to the link dialog `opened` property) as a fix.
Note: when removing the `focus` listener completely, all the tests still pass on `main` branch 🙈 
- Bugfix

fix: fire change event on hyperlink edit, update test timings

---

integration/tests/overlay-focus-trap.test.js
packages/dialog/test/dialog.common.js
packages/overlay/src/vaadin-overlay-styles.js
packages/overlay/test/focus-trap.common.js

Fixes #7245
- Bugfix
https://github.com/vaadin/web-components/assets/10589913/7470b381-c087-4116-9c37-a4b2089ed39f
https://github.com/vaadin/web-components/assets/10589913/b13327e3-0a51-4e04-a1a8-e885c04f0683
Test changes are due to the fact that previously `getFocusableElements()` was sometimes called with closed overlay.
As the helper used internally only checked for the element to be hidden directly, it returned the focusable elements.
Now when the CSS is updated to set `display: none` on the overlay part explicitly, those tests started to fail.
Also, some tests have been adjusted to use proper timings (so that the overlay doesn't get detached too early).

fix: set display none on overlay part to fix Safari 17.4 issue

---

packages/combo-box/src/vaadin-combo-box-data-provider-mixin.js
packages/combo-box/src/vaadin-combo-box-scroller-mixin.js

The `_shouldSkipIndex` workaround was introduced in https://github.com/vaadin/vaadin-combo-box/pull/978 at a time combo-box had its own scroll restoration logic. However, this logic was later removed when replacing iron-list with virtualizer in https://github.com/vaadin/web-components/pull/2339, which makes the workaround also obsolete. Note, there is no such workaround in grid.

refactor: drop obsolete scroller workaround

---

packages/combo-box/src/vaadin-combo-box-data-provider-mixin.js
packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js

The PR moves the logic that prevents  data provider requests for the readonly state from `_shouldLoadPage` to `_shouldFetchData` in multi-select-combo-box, as this seems more logical considering the method name.

refactor: use _shouldFetchData to prevent requests for readonly

---

packages/checkbox-group/src/vaadin-checkbox-group-styles.d.ts
packages/checkbox-group/src/vaadin-checkbox-group-styles.js
packages/checkbox-group/src/vaadin-checkbox-group.js

Extracted `vaadin-checkbox-group` base styles to CSS literal for using by the Lit version.
- Refactor

refactor: extract checkbox-group styles to reusable css literal

---

packages/combo-box/src/vaadin-combo-box-data-provider-mixin.js

The PR removes an obsolete check for `filteredItems` in `_shouldLoadPage`. This check became unnecessary after #7262 which stopped `_shouldLoadPage` from being called in `_ensureFirstPage` on open when no data provider is set. Note, when a data provider is set, `filteredItems` are guaranteed to be an array.

refactor: remove obsolete check for filteredItems

---

packages/component-base/src/virtualizer-iron-list-adapter.js
packages/component-base/test/virtualizer-unlimited-size.test.js

The PR fixes the bug that allowed reaching items beyond the set size when the scroll target had a border or horizontal scrollbar i.e. in situations where the scroll target's `clientHeight` didn't equal its `offsetHeight`.
Fixes https://github.com/vaadin/web-components/issues/7188

fix: calculate vidxOffset correctly when clientHeight != offsetHeight

---

packages/component-base/src/virtualizer-iron-list-adapter.js
packages/component-base/test/virtualizer-unlimited-size.test.js

Cherry-picks to 24.3:
- https://github.com/vaadin/web-components/pull/7227
- https://github.com/vaadin/web-components/pull/7268
Fixes https://github.com/vaadin/web-components/issues/7188

fix: calculate vidxOffset correctly when clientHeight != offsetHeight (#7268) (CP: 24.3)

---

packages/grid/src/vaadin-grid-mixin.js
packages/grid/test/keyboard-navigation-cell-button.common.js

Fixes #7267
The regression was caused by the fact that `_createCell(tagName, column)` resulted in `column._focusButtonMode` to be applied to header and footer cells, while it's supposed to be only used by the body cells (e.g. in `vaadin-grid-pro`).
Visual tests can't catch this as we run them on Windows and the "focus button" mode is specific to Mac OS 😕 
- Bugfix
The logic of “focus button mode” is currently a bit fragile since it relies on the second argument of `_createCell()` being passed to body cells only (not header / footer / details). Also, I don't really like copy-pasting of `addEventListener()`.

fix: only create focus button mode div for body cells

---

packages/grid-pro/test/keyboard-navigation.common.js
packages/grid/src/vaadin-grid-column-reordering-mixin.js
packages/grid/test/column-reordering.common.js

This is not to a GridPro edit column issue, but can also be reproduced using regular columns with `_focusButtonMode` property. When focus button mode is used, the cell is content is wrapped into a div. Because of this, the cell from point is not correctly determined during tracking events.
This PR adds another clause for extracting the cell from point, which enables reordering focus button mode columns.
Fixes #7229

fix: handle focus button mode columns for reordering

---

packages/grid/src/vaadin-grid-filter-element-mixin.js
packages/grid/test/filtering.common.js

Fixes #7247 
Updated the `vaadin-grid-filter` logic to remove workaround added when converting to Lit.
- Bugfix

fix: update vaadin-grid-filter to use input event instead of value-changed

---

packages/grid/src/vaadin-grid-filter-column-mixin.js

The PR removes the `_filterValue` property along with its related listeners from `<vaadin-grid-filter-column />`. This property seems to be useless, as the grid listens for `filter-changed` [directly](https://github.com/vaadin/web-components/blob/ac5c22e8ae9a78f3a0673d989f668416d4b6b730/packages/grid/src/vaadin-grid-filter-mixin.js#L25-L26) on `<vaadin-grid-filter />`.

refactor: remove useless _filterValue property and related listeners

---

packages/select/src/vaadin-select-base-mixin.js
packages/select/test/select.common.js

Fixes #7286
The PR where the change was introduced contains some clarification: https://github.com/vaadin/web-components/pull/6256/files#r1276178338
However, it turns out that removal of `this.opened = false` was problematic as it resulted in the regression.
- Bugfix

fix: close select overlay when clicking already selected item

---

packages/overlay/src/vaadin-overlay-position-mixin.js
packages/overlay/test/position-mixin-listeners.test.js

The PR adds listeners for visual viewport scroll and resize events to update the overlay's position accordingly. Based on my testing, the visual viewport events are triggered in all scenarios in which the corresponding window events are triggered, so I completely replaced the window scroll and resize listeners with the visual viewport ones.
The [Visual Viewport API](https://developer.mozilla.org/en-US/docs/Web/API/Visual_Viewport_API) has [good support](https://caniuse.com/mdn-api_visualviewport) across all browsers supported by Vaadin 24:
Fixes https://github.com/vaadin/web-components/issues/7214

fix: update position on visual viewport scroll and resize

---

packages/overlay/src/vaadin-overlay-position-mixin.js
packages/overlay/test/position-mixin-listeners.test.js

Follow-up to #7279 
After merging the above PR, I discovered that for some reason, `scroll` event isn't fired on `window.visualViewport` on desktop browsers, so e.g. `vaadin-combo-box` overlay doesn't reposition on scroll with that change:
https://github.com/vaadin/web-components/assets/10589913/cc15e452-fb30-4bad-9805-c484e590ae3e
Restored listening to `scroll` event on the `document` in addition to `window.visualViewport` (used by iOS).
- Bugfix

fix: use document scroll instead of the visual viewport

---

packages/select/theme/lumo/vaadin-select-styles.js

Fixes #7234
When introducing custom CSS properties for font-weight, we missed to use it in `vaadin-select`.
Regarding font-size property, it is used but slotted `vaadin-select-item` overrides its value.
Note: I'm not sure why font-weight is set to `500` for select and not `400` like in text-field etc.
- Bugfix

fix: make Lumo font custom properties work for vaadin-select

---

packages/select/src/vaadin-select-base-mixin.js
packages/select/test/select.common.js

Fixes #7243
Restored `_hasContent` check which was removed by mistake in #2282.
Can be tested with the following snippet:
```html
<vaadin-select placeholder="Select size"></vaadin-select>
<script>
const select = document.querySelector('vaadin-select');
select.items = [
{ label: '', value: '' },
{ component: 'hr' },
{ label: 'XS (out of stock)', value: 'xs', disabled: true },
{ label: 'S', value: 's' },
{ label: 'M', value: 'm' },
{ label: 'L', value: 'l' },
{ label: 'XL', value: 'xl' },
];
</script>
```
Without a fix, selecting first (empty) item makes it show in the value button, which is not a desirable behavior.
The correct behavior in this case is to not attach selected item and show the placeholder item instead.
- Bugfix

fix: show placeholder item when an empty item is selected

---

packages/date-picker/test/value-commit.common.js

This PR updates the tests to use the formatter from date picker. The reason is that the current formatter in the test does not take time zones into consideration. This leads to tests failing when time zone is not GMT.
Extracted from https://github.com/vaadin/web-components/pull/7293 as a follow-up to a [comment](https://github.com/vaadin/web-components/pull/7293#discussion_r1555664979).

test: use formatter from date picker in tests

---

packages/date-picker/src/vaadin-date-picker-mixin.js
packages/date-picker/test/value-commit.common.js

Currently, when
1. the date picker has a value
2. an invalid value is entered
3. date picker overlay is closed using `escape`
the input is not reverted and the date picker is validated using the unparsable input.
This PR reverts the input value to the last selected date if the overlay is closed using `escape`.
!!! This fix was tested with the Flow counterpart. However, if any regressions occur regarding the validation chain, this PR can be the culprit. !!!
Fixes #4354

fix: revert input on overlay close by escape

---

packages/grid/src/vaadin-grid-scroll-mixin.js
packages/grid/test/column-rendering.common.js

When a new column is added to a grid with lazy column rendering, some of the listeners are invoked before the column tree is updated and the sizer cells are assigned. This creates problems when the sizer cell is needed for calculations. A new column currently cannot be appended to a grid with lazy column rendering. Those calculations involving the sizer cells are made again after the node observer is invoked and the column tree is updated. Therefore, it seems like they can be safely skipped.
This PR skips the calculations that require sizer cells if they are not assigned yet.
Fixes #7281

fix: check if sizer cells are assigned for lazy column rendering

---

packages/overlay/src/vaadin-overlay-mixin.js
packages/overlay/test/renderer.common.js

This PR is needed for `vaadin-combo-box` Lit version to prevent issue with re-creating `vaadin-combo-box-scroller`.
Currently with the Lit version, setting `overlay.renderer` triggers observer in `OverlayMixin` which [clears `innerHTML`](https://github.com/vaadin/web-components/blob/900a453b3dab37cd20f8132aa440ad3a357bde48/packages/overlay/src/vaadin-overlay-mixin.js#L228-L234) without checking for the old renderer. Then on overlay open, the scroller is re-attached by calling `appendChild()`.
This isn't the case in Polymer version where observers run differently and clearing `innerHTML` is called before the first renderer invocation by `requestContentUpdate()`. Note: changing all the properties to use `sync: true` doesn't help.
While `vaadin-combo-box` Lit tests pass on the main branch, …

fix: only clear overlay root when assigning a renderer if needed

---

integration/tests/component-relayout-page.test.js
packages/context-menu/src/vaadin-context-menu-mixin.js
packages/context-menu/test/dom/__snapshots__/context-menu.test.snap.js

Related to https://github.com/vaadin/web-components/issues/7271
Because of the error, the `opened-changed` event listener also called `__alignOverlayPosition()` when `opened` was set to `false` (initial value). This triggers some measurements of `vaadin-context-menu-overlay` which [force re-layout](https://gist.github.com/paulirish/5d52fb081b3570c81e3a).
Note: this PR alone is not enough to fix `vaadin-menu-bar`, I'll create another PR for its logic to keep fixes granular.
- Bugfix

fix: do not measure overlay boundaries when menu is closed

---

packages/checkbox/src/vaadin-checkbox.d.ts
packages/checkbox/test/typings/checkbox.types.ts

Follow-up to #7285
Added missing event types for `invalid-changed` and `validated` event (reported by React components release build):
```
[dts] src/generated/Checkbox.ts(8,46): error TS2339: Property 'validated' does not exist on type 'CheckboxEventMap'.
[dts] src/generated/Checkbox.ts(11,51): error TS2339: Property 'invalid-changed' does not exist on type 'CheckboxEventMap'.
```
- Bugfix

fix: add missing invalid-changed and validated event types

---

packages/crud/src/vaadin-crud-dialog.js
packages/crud/test/a11y.test.js

Finding from https://github.com/vaadin/web-components/pull/7264#issuecomment-2019904617
When decoupling `vaadin-crud-dialog` from `vaadin-dialog`, I missed to set `role` attribute. This PR fixes that.
- Bugfix

fix: set role attribute on the CRUD edit dialog overlay

---

integration/tests/component-relayout-page.test.js
packages/menu-bar/src/vaadin-menu-bar-mixin.js
packages/menu-bar/test/visual/lumo/menu-bar.test.js
packages/menu-bar/test/visual/material/menu-bar.test.js

Related to #7271
- Bugfix
This change will require a fix to `menuBarConnector.js` to make sure `menubar._buttons` array is ready:
```diff
generateItems: tryCatchWrapper((nodeId) => {
if (!menubar.shadowRoot) {
// workaround for https://github.com/vaadin/flow/issues/5722
setTimeout(() => menubar.$connector.generateItems(nodeId));
return;
}
+       if (!menubar._container) {
+         // Menu-bar defers first buttons render to avoid re-layout
+         // See https://github.com/vaadin/web-components/issues/7271
+         queueMicrotask(() => menubar.$connector.generateItems(nodeId));
+         return;
+       }
```

fix: postpone menu-bar initial render to prevent re-layout

---

packages/grid-pro/src/vaadin-grid-pro-edit-column-mixin.d.ts
packages/grid-pro/src/vaadin-grid-pro-edit-column-mixin.js
packages/grid-pro/src/vaadin-grid-pro-inline-editing-mixin.js
packages/grid-pro/test/edit-column.common.js

Adds a `isCellEditable` API to `vaadin-grid-pro-edit-column` that allows to disable editing for individual cells, or whole rows by applying the same function to all edit columns. If the function returns false for a cell it:
- Prevents editing the cell
- Does not apply the `navigating` mode to the grid when clicking on the cell (so does not show focus ring)
- Does not add the `editable-cell` part name
- Skips over that cell when trying to navigate from one cell editor to the next with Tab or Enter. If there are multiple non-editable cells, the logic should skip over all of those until it finds the next editable cell.
Part of https://github.com/vaadin/flow-components/issues/4524
AC: https://github.com/vaadin/platform/issues/5177

feat: disable editing for individual cells

---

packages/dialog/src/vaadin-dialog.js
packages/dialog/src/vaadin-lit-dialog.js

The PR updates the dialog to set the `role` attribute directly in the template rather than in the `ready()` method.

refactor: set role attribute directly in template

---

packages/combo-box/src/vaadin-combo-box-scroller-mixin.js
packages/combo-box/test/lazy-loading.common.js

Fixes a regression from #7277 
In `vaadin-combo-box`, we have a logic that clears scroller items on close:
https://github.com/vaadin/web-components/blob/2efeeebbeabddfde14c845ee4098f9e62e352ffe/packages/combo-box/src/vaadin-combo-box-mixin.js#L507-L508
In the PR linked above, this behavior was broken by the `items` observer change.
Added a test to ensure visible items count is reset (which is a side effect of clearing items).
This seems to be the easiest way to test the change without accessing `__virtualizer` API.
- Bugfix

fix: allow to set virtualizer items when not opened

---

integration/tests/menu-bar-tooltip.test.js
packages/menu-bar/src/vaadin-menu-bar-mixin.js

Fixes https://github.com/vaadin/flow-components/issues/5614
The issue was caused by the fact that `vaadin-menu-bar` uses `vaadin-tooltip` in manual mode, where the corresponding [listener](https://github.com/vaadin/web-components/blob/2efeeebbeabddfde14c845ee4098f9e62e352ffe/packages/tooltip/src/vaadin-tooltip-mixin.js#L700) added automatically doesn't work. Fixed this by adding event listener manually and copying the corresponding logic.
- Bugfix

fix: hide menu-bar tooltip on overlay mouseleave to outside

---

packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js
packages/grid/test/keyboard-navigation.common.js

The [block](https://github.com/vaadin/web-components/blob/main/packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js#L816-L824) in the listener `_onFocusin` assumes that if the root target is the top/bottom of the grid, it is the result of a tab/shift-tab action. However, it is also possible that it is the result of a click. In this case, the focus should not be moved.
This PR updates the logic to move focus only if it is not caused by a click.
Fixes #2911

fix: do not move focus when focused in on grid via clicking

---

integration/tests/component-relayout-page.test.js
packages/combo-box/src/vaadin-combo-box-scroller-mixin.js
packages/combo-box/test/lazy-loading.test.js

Manual cherry-pick of #7277 to `24.3` branch with a fix from #7325
- Cherry-pick

fix: postpone virtualizer creation until overlay is opened (#7277) (CP: 24.3)

---

integration/tests/menu-bar-tooltip.test.js
packages/menu-bar/src/vaadin-menu-bar-interactions-mixin.js

Cherry-pick of #7322 to `23.3` branch.
- Cherry-pick

fix: hide menu-bar tooltip on overlay mouseleave to outside (#7322) (CP: 23.3)

---

integration/tests/menu-bar-tooltip.test.js
packages/menu-bar/src/vaadin-menu-bar-interactions-mixin.js

Cherry-pick of #7322 to `23.5` branch.
- Cherry-pick

fix: hide menu-bar tooltip on overlay mouseleave to outside (#7322) (CP: 23.5)

---

packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js
packages/grid/test/keyboard-navigation.test.js

Back-port of the [fix](https://github.com/vaadin/web-components/pull/7323) for the grid horizontal scroll click [issue](https://github.com/vaadin/web-components/issues/2911).

fix: do not move focus when focused in on grid via clicking (#7323)

---

packages/select/src/vaadin-lit-select.js
packages/select/src/vaadin-select-base-mixin.js
packages/select/src/vaadin-select-overlay.js
packages/select/test/pre-opened-polymer.test.js

Fixes https://github.com/vaadin/flow-components/issues/6148
See also https://github.com/vaadin/web-components/pull/4610 for a similar `vaadin-tooltip` fix.
When `opened` is set to the select in the template as an attribute, in the Polymer version overlay opens before the `ready()` callback is called. The `opened` is then [reset to `false`](https://github.com/vaadin/web-components/blob/8e5223bcb61a5561fd984db5d11b31a73ec98eaa/packages/select/src/vaadin-select-base-mixin.js#L355-L357) as `_overlayElement` is empty, but due to the animation the overlay doesn't close immediately and is still under `<body>` by the time `querySelector()` is called, so the error is thrown.
Lit version doesn't have this issue since by the time `ready()` is called on the `vaadin-select`, its overlay is not yet …

fix: do not throw error when opened is set before adding to DOM

---

packages/grid/src/vaadin-grid-data-provider-mixin.js
packages/grid/test/data-provider.common.js
packages/grid/test/helpers.js

The PR causes grid to update all rendered rows once it receives a page response that affects the flat size. This guarantees that all pages associated with the rendered rows are loaded.
> [!WARNING]
> It's been decided to wait until https://github.com/vaadin/flow/issues/19006 is fixed, as it's currently causing interference in many scenarios related to the current regression, making it difficult to distinguish the causes.
Fixes https://github.com/vaadin/web-components/issues/7097
Bugfix

fix: update all rendered rows on flat size change from page response

---

packages/crud/test/crud-editor.test.js
packages/crud/theme/lumo/vaadin-crud-styles.js
packages/crud/theme/material/vaadin-crud-styles.js

The problem was that the focus ring element that covers the editor was receiving pointer events so the wheel events were emitted on it instead of the underlying editor:
https://github.com/vaadin/web-components/assets/1222264/b9a9617a-ea8a-43e7-86d5-1683308789e1
This PR hides the crud editor focus ring from pointer events.
Fixes https://github.com/vaadin/web-components/issues/6693
Bugfix

fix: hide crud editor focus ring from pointer events

---

packages/notification/test/animation.test.js

The animation tests for `<vaadin-notifiction>` need cleaning up. In their current state, they rely on the `duration` timing to close the notifications around the time the test case starts.
This PR refactors the tests to use -1 for `duration` and use `notification.close()` to explicitly close the notifications when necessary. It also removes the custom CSS in favor of using inline styles.
This is a prerequisite for fixing https://github.com/vaadin/web-components/issues/6878
Tests

test: clean up notification animation tests

---

packages/notification/src/vaadin-notification.js
packages/notification/test/animation.test.js

This PR makes `<vaadin-notification>` use a shared "animationend" listener reference for the opening and closing animations. Using a shared reference makes it possible to remove any active listeners in case an animation starts while another one is still running.
Fixes https://github.com/vaadin/web-components/issues/6878
Bugfix

fix: share animationend listener reference in notification

---

packages/grid/test/keyboard-navigation.common.js

The `should tab through the elements in order` test in grid is especially flaky when running locally. This is an attempt to make the test less flaky.
Tests

test: reduce flakiness in grid element tabbing tests

---

packages/checkbox-group/package.json
packages/checkbox-group/src/vaadin-checkbox-group-mixin.js
packages/checkbox-group/src/vaadin-lit-checkbox-group.d.ts
packages/checkbox-group/src/vaadin-lit-checkbox-group.js
packages/checkbox-group/test/checkbox-group-lit.test.js
packages/checkbox-group/test/checkbox-group-polymer.test.js
packages/checkbox-group/test/checkbox-group.common.js
packages/checkbox-group/test/validation-lit.test.js
packages/checkbox-group/test/validation-polymer.test.js
packages/checkbox-group/test/validation.common.js

Depends on #7258
Depends on #7259
- Experiment

experiment: add LitElement based version of checkbox-group

---

packages/combo-box/test/lazy-loading.common.js

Extracted from https://github.com/vaadin/web-components/pull/7044
The PR adds a few missing unit tests related to combo-box data provider.

test: add missing data provider tests

---

web-test-runner-lumo.config.js

Updated Chrome version in Lumo visual tests to 110. Tested locally and all tests passed:
```
Windows 10 chrome 110: |██████████████████████████████| 64/64 test files | 742 passed, 0 failed
Finished running tests in 1024.8s, all tests passed! 🎉
✨  Done in 1031.63s.
```
Related to https://github.com/vaadin/web-components/pull/7347#discussion_r1574380638 

chore: update Chrome version in Lumo visual tests

---

integration/tests/dialog-menu-bar.test.js
packages/menu-bar/src/vaadin-menu-bar-mixin.js
packages/menu-bar/test/visual/material/menu-bar.test.js

Fixes #7338
Note: the original issue appears to be caused by the Lumo dialog animation, so I only added the integration test.
- Bugfix

fix: detect overflow correctly when used in a dialog

---

integration/tests/dialog-menu-bar.test.js
packages/menu-bar/src/vaadin-menu-bar-mixin.js
packages/menu-bar/test/visual/material/menu-bar.test.js

Manual cherry-pick of #7347 to `24.3` branch (there was a conflict due to `reverseCollapse` feature on `main` branch).
- Cherry-pick

fix: detect overflow correctly when used in a dialog (#7347) (CP: 24.3)

---

packages/checkbox-group/theme/lumo/vaadin-checkbox-group-styles.js

Updated `vaadin-checkbox-group` Lumo label color styles to align with the input fields and `vaadin-radio-group`.
- Bugfix

fix: do not modify readonly group label color on hover

---

packages/message-input/src/vaadin-message-input.js
packages/message-input/test/message-input.test.js

Related to https://github.com/vaadin/flow-components/issues/6243
This aligns the behavior of `vaadin-message-input` with the `vaadin-date-time-picker` to focus the first focusable element. 

feat: add missing focus method to message-input

---

packages/date-time-picker/src/vaadin-date-time-picker.js
packages/date-time-picker/test/basic.test.js

Added logic and test to ensure `document.createElement('vaadin-date-time-picker').focus()` doesn't throw.
- Bugfix

fix: do not throw on focus before adding to the DOM

---

packages/split-layout/src/vaadin-split-layout-mixin.js
packages/split-layout/test/split-layout.common.js

Fixes https://github.com/vaadin/flow-components/issues/6248
Currently, when removing an element from split-layout, the `_primaryChild` or `_secondaryChild` reference isn't updated.
As a result, `track` event is handled and `splitter-dragend` is fired, which is then handled by the Flow counterpart.
The error is thrown by [this logic](https://github.com/vaadin/flow-components/blob/2b4d418cb8412382eebfc9b1156d2de1cb54e0e7/vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/main/java/com/vaadin/flow/component/splitlayout/SplitLayout.java#L344-L345) which relies on both primary and secondary components to be available.
Added logic to clear the reference along with removal of the corresponding slot and a test to check the event isn't fired.
- Bugfix

fix: clear reference to element removed from split-layout

---

packages/combo-box/src/vaadin-combo-box-scroller-mixin.js

There seems to be no need to flush the virtualizer after updating its size in combo-box. The flush was added in https://github.com/vaadin/web-components/pull/2339 when the iron-list was replaced with the virtualizer. However, all tests for both web-components and flow-components pass without it.

refactor: do not flush virtualizer after updating its size

---

packages/combo-box/src/vaadin-combo-box-scroller-mixin.js
packages/combo-box/test/external-filtering.common.js

The PR gathers all instances of `virtualizer.size = this.items.length` and replaces them with a single one in the combo-box scroller's `requestContentUpdate`.

fix: update virtualizer size on requestContentUpdate

---

dev/tabs.html
packages/tabs/package.json
packages/tabs/src/vaadin-lit-tab.d.ts
packages/tabs/src/vaadin-lit-tab.js
packages/tabs/src/vaadin-lit-tabs.d.ts
packages/tabs/src/vaadin-lit-tabs.js
packages/tabs/src/vaadin-tabs-mixin.js
packages/tabs/test/scroll-lit.test.js
packages/tabs/test/scroll-polymer.test.js
packages/tabs/test/scroll.common.js
packages/tabs/test/tab-lit.test.js
packages/tabs/test/tab-polymer.test.js
packages/tabs/test/tab.common.js
packages/tabs/test/tabs-lit.test.js
packages/tabs/test/tabs-polymer.test.js
packages/tabs/test/tabs.common.js
packages/tabs/theme/lumo/vaadin-lit-tab.js
packages/tabs/theme/lumo/vaadin-lit-tabs.js
packages/tabs/theme/material/vaadin-lit-tab.js
packages/tabs/theme/material/vaadin-lit-tabs.js

Added a version of `vaadin-tabs` and `vaadin-tab` based on LitElement and updated tests.
- Experiment

experiment: add LitElement based version of tabs

---

packages/component-base/src/overlay-class-mixin.js
packages/component-base/test/overlay-class-mixin.test.js

Fixes https://github.com/vaadin/flow-components/issues/6274
- Bugfix

fix: do not throw when overlayClass is set to empty string

---

packages/grid/src/vaadin-grid-mixin.js
packages/grid/test/tree-toggle.common.js

Added a check to `_updateItem()` method and a test to verify that removing the `vaadin-grid-tree-column` doesn't throw.
This fixes the following problem that was [reported internally](https://vaadin.slack.com/archives/C3TGRP4HY/p1715082136231939?thread_ts=1715077041.083499&cid=C3TGRP4HY):
```
TypeError: Cannot read properties of undefined (reading 'itemHasChildrenPath')
at GridTreeColumn.__defaultRenderer (http://localhost:8080/VAADIN/@fs/Users/serhii/vaadin/web-components/node_modules/@vaadin/grid/src/vaadin-grid-tree-column-mixin.js?t=1715085767730&v=57315da2:51:56)
at http://localhost:8080/VAADIN/@fs/Users/serhii/vaadin/web-components/node_modules/@vaadin/grid/src/vaadin-grid-mixin.js?t=1715086641624&v=57315da2:955:26
at Array.forEach (<anonymous>)
at iterateChildren …
```

fix: do not call renderer for disconnected columns

---

README.md
packages/grid/README.md

Update the grid readme example not to use em units. See https://github.com/vaadin/web-components/issues/6974#issuecomment-1867309522
Also, remove `theme="row-dividers"` since grid doesn't have such a theme variant.
Documentation

docs: update the grid readme example not to use em units

---

packages/rich-text-editor/test/a11y.common.js
packages/rich-text-editor/test/basic.common.js

Removed `'use strict'` lines that were added when converting to Polymer 3 in https://github.com/vaadin/vaadin-rich-text-editor/pull/173.
We don't need them as our tests are implemented using ES modules and therefore use strict mode automatically.
- Test

test: remove not needed use strict from unit tests

---

packages/rich-text-editor/src/vaadin-rich-text-editor-mixin.js
packages/rich-text-editor/test/basic.common.js

Extracted from #7392
The logic for stripping `<span>` elements introduced in #6434 was intended to only remove empty spans, but currently it also removes elements with `style` attribute, so that `color` and `background` styles get lost. This PR fixes that.
- Bugfix

fix: do not strip style attribute from the htmlValue

---

packages/tooltip/src/vaadin-lit-tooltip-overlay.js
packages/tooltip/src/vaadin-tooltip-overlay-mixin.js
packages/tooltip/src/vaadin-tooltip-overlay.js

This PR is needed for reusing `vaadin-tooltip-overlay` position logic in `vaadin-popover`:
- Moved `hidden` attribute setting to the actual overlay elements that use this mixin,
- Replaced hardcoded custom CSS property with an overridable `_tagNamePrefix`.
- Refactor

refactor: prepare tooltip overlay mixin for using by popover

---

packages/component-base/src/virtualizer-iron-list-adapter.js
packages/component-base/test/virtualizer-variable-row-height.test.js

Schedule an update after Virtualizer size change to ensure item positions are correct after subsequent size change+update calls
Fixes https://github.com/vaadin/flow-components/issues/6269
Bugfix

fix: debounce an update after virtualizer size change

---

dev/popover.html
packages/popover/package.json
packages/popover/src/vaadin-popover-overlay-mixin.js
packages/popover/src/vaadin-popover-overlay.js
packages/popover/src/vaadin-popover-position-mixin.d.ts
packages/popover/src/vaadin-popover-position-mixin.js
packages/popover/src/vaadin-popover-target-mixin.d.ts
packages/popover/src/vaadin-popover-target-mixin.js
packages/popover/src/vaadin-popover.d.ts
packages/popover/src/vaadin-popover.js
packages/popover/test/basic.test.js
packages/popover/test/not-animated-styles.js
packages/popover/test/position.test.js
packages/popover/test/typings/popover.types.ts
packages/tooltip/package.json
packages/tooltip/src/vaadin-lit-tooltip-overlay.js
packages/tooltip/src/vaadin-tooltip-mixin.d.ts
packages/tooltip/src/vaadin-tooltip-mixin.js
packages/tooltip/src/vaadin-tooltip-overlay.js

Part of https://github.com/vaadin/platform/issues/5271
Implemented the following logic of `vaadin-popover`:
- `target`, `for` and `position` properties (corresponding mixins extracted from `vaadin-tooltip`)
- `renderer` property and `requestContentUpdate()` method (logic copied from `vaadin-dialog`)
- overlay opens on target click , closes on outside click and <kbd>Esc</kbd> press (default overlay behavior)
- Feature

feat: implement basic popover logic, move mixins from tooltip

---

packages/popover/src/vaadin-popover-overlay.js
packages/popover/src/vaadin-popover.d.ts
packages/popover/src/vaadin-popover.js
packages/popover/test/basic.test.js
packages/popover/test/typings/popover.types.ts

Extracted from #7412
This PR adds the following properties:
- `noCloseOnEsc`
- `noCloseOnOutsideClick`
Also, added logic to close on target element <kbd>Esc</kbd> (will be useful for non-modal popovers).
Set `tabindex="0"` on the overlay part to allow focusing it and pressing <kbd>Esc</kbd> to close.
- Feature

feat: add properties to control popover closing behavior

---

packages/vaadin-lumo-styles/utilities/layout.js

Typo in the responsive utility classes for `display: grid`.
Fixes # (issue)

fix: fix typo in the responsive grid layout utility classes

---

packages/popover/src/vaadin-popover-overlay.js
packages/popover/src/vaadin-popover.d.ts
packages/popover/src/vaadin-popover.js
packages/popover/test/basic.test.js
packages/popover/test/typings/popover.types.ts

- Changed the popover to set `modeless` property on the overlay by default, added `modal` property (default to false),
- Added the `withBackdrop` property to `vaadin-popover` that works the same as in `vaadin-dialog` when modal,
- Changed the backdrop to use `pointer-events: none` when the popover is non-modal (to allow target clicks),
- Added a separate document `click` listener to also close on outside click when the overlay is modeless.
- Feature

feat: make popover modeless by default, add modality properties

---

integration/package.json
integration/tests/dialog-popover.test.js
packages/popover/src/vaadin-popover.js

Currently, pressing <kbd>Esc</kbd> on modeless popover target closes both the popover itself and the parent overlay.
Added logic to call `event.stopPropagation()` to prevent the same event from being handled twice. Also added IT test.
- Bugfix

fix: do not close dialog when closing popover on Escape

---

packages/combo-box/src/vaadin-combo-box-data-provider-mixin.js

The PR removes the redundant initialization of the `filteredItems` property in `_ensureItemsOrDataProvider()`, as this is already handled by `clearCache()` in `_dataProviderChanged()`, and here is a related test:
https://github.com/vaadin/web-components/blob/f9559b6c8ab642d55093528851c2d56902586167/packages/combo-box/test/lazy-loading.common.js#L254-L261
Extracted from #7044

refactor: do not initialize filteredItems property repeatedly

---

packages/component-base/src/slot-observer.d.ts
packages/component-base/src/slot-observer.js
packages/component-base/test/slot-observer.test.js

Include current nodes in slot observer callback
Related to https://github.com/vaadin/web-components/issues/2043
- Chore (internal feature)

chore: include current nodes in slot observer callback

---

packages/popover/src/vaadin-popover.js
packages/popover/test/basic.test.js

Added logic to restore focus on close to the popover target.
- Feature

feat: restore focus to the popover target on overlay close

---

packages/avatar/src/vaadin-avatar.js
packages/avatar/src/vaadin-lit-avatar.js
packages/avatar/test/dom/__snapshots__/avatar.test.snap.js

Make the `<img>` element inside the avatar component's shadow root non-draggable.
If a user wants to make an avatar draggable, they can explicitly mark it so with `<vaadin-avatar draggable="true" ...>`
Part of https://github.com/vaadin/flow-components/issues/6306
Bugfix

fix: make the img element in avatar non-draggable

---

dev/popover.html
packages/popover/package.json
packages/popover/src/vaadin-popover-overlay.js
packages/popover/src/vaadin-popover.d.ts
packages/popover/src/vaadin-popover.js
packages/popover/test/basic.test.js
packages/popover/test/trigger.test.js
packages/popover/test/typings/popover.types.ts

- Added the `trigger` property for setting how popover opens and closes.
- Changed `opened` property to be public (especially for `manual` trigger).
- Feature

feat: add trigger property, make opened property public

---

packages/vaadin-lumo-styles/color.js

Code snippets in Vaadin apps look weird without this fix. @jouni says this fixes them all 💪
Example:
That kind of html is generated by e.g. all markdown generators

Removes odd double background color for typical code markup

---

packages/popover/src/vaadin-popover.js
packages/popover/test/a11y.test.js
packages/popover/test/helpers.js
packages/popover/test/trigger.test.js

Re-enabled `restoreFocusOnClose` and changed the way how it is configured to work for `click` and `focus` triggers.
When using `trigger = ['hover', 'focus']`, the focus is still restored if opened on focus, but not if opened on hover.
- Refactor

refactor: restore focus for popover click and focus triggers

---

packages/popover/src/vaadin-popover.js
packages/popover/test/basic.test.js

Depends on #7430 
Changed the logic to always close the popover on <kbd>Esc</kbd> using global listener like in `vaadin-tooltip`:
https://github.com/vaadin/web-components/blob/9f3ac555d5fef1845a1f98cc7e0b311be4094772/packages/tooltip/src/vaadin-tooltip-mixin.js#L476-L480
This is needed to align the behavior so that `vaadin-popover` opened on hover can also be dismissed by <kbd>Esc</kbd>.
- Refactor

refactor: close popover on global Escape press by default

---

packages/grid/src/vaadin-grid-column-mixin.d.ts
packages/grid/src/vaadin-grid-column-mixin.js

Add a new paragraph to mention the issue of using em length unit in columns width.
Part of https://github.com/vaadin/flow-components/issues/6260

docs: add note about `em` unit in the column `width` jsdoc

---

packages/popover/src/vaadin-popover-overlay.js
packages/popover/src/vaadin-popover.d.ts
packages/popover/src/vaadin-popover.js
packages/popover/test/basic.test.js
packages/popover/test/typings/popover.types.ts

Based on #5187
Added API to set `vaadin-popover` overlay content width and height: `_contentWidth` and `_contentHeight` properties.
These are marked as protected to align with `vaadin-confirm-dialog` - see how the [Flow counterpart](https://github.com/vaadin/flow-components/blob/2757a87931252f551798b355a08c8b08994cb9a4/vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialog.java#L124-L131) uses them.
- Feature

feat: add properties to set popover content width and height

---

packages/component-base/src/slot-controller.js
packages/field-base/test/field-mixin.test.js

Fixes https://github.com/vaadin/flow-components/issues/6323
Currently, there is a timing issue in the `SlotController` related to how `this.node` reference is updated:
- when creating default node first time in `attachDefaultNode()`, it is set immediately;
- when restoring default node, it is only updated after a delay in the slot observer.
This leads to a problem in `HelperController` which checks for `this.node` immediately after restoring:
https://github.com/vaadin/web-components/blob/66675ccdf6a23090f14079eb6c6874f68274cd2b/packages/field-base/src/helper-controller.js#L26-L34
While there is an existing test for restoring `helperText`, it uses `await` and does not catch this case.
Updated to set `this.node` before calling `appendChild()` for consistency, and added a test for the …

fix: restore default node correctly when using helperText

---

packages/grid-pro/src/vaadin-grid-pro-inline-editing-mixin.js
packages/grid/src/vaadin-grid-active-item-mixin.js
packages/grid/src/vaadin-grid-event-context-mixin.js
packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js

Refactor instances of:
```js
const path = e.composedPath();
const cell = path[path.indexOf(this.$.table) - 3];
```
in grid and grid-pro to instead use the shared `_getGridEventLocation` helper.
Refactor

refactor: use the shared _getGridEventLocation method

---

packages/grid-pro/src/vaadin-grid-pro-inline-editing-mixin.js
packages/grid-pro/test/edit-column.common.js
packages/grid/src/vaadin-grid-active-item-mixin.js

Update `vaadin-grid-pro-inline-editing-mixin.js` to not cancel click events that occur in edit column cells. Canceling the click events [blocks the grid connector](https://github.com/vaadin/flow-components/blob/5b937e811d7185bbaf6b00c977bb3054dcc6bdb1/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.ts#L1128-L1131) from dispatching `item-click` events which in turn results in the Flow Grid item click listeners not getting invoked.
Related to https://github.com/vaadin/web-components/issues/637
Bugfix

fix: do not cancel edit column cell click events

---

packages/popover/src/vaadin-popover.d.ts
packages/popover/src/vaadin-popover.js
packages/popover/test/timers.test.js
packages/popover/test/typings/popover.types.ts

Added `focusDelay`, `hoverDelay` and `hideDelay` properties to the `vaadin-popover`. 
These are similar to `vaadin-tooltip` with the exception of the following differences:
- there is no common "warm up" and "cooldown" logic (we don't need to switch between popovers quickly)
- there is no global API to set default hover, focus and hide delay values (can be added if we want to have it)
- default hover, hide and focus delays in milliseconds are set to `0` (in `vaadin-tooltip` it's set to `500`)
- Feature

feat: add focusDelay, hoverDelay and hideDelay to popover

---

packages/overlay/src/vaadin-overlay-position-mixin.js
packages/overlay/test/position-mixin.common.js

If the target element is hidden, either by having `display: none` set to itself or any of its parents, a resize observer for that element is triggered.
This change adds a check for the target element size on the resize observer callback and closes the overlay in case the element is hidden.
Fixes #7437
- [X ] Bugfix

fix: hide overlay if position target element is hidden

---

packages/grid-pro/src/vaadin-grid-pro-inline-editing-mixin.js
packages/grid-pro/test/edit-column.common.js
packages/grid/src/vaadin-grid-active-item-mixin.js

Manually cherry-pick https://github.com/vaadin/web-components/pull/7453 to `24.4`
The merge conflict was due to 24.4 not having the `emptystatecell` element
Bugfix

fix: do not cancel edit column cell click events (#7453)

---

packages/combo-box/test/data-provider-filtering.common.js

The PR adds tests to cover the following line in combo-box, which was noted as lacking coverage in [this discussion](https://github.com/vaadin/web-components/pull/7044#discussion_r1611331945):
https://github.com/vaadin/web-components/blob/7f63f1dd26edc80f34c3a955d7d46790977f85b1/packages/combo-box/src/vaadin-combo-box-data-provider-mixin.js#L114
Related to https://github.com/vaadin/web-components/pull/7044

test: add missing data provider filtering tests

---

packages/side-nav/src/vaadin-side-nav-item.js
packages/side-nav/test/navigation.test.js

Flow will soon fire 'vaadin-navigate' instead of 'popstate' when doing server side navigation

fix: listen to 'vaadin-navigate' events

---

packages/confirm-dialog/src/vaadin-confirm-dialog-mixin.d.ts
packages/confirm-dialog/src/vaadin-confirm-dialog-mixin.js
packages/confirm-dialog/src/vaadin-confirm-dialog.d.ts
packages/confirm-dialog/src/vaadin-confirm-dialog.js
packages/confirm-dialog/test/confirm-dialog.common.js
packages/confirm-dialog/test/typings/confirm-dialog.types.ts

Add a new `closed` event that is triggered after the overlay is closed
Part of #7422

feat: fire closed event when Confirm Dialog is closed

---

packages/dialog/src/vaadin-dialog-base-mixin.js
packages/dialog/src/vaadin-dialog.d.ts
packages/dialog/src/vaadin-dialog.js
packages/dialog/test/dialog.common.js
packages/dialog/test/typings/dialog.types.ts

Add a new `closed` event that is triggered after the overlay is closed
Part of #7422

feat: fire closed event when Dialog overlay is closed

---

packages/notification/src/vaadin-notification.d.ts
packages/notification/src/vaadin-notification.js
packages/notification/test/notification.test.js
packages/notification/test/typings/notification.types.ts

Add a new `closed` event that is triggered after the notification is closed
Part of #7422

feat: add closed event when Notification is closed

---

packages/grid/src/vaadin-grid-mixin.js
packages/grid/src/vaadin-grid-styles.js
packages/grid/test/column-auto-width.common.js

Cherry-pick https://github.com/vaadin/web-components/pull/7046 to `24.3`
Fixes https://github.com/vaadin/flow-components/issues/6300
Bugfix

fix: measure auto-width correctly for focusButtonMode columns (#7046)

---

packages/component-base/src/data-provider-controller/data-provider-controller.d.ts
packages/component-base/src/data-provider-controller/data-provider-controller.js
packages/component-base/test/typings/data-provider-controller/data-provider-controller.types.ts

The PR removes the size property declaration from DataProviderController because this property isn't used anywhere. It's apparently a leftover from https://github.com/vaadin/web-components/pull/6806.

refactor: remove unused size property declaration

---

packages/combo-box/src/vaadin-combo-box-data-provider-mixin.js
packages/component-base/src/data-provider-controller/cache.js
packages/component-base/src/data-provider-controller/data-provider-controller.d.ts
packages/component-base/src/data-provider-controller/data-provider-controller.js
packages/component-base/test/data-provider-controller-data-callbacks.test.js
packages/component-base/test/data-provider-controller.test.js
packages/component-base/test/typings/data-provider-controller/data-provider-controller.types.ts
packages/grid/src/vaadin-grid-data-provider-mixin.js

This PR refactors the combo-box to use DataProviderController. The refactoring is expected to be non-breaking and fully compatible with the existing ComboBox Flow connector, which is verified by successfully passing all the Flow integration tests.
Depends on 
- https://github.com/vaadin/web-components/pull/6968
- https://github.com/vaadin/web-components/pull/7205
- https://github.com/vaadin/web-components/pull/6979
- https://github.com/vaadin/web-components/pull/7257
- https://github.com/vaadin/web-components/pull/7266
- https://github.com/vaadin/web-components/pull/7262
- https://github.com/vaadin/web-components/pull/7350
- https://github.com/vaadin/web-components/pull/7426
- https://github.com/vaadin/web-components/pull/7349
- https://github.com/vaadin/web-components/pull/7353
- …

refactor: make combo-box use DataProviderController

---

packages/grid/src/vaadin-grid-active-item-mixin.js

Clean up the custom `isFocusable` implementation in Grid by making it re-use the `isElementFocusable` helper from `a11y-util`
Refactor

refactor: remove duplicate logic from grid isFocusable

---

packages/select/src/vaadin-lit-select.js
packages/select/src/vaadin-select-base-mixin.d.ts
packages/select/src/vaadin-select-base-mixin.js
packages/select/src/vaadin-select.js
packages/select/test/select.common.js
packages/select/theme/lumo/vaadin-select-styles.js

Add a property to `vaadin-select` called `noVerticalOverlap` which forwards its value to the same property present in the Overlay, to allow users to configure whether they want the overlay to overlap the input container (default) or not.
Part of #5101

feat: add no-vertical-overlap prop to vaadin-select

---

integration/tests/context-menu-grid.test.js
packages/context-menu/src/vaadin-context-menu-mixin.js
packages/context-menu/test/overlay.common.js

Dispatch a new `contextmenu` event over the target in case the context-menu gets closed by a `contextmenu` event. This enables opening a new context menu without closing the previous one first.
https://github.com/vaadin/web-components/assets/1222264/05be83c5-d2b1-4e39-a734-65466d40f5ae
Fixes #1135 
Bugfix

fix: re-open context-menu on closing contextmenu event

---

packages/menu-bar/theme/lumo/vaadin-menu-bar-styles.js

Set the MenuBar's minimum width to --lumo-size-m which is the default size of the overflow button. This way, the MenuBar can not be shrunk down to the point where the overflow button is not visible anymore.
Fixes  #6876

fix: add min-width to MenuBar

---

packages/select/src/vaadin-select-base-mixin.js
packages/select/test/select.common.js

The current placeholder logic in vaadin-select shows the placeholder when the selected item has neither a label attribute value nor text content (see https://github.com/vaadin/web-components/pull/7303). That is problematic however when a custom rendered select item only contains an image, icon or similar element that does not result in text content - in that case it also shows the placeholder instead of the image for example.
This change adds a check for whether a select item has any child element, in which case the placeholder is not shown.
Fixes https://github.com/vaadin/web-components/issues/7497

fix: do not show placeholder when select item has child elements

---

packages/date-picker/src/vaadin-date-picker-overlay-content-mixin.js
packages/date-picker/test/overlay-content.common.js

Fixes #7505
Updated the logic to use "today midnight" for comparing with `max`. Without this change, the actual time is used and `dateAllowed` returns `false` when clicking "Today" button, thus making selecting today in this case impossible.
- Bugfix

fix: select date on Today click if today is max date

---

packages/date-picker/src/vaadin-date-picker-overlay-content-mixin.js
packages/date-picker/test/overlay-content.common.js

Manual cherry-pick of #7516 to `24.3` branch. 
The automated cherry-pick failed due to `isDateDisabled` present in main / 24.4 but missing in 24.3 branch.
- Cherry-pick

fix: select date on Today click if today is max date (#7516) (CP: 24.3)

---

packages/context-menu/src/vaadin-contextmenu-items-mixin.js
packages/context-menu/test/items.common.js

Fixes https://github.com/vaadin/flow-components/issues/6386
Updated the context-menu to check if the sub-menu contained a focused item before closing it:
- If that's true, the focus is moved to the corresponding parent item (and the outline is preserved).
- Otherwise, the overlay part receives focus, so that we can still handle `keydown` for arrow keys.
I think this makes more sense than a workaround with focusing the item without showing outline.
- Bugfix
See video below for the updated behavior:
Parent / child item is not focused when opening / closing sub-menu on hover:
https://github.com/vaadin/web-components/assets/10589913/7434555c-8d0e-4086-9060-47f574c1e1d7
Parent item is focused after closing a sub-menu with a focused child item: …

fix: only focus parent item if sub-menu contained focus

---

packages/field-base/src/input-control-mixin.js
packages/field-base/test/input-control-mixin.test.js

Currently helpers are also disallowed the char patterns as set for the main input. The issue mentions the very real problem of not being able to check a helper checkbox with keyboard navigation if the input disallows spaces, like it should for a lot of inputs.
This PR checks that the event target is the main input of the input-field. 
Fixes https://github.com/vaadin/flow-components/issues/6391

fix: allow helper disallowed char patterns set for input

---

packages/menu-bar/test/a11y.common.js
packages/menu-bar/test/sub-menu.common.js

While reviewing #7525, I noticed that for the "accessibility" test suite is confusingly placed in `sub-menu` test file.
This is a leftover from the V14 version. Now when we have `a11y` test file, it makes sense to move the suite there.
- Test

test: move a11y test suite to the appropriate file

---

packages/confirm-dialog/src/vaadin-confirm-dialog-mixin.js
packages/dialog/src/vaadin-dialog-base-mixin.js
packages/notification/src/vaadin-notification.js

Related to https://github.com/vaadin/web-components/issues/7422
While reviewing PRs related to the above change, I missed that we need to annotate this event using `@event` for Polymer Analyzer, which then generates `web-types.json` used by React components, so we could use `onClosed` in React.
This PR adds missing annotations. I will check if there are more events like these and if so, fix them separately.
- Documentation fix

docs: add missing JSDoc annotations for closed event

---

packages/dialog/src/vaadin-dialog-resizable-mixin.js

Added missing `@event` annotation for using by Polymer Analyzer to make the `resize` event appear in API docs.
This will also add it to `web-types.json` and therefore will generate `onResize` listener for the React wrapper.

docs: add missing JSDoc annotation for resized event

---

packages/details/theme/lumo/vaadin-details-summary-styles.js

Even though it's now easy for the user to style the content part of the summary, this gives the content the remainder of the width by default.
Fixes #497

fix: allow the content part of details summary the remainder of the width

---

packages/popover/src/vaadin-popover.d.ts
packages/popover/src/vaadin-popover.js

Added missing `vaadin-popover` styling API documentation (adapted from the corresponding docs for `vaadin-tooltip`).

docs: add styling API documentation to popover JSDoc

---

packages/popover/src/vaadin-popover.d.ts
packages/popover/src/vaadin-popover.js
packages/popover/test/basic.test.js
packages/popover/test/typings/popover.types.ts

Related to #7422
Implemented `closed` event similar to what was added to `vaadin-dialog` in #7471
- Feature

feat: fire closed event when popover overlay is closed

---

packages/field-base/src/validate-mixin.d.ts

We only need `@event` annotation in `.js` files as Polymer Analyzer does not scan `.d.ts` files for it.
Removed this comment (there is a correct one in the corresponding `.js` file for this mixin.

chore: remove unnecessary event JSDoc from d.ts file

---

packages/vaadin-lumo-styles/utilities/background.js
packages/vaadin-lumo-styles/utilities/border.js
packages/vaadin-lumo-styles/utilities/flexbox-grid.js
packages/vaadin-lumo-styles/utilities/layout.js
packages/vaadin-lumo-styles/utilities/shadows.js
packages/vaadin-lumo-styles/utilities/transition.js

Mostly just clean up (read: OCD sorting to match the `LumoUtility` classes).
- Added `flex-1` per @marcushellberg's request.
- Renamed `flex-grow`/`flex-shrink` to `grow`/`shrink` respectively (since we're following Tailwind's naming convention).
- `z-0` and `z-auto` added.
- `shadow-0` added.

Utility update

---

packages/date-picker/src/vaadin-month-calendar-mixin.js
packages/date-picker/test/month-calendar.common.js

Nothing stops the user from setting more than 7 weekdays, this PR renders only the first 7 of the given weekdays.
Weekday items are given a width of 100%/7 meaning that the are aligned even with less than 7 items, but when there are 8 or more, the width exceeds 100% and the parent container's flexbox squeezes them together, misaligning the weekdays from the dates.
Fixes part of https://github.com/vaadin/flow-components/issues/6353
Related PR: https://github.com/vaadin/flow-components/pull/6432

fix: render at most 7 weekdays in datepicker

---

packages/combo-box/test/data-provider-dynamic-size.common.js
packages/combo-box/test/data-provider.common.js
packages/dialog/test/draggable-resizable.common.js
packages/grid/test/accessibility.common.js
packages/grid/test/scroll-to-index.common.js

This fixes some warnings reported by [no-array-constructor](https://eslint.org/docs/latest/rules/no-array-constructor) rule in the latest `eslint-config-vaadin` alpha.
- Tests

test: do not use Array constructor in unit tests

---

integration/tests/dialog-combo-box.test.js
packages/combo-box/src/vaadin-combo-box-mixin.js
packages/combo-box/test/interactions.common.js
packages/time-picker/src/vaadin-time-picker.js

Fixes #7552
Changed the blur logic of `vaadin-combo-box` to only close when losing focus from keyboard, or if the `opened` is set to `true` but the overlay is not actually open (which is the case if no dropdown items match the filter).
This way we make sure that closing an opened combo-box happens on outside click (vs `focusout`) and therefore avoid closing of the parent `vaadin-dialog` (or `vaadin-popover`) - this is covered by new test in `integration` folder.
Also updated `vaadin-time-picker` to remove unnecessary value commit from `focusout` - in fact it was triggered twice in this case: first from `focusout` and then from combo-box `change` event. Now only the latter is used.
- Bugfix

fix: only close combo-box overlay on blur from keyboard

---

integration/tests/dialog-combo-box.test.js
packages/combo-box/src/vaadin-combo-box-mixin.js
packages/combo-box/test/toggling-dropdown.test.js
packages/time-picker/src/vaadin-time-picker.js

Manual cherry-pick of #7554 to `24.3` branch. The automated cherry-pick failed due to changes in tests on `main`.
- Cherry-pick

fix: only close combo-box overlay on blur from keyboard (#7554) (CP: 24.3)

---

packages/time-picker/src/vaadin-time-picker.js
packages/time-picker/test/aria.test.js

fix: remove ARIA attributes when time-picker has no dropdown

---

packages/login/theme/lumo/vaadin-login-overlay-styles.js
packages/login/theme/material/vaadin-login-overlay-styles.js

The `constant()` was an old version of [`env()`](https://caniuse.com/css-env-function) function supported only in Safari 11. 
As we dropped support for that version long ago, it's safe to only use `env`.
Note: discovered when trying to upgrade to Stylelint 16 and `stylelint-config-recommended`:
```
packages/login/theme/lumo/vaadin-login-overlay-styles.js
141:22  ✖  Unexpected unknown function "constant"  function-no-unknown
```
- Refactor

refactor: drop usage of deprecated constant() function

---

packages/app-layout/theme/material/vaadin-app-layout-styles.js
packages/app-layout/theme/material/vaadin-drawer-toggle-styles.js
packages/date-picker/theme/lumo/vaadin-date-picker-overlay-styles.js
packages/login/theme/lumo/vaadin-login-overlay-styles.js
packages/tabs/theme/lumo/vaadin-tab-styles.js
packages/tabs/theme/material/vaadin-tabs-styles.js

Fixed a few warnings about duplicate CSS selectors reported after enabling `no-duplicate-selectors` Stylelint rule.
- Refactor

refactor: remove duplicate CSS selectors from themes

---

integration/tests/dialog-popover.test.js
packages/popover/src/vaadin-popover.js
packages/popover/test/basic.test.js

Fixes #7481
This issue turned out to be caused by the fact that I used different elements for global `click` listeners:
- `vaadin-popover` uses `doument.addEventListener('click')`
- `vaadin-dialog-overlay` uses `document.documentElement`
This is a problem especially for modeless `vaadin-popover` (the one that uses its own click listener).
The fix might not be very intuitive (ideally we would instead implement something like https://github.com/vaadin/web-components/issues/7481#issuecomment-2180098804 to avoid having a separate listener in the first place). But I do think that it makes sense to align elements used for adding click listener.
The listener on the `document` is called first, then the one on `document.documentElement`:
1. click listener from `vaadin-popover` is called and it …

fix: use correct element for popover global click listener

---

packages/date-picker/src/vaadin-date-picker-mixin.js
packages/date-picker/test/fullscreen.common.js

Fixes https://github.com/vaadin/flow-components/issues/4809
Updated the date-picker logic to allow focusing with keyboard when `_noInput` flag is set due to fullscreen mdoe.
This way we make it possible to focus the date-picker on narrow screens or when applying zoom.
Can be tested e.g. by resizing a browser width to 600px and zooming to 150% (so that width changes to 400px).
- Bugfix

fix: allow focusing date-picker input using keyboard on fullscreen

---

packages/select/src/vaadin-lit-select-overlay.js
packages/select/src/vaadin-select-overlay-mixin.js
packages/select/src/vaadin-select-overlay.js
packages/select/src/vaadin-select.js
packages/select/test/select.common.js
packages/select/theme/lumo/vaadin-select-styles.js
packages/select/theme/material/vaadin-select-styles.js

Part of https://github.com/vaadin/web-components/issues/7502
Added `--vaadin-select-overlay-width` custom CSS property set on the host and forwarded to the overlay on open.
- Feature

feat: add custom CSS property to customize select overlay width

---

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js
packages/multi-select-combo-box/test/accessibility.test.js
packages/multi-select-combo-box/test/dom/__snapshots__/multi-select-combo-box.test.snap.js

Fixes #7551
Changed to align with `InputControlMixin` by removing default empty string value, so that we don't have `placeholder` attribute set by default. Also fixed the logic for restoring placeholder property in selected items observer.
Note, the property has `reflectToAttribute` so technically setting empty string can still cause that to happen (which is the case for all input fields). I don't think we can easily fix that without a breaking change.
- Bugfix

fix: do not set placeholder to empty string by default

---

packages/dialog/src/vaadin-dialog-base-mixin.d.ts
packages/dialog/src/vaadin-dialog-base-mixin.js
packages/dialog/src/vaadin-dialog.js
packages/dialog/src/vaadin-lit-dialog.js
packages/dialog/test/dialog.common.js
packages/dialog/test/dom/__snapshots__/dialog.test.snap.js
packages/dialog/test/dom/dialog.test.js
packages/dialog/test/typings/dialog.types.ts

Part of #4977
Added `overlayRole` property similar to the one we now have in `vaadin-popover` to customize the dialog role.
- Feature

feat: add overlayRole property to customize dialog role

---

packages/dialog/test/dialog.common.js

- Removed a few tests about default `role` and `theme` propagation as covered by snapshots
- Changed the "attributes" test suite to be about `aria-label` and added `beforeEach()` block
- Tests

test: remove dialog unit tests covered by snapshots

---

packages/input-container/theme/lumo/vaadin-input-container-styles.js

Follow-up to #7553
Restored the incorrectly changed CSS selector for input container color to apply to slotted `input`.
- Bugfix

fix: use proper selector for input container disabled color

---

packages/grid/src/vaadin-grid-drag-and-drop-mixin.js
packages/grid/src/vaadin-grid.js
packages/grid/test/drag-and-drop.common.js

Adds part attributes to the cells that are to be dragged. The image that follows the cursor around is left unchanged, it can be styled using the existing `dragstart-row-cell` part. 
Styling the row itself cause issues, which is why it was intentionally left out. 
Fixes #5548

feat: add parts to drag source row cells

---

packages/a11y-base/src/focus-restoration-controller.js
packages/a11y-base/test/focus-restoration-controller.test.js
packages/overlay/src/vaadin-overlay-focus-mixin.js
packages/overlay/test/restore-focus.common.js

Fixes https://github.com/vaadin/flow-components/issues/6483
Changed the restoring focus logic to prevent page scroll when it's done not from keyboard.
This should prevent unexpected page scroll change after closing overlays on outside click.
- Bugfix

fix: prevent scroll when restoring focus not from keyboard

---

packages/vaadin-lumo-styles/mixins/input-field-shared.js

Rolf actually wanted to separate labels from the values of the input container

fix: reintroduce disabled variable for slotted parts of input-field

---

packages/select/src/vaadin-select-base-mixin.js
packages/select/src/vaadin-select-overlay-mixin.js
packages/select/test/keyboard.common.js

This aligns `vaadin-select` with e.g. `vaadin-date-picker` and ensures it also benefits from #7599
- Refactor

refactor: update select to use overlay focus restoration logic

---

packages/select/src/vaadin-lit-select-overlay.js
packages/select/src/vaadin-select-base-mixin.js
packages/select/src/vaadin-select-overlay.js
packages/select/test/keyboard.common.js

Manual cherry-pick of #7601 to `24.3` branch. 
The automated cherry-pick failed due to `vaadin-select-overlay-mixin` only present in `main` but not in older branches.
- Cherry-pick

refactor: update select to use overlay focus restoration logic (#7601) (CP: 24.3)

---

packages/select/src/vaadin-lit-select-overlay.js
packages/select/src/vaadin-select-base-mixin.js
packages/select/src/vaadin-select-overlay.js
packages/select/test/keyboard.common.js

Manual cherry-pick of #7601 to `24.4` branch. 
The automated cherry-pick failed due to `vaadin-select-overlay-mixin` only present in `main` but not in older branches.
- Cherry-pick

refactor: update select to use overlay focus restoration logic (#7601) (CP: 24.4)

---

packages/popover/src/vaadin-popover.js
packages/popover/test/a11y.test.js

Fixes #7607
Implemented the <kbd>Tab</kbd> order for `vaadin-popover` overlay content. See the video:
https://github.com/user-attachments/assets/b1ede21f-0b46-40c9-bfed-97d7b4135e5b
- A11y feature
As it's now impossible to close the popover on target <kbd>Tab</kbd> (the focus will move to the overlay when it's non modal, and the focus will be trapped inside the overlay when modal), corresponding listener and test has been removed.

feat: include popover content in Tab order after the target

---

packages/popover/lit.d.ts
packages/popover/lit.js
packages/popover/package.json
packages/popover/src/lit/renderer-directives.d.ts
packages/popover/src/lit/renderer-directives.js
packages/popover/test/lit-renderer-directives.test.js
packages/popover/test/typings/lit.types.ts

Added a Lit renderer directive for the `renderer` property of the popover in order to provide a better DX for Lit users.
- Feature

feat: add Lit renderer directive for popover

---

packages/popover/src/vaadin-popover.d.ts
packages/popover/src/vaadin-popover.js
packages/popover/test/a11y.test.js
packages/popover/test/typings/popover.types.ts

Added API for setting automatically focusing the popover when opened.
- Feature

feat: add autofocus property for non-modal popovers

---

packages/vaadin-lumo-styles/style.js

Follow up to https://github.com/vaadin/web-components/pull/7615
Mistakenly had switched up the two new global defaults.

fix: set the right globals

---

packages/component-base/src/slot-controller.d.ts
packages/component-base/src/slot-controller.js
packages/date-picker/src/vaadin-date-picker.js
packages/date-picker/test/dom/__snapshots__/date-picker.test.snap.js
packages/date-time-picker/test/dom/__snapshots__/date-time-picker.test.snap.js
packages/field-base/src/input-controller.js
packages/time-picker/src/vaadin-time-picker.js
packages/time-picker/test/dom/__snapshots__/time-picker.test.snap.js

The PR adds the "search" prefix to the date and time picker's id attribute. This is a trick to prevent Safari from enabling AutoFill, which is causing click issues. See the referenced ticket for more details.
> [!WARNING]
> @web-padawan: could be considered behavior altering fix due to the fact of changing ID attributes which can be unexpected by some users in terms of testing.
Fixes #6817

fix!: prevent Safari AutoFill to avoid click issues

---

packages/text-area/theme/lumo/vaadin-text-area-styles.js

Fixes https://github.com/vaadin/flow-components/issues/6503
- Bugfix

fix: use custom CSS property for text-area readonly border

---

packages/app-layout/package.json

The `@vaadin/app-layout` package does not use `@vaadin/tabs` so this dev dependency can be removed.
It is most likely a leftover from the V14 version which used to have `vaadin-tabs` in drawer visual tests.

chore: remove unused tabs from devDependencies

---

packages/checkbox-group/package.json

Looks like I missed to add `lit` dependency when adding Lit based version. This PR fixes that.

chore: add missing Lit dependency to checkbox-group

---

packages/field-highlighter/package.json

The `announce` helpers is imported in the `src` folder so we need to use `"dependencies"`, not `"devDependencies"`.
https://github.com/vaadin/web-components/blob/19bcd2bc48a751ea061e2d845372abb3f2bb8f02/packages/field-highlighter/src/vaadin-field-highlighter.js#L8

chore: move a11y-base to field-highlighter dependencies

---

packages/notification/test/visual/lumo/notification.test.js

Changed to use `@vaadin/button` import instead of the relative import in visual test.
- Test

test: use correct button import in notification test

---

packages/rich-text-editor/package.json

Looks like I missed to add this dependency when implementing color pickers in #7392. This PR fixes that.

chore: add missing overlay dependency to rich-text-editor

---

packages/tooltip/package.json

Looks like I missed to add `lit` dependency when adding Lit based version of the component. This PR fixes that.

chore: add missing Lit dependency to tooltip

---

packages/split-layout/package.json

Looks like I missed to add `lit` dependency when adding Lit based version of the component. This PR fixes that.

chore: add missing Lit dependency to split-layout

---

packages/popover/src/vaadin-popover-overlay.js

This is the only remaining error reported when upgrading to Stylelint 16:
```
packages/popover/src/vaadin-popover-overlay.js
66:11  ✖  Expected shorthand property "inset-inline"  declaration-block-no-redundant-longhand-properties
```
- Refactor

refactor: update popover styles to use inset-inline shorthand

---

packages/side-nav/theme/lumo/vaadin-side-nav-styles.js
packages/side-nav/theme/material/vaadin-side-nav-styles.js

Fixed two more warnings reported by upgrading to Stylelint 16:
```
packages/side-nav/theme/lumo/vaadin-side-nav-styles.js
50:5  ✖  Expected shorthand property "margin-inline"  declaration-block-no-redundant-longhand-properties
packages/side-nav/theme/material/vaadin-side-nav-styles.js
41:5  ✖  Expected shorthand property "margin-inline"  declaration-block-no-redundant-longhand-properties
```
- Refactor

refactor: update side-nav styles to use margin shorthand

---

packages/notification/theme/lumo/vaadin-notification-styles.js
packages/notification/theme/material/vaadin-notification-styles.js
packages/number-field/theme/lumo/vaadin-number-field-styles.js

Replaced `\$` with `$` in tagged css literals. Backslash was added by `polymer-modulizer` when converting to Polymer 3, in fact this character isn't needed. We have already removed it from most of theme files, this PR covers remaining ones.
- Refactor

refactor: remove not needed backslash in css literals

---

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js
packages/multi-select-combo-box/test/selecting-items.test.js

During a previous [fix](https://github.com/vaadin/web-components/pull/4075), a mechanism to avoid unwanted un-selections was added. This mechanism is based on keeping track of the last filter. However, the [update of this last filter](https://github.com/vaadin/web-components/blob/main/packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js#L308-L310) is only done on `_commitValue()`, which is not called when the selection is done via a click. 
This PR adds this filter update to `_overlaySelectedItemChanged()`, which is another path which is used to update the selection. This does not break the previous fix.
Fixes #7621

fix: store last filter also on item click

---

package.json
yarn.lock

Add missing `@types/mocha` dev dependency to fix ts test errors

chore: add missing mocha types

---

dev/upload.html
packages/upload/src/vaadin-upload-mixin.js
packages/upload/test/keyboard-navigation.common.js

Keyboard navigation in the upload list was broken. This PR fixes that by:
- focus next when a file is removed
- focus previous when the last file is removed
- focus the upload button when the last remaining file is removed
- focus self on retry
- focus upload button after upload (or really, just don't move it elsewhere)
These choices for navigation have been discussed internally. This PR focuses on keyboard navigation, possible ARIA issues are not taken into account.
I noticed that some of the tests were false positives because `null === null` so I added to each test that compares two objects an additional check for null. Of course, as these aren't supposed to be null, I also changed the way some of the elements are query selected.
Updated dev/upload.html to have proper files, this allows …

fix: fix and test focus issues in vaadin upload

---

dev/dashboard-layout.html
packages/dashboard/src/vaadin-dashboard-layout-mixin.d.ts
packages/dashboard/src/vaadin-dashboard-layout-mixin.js
packages/dashboard/src/vaadin-dashboard-layout.d.ts
packages/dashboard/src/vaadin-dashboard-layout.js
packages/dashboard/test/dashboard-layout.test.ts
packages/dashboard/test/helpers.ts
packages/dashboard/test/typings/dashboard.types.ts
packages/dashboard/theme/lumo/vaadin-dashboard-layout.js
packages/dashboard/theme/material/vaadin-dashboard-layout.js
packages/dashboard/vaadin-dashboard-layout.d.ts
packages/dashboard/vaadin-dashboard-layout.js

Add the very basic layout functionality of the `<vaadin-dashboard>` and `<vaadin-dashboard-layout>` components:
- Automatically placed widgets
- Responsive
- Number of columns vary depending on component width and minimum column width
- Widgets automatically wrap to new lines as needed
- Added API:
- `--vaadin-dashboard-col-min-width`: CSS variable that affects the number of column and limits how narrow the last column can shrink before it overflows
- `--vaadin-dashboard-col-max-width`: CSS variable that limits how wide the columns can grow when given enough space
Fixes https://github.com/orgs/vaadin/projects/70/views/1?pane=issue&itemId=74624766
- Feature

feat: add vaadin-dashboard-layout

---

dev/dashboard-layout.html
packages/dashboard/src/vaadin-dashboard-layout-mixin.d.ts
packages/dashboard/src/vaadin-dashboard-layout-mixin.js
packages/dashboard/test/dashboard-layout.test.ts
packages/dashboard/test/helpers.ts

Add column spanning support for `<vaadin-dashboard-layout>`
- Items can span multiple columns
- Actual column span is capped to currently available columns
https://github.com/user-attachments/assets/77486810-f586-460a-9a09-29962dd2a439
Added API:
`--vaadin-dashboard-item-colspan`: Applied to a child element of a dashboard layout. Affects its column span in the layout grid.
Fixes https://github.com/orgs/vaadin/projects/70/views/1?pane=issue&itemId=74625129
Feature

feat: add colspan support to dashboard

---

packages/popover/src/vaadin-popover.js
packages/popover/test/trigger.test.js

Part of https://github.com/vaadin/web-components/issues/7652
Fixes the issue that happens on click inside the popover content when `focus` trigger is used. In this case, `focusout` event occurs and the overlay unexpectedly closes despite the fact that the click was inside the overlay. 
The solution is to use `mousedown` event listener and set a flag to ignore next `focusout` event, if any. 
The flag is then set back to `false` on `mouseup` using a global event listener.
Can be tested with the following HTML:
```html
<button id="button">Open</button>
<vaadin-popover for="button"></vaadin-popover>
import '@vaadin/popover';
const popover = document.querySelector('vaadin-popover');
popover.trigger = ['focus'];
popover.renderer = (root) => {
if (!root.firstChild) {
// …
```

fix: do not close popover on focusout after mousedown inside

---

packages/popover/src/vaadin-popover.js
packages/popover/test/a11y.test.js

Fixes #7665
Restored logic which was incorrectly removed in #7609 and added a test for <kbd>Shift</kbd> + <kbd>Tab</kbd>.
- Bugfix

fix: do not restore focus on popover target Shift Tab

---

packages/popover/src/vaadin-popover.js
packages/popover/test/nested.test.js

Part of https://github.com/vaadin/web-components/issues/7652
This is an alternative solution to #7658. The idea here is to simply ignore `focusout` if the popover is not the last one.
The benefit of this approach is that we don't to check `event.relatedTarget` is in the nested overlay. Therefore, no need to tweak any existing components to set `overlay.owner` like we would need to do with my original idea.
Also, this covers both 1. and 2. problems showcased in https://github.com/vaadin/web-components/issues/7652#issuecomment-2291105312.
- Bugfix

fix: only close popover on focusout if it is the last one

---

packages/popover/src/vaadin-popover.js
packages/popover/test/nested.test.js

Part of #7652
Depends on https://github.com/vaadin/web-components/pull/7661
This is essentially the same as `focusout` fix but applied to overlay `mouseleave`. There are two possible cases here:
1. The `mouseleave` on the overlay that occurs immediately on opening the nested overlay (in case if it's modal)
2. The `mouseleave` on the target when opening a modeless overlay (e.g. nested popover) and moving mouse back to the target and then outside it (and also outside the overlay)
The second case is a bit questionable but IMO we shouldn't close both popovers at once in this case for better UX.
- Bugfix

fix: only close popover on mouseleave if it is the last one

---

packages/popover/theme/lumo/vaadin-popover-styles.js
packages/popover/theme/material/vaadin-popover-styles.js

Fixes #7667
This aligns the appearance with `vaadin-dialog` which was introduced https://github.com/vaadin/vaadin-dialog/pull/63
- Bugfix

fix: remove default outline from the popover overlay part

---

dev/dashboard-layout.html
packages/dashboard/src/vaadin-dashboard-layout-mixin.js
packages/dashboard/test/dashboard-layout.test.ts
packages/dashboard/test/helpers.ts

Add max columns support for `<vaadin-dashboard-layout>`
https://github.com/user-attachments/assets/7c749a4f-fbd8-4637-9d74-78a139b1e0ec
Added API:
- `--vaadin-dashboard-col-max-count`: Specifies the maximum count of columns the layout grid can have
Fixes https://github.com/orgs/vaadin/projects/70/views/1?pane=issue&itemId=74905298
Feature

feat: add max column count support to dashboard

---

packages/checkbox/src/vaadin-checkbox-mixin.js
packages/checkbox/test/dom/__snapshots__/checkbox.test.snap.js

When implementing `required` state in #7285 for some reason I didn't add `required` attribute propagation.
Tested this with VoiceOver on Chrome and Safari and the `required` state is now announced:
- Bugfix

fix: propagate checkbox required attribute to input

---

dev/dashboard-layout.html
packages/dashboard/src/title-controller.d.ts
packages/dashboard/src/title-controller.js
packages/dashboard/src/vaadin-dashboard-widget.d.ts
packages/dashboard/src/vaadin-dashboard-widget.js
packages/dashboard/test/dashboard-widget.test.ts
packages/dashboard/test/typings/dashboard.types.ts

Add basic `<vaadin-dashboard-widget>` structure
Added API:
- `widgetTitle`: Specifies the title of the widget
Fixes https://github.com/orgs/vaadin/projects/70/views/1?pane=issue&itemId=75304804
Part of https://github.com/vaadin/platform/issues/6627
Feature

feat: add basic dashboard widget structure

---

packages/popover/src/vaadin-popover.js

The `@mixes` annotation for `ElementMixin` is specified twice while `OverlayClassMixin` is missing. This PR fixes that.

docs: add missing mixes JSDoc annotation to popover

---

packages/avatar-group/test/dom/__snapshots__/avatar-group.test.snap.js
packages/combo-box/test/dom/__snapshots__/combo-box.test.snap.js
packages/context-menu/test/dom/__snapshots__/context-menu.test.snap.js
packages/date-picker/test/dom/__snapshots__/date-picker.test.snap.js
packages/date-picker/theme/material/vaadin-date-picker-overlay-styles.js
packages/date-time-picker/test/dom/__snapshots__/date-time-picker.test.snap.js
packages/menu-bar/test/dom/__snapshots__/menu-bar.test.snap.js
packages/overlay/src/vaadin-overlay-position-mixin.js
packages/overlay/test/position-mixin.common.js
packages/select/test/dom/__snapshots__/select.test.snap.js
packages/tooltip/test/dom/__snapshots__/tooltip.test.snap.js

Fixes #7676 
This removes logic for setting `dir` based on `computedStyle.direction` - originally this line was added in #2567 when updating `vaadin-date-picker` to use `PositionMixin` (previously, date-picker was setting `dir` to the `inputElement` direction which was introduced long ago in https://github.com/vaadin/vaadin-date-picker/pull/584).
Setting `dir` this way is problematic since it overrides `dir` attribute propagation from the `<html>` element which is performed by `DirMixin`. As a result, once `dir` is set to `ltr` it can't be changed to `rtl` upon overlay re-opening. In fact, the current tests just don't verify the value of the `dir` attribute set on the overlay.
This PR removes the line so that we could rely on the `DirMixin` instead, and updates RTL tests accordingly so …

fix!: do not override dir attribute on the overlay to rely on DirMixin

---

dev/dashboard.html
packages/dashboard/src/vaadin-dashboard-layout-mixin.js
packages/dashboard/src/vaadin-dashboard-widget.js
packages/dashboard/src/vaadin-dashboard.d.ts
packages/dashboard/src/vaadin-dashboard.js
packages/dashboard/test/dashboard.test.ts
packages/dashboard/test/helpers.ts
packages/dashboard/test/typings/dashboard.types.ts

Add `items` and `renderer` properties to `<vaadin-dashboard>`
New API for `<vaadin-dashboard>`:
- `items`: An array containing the items of the dashboard
- `renderer`: Custom function for rendering a widget for each dashboard item.
Fixes https://github.com/orgs/vaadin/projects/70/views/1?pane=issue&itemId=74625491
Feature

feat: add items and renderer to dashboard

---

packages/popover/src/vaadin-popover.d.ts
packages/popover/src/vaadin-popover.js
packages/popover/test/a11y.test.js
packages/popover/test/nested.test.js
packages/popover/test/timers.test.js
packages/popover/test/trigger.test.js
packages/popover/test/typings/popover.types.ts

Follow-up to https://github.com/vaadin/web-components/pull/7440
1. Added the following API related to `focusDelay`, `hoverDelay` and `hideDelay` excluded from the above PR:
- `Popover.setDefaultHoverDelay()`
- `Popover.setDefaultFocusDelay()`
- `Popover.setDefaultHideDelay()`
2. Changed default value for these properties to be `500` instead of `0` like I originally implemented.
As discussed with @rolfsmeds the popover with `hover` and `focus` triggers is likely to be used as interactive (rich) tooltip and as such, it makes sense to keep the same defaults as in `vaadin-tooltip` for the consistent UX.
- Feature

feat: align popover delay defaults and API with tooltip

---

dev/dashboard-layout.html
packages/dashboard/src/title-controller.d.ts
packages/dashboard/src/title-controller.js
packages/dashboard/src/vaadin-dashboard-layout-mixin.js
packages/dashboard/src/vaadin-dashboard-section.d.ts
packages/dashboard/src/vaadin-dashboard-section.js
packages/dashboard/test/dashboard-layout.test.ts
packages/dashboard/test/dashboard-section.test.ts
packages/dashboard/test/helpers.ts
packages/dashboard/test/typings/dashboard.types.ts
packages/dashboard/theme/lumo/vaadin-dashboard-section.js
packages/dashboard/theme/material/vaadin-dashboard-section.js
packages/dashboard/vaadin-dashboard-section.d.ts
packages/dashboard/vaadin-dashboard-section.js

Add basic `<vaadin-dashboard-section>` structure
Added API:
- `sectionTitle`: Specifies the title of the section
Automatic updating of widget title heading level will be implemented [separately](https://github.com/orgs/vaadin/projects/70/views/1?pane=issue&itemId=75965519)
Fixes https://github.com/orgs/vaadin/projects/70/views/1?pane=issue&itemId=75249405
Feature

feat: add basic dashboard section structure

---

dev/dashboard.html
packages/dashboard/src/vaadin-dashboard-section.js
packages/dashboard/src/vaadin-dashboard.d.ts
packages/dashboard/src/vaadin-dashboard.js
packages/dashboard/test/dashboard.test.ts
packages/dashboard/test/typings/dashboard.types.ts

Add sections support to `<vaadin-dashboard>`
Added API:
- `items` can now also include a section
Fixes https://github.com/orgs/vaadin/projects/70/views/1?pane=issue&itemId=75977454
Feature

feat: add sections support to vaadin-dashboard

---

packages/popover/src/vaadin-popover-target-mixin.js
packages/popover/test/trigger.test.js

Fixes #7683
This removes `target` event listeners when `vaadin-popover` is disconnected from the DOM, and restores them in case it is re-connected later. 
- Bugfix
There might be a case when `target` is set before adding `vaadin-popover` to the DOM, causing event listeners to be added twice. According to the [spec](https://www.w3.org/TR/2000/REC-DOM-Level-2-Events-20001113/events.html#Events-EventTarget-addEventListener) this is not a problem as duplicate listeners are discarded:
> If multiple identical [EventListener](https://www.w3.org/TR/2000/REC-DOM-Level-2-Events-20001113/events.html#Events-EventListener)s are registered on the same EventTarget with the same parameters the duplicate instances are discarded. They do not cause the …

fix: remove target listeners when popover is detached

---

packages/grid/src/vaadin-grid-drag-and-drop-mixin.js
packages/grid/src/vaadin-grid-mixin.js
packages/grid/test/drag-and-drop.common.js
packages/grid/test/styling.common.js

The drag-source-row-cell part was incorrectly applied and did not get updated by the grid's virtual scrolling. This PR mitigates that by having the grid check the rows against `__draggedItems` to see which should receive the part.
Fixes #7622.

fix: add and remove drag-source when scrolling

---

package.json
web-test-runner-it.config.js
web-test-runner-snapshots.config.js
web-test-runner.config.js
yarn.lock

Updated to use Puppeteer launcher which downloads Chromium instead of using globally installed Chrome.
> [!WARNING]
> Please make sure you don't have `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD` and `PUPPETEER_EXECUTABLE_PATH` env variables overridden as it might cause use an older version of Chromium instead of downloading a new one.

chore: use puppeteer launcher to run Chrome tests

---

packages/component-base/src/url-utils.js
packages/component-base/test/url-utils.test.js
packages/side-nav/src/location.js
packages/side-nav/src/vaadin-side-nav-item.d.ts
packages/side-nav/src/vaadin-side-nav-item.js
packages/side-nav/test/side-nav-item.test.js

Adds a `matchNested` property to `vaadin-side-nav-item` that allows an item to match nested paths. When enabled, then an item with the path `/users` does not only match `/users`, but also `/users/1`, `/users/1/permissions`, etc.
For context, the Flow `RouterLink` and React Router `NavLink` have similar options:
- `RouterLink` allows setting a `HighlightCondition` that determines whether the link is considered active or not. The most useful default implementations are `HighlightConditions.sameLocation` (exact match) and `HighlightConditions.locationPrefix` (match prefix).
- `NavLink` has an `end` property to force exact matching, otherwise it matches by prefix.
Note that both `RouterLink` and `NavLink` use prefix matching by default, while side nav item would keep using exact matching by …

feat: allow matching navigation hierarchies with side nav item

---

packages/tabsheet/src/vaadin-tabsheet-mixin.js
packages/tabsheet/test/tabsheet.test.js

This fixes a finding with React component reported internally on Slack:
```jsx
<TabSheet>
<Button>Close all</Button>
<TabSheetTab label="One" />
<TabSheetTab label="Two" />
<TabSheetTab label="Three" />
</TabSheet>
```
> add the missing `slot="prefix"` to `<Button>` - how come the UI is not updated with HMR but requires a refresh?
The actual problem is that the web component treats any elements without `slot` attribute as panels and then doesn’t reset `hidden` attribute when the `slot` is set (or e.g. when the element is moved to the different parent).
- Bugfix
There is an edge case with `hidden` set initially on the panel before adding it to tabsheet - it will be reset to `false` on removing. I don't think it's a big problem

fix: reset hidden state when removing panel from tabsheet

---

packages/menu-bar/src/vaadin-menu-bar-mixin.js
packages/menu-bar/test/sub-menu.common.js

Fixes https://github.com/vaadin/flow-components/issues/6580
Fixes https://github.com/vaadin/flow-components/issues/6577
The issue is caused by the fact that I removed setting `positionTarget` to `undefined` in #7524 and therefore by the first time `_updatePosition()` is called, the `positionTarget` still contains a reference to the old menu-bar button which is no longer in the DOM. And then `getBoundingClientRect().width` for this button is `0` and that closes overlay since #7454.
- Bugfix

fix: reset overlay position target to avoid closing after items change

---

packages/date-picker/src/vaadin-date-picker-helper.js
packages/date-picker/src/vaadin-lit-month-calendar.js
packages/date-picker/src/vaadin-month-calendar.js
packages/date-picker/test/dom/__snapshots__/month-calendar.test.snap.js
packages/date-picker/test/dom/month-calendar.test.js

Adds past and future parts for styling the past and future dates in the month calendar. Based on the fact that the parts `today` and `disabled` are not mutually exclusive, `past` and `future` parts can also be applied to disabled cells. It'll be up to the user to use CSS selectors in a way to get what they want.
Fixes https://github.com/vaadin/flow-components/issues/5165

feat: add past and future parts to cells in date picker calendar

---

packages/date-picker/theme/lumo/vaadin-month-calendar-styles.js

Basically just changes the CSS selectors that remove focus related styles on pointer: coarse to only work when the parent month-calendar does not have the focus-ring attribute. In other words, do not hide the focus ring when the user is keyboard navigating on a touch device.
Fixes #6381

fix: allow focus rings on pointer coarse devices

---

packages/date-picker/theme/lumo/vaadin-month-calendar-styles.js
packages/progress-bar/theme/lumo/vaadin-progress-bar-styles.js

These `@keyframes` are copied from corresponding shadow DOM styles due to the old [WebKit bug](https://bugs.webkit.org/show_bug.cgi?id=173027) with Safari not animating `::before` and `::after` correctly. The bug was fixed in 2020 which means the fix was available at least in Safari 14 released later that year, and in Safari 15 for sure. So we can safely drop these styles now. 
- Refactor

refactor: remove no longer needed global keyframes declaration

---

package.json
web-test-runner-it.config.js
web-test-runner-snapshots.config.js
web-test-runner.config.js
yarn.lock

Manual cherry-pick of ##7701 to `24.4` branch needed to make Chrome tests pass.
- Cherry-pick

chore: use puppeteer launcher to run Chrome tests (#7701) (CP: 24.4)

---

packages/grid/theme/lumo/vaadin-grid-styles.js

Decrease the resize handle area to use `--lumo-size-s` to avoid overlapping with the column sorter when the column width is reduced. It also uses the resize handle width to calculate the amount of translation in the X-axis to make it better center-aligned.
----
To test it locally, the `grid.html` file can be modified to add/change the columns to something like:
```html
<vaadin-grid-sort-column path="name" width="200px" resizable header="Long header"
flex-shrink="0"></vaadin-grid-sort-column>
<vaadin-grid-sort-column path="name" width="200px" resizable flex-shrink="0"></vaadin-grid-sort-column>
```
2Then, shrink one of the columns so it starts truncating the header title and see if the sorter can be hovered/clicked as expected.
Fixes #5637

fix: make resize handle not overlap with column sorter

---

packages/grid/src/vaadin-grid-mixin.js
packages/grid/src/vaadin-grid-scroll-mixin.js
packages/grid/test/scroll-into-view-lit.test.js
packages/grid/test/scroll-into-view-polymer.test.js
packages/grid/test/scroll-into-view.common.js

Prevents scrolling when focusing a cell via click by:
- Updating the scroll logic in scroll mixin to only take effect when the mouse is not used
- Updating a Chrome + Webkit specific workaround for focusing on click to use `focus({ preventScroll: true })` to avoid automatic scrolling by the browser
Fixes https://github.com/vaadin/web-components/issues/7684

fix: do not scroll when clicking cells

---

packages/time-picker/src/vaadin-time-picker.d.ts
packages/time-picker/src/vaadin-time-picker.js

The `vaadin-time-picker` JSDoc tables are using incorrect custom property from combo-box and lacks the property to set overlay width. Updated these to reflect the actual custom CSS properties used by the component.

docs: update time-picker custom CSS properties tables

---

packages/context-menu/src/vaadin-context-menu.d.ts
packages/context-menu/src/vaadin-context-menu.js
packages/context-menu/src/vaadin-contextmenu-items-mixin.js
packages/menu-bar/src/vaadin-menu-bar.d.ts
packages/menu-bar/src/vaadin-menu-bar.js

For some reason the `expanded` state attribute of `vaadin-context-menu-item` is mentioned in property rather than the component JSDoc, so I moved it to the right place. Also updated `vaadin-menu-bar` JSDoc accordingly.

docs: add missing docs for expanded item state attribute

---

packages/grid/src/vaadin-grid.d.ts

Follow-up to #7593
The PR above only updated the list of shadow parts in `vaadin-grid.js`, so I updated `vaadin-grid.d.ts` to align with it.

docs: add grid drag source shadow parts docs to .d.ts

---

packages/select/src/vaadin-select.d.ts

Follow-up to #7578
The PR above only updated the list of properties in `vaadin-select.js`, so I updated `vaadin-select.d.ts` to align with it.

docs: add select overlay width custom property to .d.ts

---

packages/grid/test/row-details.common.js

Usage of `dom-repeat` was removed in #5473 so this import is no longer needed.
- Test

test: remove no longer needed dom-repeat import

---

packages/form-layout/test/form-item.test.js

This import was there because of #499 (tests related to `updateStyle()` didn't pass without it).
The method and related tests were removed in #4993 but we missed to also remove this import.
- Test

test: remove no longer needed custom-style import

---

packages/date-picker/src/vaadin-date-picker.d.ts
packages/date-picker/src/vaadin-date-picker.js

Follow-up to #7691
Added `past` and `future` shadow parts to the tables in JSDoc.

docs: add past and future to the list of date-picker parts

---

packages/login/src/vaadin-lit-login-overlay-wrapper.js
packages/login/src/vaadin-lit-login-overlay.js
packages/login/src/vaadin-login-overlay-wrapper-mixin.js
packages/login/src/vaadin-login-overlay-wrapper.js
packages/login/src/vaadin-login-overlay.js
packages/login/test/dom/__snapshots__/login-overlay.test.snap.js
packages/login/test/login-overlay.common.js

Fixes #6385 
See https://github.com/vaadin/web-components/issues/6385#issuecomment-2320479429 for screen reader announcements.
- Bugfix
The change is reflected in a11y tree as the "dialog":

fix: set login overlay role to dialog, use title as aria-label

---

packages/menu-bar/src/vaadin-lit-menu-bar-button.js
packages/menu-bar/src/vaadin-menu-bar-button.js
packages/menu-bar/test/menu-bar.common.js

Fixes #7489
The code related to `z-index` was originally added when creating `vaadin-menu-bar` for Vaadin 14 due to the problem of handling clicks on root level menu items - see https://github.com/vaadin/vaadin-menu-bar/pull/69. The issue about `vaadin-menu-bar-button` consuming clicks was apparently caused by native `<button>` with `position: absolute` used by [V14 `vaadin-button`](https://github.com/vaadin/vaadin-button/blob/43d48864fd9abcd1b579d610644f29e669007d74/src/vaadin-button.html#L59-L60).
However, since in Vaadin 22 we changed `<vaadin-button>` to not use native `<button>` internally, these styles are no longer needed. Furthermore, removing them resolves the Firefox issue (which unfortunately can only be tested manually at the moment), so it seems like this rendering bug is a …

fix: remove no longer needed z-index for root menu-bar items

---

packages/menu-bar/src/vaadin-menu-bar-button.js
packages/menu-bar/test/menu-bar.test.js

Manual cherry-pick of #7743 to `24.3` branch which doesn't have Lit based version of the menu-bar.
- Cherry-pick

fix: remove no longer needed z-index for root menu-bar items (#7743) (CP: 24.3)

---

packages/dashboard/src/title-controller.js
packages/dashboard/src/vaadin-dashboard-section.js
packages/dashboard/src/vaadin-dashboard-widget.js
packages/dashboard/test/dashboard-widget.test.ts

Automatically update the title heading level of a dashboard widget. By default, root level widgets use `<h2>` and widgets inside a section use `<h3>` for the title heading.
Fixes https://github.com/orgs/vaadin/projects/70/views/1?pane=issue&itemId=75965519
Part of https://github.com/vaadin/platform/issues/6627
Feature

feat: auto-update dashboard widget title level

---

packages/dashboard/src/vaadin-dashboard-layout-mixin.js
packages/dashboard/src/vaadin-dashboard-layout.js
packages/dashboard/src/vaadin-dashboard.js
packages/dashboard/test/dashboard-layout.test.ts
packages/dashboard/test/helpers.ts

Move the dashboard CSS grid inside the host's shadow root. This enables us to resize the grid programmatically when the `ResizeMixin`'s `ResizeObserver` invokes on host size change. The change aims to eliminate flickering that might occur on component resize.
Before (CPU slowdown in use to highlight the flickering):
https://github.com/user-attachments/assets/0749e472-c6dc-4985-a4e1-c55efb7e7f59
After:
https://github.com/user-attachments/assets/ddb798a5-21f8-4a95-94a1-601ab64b7f62
Fixes https://github.com/orgs/vaadin/projects/70/views/1?pane=issue&itemId=75035546
Refactor/bugfix

refactor: move dashboard CSS grid inside shadow root

---

packages/grid/src/vaadin-grid-mixin.js
test/integration/grid-tooltip.test.js

Fixes #7744
In grids with many columns it's quite common to have cases where certain cell is not fully in the viewport due to horizontal scrolling. IMO we shouldn't show cell tooltip in this case as it might be positioned incorrectly.
Note: there is still a chance that the `vaadin-tooltip` using `bottom` or `top` position will not be fully visible as there is a more general issue: https://github.com/vaadin/web-components/issues/7744#issuecomment-2326353872. IMO that's worth extracting to the separate ticket as it needs more thinking.
- Bugfix

fix: only show tooltip if the target cell is fully visible

---

packages/popover/test/basic.test.js

The following logic is currently untested (when removing this line, tests still pass on `main` branch):
https://github.com/vaadin/web-components/blob/d8ae51196a1ded333c40e091ab07b184aa317d57/packages/popover/src/vaadin-popover.js#L900-L902
I added checks to `modal` tests as in that case, the `overlay` is closed internally and the `opened` property needs to be updated on the host accordingly (which is why we actually need this overlay `opened-change` listener).
- Test

test: ensure popover opened property is updated when closed

---

packages/component-base/src/media-query-controller.d.ts

This annotation was added when creating `MediaQueryController` in #3426. 
However, its constructor doesn't actually accept `host`, so it's likely a copy-paste from elsewhere.

docs: remove incorrect JSDoc annotation from typings

---

packages/virtual-list/src/vaadin-virtual-list.d.ts

Both `@extends` and `@mixes` annotations are only needed in `.js` files used by Polymer Analyzer, but not in `.d.ts`.

docs: remove unneeded JSDoc annotations from typings

---

packages/tabsheet/src/vaadin-tabsheet.d.ts
packages/tabsheet/src/vaadin-tabsheet.js

This link has `hhttps` which makes it broken (also the URL hasn't been updated due to that).

docs: fix broken link to styling docs in tabsheet JSDoc

---

packages/popover/README.md

Now when https://vaadin.com/docs/latest/components/popover is deployed, let's add the link to README.

docs: add link to vaadin.com docs to popover README

---

packages/tooltip/README.md

For some reason the tooltip README was lacking vaadin.com docs link so I added it.

docs: add link to vaadin.com docs to tooltip README

---

packages/icon/README.md
packages/icons/README.md

Updated "live demo" links that were outdated since "foundation" docs sections have been moved.

docs: use correct vaadin.com links in icons READMEs

---

dev/dashboard-layout.html
dev/dashboard.html
packages/dashboard/src/vaadin-dashboard-layout-mixin.js
packages/dashboard/src/vaadin-dashboard-section.js
packages/dashboard/test/dashboard-layout.test.ts
packages/dashboard/test/helpers.ts

Add minimum row height to dashboard
- Added API:
- `--vaadin-dashboard-row-min-height`: CSS variable that affects the minimum row height of the dashboard and dashboard section grid
Fixes https://github.com/orgs/vaadin/projects/70/views/1?pane=issue&itemId=78393622
Feature

feat: add minimum row height to dashboard

---

dev/dashboard.html
packages/dashboard/src/vaadin-dashboard-section.js
packages/dashboard/src/vaadin-dashboard-styles.js
packages/dashboard/src/vaadin-dashboard-widget.js
packages/dashboard/src/vaadin-dashboard.d.ts
packages/dashboard/src/vaadin-dashboard.js
packages/dashboard/src/widget-reorder-controller.js
packages/dashboard/test/dashboard-layout.test.ts
packages/dashboard/test/dashboard-widget-reordering.test.ts
packages/dashboard/test/dashboard.test.ts
packages/dashboard/test/helpers.ts
packages/dashboard/test/typings/dashboard.types.ts

Add support for DnD reordering of `<vaadin-dashboard>` widgets and sections
https://github.com/user-attachments/assets/d075811d-2713-4472-b151-d32d8c93fb09
Added API:
- `editable` if true, the widget/section header controls are visible
- Events:
- `dashboard-item-reorder-start`: Fired when item reordering starts
- `dashboard-item-reorder-end`: Fired when item reordering ends
- `dashboard-item-drag-reorder`: Fired when an items will be reordered by dragging
- `event.item`: The item being dragged
- `event.targetIndex`: The new index of the item in its host `items` array
Fixes https://github.com/orgs/vaadin/projects/70/views/1?pane=issue&itemId=74625606
Feature

feat: support drag-reordering of dashboard items

---

packages/dashboard/src/vaadin-dashboard.js
packages/dashboard/test/dashboard.test.ts

Support providing element instances in `<vaadin-dashboard>` `items`.
If an `HTMLElement` instance is passed as `item.component`
- Widget items: a `renderer` call for the item is skipped in favor of using the provided element as the widget.
- Section items: generating a `<vaadin-dashboard-section>` element internally is skipped in favor of using the provided element as the section.
This feature is added exclusively for the `Dashboard` Flow component's purposes, specifically to enable `DashboardSection` to extend `Component`, and thus doesn't include type definitions.
Feature

feat: support elements in dashboard items

---

packages/number-field/theme/lumo/vaadin-number-field-styles.js
packages/number-field/theme/material/vaadin-number-field-styles.js

I noticed that we have `fieldButton` styles applied twice in case of `vaadin-number-field` as the `inputFieldShared` already contains them for both Lumo and Material themes:
https://github.com/vaadin/web-components/blob/6f3ad57baff3a5d4c51126151bfaf98301c68539/packages/vaadin-lumo-styles/mixins/input-field-shared.js#L150
https://github.com/vaadin/web-components/blob/6f3ad57baff3a5d4c51126151bfaf98301c68539/packages/vaadin-material-styles/mixins/input-field-shared.js#L198
While it should be deduped by `ThemableMixin`, we should remove this unnecessary style.
- Refactor

refactor: remove duplicate fieldButton styles usage from number-field

---

packages/combo-box/theme/lumo/vaadin-combo-box-styles.js
packages/combo-box/theme/material/vaadin-combo-box-styles.js
packages/date-picker/theme/lumo/vaadin-date-picker-styles.js
packages/select/theme/material/vaadin-select-styles.js
packages/vaadin-material-styles/mixins/input-field-shared.js

The following styles are no longer needed in themes as they are covered by `fieldShared` styles in `src`:
https://github.com/vaadin/web-components/blob/d665940d99599dc6005aecff2107687e4aeb1430/packages/field-base/src/styles/field-shared-styles.js#L8-L12
Updated themes for some components and Material input field styles to remove them.
- Refactor

refactor: remove unnecessary theme styles covered by src

---

packages/grid-pro/src/lit/column-renderer-directives.d.ts
packages/grid-pro/test/typings/lit-renderer-directives.types.ts
packages/grid/src/lit/column-renderer-directives.d.ts
packages/grid/src/lit/renderer-directives.d.ts
packages/grid/test/typings/lit-renderer-directives.types.ts

Fixes #7780
Looks like the return type of some renderer directives was not properly evaluated since Lit enforces using `.js` extension and it was missing from several imports in `grid` and `grid-pro` packages. Adding it fixes the Lit plugin warning.
- Bugfix

fix: add missing extension to Lit directive import

---

dev/dashboard-layout.html
dev/dashboard.html
packages/dashboard/src/vaadin-dashboard-layout-mixin.js
packages/dashboard/src/vaadin-dashboard-section.js
packages/dashboard/src/vaadin-dashboard-widget.js
packages/dashboard/src/vaadin-dashboard.d.ts
packages/dashboard/src/vaadin-dashboard.js
packages/dashboard/test/dashboard-layout.test.ts
packages/dashboard/test/dashboard.test.ts
packages/dashboard/test/helpers.ts
packages/dashboard/test/typings/dashboard.types.ts

Add row spanning support for `<vaadin-dashboard-layout>` and `<vaadin-dashboard>`
- Items can span multiple rows
Added API:
`--vaadin-dashboard-item-rowspan`: Applied to a child element of a dashboard. Affects its row span in the layout grid.
Fixes https://github.com/orgs/vaadin/projects/70/views/1?pane=issue&itemId=78393707
Feature

feat: dashboard widget rowspan

---

packages/charts/src/vaadin-chart.js
packages/charts/test/private-api.test.js

Part of https://github.com/vaadin/flow-components/issues/6607
This fixes the first part of the issue (reference error when redrawing all charts instances) by checking for `undefined`.
- Bugfix

fix: filter out undefined instances when redrawing all charts

---

package.json
yarn.lock

Upgraded `@web/test-runner` to latest version including newest Puppeteer and removed pinning it from `resolutions`.
Tested locally and confirmed that switching back to `chromeLauncher` still doesn't work with Chrome 128.0.6613.120

chore: update web test runner dependencies and puppeteer

---

packages/charts/src/vaadin-chart.js
packages/charts/test/chart-element.test.js
packages/charts/test/reattach.test.js

Depends on #7779
Part of https://github.com/vaadin/flow-components/issues/6607
This is a potential fix for the second part of the issue:
>  Currently, detaching the chart from the DOM doesn't destroy it, and the gobal charts array will still reference it. This is a resource leak, and you can also reproduce this by switching back and forth between the two views 
We need to test if the Flow counterpart still works after the change (especially since there is a known issue in the Flow router where the view component moved within the DOM during initialization causing detach and re-attach).

fix!: destroy chart instance when disconnected from the DOM

---

packages/charts/src/vaadin-chart.js
packages/charts/test/private-api.test.js

Manual cherry-pick of #7779 to `24.4` branch (there was a conflict in the test file due to the import change on `main`).
- Cherry-pick

fix: filter out undefined instances when redrawing all charts (#7779) (CP: 24.4)

---

packages/form-layout/package.json
packages/form-layout/src/vaadin-form-layout.js
packages/form-layout/test/form-layout.test.js

Manual cherry-pick of #7792 to `24.4` branch (needed due to conflict in `package.json`).
- Cherry-pick

fix: do not update form-layout when it is not visible (#7792) (CP: 24.4)

---

packages/dashboard/src/widget-reorder-controller.js
packages/dashboard/test/dashboard-widget-reordering.test.ts

Avoid an error when dragging a widget while there are no other widgets in the dashboard
Bugfix

fix: do not throw on drag when dashboard has one widget

---

dev/dashboard.html
packages/dashboard/src/vaadin-dashboard-helpers.js
packages/dashboard/src/vaadin-dashboard-section.js
packages/dashboard/src/vaadin-dashboard-styles.js
packages/dashboard/src/vaadin-dashboard-widget.js
packages/dashboard/src/vaadin-dashboard.d.ts
packages/dashboard/src/vaadin-dashboard.js
packages/dashboard/src/widget-reorder-controller.js
packages/dashboard/src/widget-resize-controller.js
packages/dashboard/test/dashboard-widget-reordering.test.ts
packages/dashboard/test/dashboard-widget-resizing.test.ts
packages/dashboard/test/dashboard.test.ts
packages/dashboard/test/helpers.ts
packages/dashboard/test/typings/dashboard.types.ts

Add remove button to dashboard widget and section
The selection feature, which will allow focusing the remove button, is to be added later
Fixes https://github.com/orgs/vaadin/projects/70/views/1?pane=issue&itemId=79677729
Added API:
- Events:
- `dashboard-item-removed`: Fired when an item is removed
- `event.item`: The item being removed
- `event.items`: The updated items array of the dashboard
Feature

feat: dashboard widget remove button

---

packages/dashboard/src/vaadin-dashboard.js
packages/dashboard/test/dashboard.test.ts

Update the dashboard widget wrapper rendering so that element focus never gets lost on re-render.
Feature

feat: keep widget focus on dashboard items change

---

packages/input-container/theme/lumo/vaadin-input-container-styles.js
packages/vaadin-lumo-styles/mixins/field-button.js
packages/vaadin-lumo-styles/mixins/input-field-shared.js

The recently added custom CSS property `--vaadin-input-field-disabled-value-color` is only supposed to affect the value of the `<input>` element (or, in case of `vaadin-select`, of the selected item). But it also applies to prefix and suffix:
So I updated `::slotted(*)` to be `::slotted(:not([slot$='fix']))` (which covers both `prefix` and `suffix` slots).
Note: some users might expect `--lumo-disabled-text-color` to be applied to their custom `prefix` icons etc, so I figured out we can use it still for backwards compatibility with `24.4` which uses this CSS:
https://github.com/vaadin/web-components/blob/fb99836f8969f84e50c93356028cc7f7552ca7cf/packages/vaadin-lumo-styles/mixins/input-field-shared.js#L93-L96
- Bugfix

fix: do not apply disabled value color to prefix and suffix

---

packages/dashboard/src/vaadin-dashboard-helpers.js
packages/dashboard/src/vaadin-dashboard-section.js
packages/dashboard/src/vaadin-dashboard-styles.js
packages/dashboard/src/vaadin-dashboard-widget.js
packages/dashboard/src/vaadin-dashboard.js
packages/dashboard/test/dashboard-widget-reordering.test.ts
packages/dashboard/test/dashboard.test.ts
packages/dashboard/test/helpers.ts

This PR refactors the dashboard to synchronize the widget/section state (`editable` / `dragging` for now) via wrapper attributes instead of using the clunky CSS property approach.
Refactor

refactor: use attributes for widget/section state

---

packages/component-base/src/define.d.ts
packages/component-base/src/define.js
test/integration/define.test.js

This fixes an error with version listed as `undefined` when trying to re-define the same class with a different version:
```
Tried to define vaadin-iconset version undefined when version 24.5.0-alpha11 is already in use. Something will probably break.
console.error @ (index):5
defineCustomElement @ define.js:23
```
The issue is a regression from #6568 where I moved the version number from `static get version()` (always available) to be hardcoded in the `defineCustomElement` (only available for the first custom element definition).
The fix is to always define a version getter, regardless of whether the custom element is already defined or not.
- Bugfix

fix: always define custom element class version getter

---

packages/notification/src/vaadin-notification.d.ts
packages/notification/src/vaadin-notification.js
packages/notification/test/dom/__snapshots__/notification.test.snap.js
packages/notification/test/dom/notification.test.js
packages/notification/test/notification.test.js
packages/notification/test/statichelper.test.js
packages/notification/test/typings/notification.types.ts

Fixes #5768
Added `assertive` property to customize `aria-live` attribute of the notification card.
- Feature

feat: add assertive property to notification

---

dev/dashboard.html
packages/dashboard/src/keyboard-controller.js
packages/dashboard/src/vaadin-dashboard-helpers.js
packages/dashboard/src/vaadin-dashboard-section.js
packages/dashboard/src/vaadin-dashboard-styles.js
packages/dashboard/src/vaadin-dashboard-widget.js
packages/dashboard/src/widget-reorder-controller.js
packages/dashboard/src/widget-resize-controller.js
packages/dashboard/test/dashboard-keyboard.test.ts

Dashboard keyboard interactions as described [here](https://docs.google.com/spreadsheets/d/1cVXgRLIPqF0kFWKGTAmSITFRcizajP_pc9d5jEl9OvQ/edit?gid=523479405#gid=523479405).
Widget/section move-mode and resize-mode are excluded from this PR and will be added separately.
Feature

feat: dashboard keyboard interactions

---

packages/dashboard/src/keyboard-controller.js
packages/dashboard/src/vaadin-dashboard-helpers.js
packages/dashboard/src/vaadin-dashboard-item-mixin.d.ts
packages/dashboard/src/vaadin-dashboard-item-mixin.js
packages/dashboard/src/vaadin-dashboard-layout-mixin.js
packages/dashboard/src/vaadin-dashboard-section.d.ts
packages/dashboard/src/vaadin-dashboard-section.js
packages/dashboard/src/vaadin-dashboard-styles.js
packages/dashboard/src/vaadin-dashboard-widget.d.ts
packages/dashboard/src/vaadin-dashboard-widget.js
packages/dashboard/src/vaadin-dashboard.js
packages/dashboard/test/dashboard-keyboard.test.ts
packages/dashboard/test/dashboard-layout.test.ts
packages/dashboard/test/dashboard-widget-reordering.test.ts
packages/dashboard/test/dashboard-widget-resizing.test.ts
packages/dashboard/test/dashboard.test.ts
packages/dashboard/test/helpers.ts

Dashboard move mode with keyboard interactions as described [here](https://docs.google.com/spreadsheets/d/1cVXgRLIPqF0kFWKGTAmSITFRcizajP_pc9d5jEl9OvQ/edit?gid=523479405#gid=523479405).
Feature

feat: dashboard widget move mode

---

packages/charts/src/vaadin-chart.js
packages/charts/test/chart-properties.test.js

Fixes #7768
Removed checks for `title`, `subtitle` and `type` property length to allow setting `null` (which is also the case when removing attribute) and added tests to ensure corresponding elements are correctly updated.
- Bugfix

fix: reset title, subtitle and type when removing attribute

---

packages/dashboard/src/keyboard-controller.js
packages/dashboard/src/vaadin-dashboard-item-mixin.js
packages/dashboard/src/vaadin-dashboard-styles.js
packages/dashboard/src/vaadin-dashboard-widget.js
packages/dashboard/src/widget-resize-controller.js
packages/dashboard/test/dashboard-keyboard.test.ts
packages/dashboard/test/helpers.ts

Dashboard resize mode with keyboard interactions as described [here](https://docs.google.com/spreadsheets/d/1cVXgRLIPqF0kFWKGTAmSITFRcizajP_pc9d5jEl9OvQ/edit?gid=523479405#gid=523479405).
Feature

feat: dashboard widget resize mode

---

packages/dashboard/test/dashboard-layout.test.ts
packages/dashboard/test/dashboard-widget-reordering.test.ts
packages/dashboard/test/dashboard-widget-resizing.test.ts
packages/dashboard/test/dashboard.test.ts
packages/dashboard/test/helpers.ts

Use a `onceResized` test helper instead of relying on the `ResizeObserver` to run on the next frame after resizing the host. This will especially stabilize Webkit tests on Windows.
Tests

test: stabilize dashboard tests with onceResized helper

---

packages/crud/test/not-animated-styles.js
packages/crud/test/visual/lumo/crud.test.js
packages/crud/test/visual/material/crud.test.js

Part of #7823
Turned out that `vaadin-confirm-dialog` visual tests were still using `vaadin-dialog-overlay` in `not-animated-styles` which needed to be updated since #6141. And `vaadin-crud` visual tests didn't have this file to disable animations at all 😕 
- Tests

test: disable animation in confirm-dialog and CRUD tests

---

packages/checkbox-group/test/visual/common.js
packages/checkbox-group/test/visual/lumo/checkbox-group.test.js
packages/checkbox-group/test/visual/material/checkbox-group.test.js
packages/checkbox/test/visual/common.js
packages/checkbox/test/visual/lumo/checkbox.test.js
packages/checkbox/test/visual/material/checkbox.test.js
packages/combo-box/test/visual/common.js
packages/custom-field/test/visual/common.js
packages/custom-field/test/visual/lumo/custom-field.test.js
packages/custom-field/test/visual/material/custom-field.test.js
packages/date-picker/test/visual/common.js
packages/date-time-picker/test/visual/common.js
packages/multi-select-combo-box/test/visual/common.js
packages/number-field/test/visual/common.js
packages/radio-group/test/visual/common.js
packages/radio-group/test/visual/lumo/radio-group.test.js
packages/radio-group/test/visual/material/radio-group.test.js
packages/select/test/visual/common.js
packages/select/test/visual/lumo/select.test.js
packages/select/test/visual/material/select.test.js
packages/text-field/test/visual/common.js
packages/time-picker/test/visual/common.js

Part of #7823 
This should fix the following errors where the screenshot seems to be taken while error message transition is in progress:
```
❌ multi-select-combo-box > error message
Error: Screenshot is not the same width and height as the baseline. Baseline: { width: 212, height: 124 } Screenshot: { width: 212, height: 121 }
at async Ka.<anonymous> (packages/multi-select-combo-box/test/visual/lumo/multi-select-combo-box.test.js:73:5)
❌ text-area > error message
Error: Screenshot is not the same width and height as the baseline. Baseline: { width: 212, height: 146 } Screenshot: { width: 212, height: 138 }
at async n.<anonymous> (packages/text-area/test/visual/lumo/text-area.test.js:74:5)
```
- Tests

test: disable error-message transition in visual tests

---

packages/field-highlighter/test/visual/common.js

Part of #7823
This disables the following `opacity` transition which currently causes some visual tests to fail:
https://github.com/vaadin/web-components/blob/d930b7c50ef59df967f38ca2f9701571b23428e2/packages/field-highlighter/src/vaadin-user-tag.js#L34
| Baseline | Failed |
| -------- | -------|
| ![checkbox-group](https://github.com/user-attachments/assets/11c01c4b-e706-4c42-999e-7d571838981c) | ![checkbox-group](https://github.com/user-attachments/assets/7665427b-421a-4ff4-b82a-67bd19748b73) |
- Tests

test: disable user tag opacity transition in visual tests

---

packages/field-highlighter/test/visual/common.js

Follow-up to #7831 - I used `vaadin-user-tags` instead of `vaadin-user-tag` 🤦‍♂️ 
This is also fixed in cherry-pick PRs so no need to backport this to `24.4` and `24.5`.
- Test

test: use correct tag name in field highlighter visual tests

---

.github/workflows/visual-tests.yml

Updated the `nick-fields/retry` action to [v3](https://github.com/nick-fields/retry/releases/tag/v3.0.0) to get rid of the following warning:
```
The following actions use a deprecated Node.js version and will be forced to run on node20: nick-fields/retry@v2. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
```

chore: update retry GitHub action to v3 using Node 20

---

dev/dashboard.html
packages/dashboard/src/vaadin-dashboard.d.ts
packages/dashboard/src/vaadin-dashboard.js
packages/dashboard/src/widget-reorder-controller.js
packages/dashboard/src/widget-resize-controller.js
packages/dashboard/test/dashboard-keyboard.test.ts
packages/dashboard/test/dashboard-widget-reordering.test.ts
packages/dashboard/test/dashboard-widget-resizing.test.ts
packages/dashboard/test/typings/dashboard.types.ts

Refactor the dashboard events as decided [here](https://docs.google.com/spreadsheets/d/16_kVgACKa3zjQkFc1inXx8j7ONlN8Vn9ACP4-WGWVFA/edit?gid=1171535532#gid=1171535532)
Refactor

refactor: update dashboard events

---

packages/dashboard/src/widget-reorder-controller.js
packages/dashboard/test/dashboard-widget-reordering.test.ts

There's an issue where the dragged widget doesn't always switch places with the widget under the drag coordinates.
https://github.com/user-attachments/assets/7d5a9cf0-f17a-44e0-bb1e-1a53a8190896
Currently, only the closest widget to the drag coordinates (based on its center point) is considered for switching during a drag event. This PR fixes the issue by prioritizing the widget directly under the drag coordinates as the primary candidate for switching. The closest widget is only treated as a secondary candidate (when dragging over empty space).
Bugfix

fix: primarily reorder with the dragged over dashboard item

---

packages/dashboard/src/vaadin-dashboard-item-mixin.d.ts
packages/dashboard/src/vaadin-dashboard-item-mixin.js
packages/dashboard/src/vaadin-dashboard-section.d.ts
packages/dashboard/src/vaadin-dashboard-section.js
packages/dashboard/src/vaadin-dashboard-widget.d.ts
packages/dashboard/src/vaadin-dashboard-widget.js
packages/dashboard/src/vaadin-dashboard.d.ts
packages/dashboard/src/vaadin-dashboard.js
packages/dashboard/test/dashboard-section.test.ts
packages/dashboard/test/dashboard-widget.test.ts
packages/dashboard/test/dashboard.test.ts
packages/dashboard/test/typings/dashboard.types.ts

Add dashboard i18n object
Fixes https://github.com/orgs/vaadin/projects/70/views/1?pane=issue&itemId=80724405
Added API:
```js
dashboard.i18n: {
selectWidgetTitleForEditing: string;
selectSectionTitleForEditing: string;
remove: string;
move: string;
moveApply: string;
moveForward: string;
moveBackward: string;
resize: string;
resizeApply: string;
resizeShrinkWidth: string;
resizeGrowWidth: string;
resizeShrinkHeight: string;
resizeGrowHeight: string;
}
```
Feature

feat: dashboard i18n

---

packages/dashboard/src/vaadin-dashboard-item-mixin.d.ts
packages/dashboard/src/vaadin-dashboard-item-mixin.js
packages/dashboard/src/vaadin-dashboard-section.d.ts
packages/dashboard/src/vaadin-dashboard-section.js
packages/dashboard/src/vaadin-dashboard-widget.d.ts
packages/dashboard/src/vaadin-dashboard-widget.js
packages/dashboard/src/vaadin-dashboard.d.ts
packages/dashboard/src/vaadin-dashboard.js
packages/dashboard/test/dashboard-section.test.ts
packages/dashboard/test/dashboard-widget.test.ts
packages/dashboard/test/dashboard.test.ts
packages/dashboard/test/typings/dashboard.types.ts

Hide `i18n`API from dashboard widget and section. For now, the dashboard should have the only user-facing API for localizing the widgets/sections.
Refactor

refactor: hide dashboard widget and section i18n

---

packages/grid-pro/src/vaadin-grid-pro-inline-editing-mixin.js
packages/grid-pro/test/edit-column-lit.test.js
packages/grid-pro/test/edit-column-polymer.test.js
packages/grid-pro/test/edit-column.common.js
packages/grid-pro/test/keyboard-navigation.common.js
test/integration/grid-pro-custom-editor.test.js

Part of https://github.com/vaadin/web-components/issues/7796
Fixes #7108
Updated the logic on <kbd>Tab</kbd> to not call `event.preventDefault()` and move focus synchronously as this doesn't handle the case when custom editor component is updating its value on blur (this is how e.g. `vaadin-date-picker` works).
Instead, we now let the browser handle the <kbd>Tab</kbd> key press so that the `focusout` event is caused by that, and wait for it to be fired (unless the event is from `vaadin-select-overlay` in which case we still handle it manually).
Note, the focus is still moved to the next cell by the logic in `_switchEditCell()` after the `focusout` so the keyboard navigation works as expected. I had to update tests from `tab()` helper to use `sendKeys()` to verify this fix.
Also added the …

fix: wait for editor focusout on Tab to get updated value

---

packages/combo-box/src/vaadin-combo-box-light.js
packages/combo-box/src/vaadin-combo-box-mixin.js
packages/combo-box/src/vaadin-combo-box-overlay-mixin.js
packages/combo-box/src/vaadin-combo-box.js
packages/combo-box/src/vaadin-lit-combo-box-light.js
packages/combo-box/src/vaadin-lit-combo-box.js
packages/combo-box/test/interactions.common.js
packages/date-time-picker/test/basic.test.js
test/integration/grid-pro-custom-editor.test.js

Fixes #4148
An alternative approach to #7845 which is better since it doesn't affect programmatic `blur()` and only concerns outside click. By preventing `mousedown` event we ensure no `focusout` is fired at all so the focus remains in the `<input>`.
This means that the `focus-ring` attribute is also preserved (see the issue referenced above).
Also, there is no need to use `restoreFocusOnClose` with this change so I have removed it for now.
- Bugfix / refactor

fix!: prevent focusout when closing combo-box on outside click

---

packages/multi-select-combo-box/test/chips.test.js

Added an assertion to the test since current it is unreliable - after removing the following line, it still passes:
https://github.com/vaadin/web-components/blob/5c59e40013bdaa9add262222678858cd2014821e/packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js#L26
This is because when custom property is not set, `max-width` isn't set either and the equality check returns `true`.
- Test

test: ensure chip min-width custom CSS property to be set

---

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.d.ts
packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js
packages/multi-select-combo-box/test/chips.test.js

I think this was missing from: https://github.com/vaadin/web-components/pull/6702

fix: add missing CSS property for chip min-width

---

test/integration/grid-pro-custom-editor.test.js

Added `vaadin-date-time-picker` column to grid-pro integration test with some TODOs to be fixed by #7858
In particular, switching pickers by pressing <kbd>Tab</kbd> currently stops cell editing on `focusout` which is a bug.
Before V22 it was working as `vaadin-date-time-picker` inherited `internal-tab` event from `vaadin-custom-field`.
However, after we refactored it to not depend on `vaadin-custom-field` using it in grid-pro became broken.
Also removed "first name" and "last name" columns as they aren't needed by this test and to make all columns fit.
- Test

test: add date-time-picker editor to grid-pro integration test

---

packages/dashboard/src/vaadin-dashboard-widget.js
packages/dashboard/src/vaadin-dashboard.js
packages/dashboard/test/dashboard.test.ts
packages/dashboard/test/helpers.ts

When the dashboard widget including focus gets removed (for any reason), restore the focus to the widget closest to the removed one.
https://github.com/user-attachments/assets/8ed06993-6881-4b28-afb5-35cd414eec92
Feature

feat: restore focus on dashboard widget removal

---

dev/dashboard.html
packages/dashboard/src/vaadin-dashboard-item-mixin.js
packages/dashboard/src/vaadin-dashboard.d.ts
packages/dashboard/src/vaadin-dashboard.js
packages/dashboard/test/dashboard-keyboard.test.ts
packages/dashboard/test/typings/dashboard.types.ts

Add selected, move mode and resize mode change events to dashboard.
Added events:
- 'dashboard-item-selected-changed': Fired when an item selected state changed
- `event.detail.item`: The item
- `event.detail.value`: The new selected state of the widget representing the item
- 'dashboard-item-move-mode-changed': Fired when an item move mode changed
- `event.detail.item`: The item
- `event.detail.value`: The new move mode state of the widget representing the item
- 'dashboard-item-resize-mode-changed': Fired when an item resize mode changed
- `event.detail.item`: The item
- `event.detail.value`: The new resize mode state of the widget representing the item
Feature

feat: add dashboard item mode changed events

---

packages/grid-pro/src/vaadin-grid-pro-edit-column-mixin.js
packages/grid-pro/src/vaadin-grid-pro-inline-editing-mixin.js
packages/grid-pro/test/keyboard-navigation.common.js
test/integration/grid-pro-custom-editor.test.js

Follow-up to #7858
Based on the suggestion from https://github.com/vaadin/web-components/pull/7858#pullrequestreview-2328002335 we no longer need logic for `internal-tab` event in `vaadin-grid-pro` since `vaadin-custom-field` component has it covered by its `_shouldRemoveFocus()` implementation.
Removed that code and added `vaadin-custom-field` to the `vaadin-grid-pro` integration test file.
Also refactored that test to only create single column per test suite to make sure it fits into viewport.
- Refactor

refactor: remove no longer needed internal-tab event workaround

---

packages/dashboard/src/vaadin-dashboard-helpers.js
packages/dashboard/src/vaadin-dashboard.d.ts
packages/dashboard/src/vaadin-dashboard.js
packages/dashboard/src/widget-reorder-controller.js
packages/dashboard/src/widget-resize-controller.js
packages/dashboard/test/dashboard.test.ts
packages/dashboard/test/typings/dashboard.types.ts

By default, use `item.id` for identifying a dashboard item. This is primarily used by the rendering logic to determine whether it should reuse an existing widget wrapper( based on the item it was previously rendered with).
Feature

feat: identify dashboard items by id

---

packages/select/src/vaadin-select-base-mixin.js
packages/select/test/select.common.js

Fixes #7873
By setting `pointer-events: auto` it is currently possible to make `vaadin-select` flash opening on click since we don't check for `disabled` property in click listener. After adding the check, I also noticed that `vaadin-select-value-button` still receives focus which also means the same problem can happen on pressing <kbd>Enter</kbd> so I updated `keydown` listener too.
- Bugfix
I think it's weird that `focused` is set on the select and value button when setting `pointer-events: auto` on the host.
Disabled component shouldn't receive focus in any case. I'll make a separate PR to address that problem.

fix: prevent opening select on click or keydown when disabled

---

packages/dashboard/src/vaadin-dashboard.js
packages/dashboard/test/dashboard.test.ts

Make sure the focused widget remains in the viewport when dashboard's `items` array changes:
https://github.com/user-attachments/assets/968fe97f-b6d4-42e5-9fe3-e4e97a824658
Feature

feat: scroll focused dashboard widget into view

---

packages/dashboard/src/vaadin-dashboard-helpers.js
packages/dashboard/src/vaadin-dashboard-item-mixin.js
packages/dashboard/src/vaadin-dashboard-styles.js
packages/dashboard/src/vaadin-dashboard.js
packages/dashboard/test/dashboard-widget-reordering.test.ts

Native DnD doesn't work with draggable `<button>` elements on Firefox which effectively makes the Dashboard widgets not mouse-draggable.
Use the workaround described [here](https://stackoverflow.com/a/55019027/3409629) to fix the issue.
Bugfix

fix: make dashboard draggables work on firefox

---

packages/vaadin-lumo-styles/gulpfile.cjs
packages/vaadin-material-styles/gulpfile.cjs

Updated `gulpfile.js` for Material theme to match the file content (this should have been done in #5752).
Also fixed the formatting in the corresponding Lumo theme `gulpfile.js` to not cause Prettier warnings.
To test this, run `yarn icons` and check that there are no files changed shown by `git diff`.

chore: fix gulp tasks for generating font-icons files

---

packages/dashboard/src/vaadin-dashboard-layout-mixin.d.ts
packages/dashboard/src/vaadin-dashboard-layout-mixin.js
packages/dashboard/test/dashboard-layout.test.ts
packages/dashboard/test/typings/dashboard.types.ts

This PR renames the `dense` property to `denseLayout`.
Refactor

refactor: rename dense to dense layout

---

packages/custom-field/src/vaadin-custom-field-mixin.js
packages/custom-field/test/custom-field.common.js

Currently, in the Polymer version the `has-value` isn't set due to `__settingValue` check in the observer. This PR fixes that.
- Bugfix

fix: ensure has-value attribute is set on custom-value

---

packages/custom-field/src/vaadin-custom-field-mixin.js
packages/custom-field/test/custom-field.common.js
test/integration/custom-field-lazy-inputs.test.js

Fixes #7871
Added logic to store the `value` property set initially and apply it to inputs after they are populated.
Also added integration tests to cover the case when inputs are not yet upgraded (only happens for Vaadin web components but works with native `<input>` elements, see the issue description).
- Bugfix

fix: apply initially set custom field value to inputs

---

packages/custom-field/src/vaadin-custom-field.d.ts
packages/custom-field/src/vaadin-custom-field.js

The `internal-tab` event was originally designed to be used by `vaadin-date-time-picker` (which no longer depends on `vaadin-custom-field` since V22) and inside `vaadin-grid-pro` (this was removed in #7870).
Marked this event tab as deprecated and removed `@fires` annotations to avoid code completion in VSCode Lit plugin.
Note, there is no `@event` annotation for it which means this event is not exposed in API docs / React wrappers.
- Deprecation

docs!: deprecate internal-tab event and remove it from JSDoc

---

yarn.lock

The PR to replace #7848 which didn't pass visual tests due to not having access to Sauce credentials.

chore: bump rollup from 4.13.0 to 4.22.4

---

dev/dashboard-layout.html
dev/dashboard.html
packages/dashboard/src/vaadin-dashboard-widget.js

This PR renames the `header` slot to `header-content`.
Refactor

refactor: rename header slot to header content

---

packages/dashboard/src/vaadin-dashboard-layout-mixin.d.ts
packages/dashboard/src/vaadin-dashboard-layout-mixin.js
packages/dashboard/src/vaadin-dashboard-layout.d.ts
packages/dashboard/src/vaadin-dashboard-layout.js
packages/dashboard/src/vaadin-dashboard-section.d.ts
packages/dashboard/src/vaadin-dashboard-section.js
packages/dashboard/src/vaadin-dashboard-widget.d.ts
packages/dashboard/src/vaadin-dashboard-widget.js
packages/dashboard/src/vaadin-dashboard.d.ts
packages/dashboard/src/vaadin-dashboard.js

This PR adds JSDocs for 
- Dashboard
- Dashboard layout
- Dashboard widget
- Dashboard section
Docs/Chore

docs: add dashboard jsdocs

---

packages/dashboard/src/vaadin-dashboard-layout.d.ts
packages/dashboard/src/vaadin-dashboard-layout.js
packages/dashboard/src/vaadin-dashboard.d.ts
packages/dashboard/src/vaadin-dashboard.js
packages/dashboard/test/helpers.ts

This PR
- updates the dashboard spacing related JSDocs to further clarify what it does 
- fixes the incorrect description for `--vaadin-dashboard-row-min-height`
Docs / chore

docs: update spacing related jsdocs

---

packages/field-base/src/input-control-mixin.js

Starting from #2519 the `_onChange` listener was moved to `InputConstraintsMixin` and its code is exactly the same in `InputControlMixin` which uses that mixin internally. So there is no point in overriding it anymore.
- Refactor

refactor: remove duplicate change event listener override

---

packages/date-time-picker/src/vaadin-date-time-picker.js
packages/date-time-picker/test/validation.test.js

Fixes #7906
Similar to the fix for `vaadin-select` previously implemented in #4201 - `vaadin-date-time-picker` also doesn't use `InputConstraintsMixin` and therefore needs to call `validate()` when setting `required` to `false`.
- Bugfix

fix: validate date-time-picker when required is set to false

---

packages/date-picker/vaadin-lit-date-picker-light.d.ts
packages/date-picker/vaadin-lit-date-picker-light.js

These files were added in https://github.com/vaadin/web-components/pull/6801 with the regular `vaadin-lit-date-picker.js`
However, there is no Lit based version of `vaadin-date-picker-light` yet.
Removed these as importing them would simply cause applications to break.
- Bugfix

fix: remove not working vaadin-lit-date-picker-light entrypoint

---

packages/grid/src/vaadin-grid-mixin.d.ts

Fixed some duplicate imports reported when trying `vaadin/imports` preset from `eslint-config-vaadin` locally.
- Refactor

refactor: simplify type imports in GridMixin typings

---

packages/polymer-legacy-adapter/template-renderer.js

Updated this file to align with `index.js` and `style-modules.js` in the same package.
While current `export` seems to work with native ES modules the `eslint-plugin-import` reports a warning:
```
/Users/serhii/vaadin/web-components/packages/polymer-legacy-adapter/template-renderer.js
6:15  error  No named exports found in module './src/template-renderer.js'
```
- Refactor

refactor: use correct import in template-renderer entrypoint

---

packages/combo-box/src/vaadin-combo-box-scroller.d.ts

Found this incorrect import when trying `vaadin/imports` preset for ESLint config locally.
- Bugfix

fix: use correct ComboBoxScrollerMixin import in typings

---

packages/custom-field/test/validation-lit.test.js
packages/custom-field/test/validation-polymer.test.js
packages/custom-field/test/validation.common.js

For some reason there was no Lit version of `validation.test.js` for `vaadin-custom-field`. This PR fixes that.
- Test

test: update custom-field validation tests to also use Lit

---

packages/custom-field/src/vaadin-custom-field-mixin.js
packages/custom-field/test/validation.common.js

Fixes #7905 
Same as #7908 but for `vaadin-custom-field`.
- Bugfix

fix: validate custom-field when required is set to false

---

packages/confirm-dialog/src/vaadin-confirm-dialog-base-mixin.d.ts

Found this issue when testing `vaadin/imports` preset from `eslint-config-vaadin`.
Note: this is an internal mixin used by `vaadin-confirm-dialog-dialog` which doesn't have its own typings.
- Bugfix

fix: use correct class name in confirm-dialog typings

---

packages/rich-text-editor/src/vaadin-rich-text-editor-mixin.js
packages/rich-text-editor/test/attach-lit.test.js
packages/rich-text-editor/test/attach-polymer.test.js
packages/rich-text-editor/test/attach.common.js
packages/rich-text-editor/test/basic.common.js

In Firefox, the styles won't be computed properly if an element is attached to the DOM, but not rendered (e.g., it's placed as a child element of another element that does not define a slot). That leads to an issue with RTE if the component is added as a child of a Lit element. The reason is that a `LitElement` renders its DOM asynchronously, so for a brief moment, their children are attached while the template is not yet ready.
That's problematic for RTE while using `dangerouslySetHtmlValue` before the element is fully rendered in the page because this method uses the clipboard `Quill` feature, that in turn, uses `getComputedStyle` to parse the `HTML` snipped provided into the delta format used by `Quill`. Since `getComputedStyle` won't return the correct styles in the mentioned …

fix: delay parsing htmlValue when RTE is attached but not rendered

---

packages/select/src/vaadin-lit-select-list-box.js
packages/select/src/vaadin-select-list-box.js

When changing `vaadin-select-list-box` to not extend `vaadin-list-box` I added the export to the `.d.ts` file.
However, the corresponding JS class isn't exported, unlike `SelectItem` and e.g. `ContextMenuListBox`.
Added the export to make importing the component possible and align with other similar components.
- Bugfix

fix: add missing export for SelectListBox element class

---

packages/checkbox-group/src/vaadin-checkbox-group-mixin.js
packages/checkbox-group/test/checkbox-group.common.js
packages/checkbox-group/test/validation.common.js

Updated some logic in `vaadin-checkbox-group` to not throw error when `value` is set to `null` (which is technically possible to do from JS even though we enforce the property type in `.d.ts` to be an array of strings).
- Bugfix

fix: do not throw when setting checkbox-group value to null

---

packages/list-box/package.json
packages/list-box/src/vaadin-lit-list-box.d.ts
packages/list-box/src/vaadin-lit-list-box.js
packages/list-box/test/list-box-lit.test.js
packages/list-box/test/list-box-polymer.test.js
packages/list-box/test/list-box.common.js

Added Lit based version of `vaadin-list-box` (note, the `MultiSelectListMixin` already has tests running with Lit).
- Experiment
I didn't add `_checkImport()` logic for now, could be done if we want to preserve it after #7936 is merged.

experiment: add Lit based version of vaadin-list-box

---

packages/popover/src/vaadin-popover.d.ts
packages/popover/src/vaadin-popover.js

Fixed some incorrect JSDoc (which was actually a copy-paste from Tooltip, will cover that in a separate PR).

docs: fix popover JSDoc to use correct parameter name

---

packages/tooltip/src/vaadin-tooltip-mixin.js
packages/tooltip/src/vaadin-tooltip.d.ts

Same as #7938 but for `vaadin-tooltip`.

docs: fix tooltip JSDoc to use correct parameter name
