packages/scroller/src/vaadin-scroller.js
=> fix: add missing .js extension to ScrollerMixin import

packages/dashboard/src/vaadin-dashboard.js, packages/dashboard/test/dashboard.test.ts
Follow up for https://github.com/vaadin/web-components/pull/7875
Seems that the original [PR](https://github.com/vaadin/web-components/pull/7875) missed one final commit and the revision that got merged didn't actually work as the video in the PR description shows.
This PR restores the final commit which covers the case in which the focused widget ends up outside the browser's viewport while still remaining inside the dashboard's viewport.
Bugfix
=> fix: scroll focused dashboard widget into view

packages/dashboard/src/keyboard-controller.js, packages/dashboard/src/vaadin-dashboard-styles.js, packages/dashboard/test/dashboard-keyboard.test.ts
When the dashboard is set non-editable while a widget is focused / in move or resize mode, make sure to also hide the mode controls.
Fixes https://github.com/vaadin/web-components/issues/7951
Bugfix
=> fix: hide non-editable dashboard widget mode controls

dev/dialog.html, packages/dialog/src/vaadin-dialog-draggable-mixin.js, packages/dialog/test/draggable-resizable.common.js
Change the behavior of which properties the `DialogDraggableMixin` sets on drag. Before, the `_startDrag` listener would set the initial bounds using the `top`, `left`, `width`, and `height` values, which could cause some unexpected behaviors as described in #436. With this change, only the `top` and `left` properties are set when the user drags the Dialog overlay.
>[!WARNING]
> Marking it as a breaking change, as this could potentially create some unexpected behaviors, especially if the developer defines a size for the `<vaadin-dialog-overlay>` component as can be seen in more details [on this comment](https://github.com/vaadin/web-components/issues/1060#issuecomment-2402046205).
Part of #1060
Fix #436
- Bugfix
=> fix!: only set top and left properties on drag

packages/grid/src/vaadin-grid-scroll-mixin.js
Converted `_rowWithFocusedElement` from a class property to a local variable, as it's not used anywhere else. Also, removed the related `focusout` listener.
=> refactor: convert class property to local variable

packages/grid/src/vaadin-grid-selection-column-mixin.js, packages/grid/src/vaadin-grid-selection-mixin.js, packages/grid/test/selection.common.js
Use `getItemId` when comparing items from `selectedItems` with items from the data provider, instead of comparing by reference.
=> fix: use item id provider when comparing selected items

packages/component-base/src/virtualizer-iron-list-adapter.js, packages/component-base/test/virtualizer-variable-row-height.test.js
The iron list core uses the optimal physical size (`_optPhysicalSize`) when determining whether to increase the item pool. For the cases where some items are much larger than the average, the iron list core might not increase item pool. This can lead to the large item not being rendered.
This PR overrides the getter for `_optPhysicalSize` from iron list core and adds an item height buffer whenever necessary.
The calculation for the extra item buffer is based on the calculation of the regular buffer, which is `_viewportHeight * (_maxPages - 1)`. `_maxPages` is 1.3 in our case. So there is a buffer with a height of  `_viewportHeight * 0.15` each for top and bottom. If the item heights are varied, then the extra buffer of `maxItemHeight - _viewportHeight * 0.15` is added to the optimal …
=> fix: preserve large items when new items are added

packages/form-layout/src/vaadin-form-layout.js, packages/form-layout/test/form-layout.test.js
Fixes https://github.com/vaadin/flow-components/issues/6728
This is a fix for regression from #7792: as we no longer update layout when it's hidden, let's add `IntersectionObserver` to check the case when it becomes visible (e.g. by `hidden` attribute removed from the parent element).
- Bugfix
Can be tested with the following example:
```html
<div hidden>
<vaadin-form-layout>
<div>Foo</div>
<div>Bar</div>
</vaadin-form-layout>
</div>
import '@vaadin/form-layout';
document.querySelector('vaadin-form-layout').responsiveSteps = [{ columns: 1 }];
requestAnimationFrame(() => {
document.querySelector('div').removeAttribute('hidden');
});
</script>
```
=> fix: update form-layout when its parent becomes visible

wtr-utils.js
Added support for running individual unit test files using `--glob` argument. Can be used e.g. like this:
- Only run Lit tests: `yarn test --group combo-box --glob="*-lit"`
- Only run Polymer tests: `yarn test --group combo-box --glob="*-polymer"`
- Only run validation tests: `yarn test --group combo-box --glob="validation-*"`
=> chore: add support for specifying test files glob

packages/grid/test/helpers.js, packages/grid/test/keyboard-interaction-mode-lit.test.js, packages/grid/test/keyboard-interaction-mode-polymer.test.js, packages/grid/test/keyboard-interaction-mode.common.js, packages/grid/test/keyboard-navigation-row-focus.common.js, packages/grid/test/keyboard-navigation.common.js
- Extracted keyboard interaction mode tests into a new separate file
- Moved `getFocusedRowIndex` and `getFocusedCellIndex` helpers into the common grid helpers file
=> test: extract keyboard interaction mode tests

packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js, packages/grid/src/vaadin-grid-styles.js, packages/grid/test/helpers.js, packages/grid/test/keyboard-navigation.common.js
Fixes the issue where the focus outline repeatedly appeared on random items as the user scrolled when the actual focused item was out of view. This specifically happened if the item was focused by the mouse and a custom CSS was applied to show the focus outline on clicks:
```css
vaadin-grid::part(focused-cell)::before {
content: '';
position: absolute;
top: 0;
right: 0;
bottom: 0;
left: 0;
pointer-events: none;
box-shadow: inset 0 0 0 2px var(--lumo-primary-color-50pct);
}
```
Depends on 
- https://github.com/vaadin/web-components/pull/7977
Fixes https://github.com/vaadin/web-components/issues/7614
=> fix: ensure no focus outline when item is scrolled out of view

packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js, packages/grid/test/keyboard-navigation-row-focus.common.js
Refactor of the `_onTabKeyDown` handler in `KeyboardNavigationMixin`. 
Summary:
- Removed unnecessary conditional branches
- Explained why `preventDefault` isn't called when the next element is `this.$.table` or `this.$.focusexit`
=> refactor: simplify focus logic in Tab keydown handler

packages/custom-field/src/vaadin-custom-field-mixin.js, packages/custom-field/test/validation.common.js
Fixes https://github.com/vaadin/flow-components/issues/6739
Updated `checkValidity()` method to check that `this.inputs` and `this.value` are defined before accessing them.
- Bugfix
=> fix: prevent possible errors when inputs property is not set

packages/date-picker/src/vaadin-date-picker-helper.d.ts
Adds missing type annotation to a helper function.
=> fix: use correct type syntax in date picker helper

packages/date-picker/src/vaadin-date-picker-helper.js, packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-time-picker/src/vaadin-date-time-picker.js, packages/date-time-picker/test/basic.test.js, packages/date-time-picker/test/timezone.test.js
Currently date time picker uses Date APIs such as `setHours` / `getHours` to parse and format date and time. These APIs are timezone-aware, using the current system timezone. When that timezone uses daylight savings time (DST), entering the start date + time of DST in the component results in the component value skipping an hour, as the hour does not exist in that timezone. For example, when using CET timezone:
```js
// Parse DST start in CET timezone
const date = new Date('2024-03-31T02:00');
// 02:00 actually doesn't exist in CET on that date, so it skips to 03:00
console.log(date); // Sun Mar 31 2024 03:00:00 GMT+0200 (Mitteleuropäische Sommerzeit)
console.log(date.getHours()); // 3
```
Our components should work independent of the system timezone, and should just allow entering a date …
=> fix: use non timezone-aware date APIs in date time picker

packages/grid/src/vaadin-grid-selection-column-mixin.js, packages/grid/test/selectable-provider.common.js
Currently the select all checkbox is only hidden if the column is already part of the grid when a respective event fires. This change also hides it if a selection column is added to an existing grid.
=> fix: update select all checkbox visibility when adding column to DOM

packages/grid/src/vaadin-grid-selection-mixin.js
Removes the `is-item-selectable-changed` event from the API docs, which then hopefully fixes this issue when generating React components:
```
[dts] src/generated/Grid.ts(21,60): error TS2339: Property 'is-item-selectable-changed' does not exist on type 'GridEventMap<T1>'.
```
=> chore: do not document is-item-selectable-changed event

packages/dialog/src/vaadin-dialog-base-mixin.d.ts, packages/dialog/src/vaadin-dialog-base-mixin.js, packages/dialog/src/vaadin-dialog-draggable-mixin.js, packages/dialog/src/vaadin-dialog-overlay-mixin.js, packages/dialog/test/dialog.common.js, packages/dialog/test/draggable-resizable.common.js
Add `top` and `left` properties to `<vaadin-dialog>` to allow setting the overlay position programmatically.
Part of https://github.com/vaadin/web-components/issues/1060
Depends on #7970
- Feature
=> feat: add API to define Dialog position programmatically

packages/menu-bar/theme/lumo/vaadin-menu-bar-styles.js
Reverts vaadin/web-components#7498 because it causes MenuBar to shrink unexpectedly when used in Vaadin layouts, as reported in https://github.com/vaadin/web-components/issues/8004
=> Revert "fix: add min-width to MenuBar"

packages/dialog/src/vaadin-dialog-base-mixin.d.ts, packages/dialog/src/vaadin-dialog-base-mixin.js, packages/dialog/src/vaadin-dialog-resizable-mixin.js, packages/dialog/test/dialog.common.js, packages/dialog/test/draggable-resizable.common.js
Add `width` and `height` API to `<vaadin-dialog>` to allow defining the overlay size programmatically.
Part of https://github.com/vaadin/web-components/issues/1060
- Feature
=> feat: add API do define Dialog size programmatically

packages/upload/src/vaadin-upload-mixin.js, packages/upload/test/adding-files.common.js, packages/upload/test/helpers.js
Allows to drop folders into the upload component. Folders will be scanned recursively for files and any file found will be added to the file list for uploading. It's also possible to drop a combination of files and folders. Files are still filtered by the accept filter and any non-matching file will be discarded.
Just noting that this doesn't introduce any new concepts such as having folders as a separate entry in the upload component. This is just a shortcut for adding all files from a folder to the upload.
Part of #857
=> feat: allow dropping folders

packages/combo-box/package.json, packages/combo-box/src/vaadin-lit-combo-box-item.js, packages/combo-box/src/vaadin-lit-combo-box-light.js, packages/combo-box/src/vaadin-lit-combo-box.js, packages/combo-box/theme/material/vaadin-lit-combo-box-light.js, packages/combo-box/theme/material/vaadin-lit-combo-box.js, packages/combo-box/vaadin-lit-combo-box-light.d.ts, packages/combo-box/vaadin-lit-combo-box-light.js, packages/combo-box/vaadin-lit-combo-box.d.ts, packages/combo-box/vaadin-lit-combo-box.js
- Added import files (root entrypoints and Material)
- Lumo entrypoints were already added earlier
- Aligned disclaimer comment with other components
- Experiment
=> experiment: prepare LitElement based combo-box for publishing

packages/combo-box/package.json
As we have Lit version now, the `lit` itself should be a direct dependency rather than a dev dependency.
=> chore: move Lit from combo-box devDependencies to dependencies

packages/grid/src/vaadin-grid-drag-and-drop-mixin.js, packages/grid/src/vaadin-grid-mixin.js, packages/grid/test/drag-and-drop.common.js, packages/virtual-list/src/vaadin-virtual-list-mixin.js, packages/virtual-list/test/drag-and-drop-lit.test.js, packages/virtual-list/test/drag-and-drop-polymer.test.js, packages/virtual-list/test/drag-and-drop.common.js
Chromium based browsers cannot properly generate drag images for elements that have children with massive heights. Chrome is prone to crashing while Safari slows down when a grid or virtual list with 1000+ items is dragged.
This PR temporarily sets the max height for items scroll containers to 0 when the "dragstart" event is fired. This prevents the crashes and slowdowns. This workaround also handles the case when a parent is dragged instead of the element itself.
The cutoff for applying the workaround is 20000px, and is based on experimentation with the parameters that cause the issues.
Fixes #7985
=> fix: exclude items from drag image for large scrollers

packages/dialog/src/vaadin-dialog-draggable-mixin.js, packages/dialog/src/vaadin-dialog.d.ts, packages/dialog/src/vaadin-dialog.js, packages/dialog/test/draggable-resizable.common.js, packages/dialog/test/typings/dialog.types.ts
Adds a `dragged` event at the end of the drag of Dialog overlay. The event is particularly useful for keep the `top` and `left` properties in sync with the Flow counterpart.
Part of #1060 
- Feature
=> feat: add "dragged" event in Dialog

packages/tabsheet/src/vaadin-tabsheet.js
Current implementation of `vaadin-tabsheet` imports `vaadin-tabs` in Lumo and Material, but not in `src`.
As a result, the error will be thrown when using the unstyled version as seen in https://github.com/vaadin/web-components/pull/7945#discussion_r1789579308.
- Bugfix
=> fix: import src version of vaadin-tabs in tabsheet

packages/dialog/src/vaadin-dialog-resizable-mixin.js, packages/dialog/src/vaadin-dialog.d.ts, packages/dialog/test/draggable-resizable.common.js
Add `top` and `left` to the `resize` event to make it possible to sync these values on the server on the event listener.
Part of #1060
- Feature
=> feat: add `top` and `left` to Dialog resize event detail

packages/list-box/package.json, packages/list-box/theme/lumo/vaadin-lit-list-box.js, packages/list-box/theme/material/vaadin-lit-list-box.js, packages/list-box/vaadin-lit-list-box.d.ts, packages/list-box/vaadin-lit-list-box.js
- Added missing `lit` dependency to package.json
- Experiment
=> experiment: prepare LitElement based list-box for publishing

packages/tabsheet/package.json, packages/tabsheet/src/vaadin-lit-tabsheet-scroller.js, packages/tabsheet/src/vaadin-lit-tabsheet.d.ts, packages/tabsheet/src/vaadin-lit-tabsheet.js, packages/tabsheet/src/vaadin-tabsheet-mixin.js, packages/tabsheet/test/tabsheet-lit.test.js, packages/tabsheet/test/tabsheet-polymer.test.js, packages/tabsheet/test/tabsheet.common.js
Depends on #7944
Added Lit based version of `vaadin-tabsheet`.
- Experiment
=> experiment: add Lit based version of vaadin-tabsheet

packages/grid/src/vaadin-grid-drag-and-drop-mixin.js, packages/grid/test/drag-and-drop.test.js, packages/virtual-list/src/vaadin-virtual-list.js, packages/virtual-list/test/virtual-list.test.js
Back-port of #8028 for v23.5. 
Note: Tests are an older version of the tests in the original PR. The reason is that simulating the mouse events or manually dispatching drag events do not reproduce the issue and crash the browser. It still can be manually reproduced.
=> fix: exclude items from drag image for large scrollers (#8028) (CP: 23.5)

packages/text-field/src/vaadin-text-field.js
These properties were extracted to `TextFieldMixin` in #5520 but I missed to remove them from the component.
- Refactor
=> refactor: remove duplicate property declarations from text-field

packages/date-time-picker/src/vaadin-date-time-picker.js, packages/time-picker/src/vaadin-time-picker-helper.d.ts, packages/time-picker/src/vaadin-time-picker-helper.js, packages/time-picker/src/vaadin-time-picker.d.ts, packages/time-picker/src/vaadin-time-picker.js
Extracted default implementations of `formatTime` and `parseTime` to get rid of the following Polymer API usage:
https://github.com/vaadin/web-components/blob/72f4b092db55e71542c53bd6c9fd7040817e6afb/packages/time-picker/src/vaadin-time-picker.js#L807-L817
This is a pre-requisite for extracting `vaadin-time-picker` logic into a mixin for using in LitElement version.
- Refactor
=> refactor: extract time-picker formatTime and parseTime helpers

packages/date-time-picker/src/vaadin-date-time-picker.js, packages/time-picker/src/vaadin-time-picker-helper.d.ts, packages/time-picker/src/vaadin-time-picker-helper.js, packages/time-picker/src/vaadin-time-picker.js
Follow-up to #8073
Extracted `validateTime` helper to avoid copy-pasting corresponding code in `vaadin-date-time-picker`.
- Refactor
=> refactor: extract time-picker validateTime helper to avoid duplication

packages/time-picker/src/vaadin-time-picker.js, packages/time-picker/test/time-picker.test.js
This is a pre-requisite for adding LitElement based version of `vaadin-time-picker`.
- Refactor
=> refactor: update time-picker observer to not use Polymer syntax

packages/dashboard/src/vaadin-dashboard.d.ts, packages/dashboard/test/typings/dashboard.types.ts
To make the dashboard section item typing better compatible with Hilla, remove `null` from the title type
Bugfix
=> fix: remove null from dashboard section item title type

packages/date-time-picker/test/basic.test.js, packages/date-time-picker/test/properties.test.js
We don't need to have tests for label, helper and error message `textContent` as these are covered by snapshots.
- Tests
=> test: remove date-time-picker tests covered by snapshots

packages/notification/src/vaadin-notification-mixin.d.ts
For some reason React components build fails without `.js` extension 😕 
- Bugfix
=> fix: add missing .js extension to mixin imports in typings

packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-time-picker/src/vaadin-date-time-picker.js, packages/time-picker/src/vaadin-time-picker-mixin.js
Exposed defaults to avoid getting `i18n` values from `DatePicker` and `TimePicker` prototypes.
Also changed to not use `target.set()` (Polymer API) and set the whole `i18n` object instead.
This is a pre-requisite for extracting `vaadin-date-time-picker` logic into a mixin for Lit version.
- Refactor
=> refactor: export i18n defaults for using in date-time-pickers

packages/popover/src/vaadin-popover.js, packages/popover/test/timers.test.js
Fixes https://github.com/vaadin/flow-components/issues/6750
The issue was caused by missing logic to abort opening when close is triggered (as I missed to add this logic which is present in `TooltipStateController` in the `__abortWarmup()` method).
Also, the check for `isLastOverlay()` returns false when overlay is not yet opened, so I had to modify that as well.
- Bugfix
=> fix: do not open popover after mouseleave during hover delay

packages/popover/src/vaadin-popover-overlay.js, packages/popover/test/basic.test.js
Fixes #8016
Unlike `vaadin-dialog`, the `vaadin-popover` was missing `max-height: 100%` on the overlay part.
Also, I had to set it on the content part as well in order to make sure scrolling works properly.
Note: original styles for dialog were added in https://github.com/vaadin/vaadin-dialog/pull/168 but in case of popover we need a slightly different approach since we don't have a "resizer container" element.
Here's how the resulting behavior looks like:
https://github.com/user-attachments/assets/adafaf9d-f894-4e14-84a8-030cddba83bb
- Bugfix
=> fix: set max-height on popover overlay to not overflow viewport

packages/date-time-picker/src/vaadin-date-time-picker-mixin.js
Removed logic for propagating properties to default pickers since that is covered by individual observers since https://github.com/vaadin/web-components/pull/4971. Some of these properties were removed in https://github.com/vaadin/web-components/pull/4987 but not all of them, removed remaining ones and tests still pass.
Also removed logic for time-picker `value` update on `min` change since we no longer adjust value based on `min` or `max` since V24 as of https://github.com/vaadin/web-components/pull/4987 (the original logic was there since V14 version and is no longer needed).
Also, updated logic for setting `i18n` on individual pickers to only set relevant properties using `__syncI18n()` method.
- Refactor
=> refactor: cleanup no longer needed date-time-picker logic

packages/charts/src/vaadin-chart.js, packages/charts/test/private-api.test.js
Cherry-pick needed for the following cherry-pick of the https://github.com/vaadin/web-components/pull/7785 to the 23.5 branch.
=> fix: filter out undefined instances when redrawing all charts (#7779) (CP: 23.5)

packages/charts/src/vaadin-chart.js, packages/charts/test/chart-element.test.js, packages/charts/test/reattach.test.js
Cherry-pick of #7785.
This is needed in 23.5 as it can be used as a workaround for the BFP issue reported in https://github.com/vaadin/flow-components/issues/6383 while there isn't a fix for the underlying issue in Highcharts.
Depends on #8103
=> fix!: destroy chart instance when disconnected from the DOM (#7785) (CP: 23.5)

packages/grid/src/vaadin-grid-mixin.js, packages/grid/test/hidden-grid.common.js
Fixes #8098
When the grid is initially hidden, `_headerFocusable` is set to `undefined` since there is no first visible row.
Added the call to `_resetKeyboardNavigation()` on appear and a test to ensure focus gets moved properly.
This makes the grid <kbd>Tab</kbd> navigation work in `Popover` and manually attached `Dialog`.
- Bugfix
=> fix: ensure grid has tabbable elements after it becomes visible

packages/dashboard/src/vaadin-dashboard-item-mixin.js, packages/dashboard/src/vaadin-dashboard-layout-mixin.js, packages/dashboard/src/widget-resize-controller.js, packages/dashboard/test/dashboard-keyboard.test.ts, packages/dashboard/test/dashboard-layout.test.ts, packages/dashboard/test/dashboard-widget-reordering.test.ts, packages/dashboard/test/dashboard.test.ts, packages/dashboard/test/helpers.ts
Add default min row height (12rem) to dashboard layout.
This will also enable vertical resizing of widgets by default.
Refactor/feature
=> refactor: add default min row height to dashboard

packages/notification/src/vaadin-notification-mixin.js, packages/notification/test/renderer.common.js
Fixes #8109
This fixes an issue in Lit based version (related test is Lit specific) but the error thrown can be also reproduced in Polymer when calling `requestContentUpdate()` without adding to the DOM.
- Bugfix
=> fix: do not throw on requestContentUpdate if card is not set

packages/a11y-base/src/disabled-mixin.js, packages/a11y-base/test/disabled-mixin.test.js, packages/radio-group/test/radio-group.common.js
Fixes #8111 
Updated `disabled` property to use `sync: true` for the Lit version and added missing Lit tests for the `DisabledMixin`.
Added also a new test to `radio-group` package to make sure https://github.com/vaadin/flow-components/pull/2563 also works with Lit.
- Refactor
=> refactor: make disabled property update synchronously with Lit

packages/charts/src/vaadin-chart.js, packages/charts/test/reattach.test.js
Based on https://github.com/vaadin/web-components/pull/8115#discussion_r1834317145
Decided to extract this to a separate PR, I'll rebase #8115 on top of this one.
- Bugfix / refactor
=> fix: do not reset configuration if chart is immediately re-attached

packages/charts/src/vaadin-chart.js, packages/charts/test/reattach.test.js
Manual cherry-pick of #8117 to `23.5` branch.
- Cherry-pick
=> fix: do not reset configuration if chart is immediately re-attached (CP: 23.5)

packages/charts/src/vaadin-chart-series.js, packages/charts/src/vaadin-chart.js, packages/charts/test/reattach.test.js
=> fix: reset charts series objects when chart is detached

packages/charts/src/vaadin-chart.js, packages/charts/test/reattach.test.js
Manual cherry-pick of #8117 to `24.4` branch.
- Cherry-pick
=> fix: do not reset configuration if chart is immediately re-attached (CP: 24.4)

packages/radio-group/src/vaadin-radio-group-mixin.js, packages/radio-group/test/radio-group.common.js
Currently the Lit version breaks with [read-only group](https://github.com/vaadin/flow-components/blob/9e18d5c747ac161a88c85ad8d6e57086fdab3a7c/vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/src/main/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonGroupDemoPage.java#L196) where there is an infinite loop (as far as I understand it's related to calling `rebuild()`). Changing `value` property to use `sync: true` fixes that.
Note: I though that it makes sense to also update `name` and `readonly` so that the component works consistently in terms of updating radio buttons (as e.g. `disabled` property is already using `sync` as well as `value`).
- Refactor
=> refactor: make radio-group properties use sync updates in Lit

packages/tooltip/src/vaadin-tooltip-mixin.js, packages/tooltip/test/tooltip-timers.common.js
These are two findings that I discovered while working on #8129
1. When `close()` is called twice e.g. on target `mouseleave` and then parent `mouseover`, the second call overwrites the `__closeTimeout` reference so one of the timeouts is not cleared properly on reopening and tooltip unexpectedly closes,
2. Also, aborting close only aborts `__closeTimeout` but the tooltip is not removed from the `closing` set - so before reopening, it is immediately closed by the logic that is supposed to flush other closing tooltips.
This unfortunately can't be easily reproduced with default tooltips so I had to add a test that checks the controller logic.
IMO this is fine since the controller API + `manual` mode is what we use in `vaadin-menu-bar` so we need to test it.
- Bugfix
=> fix: handle tooltip controller closing state properly

packages/component-base/src/polylit-mixin.js, packages/component-base/test/polylit-mixin.test.js
Fixes #8136
This is needed to make Grid and Virtual List connectors work. Note, I also added support for multiple dynamic observers per property as Grid connector does that for `activeItem` property to handle [selection](https://github.com/vaadin/flow-components/blob/ac0436312aae4bd55a80958420ed50d68290b28a/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.ts#L190) and [details visibility](https://github.com/vaadin/flow-components/blob/ac0436312aae4bd55a80958420ed50d68290b28a/vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.ts#L207) separately.
=> feat: add _createPropertyObserver() to PolylitMixin

package.json, yarn.lock
Bumped Stylelint and upgraded `stylelint-config-vaadin` to include https://github.com/vaadin/stylelint-config-vaadin/pull/11 and unblock https://github.com/vaadin/web-components/pull/8146. 
=> chore: upgrade Stylelint and stylelint-config-vaadin

packages/avatar-group/src/vaadin-avatar-group-styles.d.ts, packages/avatar-group/src/vaadin-avatar-group-styles.js, packages/avatar-group/src/vaadin-avatar-group.js
Extracted `vaadin-avatar-group` styles into CSS tagged literal for reusing by LitElement based version.
- Refactor
=> refactor: extract avatar-group styles into reusable css literal

packages/avatar-group/src/vaadin-avatar-group.js, packages/avatar-group/test/avatar-group.test.js, packages/avatar-group/test/dom/__snapshots__/avatar-group.test.snap.js
Removed usage of `.splice()` API from `vaadin-avatar-group` and removed `calculateSplices()` usage.
From now one, mutating `items` property is no longer supported, instead it needs to be re-assigned.
Marked as a behavior altering change because of that (but Flow counterpart shouldn't be affected).
Also updated observers syntax which is a pre-requisite for creating LitElement based version.
- Refactor
=> refactor!: update avatar group to not use Polymer splices API

packages/crud/src/vaadin-crud-dialog.js, packages/crud/src/vaadin-crud-styles.d.ts, packages/crud/src/vaadin-crud-styles.js, packages/crud/src/vaadin-crud.js
Extracted `vaadin-crud` styles into CSS tagged literal for reusing by LitElement based version.
- Refactor
=> refactor: extract crud styles into reusable css literal

packages/input-container/theme/lumo/vaadin-input-container-styles.js, packages/vaadin-lumo-styles/mixins/input-field-shared.js, packages/vaadin-lumo-styles/style.js
Fixes #7957
Moved the font-weight custom CSS property to the correct file. Also changed it to `500` for backwards compatibility in order to not break screenshots (currently used `400` has never been working properly). 
Marked as a behavior altering fix, though I think we can still backport it at least to 24.5 to make the property work.
=> fix: set input value font weight property on input container

packages/component-base/src/define.js, packages/component-base/test/define.test.js
Added an option to mark the custom element as experimental with the following syntax:
```js
static get experimental() {
return true;
}
```
This is needed to enable using Vaadin feature flags in web components without separate `enable.js` file.
The reason behind this approach is that separate `enable.js` would still have to be added to dev bundle.
=> feat: add option to mark defined custom element as experimental

packages/grid-pro/src/vaadin-grid-pro-inline-editing-mixin.js, packages/grid-pro/test/keyboard-navigation.common.js, packages/grid-pro/theme/lumo/vaadin-grid-pro-styles.js
To resolve https://github.com/vaadin/web-components/issues/2550, add support to `vaadin-grid-pro` for `loading-editor` attribute, which disables keyboard interaction on the focused cell and styles it with a pulsating outline. Also, content of the cell is hidden (using opacity) and pointer events are prevented on it.
The following recording uses the Flow GridPro component with network throttling on.
https://github.com/user-attachments/assets/a1893997-3a31-4f82-9507-0a63cf294192
Related https://github.com/vaadin/flow-components/pull/6820
The feature is not intended for public use so it's not documented nor exposed as a property.
Part of https://github.com/vaadin/web-components/issues/2550
Feature
=> feat: grid-pro loading editor state

packages/grid-pro/src/vaadin-grid-pro-inline-editing-mixin.js, packages/grid-pro/test/keyboard-navigation.common.js, packages/grid-pro/theme/lumo/vaadin-grid-pro-styles.js
Manually cherry-pick #8156 to `24.4`
=> feat: grid-pro loading editor state (#8156) (CP: 24.4)

packages/component-base/src/define.js, packages/component-base/test/define.test.js
- Added option to specify feature flag using the `static get experimental()`
- Refactored to support defining multiple custom elements with single flag
=> feat: add option to return feature flag name from static getter

packages/dashboard/test/dashboard-layout.test.ts, packages/dashboard/theme/lumo/vaadin-dashboard-layout-styles.js
Update Dashboard default spacing to `--lumo-space-l`.
This will cause a temporary issue where the resize mode buttons may overlap other widgets, but it will get fixed by https://github.com/vaadin/web-components/issues/8153
Fixes https://github.com/vaadin/web-components/issues/8150
Refactor
=> refactor: update dashboard default spacing

packages/date-picker/src/vaadin-infinite-scroller.js, packages/date-picker/test/dom/__snapshots__/date-picker-year-scroller.test.snap.js, packages/date-picker/test/dom/date-picker-year-scroller.test.js
Since Chrome 130, scrollable elements have become keyboard focusable by default. The PR prevents the date-picker year scroller from getting unexpectedly focused when navigating inside the overlay in Chrome.
=> fix: prevent year scroller from getting focused in Chrome

packages/combo-box/src/vaadin-combo-box-item-mixin.js, packages/combo-box/test/item-renderer.common.js
Since adding the data provider controller to combo box in https://github.com/vaadin/web-components/pull/7044, the component now calls `ComboBoxMixin.requestContentUpdate` when filtering using a data provider. That method iterates over every item in the overlay, regardless whether visible or hidden, and runs its renderer function:
https://github.com/vaadin/web-components/blob/d8772844d1d469094ef26762db90f295ec510ea7/packages/combo-box/src/vaadin-combo-box-mixin.js#L412-L414
That can lead to an issue in the Flow component when using component renderers:
- Entering a filter can move an item's content element to a different item (for example the first one if there is only one match)
- The item that originally contained the content element is then hidden and not updated - it still references …
=> fix: do not render hidden combo box items

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-chip.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-styles.d.ts, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-styles.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js
Extracted multi-select-combo-box styles into CSS tagged literals for reusing by Lit based version.
- Refactor
=> refactor: extract multi-select-combo-box styles into CSS literals

packages/dashboard/src/vaadin-dashboard-helpers.js, packages/dashboard/src/vaadin-dashboard-item-mixin.js, packages/dashboard/src/vaadin-dashboard.js, packages/dashboard/test/dashboard-keyboard.test.ts
This change improves Dashboard UX by only showing a widget's resize-mode buttons that affect its column span/row span on click.
https://github.com/user-attachments/assets/8c66cfe0-ee22-4749-a445-17378472c41a
Fixes https://github.com/vaadin/web-components/issues/8152
Refactor / UX
=> refactor: hide dashboard resize buttons that have no effect

packages/dashboard/src/vaadin-dashboard-styles.js, packages/dashboard/test/dashboard-keyboard.test.ts, packages/dashboard/theme/lumo/vaadin-dashboard-widget-styles.js
Move resize mode buttons inside dashboard widget
https://github.com/user-attachments/assets/27919695-1b95-420d-b4dd-43f673aa0f95
Fixes https://github.com/vaadin/web-components/issues/8153
Refactor
=> refactor: move resize mode buttons inside dashboard widget

packages/dashboard/theme/lumo/vaadin-dashboard-widget-styles.js
Apply widget content blur on slotted content to avoid it bleeding outside the widget
Depends on https://github.com/vaadin/web-components/pull/8191
Fixes https://github.com/vaadin/web-components/issues/8137
Bugfix
=> fix: apply widget content blur on slotted content

packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/test/events.common.js, packages/field-base/src/input-mixin.js, packages/time-picker/src/vaadin-lit-time-picker-combo-box.js, packages/time-picker/src/vaadin-time-picker-combo-box.js
DatePicker and TimePicker counterparts [have been recently updated](https://github.com/vaadin/flow-components/pull/6846) to no longer rely on the `hasInputValue` property for detecting bad input. This removes the need for workarounds that caused the `hasInputValue` behavior to be inconsistent with other components
Fixes https://github.com/vaadin/web-components/issues/5639
=> refactor!: align hasInputValue behavior across components

packages/grid-pro/theme/lumo/vaadin-grid-pro-styles.js
Opacity animations can be done by the GPU compositor, and don't require a paint cycle by the browser as animating box-shadow does.
=> refactor: animate opacity instead of box-shadow

packages/popover/src/vaadin-popover.js, packages/popover/test/basic.test.js
Currently a popover is immediately closed when it is disconnected from the DOM. That can be an issue in a Flow dialog when the popover is opened right away after adding it to the dialog. Here the element is first added as a child of the dialog, then opened, and afterwards moved to the dialog overlay by the renderer function. The last step causes the popover to close again.
This fixes the issue by delaying closing and checking if the element has been added to the DOM again. This is similar to what we are doing in other components such as dialog or notification.
Fixes https://github.com/vaadin/flow-components/issues/6840
=> fix: do not close popover when it is just moved in DOM

packages/tooltip/src/vaadin-tooltip-overlay-styles.js
Follow-up to #8198
Now when notification container is included to the overlay stack, we no longer need this workaround added in #6074
- Refactor
=> refactor: remove z-index override from tooltip overlay

packages/dashboard/src/vaadin-dashboard-layout-mixin.js, packages/dashboard/src/vaadin-dashboard-layout.d.ts, packages/dashboard/src/vaadin-dashboard-layout.js, packages/dashboard/src/vaadin-dashboard-section.js, packages/dashboard/src/vaadin-dashboard.d.ts, packages/dashboard/src/vaadin-dashboard.js, packages/dashboard/test/dashboard-layout.test.ts, packages/dashboard/test/helpers.ts, packages/dashboard/theme/lumo/vaadin-dashboard-layout-styles.js, packages/dashboard/theme/lumo/vaadin-dashboard-section-styles.js, packages/dashboard/theme/lumo/vaadin-dashboard-widget-styles.js
This PR splits the current `--vaadin-dashboard-spacing` property into separate `--vaadin-dashboard-gap` and `--vaadin-dashboard-padding` properties
Refactor / feature
=> refactor: split dashboard spacing into gap and padding

packages/text-area/src/vaadin-text-area-mixin.js
The auto-sizing mechanism of `<vaadin-text-area>` is currently not stable when the component switches from three rows to two rows. In that case subsequent `_updateHeight` calls can determine alternating content heights for the same value. In combination with the resize observer that the component uses that can end in an infinite resize loop, but the issue is also noticable without the resize observer when removing characters one by one.
This change makes the mechanism stable so that multiple `_updateHeight` calls in succession will determine the same height.
Fixes https://github.com/vaadin/web-components/issues/7828
=> fix: make text area auto-sizing stable

packages/date-picker/src/vaadin-date-picker-overlay-content-mixin.js, packages/date-picker/src/vaadin-infinite-scroller.js, packages/date-picker/test/custom-input.test.js, packages/date-picker/test/dropdown.common.js, packages/date-picker/test/events.common.js, packages/date-picker/test/fullscreen.common.js, packages/date-picker/test/helpers.js, packages/date-picker/test/keyboard-input.common.js, packages/date-picker/test/keyboard-navigation.common.js, packages/date-picker/test/theme-propagation.common.js, packages/date-picker/test/value-commit.common.js, packages/grid/test/column-rendering.common.js, test/integration/context-menu-date-picker.test.js, test/integration/dialog-date-picker.test.js
It turns out essential to flush all scroller debouncers before trying to focus any date to ensure the DOM is updated and the date is truly focusable. Previously, `date.focus()` could be called before the scrolled applied `tabindex=0` to the date element, and this led to test failures because not all browsers allow focusing elements with `tabindex=-1`.
Part of #8187
=> fix: force scroller update after revealing a date

packages/date-picker/src/vaadin-date-picker-overlay-content-mixin.js, packages/date-picker/src/vaadin-infinite-scroller.js
The PR refactors `date-picker` to ensure that the initial rendering of Lit month calendars happens synchronously. This eliminates rendering differences between the Lit and Polymer versions, which were causing test failures in  https://github.com/vaadin/web-components/pull/8187.
=> refactor: ensure Lit month calendars are rendered synchronously

dev/date-picker.html, packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/src/vaadin-date-picker-overlay-content-mixin.js, packages/date-picker/src/vaadin-lit-month-calendar.js, packages/date-picker/src/vaadin-month-calendar-mixin.js, packages/date-picker/src/vaadin-month-calendar.js, packages/date-picker/test/keyboard-input.common.js, packages/date-picker/test/wai-aria.common.js
The PR hides the flashing calendar date outline when the user enters unparsable input to avoid misleading since pressing <kbd>Enter</kbd> doesn't apply the flashing date in such cases. The outline is hidden by removing the `focused` part, except when the date element directly receives browser focus. 
Depends on 
- https://github.com/vaadin/web-components/pull/8220
Related to
- https://github.com/vaadin/flow-components/pull/6743#discussion_r1839963822
- https://github.com/vaadin/flow-components/issues/2466
=> refactor!: remove date focused part when input is unparsable

packages/avatar-group/src/vaadin-lit-avatar-group-overlay.js, packages/combo-box/src/vaadin-lit-combo-box-overlay.js, packages/context-menu/src/vaadin-lit-context-menu-overlay.js, packages/date-picker/src/vaadin-lit-date-picker-overlay.js, packages/menu-bar/src/vaadin-lit-menu-bar-overlay.js, packages/overlay/src/vaadin-overlay-mixin.js, packages/overlay/test/animations.common.js, packages/overlay/test/basic.common.js, packages/overlay/test/focus-trap.common.js, packages/overlay/test/interactions.common.js, packages/overlay/test/multiple.common.js, packages/overlay/test/position-mixin.common.js, packages/overlay/test/renderer.common.js, packages/overlay/test/restore-focus.common.js, packages/time-picker/src/vaadin-lit-time-picker-overlay.js
Updated properties in `OverlayMixin` to use `sync: true` and removed corresponding overrides from Lit components.
Also removed a bunch of `await` statements added back in the day as part of the following PRs:
- https://github.com/vaadin/web-components/pull/6047
- https://github.com/vaadin/web-components/pull/6113
- https://github.com/vaadin/web-components/pull/6115
- Refactor
=> refactor: update OverlayMixin properties to use sync: true

packages/dashboard/src/widget-resize-controller.js, packages/dashboard/test/dashboard-widget-resizing.test.ts, packages/dashboard/test/helpers.ts
This PR fixes the flicker on drag resize by only allowing resize if the drag direction is the same with the resize direction.
Fixes #7950
=> fix: resize only on direction of drag move

packages/grid/src/vaadin-grid-selection-column-base-mixin.js, packages/grid/src/vaadin-grid-selection-column-mixin.js
The `autoSelect` property is defined in `SelectionColumnBaseMixin`, so it makes sense to have the autoSelect logic there as well.
Part of #8142
=> refactor: move autoSelect logic to SelectionColumnBaseMixin

packages/grid/src/vaadin-grid-selection-column-base-mixin.js, packages/grid/test/selection.common.js
Switching from `checked-changed` to the `change` event removes the need for the `__renderedChecked` workaround, which was needed to ignore checkbox changes not initiated by the user.
=> refactor: subscribe to change instead of checked-changed

packages/grid-pro/src/vaadin-grid-pro-inline-editing-mixin.js, packages/grid-pro/test/keyboard-navigation.common.js
When a slow custom editor is used, quickly tabbing through the cells can cause a false positive on cell value change since the editor value is not updated yet at that point. This leads to firing unnecessary `item-property-changed` events.
This PR adds an editor loading check in `_stopEdit` in order to avoid firing the events. This is effectively the same as canceling the edit.
Fixes [#6816](https://github.com/vaadin/flow-components/issues/6816)
=> fix: do not dispatch event on stopedit when editor loading

packages/message-list/test/message-list.test.js
Updated `vaadin-message-list` tests to use correct properties e.g. `userName`, `userImg` etc instead of the `user` object. The object was used in the initial version https://github.com/vaadin/vaadin-messages/pull/9, but we then changed to use individual properties in https://github.com/vaadin/vaadin-messages/pull/19 and tests were not updated accordingly.
Also changed the base64 image to the one that doesn't affect syntax highlighting in VSCode.
- Tests
=> test: update message list test to use correct items format

packages/checkbox/test/checkbox.common.js, packages/checkbox/test/validation.common.js, packages/field-base/src/checked-mixin.js, packages/field-base/test/checked-mixin.test.js, packages/radio-group/src/vaadin-lit-radio-button.js
Updated `checked` property declaration to use `sync: true` and removed override from `vaadin-radio-button`.
Also, added missing Lit tests for `CheckedMixin` and removed no longer needed `await` from checkbox tests.
- Refactor
=> refactor: update checked property to use sync: true in Lit

packages/crud/src/vaadin-crud-mixin.js
Remove use of sub-properties in CRUD observers
This is a preferred alternative to https://github.com/vaadin/web-components/pull/8248
Refactor
=> refactor: do not use sub-properties in crud observers

packages/component-base/src/polylit-mixin.js, packages/component-base/test/polylit-mixin.test.js, packages/date-picker/src/vaadin-lit-date-picker.js, packages/number-field/src/vaadin-lit-number-field.js, packages/number-field/src/vaadin-number-field-mixin.js, packages/number-field/src/vaadin-number-field.js, packages/time-picker/src/vaadin-lit-time-picker.js
Ensures that ready() is called only after all observers have been executed, including nested calls.
Extracted from #8223
=> fix: ensure ready() is called after observers

packages/date-picker/src/vaadin-lit-date-picker.js
Noticed this while reviewing #8254. The logic is apparently only covered by snapshot tests and they only run for Polymer.
- Bugfix for Lit version
=> fix: add missing uniqueIdPrefix to Lit date-picker version

packages/time-picker/src/vaadin-lit-time-picker.js, packages/time-picker/src/vaadin-time-picker-mixin.js, packages/time-picker/src/vaadin-time-picker.js
Follow-up to #8254
Now when the `firstUpdated()` was replaced with `ready()`, Polymer and Lit versions of time-picker are identical.
Moved this code to the mixin as we have no reason to keep two separate implementations anymore.
- Refactor
=> refactor: move time-picker ready block to the mixin

packages/list-box/src/vaadin-multi-select-list-mixin.js
Current logic covers the case with mutating `selectedValues` array property using Polymer splices API.
As we already updated most of components to not support this, let's update `vaadin-list-box` as well.
- Refactor
=> refactor: update list-box observer to not use Polymer syntax

packages/grid-pro/src/vaadin-grid-pro-inline-editing-mixin.js, packages/grid-pro/test/keyboard-navigation.common.js
Back-port of [8232](https://github.com/vaadin/web-components/pull/8232) for v24.4.
=> fix: do not dispatch event on stopedit when editor loading (#8232) (CP: 24.4)

packages/date-picker/src/vaadin-date-picker.js, packages/date-picker/src/vaadin-lit-date-picker.js, packages/date-picker/test/dropdown.common.js
Related to https://github.com/vaadin/web-components/issues/7812#issuecomment-2511720183
While we might want to reconsider the current behavior or align it across components, let's first add missing tests to ensure this listener is actually covered (as `preventDefault()` for `vaadin-overlay-close` keeps the date-picker open).
- Test
=> test: add missing test for date-picker label click

packages/message-input/package.json, packages/message-input/src/vaadin-lit-message-input.d.ts, packages/message-input/src/vaadin-lit-message-input.js, packages/message-input/src/vaadin-message-input-mixin.js, packages/message-input/test/message-input-lit.test.js, packages/message-input/test/message-input-polymer.test.js, packages/message-input/test/message-input.common.js, packages/message-input/theme/lumo/vaadin-lit-message-input.js, packages/message-input/theme/material/vaadin-lit-message-input.js, packages/message-input/vaadin-lit-message-input.d.ts, packages/message-input/vaadin-lit-message-input.js
Added Lit based version of `vaadin-message-input`. 
Also changed the i18n logic to use `accessibleName` internally instead of manipulating `aria-label` directly.
- Experiment
=> experiment: add LitElement based version of message-input

packages/charts/src/vaadin-chart.js, packages/charts/test/reattach.test.js
Fix an issue where a chart defined using the `updateConfiguration` method loses its configuration after detaching and re-attaching. This fix stores the `userOptions` object when the component is disconnected to use it again when the component is connected back later.
The `userOptions`, according to the [Highcharts documentation](https://api.highcharts.com/class-reference/Highcharts.Chart#userOptions) is:
>The original options given to the constructor or a chart factory like [Highcharts.chart](https://api.highcharts.com/class-reference/Highcharts.html#.chart) and [Highcharts.stockChart](https://api.highcharts.com/class-reference/Highcharts.html#.stockChart). The original options are shallow copied to avoid mutation. The copy, chart.userOptions, may later be mutated to reflect updated …
=> fix: save userOptions charts disconnect

packages/accordion/src/vaadin-accordion-heading.js, packages/accordion/src/vaadin-lit-accordion-heading.js, packages/accordion/test/dom/__snapshots__/accordion-heading.test.snap.js
This is a finding from snapshot test: Lit version sets `aria-expanded="false"` by default, but with Polymer it's not set until `opened` has a value (that's how computed property bindings generally work in Polymer). 
Updated the property to add default `false` value (also this make it aligned with `vaadin-accordion-panel`.
- Refactor
=> refactor: set opened to false by default on accordion heading

packages/accordion/src/vaadin-accordion-panel-mixin.js, packages/accordion/test/accordion-panel.common.js
Fixed the issue with `vaadin-accordion-panel` not delegating `theme` attribute to its heading in Lit version.
The reason is that `DelegateStateMixin` supposes that attribute should have matching property, which is not the case for `theme` and `_theme` - however, Polymer somehow still creates also `theme` property so there it works.
Updated to use the same workaround as implemented in #7945 for `vaadin-tabsheet`.
- Bugfix
=> fix: delegate accordion panel theme attribute in Lit version

packages/details/src/vaadin-details-base-mixin.js, packages/details/test/details.common.js
Same as #8265 but for `vaadin-details` which was also using `delegateAttrs()` for `theme`.
- Bugfix
=> fix: delegate details theme attribute in Lit version

packages/menu-bar/src/vaadin-lit-menu-bar-submenu.js, packages/menu-bar/src/vaadin-menu-bar-submenu-mixin.js, packages/menu-bar/src/vaadin-menu-bar-submenu.js
Created a mixin to avoid code duplication in #8272. Note, these elements are internal so no `.d.ts` files for now.
- Refactor
=> refactor: extract common sub-menu logic into reusable mixin

packages/number-field/src/vaadin-lit-number-field.js, packages/select/src/vaadin-lit-select.js, packages/text-area/src/vaadin-lit-text-area.js, packages/text-field/src/vaadin-lit-text-field.js
Aligned Lit versions of components to use `ifDefined()` directive for `theme` attribute propagation to sub-components, so that the `theme` is removed (instead of being set to empty string) when it's removed from the host element.
- Refactor
=> refactor: use ifDefined directive for theme attribute propagation

packages/custom-field/src/vaadin-custom-field-mixin.js, packages/custom-field/test/custom-field.common.js
When all the inputs are removed, the value modified via the inputs is incorrectly preserved. This PR fixes this by setting a flag on whether the value change was made on the input, and resetting the value also when all the inputs are removed. Because of the Polymer&Lit timing differences, both `input` and `value` properties are now marked as `sync`.
Fixes #8252
=> fix: clear value when removing the last input

packages/form-layout/src/vaadin-form-layout.js, packages/form-layout/test/form-layout.test.js
Fixes https://github.com/vaadin/flow/issues/20598 (which is a regression from https://github.com/vaadin/web-components/pull/7988)
This is a fix for the case when `vaadin-form-layout` height is inherited from a fixed-size parent element (which is what happens in Flow due to the fact that it sets `height: 100vh` on the `<body>` and outlet element).
Currently, when scrolling long enough, the layout is becoming "not intersecting" and `opacity` is wrongly set to 0. This change ensures that `IntersectionObserver` instead uses the internal element since its height is defined by content.
- Bugfix
=> fix: observe internal layout to avoid problems with fixed height

packages/context-menu/src/vaadin-contextmenu-items-mixin.js, packages/menu-bar/src/vaadin-menu-bar-mixin.js, packages/menu-bar/src/vaadin-menu-bar-submenu-mixin.js, packages/menu-bar/test/sub-menu.common.js
Fixes #8269
Updated menu-bar logic to not incorrectly call `close()` while opening sub-menu in case if the "outside" click is actually originating from the menu-bar button. This eliminates the need for calling `stopPropagation()` on the `click` event.
Also, added tests to check that `pointerEvents` are correctly set and removed (which was actually broken when removing `stopPropagation()` without the change to the listener) - previously these tests only covered "open on hover" mode.
- Bugfix
=> fix: do not stop click event propagation on menu-bar button

packages/item/src/vaadin-item-mixin.js, packages/select/src/vaadin-select-base-mixin.js, packages/select/test/keyboard.common.js, packages/select/test/select.common.js
- Updated `selected` property in `ItemMixin` to use `sync: true` so it triggers observer synchronously
- Added call to `performUpdate()` on the item clone in `vaadin-select` to remove `aria-selected`
- Added missing unit test to ensure `aria-selected` attribute is removed (in Lit version it was not)
Note: there was an error in the "keyboard selection" test apparently caused by the fact that  "append value item" was called too late. Added `await nextUpdate()` to this test helped to remove the error so I think it was a test issue.
```
at SelectItem.update (node_modules/lit-element/src/lit-element.ts:163:23)
at SelectItem.performUpdate (node_modules/@lit/reactive-element/src/reactive-element.ts:1440:13)
at Select.__appendValueItemElement …
```
=> fix: ensure aria-selected attribute is removed from the item clone

packages/date-picker/src/vaadin-infinite-scroller.js, packages/date-picker/test/scroller.test.js
Fixes #1665
See https://github.com/vaadin/web-components/issues/1665#issuecomment-2519771918 for clarification.
Added a test that sets item height to `30.0001px` - with the test setup, the first item should be `0` but with previous logic the item count is calculated incorrectly and the item text content becomes `1`. 
- Bugfix
=> fix: use Math.round to get correct scroller first index

packages/grid/src/vaadin-grid-tree-toggle-mixin.js
Renamed `---level` to `--_level` to align with our naming convention for private CSS variables.
=> refactor: use underscore to indicate CSS variable is private

.github/workflows/coverage.yml, .github/workflows/unit-tests.yml, .github/workflows/verify.yml, .github/workflows/visual-tests.yml
Updated to use same Node version in `23.5` as in other supported branches.
=> chore: update GitHub Actions to latest, use Node 20 (#7301) (CP: 23.5)

wtr-utils.js
Update the web-test-runner change detection script to use 24.6 as a base branch for Vaadin 24.6
=> chore: update change detection branch to 24.6

packages/overlay/src/vaadin-overlay-stack-mixin.js, test/integration/not-animated-styles.js, test/integration/notification-overlay.test.js
Fixes #8281
The change in #8198 introduced two regressions related to "notification" + "dialog" combination:
1. First, the `vaadin-notification-container` is now considered a "last" overlay so the keydown listener is not firing thus making it impossible to close `vaadin-dialog` on <kbd>Esc</kbd> if there is a notification on top of it,
2. Also, the `vaadin-notification-container` is treated as modal overlay (as it doesn't have `modeless`) - as a result, `pointer-events: none` is not removed from parent dialog if notification is open before closing nested dialog.
This PR changes the logic to only include notification container in the "visual" stack (z-index) and adds separate helper that filters it out from `getAttachedInstances()` so that overlay "modality" stack is not affected.
- Bugfix
=> fix: prevent notification from affecting overlay interactions

packages/dashboard/src/vaadin-dashboard.js, packages/dashboard/test/dashboard.test.ts
Fixes an issue where the dashboard widget focus gets lost on items change if the dashboard is inside a shadow root.
Bugfix
=> fix: do not lose dashboard widget focus in shadow root

packages/accordion/src/vaadin-accordion-heading-styles.js, packages/button/src/vaadin-button-base.js, packages/checkbox/theme/lumo/vaadin-checkbox-styles.js, packages/checkbox/theme/material/vaadin-checkbox-styles.js, packages/context-menu/theme/lumo/vaadin-context-menu-item-styles.js, packages/date-picker/src/vaadin-date-picker-year-scroller.js, packages/date-picker/theme/lumo/vaadin-month-calendar-styles.js, packages/details/src/vaadin-details-summary.js, packages/details/src/vaadin-lit-details-summary.js, packages/grid-pro/theme/lumo/vaadin-grid-pro-edit-select-styles.js, packages/grid-pro/theme/material/vaadin-grid-pro-edit-select-styles.js, packages/grid/src/vaadin-grid-styles.js, packages/grid/test/column-reordering.common.js, packages/grid/theme/lumo/vaadin-grid-sorter-styles.js, packages/grid/theme/material/vaadin-grid-sorter-styles.js, packages/map/src/vaadin-map.js, packages/number-field/src/vaadin-number-field-styles.js, packages/radio-group/theme/lumo/vaadin-radio-button-styles.js, packages/radio-group/theme/material/vaadin-radio-button-styles.js, packages/rich-text-editor/src/vaadin-rich-text-editor-styles.js, packages/select/src/vaadin-select-value-button-styles.js, packages/tabs/theme/lumo/vaadin-tab-styles.js
The PR removes `-ms-user-select` and `-moz-user-select`, as they are no longer necessary according to [caniuse](https://caniuse.com/mdn-css_properties_user-select):
=> refactor: remove obsolete vendor-prefixed CSS properties

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal-mixin.js, packages/multi-select-combo-box/test/selecting-items.common.js
Fixes #8300
Originally, unselecting was workarounded by #3807 which was setting a flag on `focusout` event.
However, since #7846 there is no more focusout when closing combo-box overlay on outside click.
Updated to also set this flag in `_onClosed()` method which triggers value commit in combo-box.
Also added a missing test using `sendMouse()` - note, `outsideClick()` helper isn't suitable here.
UPD: also fixed the problem with selected item text incorrectly applied to input field on blur.
- Bugfix
Will cherry-pick manually to `24.5` once this is merged since that branch doesn't have a mixin.
=> fix: prevent unselecting already committed value on outside click

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal-mixin.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-mixin.js, packages/multi-select-combo-box/test/basic.common.js, packages/multi-select-combo-box/test/selecting-items.common.js
Depends on #8301
Fixes #8067 
Fixes #3645
Changed the MSCB logic to discard custom value from the internal combo-box on input blur with <kbd>Tab</kbd> or outside click. 
This would require user to explicitly commit custom value by pressing <kbd>Enter</kbd> after typing the filter in the input.
- Bugfix
=> fix: do not fire custom-value-set on input blur or outside click

packages/grid/src/vaadin-grid-selection-column-base-mixin.js, packages/grid/test/selection.common.js
The PR fixes a dragSelect issue that caused recurring attempts to select or deselect items after they were already in the desired state.
Fixes https://github.com/vaadin/flow-components/issues/6909
=> fix: prevent repeated selection attempts during drag selection

packages/component-base/src/polylit-mixin.js, packages/component-base/test/polylit-mixin.test.js, packages/select/src/vaadin-lit-select-overlay.js, packages/select/src/vaadin-lit-select.js, packages/select/src/vaadin-select-base-mixin.js, packages/select/src/vaadin-select-overlay-mixin.js, packages/select/src/vaadin-select-overlay.js, packages/select/src/vaadin-select.js, packages/select/test/dom/__snapshots__/select.test.snap.js, packages/tooltip/src/vaadin-lit-tooltip.js, packages/tooltip/src/vaadin-tooltip-mixin.js, packages/tooltip/src/vaadin-tooltip-overlay.js, packages/tooltip/src/vaadin-tooltip.js, packages/tooltip/test/dom/__snapshots__/tooltip.test.snap.js
The PR improves PolylitMixin to make it add custom elements with id to the `$` map immediately after they are connected to the DOM. This guarantees that the reference will be saved even if the element, such as an overlay, is teleported elsewhere during the first render.
=> refactor: add elements to $ map immediately after their connection to DOM

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js, packages/multi-select-combo-box/test/basic.test.js, packages/multi-select-combo-box/test/selecting-items.test.js
Manual cherry-pick of #8308 to `24.5` branch.
- Cherry-pick
=> fix: do not fire custom-value-set on input blur or outside click (#8308) (CP: 24.5)

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js, packages/multi-select-combo-box/test/basic.test.js, packages/multi-select-combo-box/test/selecting-items.test.js
Manual cherry-pick of #8308 to `24.4` branch.
- Cherry-pick
=> fix: do not fire custom-value-set on input blur or outside click (#8308) (CP: 24.4)

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-internal.js, packages/multi-select-combo-box/test/basic.test.js, packages/multi-select-combo-box/test/selecting-items.test.js
Manual cherry-pick of #8308 to `23.5` branch.
- Cherry-pick
=> fix: do not fire custom-value-set on input blur or outside click (#8308) (CP: 23.5)

packages/component-base/src/polylit-mixin.js, packages/component-base/test/polylit-mixin.test.js
The PR ensures that children with id whose parent was teleported are still added to the id map of the host component.
Required for https://github.com/vaadin/web-components/pull/8290
=> fix: add children with id to id map even if their parent was teleported

packages/side-nav/src/vaadin-side-nav-item.js, packages/side-nav/test/dom/__snapshots__/side-nav-item.test.snap.js
For side nav items, the text "Toggle child items" is currently only visually hidden but is still reachable using ATs when cycling elements, for example with <kbd>Ctrl+Option+ArrowRight</kbd> when using Voiceover. This results in an unnecessary announcement when selecting the element, and is confusing because the element can not be toggled. Also the element is always there, even if the item does not have children / group semantics.
Since the element's only purpose is to provide additional text for the toggle button, it can be fully hidden. This prevents it from being accessed, but it will still be used by `aria-labelledby` when announcing the toggle button.
=> fix: hide toggle items text

packages/virtual-list/src/vaadin-virtual-list-mixin.d.ts, packages/virtual-list/src/vaadin-virtual-list-mixin.js, packages/virtual-list/test/typings/virtual-list.types.ts, packages/virtual-list/test/virtual-list.common.js
Extracted from https://github.com/vaadin/web-components/pull/8318
Part of https://github.com/vaadin/platform/issues/6838
Address the following a11y-related topics from the AC:
- When selection is disabled, VirtualList has ARIA role="list" and item wrappers have role="listitem"
- VirtualList needs an aria-label(ledby) API in order to provide an accessible name
- Added as `itemAccessibleNameGenerator`
This PR also adds `aria-setsize` and `aria-posinset` attributes to the elements.
Feature
=> feat: improve virtual-list a11y

packages/avatar/src/vaadin-lit-avatar.js
Currently, in Lit version the empty `src` attribute is set by default (can be checked by snapshot test). This PR fixes that:
```
❌ vaadin-avatar > default
AssertionError: Snapshot vaadin-avatar default does not match the saved snapshot on disk
<img
aria-hidden="true"
draggable="false"
hidden=""
-  src=""
>
<slot name="tooltip">
</slot>
```
- Bugfix
=> fix: only set avtar img src attribute if property is defined

packages/confirm-dialog/src/vaadin-lit-confirm-dialog-overlay.js
The Lit version is lacking `aria-label` attribute propagation (can be checked by snapshot test). This PR fixes that.
- Bugfix
=> fix: add missing aria-label attribute to Lit confirm-dialog

packages/custom-field/src/vaadin-lit-custom-field.js
The part name was added in #6703 but the Lit version was not updated accordingly. This PR fixes that.
- Bugfix
=> fix: add missing inputs-wrapper part to Lit based custom-field

packages/custom-field/src/vaadin-custom-field-mixin.js, packages/field-base/src/validate-mixin.js, packages/field-base/test/validate-mixin.test.js
Updated `required` and `invalid` properties to use `sync: true` and modified the mixin test accordingly.
- Refactor
=> refactor: make required and invalid properties use sync update

packages/grid/src/vaadin-lit-grid.js
There's a problem in Lit grid which can be checked by snapshot tests with e.g. `safari="false"`. This PR fixes that.
```
❌ vaadin-grid > shadow > default
AssertionError: Snapshot vaadin-grid shadow default does not match the saved snapshot on disk
<div
-  column-reordering-allowed="false"
id="scroller"
-  ios="false"
-  safari="false"
style="touch-action: none;"
>
```
- Bugfix
=> fix: use correct binding for boolean attributes in Lit grid

packages/login/src/vaadin-lit-login-form.js
Updated to bind `label` using property and use `ifDefined()` directive to set `action` on the `<form>` element.
- Refactor
=> refactor: use correct property bindings in Lit based login form

packages/notification/src/vaadin-lit-notification.js
Follow-up to #8276
Aligned `vaadin-notification` with other Lit based components to not set empty `theme` attribute.
- Refactor
=> refactor: use ifDefined directive for notification theme attribute

packages/crud/src/vaadin-crud-grid-mixin.d.ts, packages/crud/src/vaadin-crud-grid-mixin.js, packages/crud/src/vaadin-crud-mixin.js
The (internal) crud grid component currently [declares](https://github.com/vaadin/web-components/blob/849dc36562b677ca7faad7e0845eacc87bbe841d/packages/crud/src/vaadin-crud-grid-mixin.js#L43) a private `__hideEditColumn` property, which isn't used. An undeclared `hideEditColumn` is used instead by the `__onHideEditColumnChange` observer.
Update the component to declare the `hideEditColumn` property
Refactor
=> refactor: fix crud grid hide edit column usage

packages/form-layout/src/vaadin-form-item.js, packages/form-layout/src/vaadin-form-layout-styles.d.ts, packages/form-layout/src/vaadin-form-layout-styles.js, packages/form-layout/src/vaadin-form-layout.js
Extracted `vaadin-form-layout` styles into `css` tagged literal for reusing by Lit version.
- Refactor
=> refactor: extract form-layout styles into reusable CSS literal

packages/app-layout/src/vaadin-app-layout-styles.d.ts, packages/app-layout/src/vaadin-app-layout-styles.js, packages/app-layout/src/vaadin-app-layout.js
Extracted `vaadin-app-layout` styles into `css` tagged literal for reusing by Lit version.
- Refactor
=> refactor: extract app-layout styles into reusable CSS literal

packages/form-layout/src/vaadin-form-item-mixin.js, packages/form-layout/src/vaadin-form-layout-mixin.js, packages/form-layout/src/vaadin-lit-form-item.d.ts, packages/form-layout/src/vaadin-lit-form-item.js, packages/form-layout/src/vaadin-lit-form-layout.d.ts, packages/form-layout/src/vaadin-lit-form-layout.js, packages/form-layout/test/form-item-lit.test.js, packages/form-layout/test/form-item-polymer.test.js, packages/form-layout/test/form-item.common.js, packages/form-layout/test/form-layout-lit.test.js, packages/form-layout/test/form-layout-polymer.test.js, packages/form-layout/test/form-layout.common.js, packages/form-layout/theme/lumo/vaadin-lit-form-item.js, packages/form-layout/theme/lumo/vaadin-lit-form-layout.js, packages/form-layout/theme/material/vaadin-lit-form-item.js, packages/form-layout/theme/material/vaadin-lit-form-layout.js, packages/form-layout/vaadin-lit-form-item.d.ts, packages/form-layout/vaadin-lit-form-item.js, packages/form-layout/vaadin-lit-form-layout.d.ts, packages/form-layout/vaadin-lit-form-layout.js
Added an experimental version of `vaadin-form-layout` based on LitElement.
- Experiment
=> experiment: add LitElement based version of vaadin-form-layout

packages/app-layout/src/vaadin-app-layout-mixin.js, packages/app-layout/src/vaadin-lit-app-layout.d.ts, packages/app-layout/src/vaadin-lit-app-layout.js, packages/app-layout/src/vaadin-lit-drawer-toggle.d.ts, packages/app-layout/src/vaadin-lit-drawer-toggle.js, packages/app-layout/test/app-layout-lit.test.js, packages/app-layout/test/app-layout-polymer.test.js, packages/app-layout/test/app-layout.common.js, packages/app-layout/test/drawer-toggle-lit.test.js, packages/app-layout/test/drawer-toggle-polymer.test.js, packages/app-layout/test/drawer-toggle.common.js, packages/app-layout/test/keyboard-desktop-lit.test.js, packages/app-layout/test/keyboard-desktop-polymer.test.js, packages/app-layout/test/keyboard-desktop.common.js, packages/app-layout/test/keyboard-mobile-lit.test.js, packages/app-layout/test/keyboard-mobile-polymer.test.js, packages/app-layout/test/keyboard-mobile.common.js, packages/app-layout/theme/lumo/vaadin-lit-app-layout.js, packages/app-layout/theme/lumo/vaadin-lit-drawer-toggle.js, packages/app-layout/theme/material/vaadin-lit-app-layout.js, packages/app-layout/theme/material/vaadin-lit-drawer-toggle.js, packages/app-layout/vaadin-lit-app-layout.d.ts, packages/app-layout/vaadin-lit-app-layout.js, packages/app-layout/vaadin-lit-drawer-toggle.d.ts, packages/app-layout/vaadin-lit-drawer-toggle.js
Added Lit based versions of `vaadin-app-layout` and `vaadin-drawer-toggle`.
- Experiment
=> experiment: add LitElement based version of app-layout

packages/popover/src/vaadin-popover-target-mixin.js, packages/popover/test/basic.test.js
Fixes https://github.com/vaadin/flow-components/issues/6953
Currently, target listeners are removed when popover is detached. However, we don't handle case when `target` property is set while detached - in this case, the target listeners will be still added. This PR fixes that by changing the observer logic to use `_isConnected` property and take it into account when checking whether listeners should be added.
- Bugfix
=> fix: ignore target set while popover is detached until re-attached

packages/dashboard/test/dashboard.test.ts, packages/dashboard/test/helpers.ts
Try to stabilize flaky Dashboard tests by using a helper with `nextUpdate`
Tests
=> test: use nextUpdate to stabilize dashboard tests on Webkit

packages/dashboard/src/vaadin-dashboard-section.js, packages/dashboard/src/vaadin-dashboard.js, packages/dashboard/test/dashboard-keyboard.test.ts, packages/dashboard/test/dashboard-widget-reordering.test.ts, packages/dashboard/test/dashboard.test.ts
Refactor `<vaadin-dashboard>` to reorder the widgets by assigning them updated `slot` names instead of reordering the elements in the DOM. This will fix issues such as a `<vaadin-grid>` losing its scroll position on reorder when used as a widget child element.
NOTE: This change will require picking up [this commit](https://github.com/vaadin/flow-components/commit/d6409f0ee6f19b79c24bddc3b42d13e475b05651) to the web component version bump PR in `flow-components`
Bugfix/refactor
=> fix: slot dashboard widgets instead of dom reordering

packages/crud/src/vaadin-crud-mixin.js, packages/crud/test/crud-buttons.test.js
Fixes https://github.com/vaadin/flow-components/issues/6965
Updated the check before moving child nodes to allow teleporting header and form if some of buttons is not set.
This covers the case with `_noDefaultButtons` (used by Flow counterpart) when using `setVisible(false)` which not only sets `hidden` attribute on the corresponding button, but also disallows setting proper `slot` attribute on it.
- Bugfix
=> fix: teleport CRUD form to overlay if some buttons are not set

.github/workflows/coverage.yml, .github/workflows/unit-tests.yml, .github/workflows/verify.yml, .github/workflows/visual-tests.yml
`ubuntu-latest` now refers to `ubuntu-24.04`, which results in the following issues:
- Ubuntu now includes an App Armor profile for Chrome that prevents running builds downloaded from the internet, such as the ones downloaded by Puppeteer and Playwright
- Playwright browser install fails with `Package libicu70 is not available, but is referred to by another package`
For the App Armor issue we could do what the Puppeteer team did, and disable App Armor for CI runs (https://github.com/puppeteer/puppeteer/pull/13196). However that doesn't solve the Playwright installation issue. For now it seems easiest to pin the Ubuntu version to the one we used before and wait for things to settle.
=> chore: pin ubuntu version in GitHub Actions

packages/crud/src/vaadin-crud.js, packages/crud/test/crud-buttons.test.js
Manual cherry-pick of #8372 to `24.5` branch.
- Cherry-pick
=> fix: teleport CRUD form to overlay if some buttons are not set (#8372) (CP: 24.5)

packages/cookie-consent/package.json, packages/dashboard/package.json, packages/horizontal-layout/package.json, packages/progress-bar/package.json, packages/scroller/package.json, packages/vertical-layout/package.json, yarn.lock
I used an incorrect search pattern, which caused some files to be missed in #8388
=> chore: upgrade @vaadin/testing-helpers to 1.1.0

packages/app-layout/test/app-layout.common.js, packages/app-layout/test/not-animated-styles.js, packages/avatar-group/test/avatar-group.common.js, packages/board/test/helpers.js, packages/board/test/redraw.test.js, packages/charts/test/chart-element.test.js, packages/component-base/test/overflow-controller.test.js, packages/component-base/test/resize-mixin.test.js, packages/dashboard/test/dashboard-keyboard.test.ts, packages/dashboard/test/dashboard-layout.test.ts, packages/dashboard/test/dashboard-widget-reordering.test.ts, packages/dashboard/test/dashboard-widget-resizing.test.ts, packages/dashboard/test/dashboard.test.ts, packages/dashboard/test/helpers.ts, packages/dialog/test/header-footer.common.js, packages/form-layout/test/form-layout.common.js, packages/grid/test/column-groups.common.js, packages/grid/test/column-rendering.common.js, packages/grid/test/frozen-columns.common.js, packages/grid/test/helpers.js, packages/grid/test/min-height.common.js, packages/grid/test/resizing.common.js, packages/grid/test/scrolling-mode.common.js, packages/icon/test/icon-font.common.js, packages/menu-bar/test/overflow.common.js, packages/multi-select-combo-box/test/chips.common.js, packages/tabs/test/tabs.common.js, packages/text-area/test/text-area.common.js
Replaces `onceResized` test helpers with `nextResize`, which subscribes to a real ResizeObserver instead of spying for internal component methods. Apart from cleaning up tests, this change also fixes Webkit failures in #8355.
Depends on 
- https://github.com/vaadin/testing-helpers/pull/13
- https://github.com/vaadin/web-components/pull/8388
=> test: replace onceResized with nextResize

packages/app-layout/test/app-layout.test.js, packages/app-layout/test/not-animated-styles.js, packages/avatar-group/test/avatar-group.common.js, packages/board/test/helpers.js, packages/board/test/redraw.test.js, packages/charts/test/chart-element.test.js, packages/component-base/test/overflow-controller.test.js, packages/component-base/test/resize-mixin.test.js, packages/dashboard/test/dashboard-keyboard.test.ts, packages/dashboard/test/dashboard-layout.test.ts, packages/dashboard/test/dashboard-widget-reordering.test.ts, packages/dashboard/test/dashboard-widget-resizing.test.ts, packages/dashboard/test/dashboard.test.ts, packages/dashboard/test/helpers.ts, packages/dialog/test/header-footer.common.js, packages/form-layout/test/form-layout.test.js, packages/grid/test/column-groups.common.js, packages/grid/test/column-rendering.common.js, packages/grid/test/frozen-columns.common.js, packages/grid/test/helpers.js, packages/grid/test/min-height.common.js, packages/grid/test/resizing.common.js, packages/grid/test/scrolling-mode.common.js, packages/icon/test/icon-font.common.js, packages/menu-bar/test/overflow.common.js, packages/multi-select-combo-box/test/chips.common.js, packages/tabs/test/tabs.common.js, packages/text-area/test/text-area.common.js
Cherry-picks #8387 to branch 24.6
Conflicts:
- `packages/app-layout/test/app-layout.test.js` (import declarations difference)
=> test: replace onceResized with nextResize (#8387) (CP: 24.6)

packages/checkbox-group/test/dom/__snapshots__/checkbox-group.test.snap.js, packages/checkbox/test/dom/__snapshots__/checkbox.test.snap.js, packages/combo-box/test/dom/__snapshots__/combo-box.test.snap.js, packages/custom-field/test/dom/__snapshots__/custom-field.test.snap.js, packages/date-picker/test/dom/__snapshots__/date-picker.test.snap.js, packages/date-time-picker/test/dom/__snapshots__/date-time-picker.test.snap.js, packages/email-field/test/dom/__snapshots__/email-field.test.snap.js, packages/field-base/src/error-controller.js, packages/field-base/test/field-mixin.test.js, packages/integer-field/test/dom/__snapshots__/integer-field.test.snap.js, packages/login/test/dom/__snapshots__/login-form.test.snap.js, packages/multi-select-combo-box/test/dom/__snapshots__/multi-select-combo-box.test.snap.js, packages/number-field/test/dom/__snapshots__/number-field.test.snap.js, packages/password-field/test/dom/__snapshots__/password-field.test.snap.js, packages/radio-group/test/dom/__snapshots__/radio-group.test.snap.js, packages/select/test/dom/__snapshots__/select.test.snap.js, packages/text-area/test/dom/__snapshots__/text-area.test.snap.js, packages/text-field/test/dom/__snapshots__/text-field.test.snap.js, packages/time-picker/test/dom/__snapshots__/time-picker.test.snap.js
The PR fixes the issue where VoiceOver didn't announce the error message when returning focus to the field from another element in Safari. The issue is fixed by removing the `alert` role from the error message element and instead using a separate element with `aria-live="assertive"` for the announcement. The assertive mode ensures the error message is correctly announced on value commit with <kbd>Enter</kbd> to match the previous behavior.
| Screen reader | Tested |
|:--------------|:-------|
| VoiceOver | ✅  |
| NVDA         | ✅ |
| JAWS         | ✅ |
Fixes #8349
=> fix: ensure error message is announced by VoiceOver

packages/checkbox-group/test/visual/common.js, packages/combo-box/test/visual/common.js, packages/custom-field/test/visual/common.js, packages/date-picker/test/visual/common.js, packages/date-time-picker/test/visual/common.js, packages/multi-select-combo-box/test/visual/common.js, packages/number-field/test/visual/common.js, packages/radio-group/test/visual/common.js, packages/select/test/visual/common.js, packages/text-area/test/visual/common.js, packages/text-field/test/visual/common.js, packages/time-picker/test/visual/common.js
Current styles for disabling error message transition only work for Lumo since Material theme uses `animation`:
https://github.com/vaadin/web-components/blob/0a54c0e87ec312c9dc60a308ba2181d3150aca9a/packages/vaadin-material-styles/mixins/required-field.js#L53-L61
Updated "common" styles for all field components to also cover Material. This should help to fix errors in #8383
```
- Test
=> test: disable error-message animation in Material visual tests

packages/notification/src/vaadin-notification-mixin.js
This fixes a  problem reported at [forum](https://vaadin.com/forum/t/notification-component-not-working-in-ff/168004) with `Notification is not defined` - the regression is introduced in #8083.
The component just happens to work since there's a global `Notification` object, but it's not 100% available. 
- Bugfix
=> fix: get the correct reference to the Notification class

packages/select/src/vaadin-select-base-mixin.js, packages/select/test/lit-renderer-directives.common.js, packages/select/test/select.common.js
Fixes #8398
Changed the observer to depend on `_overlayElement` (also, updated the order of setting references in `ready()` as the observer also uses `_inputContainer` internally - didn't include both to avoid triggering it multiple times unnecessarily).
- Bugfix
I didn't remove resetting `opened` to `false` as that could be considered a behavior altering change, and I added some missing tests that cover the relevant part of the observer for `readonly` and `disabled` test suites.
=> fix: do not close select overlay when opened before attached

wtr-utils.js
This is needed to make it possible to use package name for running visual tests, as with other packages:
```
yarn test:lumo --group icons
```
Currently used `vaadin-icons` group is a leftover from pre-V22 era when we had `@vaadin/vaadin-icons`.
=> chore: do not use vaadin prefix for icons visual test

.gitignore
In Lumo and Material themes, the path to visual test screenshots folder is different from other packages, so failed screenshots aren't currently ignored as expected. This PR fixes that.
=> chore: add failed screenshots for themes to .gitignore

packages/popover/src/vaadin-popover.d.ts, packages/popover/src/vaadin-popover.js, packages/popover/test/trigger.test.js
Fixes https://github.com/vaadin/web-components/issues/8306
Changed the behavior to allow closing on outside click or <kbd>Esc</kbd> unless explicitly disabled.
=> refactor!: close popover without trigger on Esc and outside click

packages/field-base/src/input-mixin.d.ts, packages/field-base/src/input-mixin.js, packages/number-field/src/vaadin-number-field-mixin.js
This PR changes number fields to make the `_inputElementValue` getter return a `NaN` marker string when input can't be parsed. This change will allow us to [replace](https://github.com/vaadin/flow-components/pull/6991) `_hasInputValue` with `_inputElementValue` in Flow NumberField and then deprecate it in the web components. Previously, detecting bad input via `_inputElementValue` wasn't possible since `input[type=number]` elements give an empty string for unparsable values.
Since `_inputElementValue` is a protected method, I marked this as a possible breaking change
=> refactor!: return a marker string to help Flow detect bad input

packages/dialog/src/vaadin-dialog-draggable-mixin.js, packages/dialog/src/vaadin-dialog-resizable-mixin.js
Reverted changes added in #6187 since the initial render in Lit is now synchronous and `await` is no longer needed.
- Refactor
=> refactor: remove no longer needed await from dialog ready

packages/button/src/vaadin-button-mixin.js, packages/checkbox/src/vaadin-checkbox-mixin.js, packages/radio-group/src/vaadin-radio-button-mixin.js
Replaced property override with setting `tabindex` manually in the constructor (which is how Lit recommends to set default property values). This would allow to e.g. change the property to use `sync: true` by only updating it once.
Related PRs where the override was added:
- https://github.com/vaadin/web-components/pull/6780
- https://github.com/vaadin/web-components/pull/3627
- Refactor
=> refactor: do not override tabindex property to set default value

packages/time-picker/src/vaadin-time-picker-mixin.js, packages/time-picker/test/value-commit.common.js
Fixes the issue where time-picker would not strip milliseconds on commit attempt when the value remained unchanged.
Fixes https://github.com/vaadin/web-components/issues/711
=> fix: always strip input value to match step interval

packages/time-picker/src/vaadin-time-picker.js, packages/time-picker/test/value-commit.test.js
Cherry-picks #8421 to branch 24.5
=> fix: always strip input value to match step interval (#8421) (CP: 24.5)

packages/avatar-group/src/vaadin-avatar-group-mixin.js, packages/component-base/src/polylit-mixin.js, packages/component-base/test/polylit-mixin.test.js, packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/src/vaadin-lit-month-calendar.js, packages/date-picker/src/vaadin-month-calendar-mixin.js, packages/date-picker/src/vaadin-month-calendar.js, packages/field-base/test/field-mixin.test.js, packages/grid/src/vaadin-grid-column-mixin.js
The PR moves the property value computation from `updated(props)` to `willChange(props)` so that the values are computed before `render()` where they might be already needed.
=> fix: compute property values in willUpdate

packages/date-picker/src/vaadin-lit-month-calendar.js, packages/date-picker/src/vaadin-month-calendar-mixin.js, packages/date-picker/src/vaadin-month-calendar.js, packages/date-picker/test/dom/__snapshots__/month-calendar.test.snap.js, packages/date-picker/test/dom/month-calendar.test.js
- Moved common template logic from component class to MonthCalendarMixin
- Renamed methods that compute values for templates
- Aligned `aria-selected` and `aria-disabled` attributes to be consistently set in both Lit and Polymer (previously inconsistent)
Part of https://github.com/vaadin/web-components/issues/3385
=> refactor: move common template logic to MonthCalendarMixin

packages/component-base/src/polylit-mixin.js, packages/component-base/test/polylit-mixin.test.js
Fixes #8419
This should fix the problem with `@property()` decorator where the `options` object can be undefined.
- Bugfix
=> fix: check if options object is defined when creating property

packages/date-picker/src/vaadin-date-picker-mixin.d.ts, packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/src/vaadin-lit-month-calendar.js, packages/date-picker/src/vaadin-month-calendar-mixin.js, packages/date-picker/src/vaadin-month-calendar.js, packages/date-picker/test/dom/__snapshots__/month-calendar.test.snap.js, packages/date-picker/test/dom/month-calendar.test.js, packages/date-picker/test/month-calendar.common.js, packages/date-picker/test/wai-aria.common.js
This PR updates the date-picker to use `Intl.DateTimeFormat` for generating calendar day aria-labels, replacing its custom formatting logic. Additionally, it adds a new i18n property, `locale`, to allow developers to specify the locale for `Intl.DateTimeFormat`. By default, the browser's locale is used.
Fixes https://github.com/vaadin/web-components/issues/3385
=> feat: add locale i18n property, use Intl.DateTimeFormat for aria-labels

packages/date-picker/src/vaadin-date-picker-mixin.d.ts, packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/src/vaadin-lit-month-calendar.js, packages/date-picker/src/vaadin-month-calendar-mixin.js, packages/date-picker/src/vaadin-month-calendar.js, packages/date-picker/test/dom/__snapshots__/month-calendar.test.snap.js, packages/date-picker/test/dom/month-calendar.test.js, packages/date-picker/test/month-calendar.common.js, packages/date-picker/test/wai-aria.common.js
We decided to revert #8433 because using `Intl.DateTimeFormat` with the `locale` i18n property requires more thorough consideration. For example, it's unclear whether the `locale` property should be optional or mandatory, and if it's optional, what the default value should be (browser's locale? html tag lang?).
Ticket https://github.com/vaadin/web-components/issues/3385
=> Revert "feat: add locale i18n property, use Intl.DateTimeFormat for aria-labels"

packages/login/src/vaadin-lit-login-form-wrapper.js, packages/login/src/vaadin-login-form-wrapper.js, packages/login/test/dom/__snapshots__/login-form.test.snap.js, packages/login/theme/lumo/vaadin-login-form-wrapper-styles.js, packages/login/theme/material/vaadin-login-form-wrapper-styles.js
Part of #98
See https://github.com/vaadin/web-components/issues/98#issuecomment-1002991495
- Refactor / a11y fix
Internal HTML tag names are not considered public API and can be changed as long as part names remain intact.
So IMO we can consider this a non-breaking change and backport it to previous versions.
=> refactor: replace h5 in login error message with strong

packages/login/src/vaadin-lit-login-form-wrapper.js, packages/login/src/vaadin-login-form-wrapper.js, packages/login/test/dom/__snapshots__/login-form.test.snap.js, packages/login/theme/lumo/vaadin-login-form-wrapper-styles.js, packages/login/theme/material/vaadin-login-form-wrapper-styles.js, packages/login/theme/material/vaadin-login-overlay-styles.js
Part of #98
See https://github.com/vaadin/web-components/issues/98#issuecomment-1002991495
- Refactor / a11y fix
Internal HTML tag names are not considered public API and can be changed as long as part names remain intact.
So IMO we can consider this a non-breaking change and backport it to previous versions same as #8438.
I'll create a separate PR with a new property in order to customize the heading level, that will only target 24.7
=> refactor: use div with heading role instead of h2 in form title

packages/grid-pro/src/vaadin-grid-pro-inline-editing-mixin.js, packages/grid-pro/test/keyboard-navigation.common.js, packages/grid-pro/theme/lumo/vaadin-grid-pro-styles.js
Adds cell styles for hiding cell content and showing a loading animation while a cell is being updated. Intended to be used by the Flow component to hide cell content while updating cell values, which requires a server roundtrip for custom editors.
Part of https://github.com/vaadin/web-components/issues/8234
Corresponding Flow PR: https://github.com/vaadin/flow-components/pull/6973
=> refactor: add updating-cell part styles

packages/message-input/src/vaadin-message-input-mixin.js, packages/message-input/test/dom/__snapshots__/message-input.test.snap.js
Based on https://github.com/vaadin/web-components/pull/8168
Now when we can set `minRows` to `1`, let's use this API instead of modifying native `<textarea>`.
- Refactor
=> refactor: use minRows property for message input textarea

packages/login/src/vaadin-lit-login-form-wrapper.js, packages/login/src/vaadin-lit-login-form.js, packages/login/src/vaadin-lit-login-overlay-wrapper.js, packages/login/src/vaadin-lit-login-overlay.js, packages/login/src/vaadin-login-form-wrapper.js, packages/login/src/vaadin-login-form.js, packages/login/src/vaadin-login-mixin.d.ts, packages/login/src/vaadin-login-mixin.js, packages/login/src/vaadin-login-overlay-mixin.js, packages/login/src/vaadin-login-overlay-wrapper-mixin.js, packages/login/src/vaadin-login-overlay-wrapper-styles.js, packages/login/src/vaadin-login-overlay-wrapper.js, packages/login/src/vaadin-login-overlay.js, packages/login/test/dom/__snapshots__/login-form.test.snap.js, packages/login/test/dom/__snapshots__/login-overlay.test.snap.js, packages/login/test/login-overlay.common.js, packages/login/test/typings/login.types.ts, packages/login/theme/lumo/vaadin-login-overlay-styles.js, packages/login/theme/material/vaadin-login-overlay-styles.js
Fixes #98
Implemented the new API based on the suggestion from https://github.com/vaadin/web-components/issues/98#issuecomment-2567460241:
> - Make the "Log in" `<h2>` level dynamic based on whether the title is displayed (so that it's rendered as `<h1>` if no title is provided)
> - Introduce an API for setting the root heading level, which then affects both the Title (if provided) and the "Log in" heading.
- Feature
=> feat: add headingLevel property to customize login heading level

packages/app-layout/test/app-layout-lit.test.js, packages/app-layout/test/app-layout-polymer.test.js, packages/app-layout/test/app-layout.common.js
This fixes the following warning introduced in #8387:
```
packages/app-layout/test/app-layout-lit.test.js:
The custom element definition for "vaadin-app-layout" was finalized before a style module was registered. Ideally, import component specific style modules before importing the corresponding custom element. This warning can be suppressed by setting "window.Vaadin.suppressPostFinalizeStylesWarning = true".
```
- Test
=> test: move app-layout styles import to avoid warning with Lit

.github/workflows/unit-tests.yml, package.json, packages/checkbox-group/test/checkbox-group.common.js, packages/checkbox-group/test/validation.common.js, packages/checkbox/test/validation.common.js, packages/combo-box/test/interactions.common.js, packages/combo-box/test/keyboard.common.js, packages/component-base/test/virtualizer-reorder-elements.test.js, packages/context-menu/test/a11y.common.js, packages/dashboard/test/dashboard-keyboard.test.ts, packages/date-picker/test/dropdown.common.js, packages/field-base/test/virtual-keyboard-controller.test.js, packages/field-highlighter/test/user-tags.test.js, packages/grid/test/drag-and-drop.common.js, packages/grid/test/keyboard-interaction-mode.common.js, packages/grid/test/keyboard-navigation.common.js, packages/grid/test/scrolling-mode.common.js, packages/icon/test/icon-font.common.js, packages/multi-select-combo-box/test/chips.common.js, packages/multi-select-combo-box/test/readonly.common.js, packages/radio-group/test/radio-group-keyboard-navigation.common.js, packages/radio-group/test/radio-group.common.js, packages/radio-group/test/validation.common.js, packages/rich-text-editor/test/a11y.common.js, packages/rich-text-editor/test/attach.common.js, packages/select/src/vaadin-select-base-mixin.js, packages/select/test/validation.common.js, packages/virtual-list/test/drag-and-drop.common.js, web-test-runner-firefox.config.js, yarn.lock
Upgrades Playwright to version 1.48.2.
Depends on 
- https://github.com/vaadin/web-components/pull/8387
=> chore: upgrade playwright to 1.48.2

packages/grid/test/keyboard-navigation-row-focus.common.js
Replacing `flushGrid` with `nextFrame` helps deal with this failure when running tests locally in Firefox:
```
yarn test:firefox --group grid --glob="keyboard-navigation-row-focus*"
yarn run v1.22.19
$ web-test-runner --config web-test-runner-firefox.config.js --group grid '--glob=keyboard-navigation-row-focus*'
packages/grid/test/keyboard-navigation-row-focus-polymer.test.js:
❌ keyboard navigation - row focus > scrolling and navigating > should scroll focused nested row into view on Tab
TypeError: Node.insertBefore: Argument 1 is not an object.
at __reorderElements (packages/component-base/src/virtualizer-iron-list-adapter.js:824:32)
at _scrollHandler/this.__scrollReorderDebouncer< (packages/component-base/src/virtualizer-iron-list-adapter.js:567:20)
at flush …
```
=> test: replace flushGrid with nextFrame to fix local failure

packages/combo-box/src/vaadin-combo-box-mixin.js, packages/combo-box/test/keyboard.common.js, packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/test/basic.common.js, packages/field-base/src/clear-button-mixin.js, packages/field-base/test/clear-button-mixin.test.js, packages/multi-select-combo-box/test/basic.common.js
Fixes #8448
- Added missing logic and tests to check `readonly` property before clearing value on <kbd>Esc</kbd>
- Refactored `ComboBoxMixin` listener to remove duplication and only check for `readonly` once
- Bugfix
Ideally this change would require moving `readonly` property to `ClearButtonMixin` since it's now used there.
However we already have some problems with mixins structure since e.g. `ComboBoxMixin` and `DatePickerMixin` technically use `clearButtonVisible` while not extending `ClearButtonMixin`. So maybe we can keep it as is for now.
=> fix: do not clear on Esc with clear button visible when readonly

packages/rich-text-editor/test/a11y.common.js
Moves Tab RTE tests to a separate suite to ensure there is only one RTE on the page, which seems to fix the flakiness in Webkit.
Follow-up #8355
=> test: fix flaky RTE test by moving Tab tests to a separate suite

.github/workflows/unit-tests.yml, package.json, packages/checkbox-group/test/checkbox-group.common.js, packages/checkbox-group/test/validation.common.js, packages/checkbox/test/validation.common.js, packages/combo-box/test/interactions.common.js, packages/combo-box/test/keyboard.common.js, packages/component-base/test/virtualizer-reorder-elements.test.js, packages/context-menu/test/a11y.common.js, packages/date-picker/test/dropdown.common.js, packages/field-base/test/virtual-keyboard-controller.test.js, packages/field-highlighter/test/user-tags.test.js, packages/grid/test/drag-and-drop.common.js, packages/grid/test/keyboard-interaction-mode.common.js, packages/grid/test/keyboard-navigation.common.js, packages/grid/test/scrolling-mode.common.js, packages/icon/test/icon-font.common.js, packages/multi-select-combo-box/test/chips.test.js, packages/multi-select-combo-box/test/readonly.test.js, packages/radio-group/test/radio-group-keyboard-navigation.common.js, packages/radio-group/test/radio-group.common.js, packages/radio-group/test/validation.common.js, packages/rich-text-editor/test/a11y.common.js, packages/rich-text-editor/test/attach.common.js, packages/select/src/vaadin-select-base-mixin.js, packages/select/test/validation.common.js, packages/virtual-list/test/drag-and-drop.common.js, yarn.lock
Cherry-picks #8355 to branch 24.5. Source of conflicts that failed automatic cherry-pick:
- Dashboard tests don't exist in this branch
- MultiSelectComboBox readonly test doesn't have the async keyword in this branch
=> chore: upgrade playwright to 1.48.2 (#8355) (CP: 24.5)

packages/vaadin-lumo-styles/mixins/input-field-shared.js
Currently, the focus-ring width is hardcoded to `2px` in case of `invalid` state.
I checked https://github.com/vaadin/web-components/pull/6634 and there was no mention of it, most probably it's an oversight.
- Bugfix
=> fix: also apply focus-ring width custom property to invalid state

DEVELOPMENT.md
Documented the config needed for tests with `sendKeys({ press: 'Tab' })` on native `<button>` to pass in WebKit.
=> chore: document testing Tab with Playwright WebKit on Mac OS

packages/dashboard/theme/lumo/vaadin-dashboard-section-styles.js, packages/dashboard/theme/lumo/vaadin-dashboard-widget-styles.js
Remove use of `addGlobalThemeStyles` in dashboard widget in favor of using local CSS variables
Refactor
=> refactor: remove global dashboard widget styles

packages/charts/theme/vaadin-chart-base-theme.js
In the Highcharts Gantt chart, you can create tasks (as data points of the series) and using the `completed` property you can define how much the given task is completed:
This should be visually represented in the chart (for example, see this demo: https://www.highcharts.com/demo/gantt/progress-indicator). While testing Gantt chart integration in Vaadin `<vaadin-chart>` component, I noticed that the progress is not visible in the chart at all.
The reason for it was that in the `styled mode` there is no custom style defined for the progress element overlay:
This change introduces a proper style, that darkens the underlying color a bit so the progress is visible (the default behavior of the Highcharts Gantt is also to darken the underlying color):
Part of …
=> feat: add support for Gantt task progress indication

packages/board/src/vaadin-board-row.js, packages/board/src/vaadin-board.js
Both `vaadin-board` and `vaadin-board-row` are missing styles for `hidden` attribute. This PR fixes that.
- Bugfix
=> fix: add missing hidden attribute styles to board and board row

packages/map/package.json, packages/map/src/vaadin-map-mixin.d.ts, packages/map/src/vaadin-map-mixin.js, packages/map/src/vaadin-map.d.ts, packages/map/src/vaadin-map.js
Extracted `vaadin-map` logic into mixin to be reused by the Lit version.
- Refactor
=> refactor: extract map logic into reusable mixin

packages/cookie-consent/package.json, packages/cookie-consent/src/vaadin-cookie-consent-mixin.d.ts, packages/cookie-consent/src/vaadin-cookie-consent-mixin.js, packages/cookie-consent/src/vaadin-cookie-consent.d.ts, packages/cookie-consent/src/vaadin-cookie-consent.js
Extracted `vaadin-cookie-consent` logic into mixin for reusing by Lit based version.
- Refactor
=> refactor: extract cookie consent logic into reusable mixin

packages/field-highlighter/src/vaadin-field-highlighter-styles.d.ts, packages/field-highlighter/src/vaadin-field-highlighter-styles.js, packages/field-highlighter/src/vaadin-field-outline.js, packages/field-highlighter/src/vaadin-user-tag.js, packages/field-highlighter/src/vaadin-user-tags-overlay.js
Extracted `vaadin-field-highlighter` styles into CSS tagged literals for reusing by LitElement based version.
- Refactor
=> refactor: extract field highlighter styles into reusable css literals

packages/cookie-consent/package.json, packages/cookie-consent/src/vaadin-lit-cookie-consent.d.ts, packages/cookie-consent/src/vaadin-lit-cookie-consent.js, packages/cookie-consent/test/cookie-consent-lit.test.js, packages/cookie-consent/test/cookie-consent-polymer.test.js, packages/cookie-consent/test/cookie-consent.common.js, packages/cookie-consent/theme/lumo/vaadin-lit-cookie-consent.js, packages/cookie-consent/theme/material/vaadin-lit-cookie-consent.js, packages/cookie-consent/vaadin-lit-cookie-consent.d.ts, packages/cookie-consent/vaadin-lit-cookie-consent.js
Depends on #8491
Added an experimental version of `vaadin-cookie-consent` based on LitElement.
- Experiment
=> experiment: add LitElement based version of vaadin-cookie-consent

packages/vaadin-lumo-styles/utilities/flexbox-grid.js
Classes added in #7515 didn't have a colon and it went unnoticed for a while 😕 
- Bugfix
=> fix: add missing colon in responsive alignment utility classes

packages/grid/src/vaadin-grid-drag-and-drop-mixin.js, packages/grid/test/drag-and-drop.common.js
Grid currently stops the propagation of all native "dragleave" events which causes the issue. The propagation of "dragleave" event should only be stopped if the grid has a `dropMode`, in which case corresponding "dragover" and "dragenter" events are also processed by the grid dnd logic
Fixes #8476
- Bugfix
=> fix: do not stop ignored dragleave events in grid

packages/grid/src/vaadin-grid-column-auto-width-mixin.d.ts, packages/grid/src/vaadin-grid-column-auto-width-mixin.js, packages/grid/src/vaadin-grid-mixin.d.ts, packages/grid/src/vaadin-grid-mixin.js
As a first step to fixing the related issue, let's extract the logic related to column auto-width recalculation into a separate mixin from the already-too-bloated `GridMixin`.
Related to https://github.com/vaadin/flow-components/issues/6976
Refactor
=> refactor: extract grid column auto-width mixin

packages/horizontal-layout/src/vaadin-horizontal-layout-styles.d.ts, packages/horizontal-layout/src/vaadin-horizontal-layout-styles.js, packages/horizontal-layout/src/vaadin-horizontal-layout.js, packages/horizontal-layout/src/vaadin-lit-horizontal-layout.js
Related to https://github.com/vaadin/platform/issues/5038
Let's extract styles into single file to avoid further code duplication when adding styles for `middle` and `end` slots.
- Refactor
=> refactor: extract horizontal layout styles into CSS literal

packages/grid/src/vaadin-grid-column-auto-width-mixin.js, packages/grid/src/vaadin-grid-mixin.js, packages/grid/test/column-auto-width.common.js, packages/grid/test/filtering.common.js, packages/grid/test/helpers.js
Follow-up for https://github.com/vaadin/web-components/pull/8507
This PR cleans up the newly added `ColumnAutoWidthMixin`
- All checks for whether grid is ready for column width recalculation are now performed in a single function (`__isReadyForColumnWidthCalculation`) instead of having them scattered around like before
- `recalculateColumnWidths` is now short and clean
- All external calls to the mixin's functions (`__tryToRecalculateColumnWidthsIfPending`, `recalculateColumnWidths`) are removed. The mixin itself uses property observers and event listeners to determine when they should be called.
Related to https://github.com/vaadin/flow-components/issues/6976
Refactor
=> refactor: clean up grid column auto width mixin

packages/grid/src/vaadin-grid-column-auto-width-mixin.js, packages/grid/test/column-auto-width.common.js
Defer column width calculation until frozen columns are updated.
Fixes https://github.com/vaadin/flow-components/issues/6976
Bugfix
=> fix: defer column width calculation until frozen columns update

packages/grid/src/vaadin-grid-mixin.js, packages/grid/test/column-auto-width.common.js, packages/grid/test/frozen-columns.common.js
Fixes https://github.com/vaadin/flow-components/issues/6976 in `24.6` branch. Note that the implementation is different from the one in `main` branch due to the structural differences (https://github.com/vaadin/web-components/pull/8507 and https://github.com/vaadin/web-components/pull/8512).
- In `main`, the column width calculation is [postponed](https://github.com/vaadin/web-components/pull/8514) until frozen columns are updated
- In `24.6`, any active frozen columns update is flushed before column width calculation
Bugfix
=> fix: flush frozen columns before calculating auto width

packages/charts/src/vaadin-chart.d.ts, packages/charts/src/vaadin-chart.js, packages/charts/test/events.test.js, packages/charts/test/typings/chart.types.ts
Until now, the `vaadin-chart` component did not support drag&drop at all.
This PR brings support for drag and drop:
* It loads the required extension module
* It adds three new events to the `vaadin-chart`: dragStart, drag and drop -> the code is the same as for any other chart point event
The only significant change is in the `__createEventListeners` method: I found during testing, that the data of the `customEvent` are not correct in case of `dragStart`. Highcharts fires `dragStart` with a different content of the `event` object: `event.type` is missing, and the `event` object itself is actually the original `mousedown` event object. 
However, Highcharts passes the `point` that is being dragged as a `this` of the event handler (it does this for every event type... even for the series …
=> feat: add drag&drop support to vaadin-chart

packages/menu-bar/src/vaadin-menu-bar-mixin.js
Vaadin buttons automatically set the appropriate tabindex based on their disabled state, so it's unnecessary to manually set it for menu bar buttons.
Part of #4585
=> refactor: remove duplicate tabindex logic

packages/a11y-base/src/list-mixin.js
The `_isItemHidden` of ListMixin isn't used anywhere.
=> refactor: remove unused method in list-mixin

packages/grid/src/vaadin-grid-drag-and-drop-mixin.js, packages/virtual-list/src/vaadin-virtual-list-mixin.js
Fixes #8386
This PR enhances the [drag image workaround](https://github.com/vaadin/web-components/blob/0ea930d9acac0244e7c4a4b550e558dae190411d/packages/grid/src/vaadin-grid-drag-and-drop-mixin.js#L327) in grid (and virtual-list) to avoid having content outside the dragged element from ending up in the drag image on grids with smaller amount or rows.
Before this change:
https://github.com/user-attachments/assets/80e9a273-e6c6-404d-803e-fdb3deefea2d
Bugfix
=> fix: avoid content outside grid ending up in drag image

packages/grid/src/vaadin-grid-styles.js, packages/grid/test/min-height.common.js, packages/grid/test/resizing.common.js
Prevent grid with all rows visible from shrinking.
Fixes #8509 
Bugfix
=> fix: prevent grid with all rows visible from shrinking

packages/split-layout/src/vaadin-split-layout-mixin.js, packages/split-layout/test/split-layout.common.js
Fixes #8531
Added missing check for `nodeType` in `MutationObserver` to ignore disconnected comment nodes inserted by Lit.
- Bugfix
=> fix: check if node is an element when removing slot attribute

packages/button/src/vaadin-button-mixin.js, packages/button/test/button.common.ts, packages/crud/test/crud-buttons.common.js
The PR ensures that interaction events like `click`, `mousedown`, etc. are suppressed on disabled buttons even when `pointer-events` is set to `auto`. 
This change revealed an issue with a CRUD test. When running this test with the Lit version in WebKit or Safari, the save button remains disabled for some reason after the click event. Previously, it was passing by mistake. I've decided to temporarily skip this test, as the cause remained unclear even after several hours of debugging:
https://github.com/vaadin/web-components/blob/8463c9fc33eea453e2a28c8d9e1e6390ea80357d/packages/crud/src/vaadin-crud-mixin.js#L693
Part of #4585
=> refactor: ensure disabled buttons suppress interaction events

.eslintrc.json, test/integration/notification-overlay.test.js
Fixed incorrect override glob that was using `*.js` and removed one `console.log` which was unnoticed because of that.
=> chore: fix ESLint override glob, remove console.log from test

packages/grid/src/vaadin-grid-drag-and-drop-mixin.js
Remove no longer necessary check for native dnd support in grid's drag/drop mixin
Chore
=> chore: remove unnecessary native dnd support check in grid

test/integration/component-tooltip.test.js, test/integration/confirm-dialog-fields.test.js
Updated IT tests to avoid following warnings:
```
test/integration/component-tooltip.test.js:
Error: [object HTMLInputElement] is not contained inside [object HTMLBodyElement]. Skip setting aria-hidden.
Error: [object HTMLInputElement] is not contained inside [object HTMLBodyElement]. Skip setting aria-hidden.
test/integration/confirm-dialog-fields.test.js:
Error: [object HTMLInputElement] is not contained inside [object HTMLBodyElement]. Skip setting aria-hidden.
```
- In the component tooltip test, added `await nextRender()` after opening date-picker overlay,
- in the confirm-dialog test, added `autoOpenDisabled` as we don't need to open overlay there. …
=> test: prevent date-picker aria-hidden warning in ITs

packages/card/src/vaadin-card.d.ts
Follow-up to #8233
The change in JSDoc was only made in `.js` file. This PR updates the `.d.ts` file accordingly.
=> chore: align vaadin-card JSDoc annotation in .d.ts file

packages/field-highlighter/src/vaadin-user-tags.js, packages/field-highlighter/test/user-tags.test.js
Remove the use of `calculateSplices` in `<vaadin-user-tags>` as suggested in https://github.com/vaadin/web-components/pull/8494#pullrequestreview-2542593734
Refactor
=> refactor: remove use of calculateSplices in user tags

packages/vertical-layout/src/vaadin-lit-vertical-layout.js, packages/vertical-layout/src/vaadin-vertical-layout-styles.d.ts, packages/vertical-layout/src/vaadin-vertical-layout-styles.js, packages/vertical-layout/src/vaadin-vertical-layout.js
Similar to https://github.com/vaadin/web-components/pull/8510, extracts vertical layout styles to avoid further duplication when adding the planned layout fixes.
=> refactor: extract vertical layout styles into CSS literal

packages/button/src/vaadin-button.d.ts, packages/button/src/vaadin-button.js, packages/menu-bar/src/vaadin-menu-bar-mixin.d.ts, packages/menu-bar/src/vaadin-menu-bar-mixin.js
Following Rolf's suggestion, the PR updates the JSDoc for disabled buttons to remove mentions of "experimental". The new version is based on the [docs text](https://github.com/vaadin/docs/pull/4077).
Part of #4585
=> docs: remove mentions of 'experimental' from JSDoc

packages/upload/src/vaadin-lit-upload.js
Unlike other Lit components, the `vaadin-upload` incorrectly imported Polymer based version of `vaadin-button`.
- Bugfix
=> fix: import button from correct file in Lit version of upload

packages/icon/src/vaadin-lit-icon.js, packages/notification/src/vaadin-lit-notification.js, packages/virtual-list/src/vaadin-lit-virtual-list.js
Some components were missing this annotation so I added it for consistency. This will be needed in the future when we switch implementations to use Lit by default so that `render()` doesn't get shown as public method in the API docs.
=> chore: add protected JSDoc annotation to render method

packages/grid/src/vaadin-grid-styles.js, packages/grid/test/min-height.common.js, packages/grid/test/resizing.common.js
https://github.com/vaadin/web-components/pull/8535 caused a regression by preventing a grid with all rows visible from shrinking horizontally in a flexbox.
Seems we have to use the `min-height: auto` approach to fix the original issue after all.
Bugfix
=> fix: allow all rows visible grid shrink horizontally

packages/grid-pro/test/keyboard-navigation.common.js
Adds `await nextFrame()` to wait for possible scroll into view, which may occur if the next cell isn't fully within the viewport. This should hopefully stabilize the test in Webkit.
=> test: wait for possible scroll into view

packages/multi-select-combo-box/test/visual/common.js
Unlike other components, `vaadin-multi-select-combo-box` handles `caret-color` property on the slotted input to detect whether to show placeholder or not. This rule overrides the hack that we have in visual tests making one of them flaky:
Updated the hack to increase specificity so that it overrides the style defined in Lumo and Material themes. 
- Test
=> test: increase specificity to hide caret color in visual tests

packages/date-time-picker/test/visual/common.js
Currently, in `vaadin-date-time-picker` visual tests the CSS workaround is applied to `vaadin-date-picker`.
Changed it to use `vaadin-*-picker` so that it also applies to `vaadin-date-time-picker` and `vaadin-time-picker`.
This is needed because the slotted input styles are for individual pickers, but disabling animations on the error message part needs to be done on the `vaadin-date-time-picker` element itself (which is currently not applied).
This should fix the flakiness in the following visual tests:
```
❌ date-time-picker > default > error message
Error: Visual diff failed. New screenshot is 0.42% different.
See diff for details: /home/runner/work/web-components/web-components/packages/date-time-picker/test/visual/material/screenshots/date-time-picker/failed/error-message-diff.png
at …
```
=> test: correctly apply CSS in date-time-picker visual test

packages/combo-box/test/visual/lumo/combo-box.test.js, packages/combo-box/test/visual/material/combo-box.test.js, packages/date-picker/test/visual/lumo/date-picker.test.js, packages/date-picker/test/visual/material/date-picker.test.js, packages/date-time-picker/test/visual/lumo/date-time-picker.test.js, packages/date-time-picker/test/visual/material/date-time-picker.test.js, packages/field-highlighter/test/visual/lumo/field-highlighter.test.js, packages/field-highlighter/test/visual/material/field-highlighter.test.js, packages/multi-select-combo-box/test/visual/lumo/multi-select-combo-box.test.js, packages/multi-select-combo-box/test/visual/material/multi-select-combo-box.test.js
This fixes the following warnings in visual tests after converting `field-highlighter` package to Lit:
```
The custom element definition for "vaadin-user-tags-overlay" was finalized before a style module was registered. Ideally, import component specific style modules before importing the corresponding custom element. This warning can be suppressed by setting "window.Vaadin.suppressPostFinalizeStylesWarning = true".
The custom element definition for "vaadin-user-tag" was finalized before a style module was registered. Ideally, import component specific style modules before importing the corresponding custom element. This warning can be suppressed by setting "window.Vaadin.suppressPostFinalizeStylesWarning = true".
```
Updated other visual tests to make sure `common.js` and …
=> test: import files that register styles before custom elements

packages/grid-pro/test/keyboard-navigation.common.js
There was sometimes a second focus call originating from:
https://github.com/vaadin/web-components/blob/e34b3ba52150e9e8224f72ecbf0df927f503f562/packages/grid/src/vaadin-grid-mixin.js#L795-L807
The PR updates the tests to wait for this animation to finish before any interactions.
=> test: another attempt to stabilize grid-pro test

packages/a11y-base/test/focus-trap-controller.test.js, packages/app-layout/test/helpers.js, packages/checkbox-group/test/checkbox-group.common.js, packages/checkbox-group/test/validation.common.js, packages/checkbox/test/validation.common.js, packages/component-base/test/virtualizer-reorder-elements.test.js, packages/context-menu/test/a11y.common.js, packages/date-picker/test/fullscreen.common.js, packages/date-picker/test/keyboard-input.common.js, packages/date-picker/test/keyboard-navigation.common.js, packages/date-time-picker/test/validation.test.js, packages/field-highlighter/test/field-components.test.js, packages/grid-pro/test/edit-column.common.js, packages/grid-pro/test/keyboard-navigation.common.js, packages/grid/test/disabled.common.js, packages/grid/test/keyboard-interaction-mode.common.js, packages/menu-bar/test/menu-bar.common.js, packages/menu-bar/test/sub-menu.common.js, packages/password-field/test/password-field.common.js, packages/popover/test/a11y.test.js, packages/radio-group/test/radio-group.common.js, packages/radio-group/test/validation.common.js, packages/rich-text-editor/test/a11y.common.js, packages/upload/test/file.common.js, test/integration/dialog-accordion.test.js, test/integration/dialog-date-picker.test.js, test/integration/grid-pro-custom-editor.test.js, test/test-runner-commands/index.js
=> test: add shortcut for pressing multiple keys simultaneously (#8536) (CP: 24.5)

packages/a11y-base/src/list-mixin.js, packages/a11y-base/test/list-mixin.test.js, packages/select/test/select-lit.test.js, packages/select/test/select-polymer.test.js, packages/select/test/select.common.js
Added missing `sync: true` to ensure Lit based `vaadin-list-box` works correctly in `vaadin-select`.
Also, updated tests to import respective versions of `vaadin-item` and `vaadin-list-box`.
- Refactor
=> refactor: make selected property in ListMixin use sync: true

packages/form-layout/src/vaadin-form-layout-mixin.js
Fixes #8564
I was unable to come up with a reliable test for this since the case where `IntersectionObserver` entries accumulate between callback invocations generally requires some slow rendering, like in the reproduction example provided.
- Bugfix
=> fix: use the most recent IntersectionObserver entry in form-layout

packages/form-layout/src/vaadin-form-item.d.ts, packages/form-layout/src/vaadin-form-item.js
Adds a deprecation note on the documentation that mentions the `label-position` attribute for `FormItem`
Part of #8583
=> docs: deprecate form-item label-position attribute

packages/charts/package.json, packages/charts/src/vaadin-chart-mixin.js, packages/charts/src/vaadin-chart-series-mixin.js, packages/charts/src/vaadin-lit-chart-series.d.ts, packages/charts/src/vaadin-lit-chart-series.js, packages/charts/src/vaadin-lit-chart.d.ts, packages/charts/src/vaadin-lit-chart.js, packages/charts/test/chart-properties.test.js, packages/charts/test/chart-series.test.js, packages/charts/test/exporting.test.js, packages/charts/theme/lumo/vaadin-lit-chart.js, packages/charts/theme/material/vaadin-lit-chart.js, packages/charts/vaadin-lit-chart-series.d.ts, packages/charts/vaadin-lit-chart-series.js, packages/charts/vaadin-lit-chart.d.ts, packages/charts/vaadin-lit-chart.js, scripts/generateLitTests.js
Depends on https://github.com/vaadin/web-components/pull/8562
Added an experimental version of `vaadin-chart` based on LitElement.
Experiment
=> experiment: add LitElement based version of vaadin-chart

package.json, wtr-utils.js, yarn.lock
My PR to `@web/test-runner-saucelabs` was merged and released: https://github.com/modernweb-dev/web/pull/2852
- Upgraded the dev dependency version in `package.json`, let's see if visual tests pass.
- Updated `filterBrowserLogs` to filter out `webdriver` debug warnings from their [customElements wrapper](https://github.com/webdriverio/webdriverio/blob/ec0f3216a76a13564c1fad4b631e03c24298e16a/packages/webdriverio/src/scripts/customElement.ts#L19)
- Internal change 
There are some webdriver errors when running tests for more than a single file.
Added a comment about that here https://github.com/webdriverio/webdriverio/issues/13467#issuecomment-2618557897
UPD: reported a new issue for this error https://github.com/webdriverio/webdriverio/issues/14129
=> chore: upgrade SauceLabs launcher to the latest version

packages/form-layout/src/vaadin-form-layout.js
Manual cherry-pick of #8596 to `24.5` branch.
The `FormLayoutMixin` was only added in `main` and is not present in older branches.
- Cherry-pick
=> fix: use the most recent IntersectionObserver entry in form-layout (#8596) (CP: 24.5)

wtr-utils.js
Let's use this to get rid of webdriver BiDi protocol errors and also hopefully fix the following error:
```
Error: Error while executing command set-window-height with payload {"height":610}: WebDriverError: unknown error: failed to change window state to 'normal', current state is 'maximized'
```
=> chore: enforce Webdriver classic protocol in visual tests

package.json, wtr-utils.js, yarn.lock
Manual cherry-pick of #8573 to `24.5` branch.
There was a merge conflict in yarn.lock that was resolved by running `yarn` locally.
Note: I had to enable `'wdio:enforceWebDriverClassic'` option since older branches use Chrome versions 110 (Lumo) and 88 (Material) and apparently don't support BiDi protocol used by default in Webdriver 9.
- Cherry-pick
=> chore: upgrade SauceLabs launcher to the latest version (#8573) (CP: 24.5)

packages/combo-box/theme/material/vaadin-combo-box-overlay-styles.js
The Material theme for combo box uses `overflow: visible` on the overlay part to allow showing the loading indicator, which is positioned upwards to cover the field's bottom border (added in https://github.com/vaadin/vaadin-combo-box/pull/743). However this causes the overlay sizing logic to break, which apparently needs `overflow: auto`.
This fixes the styles to only apply `overflow: visible` when the combo box is actually loading. That should be fine as the combo box is empty in that state and the overlay sizing logic is not (as) relevant.
**Before:**
https://github.com/user-attachments/assets/fe430979-7aad-4b70-bf8c-5c7de704dae8
**After:**
https://github.com/user-attachments/assets/332b5222-e261-439b-887e-fe77152e0f0f
Fixes https://github.com/vaadin/flow-components/issues/7063
- Bugfix
=> fix: fix Material combo box overlay sizing

packages/form-layout/src/vaadin-form-layout-mixin.js
Removes `IntersectionObserver` from FormLayout in favor of ResizeMixin's `_onResize` which is also triggered when the element's visibility changes as a result of `display: none` or any other method that completely removes the element from the render tree.
Part of #8583
=> refactor: use _onResize instead of IntersectionObserver

packages/upload/src/vaadin-upload.d.ts, packages/upload/test/typings/upload.types.ts
Types `event.target` for upload events, so that casting the target is unnecessary when trying to use the upload element in event handlers. This could be used for example to clear the files when an upload has finished using `event.target.files = []`.
Part of https://github.com/vaadin/web-components/issues/7868
- Feature
=> feat: type event target for upload events

packages/form-layout/test/form-layout.test.js
The PR refactors FormLayout tests to avoid relying on implementation details.
Part of #8583
=> test: refactor tests to avoid relying on implementation details

packages/form-layout/test/form-layout.test.js
Fixes the following test failures that were introduced in #8633:
```
packages/form-layout/test/form-layout-lit.generated.test.js:
❌ form layout > hidden > should update steps on show after hidden
AssertionError: expected _selectResponsiveStep to have been called exactly once, but it was called 0 times
at n.<anonymous> (packages/form-layout/test/form-layout-lit.generated.test.js:444:24)
packages/form-layout/test/form-layout.test.js:
❌ form layout > hidden > should update steps on show after hidden
AssertionError: expected _selectResponsiveStep to have been called exactly once, but it was called 0 times
at n.<anonymous> (packages/form-layout/test/form-layout.test.js:444:24)
```
=> test: add missing nextResize

packages/grid/src/vaadin-grid-drag-and-drop-mixin.js, packages/grid/test/drag-and-drop.test.js
Grid currently stops the propagation of all native "dragleave" events which causes the issue. The propagation of "dragleave" event should only be stopped if the grid has a dropMode, in which case corresponding "dragover" and "dragenter" events are also processed by the grid dnd logic
Fixes https://github.com/vaadin/web-components/issues/8476
=> fix: do not stop ignored dragleave events in grid (#8500) (CP: 23.5)

packages/form-layout/src/vaadin-form-item.d.ts, packages/form-layout/src/vaadin-form-item.js, packages/form-layout/src/vaadin-form-layout.d.ts, packages/form-layout/src/vaadin-form-layout.js
Adds:
-  missing documentation for `--vaadin-form-layout-row-spacing` styling variable
- deprecation warning to the documentation of `--vaadin-form-item-row-spacing` styling variable
=> docs: add new variable doc and deprecate old one

test/integration/dialog-form-layout.test.js
Using `<vaadin-text-field>` appears to increase the minimum width of each FormLayout column, causing the total minimum width of FormLayout to exceed FormLayout's largest breakpoint. This in turn prevents the test from alerting us to a visual regression that emerge when [switching to CSS grid](https://github.com/vaadin/web-components/pull/8590), which was the underlying purpose of this test.
=> test: improve test coverage by using native input

packages/form-layout/src/vaadin-form-layout-mixin.js
The PR refactors the `isValidCSSLength` method in FormLayout to use `CSS.supports` which is supported by all modern browsers. As a result, it also removes the need for the `style` element that was previously added as a child of FormLayout.
Part of #8583
=> refactor: simplify isValidCSSLength by using CSS.supports

packages/avatar-group/src/vaadin-avatar-group-mixin.d.ts, packages/avatar-group/src/vaadin-avatar-group-mixin.js, packages/avatar-group/test/avatar-group.test.js, packages/avatar-group/test/typings/avatar-group.types.ts, packages/component-base/src/i18n-mixin.d.ts, packages/component-base/src/i18n-mixin.js, packages/component-base/test/i18n-mixin.test.js, packages/component-base/test/typings/i18n-mixin/i18n-mixin.types.ts
Adds support for partial I18N objects to avatar group. This allows setting an I18N object that only overrides some of the translations and uses default translations as fallback.
- Feature
=>  feat: support partial i18n in avatar group 

test/test-runner-commands/index.js, yarn.lock
Upgraded `puppeteer` version to 23.11.1 to verify my finding from https://github.com/vaadin/web-components/pull/8615#issuecomment-2633334713.
Some tests in `tooltip-timers.test.js` fail since unwanted `mouseenter` event fires at `0, 0` coordinates.
Especially in `packages/tooltip/test/tooltip-timers-lit.generated.test.js`. Let's see if this also happens in CI.
=> chore: upgrade puppeteer version in yarn.lock to 23.11.1

test/test-runner-commands/index.js, yarn.lock
Manual cherry-pick of #8631 to `24.5` branch (there was a merge conflict in `yarn.lock`).
- Cherry-pick
=> chore: upgrade puppeteer version in yarn.lock to 23.11.1 (#8631) (CP: 24.5)

packages/grid/test/scroll-into-view.test.js
Some tests using `sendMouse()` are currently missing `resetMouse()`, which can cause issues after the Puppeteer version update e.g. in `field-highlighter` tests failing in #8654. This should fix that.
- Test
=> test: add missing resetMouse to tests using sendMouse

packages/app-layout/src/vaadin-app-layout-mixin.d.ts, packages/app-layout/src/vaadin-app-layout-mixin.js, packages/app-layout/test/typings/app-layout.types.ts
Adds support for partial I18N objects to app layout. This allows setting an I18N object that only overrides some of the translations and uses default translations as fallback.
- Feature
=> feat: support partial i18n in app layout

packages/grid-pro/test/keyboard-navigation.test.js
The `console.log` was left when backporting loading editor state in #8164
- Test
=> test: remove console.log from grid-pro keyboard test (24.5)

package.json, yarn.lock
Manual cherry-pick of #8652 to `24.6` branch (there was a conflict due to extra whitespace in `package.json`).
- Cherry-pick
=> chore: upgrade playwright version to ^1.50 (#8652) (CP: 24.6)

packages/checkbox-group/test/checkbox-group.test.js
This test was added in the original MVP at https://github.com/vaadin/vaadin-checkbox/pull/103 and its purpose is unclear.
There is no logic related to moving focus in the component nowadays, so it can be removed.
- Test
=> test: cleanup outdated checkbox-group focus test

packages/avatar-group/src/vaadin-avatar-group-mixin.d.ts, packages/avatar/src/vaadin-avatar-mixin.d.ts, packages/avatar/src/vaadin-avatar-mixin.js
Adds support for partial I18N objects to avatar. This allows setting an I18N object that only overrides some of the translations and uses default translations as fallback.
- Feature
=> feat: support partial i18n in avatar

packages/crud/src/vaadin-crud-mixin.d.ts, packages/crud/src/vaadin-crud-mixin.js, packages/crud/src/vaadin-crud.js, packages/crud/src/vaadin-lit-crud.js, packages/crud/test/crud-buttons.test.js, packages/crud/test/crud.test.js, packages/crud/test/typings/crud.types.ts
Adds support for partial I18N objects to crud. This allows setting an I18N object that only overrides some of the translations and uses default translations as fallback.
- Feature
=>  feat: support partial i18n in crud

packages/component-base/src/virtualizer-iron-list-adapter.js, packages/component-base/test/virtualizer.test.js
Fixes #8630
Related to https://github.com/vaadin/web-components/issues/6431#issuecomment-2620032575
When an element using virtualizer (e.g. virtual-list or grid) is used in dialog or other overlay, it is moved within DOM while also changing visibility. Added `ResizeObserver` to handle this case and restore `scrollTop`, which gets reset whenever the element gets disconnected from the DOM. This fixes the problem of empty items after dialog reopening.
- Bugfix
=> fix: restore scroll position when virtualizer host is connected

packages/dashboard/src/vaadin-dashboard-section.js, packages/dashboard/src/vaadin-dashboard-widget.js, packages/dashboard/src/vaadin-dashboard.d.ts, packages/dashboard/src/vaadin-dashboard.js, packages/dashboard/test/dashboard.test.ts, packages/dashboard/test/typings/dashboard.types.ts
Adds support for partial I18N objects to dashboard. This allows setting an I18N object that only overrides some of the translations and uses default translations as fallback.
- Feature
=> feat: support partial i18n in dashboard

.gitignore, package.json, scripts/check-releases.js, scripts/check-releases.template.html
Adds a script for checking whether new versions need to be released. The script does:
- Look up the last release commit and all commits added since then
- Determines the next patch version
- Generates an HTML file with that information for each maintained branch (branches are currently hard-coded)
- Opens the HTML file using Web Dev Server
- The HTML also contains branch-specific release instructions with specific steps, links and data that needs to be filled in
To use it:
- Define `GITHUB_API_TOKEN` in an env variable, for example with the `.env` file
- Run `npm run check-releases`
- Internal
=> chore: add check-releases script

packages/confirm-dialog/src/vaadin-confirm-dialog-overlay-styles.js, packages/confirm-dialog/test/confirm-dialog.test.js
Fixes #8650
The `_contentHeight` property sets height of the `overlay` part but the inner `<section id="resizerContainer">` does not respect it and that makes footer look incorrect. Added `height: 100%` to make sure the footer is placed at the bottom.
- Bugfix
=> fix: place confirm-dialog footer correctly when height is set

scripts/check-releases.template.html
- Make the NPM link point directly to the released version, so you don't have to click through to the versions to find it
- Make link for editing the release point to the releases overview, as the URL can not be determined beforehand (actual URL is something like `https://github.com/vaadin/web-components/releases/tag/untagged-77285af86d5ae5871db4`)
=> chore: update links generated by check releases script

package.json, yarn.lock
Upgraded `typescript` version to latest. Also updated `@typescript-eslint` transitive depdnecneis in yarn.lock
=> chore: upgrade typescript and eslint dependencies

packages/form-layout/src/vaadin-form-item-mixin.js, packages/form-layout/src/vaadin-form-item.d.ts, packages/form-layout/src/vaadin-form-item.js, packages/form-layout/src/vaadin-form-layout-styles.js, packages/form-layout/src/vaadin-form-layout.js, packages/form-layout/test/form-layout.test.js
This PR introduces the CSS properties `--vaadin-form-layout-label-width` and `--vaadin-form-layout-label-spacing`, and deprecates the old form item properties `--vaadin-form-item-label-width` and `--vaadin-form-item-label-spacing`.
Fixes https://github.com/vaadin/web-components/issues/8683
=> feat: add form layout CSS properties, deprecate form item ones

dev/form-layout-auto-responsive.html
Adds a dev page with auto responsive form layout examples.
Part of #8684
=> chore: add form-layout-auto-responsive dev page

packages/overlay/src/vaadin-overlay-stack-mixin.js, packages/overlay/test/multiple.test.js
Part of #8521
Fixing the above issue where popover overlay ends up behind its parent dialog overlay requires us to add new APIs:
1. Add internal API to mark parent-child relationship so that an overlay can have a single "nested" overlay (and then call `bringToFront()` recursively for all its nested overlays once its own `bringToFront()` is called),
2. Add helper to detect which overlay needs to be marked as parent based on certain criteria - in case of `vaadin-popover` it should be basically the overlay where its `target` is attached (note that `vaadin-popover` itself can be elsewhere).
This PR focuses on the first part. I'm going to create a separate PR as a follow-up with the actual fix for popover.
=> feat: add internal API for nested overlays to bringToFront

packages/menu-bar/src/vaadin-menu-bar-mixin.d.ts, packages/menu-bar/src/vaadin-menu-bar.d.ts, packages/menu-bar/test/typings/menu-bar.types.ts
Make `MenuBar` and `MenuBarItem` types generic so that:
- `MenuBarItem` accepts a type for custom item data, so that you can easily create custom item types
- `MenuBar` accepts a custom item type, which restricts the items that can be set, and provides that type in the `item-selected` event
The React component will require its own set of changes, and the same should be done for context menu as well. But those can be done as a follow-up.
Part of https://github.com/vaadin/web-components/issues/8700
=> feat: allow adding custom data to menu bar item types

packages/popover/src/vaadin-popover-overlay-mixin.js, packages/popover/test/nested.test.js, test/integration/dialog-popover.test.js
Fixes #8521
Depends on #8690
- Bugfix
For now the `vaadin-popover` is the only web component where the original issue can be reproduced. Other components e.g. `vaadin-combo-box` have their overlays as modal by default. The `vaadin-tooltip` is modeless but should close on mousedown regardless. So for now I thought the fix can be limited to the popover package.
If we decide to add public API for making overlays non-modal (see #451) then we should reconsider this fix as the issue would then likely affect other components using overlays as well.
=> fix: bring popover overlay to front when used in modeless dialog

packages/text-field/test/text-field.test.js
Removed tests that were only relevant with V14 version:
- value property test was added in https://github.com/vaadin/vaadin-text-field/pull/480 - back then, we used to have different logic for `__userInput`. The test is now pointless since we check for `event.isTrusted` anyways and the fake input event dispatched in the test would not set the flag. Also, the original issue is not reproducible anymore.
- input event test was added in https://github.com/vaadin/vaadin-text-field/pull/353 - back then, we used to have some logic for input event prevention and `__preventInput` flag. This logic was removed when restructuring text-field related mixins for V22.
- Test
=> test: cleanup outdated text-field unit tests

packages/a11y-base/src/focus-utils.js
Updates the isElementHidden implementation to use the native `checkVisibility` method when supported by the browser. Since this method is only available from Safari 17.4, the custom implementation remains in place as a fallback until Vaadin 25.
=> refactor: use checkVisibility when supported by browser

packages/field-base/test/clear-button-mixin.test.js, packages/field-base/test/input-control-mixin.test.js, packages/field-base/test/input-mixin.test.js, packages/text-field/test/text-field.test.js, packages/text-field/test/typings/text-field.types.ts
The following unit tests are now covered by mixins, and we have `typings` tests that ensure the text field does apply them:
- `autoselect` - covered by `InputControlMixin`
- `clearButtonVisible` - covered by `ClearButtonMixin`
- `binding` (value) - covered by `InputMixin`
- `clear()` method - covered by `InputMixin`
Also the property delegation logic was moved to mixins:
- `disabled` property - covered by `DelegateFocusMixin`
- `autocorrect`, `autocomplete`, `autocapitalize` - covered by `InputFieldMixin`
- `placeholder`, `readonly`, `required`, `title` - covered by `InputControlMixin`
IMO having these tests only in `@vaadin/text-field` package is not necessary. In particular, they are not present in other field components that use same mixins e.g. `@vaadin/number-field` - in V14, this …
=> test: cleanup text-field unit tests covered by mixins tests

packages/dialog/package.json, packages/dialog/test/draggable-resizable.test.js
This test was added as part of https://github.com/vaadin/vaadin-dialog/pull/182 which was a workaround for an older Safari 13 where "force reflow" was needed - see also https://github.com/vaadin/vaadin-dialog-flow/issues/207#issuecomment-662386853. 
The workaround itself was removed in #5310 but the test was not. Let's remove it now in order to avoid `dialog` depending on `text-area` unnecessarily.
- Test
=> test: cleanup outdated dialog test using text-area

packages/context-menu/src/vaadin-context-menu-mixin.d.ts, packages/context-menu/src/vaadin-context-menu.d.ts, packages/context-menu/src/vaadin-contextmenu-items-mixin.d.ts, packages/context-menu/test/typings/context-menu.types.ts
Make `ContextMenu` and `ContextMenuItem` types generic so that:
- `ContextMenuItem` accepts a type for custom item data, so that you can easily create custom item types
- `ContextMenu` accepts a custom item type, which restricts the items that can be set, and provides that type in the `item-selected` event
Part of https://github.com/vaadin/web-components/issues/8700
=> feat: allow adding custom data to context menu item types

packages/text-area/src/vaadin-lit-text-area.js, packages/text-area/src/vaadin-text-area.js, packages/text-area/test/text-area.test.js
Originally in V14 and up until V21, the textarea was focused on label click:
https://github.com/vaadin/web-components/blob/a865d00fa145a86f989cf19ce33042c2b6ad437a/packages/vaadin-text-field/src/vaadin-text-area.js#L138
However, I missed to add this click listener in the V22 version added in #2276 (compared to text-field in #2274).
Later we changed to focus on required indicator click in #2824 and the text-area wasn't covered.
Added listener and corresponding test to align with `vaadin-text-field` and other field components.
- Bugfix
=> fix: focus text-area on required indicator click

packages/dialog/src/vaadin-dialog-base-mixin.js, packages/dialog/src/vaadin-dialog-overlay-mixin.d.ts, packages/dialog/src/vaadin-dialog-overlay-mixin.js, packages/dialog/test/dialog.test.js
Fixes #8701
When dragging or resizing the dialog we change `position` to `absolute`. This is needed also when changing position by setting `top` and `left`, but in fact it's not needed when setting `width` or `height` so I added a flag to disable this.
- Bugfix
=> fix: do not set position and max-width when dialog size is set

packages/form-layout/test/form-layout-auto-responsive.test.js
Asserting the computed `gridColumnStart` seems better because it's the actual property responsible for creating the line break, while `--_column-start` serves as a bridge for communicating the intention of a line break from JS to CSS.
=> test: assert gridColumnStart instead of --_column-start

packages/select/src/vaadin-select-overlay-mixin.js, test/integration/dialog-select.test.js
Fixes https://github.com/vaadin/flow-components/issues/7139
See https://github.com/vaadin/flow-components/issues/7139#issuecomment-2678279256 for some clarification on how `_last` flag used by the default implementation of `_shouldCloseOnOutsideClick()` affects `vaadin-select` when inside of a modeless `vaadin-dialog` on header click.
Note: we could instead try to adapt https://github.com/vaadin/web-components/pull/8692, but IMO the proposed fix is much simpler (and aligned with combo-box etc).
- Bugfix
=> fix: always close select on outside click when in modeless dialog

packages/menu-bar/test/typings/menu-bar.types.ts, packages/vaadin-themable-mixin/vaadin-themable-mixin.d.ts
Add `ThemePropertyMixinClass` to the `ThemableMixinClass` type, as it would otherwise be missing from components that extend from `ThemableMixinClass` instead of using the `ThemableMixin` function.
This fixes a regression in `MenuBar` introduced by https://github.com/vaadin/web-components/pull/8698, where the type needed to be changed to extend from mixin class types instead of using mixin functions.
- Bugfix
=> fix: add missing mixin class to MenuBar type

packages/popover/src/vaadin-popover.js, packages/popover/test/a11y.test.js
Fix for a problem found in https://github.com/vaadin/web-components/issues/8702#issuecomment-2681328022
The original logic added in #7609 didn't take into account cases where `popover.target` isn't focused, but wraps a focusable element instead as `focusElement`, which is the case for text-field and other field components.
Modified original tests to run also with `focusElement` case (it's better to review with "ignore whitespace changes").
- Bugfix
=> fix: check if popover target has focusElement as focusable

packages/crud/test/dom/__snapshots__/crud.test.snap.js, packages/email-field/test/dom/__snapshots__/email-field.test.snap.js, packages/number-field/test/dom/__snapshots__/number-field.test.snap.js, packages/text-field/test/dom/__snapshots__/text-field.test.snap.js, packages/upload/test/dom/__snapshots__/vaadin-upload.test.snap.js
When adding a new snapshot test, the snapshot is appended to the corresponding file.
I have regenerated these files using the following command to rearrange snapshots:
```sh
rm -rf ./packages/**/test/dom/__snapshots__/*.test.snap.js && yarn update:snapshots
```
We probably could consider updating CI build to run this and check there are no files changed.
- Test
=> test: regenerate snapshots to match order in respective tests

packages/login/src/vaadin-lit-login-form.js, packages/login/src/vaadin-lit-login-overlay.js, packages/login/src/vaadin-login-form.js, packages/login/src/vaadin-login-mixin.d.ts, packages/login/src/vaadin-login-mixin.js, packages/login/src/vaadin-login-overlay-mixin.js, packages/login/src/vaadin-login-overlay.js, packages/login/test/dom/__snapshots__/login-form.test.snap.js, packages/login/test/dom/__snapshots__/login-overlay.test.snap.js, packages/login/test/dom/login-form.test.js, packages/login/test/dom/login-overlay.test.js, packages/login/test/login-overlay.test.js, packages/login/test/typings/login.types.ts
Adds support for partial I18N objects to login. This allows setting an I18N object that only overrides some of the translations and uses default translations as fallback.
- Feature
=> feat: support partial i18n in login

packages/popover/src/vaadin-popover.js, packages/popover/test/trigger.test.js
Fixes #8740
There was a similar issue previously fixed for `mouseleave` event in #8093.
The problem was introduced in #7661 where `isLastOverlay()` was added.
- Bugfix
=> fix: do not open popover after focusout during focus delay

packages/form-layout/src/vaadin-form-layout-mixin.js, packages/form-layout/src/vaadin-form-layout-styles.js, packages/form-layout/test/dom/__snapshots__/form-layout.test.snap.js
Adds the `_grid` prefix to CSS properties that are set on the `#layout` element for consistency.
=> refactor: prefix CSS properties set on #layout with _grid

packages/form-layout/src/vaadin-form-layout-mixin.js, packages/form-layout/test/form-layout-auto-responsive.test.js
The PR fixes the issue where adding / removing fields dynamically to form rows didn't trigger a layout update.
Part of https://github.com/vaadin/platform/issues/7172
=> fix(FormLayout): observe DOM changes in form rows

packages/date-picker/test/basic.test.js
This test was added in https://github.com/vaadin/vaadin-date-picker/pull/420 - back then, the component was using nested `vaadin-text-field`. While the style is still there in [shared styles](https://github.com/vaadin/web-components/blob/870230ea45058d62ba8ade14a077aa3773524269/packages/field-base/src/styles/input-field-container-styles.js#L13), removing it doesn't affect the test so it can be removed as outdated.
- Test
=> test: cleanup outdated date-picker wrapping unit test

packages/form-layout/src/layouts/auto-responsive-layout.js, packages/form-layout/src/layouts/responsive-steps-layout.js
Fixed a missing `.js` extension in two imports to avoid errors with webpack.
- Bugfix
=> fix: add missing .js extension to form-layout imports

packages/grid-pro/test/edit-column-type.test.js
This test was in https://github.com/vaadin/vaadin-grid-pro/pull/53 added alongside with check to avoid following error:
```
vaadin-grid-pro-edit-select.html.js:56 Uncaught TypeError: Cannot read properties of undefined (reading 'contains')
at GridProEditSelectWrapperElement._onSelectFocusout (vaadin-grid-pro-edit-select.html.js:56:25)
```
The `_onSelectFocusout` method was later on removed in https://github.com/vaadin/vaadin-grid-pro/pull/96 when switching to different workaround. So this test is essentially no longer relevant and can be removed as outdated.
- Test
=> test: cleanup outdated grid-pro edit select test

packages/context-menu/src/vaadin-contextmenu-event.js, test/integration/context-menu-grid.test.js
When triggering the context menu for a focused grid cell, Firefox seems to provide coordinates for the top left corner of the table body. So the menu opens further up the more you scroll down. Chrome does not have this issue and always opens the context menu in the center of the element.
This change adds custom logic for positioning the context menu when it is triggered by keyboard for Firefox specifically, so that it uses the bottom left coordinate of the closest element relating to the context menu event.
https://github.com/user-attachments/assets/6b16b5d2-ccf2-4aee-bc45-7cc10f498ad0
Fixes https://github.com/vaadin/flow-components/issues/7153
- Bugfix
=> fix: improve context menu positioning when opening menu with keyboard

dev/master-detail-layout.html, packages/master-detail-layout/README.md, packages/master-detail-layout/package.json, packages/master-detail-layout/src/vaadin-master-detail-layout.d.ts, packages/master-detail-layout/src/vaadin-master-detail-layout.js, packages/master-detail-layout/test/dom/__snapshots__/master-detail-layout.test.snap.js, packages/master-detail-layout/test/dom/master-detail-layout.test.js, packages/master-detail-layout/test/master-detail-layout.test.js, packages/master-detail-layout/test/typings/master-detail-layout.types.ts, packages/master-detail-layout/theme/lumo/vaadin-master-detail-layout.js, packages/master-detail-layout/theme/material/vaadin-master-detail-layout.js, packages/master-detail-layout/vaadin-master-detail-layout.d.ts, packages/master-detail-layout/vaadin-master-detail-layout.js
Added initial structure of the `@vaadin/master-detail-layout` package (folders, basic DOM with 2 slots, basic tests).
- Feature
=> feat: initialize master-detail-layout package

packages/form-layout/src/vaadin-form-layout-mixin.d.ts, packages/form-layout/src/vaadin-form-layout-mixin.js, packages/form-layout/src/vaadin-form-layout.d.ts, packages/form-layout/src/vaadin-form-layout.js, packages/form-layout/test/dom/__snapshots__/form-layout.test.snap.js, packages/form-layout/test/dom/form-layout.test.js
Adds support for the `defaultAutoResponsiveFormLayout ` feature flag to allow developers to enable the auto-responsive mode for all form layouts by default.
Part of https://github.com/vaadin/flow-components/issues/7164
=> feat(FormLayout): add support for defaultAutoResponsiveFormLayout feature flag

dev/master-detail-layout.html, packages/master-detail-layout/src/vaadin-master-detail-layout.d.ts, packages/master-detail-layout/src/vaadin-master-detail-layout.js, packages/master-detail-layout/test/helpers/detail-content.js, packages/master-detail-layout/test/helpers/master-content.js, packages/master-detail-layout/test/master-detail-layout.test.js, packages/master-detail-layout/test/typings/master-detail-layout.types.ts
Implenented APIs for setting the size of the two areas:
- `masterSize` / `detailSize` - sets a fixed size and disables flex-grow
- ~~`masterMinSize` / `detailMinSize` - will be used later to detect overlay mode~~ - will be added in the follow-up PR #8789
- Feature
=> feat: add masterSize and detailSize properties to master-detail-layout

packages/context-menu/src/vaadin-context-menu-mixin.js, packages/context-menu/test/overlay.test.js
The PR fixes an issue where adding a `<vaadin-context-menu>` dynamically to the DOM removed the text cursor from a focused HTML input, stopping the user from typing further. 
The problem was caused by `document.getSelection().removeAllRanges()`, which was called not only when the overlay opened or closed but also when the component was just added to the DOM.
Fixes #8780
=> fix: avoid removing selected ranges on component initialization

packages/app-layout/src/vaadin-app-layout-mixin.d.ts, packages/avatar-group/src/vaadin-avatar-group-mixin.d.ts, packages/avatar/src/vaadin-avatar-mixin.d.ts, packages/component-base/src/i18n-mixin.d.ts, packages/crud/src/vaadin-crud-mixin.d.ts, packages/dashboard/src/vaadin-dashboard.d.ts, packages/date-picker/src/vaadin-date-picker-mixin.d.ts, packages/login/src/vaadin-login-mixin.d.ts
Removes usage of the `PartialI18n` type helper and instead update I18N types manually to be deep partial. Also changes the types back to use an interface to align with the remaining I18N types that haven't been updated so far.
Fixes https://github.com/vaadin/web-components/issues/8792
- Bugfix
=> fix: properly handle functions in partial I18N types

packages/popover/src/vaadin-popover-overlay.js, packages/popover/test/trigger.test.js
The PR fixes the issue where focus-triggered modal popovers didn't close on backdrop click. 
The issue was caused by the `_shouldCloseOnOutsideClick` override in `PopoverOverlay`.  This override was originally added (according to the code comment) to prevent modal popovers from unexpected closing after receiving focus. However, this behavior doesn't actually happen without the override, while the related test seems artificial – it asserts that the second click on the target doesn't close the popover, which doesn't make practical sense since `pointer-events: none` prevents interacting with the target when the popover is open anyway. So, the override seems safe to be removed.
Fixes https://github.com/vaadin/web-components/issues/8784
=> fix: do not prevent closing on backdrop click

packages/popover/src/vaadin-popover.js, packages/popover/test/timers.test.js
Fixes https://github.com/vaadin/flow-components/issues/7085
Here's the original problem with the current incorrect logic:
1. Popover has both `hoverDelay` and `hideDelay` set to e.g. 500ms (default),
2. User moves mouse quickly over the target -> hover delay schedules opening -> hide delay schedules closing,
3. User moves mouse over the target again -> overlay is opened due to the `__closeTimeout` check below.
https://github.com/vaadin/web-components/blob/b839b64a8a5aeb9e6b5d0f110a4d0e465bb13f3a/packages/popover/src/vaadin-popover.js#L74
This check was added as part of "abort closing on overlay mouseenter" covering by the following test:
https://github.com/vaadin/web-components/blob/b839b64a8a5aeb9e6b5d0f110a4d0e465bb13f3a/packages/popover/test/timers.test.js#L227
IMO the current logic is …
=> fix: close popover immediately on mouseleave while opening

packages/component-base/src/i18n-mixin.js
Vaadin React components currently detect which properties are available on a custom element by [using Polymer property declarations](https://github.com/vaadin/react-components/blob/44d700a681869a02cb145a60cf81f179a340222b/packages/react-components/src/utils/createComponent.ts#L92-L105). Since the `i18n` property is not declared as a Polymer property it is not recognized by the React component as a property and is treated as an attribute instead.
Providing a Polymer property should solve the issue and also doesn't seem to interfere with the custom `i18n` getter and setter.
- Bugfix
=> fix: provide i18n property declaration

dev/master-detail-layout.html, packages/master-detail-layout/src/vaadin-master-detail-layout.d.ts, packages/master-detail-layout/src/vaadin-master-detail-layout.js, packages/master-detail-layout/test/helpers/master-content.js, packages/master-detail-layout/test/master-detail-layout.test.js, packages/master-detail-layout/test/typings/master-detail-layout.types.ts
Fixes #8808
Added `orientation` property that can be set to `vertical` to use vertical orientation.
Note: I was unable to make enforcing the overlay mode work using `masterSize = '100%'` so I documented that `100vh` can be used instead. This probably makes sense for common cases where MDL is expected to take the full page height.
- Feature
=> feat: add vertical orientation support to master-detail-layout

dev/master-detail-layout.html, packages/master-detail-layout/src/vaadin-master-detail-layout.d.ts, packages/master-detail-layout/src/vaadin-master-detail-layout.js, packages/master-detail-layout/test/master-detail-layout.test.js, packages/master-detail-layout/test/typings/master-detail-layout.types.ts
As discussed, let's add a property to allow enforcing overlay mode on the MDL.
- Feature
=> feat: add forceOverlay property to master-detail-layout

dev/master-detail-layout.html, packages/master-detail-layout/src/vaadin-master-detail-layout.d.ts, packages/master-detail-layout/src/vaadin-master-detail-layout.js, packages/master-detail-layout/test/master-detail-layout.test.js
Adds a `containment` property that controls whether the overlay should be confined to the layout, or the browser's viewport.
Closes https://github.com/vaadin/web-components/issues/8809
- Feature
=> feat: add containment mode to master-detail-layout

packages/dialog/src/vaadin-dialog-overlay-mixin.js, packages/dialog/src/vaadin-dialog-resizable-mixin.js, packages/dialog/test/draggable-resizable.test.js
Fixes #8790
Follow-up to #8722
Looks like we only need to apply `has-bounds-set` on resize, as pointed out by the issue creator. This PR does that.
Note: we could rename attribute as it's now set outside of `setBounds()` method but maybe it's ok to keep it as is.
- Bugfix
=> fix: only set has-bounds-set attribute on dialog resize

packages/menu-bar/src/vaadin-menu-bar-mixin.js, packages/menu-bar/test/menu-bar.test.js, packages/menu-bar/test/overflow.test.js, packages/menu-bar/test/sub-menu.test.js
Fixes #8827
Note: this needs some manual testing with the Flow counterpart. In theory this shouldn't be a breaking change but it can be considered as "behavior altering" - for example, I had to update a few tests using `button.firstChild` since there are now comment nodes created by Lit, and this could potentially affect some users who do the same in tests.
- Refactor
=> refactor: use Lit for rendering menu-bar buttons

packages/side-nav/src/vaadin-side-nav-children-mixin.d.ts, packages/side-nav/src/vaadin-side-nav-children-mixin.js, packages/side-nav/src/vaadin-side-nav-item.js, packages/side-nav/test/typings/side-nav.types.ts
Adds support for partial I18N objects to side nav. This allows setting an I18N object that only overrides some of the translations and uses default translations as fallback.
- Feature
=> feat: support partial i18n in side nav

packages/rich-text-editor/src/vaadin-lit-rich-text-editor.js, packages/rich-text-editor/src/vaadin-rich-text-editor-mixin.d.ts, packages/rich-text-editor/src/vaadin-rich-text-editor-mixin.js, packages/rich-text-editor/src/vaadin-rich-text-editor.js, packages/rich-text-editor/test/typings/rich-text-editor.types.ts
Adds support for partial I18N objects to rich text editor. This allows setting an I18N object that only overrides some of the translations and uses default translations as fallback.
- Feature
=> feat: support partial i18n in rich text editor

packages/message-input/src/vaadin-message-input-mixin.d.ts, packages/message-input/src/vaadin-message-input-mixin.js, packages/message-input/test/message-input.test.js, packages/message-input/test/typings/message-input.types.ts
Adds support for partial I18N objects to message input. This allows setting an I18N object that only overrides some of the translations and uses default translations as fallback.
- Feature
=> feat: support partial i18n in message input

packages/menu-bar/src/vaadin-menu-bar-mixin.d.ts, packages/menu-bar/src/vaadin-menu-bar-mixin.js, packages/menu-bar/test/typings/menu-bar.types.ts
Adds support for partial I18N objects to menu bar. This allows setting an I18N object that only overrides some of the translations and uses default translations as fallback.
- Feature
=> feat: support partial i18n in menu bar

dev/master-detail-layout.html, packages/master-detail-layout/src/vaadin-master-detail-layout.d.ts, packages/master-detail-layout/src/vaadin-master-detail-layout.js, packages/master-detail-layout/test/master-detail-layout.test.js, packages/master-detail-layout/test/typings/master-detail-layout.types.ts
Fixes #8804
Added `stachThreshold` property to control at which point the layout should switch to the stack mode.
- Feature
=> feat: add stackThreshold property to master-detail-layout

packages/grid/src/vaadin-grid-selection-column-base-mixin.js, packages/grid/test/selection.test.js
The PR fixes an issue where the `_shiftKeyDown` property was wrongly reset to `false` when pressing <kbd>Shift</kbd> between `mousedown` and `mouseup` events.
Fixes https://github.com/vaadin/web-components/issues/8801
=> fix: set shiftKey correctly on mousedown + Shift + mouseup

packages/master-detail-layout/package.json, packages/master-detail-layout/src/vaadin-master-detail-layout.js, packages/master-detail-layout/test/master-detail-layout.test.js, packages/master-detail-layout/test/overlay-mode.test.js
Implemented the following behavior according to PRD:
> In Stack and Overlay modes, keyboard focus automatically moves to the detail area when it is displayed.
- Feature
=> feat: focus detail content when using overlay or stack mode

dev/master-detail-layout.html, packages/master-detail-layout/src/vaadin-master-detail-layout-transition-styles.js, packages/master-detail-layout/src/vaadin-master-detail-layout.d.ts, packages/master-detail-layout/src/vaadin-master-detail-layout.js, packages/master-detail-layout/test/view-transitions.test.js
Adds a `setDetail` method for imperatively updating the detail content, and wrapping that update in a view transition if the browser supports it. During the transition a `transition` attribute is added that can be used for targeting specific types of transitions with CSS selectors. Also adds some initial animations that should be refined as a follow-up.
Part of https://github.com/vaadin/web-components/issues/8812
- Feature
=> feat: add method for starting view transitions

packages/master-detail-layout/src/vaadin-master-detail-layout.d.ts, packages/master-detail-layout/src/vaadin-master-detail-layout.js
Fixes #8810
Added tables of stylable parts and state attributes, including `orientation` and `containment`. 
Note: `has-master-size` etc could be documented as well but IMO those are rather internal.
=> docs: add master-detail-layout part names and attributes JSDoc

packages/grid/src/vaadin-grid-data-provider-mixin.js, packages/grid/test/scroll-to-index.test.js
This fixes an issue where calling `scrollToIndex` before the column tree was available had no effect, since the call wasn't deferred.
Fixes https://github.com/vaadin/flow-components/issues/6711
=> fix: defer scrollToIndex calls until columnTree is available

packages/master-detail-layout/src/vaadin-master-detail-layout.d.ts, packages/master-detail-layout/src/vaadin-master-detail-layout.js, packages/master-detail-layout/test/typings/master-detail-layout.types.ts, packages/master-detail-layout/test/view-transitions.test.js
Added `noAnimation` property which prevents calling `startViewTransition()`.
The name can be discussed, the only similar case we have is `no-anim` attribute used internally by `vaadin-app-layout`.
- Feature
=> feat: add noAnimation property to master-detail-layout

packages/card/src/vaadin-card.js
When adding `inline-flex` elements like Vaadin icons in `media` slot, Firefox and Chrome works differently. As stated in the [comment](https://github.com/vaadin/web-components/issues/8641#issuecomment-2636327402) in the issue, the aspect ratio can break in Firefox. This PR adds `overflow: hidden` on icons for `stretch-media` and `cover-media`. This does not cause any changes for Chrome, but fixes the issue for Firefox.
Fixes #8641
=> fix: use overflow hidden on icons for stretch and cover media

packages/app-layout/src/vaadin-app-layout.d.ts, packages/app-layout/src/vaadin-app-layout.js
It turns out `backdrop` part is not listed in stylable parts docs for `vaadin-app-layout`. This PR fixes that.
=> docs: add backdrop to the list of app-layout shadow parts

packages/master-detail-layout/src/vaadin-master-detail-layout-transition-styles.js
Part of https://github.com/vaadin/web-components/issues/8811
Added separate view transitions for MDL using `dir="rtl"` which uses opposite `translateX` property values.
- Feature
=> feat: add RTL support to master-detail-layout transitions

packages/vaadin-lumo-styles/mixins/required-field.js
The `calc(var(--lumo-border-radius-m) / 4)` calculation can produce a fractional value, which causes an overflow when used as the value of `margin-left`:
https://github.com/user-attachments/assets/30119584-acfc-4c9e-8eb7-e77c6fefa443
The PR replaces `margin-left` with `padding-left`, which prevents the overflow.
=> fix: use padding instead of margin to avoid overflow

packages/master-detail-layout/src/vaadin-master-detail-layout.js, packages/master-detail-layout/test/view-transitions.test.js
Adds APIs to `vaadin-master-detail-layout` to allow wrapping potentially asynchronous DOM updates in a view transition. The main purpose for now is to enable the React component to start a transition, then update the DOM asynchronously, and then resolve the update callback of the transition once the DOM is updated.
Part of https://github.com/vaadin/web-components/issues/8812
- Refactor
=> refactor: add APIs for starting view transition manually

dev/master-detail-layout.html, packages/master-detail-layout/src/vaadin-master-detail-layout.d.ts, packages/master-detail-layout/src/vaadin-master-detail-layout.js, packages/master-detail-layout/test/view-transitions.test.js
Make the `_setDetail` method in `vaadin-master-detail-layout` protected for now. We mainly need it to facilitate view transitions in the Flow component, and it's probably not going to be useful for other rendering libraries.
- Refactor
=> refactor: make setDetail protected

packages/form-layout/src/vaadin-form-item-mixin.js, packages/form-layout/test/form-item.test.js
Currently, FormItem synchronizes the `invalid` attribute only when the field is marked as `required`. However, this behavior seems incorrect, as required is not the only case where users may want to apply styles based on the invalid state. The current implementation also conflicts with server-side validation, as it sets the invalid state based on the result of the client-side `checkValidity()` method. This doesn't work in the Flow component, where the invalid state is managed by the server. 
This PR refactors FormItem to synchronize the `invalid` attribute based exclusively on the presence of the `invalid` attribute on the field, without calling `checkValidity()` and regardless of the required state.
Fixes https://github.com/vaadin/flow-components/issues/7246
=> fix: always synchronize invalid attribute regardless of required

packages/master-detail-layout/src/vaadin-master-detail-layout-transition-styles.js
The current transition styles apply the `vaadin-master-detail-layout` view transition name to all layouts. This breaks if there is more than one layout, as view transition names must only applied to a single element:
```
Unexpected duplicate view-transition-name: vaadin-master-detail-layout
```
This applies the transition name only to the layout that started the transition. Also fixes a CSS rule that was not properly closed.
- Bugfix
=> fix: apply view transition name only to layout that started transition

packages/master-detail-layout/src/vaadin-master-detail-layout.d.ts, packages/master-detail-layout/src/vaadin-master-detail-layout.js, packages/master-detail-layout/test/view-transitions.test.js
Allow skipping view transitions when using the `_setDetail` method. Can be used by the Flow component to not use a view transition if details are set when the component is first attached.
Prerequisite for https://github.com/vaadin/flow-components/pull/7267
- Refactor
=> refactor: add parameter to skip view transitions

packages/card/src/vaadin-card.js
Based on https://github.com/vaadin/flow-components/pull/7225#discussion_r2020491069 this was a leftover, so let's remove `notify: true` since it breaks React components release.
- Bugfix
=> fix: remove notify: true from cardTitle property

packages/master-detail-layout/src/vaadin-master-detail-layout.js
Fixes #8898
Added `z-index` similar to the that `vaadin-app-layout` uses in its overlay mode.
- Bugfix
=> fix: set z-index on backdrop and detail parts in overlay mode

packages/grid/theme/lumo/vaadin-grid-tree-toggle-styles.js
The grid tree toggle component has a `connectors` theme that was introduced sometime before V10. It's very unlikely that anyone is using it, so let's remove it.
=> refactor: remove obsolete `connectors` theme

packages/component-base/src/virtualizer-iron-list-adapter.js, packages/component-base/src/virtualizer.js, packages/component-base/test/virtualizer.test.js, packages/grid/src/vaadin-grid-mixin.js, packages/grid/test/basic.test.js, packages/virtual-list/src/vaadin-virtual-list-mixin.js, packages/virtual-list/test/virtual-list.test.js
Fixes #8630 
This fixes the case from https://github.com/vaadin/web-components/issues/8630#issuecomment-2636265294 based on the previous idea from https://github.com/vaadin/web-components/commit/324e4ad1534fb6dcf50650ca92b96de283c2d9df
The original fix that landed in #8642 only coverer case of "hiding -> moving -> showing" the virtualizer scroll target.
However, it won't work if the component is moved without changing visibility (e.g. attached to overlay after it fully opens).
- Bugfix
=> fix: add hostConnected to virtualizer, use it in virtual-list and grid

packages/master-detail-layout/src/vaadin-master-detail-layout-transition-styles.js
Adds dedicated transitions for when the layout is in stack mode and uses viewport containment. In that case whatever is "below" the details does not move, and the animation is not clipped at the layout borders.
- Feature
=> feat: add transitions for stack mode and viewport containment

packages/master-detail-layout/src/vaadin-master-detail-layout.js, packages/master-detail-layout/test/aria.test.js
When `forceOverlay` was set to `true`, the `inert` attribute would always be set on the master part making it inaccessible even when there was no detail element in the layout.
=> fix: don't apply `inert` on master if there is no detail

packages/component-base/src/virtualizer-iron-list-adapter.js, packages/component-base/src/virtualizer.js, packages/component-base/test/virtualizer.test.js, packages/grid/src/vaadin-grid-mixin.js, packages/grid/test/basic.test.js, packages/virtual-list/src/vaadin-virtual-list-mixin.js, packages/virtual-list/test/virtual-list.test.js
Cherry-pick of #8896 to `24.6` branch.
There was a merge conflict due to `this.recalculateColumnWidths();` present in `GridMixin` in `connectedCallback()`.
Also added checks in order to not fail in Lit version (since in 24.6 we don't use sync initial rendering and therefore the virtualizer might not yet be available). This is not a problem in 24.7 and latest version so the check isn't needed there.
- Cherry-pick
=> fix: add hostConnected to virtualizer, use it in virtual-list and grid (CP: 24.6)

packages/upload/src/vaadin-upload-mixin.d.ts, packages/upload/src/vaadin-upload-mixin.js, packages/upload/test/i18n.test.js, packages/upload/test/typings/upload.types.ts
Adds support for partial I18N objects to upload. This allows setting an I18N object that only overrides some of the translations and uses default translations as fallback.
- Feature
=> feat: support partial i18n in upload

packages/component-base/src/i18n-mixin.js, packages/component-base/test/i18n-mixin.test.js
React components seem to set the same element property in every render cycle regardless whether the reference has changed. The `i18n` property currently doesn't handle that properly and regenerates `__effectiveI18n` again, triggering the next render cycle, and potentially starting an infinite loop.
This fixes the issue by checking the custom I18N reference before regenerating `__effectiveI18n`.
Fixes https://github.com/vaadin/web-components/issues/8869
- Bugfix
=> fix: do not generate effective i18n if custom i18n reference didn't chance

packages/component-base/src/style-props.js
Add the file where base style properties are added. Includes one property which is intended to be used for all surfaces where components are displayed (page, overlays, dialogs, etc).
=> feat: add `component-base/style-props.js`

dev/master-detail-layout.html, packages/master-detail-layout/README.md, packages/master-detail-layout/src/vaadin-master-detail-layout.js, packages/master-detail-layout/test/aria.test.js, packages/master-detail-layout/test/dom/master-detail-layout.test.js, packages/master-detail-layout/test/master-detail-layout.test.js, packages/master-detail-layout/test/overlay-mode.test.js, packages/master-detail-layout/test/stack-mode.test.js, packages/master-detail-layout/test/view-transitions.test.js, packages/master-detail-layout/test/visual/lumo/master-detail-layout.test.js, packages/master-detail-layout/test/visual/material/master-detail-layout.test.js
Marks the Master Detail Layout as experimental so that it needs to be enabled with a feature flag.
Corresponding Flow PR: https://github.com/vaadin/flow/pull/21239
- Feature
=> feat: mark master detail layout as experimental

packages/dashboard/src/vaadin-dashboard-helpers.js, packages/dashboard/src/vaadin-dashboard-section.js, packages/dashboard/src/vaadin-dashboard-widget.js, packages/dashboard/src/vaadin-dashboard.d.ts, packages/dashboard/src/vaadin-dashboard.js, packages/dashboard/test/dashboard-widget.test.ts, packages/dashboard/test/dashboard.test.ts
This PR makes the heading level for the dashboard sections and widgets customizable by adding a property `rootHeadingLevel` to `Dashboard`.
- The defaults are unchanged. 
- The titles are now rendered as `div`s instead of `h2` and `h3`. Instead, the level is applied using the `aria-level` attribute on the title element.
Part of #8779
=> feat: make root heading level on dashboard customizable

dev/button.html, dev/common.js, packages/button/src/vaadin-button-base.js, packages/component-base/src/style-props.js, packages/icon/src/vaadin-icon-styles.js
| Property | Description
| --- | ---
| `--_vaadin-background-container` | Background color for components that contain text (like a button).
| `--_vaadin-background-container-strong` | A stronger background color for components that contain text.
| `--_vaadin-border-color` | Color for decorative borders.
| `--_vaadin-border-color-strong` | Color for identifiable borders (at least 3:1 contrast).
| `--_vaadin-color-subtle` | Color for decorative/disabled text (at least 3:1 contrast).
| `--_vaadin-color` | Color for text content (at least 4.5:1 contrast).
| `--_vaadin-color-strong` | Color for text with strong contrast requirements (at least 7:1).
| `--_vaadin-padding` | Padding for component containers. Applies a uniform padding on all sides.
| `--_vaadin-padding-container` | Padding for …
=> refactor!: Button base styles

packages/form-layout/src/layouts/responsive-steps-layout.js, packages/form-layout/test/dom/__snapshots__/form-layout.test.snap.js, packages/form-layout/test/dom/form-layout.test.js, packages/form-layout/test/form-layout.test.js
This change ensures that styles applied by _responsive steps_ mode are properly removed when switching to _auto-responsive_ mode in order to avoid unintended side effects. This is specifically important in React wrappers. They use `@lit/react` which applies web component properties and attributes after the component has already connected to the DOM. As a result, there is a short window during which responsive steps styles can be applied.
An alternative solution could be to delay the initialization of responsive steps styles, but this causes some tests to fail, so I think it's safer to leave it as is for now even though it may be less optimal from the performance perspective.
Related to https://github.com/vaadin/platform/issues/7172
=> fix: remove responsive step styles when switching to auto-responsive

packages/upload/src/vaadin-upload-mixin.js, packages/upload/test/adding-files.test.js
In some cases, `webkitGetAsEntry` can return `null` for `dataTransfer` items. Before the [folder drop feature](https://github.com/vaadin/web-components/pull/8032), the files were directly accessed through `dataTransfer.files`.
This PR checks if the items contain any folders, and if not, falls back to the original logic of `dataTransfer.files`. When there are no folders, there is no reason to check for `webkitGetAsEntry`. Also, currently there are no alternatives to `webkitGetAsEntry` which is widely supported.
Fixes:
- Dragging inline files from Outlook new on Windows
Does not fix (does not work in any component):
- Attachment&inline dragging from Thunderbird on MacOS 
- Dragging attachment files from Outlook new on Windows (only works when dropped on Windows explorer)
- Dragging inline …
=> fix: use data transfer files if items contain no folders

packages/dashboard/theme/lumo/vaadin-dashboard.js, packages/dashboard/theme/material/vaadin-dashboard.js
Platform validation for `24.8.0-alpha9` currently fails with this error:
> [pool-1-thread-1] WARN com.vaadin.platform.test.ChromeComponentsIT - This message in browser log console may be a potential error: '[2025-04-09T10:59:47.072Z] [WARNING] http://172.16.1.174:8080/prod-mode/VAADIN/build/indexhtml-D0Ob28c6.js 8122:18 "The custom element definition for \"vaadin-dashboard-section\" was finalized before a style module was registered. Ideally, import component specific style modules before importing the corresponding custom element. This warning can be suppressed by setting \"window.Vaadin.suppressPostFinalizeStylesWarning = true\"."'
That seems to be a regression from https://github.com/vaadin/web-components/pull/8885, which adds an import from `src/vaadin-dashboard-widget.js` to …
=> fix: dashboard theme import order

packages/upload/src/vaadin-upload-mixin.js, packages/upload/test/adding-files.test.js
Cherry-pick of https://github.com/vaadin/web-components/pull/8918 to v24.6.
=> fix: use data transfer files if items contain no folders (#8918) (CP: 24.6)

packages/upload/src/vaadin-upload-mixin.js, packages/upload/test/adding-files.test.js
Cherry-pick of https://github.com/vaadin/web-components/pull/8918 to v24.7.
=> fix: use data transfer files if items contain no folders (#8918) (CP: 24.7)

packages/form-layout/test/dom/__snapshots__/form-layout.test.snap.js
Fixes a snapshot introduced in https://github.com/vaadin/web-components/pull/8860 that for some reason doesn't match expectations:
```
❌ vaadin-form-layout > responsive-steps > host > switching to autoResponsive
AssertionError: Snapshot vaadin-form-layout responsive-steps host switching to autoResponsive does not match the saved snapshot on disk
<vaadin-form-layout
auto-responsive=""
-  style="--_max-columns: 1;"
+  style="--_column-width: 13em; --_max-columns: 1;"
>
```
=> test: update form layout snapshots

dev/common.js, dev/text-field.html, packages/button/src/vaadin-button-base.js, packages/component-base/src/style-props.js, packages/field-base/src/styles/clear-button-styles.js, packages/field-base/src/styles/field-shared-styles.js, packages/field-base/src/styles/input-field-container-styles.js, packages/input-container/src/vaadin-input-container-styles.js
| Property | Description
| --- | ---
| `--_vaadin-gap-container-inline` | Renamed from `--_vaadin-gap-container`. Inline gap between textual elements inside a component that contains mainly text and icons.
| `--_vaadin-gap-container-block` | Vertical gap between text elements inside a component that contains textual elements and other containers.
| `--_vaadin-icon-cross` | Data URL for an SVG icon of a cross. Used for the clear button inside the text field.
| `--_vaadin-icon-warn` | Data URL for an SVG icon of a warning sign. Used for the field error message.
Most of these should be self explanatory (and most are pre-existing from V24).
| Property | Description
| --- | ---
| `--vaadin-input-field-container-gap` | The gap between the field label, input field, helper, and error message …
=> refactor!: Base text field styles

packages/board/test/basic.test.js, packages/board/test/board-cols.test.js, packages/board/test/board-row.test.js, packages/board/test/light-dom.test.js, packages/board/test/redraw.test.js, packages/board/test/size.test.js
Part of https://github.com/vaadin/platform/issues/7453
=> test: import unstyled board component in unit tests

packages/tabs/test/scroll.test.js, packages/tabs/test/tabs-test-styles.js, packages/tabs/test/tabs.test.js
Updated `vaadin-tabs` styles to use `src` version and added a subset of Lumo to make sure unit tests pass.
- Test
=> test: refactor tabs unit tests to not use Lumo entrypoints

packages/combo-box/test/aria.test.js, packages/combo-box/test/basic.test.js, packages/combo-box/test/combo-box-light-validation.test.js, packages/combo-box/test/combo-box-light.test.js, packages/combo-box/test/data-provider-dynamic-size.test.js, packages/combo-box/test/data-provider-filtering.test.js, packages/combo-box/test/data-provider.test.js, packages/combo-box/test/events.test.js, packages/combo-box/test/external-filtering.test.js, packages/combo-box/test/interactions.test.js, packages/combo-box/test/internal-filtering.test.js, packages/combo-box/test/item-class-name-generator.test.js, packages/combo-box/test/item-renderer.test.js, packages/combo-box/test/keyboard.test.js, packages/combo-box/test/lit-renderer-directives.test.js, packages/combo-box/test/lit.test.js, packages/combo-box/test/object-values.test.js, packages/combo-box/test/overlay-opening.test.js, packages/combo-box/test/overlay-position.test.js, packages/combo-box/test/selecting-items.test.js, packages/combo-box/test/validation.test.js
Part of https://github.com/vaadin/platform/issues/7453
=> test: import unstyled combo-box component in unit tests

packages/app-layout/test/app-layout.test.js, packages/app-layout/test/drawer-toggle.test.js, packages/app-layout/test/keyboard-desktop.test.js, packages/app-layout/test/keyboard-mobile.test.js
Part of https://github.com/vaadin/platform/issues/7453
=> test: import unstyled app-layout component in unit tests

packages/charts/test/chart-element.test.js, packages/charts/test/chart-properties.test.js, packages/charts/test/chart-series.test.js, packages/charts/test/dom-repeat.test.js, packages/charts/test/events.test.js, packages/charts/test/exporting.test.js, packages/charts/test/private-api.test.js, packages/charts/test/reattach.test.js, packages/charts/test/styling.test.js, packages/charts/test/turbo-mode.test.js
Part of https://github.com/vaadin/platform/issues/7453
=> test: import unstyled chart component in unit tests

packages/select/test/accessibility.test.js, packages/select/test/renderer.test.js, packages/select/test/select-test-styles.test.js, packages/select/test/select.test.js, packages/select/test/validation.test.js
Updated `vaadin-select` tests to use `src` version of item and list-box, added item styles to make overlay width tests pass.
- Test
=> test: refactor select unit tests to not use Lumo entrypoints

packages/date-picker/test/basic.test.js, packages/date-picker/test/custom-input.test.js, packages/date-picker/test/dropdown.test.js, packages/date-picker/test/events.test.js, packages/date-picker/test/fullscreen.test.js, packages/date-picker/test/helpers.js, packages/date-picker/test/keyboard-input.test.js, packages/date-picker/test/keyboard-navigation.test.js, packages/date-picker/test/overlay-content.test.js, packages/date-picker/test/theme-propagation.test.js, packages/date-picker/test/validation.test.js, packages/date-picker/test/value-commit.test.js, packages/date-time-picker/test/validation.test.js, packages/field-highlighter/test/field-components.test.js, test/integration/dialog-date-picker.test.js, test/integration/grid-pro-custom-editor.test.js
- Renamed `waitForScrollToFinish` to `untilOverlayScrolled`
- Renamed `waitOverlayRender` to `untilOverlayRendered`
- Ensured that the ignoreTaps debouncer is flushed at the end of `untilOverlayScrolled` to prevent potential test failures due to 300ms delay before tap events are allowed again.
Related to https://github.com/vaadin/platform/issues/7453
=> test: flush ignoreTaps debouncer after scroll

.eslintrc.json, packages/grid-pro/src/vaadin-grid-pro-edit-select-mixin.js, packages/grid/src/vaadin-grid-column-auto-width-mixin.js, packages/grid/src/vaadin-grid-helpers.js
ES2020–2021 operators must be banned only in component files, as only those are passed to Polymer analyzer:
```
polymer analyze packages/**/vaadin-*.js > analysis.json
```
=> chore: ban ES2020-2021 operators only in component files

packages/master-detail-layout/src/vaadin-master-detail-layout.js
Also set `z-index` on the details part in stack mode, so that it covers the app layout navbar when using viewport containment.
Fixes https://github.com/vaadin/web-components/issues/8960
- Bugfix
=> fix: set z-index on details part in stack mode

packages/dialog/test/draggable-resizable.test.js, packages/dialog/test/header-footer.test.js, packages/dialog/test/renderer.test.js
Part of https://github.com/vaadin/platform/issues/7456
=> test: import unstyled dialog component in unit tests

DEVELOPMENT.md
Since Lit tests are now auto-generated and renamed, the `--glob` argument examples need to be updated accordingly
=> chore: update --glob arg examples in DEVELOPMENT.md

packages/avatar-group/package.json, packages/avatar-group/src/vaadin-avatar-group.js, packages/avatar-group/src/vaadin-lit-avatar-group.js, packages/avatar-group/test/avatar-group-test-styles.js, packages/avatar-group/test/avatar-group.test.js, packages/avatar-group/test/dom/__snapshots__/avatar-group.test.snap.js, packages/avatar/src/vaadin-avatar.js, packages/avatar/src/vaadin-lit-avatar.js, packages/avatar/test/avatar.test.js
Part of https://github.com/vaadin/platform/issues/7456
=> test: import unstyled avatar-group component in unit tests

packages/grid/test/column-groups.test.js, packages/grid/test/deprecated-api.test.js, packages/grid/test/drag-and-drop.test.js, packages/grid/test/dynamic-item-size.test.js, packages/grid/test/frozen-columns.test.js, packages/grid/test/grid-test-styles.js, packages/grid/test/hidden-grid.test.js, packages/grid/test/keyboard-navigation-cell-button.test.js, packages/grid/test/lit-renderer-directives.test.js, packages/grid/test/min-height.test.js, packages/grid/test/physical-count.test.js, packages/grid/test/renderers.test.js, packages/grid/test/row-details.test.js, packages/grid/test/row-height.test.js, packages/grid/test/scroll-into-view.test.js, packages/grid/test/scroll-restoration.test.js, packages/grid/test/scrolling-mode.test.js, packages/grid/test/selection-column-lazy-import.test.js, packages/grid/test/styling.test.js
Part of https://github.com/vaadin/platform/issues/7456
=> test: import unstyled grid component in unit tests

packages/multi-select-combo-box/test/basic.test.js, packages/multi-select-combo-box/test/multi-select-combo-box-test-styles.js
There was one test file that I missed to update to `src` version. Also needed to add item styles using `min-height` as without any defined size virtualizer would set `200` as a placeholder height and then end up with 3 items rendered instead of 4.
- Test
=> test: update remaining multi-select-combo-box test to use src

packages/crud/test/crud-editor.test.js
Follow-up to #8980
Trying to fix the following error:
```
❌ crud editor > default form > should move default form when editorPosition changes from bottom to default
Error: Error: The trap node should have at least one focusable descendant or be focusable itself. (http://localhost:8000/packages/a11y-base/src/focus-trap-controller.js:84)
```
- Test
=> test: try to prevent focus-trap errors in crud-editor test

packages/a11y-base/src/keyboard-direction-mixin.js, packages/a11y-base/test/keyboard-direction-mixin.test.js, packages/menu-bar/src/vaadin-menu-bar-mixin.js
Currently, `vaadin-menu-bar` has some special logic in `tabNavigation` mode for switching submenu (so that e.g. pressing <kbd>Tab</kbd> on the submenu item focuses the next root level button and opens its submenu, if any).
This isn't very clean since it basically copies some of `KeyboardDirectionMixin` logic for Arrow Left / Arrow Right.
Updated logic to integrate "Tab navigation" into the mixin so that switching submenu can be handled by existing logic:
https://github.com/vaadin/web-components/blob/f903c63170fc3855c721c03fc79ac0798cb24d0b/packages/menu-bar/src/vaadin-menu-bar-mixin.js#L739-L740
- Refactor
=> refactor: simplify menu-bar Tab navigation submenu logic

packages/context-menu/src/vaadin-contextmenu-items-mixin.js, packages/menu-bar/src/vaadin-menu-bar-mixin.js, packages/menu-bar/test/dom/__snapshots__/menu-bar.test.snap.js, packages/menu-bar/test/sub-menu.test.js
Depends on #8908 (this is an independent change but some Tab navigation tests would fail until that PR is merged).
Wrapping opening submenu event with `requestAnimationFrame()` was added in https://github.com/vaadin/vaadin-menu-bar/pull/12. It seems unnecessary since there is no need to delay opening overlay (the very first revision at https://github.com/vaadin/vaadin-menu-bar/pull/12/commits/3bdc2791a8d110546e423753468ef907dd979557 had an additional `before-open` event with some logic, but that was changed in a subsequent commit).
Tested this change with Flow components and it seems to make ITs more reliable in terms of timeouts.
- Refactor
=> refactor: update menu-bar submenu to open synchronously

packages/text-area/test/text-area.test.js
Since base styles added default `padding` to the `vaadin-input-container`, unit tests have to be updated accordingly.
Note: I disabled `border` in tests for simplicity (it was already disabled in a couple of existing tests).
We might want to improve these tests in the future and maybe extract to separate file in the future.
- Test
=> test: update multi-line text-area tests to pass with base styles

.github/workflows/visual-tests.yml, wtr-utils.js
- Disabled Lumo and Material visual tests for `base-styles` branch
- Updated to only run Base styles visual tests for packages that have them
- Tests
=> Disable Lumo and Material tests, fix Base visual tests

packages/date-picker/src/vaadin-date-picker-overlay-content-mixin.js, packages/date-picker/test/overlay-content.test.js
The observer removed in https://github.com/vaadin/web-components/pull/8928 caused lots of tests to fail. Let's restore it.
- Bugfix
=> fix: restore incorrectly removed observer, update tests

packages/confirm-dialog/test/confirm-dialog.test.js, packages/dialog/test/draggable-resizable.test.js
In the date-picker base styles PR https://github.com/vaadin/web-components/pull/8928 there were some overlay style changes:
- Changed from `inset: 0` to `inset: 8px`
- Added `1px` border on the overlay part
Updated some failing tests in dialog and confirm-dialog packages to pass with these changes.
- Test
=> fix: make dialog and confirm-dialog tests pass with base styles

dev/combo-box.html, packages/combo-box/src/vaadin-lit-combo-box-item.js, packages/combo-box/src/vaadin-lit-combo-box-overlay.js, packages/combo-box/src/vaadin-lit-combo-box-scroller.js, packages/combo-box/src/vaadin-lit-combo-box.js, packages/combo-box/test/basic.test.js, packages/combo-box/test/helpers.js, packages/component-base/src/style-props.js, packages/item/src/vaadin-item-styles.js, packages/multi-select-combo-box/test/chips.test.js, packages/vaadin-lumo-styles/style.js
| Property | Description |
| ------------- | ------------- |
| `--_vaadin-icon-checkmark` | Data URL for an SVG icon of a checkmark. Used to indicate the selected item. |
| `--_vaadin-icon-chevron-down` | Data URL for an SVG icon of a downward-pointing chevron. Used for combo box and select dropdown indicators. |
| Property | Description |
| -------- | ----------- |
| `--vaadin-combo-box-spinner-color` | The color of the loading spinner. |
| `--vaadin-combo-box-overlay-width` | The width of the item overlay. |
| `--vaadin-item-border-radius` | Item border radius. |
| `--vaadin-item-checkmark-color` | The color of the checkmark icon for a selected item. |
| `--vaadin-item-gap` | Space between the checkmark and content. |
| `--vaadin-item-height` | Item height. |
| …
=> refactor!: Base combo box styles

dev/select.html, dev/virtual-list.html, packages/item/src/vaadin-item-styles.js, packages/select/src/vaadin-lit-select-item.js, packages/select/src/vaadin-lit-select-list-box.js, packages/select/src/vaadin-lit-select-overlay.js, packages/select/src/vaadin-lit-select.js, packages/select/src/vaadin-select-value-button-styles.js
| Property | Description |
| -------- | ----------- |
| `--vaadin-divider-color` | Divider color (e.g., `<hr>`). |
| `--vaadin-item-border-radius` | Item border radius. |
| `--vaadin-item-gap` | Space between the checkmark and content. |
| `--vaadin-item-height` | Item height. |
| `--vaadin-item-overlay-padding` | Item container padding. |
| `--vaadin-item-padding` | Item padding. |
=> refactor!: Base select styles

package.json, yarn.lock
Upgraded Stylelint to include the [v0.36.0](https://github.com/known-css/known-css-properties/releases/tag/v0.36.0) of `known-css-properties` transitive dependency published last week.
This should allow using some modern / experimental CSS properties like `interpolate-size` used in #8992.
=> chore: upgrade Stylelint version to v16.19.0

packages/vaadin-themable-mixin/package.json, yarn.lock
Updated `style-observer` dependency to latest version. Tests passed, also verified manually that it works fine.
=> chore: update style-observer dependency to v0.0.8

wtr-utils.js
Updated `web-test-runner` scripts to use `base-styles` for change detection, so that we don't run tests for all packages in every PR targeting `base-styles` branch unnecessarily and only run tests for affected packages.
> [!WARNING]  
> This is a temporary commit that should be eventually reverted when merging `base-styles` branch to `main`.
=> chore: update WTR change detection branch for base-styles

packages/multi-select-combo-box/test/chips.test.js, packages/multi-select-combo-box/test/multi-select-combo-box-test-styles.js
- Removed custom padding from the MSCB input container to use the one provided by base styles,
- Changed the width back to `350px` used initially to verify that showing clear button causes overflow:
| No clear button | With clear button |
| ----------------|------------------| 
| ![no-clear-btn](https://github.com/user-attachments/assets/2e67e569-5eff-4d95-8565-87b7bc0bf471) | ![with-clear-button](https://github.com/user-attachments/assets/460418ce-198e-4832-afa4-c98714c901ac) |
- Test
=> test: fix multi-select-combo-box chips test with base styles

packages/rich-text-editor/test/attach.test.js, packages/rich-text-editor/test/auto-grow.test.js, packages/rich-text-editor/test/basic.test.js, packages/rich-text-editor/test/rte-test-styles.js, packages/rich-text-editor/test/toolbar.test.js
Updated `vaadin-rich-text-editor` tests to remove Lumo imports and added styles needed to make auto-grow tests pass.
- Test
=> test: update RTE unit tests to not use Lumo styles

packages/field-highlighter/test/visual/lumo/field-highlighter.test.js, packages/text-field/test/visual/lumo/text-field.test.js
Most of pointer focus-ring visual tests were updated to use new command in #8566 but a few were not. This PR fixes that.
- Test
=> test: update visual tests to use sendMouseToElement command

packages/vaadin-themable-mixin/package.json
The `src` folder was not added to `"files"` and not published to npm. This PR fixes that.
- Bugfix
=> fix: publish vaadin-themable-mixin src folder to npm

yarn.lock
The `yarn.lock` still has Lit version `3.0.0` - let's upgrade to the latest one. Also run `yarn-deduplicate`.
=> chore: bump Lit version to latest, deduplicate yarn.lock

packages/date-picker/src/vaadin-date-picker-year-scroller.js, packages/date-picker/src/vaadin-infinite-scroller.js
Fixes to date-picker styles based on visual tests:
- Updated to use `translate(-50%, -50%)` to ensure the selected year indicator is positioned vertically
- Added styles using `:dir(rtl)` to position the selected year indicator and show year scroller border
- Added `scrollbar-width` (Firefox 64+) to hide scroll bars (WebKit still needs `::-webkit-scrollbar`)
- Bugfix
=> fix: small fixes to date-picker scroller base styles

packages/date-picker/src/vaadin-date-picker-overlay-content-mixin.js, packages/date-picker/test/dom/__snapshots__/date-picker.test.snap.js, packages/date-time-picker/test/dom/__snapshots__/date-time-picker.test.snap.js
When the date-picker is in the fullscreen mode with screen less than `375px` width, year scroller is hidden by default.
Currently in the Lumo version we have `track` gesture added in https://github.com/vaadin/vaadin-date-picker/pull/49 to toggle year scroller:
https://github.com/user-attachments/assets/08845995-fa8b-4b15-b058-f8b331a7066b
The gesture is using `transform: translateX()` for smooth transitions. This stopped working since https://github.com/vaadin/web-components/pull/8928 where the overlay content has been updated to use CSS grid and uses `grid-template-columns` to determine whether to show year scroller.
Removed all the logic related to this (the base styles PR removed `_translateXChanged` observer which broke tests so I added it back in #8995 but in fact it's not needed). …
=> refactor!: remove swipe gesture for toggling year scroller

packages/number-field/src/vaadin-number-field-styles.js
Restores `user-select: none` to prevent value text selection when clicking on increase/decrease button.
https://github.com/user-attachments/assets/dcf84fd5-fdb9-4843-bcec-0d0c2be12003
=> fix: restore user-select: none on step buttons

packages/menu-bar/src/vaadin-menu-bar-mixin.js, packages/menu-bar/test/overflow.test.js
The `width` property on menu-bar buttons is set when they no longer fit and are moved to the overflow. However, currently it is not reset when they become visible again, which can fix override some theme styles. This PR fixes that. 
- Bugfix
=> fix: reset width on menu-bar buttons when restoring them

packages/menu-bar/src/vaadin-menu-bar-mixin.js, packages/menu-bar/test/overflow.test.js
Depends on #8871
The original implementation sets `button.disabled = true` when hiding buttons and moving items to the overflow menu - see https://github.com/vaadin/vaadin-menu-bar/pull/16#discussion_r268981508. It was needed because back then the menu-bar used its own version of [`_getAvailableIndex()`](https://github.com/vaadin/vaadin-menu-bar/blob/35fee93c18e2593d4e62df99ad9329aad842fe3c/src/vaadin-menu-bar-interactions-mixin.html#L222) that checked for `disabled` and `hidden` attributes but not for `visibility`.
Disabling is no longer needed since both <kbd>Tab</kbd> and arrow keys are now handled by `KeyboardDirectionMixin` which filters out hidden buttons using `isElementHidden()` and that helper checks for `visibility` property internally. 
Updated to not modify `disabled` on …
=> refactor: do not disable buttons when moving to overflow

packages/menu-bar/src/vaadin-menu-bar-mixin.js, packages/menu-bar/test/a11y.test.js, packages/menu-bar/test/keyboard-navigation.test.js, packages/menu-bar/test/menu-bar.test.js, packages/menu-bar/test/overflow.test.js
Updated to use `sync: true` and removed `await` from tests where possible.
- Refactor
=> refactor: update menu-bar properties to use sync: true

packages/tabs/src/vaadin-tabs-mixin.js
Same as #9032 but for `vaadin-tabs`.
Tested manually and waiting for `afterNextRender()` is redundant as it's always followed by call in `_onResize()` which is triggered also after rendering the component initially (so that `_updateOverflow()` is called twice after initial render).
Furthermore, there is also `__itemsResizeObserver` that observes resizing individual `vaadin-tab` elements.
- Refactor
=> refactor: remove unnecessary logic covered by resize observer

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-styles.js
This test started to fail in Chrome in CI due to `offsetWidth` of combo-box exceeding parent width:
```
packages/multi-select-combo-box/test/chips.test.js:
❌ chips > autoExpandHorizontally > should collapse chips to overflow when max-width is set on the parent
AssertionError: expected 5 to equal 3
-5
+3
at n.<anonymous> (packages/multi-select-combo-box/test/chips.test.js:526:44)
```
Added `max-width: 100%` on the `vaadin-multli-select-combo-box` to prevent possible problems. 
UPD: seems to be related to Chrome version update. CI uses `Google Chrome 136.0.7103.59`
I was able to reproduce this locally with Chrome `136.0.7103.49` on Mac OS Sonoma:
- Test
=> fix: set max-width on multi-select-combo-box to fix Chrome 136

packages/icon/src/vaadin-icon-font-size-mixin.js
The `dedupingMixin` helper is intended only for mixins that can be applied multiple times in the prototype chain (e.g. some basic mixins like `KeyboardMixin` use that). Let's remove it from here since `IconFontSizeMixin` is only applied once.
Side note: according to https://github.com/vaadin/web-components/pull/6442 we could probably remove `IconFontSizeMixin` altogether in V25 as we drop Safari 15.
- Refactor
=> refactor: remove not needed usage of Polymer mixin helper

packages/context-menu/test/a11y.test.js, packages/context-menu/test/helpers.js, packages/context-menu/test/items.test.js
Extracted from https://github.com/vaadin/web-components/pull/9041
- Updated `a11y` tests to wait for `vaadin-overlay-open` event to ensure focus logic works properly
- Updated `openMenu` test helper to only use it for items that have submenu (i.e. "parent items")
- Changed `openMenu` to also wait for `vaadin-overlay-open` instead of waiting for `nextRender`
- Added `activateItem` test helper to be used by items without submenu (i.e. "non-parent items")
- Test
=> test: improve context-menu test helpers structure and usage

packages/menu-bar/test/a11y.test.js, packages/menu-bar/test/sub-menu.test.js
Extracted from https://github.com/vaadin/web-components/pull/9041
Updated menu-bar tests to wait for `vaadin-overlay-open` event explicitly instead of `nextRender`.
- Test
=> test: update menu-bar tests to use vaadin-overlay-open event

packages/popover/test/a11y.test.js, packages/popover/test/basic.test.js, packages/popover/test/trigger.test.js
Related to #9041
Updated popover tests to wait for `vaadin-overlay-open` event explicitly instead of `nextRender`.
- Test
=> test: update popover tests to use vaadin-overlay-open event

packages/login/test/login-overlay.test.js
Related to #9041
Updated login overlay tests to wait for `vaadin-overlay-open` event explicitly instead of `nextRender`.
- Test
=> test: update login tests to use vaadin-overlay-open event

.gitignore
This file is produced by TS when running `build:ts` script as part of building theme typings. Let's add it to `.gitignore`.
=> chore: add tsconfig.build.tsbuildinfo to .gitignore

packages/rich-text-editor/test/toolbar.test.js
Related to #9041
Updated RTE tests to wait for `vaadin-overlay-open` event explicitly instead of `nextRender`.
- Test
=> test: update rich-text-editor tests to use vaadin-overlay-open event

packages/date-picker/src/vaadin-date-picker-overlay-content-mixin.js, packages/overlay/src/vaadin-overlay-mixin.js, packages/overlay/test/animations.test.js
Replaced `afterNextRender` with combination of `requestAnimationFrame` + `setTimeout` to preserve event timings.
- Refactor
=> refactor: remove usage of afterNextRender helper from overlay

dev/master-detail-layout.html, packages/master-detail-layout/src/vaadin-master-detail-layout.d.ts, packages/master-detail-layout/src/vaadin-master-detail-layout.js, packages/master-detail-layout/test/aria.test.js, packages/master-detail-layout/test/stack-mode.test.js, packages/master-detail-layout/test/typings/master-detail-layout.types.ts
Fixes #9048
- Replaced `stackThreshold` property with `stackOverlay` that defines whether the layout should use stack mode
- The `stackOverlay` can now be used in combination with `forceOverlay` to enforce the stack mode to be used
- State attributes `overlay` and `stack` are preserved depending on which mode is used, so no changes to styling
=> feat!: use stackOverlay property instead of stackThreshold

packages/combo-box/src/vaadin-combo-box-light-mixin.js
Changed to use `queueMicrotask` which should be enough for slotted DOM distribution. Also inlined `dashToCamelCase`.
- Refactor
=> refactor: remove usage of Polymer utils from combo-box-light

packages/upload/test/upload.test.js
Waiting for `afterNextRender` was apparently needed back in the day when `vaadin-upload` was using `dom-repeat`.
- Test
=> test: remove unnecessary afterNextRender from upload test

packages/crud/vaadin-lit-crud-edit-column.d.ts, packages/crud/vaadin-lit-crud-edit.d.ts, packages/crud/vaadin-lit-crud.d.ts, packages/grid/vaadin-lit-grid-column-group.d.ts
Looking into https://github.com/vaadin/react-components/issues/320 I first tried to update the generator to use Lit element versions of components if they exist. That seems to work fine, except that some Lit element entry points have missing or invalid type definitions. This change fixes those.
- Bugfix
=> fix: add missing type definitions for Lit element entry points

packages/upload/src/vaadin-upload-mixin.js, packages/upload/test/file-list.test.js
Fixes #9058
The custom file list can be any element, added a check to avoid errors being thrown. Also added a missing test.
- Bugfix
=> fix: do not throw with custom file list, add missing test

dev/markdown.html, packages/markdown/package.json, packages/markdown/src/markdown-helpers.js, packages/markdown/src/vaadin-markdown.d.ts, packages/markdown/src/vaadin-markdown.js, packages/markdown/test/dom-sync.test.js, packages/markdown/test/markdown.test.js, packages/markdown/test/rendering.test.js, packages/markdown/test/typings/markdown.types.ts, yarn.lock
Implement the `<vaadin-markdown>` component
Feature
=> feat: implement vaadin-markdown component

packages/app-layout/src/vaadin-app-layout-mixin.js
Replaced `afterNextRender` with combination of `requestAnimationFrame` + `setTimeout` [used in Polymer](https://github.com/Polymer/polymer/blob/26171d33853460066fb866e4c72a5b2d3b758e2a/lib/utils/render-status.js#L26-L33). 
Note: Polymer has some logic to queue invocations but IMO we don't need that.
Also removed the call to `_blockAnimationUntilAfterNextRender` from `_afterFirstRender` - it seems to be redundant, at least in dev page the unwanted initial drawer transition is prevented using the single call in `connectedCallback()`.
- Refactor
=> refactor: remove usage of Polymer helpers from app-layout

.github/workflows/unit-tests.yml, .github/workflows/verify.yml
I noticed that we have `npx playwright install chrome` in "Integration tests" and sometimes it takes more than 5 minutes.
This shouldn't be needed as we run against the Chrome already installed on the machine using `channel` option.
For example, Snapshot tests job doesn't have this step and tests pass there. Let's see if we can remove it.
=> chore: do not run playwright-install for Chrome in CI

packages/a11y-base/src/delegate-focus-mixin.js, packages/a11y-base/src/disabled-mixin.js, packages/a11y-base/src/focus-mixin.js, packages/a11y-base/src/keyboard-mixin.js, packages/component-base/src/controller-mixin.js, packages/component-base/src/delegate-state-mixin.js, packages/component-base/src/resize-mixin.js, packages/component-base/src/slot-styles-mixin.js, packages/field-base/src/checked-mixin.js, packages/field-base/src/input-constraints-mixin.js, packages/field-base/src/input-mixin.js, packages/field-base/src/label-mixin.js, packages/field-base/src/validate-mixin.js
Part of #6860
Replaced `dedupingMixin` helper from Polymer with an identical `dedupeMixin` from `@open-wc`.
Note: this npm package is already a dependency but until now it was only used in type definitions.
- Refactor
=> refactor: replace Polymer mixin helper with the open-wc

packages/crud/src/vaadin-crud-helpers.js
Part of #6860
Changed to use `set()` and `get()` helpers which are mostly identical (except the order of parameters).
- Refactor
=> refactor: replace usage of Polymer path helpers in CRUD

packages/date-picker/src/vaadin-date-picker-light.js
Inlined `dashToCamelCase` like it was done for `vaadin-combo-box-light` in https://github.com/vaadin/web-components/pull/9053.
Side note: we might consider dropping `-light` components in V25 altogether.
- Refactor
=> refactor: replace Polymer dashToCamelCase helper usage

.gitignore, package.json, wtr-utils.js
The PR adds two new yarn commands: `update:local:lumo` and `test:local:lumo`. These commands let you run visual tests using the locally installed Chrome browser instead of Sauce Labs which is too slow to use during active development cycles such as the Lumo refactoring.
Example of usage:
1. Run `yarn update:local:lumo` on a reference branch (e.g., main) to generate baseline screenshots.
2. Switch to your branch and run `yarn test:local:lumo` to compare your changes against the baseline.
=> chore: allow running visual tests locally

dev/accordion.html, packages/accordion/src/vaadin-accordion-heading-styles.js, packages/accordion/src/vaadin-accordion-panel-styles.js, packages/accordion/test/accordion-panel.test.js, test/integration/dialog-accordion.test.js
- Move most summary/heading styles from the internal button to the host.
- Fix disabled panel styles.
- Fix forced color mode styles.
=> refactor: fix accordion base styles, remove open / close transition

wtr-utils.js
Simplifies the `getVisualTestGroups` helper in `wtr-utils.js`
Part of #9082
=> chore: simplify getVisualTestGroups in wtr-utils.js

packages/polymer-legacy-adapter/src/template-renderer.js, packages/polymer-legacy-adapter/test/warning.test.js, wtr-utils.js
This warning has been there for a while, let's add a mention about removal in V25.
Also removed the docs link which appears to be no longer working anyway.
=> chore: update deprecation warning in polymer-legacy-adapter

packages/component-base/src/polylit-mixin.js
Since we intentionally force synchronous renders in Lit-based components, let's consider dropping the warning about this resulting in inefficient rendering. Otherwise pretty much every components logs these warnings, spamming the browser console and confusing application developers whether something is wrong either with their app or our components.
Part of https://github.com/vaadin/platform/issues/7334
- Refactor
=> refactor: disable change-in-update warnings for Lit components

package.json, wtr-utils.js, yarn.lock
There is a problem with Web Test Runner when using `sinon-chai` assertions described in https://github.com/modernweb-dev/web/issues/2772.
As this wasn't yet solved, let's apply workaround from https://github.com/modernweb-dev/web/issues/2802#issuecomment-2352116570 to make tests debuggable.
=> chore: workaround WTR tests hanging due to structuredClone

packages/overlay/src/vaadin-overlay-mixin.js, packages/overlay/test/basic.test.js
This should prevent some errors in tests where `opened` is changed to `true` and back to `false`, for example:
```
packages/date-time-picker/test/value-commit-lit.generated.test.js:
Error: [object HTMLInputElement] is not contained inside [object HTMLBodyElement]. Skip setting aria-hidden.
Error: [object HTMLInputElement] is not contained inside [object HTMLBodyElement]. Skip setting aria-hidden.
```
- Bugfix
=> fix: cancel vaadin-overlay-open event when opened set to false

packages/cookie-consent/src/vaadin-cookie-consent-mixin.js
When using dev mode, LitElement has `__initialize` method and it gets overridden.
This was discovered in #9102 by trying to use dev mode for running tests.
- Bugfix
=> fix: rename method in cookie-consent to not conflict with Lit

packages/component-base/src/polylit-mixin.js, wtr-utils.js
Thanks to https://github.com/lit/lit/pull/4901 landed in Lit `3.3.0` it's now possible to suppress some warnings.
Let's set flags to prevent warnings that are caused by the structure of `PolylitMixin`:
```
Overriding ReactiveElement.createProperty() is deprecated. The override will not be called with standard decorators See https://lit.dev/msg/no-override-create-property for more information.
Overriding ReactiveElement.getPropertyDescriptor() is deprecated. The override will not be called with standard decorators See https://lit.dev/msg/no-override-get-property-descriptor for more information.
```
- Refactor
=> refactor: suppress Lit warnings about overriding static methods

packages/context-menu/test/context.test.js, packages/context-menu/test/integration.test.js, packages/context-menu/test/touch.test.js
Replaced usage of `PolymerElement` in context-menu tests and inlined some fixtures.
- Test
=> test: replace Polymer based fixture elements in context-menu tests

packages/master-detail-layout/src/vaadin-master-detail-layout-transition-styles.js, packages/master-detail-layout/src/vaadin-master-detail-layout.d.ts, packages/master-detail-layout/src/vaadin-master-detail-layout.js, packages/master-detail-layout/test/aria.test.js, packages/master-detail-layout/test/drawer-mode.test.js, packages/master-detail-layout/test/events.test.js, packages/master-detail-layout/test/master-detail-layout.test.js, packages/master-detail-layout/test/stack-mode.test.js, packages/master-detail-layout/theme/lumo/vaadin-master-detail-layout-styles.js, packages/master-detail-layout/theme/material/vaadin-master-detail-layout-styles.js
Based on the internal discussion, let's reconsider the naming and use `drawer` instead of the `overlay`.
Technically `drawer` and `stack` are two different types of the overlay mode, see also https://github.com/vaadin/flow-components/pull/7419.
=> refactor: rename master-detail-layout overlay mode to drawer

packages/grid/test/column.test.js, packages/grid/test/data-provider.test.js, packages/grid/test/light-dom-observing.test.js, packages/grid/test/resizing.test.js, packages/grid/test/row-details.test.js
Replaced usage of `PolymerElement` in context-menu tests and inlined some fixtures.
Also removed one test which was added in https://github.com/vaadin/vaadin-grid/pull/840 and was specific to the `<template>` logic - it's no longer relevant since https://github.com/vaadin/web-components/pull/5473. Also we have other test "should render the details" checking for `textContent`.
- Test
=> test: replace Polymer based fixture elements in grid tests

packages/custom-field/test/slot-wrapper.test.js
Replaced usage of `PolymerElement` in custom-field tests with vanilla custom elements.
- Test
=> test: replace Polymer based fixture elements in custom-field tests

packages/date-time-picker/test/i18n.test.js
Replaced date-time-picker `i18n` tests to not use Polymer fixtures and instead set custom `i18n` via template.
Setting `i18n` on the time-picker seems no longer needed - tests pass without it, and don't check for it either.
- Test
=> test: simplify date-time-picker i18n tests to not use Polymer

packages/a11y-base/src/delegate-focus-mixin.js, packages/a11y-base/src/tabindex-mixin.js, packages/a11y-base/test/delegate-focus-mixin.test.js, packages/a11y-base/test/tabindex-mixin.test.js
These two mixins currently have some complexity due to `tabindex` property being used. In case of Lit, it can go out of sync with the native `tabIndex` so it requires calling `setAttribute()` to make sure removing / restoring attribute works.
Maybe we can try replacing `tabindex` when switching to Lit. The fact that lowercase property is used is most probably related to the Polymer limitation where `reflectToAttribute` would convert camel-cased property to dash-case attribute.
IMO it should be possible to use `attribute: 'tabindex'` plus a custom converter to handle setting values correctly.
- Refactor
=> refactor: update tabindex logic to work with Lit, add sync: true

packages/accordion/src/vaadin-accordion-mixin.js, packages/accordion/test/accordion.test.js
The two-way synchronization of the opened state between an accordion and its panels can cause the `opened` index property to change multiple times when setting it programmatically. This change prevents changing the `opened` index while it is synced from the accordion to its panels.
Fixes https://github.com/vaadin/web-components/issues/9120
- Bugfix
=> fix: fire single event when changing accordion opened index

packages/a11y-base/test/active-mixin.test.js, packages/a11y-base/test/focus-mixin.test.js, packages/a11y-base/test/focus-trap-controller.test.js, packages/a11y-base/test/keyboard-direction-mixin.test.js, packages/a11y-base/test/keyboard-mixin.test.js
Changed tests for remaining a11y-base mixins and controllers to use `runTests` with Polymer + Lit consistently.
- Test
=> test: update remaining a11y-base tests to also run with Lit

packages/field-base/test/input-controller.test.js, packages/field-base/test/labelled-input-controller.test.js, packages/field-base/test/text-area-controller.test.js, packages/field-base/test/virtual-keyboard-controller.test.js
Changed tests for remaining field-base mixins and controllers to use `runTests` with Polymer + Lit consistently.
- Test
=> test: update remaining field-base tests to also run with Lit

packages/charts/test/exporting-styles.js, packages/charts/test/exporting.test.js, packages/charts/test/styling.test.js, packages/charts/test/theme-styles.js
- Removed usage of Polymer based wrapper from charts exporting test, it seems unneeded.
- Extracted test styles into separate files to prevent ThemanleMixin warnings in Lit tests:
```
packages/charts/test/styling-lit.generated.test.js:
The custom element definition for "vaadin-chart" was finalized before a style module was registered. Ideally, import component specific style modules before importing the corresponding custom element. This warning can be suppressed by setting "window.Vaadin.suppressPostFinalizeStylesWarning = true".
```
Also, removed redundant usage of `chartBaseTheme` from `registerStyles` to avoid this warning:
```
packages/charts/test/styling-lit.generated.test.js:
Registering styles that already exist for vaadin-chart
```
- Test
=> test: remove Polymer fixture from charts tests, extract styles

packages/charts/src/vaadin-lit-chart-series.js
There `vaadin-chart` imports `vaadin-chart-series`, there is no need for extra import (it's not present in Polymer version).
- Refactor
=> refactor: remove chart import from Lit based chart-series

packages/grid-pro/src/vaadin-lit-grid-pro-edit-checkbox.js, packages/grid-pro/src/vaadin-lit-grid-pro-edit-select.js, packages/grid-pro/src/vaadin-lit-grid-pro-edit-text-field.js
Updated JSDoc annotation for components that are marked as `@private` - they would not end up in API docs anyway.
Will update the public components separately as a preparation for switching to Lit based versions later.
=> docs: update JSDoc for internal Lit based custom elements

packages/crud/src/vaadin-crud-edit-column.d.ts, packages/crud/src/vaadin-crud-edit-column.js, packages/grid-pro/src/vaadin-grid-pro-edit-column.d.ts, packages/grid-pro/src/vaadin-grid-pro-edit-column.js, packages/grid/src/vaadin-grid-filter-column.d.ts, packages/grid/src/vaadin-grid-filter-column.js, packages/grid/src/vaadin-grid-selection-column.d.ts, packages/grid/src/vaadin-grid-selection-column.js, packages/grid/src/vaadin-grid-sort-column.d.ts, packages/grid/src/vaadin-grid-sort-column.js, packages/grid/src/vaadin-grid-tree-column.d.ts, packages/grid/src/vaadin-grid-tree-column.js
Removed Polymer specific data binding to items from JSDoc.
- Docs
=> docs: remove Polymer specific items API from JSDoc examples

packages/date-picker/test/visual/common.js
To improve the stability of visual tests, the PR disables the [animation](https://github.com/vaadin/web-components/blob/9939fbc29849369208c7efc07cec7c8f760faf85/packages/date-picker/src/vaadin-date-picker-overlay-content-styles.js#L57-L60) applied to the year and month date-picker scrollers. This change also helps work around a [browser crash](https://github.com/vaadin/web-components/pull/9138#issuecomment-2880047587) that occurs when using CSSInjector in Sauce Labs with Chrome 130 on Windows.
=> test: disable animation on infinite scrollers

packages/icons/package.json, packages/rich-text-editor/gulpfile.cjs, packages/rich-text-editor/package.json, packages/vaadin-lumo-styles/gulpfile.cjs, packages/vaadin-lumo-styles/package.json, packages/vaadin-material-styles/gulpfile.cjs, packages/vaadin-material-styles/package.json, yarn.lock
Updated `gulp` to v5 and `gulp-cli` to v3 - this should resolve dependabot alert on outdated `chokidar` version.
Also added tweaks to make sure `gulp-iconfont` works based on https://github.com/nfroidure/gulp-iconfont/issues/205#issuecomment-2147997629.
Can be verified by running `yarn icons` - there should be no changed files after this.
=> chore: update gulp and gulp-cli to latest version

packages/select/src/vaadin-lit-select.js, packages/select/src/vaadin-select.js
This change is needed in preparation for adding base styles. Currently, select imports only two CSS modules it needs:
https://github.com/vaadin/web-components/blob/abc511948a01c22bb1500492a17b16680a2e1e17/packages/field-base/src/styles/input-field-shared-styles.js#L6-L10
This is because `vaadin-select` doesn't have a clear button. However, in `base-styles` branch that file has been renamed to `button` and also provides toggle button styles. Also, e.g. `vaadin-date-time-picker` already imports all of these.
Let's update to use `inputFieldShared` in select to be aligned with all other field components.
- Refactor
=> refactor: align select shared styles with other components

packages/a11y-base/test/focus-trap-controller.test.js
This test is intended to cover the following logic in the controller:
https://github.com/vaadin/web-components/blob/abc511948a01c22bb1500492a17b16680a2e1e17/packages/a11y-base/src/focus-trap-controller.js#L89-L91
However, currently removing `if (this.__focusedElementIndex === -1) {` doesn't break it because the element that we focus manually before trapping focus is the first one. Let's update the test to focus the second element instead.
Note: this was originally fixed in https://github.com/vaadin/vaadin-overlay/pull/74.
- Test
=> test: improve test for trapping focus after focusing element

packages/grid/src/vaadin-grid-column-auto-width-mixin.js
Grid's column auto-width calculation logic currently [caches](https://github.com/vaadin/web-components/blob/3d0496e24d90cddd14189c1d55094caf377530b1/packages/grid/src/vaadin-grid-column-auto-width-mixin.js#L158) the intrinsic width of each column in a single batch before [applying](https://github.com/vaadin/web-components/blob/3d0496e24d90cddd14189c1d55094caf377530b1/packages/grid/src/vaadin-grid-column-auto-width-mixin.js#L161) the updated widths. This helps avoid layout reflows between individual column updates.
However, the existing implementation does not pre-cache the widths of the columns' parent groups. As a result, the [group](https://github.com/vaadin/web-components/blob/3d0496e24d90cddd14189c1d55094caf377530b1/packages/grid/src/vaadin-grid-column-auto-width-mixin.js#L103) widths …
=> refactor: cache column group widths in auto-width calculation

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-mixin.js, packages/multi-select-combo-box/test/chips.test.js
Fixes https://github.com/vaadin/flow-components/issues/7446
This change fixes a problem introduced in https://github.com/vaadin/web-components/issues/4821 where enforcing at least one chip to be shown next to overflow didn't take remaining width into account.
Here's the overview of how this will affect the component:
| Default size | Clear button | 100px width |
| ------------ | ------------ | ------------ |
| ![mscb-before-default](https://github.com/user-attachments/assets/d3c09921-83dc-4d32-81b8-2a95f78187c9) | ![mscb-before](https://github.com/user-attachments/assets/b1de838a-679b-4361-9d05-f829acf7f16e) | ![mscb-before-100px](https://github.com/user-attachments/assets/056598d6-a24f-4e00-99d3-07101ec7ed51)
| Default size | Clear button | 100px width |
| ------------ | ------------ | …
=> fix: collapse all chips to overflow if there is not enough width

packages/accordion/src/vaadin-accordion-heading-base-styles.js, packages/accordion/src/vaadin-accordion-panel-base-styles.js, packages/details/src/vaadin-details-summary-base-styles.js, packages/field-base/src/styles/button-base-styles.js, packages/field-base/src/styles/container-base-styles.js, packages/field-base/src/styles/field-base-styles.js, packages/input-container/src/vaadin-input-container-base-styles.js, packages/list-box/src/vaadin-list-box-base-styles.js, packages/number-field/src/vaadin-number-field-base-styles.js, packages/overlay/src/vaadin-overlay-base-styles.js, packages/password-field/src/vaadin-password-field-base-styles.js, packages/password-field/src/vaadin-password-field-button-base-styles.js, packages/select/src/vaadin-select-base-styles.js, packages/select/src/vaadin-select-overlay-base-styles.js, packages/select/src/vaadin-select-value-button-base-styles.js, packages/side-nav/src/vaadin-side-nav-base-styles.js
Ensures that all base styles are inside the `base` CSS layer to prevent them from overriding the Lumo styles in https://github.com/vaadin/web-components/pull/9206
=> experiment: wrap all base styles in base CSS layer

packages/vaadin-lumo-styles/src/props/base-layer-reset.css
This PR increases the specificity of the `html` selector in `base-layer-reset.css` to ensure that custom CSS properties are also reverted in forced colors mode.
Part of #9082
=> fix: reset base layer CSS properties in forced colors mode too

packages/date-picker/src/vaadin-date-picker-overlay-content-mixin.js, packages/date-picker/src/vaadin-infinite-scroller.js, packages/date-picker/test/helpers.js
Lit based version doesn't use `dom-repeat` so the usage of `flush()` can be removed.
- Refactor
=> refactor: remove Polymer helpers usage from date-picker

packages/component-base/package.json, packages/component-base/src/element-mixin.js, packages/component-base/test/element-mixin.test.js
This essentially reverts https://github.com/vaadin/web-components/pull/3510 which was needed as a workaround for issues caused by using `<iron-icon>`. 
Also moved Polymer to devDependencies as it's only used in tests (will remove it later in a separate PR).
- Refactor
=> refactor: remove Polymer helper usage from ElementMixin

packages/grid/src/vaadin-grid-data-provider-mixin.js, packages/grid/test/scroll-to-index.test.js
In some cases (like calling from the Flow component on `afterNavigation` when using Spring Boot), it is possible that the component is not fully ready yet when `scrollToIndex` is called.
This PR defers `scrollToIndex` calls until the component is ready.
Fixes [#7375](https://github.com/vaadin/flow-components/issues/7375)
=> fix: defer scrollToIndex until grid is ready

packages/combo-box/src/vaadin-combo-box-mixin.js
Removed no longer needed `_propertiesChanged` callback - for Lit the logic is covered by `updated()` below.
- Refactor
=> refactor: remove Polymer specific logic from combo-box

packages/menu-bar/test/sub-menu.test.js
This was removed in https://github.com/vaadin/web-components/pull/9226, it shouldn't be needed in tests either.
- Test
=> test: remove usage of Polymer helper from menu-bar tests

dev/charts/theme-switcher.js
Updated the `theme-switcher` used in charts dev pages to not use Polymer.
=> chore: convert theme-switcher to vanilla custom element

packages/field-base/src/input-field-mixin.js, packages/integer-field/test/integer-field.test.js
Removed no longer needed workaround added in https://github.com/vaadin/vaadin-text-field/pull/484
- Refactor
=> refactor: remove no longer needed Polymer workaround

packages/crud/src/vaadin-crud-mixin.js, packages/crud/test/crud-editor.test.js, packages/crud/test/dom/__snapshots__/crud.test.snap.js
Currently, when closing `vaadin-crud-dialog`, teleported elements (header, form and buttons) are not returned and end up in `vaadin-crud` shadow DOM. This PR fixes that by calling `__moveChildNodes()` on closing the editor.
Also updated the order in which controllers are added to match the list of slots in the template, and added a check to avoid moving nodes in the DOM unnecessarily when using default / aside editor position.
- Bugfix / refactor
=> fix: move CRUD children back to light DOM and keep their order

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-mixin.js, packages/multi-select-combo-box/test/selecting-items.test.js
This PR makes sure the `topGroup` items are always in sync with the selected items even when the dropdown is opened. The `topGroup` items are used to hold the references to the items that will be displayed on top when `selectedItemsOnTop` is set `true`. This fix does not change the intended behaviour of retaining the visible item order when the selected items are updated while the dropdown is opened.
Fixes [#7161](https://github.com/vaadin/flow-components/issues/7161)
=> fix: sync top group if necessary even when dropdown is opened

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/multi-select-combo-box/test/selecting-items.test.js
Back-port of https://github.com/vaadin/web-components/pull/9095 to v23.5
=> fix: sync top group if necessary even when dropdown is opened (#9095) (CP: 23.5)

packages/horizontal-layout/package.json
This dependency is used in type definitions for the mixin, let's add it to package.json.
=> chore: add missing open-wc dependency to horizontal-layout

packages/overlay/test/multiple.test.js
The import is within the same package so let's change it to relative.
- Test
=> test: use relative import in vaadin-overlay unit test

web-dev-server.config.js, wtr-utils.js
Fixes the `yarn:base` command to make it remove CSS imports from dev pages like Lumo does.
=> chore: remove CSS imports when running yarn:base

web-dev-server.config.js
Updates the enforceThemePlugin to replace `global.css` with `autoload.js` in the `transform` hook instead of `transformImport`. The `transformImport` hook runs after `transform`, so code already doesn't have CSS imports at that point.
=> chore: replace global.css with autoload.js in transform hook

packages/login/src/vaadin-login-form.js, packages/login/test/dom/__snapshots__/login-form.test.snap.js, packages/login/test/dom/__snapshots__/login-overlay.test.snap.js, packages/message-input/src/vaadin-message-input-mixin.js, packages/message-input/test/dom/__snapshots__/message-input.test.snap.js
Removed "contained" theme variant usage - it is a leftover from Material theme (Lumo doesn't have it).
- Refactor
=> refactor: remove no longer needed contained theme from buttons

packages/app-layout/src/vaadin-app-layout-mixin.js, packages/app-layout/test/app-layout.test.js
Allow the layout to react to drawer content size changes when drawer width is auto.
https://github.com/user-attachments/assets/e4f17718-61c3-4114-8320-6931ca17cc42
https://github.com/user-attachments/assets/a5897c41-7f42-4258-af74-dbafbf91f6a4
=> fix: resize app layout drawer based on content

dev/card.html, packages/card/README.md, packages/card/src/vaadin-card.js, packages/card/test/accessibility.test.js, packages/card/test/card.test.ts, packages/card/test/visual/lumo/card.test.js
Removes the feature flag from `vaadin-card` in 24.8.
Part of https://github.com/vaadin/components-team-tasks/issues/634
=> chore: remove card feature flag

packages/login/theme/lumo/vaadin-login-overlay-styles.js, packages/login/theme/lumo/vaadin-login-overlay.js
There is currently a warning when using Vaadin 25.0.0-alpha1 in a Flow project:
```
vaadin.js?v=e1c52694:184194 The custom element definition for "vaadin-login-form-wrapper" was finalized before a style module was registered. Ideally, import component specific style modules before importing the corresponding custom element. This warning can be suppressed by setting "window.Vaadin.suppressPostFinalizeStylesWarning = true".
```
Seems like styles could end up in the wrong order. Changed the way how components are imported to avoid this.
- Refactor
=> refactor: restructure Lumo imports for login-overlay styles

packages/combo-box/src/vaadin-combo-box-mixin.js
Removed `_nativeInput` which was used by `vaadin-combo-box-light` and replaced it with `inputElement`.
- Refactor
=> refactor: simplify input element logic in ComboBoxMixin

README.md
Removed live demo link as it's using webcomponents.dev which is [shutting down](https://divriots.com/blog/ide-product-update) on June 1st.
Also moved the link to the documentation above the table to make it more discoverable.
=> chore: remove example and link to live demo from README

packages/form-layout/theme/lumo/vaadin-form-item-styles.js
There is no rule that modifies `color` for the label part, so defining a color transition is pointless. It's apparently a leftover from an earlier implementation.
=> refactor: remove unused color transition

packages/select/src/vaadin-select-base-mixin.js
This logic was added in https://github.com/vaadin/web-components/pull/6256 - back then, the component was not using `sync: true` for `value`. It was added much later in https://github.com/vaadin/web-components/pull/8223. So `value-changed` fires synchronously now and there is no more need to wait for `updateComplete`.
- Refactor
=> refactor: cleanup waiting for updateComplete in select

packages/avatar/src/vaadin-avatar.js, packages/avatar/test/avatar.test.js, packages/avatar/test/dom/__snapshots__/avatar.test.snap.js
Removes the ID attributes `avatar-icon` and `avatar-abbr`  from the `vaadin-avatar` component, as they were only used in unit tests.
Follow-up to #9316
=> refactor: remove unused ID attributes

packages/context-menu/src/vaadin-context-menu-mixin.js, packages/context-menu/test/overlay.test.js, packages/menu-bar/test/sub-menu.test.js
Currently, when opening a context menu, it sets the opacity of the overlay to `0` and then resets it to the default value after the overlay fires the opened event. I assume that is to allow the overlay to properly render its content before it is positioned. The change was added quite some time ago here: https://github.com/vaadin/vaadin-context-menu/pull/200
However, this doesn't work consistently as the `opening` animation also modifies `opacity`. This can result in the overlay briefly becoming visible before content is rendered, while it is positioned incorrectly, as the size of the overlay does not reflect its final size.
Changed this to use `visibility` instead, so that it doesn't conflict with the animation. I haven't been able to reproduce the issue locally, but only with the Flow …
=> fix: hide context menu overlay until rendered

packages/icon/src/vaadin-icon-mixin.js, packages/icon/src/vaadin-icon-svg.d.ts, packages/icon/src/vaadin-icon-svg.js, packages/icon/src/vaadin-icon.js, packages/icon/test/icon.test.js
Updated `vaadin-icon` to pass `svg` directly to the `render()` method without storing a reference to the `<g>` element - this was only needed with Polymer. Also inlined methods that were extracted due to Polymer into the `render()`.
- Refactor
=> refactor: simplify icon rendering logic, inline some methods

packages/combo-box/src/vaadin-combo-box-data-provider-mixin.js, packages/combo-box/src/vaadin-combo-box-mixin.js
Currently, `vaadin-combo-box` triggers way too many updates on initial render. This PR attempts to reduce the count by changing how scroller is initialized - it's now moved to `firstUpdated()` callback. This callback is executed before all observers are run so we no longer need `_scroller` available as a reactive property for `_updateScroller` observer.
Also modified a few other internal flags to not be defined in `static get properties()` as these are not used in observers.
- Refactor
12 updates:
```
vaadin-combo-box-mixin.js:425 Map(1) {'_overlayOpened' => undefined}
vaadin-combo-box-mixin.js:425 Map(3) {'__previousDataProviderFilter' => undefined, '_overlayElement' => undefined, '_scroller' => undefined}
vaadin-combo-box-mixin.js:425 Map(3) {'_lastCommittedValue' => undefined, …
```
=> refactor: simplify combo-box scroller initialization and update logic

packages/component-base/src/style-props.js
Replaces `hsl(X Y Z)` syntax with `hsl(Xdeg, Y%, Z%)` to make it work in Safari 17.
=> fix: avoid using hsl(0 0 0) syntax not supported in Safari 17

packages/combo-box/test/data-provider-styles.js, packages/combo-box/test/overlay-position-styles.js, packages/combo-box/test/overlay-position.test.js
Some combo-box tests pass in CI but fail locally. This PR adds styles to make them pass consistently.
- Test
=> test: add CSS to make combo-box tests pass locally in Firefox

packages/vaadin-themable-mixin/src/css-injector.js, packages/vaadin-themable-mixin/src/css-property-observer.js
Updated CSSPropertyObserver to filter out transition events triggered by CSS properties that aren't being observed.
=> refactor: filter out irrelevant transition events

packages/avatar-group/src/vaadin-avatar-group-mixin.js, packages/avatar-group/src/vaadin-avatar-group.js, packages/avatar-group/test/avatar-group.test.js
Currently, by default there is a situation where `requestContentUpdate()` is called unnecessarily on initialization, especially due to the fact that in the `__overflowItemsChanged` observer both `items` and `oldItems` are set to `[]`.
This improves the logic to only render if we actually have valid overflow items. Also moved `renderer` setting to the template, it feels unnecessary to set it via property (especially now that we only have Lit version of the component). 
- Refactor
=> refactor: prevent unnecessary avatar-group-overlay renders

packages/checkbox-group/test/visual/common.js, packages/checkbox/test/visual/common.js, packages/radio-group/test/visual/common.js
To improve the stability of visual tests, the PR disables the CSS transitions applied to `vaadin-radio-button` and `vaadin-checkbox`.
Part of #9082
=> test: disable CSS transitions on checkbox and radio

packages/tooltip/src/vaadin-tooltip-mixin.js, packages/tooltip/test/tooltip.test.js
`vaadin-grid` uses a manually controlled tooltip that is shown when the pointer enters a cell, and hidden when it leaves a cell. However, when moving the pointer from the cell to the tooltip overlay, the tooltip stays open and then never closes if the pointer moves out of the grid after that as there is no mouseleave event from a cell. The issue is that the tooltip overlay allows the tooltip to stay open on mouseenter, whereas for mouseleave there is a specific condition to ignore that when the tooltip is controlled manually.
This adds the same condition to the tooltip overlay mouseenter, so that if the tooltip was closed manually, it does not reopen. I assume this should be fine:
- The tooltip overlay mouseenter / mouseleave logic allows to move the pointer into the tooltip without …
=> fix: do not reopen manual tooltips on overlay mouseenter

packages/grid/src/vaadin-grid-scroll-mixin.js, packages/grid/theme/lumo/vaadin-grid-styles.js
After some more investigation related to https://github.com/vaadin/web-components/pull/9342#discussion_r2125950679, we discovered that it's possible to unlock styling opportunities and improve current scrolling performance on row focus mode by updating an adopted style sheet with specific selectors, instead of updating a custom CSS property on grid scroll:
Before:
https://github.com/user-attachments/assets/da13418d-cffb-425f-88f8-e3409fd59af3
After:
https://github.com/user-attachments/assets/f62b3845-c1b7-4471-bff8-05c1cb3394a8
Refactor/performance enhancement
=> refactor: avoid updating CSS property on grid scroll

packages/overlay/src/vaadin-overlay-stack-mixin.js, packages/popover/src/vaadin-popover.js, test/integration/popover-tooltip.test.js
Popovers are currently only allowed to close if they are the last overlay in the overlay stack. If the target element also has a tooltip that opens after the popover, then a popover can not close on `mouseleave` because the tooltip is the last overlay. This can easily happen on grids with a tooltip generator, as the tooltip overlay is always shown when hovering a cell, even if the generator doesn't return a text for that specific column / cell.
This changes the last overlay check to ignore tooltip overlays, so that a popover can still close even if a tooltip was opened afterwards.
Part of https://github.com/vaadin/flow-components/issues/7504
- Bugfix
=> fix: allow popover to close while tooltip is open

packages/dialog/src/vaadin-dialog-resizable-mixin.js, packages/dialog/src/vaadin-dialog.d.ts, packages/dialog/test/draggable-resizable.test.js
Fixes https://github.com/vaadin/web-components/issues/9414
=> refactor!: remove contentWidth and contentHeight from resize event

packages/custom-field/src/vaadin-custom-field-mixin.js, packages/custom-field/src/vaadin-custom-field.d.ts, packages/custom-field/test/keyboard.test.js, packages/custom-field/test/typings/custom-field.types.ts
Removed the `internal-tab` event which is no longer used and deprecated, see these PRs:
- https://github.com/vaadin/web-components/pull/7870
- https://github.com/vaadin/web-components/pull/7889
=> refactor!: remove deprecated custom-field internal-tab event

packages/multi-select-combo-box/src/styles/vaadin-multi-select-combo-box-chip-styles.js, packages/multi-select-combo-box/src/styles/vaadin-multi-select-combo-box-overlay-styles.js, packages/multi-select-combo-box/src/styles/vaadin-multi-select-combo-box-scroller-styles.js, packages/multi-select-combo-box/src/styles/vaadin-multi-select-combo-box-styles.d.ts, packages/multi-select-combo-box/src/styles/vaadin-multi-select-combo-box-styles.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-chip.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-item.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-overlay.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-scroller.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js
Moved `vaadin-multi-select-combo-box` core CSS to `styles` folder. Also changed to use shared item styles.
- Refactor
=> refactor: move multi-select-combo-box CSS to styles folder

packages/tabsheet/src/styles/vaadin-tabsheet-styles.d.ts, packages/tabsheet/src/styles/vaadin-tabsheet-styles.js, packages/tabsheet/src/vaadin-tabsheet.js
Extracted `vaadin-tabsheet` core styles into separate file in `styles` folder.
- Refactor
=> refactor: extract tabsheet core CSS to styles folder

packages/charts/src/styles/vaadin-chart-styles.d.ts, packages/charts/src/styles/vaadin-chart-styles.js, packages/charts/src/vaadin-chart.js, packages/charts/test/chart-element.test.js, packages/charts/test/chart-properties.test.js, packages/charts/test/chart-series.test.js, packages/charts/test/exporting.test.js, packages/charts/test/styling.test.js, packages/charts/test/turbo-mode.test.js, packages/charts/theme/lumo/vaadin-chart-styles.js
Moved `vaadin-chart-base-theme` from the `theme` folder to `src/styles` as these are essentially core styles.
- Refactor
=> refactor: move chart base theme CSS to src styles folder

packages/popover/src/styles/vaadin-popover-overlay-styles.d.ts, packages/popover/src/styles/vaadin-popover-overlay-styles.js, packages/popover/src/vaadin-popover-overlay.js
Extracted `popover` core styles into separate file in `styles` folder.
- Refactor
=> refactor: extract popover core CSS to styles folder

packages/map/package.json, yarn.lock
Bumps openlayers to `10.5.0` in v25. The new version should work with the Flow component with minor changes ([draft PR](https://github.com/vaadin/flow-components/pull/7591)).
- Chore
=> chore: bump openlayers to 10.5.0

.stylelintrc, custom-rules/stylelint/use-layers.js, packages/icon/src/styles/vaadin-icon-base-styles.js
The PR introduces a custom Stylelint plugin to ensure all base styles are defined inside base CSS layer.
=> chore: add Stylelint plugin to ensure base styles are inside base CSS layer

packages/grid/src/vaadin-grid-keyboard-navigation-mixin.js, packages/grid/src/vaadin-grid-scroll-mixin.js, packages/grid/test/scroll-into-view.test.js
When the grid receives a focus event from either a row, cell, or element within a cell, it tries to scroll the related row into view. However, if the row is larger than the visible viewport of the grid and the focus event is from an element within a cell (e.g. an input), then that focused element can still end up outside of the viewport after scrolling.
This adds an additional check to see if the whole row fits into the viewport. If not it only tries to scroll the actual focused element into view.
Fixes https://github.com/vaadin/flow-components/issues/7554
- Bugfix
=> fix: scroll focus target into view when row is larger than viewport

package.json
Configures pre-commit hook to run stylelint and prettier for CSS files.
=> chore: lint and format CSS files in pre-commit hook

packages/overlay/src/styles/vaadin-overlay-base-styles.js
Use an older color syntax to support Safari 17.
=> fix: overlay shadow color (support Safari 17)

packages/field-base/src/styles/checkable-base-styles.js, packages/field-base/src/styles/group-base-styles.js
Some combination of nested flex containers causes a weird rendering issue in Safari 17 (tested on iOS 17.5 simulator).
Test case:
```html
<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Checkbox Group</title>
<script type="module" src="./common.js"></script>
import '@vaadin/checkbox-group';
</script>
</head>
<body>
<vaadin-checkbox-group label="Options">
<vaadin-checkbox value="1" label="Option One" checked></vaadin-checkbox>
<vaadin-checkbox value="2" label="Option Two"></vaadin-checkbox>
<vaadin-checkbox value="3" label="Option Three"></vaadin-checkbox>
</vaadin-checkbox-group>
</body>
</html>
```
Before:
After:
=> fix: make checkbox render correctly in column flex on Safari 17

scripts/check-releases.js
Vaadin 24.6 is EOL tomorrow, let's remove it from the script.
=> chore: remove 24.6 branch from the check-releases script

packages/vaadin-lumo-styles/components/icon.css, packages/vaadin-lumo-styles/src/components/icon.css
The PR adds missing core styles to `icon.css`.
=> fix: add missing core styles to icon.css

test/integration/component-tooltip.test.js
Fixes the following failures with tooltip not shown due to checkbox-group / radio-group zero height without items:
```
test/integration/component-tooltip.test.js:
❌ vaadin-checkbox-group with a slotted tooltip > should or should not show tooltip
AssertionError: expected false to be true
-false
+true
at n.<anonymous> (test/integration/component-tooltip.test.js:124:42)
❌ vaadin-radio-group with a slotted tooltip > should or should not show tooltip
AssertionError: expected false to be true
-false
+true
at n.<anonymous> (test/integration/component-tooltip.test.js:124:42)
```
- Test
Remaining IT failures with base styles are caused by dialog and will be covered by https://github.com/vaadin/web-components/pull/9531.
=> test: update component tooltip ITs to pass with base styles

packages/combo-box/test/basic.test.js, packages/combo-box/test/helpers.js, packages/combo-box/test/keyboard.test.js
Ported some test fixes from the `base-styles` branch, including item `min-height` needed to avoid browser-specific differences causing certain scrolling items tests to behave unexpectedly and fail in Firefox with base styles.
Can be verified with `yarn test:firefox --group combo-box --theme=base`.
- Test
=> test: update combo-box unit tests to pass with base styles

packages/grid/src/vaadin-grid.d.ts, packages/grid/src/vaadin-grid.js
Usage of `.html` here is a leftover from V14 and HTML Imports, let's fix to use `.js` instead.
=> docs: fix JSDoc for all-imports entrypoint to use .js

package.json, scripts/updateVersion.js, yarn.lock
As the project now uses ES modules for scripts, we can upgrade `replace-in-file` to v8.
=> chore: update replace-in-file dev dependency version

packages/message-list/test/message-list.test.js
Updated `vaadin-message-list` scroll test to have some padding on messages to make their height be > 50px
This could be probably removed when adding actual base styles but I'm not sure if we'll set padding there.
Note: core styles tests currently pass due to `--vaadin-avatar-size` being set to `64px` by default 😕 
- Test
=> test: update message-list unit tests to pass with base styles

packages/popover/test/basic.test.js
Updated a test to pass with base styles where `border` is set on the `[part='overlay']`.
Can be verified by using `yarn test --group popover --theme=base`.
- Test
=> test: update popover content test to pass with base styles

packages/overlay/test/position-mixin.test.js
This fixes the following tests that currently fail on `main` branch with `yarn test --group overlay --theme=base`.
```
packages/overlay/test/position-mixin.test.js:
❌ position mixin > vertical align top > no overlap > should flip back to default when it fits again
AssertionError: expected 467 to be close to 541 +/- 1
at expectEdgesAligned (packages/overlay/test/position-mixin.test.js:26:71)
at n.<anonymous> (packages/overlay/test/position-mixin.test.js:214:9)
❌ position mixin > horizontal align start > no overlap > should flip back to default when it fits again
AssertionError: expected 667 to be close to 741 +/- 1
at expectEdgesAligned (packages/overlay/test/position-mixin.test.js:26:71)
at n.<anonymous> (packages/overlay/test/position-mixin.test.js:445:9)
```
The problem was that base …
=> test: fix overlay position tests to pass with base styles

packages/context-menu/test/items.test.js, packages/context-menu/test/overlay.test.js
Similar to https://github.com/vaadin/web-components/pull/9554
Base styles added 1px border to `[part='overlay']` and that breaks some tests. Updated to take border into account.
- Test
=> test: fix context-menu overlay tests to pass with base styles

packages/field-base/src/styles/checkable-core-styles.js, packages/input-container/src/styles/vaadin-input-container-core-styles.js, packages/map/src/styles/vaadin-map-core-styles.js, packages/number-field/src/vaadin-number-field-mixin.js, packages/side-nav/src/styles/vaadin-side-nav-item-core-styles.js, packages/text-area/src/styles/vaadin-text-area-core-styles.js, packages/vaadin-lumo-styles/src/components/input-container.css, packages/vaadin-lumo-styles/src/components/map.css, packages/vaadin-lumo-styles/src/components/side-nav-item.css, packages/vaadin-lumo-styles/src/components/text-area.css, packages/vaadin-lumo-styles/src/mixins/checkable-field.css
The `appearance` CSS property is supported without vendor prefixes in all modern browsers.
=> refactor: remove vendor prefixes from appearance CSS property

packages/avatar-group/src/styles/vaadin-avatar-group-core-styles.js, packages/date-picker/theme/lumo/vaadin-date-picker-overlay-content-styles.js, packages/date-picker/theme/lumo/vaadin-date-picker-overlay-styles.js, packages/field-highlighter/theme/lumo/vaadin-field-outline-styles.js, packages/input-container/theme/lumo/vaadin-input-container-styles.js, packages/multi-select-combo-box/theme/lumo/vaadin-multi-select-combo-box-styles.js, packages/tabs/theme/lumo/vaadin-tabs-styles.js, packages/vaadin-lumo-styles/mixins/input-field-shared.js, packages/vaadin-lumo-styles/mixins/menu-overlay.js, packages/vaadin-lumo-styles/src/components/avatar-group.css, packages/vaadin-lumo-styles/src/components/date-picker-overlay-content.css, packages/vaadin-lumo-styles/src/components/date-picker-overlay.css, packages/vaadin-lumo-styles/src/components/field-outline.css, packages/vaadin-lumo-styles/src/components/input-container.css, packages/vaadin-lumo-styles/src/components/multi-select-combo-box.css, packages/vaadin-lumo-styles/src/components/tabs.css, packages/vaadin-lumo-styles/src/mixins/field-base.css, packages/vaadin-lumo-styles/src/mixins/menu-overlay-ext.css
The `mask` property is widely supported in all modern browsers and no longer requires vendor prefixes.
=> refactor: drop legacy -webkit-mask fallback

packages/date-picker/src/vaadin-infinite-scroller.js
Based on manual testing on Mobile Safari 18.5 (real device) and Mobile Safari 17 (via BrowserStack), momentum scrolling does not occur in Safari when scrolling to a date programmatically – even without setting `-webkit-overflow-scrolling: auto`. So, the related workaround in date-picker appears obsolete.
=> refactor: drop momentum scrolling prevention workaround

packages/side-nav/theme/lumo/vaadin-side-nav-item-styles.js, packages/vaadin-lumo-styles/src/components/side-nav-item.css
This PR removes `@supports` wrappers for properties that are now supported across all modern browsers.
=> refactor: remove obsolete @supports wrappers

packages/dashboard/src/styles/vaadin-dashboard-button-core-styles.d.ts, packages/dashboard/src/styles/vaadin-dashboard-button-core-styles.js, packages/dashboard/src/styles/vaadin-dashboard-widget-core-styles.js, packages/dashboard/src/vaadin-dashboard-button.js, packages/dashboard/test/dashboard-keyboard.test.ts, packages/dashboard/test/dashboard-layout.test.ts, packages/dashboard/test/dashboard-section.test.ts, packages/dashboard/test/dashboard-widget-reordering.test.ts, packages/dashboard/test/dashboard-widget-resizing.test.ts, packages/dashboard/test/dashboard-widget.test.ts, packages/dashboard/test/dashboard.test.ts
Updated dashboard tests to use `src` version instead of Lumo, which fixes errors noticeable with `--theme=base`:
1. Added `min-height` to the content part as otherwise it has 0 height
2. Added `min-width` to dashboard button as otherwise it has 0 width
3. Limited height in some tests to smaller value to ensure scrollbar
- Test
=> refactor: update dashboard styles, fix unit tests to use src version

packages/field-highlighter/src/styles/vaadin-user-tags-overlay-core-styles.js, packages/field-highlighter/theme/lumo/vaadin-user-tags-styles.js, packages/vaadin-lumo-styles/src/components/user-tags-overlay.css
User-tags overlay is actually not supposed to have background and box-shadow but the CSS for it was overridden as a regression from https://github.com/vaadin/web-components/pull/8548. Originally, `src` styles were applied using `registerStyles` without setting `moduleId` and they were overriding Lumo as a side-effect.
Let's improve this by moving CSS for resetting background and box-shadow to Lumo itself.
BTW, the fact that existing visual tests didn't catch this is somewhat disturbing 😞  
- Bugfix
=> fix: reset user-tags overlay part background and box-shadow

packages/select/src/styles/vaadin-select-overlay-base-styles.js, packages/select/src/styles/vaadin-select-overlay-core-styles.js, packages/select/src/vaadin-select-base-mixin.js, packages/select/src/vaadin-select-overlay-mixin.js, packages/select/src/vaadin-select.d.ts, packages/select/src/vaadin-select.js, packages/select/test/select.test.js, packages/vaadin-lumo-styles/src/components/select-overlay.css
Currently, `vaadin-select` sets custom CSS property called `--vaadin-select-text-field` on the overlay. This property shouldn't be configured by the user and there is no need to keep it marked as public. This PR aligns the property name with `vaadin-combo-box` where we use `--_vaadin-combo-box-overlay-default-width` private CSS custom property.
Also moved the logic for setting custom property to the overlay and simplified `_openedChanged` observer a bit.
=> refactor!: make default overlay width custom CSS property private

packages/select/src/vaadin-select-overlay-mixin.js, packages/select/test/accessibility.test.js
Currently, the logic for restoring `focus-ring` attribute in `vaadin-select` works incorrectly when closed on outside click.
1. First, `focus-ring` is set in the `_openedChanged` observer based on `_openedWithFocusRing`,
2. Then focus moves to `<body>` and `FocusRestorationController` restores it after a timeout,
3. But then `_keyboardActive` flag is `false` due to click event, and `focus-ring` gets removed.
Added `preventDefault()` on `mousedown` event when opened to align with combo-box & date-picker behavior:
- #7846 
- #7855
As a result, the `FocusRestorationController` now resets focus synchronously and `_openedWithFocusRing` works.
- Refactor
=> fix!: prevent focusout when closing select overlay on outside click

packages/field-highlighter/src/fields/vaadin-select-observer.js, packages/field-highlighter/test/field-components.test.js
Follow-up to https://github.com/vaadin/web-components/pull/9572
- Changed field highlighter logic for `vaadin-select` to not use special handling for `_phone` as it's no longer handled separately since https://github.com/vaadin/web-components/pull/3120.
- Updated tests to use `sendMouse()` instead of `outsideClick()` helper because the latter focuses `body` under the hood and this doesn't happen anymore since https://github.com/vaadin/web-components/pull/9572
- Refactor
=> refactor: simplify select field-highlighter logic and tests

dev/common.js
A couple of minor updates to dev page base styles.
Baseline alignment allows to see alignment issues more easily, and it doesn't stretch components unnecessarily, for example, in the “Min & Max Rows” text area examples.
OS-level dark mode support to easily test that the colors work on both modes.
=> Dev page base styles

packages/field-highlighter/src/vaadin-field-highlighter-styles.js, packages/field-highlighter/theme/lumo/vaadin-user-tags-styles.js, packages/field-highlighter/theme/material/vaadin-user-tags-styles.js
Manual cherry-pick of #9574 to `24.8` - also added reset styles for Material theme.
- Cherry-pick
=> fix: reset user-tags overlay part background and box-shadow (#9574) (CP: 24.8)

packages/field-highlighter/src/vaadin-field-highlighter-styles.js, packages/field-highlighter/theme/lumo/vaadin-user-tags-styles.js, packages/field-highlighter/theme/material/vaadin-user-tags-styles.js
Manual cherry-pick of #9574 to `24.7` - also added reset styles for Material theme.
- Cherry-pick
=> fix: reset user-tags overlay part background and box-shadow (#9574) (CP: 24.7)

dev/common.js
With this property, the style in the dev pages look off when running the server with the Lumo styles.
Removing it for now. Can be reintroduced later when base styles become the default.
=> chore: remove `color-scheme` property from body

packages/icons/test/visual/lumo/vaadin-iconset.test.js
Adds a missing `@vaadin/vaadin-lumo-styles/props.css` import to iconset visual tests.
=> test: add missing Lumo props.css import

packages/grid-pro/test/visual/lumo/grid-pro.test.js
This fixes the last remaining warning in visual tests:
```
packages/grid-pro/test/visual/lumo/grid-pro.test.js:
The custom element definition for "vaadin-select-overlay" was finalized before a style module was registered. Ideally, import component specific style modules before importing the corresponding custom element. This warning can be suppressed by setting "window.Vaadin.suppressPostFinalizeStylesWarning = true".
```
- Test
=> test: update grid-pro test to fix post-finalize style warning

packages/vaadin-themable-mixin/src/css-property-observer.js
This PR adds `!important` to the CSS declarations set by the CSS property observer to track custom property changes. This helps reduce the risk of those declarations being unintentionally overridden by user-defined styles.
Part of #9082
=> refactor: add !important to ::before styles in CSS property observer

dev/custom-field.html
Added missing Lumo CSS import and fixed the `allowedCharPattern` to prevent this error:
```
input-control-mixin.js:249 SyntaxError: Invalid regular expression: /^[0-9]**$/u: Nothing to repeat (at input-control-mixin.js:247:38)
at new RegExp (<anonymous>)
at TextField._allowedCharPatternChanged
````
=> chore: update custom-field dev page, fix console error

packages/vaadin-lumo-styles/components/rich-text-editor.css, packages/vaadin-lumo-styles/global.css, packages/vaadin-lumo-styles/gulpfile.js, packages/vaadin-lumo-styles/src/global/color.css, packages/vaadin-lumo-styles/src/global/dark.css, packages/vaadin-lumo-styles/src/global/style.css, packages/vaadin-lumo-styles/src/global/typography.css, packages/vaadin-lumo-styles/src/props/color.css, packages/vaadin-lumo-styles/src/props/icons.css, packages/vaadin-lumo-styles/src/props/sizing.css, packages/vaadin-lumo-styles/src/props/spacing.css, packages/vaadin-lumo-styles/src/props/style.css, packages/vaadin-lumo-styles/src/props/typography.css
This PR replaces the `html` selector with `:where(:root, :host)` to ensure Lumo global properties and styles apply when Lumo is loaded in Shadow DOM.
Part of #9082
=> refactor: ensure Lumo global props and styles apply in Shadow DOM

packages/vaadin-lumo-styles/src/components/time-picker.css, packages/vaadin-lumo-styles/src/mixins/base-layer-reset.css
The PR adds some missing core styles to `time-picker.css`. They were overlooked because `all: revert-layer` resets all properties except `direction`, which allowed some new base styles to leak through to Lumo and cause the visual tests to pass.
Finding from #9594
=> fix: add missing core styles to time-picker.css

packages/menu-bar/src/vaadin-menu-bar-mixin.js, packages/menu-bar/test/dom/__snapshots__/menu-bar.test.snap.js, packages/menu-bar/test/dom/menu-bar.test.js, packages/menu-bar/test/overflow.test.js, packages/menu-bar/test/visual/lumo/menu-bar.test.js, packages/menu-bar/test/visual/material/menu-bar.test.js, test/integration/dialog-menu-bar.test.js
Manual cherry-pick of #9618 to `24.7` branch.
- Cherry-pick
=> fix!: debounce updating overflow to improve performance (#9618) (CP: 24.7)

dev/common.js
This aligns the `body` selector specificity with the change from https://github.com/vaadin/web-components/pull/9626 so that with ported Lumo, dev page styles do not take precedence over Lumo typography `body` styles.
=> chore: decrease body selector specificity in dev pages

packages/vaadin-lumo-styles/src/components/rich-text-editor.css
The script I used to automate porting styles to CSS files failed to add these rich-text-editor core styles due to an incorrect condition. The visual tests didnt't catch it either because this component isn't using the new base styles yet.
Finding from https://github.com/vaadin/web-components/pull/9594
Part of #9082
=> fix: add missing core styles to rich-text-editor.css

packages/menu-bar/src/vaadin-menu-bar-mixin.js, packages/menu-bar/src/vaadin-menu-bar.js
Follow-up to #9618
Previously, we were setting `_container` after a microtask to delay running observers. This is no longer needed.
- Updated the menu-bar logic to use `updated()`, which runs after `ready()`, instead of individual observers that run before `ready()`. This way it runs after both `_container` and `_overflow` are set, which eliminates the need to define them in `static get properties()`. As a result we get one update less during an initial render of the component.
- Changed `_hasOverflow` to not be a reactive property either, otherwise setting it on resize (e.g. when inside of a split layout on the dev page) triggers update cycle for the component unnecessarily, whereas in fact we only need to set or remove the attribute.
- Moved two container event listeners to the Lit …
=> refactor: simplify menu-bar observers to reduce update count

packages/component-base/src/loader-styles.js
Combining `light-dark()` with relative colors doesn't work in Safari 17 ([reference](https://github.com/w3c/csswg-drafts/issues/10572)), but combining with `color-mix()` does work.
=> fix: use color-mix instead of relative color syntax

.github/workflows/visual-tests.yml
Currently, when both Base and Lumo visual test jobs fail, only the first one that failed upload artifacts.
The other one fails with the following error as we use the same "screenshots" artifact name:
```
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```
Updated to add prefix so that we can handle these cases and get screenshots uploaded for all jobs.
=> chore: use different names for failed screenshot artifacts

packages/split-layout/src/styles/vaadin-split-layout-core-styles.js, packages/vaadin-lumo-styles/src/components/split-layout.css
Fixes https://github.com/vaadin/web-components/issues/537
While `overflow: hidden` should be preserved as I mentioned in https://github.com/vaadin/web-components/issues/537#issuecomment-3051502245, I couldn't reproduce the stacking issue mentioned in https://github.com/vaadin/vaadin-split-layout/pull/19#issuecomment-262521655, so let's remove `transform: translateZ(0)`. 
=> refactor!: remove transform: translateZ(0) from split-layout

packages/icon/src/styles/vaadin-icon-base-styles.js, packages/icon/src/vaadin-icon.js, packages/vaadin-lumo-styles/src/components/button.css, packages/vaadin-lumo-styles/src/components/icon.css, packages/vaadin-lumo-styles/src/components/menu-bar-item.css
Add an explicit baseline alignment element to the shadow DOM, since both pseudo elements are already used.
Before:
After:
=> fix: icon baseline alignment

packages/component-base/src/style-props.js
This is needed to ensure Lumo can override base properties even if its CSS file is loaded before `style-props.js` file.
- Refactor
=> refactor: restore usage of CSS layer for base style properties

packages/app-layout/src/styles/vaadin-app-layout-base-styles.js, packages/avatar-group/src/styles/vaadin-avatar-group-base-styles.js, packages/avatar/src/styles/vaadin-avatar-base-styles.js, packages/date-picker/src/styles/vaadin-date-picker-overlay-content-base-styles.js, packages/date-picker/src/styles/vaadin-month-calendar-base-styles.js, packages/grid/src/styles/vaadin-grid-tree-toggle-base-styles.js, packages/map/src/styles/vaadin-map-base-styles.js, packages/popover/src/styles/vaadin-popover-overlay-base-styles.js, packages/progress-bar/src/styles/vaadin-progress-bar-base-styles.js, packages/split-layout/src/styles/vaadin-split-layout-base-styles.js, packages/tabsheet/src/styles/vaadin-tabsheet-base-styles.js, packages/tooltip/src/styles/vaadin-tooltip-overlay-base-styles.js
If a user wants bigger text to make things easier to read, they don't necessarily want to increase the sizing or spacing of controls at the same time.
I’m still a bit unsure about the gap values we have in the base style-props.js. The inline variant feels like it makes sense, because one of the main purposes for that gap is between icons and text. But maybe that could also just be pixels.
Checkbox and radio button control sizing is also something I felt could still be tied to the font size, and dialog min/max width as well.
=> fix: don't use `rem` and `em` values for most sizing and spacing

packages/avatar/src/vaadin-avatar.js, packages/vaadin-lumo-styles/src/components/avatar.css
This PR enables the new base styles for avatars when using Lumo, removes redundant styles from `avatar.css` and adds necessary overrides to preserve the previous behavior.
- Refactor
=> refactor: update avatar Lumo CSS to extend base styles

test/integration/grid-pro-custom-editor.test.js
The following test fails locally but for some reason passes in CI:
```
test/integration/grid-pro-custom-editor.test.js:
❌ grid-pro custom editor > custom-field > should not stop editing when switching between fields using mouse
AssertionError: expected null to be truthy
at n.<anonymous> (test/integration/grid-pro-custom-editor.test.js:305:71)
Chromium: |██████████████████████████████| 28/28 test files | 268 passed, 1 failed, 1 skipped
```
I wasn't able to figure out why it happens but it's somehow related to removal of Lumo from ITs.
After some debugging I figured out that test passes after adding `line-height` to the field.
- Test
=> test: add workaround to fix failing grid-pro custom-field test

packages/component-base/src/style-props.js
Follow-up to #9675
The original layer was using `vaadin.base` - let's use that again.
- Refactor
=> refactor: restore vaadin prefix to style-props base layer

dev/login-form.html, packages/login/src/vaadin-login-form.js, packages/login/theme/lumo/vaadin-login-form-wrapper-styles.js, packages/vaadin-lumo-styles/src/components/login-form-wrapper.css
Depends on https://github.com/vaadin/web-components/pull/9688
Aligned `vaadin-login-form` styles with the approach in new base styles, see https://github.com/vaadin/web-components/pull/9686.
Also removed custom wrapper styles from the dev page to verify that the form shrinks properly.
Using Lumo custom CSS properties values there is anyway not going to work for base styles.
- Refactor
=> refactor: update login-form to use column flex on slotted form

packages/grid/src/vaadin-grid-mixin.js, packages/grid/src/vaadin-grid-row-details-mixin.js, packages/grid/test/row-details.test.js
The PR renames `_updateRow` to `__initRow` and marks it as private.
=> refactor!: rename updateRow to initRow, mark it as private

packages/grid-pro/src/vaadin-grid-pro-inline-editing-mixin.js, packages/grid/src/vaadin-grid-data-provider-mixin.js, packages/grid/src/vaadin-grid-mixin.js, packages/grid/src/vaadin-grid-row-details-mixin.js, packages/grid/test/data-provider.test.js
The PR renames `_updateItem` to `__updateRow`, marks it as private, and provides a default value for the second parameter `item`.
=> refactor!: rename updateItem to updateRow, mark it as private

packages/grid-pro/src/vaadin-grid-pro-inline-editing-mixin.js, packages/grid/src/vaadin-grid-data-provider-mixin.js, packages/grid/src/vaadin-grid-mixin.js, packages/grid/test/data-provider.test.js
1. Splits `_getItem` into smaller methods: `__getRowItem`, `__ensureRowItem`, and `__ensureRowHierarchy`, 
2. Updates other grid methods to use these new methods
3. Moves row loading state handling from `_getItem` to `__updateRow` which manages other similar aspects of row state.
=> refactor!: split getItem into smaller methods, set loading state in updateRow

packages/confirm-dialog/src/vaadin-confirm-dialog-overlay.js, packages/dialog/src/vaadin-dialog-base-mixin.d.ts, packages/dialog/src/vaadin-dialog-base-mixin.js, packages/dialog/src/vaadin-dialog-size-mixin.d.ts, packages/dialog/src/vaadin-dialog-size-mixin.js, packages/dialog/src/vaadin-dialog.d.ts, packages/dialog/src/vaadin-dialog.js
Created `DialogSizeMixin` to be reused by `vaadin-confirm-dialog` instead of `DialogBaseMixin`.
- Refactor
=> refactor: extract dialog size properties into separate mixin

packages/avatar-group/src/vaadin-avatar-group.js, packages/avatar-group/test/avatar-group.test.js
Follow-up to https://github.com/vaadin/web-components/pull/9585
In the previous PR, `owner` was added to most of overlays except for avatar-group. This PR fixes that.
The change is relevant for Copilot which has some internal logic that relies on `owner` being set.
- Refactor
=> refactor: set owner property on the avatar-group overlay element

packages/overlay/src/vaadin-overlay-focus-mixin.js, packages/overlay/test/focus-trap.test.js
Fixes https://github.com/vaadin/web-components/issues/9702
Added a separate test suite using native popover in addition to the existing one.
- Refactor
=> refactor: make it possible to customize overlay modality root

packages/avatar-group/test/dom/__snapshots__/avatar-group.test.snap.js, packages/combo-box/test/dom/__snapshots__/combo-box.test.snap.js, packages/context-menu/test/dom/__snapshots__/context-menu.test.snap.js, packages/crud/test/dom/__snapshots__/crud.test.snap.js, packages/menu-bar/test/dom/__snapshots__/menu-bar.test.snap.js, packages/overlay/src/vaadin-overlay-mixin.js, packages/overlay/src/vaadin-overlay-position-mixin.js, packages/overlay/src/vaadin-overlay-utils.d.ts, packages/overlay/src/vaadin-overlay-utils.js, packages/overlay/test/animations.test.js, packages/overlay/test/basic.test.js, packages/overlay/test/position-mixin.test.js, packages/overlay/test/renderer.test.js, packages/select/test/dom/__snapshots__/select.test.snap.js, packages/time-picker/test/dom/__snapshots__/time-picker.test.snap.js, packages/tooltip/test/dom/__snapshots__/tooltip.test.snap.js
With moving overlay elements into the shadow root of their owner element, state attributes need to be exposed on the owner element so that they can be still used for targeting styles through the light DOM. This reflects the following common state attributes of overlay elements to their owner:
- `top-aligned`, `bottom-aligned`, `start-aligned`, `end-aligned`
- `opening`
- `closing`
- `modeless`
- `with-backdrop`
State attributes specific to individual components (dialog, popover, ...) will be covered in respective PRs for those components.
Fixes https://github.com/vaadin/web-components/issues/9704
- Refactor
=> refactor: reflect overlay state attributes to owner

packages/rich-text-editor/src/vaadin-rich-text-editor-mixin.js, packages/rich-text-editor/src/vaadin-rich-text-editor.js, packages/rich-text-editor/test/a11y.test.js, packages/rich-text-editor/test/toolbar.test.js
Replaces the existing tooltips in the shadow DOM with a single tooltip in the light DOM that is dynamically assigned to individual toolbar buttons when those are hovered or focused.
Fixes https://github.com/vaadin/web-components/issues/9711
=> refactor!: update rich-text-editor to render tooltip in light DOM 

packages/rich-text-editor/src/vaadin-rich-text-editor-mixin.js, packages/rich-text-editor/src/vaadin-rich-text-editor.js, packages/rich-text-editor/test/toolbar.test.js
Render the link dialog as slotted content in the light DOM.
Fixes https://github.com/vaadin/web-components/issues/9710
=> refactor!: update rich-text-editor to render link dialog in light DOM

packages/avatar-group/test/avatar-group.test.js, packages/avatar-group/test/dom/__snapshots__/avatar-group.test.snap.js, packages/menu-bar/src/vaadin-menu-bar-mixin.js, packages/tooltip/src/vaadin-tooltip-mixin.js, packages/tooltip/src/vaadin-tooltip-overlay.js, packages/tooltip/src/vaadin-tooltip.d.ts, packages/tooltip/src/vaadin-tooltip.js, packages/tooltip/test/dom/__snapshots__/tooltip.test.snap.js, packages/tooltip/test/tooltip.test.js, test/integration/checkbox-group-tooltip.test.js, test/integration/menu-bar-tooltip.test.js, test/integration/notification-overlay.test.js, test/integration/radio-group-tooltip.test.js
Fixes https://github.com/vaadin/web-components/issues/9712
=> refactor!: update tooltip overlay to use native popover

packages/crud/src/vaadin-crud-mixin.js, packages/crud/src/vaadin-crud.js, packages/crud/test/a11y.test.js, packages/crud/test/crud-buttons.test.js, packages/crud/test/crud-editor.test.js, packages/crud/test/crud.test.js, packages/crud/test/dom/__snapshots__/crud.test.snap.js, packages/rich-text-editor/src/vaadin-rich-text-editor.js
Move CRUD confirm dialogs to the light DOM, so that their overlay shadow parts can be targeted with CSS.
Note: Both CRUD and confirm dialog use these same slots: `header`, `cancel-button`. Targeting the CRUD header for example requires using `vaadin-crud > [slot="header"]` specifically in order to not target the confirm dialog header. That is already the recommended selector in the docs.
Fixes https://github.com/vaadin/web-components/issues/9708
=> refactor!: move crud confirm dialogs to light DOM

packages/crud/src/vaadin-crud-dialog.js, packages/crud/src/vaadin-crud-mixin.js, packages/crud/src/vaadin-crud.d.ts, packages/crud/src/vaadin-crud.js, packages/crud/test/a11y.test.js, packages/crud/test/crud-buttons.test.js, packages/crud/test/crud-editor.test.js, packages/crud/test/crud.test.js, packages/crud/test/dom/__snapshots__/crud.test.snap.js, packages/crud/test/dom/crud.test.js, packages/crud/test/helpers.js, packages/dialog/src/vaadin-dialog-base-mixin.js
Fixes https://github.com/vaadin/web-components/issues/9732
=> refactor!: update crud editor dialog to use native popover

packages/confirm-dialog/test/confirm-dialog.test.js
Updated `vaadin-confirm-dialog` tests to use `sendKeys()` instead of `esc()` helper.
- Test
=> test: update confirm-dialog Esc tests to use sendKeys

packages/crud/src/vaadin-crud-dialog.js, packages/crud/src/vaadin-crud.js, packages/crud/test/a11y.test.js, packages/crud/test/dom/__snapshots__/crud.test.snap.js
Move dialog role and aria-label to the CRUD dialog element (instead of the overlay) to align with Confirm Dialog and the upcoming change in Dialog.
Part of https://github.com/vaadin/web-components/issues/9732
- Refactor
=> refactor: move dialog role to CRUD dialog

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-mixin.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-overlay.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.d.ts, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/multi-select-combo-box/test/basic.test.js, packages/multi-select-combo-box/test/chips.test.js, packages/multi-select-combo-box/test/dom/__snapshots__/multi-select-combo-box.test.snap.js, packages/multi-select-combo-box/test/selecting-items.test.js
Fixes https://github.com/vaadin/web-components/issues/9723
Depends on https://github.com/vaadin/web-components/pull/9804
Similar to the time-picker change https://github.com/vaadin/web-components/pull/9755 but for `vaadin-multi-select-combo-box`.
Flow components branch: https://github.com/vaadin/flow-components/compare/proto/mscb-native-popover
=> refactor!: update multi-select-combo-box to use native popover

packages/dialog/src/vaadin-dialog.js, packages/dialog/src/vaadin-lit-dialog.js, packages/dialog/test/draggable-resizable.test.js
Adds draggable attribute to vaadin-dialog-overlay such that it can be styled as currently it can be done with resizable like 
```
vaadin-dialog-overlay[draggable]::part(overlay){
}
```
Fixes # [9377](https://github.com/vaadin/web-components/issues/9377)
=> feat: add draggable attribute to vaadin-dialog-overlay

packages/combo-box/src/vaadin-combo-box-base-mixin.js, packages/combo-box/src/vaadin-combo-box-item-mixin.js, packages/combo-box/src/vaadin-combo-box-overlay-mixin.js, packages/combo-box/src/vaadin-combo-box-overlay.js, packages/combo-box/src/vaadin-combo-box.d.ts, packages/combo-box/src/vaadin-combo-box.js, packages/combo-box/test/basic.test.js, packages/combo-box/test/dom/__snapshots__/combo-box.test.snap.js, packages/combo-box/test/overlay-opening.test.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-mixin.js, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box.js, packages/time-picker/src/vaadin-time-picker-item.js, packages/time-picker/src/vaadin-time-picker-mixin.js, packages/time-picker/src/vaadin-time-picker-overlay.js, packages/time-picker/src/vaadin-time-picker.js, test/integration/dialog-combo-box.test.js
Fixes https://github.com/vaadin/web-components/issues/9721
Depends on https://github.com/vaadin/web-components/pull/9814
Updated `vaadin-combo-box` to use native `popover` for the overlay.
Also removed no longer needed `bringToFront()` workaround (same change was done for `vaadin-date-picker`).
Flow components branch: https://github.com/vaadin/flow-components/compare/proto/combo-native-popover
=> refactor!: update combo-box overlay to use native popover

packages/popover/src/vaadin-popover-overlay.js, packages/popover/src/vaadin-popover.js, packages/popover/test/basic.test.js
It is possible that the target is set after the popover is opened. One case is the popover being programmatically opened via the Flow component. In that case, the focus has already been saved and does not get updated. Therefore it is not restored when the popover is closed.
This PR saves focus when target is set. This allows returning the focus to the target in the initial open without a target.
Fixes #9555
=> fix: save focus if target is set while popover is open

packages/popover/src/vaadin-popover-overlay.js, packages/popover/test/basic.test.js
Cherry-pick of #9826 to `24.7` branch.
- Cherry-pick
=> fix: save focus if target is set while popover is open (#9826) (CP: 24.7)

packages/popover/test/position.test.js
The `--_default-offset` is `0px` in core styles but `4px` in base styles. Adjusted position tests to take it into account.
- Test
=> test: update popover position unit tests to pass with base styles

packages/field-highlighter/src/styles/vaadin-user-tags-overlay-core-styles.js, packages/field-highlighter/src/vaadin-user-tags-overlay.js, packages/field-highlighter/src/vaadin-user-tags.js, packages/field-highlighter/test/user-tags.test.js, packages/vaadin-lumo-styles/src/components/user-tags-overlay.css
Fixes
- Changed `vaadin-user-tags` to render `vaadin-user-tag` elements in the light DOM and set `part` attribute,
- Removed extra `<div part="tags">` wrapper and updated `part="content"` to be a flex container instead,
- Also added `exportparts` attribute to export the overlay stylable parts so that they can be used as follows:
```css
vaadin-checkbox-group::part(user-tags-overlay) {
background-color: green;
}
vaadin-checkbox-group::part(user-tags-content) {
border: solid 1px red;
}
vaadin-checkbox-group::part(user-tag) {
border: solid 1px white;
}
```
=> refactor!: update user-tags overlay to use native popover

packages/context-menu/src/vaadin-context-menu-mixin.js, packages/context-menu/src/vaadin-context-menu-overlay.js, packages/context-menu/src/vaadin-context-menu.d.ts, packages/context-menu/src/vaadin-context-menu.js, packages/context-menu/src/vaadin-contextmenu-items-mixin.js, packages/context-menu/src/vaadin-menu-overlay-mixin.d.ts, packages/context-menu/src/vaadin-menu-overlay-mixin.js, packages/context-menu/test/context.test.js, packages/context-menu/test/dom/__snapshots__/context-menu.test.snap.js, packages/context-menu/test/dom/context-menu.test.js, packages/context-menu/test/helpers.js, packages/context-menu/test/items-theme.test.js, packages/context-menu/test/lit-renderer-directives.test.js, packages/context-menu/test/overlay.test.js, packages/context-menu/test/renderer.test.js, packages/context-menu/test/selection.test.js, packages/menu-bar/src/vaadin-menu-bar-mixin.js, packages/menu-bar/src/vaadin-menu-bar-overlay.js, packages/menu-bar/src/vaadin-menu-bar.d.ts, packages/menu-bar/src/vaadin-menu-bar.js, packages/menu-bar/test/a11y.test.js, packages/menu-bar/test/dom/__snapshots__/menu-bar.test.snap.js, packages/menu-bar/test/dom/menu-bar.test.js, packages/menu-bar/test/keyboard-navigation.test.js, packages/menu-bar/test/overflow.test.js, packages/menu-bar/test/sub-menu.test.js
Updates `vaadin-context-menu` to use native popovers for its overlay. As part of that overlay content is rendered into a slotted div in the light DOM. Likewise, the submenu is slotted from the light DOM. Also updates `vaadin-menu-bar` to use the new structure for `vaadin-menu-bar-submenu`.
Fixes https://github.com/vaadin/web-components/issues/9714
Fixes https://github.com/vaadin/web-components/issues/9715
=> refactor!: update context-menu to use native popover

packages/dialog/test/visual/lumo/dialog.test.js
Updated the CSS used in visual test added in https://github.com/vaadin/web-components/pull/6689 to work with native `popover`.
- Test
=> test: update custom dialog CSS in Lumo no-padding visual test

packages/field-base/src/styles/checkable-base-styles.js
Added a comment to disable the Stylelint warning caused by `unsafeCSS` syntax it fails to handle:
```
$ yarn lint:css
yarn run v1.22.22
$ stylelint --ignore-path .gitignore "packages/**/src/**/*.js" "packages/**/theme/**/*-styles.js" "packages/**/*.css" "dev/**/*.html"
[postcss-lit] Skipping template (/Users/serhii/vaadin/web-components/packages/field-base/src/styles/checkable-base-styles.js:9) as it included either invalid syntax or complex expressions the plugin could not interpret. Consider using a "// postcss-lit-disable-next-line" comment to disable this message
✨  Done in 7.15s
```
=> chore: add postcss-lit comment to disable Stylelint warning

packages/confirm-dialog/src/vaadin-confirm-dialog-mixin.js
This getter was used for teleporting content, it's no longer used since https://github.com/vaadin/web-components/pull/9776.
- Refactor
=> refactor: remove no longer used private getter from confirm-dialog

packages/context-menu/test/helpers.js
The selector was intended to ignore separators, but due to an invalid syntax it still returned separators. All tests are written so that they deal with that, so I just removed the selector.
- Internal
=> chore: fix context menu selector in tests

packages/overlay/src/vaadin-overlay-stack-mixin.js
Usage of `_hasOverlayStackMixin` is no longer needed after we changed to not use `body.children` in https://github.com/vaadin/web-components/pull/9738. 
- Refactor
=> refactor: simplify OverlayStackMixin attached instances logic

packages/context-menu/src/vaadin-context-menu-mixin.js, packages/context-menu/src/vaadin-context-menu.js, packages/context-menu/test/dom/__snapshots__/context-menu.test.snap.js, packages/menu-bar/src/vaadin-menu-bar-submenu-mixin.js, packages/menu-bar/src/vaadin-menu-bar-submenu.js, packages/menu-bar/test/dom/__snapshots__/menu-bar.test.snap.js
Moved `vaadin-context-menu-overlay` and `vaadin-menu-bar-overlay` back to the template.
This essentially reverts https://github.com/vaadin/web-components/pull/6870 which is no longer relevant after switching to native `popover`.
- Refactor
=> refactor: move context-menu and menu-bar overlay to the template

package.json, packages/field-base/src/input-field-mixin.d.ts, yarn.lock
Cherry-pick of https://github.com/vaadin/web-components/pull/9870 to `24.8` branch.
- Cherry-pick
=> fix: bump TypeScript to 5.9, remove autocorrect property override (CP: 24.8)

packages/context-menu/src/vaadin-context-menu-mixin.js, packages/context-menu/src/vaadin-context-menu.d.ts, packages/context-menu/src/vaadin-context-menu.js, packages/context-menu/test/overlay.test.js, packages/context-menu/test/typings/context-menu.types.ts
Adds a `closed` event to `vaadin-context-menu` that fires after the overlay's closing animation has finished.
- Feature
=> feat: fire closed event after closing animation has finished

dev/card.html, packages/vaadin-lumo-styles/components/button.css
Fixed Prettier formatting for some HTML / CSS that we missed to update (we only get ESLint errors for Prettier in JS).
=> chore: fix Prettier formatting in card dev page and button CSS

packages/dashboard/src/styles/vaadin-dashboard-base-styles.js, packages/dashboard/src/styles/vaadin-dashboard-button-base-styles.js, packages/dashboard/src/styles/vaadin-dashboard-section-base-styles.js, packages/dashboard/src/styles/vaadin-dashboard-widget-base-styles.js
Base styles should be imported from correct files, currently these used `-core` (it was still rewritten to `-base` in tests).
- Bugfix
=> fix: import dashboard base styles from the correct files

packages/grid/src/vaadin-grid-a11y-mixin.js, packages/grid/src/vaadin-grid-mixin.js, packages/grid/test/accessibility.test.js
Apply some adjustments to how the `aria-rowcount`/`aria-colcount` values are measured. The changes in this PR are:
- Fix the wrong usage of `headerRenderer` at the method responsible of counting the number of footer rows
- Add a call to `_a11yUpdateGridSize` in the `__updateHeaderFooterRowVisibility` method to recalculate the number of rows/cols when the renderers change
- If empty-state is used and it's active, it is counted as a row
- If the grid has no items and no header/footer is rendered, then the number of columns is adjusted accordingly
Below is a table with the possible states and how the amount of `aria-rowcount` and `aria-colcount` are reflected:
_B: is the number of body rows, H of header rows, and F of footer rows_
| Body Rows | Header | Footer | Empty State | `aria-rowcount` …
=> fix: adjust row and col count base on Grid state

packages/notification/src/styles/vaadin-notification-container-base-styles.js
Before fix:
https://github.com/user-attachments/assets/0bc73a03-2d0b-4da1-bb49-7d5f58deb807
=> fix: avoid shifting center regions on hover

packages/date-picker/src/vaadin-date-picker-mixin.js, packages/date-picker/src/vaadin-date-picker.js, packages/date-picker/test/dropdown.test.js
This fixes a regression from adding native popover to date-picker (which caused the grid-pro date-picker IT to fail).
Once this is merged, I will re-enable the following IT in the base styles PR where backdrop will be styled correctly:
https://github.com/vaadin/web-components/blob/d5ca0d94c0d16eacc65608d06000238f4e4b5eb5/test/integration/grid-pro-custom-editor.test.js#L221-L222
- Bugfix
=> fix: close date-picker overlay correctly on backdrop click

packages/avatar-group/src/vaadin-avatar-group-overlay.js, packages/vaadin-lumo-styles/src/components/avatar-group-overlay.css
The `tabindex="0"` shouldn't be needed in avatar-group as we always focus the list-box.
It was likely copied from `vaadin-select-overlay` where we removed it in https://github.com/vaadin/web-components/pull/9751.
- Refactor
=> refactor: remove tabindex from avatar-group overlay part

web-dev-server.config.js, wtr-utils.js
Updated WTR config to use `enforceThemePlugin` for all themes, and added `cssImportPlugin()` for Aura visual tests.
=> chore: simplify web-test-runner theme plugins config

packages/component-base/src/polylit-mixin.js, packages/component-base/test/polylit-mixin.test.js
This essentially reverts https://github.com/vaadin/web-components/pull/8321. Now when we no longer teleport overlays from shadow DOM, the logic for collecting IDs from the overlay content elements is no longer needed, so I removed it.
- Refactor
=> refactor: remove PolylitMixin logic for handling teleported elements

packages/rich-text-editor/test/visual/lumo/rich-text-editor.test.js
The `common.js` file with styles disabling caret was added in https://github.com/vaadin/web-components/pull/9677 but I missed to add it to Lumo.
- Test
=> test: update rich-text-editor visual tests to hide caret

eslint.config.js, package.json
Removed no longer needed `theme` from linter configuration.
=> chore: remove theme folder files from ESLint and Stylelint

packages/notification/src/styles/vaadin-notification-card-base-styles.js, packages/overlay/src/styles/vaadin-overlay-base-styles.js, packages/tooltip/src/styles/vaadin-tooltip-overlay-base-styles.js
Make it hard to break the overlay border in forced color mode. The thicker border is used to convey separation from underlying content, as all shadows are removed in forced color more.
=> fix: unify border on all overlays in forced color mode

dev/card.html
Lumo isn't always loaded on the dev pages, so this makes the padding work regardless of the theme.
=> chore: don't use lumo prop for padding on dev page

packages/component-base/src/styles/style-props.js
This property isn't used anywhere.
=> chore: remove unused radius-full property

packages/confirm-dialog/src/styles/vaadin-confirm-dialog-overlay-base-styles.js, packages/confirm-dialog/src/vaadin-confirm-dialog-overlay.js, packages/vaadin-lumo-styles/src/components/confirm-dialog-overlay.css
This element is a copy-paste from dialog, it shouldn't be needed as confirm-dialog is not resizable.
- Refactor
=> refactor: remove resizer-container from confirm-dialog overlay

packages/popover/src/vaadin-popover.js, packages/popover/test/basic.test.js
Added missing check for `this.target` to avoid following error:
```
TypeError: Cannot read properties of null (reading 'style')
at Popover.__onOverlayClosed (packages/popover/src/vaadin-popover.js:990:35)
at EventPart.handleEvent (node_modules/lit-html/src/lit-html.ts:2105:28)
```
- Bugfix
=> fix: do not throw on closing popover when target is not set

packages/confirm-dialog/test/dom/__snapshots__/confirm-dialog.test.snap.js, packages/confirm-dialog/test/dom/confirm-dialog.test.js
Updated `vaadin-confirm-dialog` snapshot tests to also cover overlay shadow DOM.
- Test
=> test: extend confirm-dialog snapshots to cover shadow DOM

packages/dashboard/src/styles/vaadin-dashboard-button-base-styles.js
This CSS was added in https://github.com/vaadin/web-components/pull/9563 as a workaround to make tests pass with old core styles, where empty button could have 0 width by default. This is no longer an issue with new base styles so let's remove min-width.
- Refactor
=> refactor: remove not needed dashboard-button min-width

packages/grid-pro/src/styles/vaadin-grid-pro-base-styles.js, packages/grid-pro/src/vaadin-grid-pro-inline-editing-mixin.js, packages/vaadin-lumo-styles/src/components/grid-pro.css
Updated `vaadin-grid-pro` to not use `registerStyles()` API and instead moved CSS to base / Lumo styles.
- Refactor
=> refactor: update grid-pro CSS to not use registerStyles

packages/rich-text-editor/test/dom/__snapshots__/rich-text-editor.test.snap.js
Follow-up to https://github.com/vaadin/web-components/pull/9007
There are some minor changes to DOM after Quill v2 was merged, this PR fixes snapshot.
- Test
=> test: update rich-text-editor snapshot after Quill bump

packages/popover/src/vaadin-popover-overlay-mixin.js, packages/popover/src/vaadin-popover-overlay.js, packages/popover/test/basic.test.js
Addresses a regression from https://github.com/vaadin/web-components/pull/9972
When clicking on the target when the popover is opened, it currently closes due to the outside click, and then reopens immediately as clicking the target also toggles the opened state. This excludes the target from the outside click handling, which should be how it was before with the custom global click handler in popover: https://github.com/vaadin/web-components/pull/9972/files#diff-1171ae48b99c01700dcc87f053aefeeeef342b9c9a12ad3c731a1dccf9188f5dL663-L673
- Bugfix
=> fix: do not reopen popover when clicking target

packages/component-base/src/data-provider-controller/cache.js, packages/component-base/src/data-provider-controller/data-provider-controller.js
Makes DataProviderController's private methods truly private by prefixing them with `#`.
=> refactor: prefix DataProviderController's private methods with #

packages/combo-box/src/vaadin-combo-box-scroller-mixin.d.ts
Found this one while looking for "overlay" occurrences, seems like a copy-paste mistake.
- Docs
=> docs: fix incorrect JSDoc annotation in combo-box-scroller-mixin

packages/rich-text-editor/src/styles/vaadin-rich-text-editor-base-styles.js, packages/vaadin-lumo-styles/src/components/rich-text-editor.css
Let's use the `toolbar-button-pressed` part instead of the internal `on` attribute so it can be removed in V25.
The part name was added in https://github.com/vaadin/web-components/pull/6691 for `::part()` styling, but internal styles were not updated accordingly.
Note, I had to update Lumo `:hover` and `:focus` states due to lower selector specificity.
- Refactor
=> refactor: use toolbar-button-pressed attribute for button styles

packages/popover/src/lit/renderer-directives.d.ts, packages/popover/src/lit/renderer-directives.js, packages/popover/src/vaadin-popover.d.ts, packages/popover/src/vaadin-popover.js
In V25 users can pass content to `vaadin-popover` using default slot, so let's deprecate `renderer`.
- Docs
=> docs: deprecate popover renderer property and Lit directive

packages/rich-text-editor/src/vaadin-rich-text-editor-mixin.js, packages/rich-text-editor/src/vaadin-rich-text-editor.d.ts, packages/rich-text-editor/src/vaadin-rich-text-editor.js, packages/rich-text-editor/test/toolbar.test.js
Removed `on` attribute which is replaced by `toolbar-button-pressed` part added in V24.3, see following PRs:
- https://github.com/vaadin/web-components/pull/6691
- https://github.com/vaadin/web-components/pull/9991
=> refactor!: remove on state attribute from pressed toolbar buttons

dev/confirm-dialog.html, packages/confirm-dialog/src/vaadin-confirm-dialog-mixin.js, packages/confirm-dialog/src/vaadin-confirm-dialog-overlay.js, packages/confirm-dialog/src/vaadin-confirm-dialog.js, packages/confirm-dialog/test/confirm-dialog.test.js, packages/confirm-dialog/test/dom/__snapshots__/confirm-dialog.test.snap.js, packages/crud/test/dom/__snapshots__/crud.test.snap.js, packages/overlay/src/vaadin-overlay-focus-mixin.js, packages/rich-text-editor/test/dom/__snapshots__/rich-text-editor.test.snap.js
Related to https://github.com/vaadin/web-components/issues/9759
- Added `aria-modal="true"` on the `vaadin-confirm-dialog` host element
- Changed from `display: contents` to `display: block` for Safari VoiceOver
- Moved `tabindex="0"` from the overlay part to the confirm-dialog itself
Both `display: contents` and `tabindex` change are needed to make sure Safari VoiceOver web rotor doesn't list elements outside the dialog, which happened especially when focus was on the `overlay` part in shadow DOM.
- Refactor
=> refactor: set aria-modal and tabindex on the confirm-dialog

packages/charts/src/vaadin-chart-mixin.d.ts, packages/charts/src/vaadin-chart-mixin.js, packages/charts/src/vaadin-chart.d.ts, packages/charts/src/vaadin-chart.js, packages/charts/test/chart-element.test.js, packages/charts/test/typings/chart.types.ts
Add a new event that fires when the callback to `Highcharts.Chart#event:endResize` is called. It is being added now to make tests that check for the size of a chart after a resize is performed to be more reliable and to work better when the Highcharts version is upgraded.
Part of #9908
=> feat: add `chart-end-resize` event

packages/popover/src/vaadin-popover.d.ts, packages/popover/src/vaadin-popover.js
Replaced some mentions of the `overlay` with the `popover` as the overlay is more of implementation detail in V25.
Also updated JSDoc for `noCloseOnEsc` to match the new behavior after changing to global listener in  https://github.com/vaadin/web-components/pull/9972.
=> docs: update popover JSDoc to reduce mentions of the overlay

dev/charts/index.html, dev/index.html, dev/rollup.config.js, wds-utils.js, web-dev-server.config.js
Add a similar `index.html` page that is available in `/dev/index.html` to `/dev/charts/` to make it easier to move between charts dev pages.
=> chore: add charts demo listing page

packages/crud/src/vaadin-crud-dialog.js, packages/crud/test/a11y.test.js, packages/crud/test/dom/__snapshots__/crud.test.snap.js, packages/dialog/src/vaadin-dialog-base-mixin.js, packages/dialog/src/vaadin-dialog-overlay.js, packages/dialog/src/vaadin-dialog.js, packages/dialog/test/dialog.test.js, packages/dialog/test/dom/__snapshots__/dialog.test.snap.js
Related to https://github.com/vaadin/web-components/issues/9759
Same as https://github.com/vaadin/web-components/pull/9980 but for `vaadin-dialog` and `vaadin-crud-dialog`.
- Added `aria-modal="true"` on the `vaadin-dialog` element unless it is `modeless`
- Changed from `display: contents` to `display: block` for Safari VoiceOver
- Moved `tabindex="0"` from the overlay part to the dialog element itself
- Removed `vaadin-crud-dialog` tests for setting `aria-hidden` attribute
- Refactor
=> refactor: set aria-modal and tabindex on the dialog

packages/board/README.md, packages/board/src/vaadin-board-row.d.ts, packages/board/src/vaadin-board-row.js, packages/board/src/vaadin-board.d.ts, packages/board/src/vaadin-board.js
Deprecate `<vaadin-board>` with the intention to remove it in Vaadin 26.
Part of https://github.com/vaadin/web-components/issues/9741
- Refactor
=> refactor: deprecate vaadin-board

packages/a11y-base/src/focus-trap-controller.js, packages/a11y-base/test/focus-trap-controller.test.js
Related to https://github.com/vaadin/web-components/issues/437.
As we plan to always set `focus-ring` on programmatic focus, I realised that `FocusTrapController` behavior would be inconsistent since it doesn't enforce that for native elements, such as `<button>`. Modified the logic accordingly.
The change is to use [`focus({ focusVisible: true })`](https://caniuse.com/mdn-api_htmlelement_focus_options_focusvisible_parameter) supported in Firefox and Safari 18 but not in Chrome.
Example in `vaadin-rich-text-editor-popup`:
| Chrome | Firefox |
|---------|--------|
| <img width="215" height="190" alt="Screenshot 2025-08-19 at 12 45 18" src="https://github.com/user-attachments/assets/aaa5256b-073a-4430-9283-31fe9ae82015" /> |  <img width="216" height="188" alt="Screenshot 2025-08-19 at 12 45 …
=> refactor: use focusVisible: true in FocusTrapController focus

packages/dialog/test/dialog.test.js, packages/overlay/src/vaadin-overlay-mixin.js
Follow-up to https://github.com/vaadin/web-components/pull/10024
After changing dialog to set `tabindex` on the host, the login in keydown listener no longer works as expected for modeless dialogs because `this.$.overlay` is not in the `event.composedPath()`. Changed to use `_focusTrapRoot` to fix this. Also modified dialog tests to use actual `sendKeys()` instead of `esc()` helper and to cover this case.
- Bugfix
=> fix: close modeless dialog on Esc when dialog itself has focus

packages/component-base/src/tooltip-controller.js, packages/component-base/test/tooltip-controller.test.js, packages/tooltip/src/vaadin-tooltip-mixin.js, packages/tooltip/src/vaadin-tooltip.d.ts, packages/tooltip/src/vaadin-tooltip.js, packages/tooltip/test/tooltip.test.js, packages/tooltip/test/typings/tooltip.types.ts
Related to https://github.com/vaadin/web-components/pull/10008 - see https://github.com/vaadin/web-components/pull/10008#discussion_r2287925759
Added an event that can be used in `TooltipController` to fire its own event - IMO it's ok to also keep it as public because currently there is no way to detect when tooltip text is changed without observing DOM nodes.
- Feature
=> feat: add tooltip content-changed event and use it in controller

packages/form-layout/src/vaadin-form-layout-mixin.js
Aligned JSDoc annotation for `get slotStyles()` with other components to not show in [API docs](https://cdn.vaadin.com/vaadin-web-components/25.0.0-alpha16/elements/vaadin-form-layout/#slotstyles).
=> docs: mark slotStyles as protected to exclude from API docs

packages/a11y-base/src/list-mixin.d.ts, packages/a11y-base/src/list-mixin.js, packages/tabsheet/src/vaadin-tabsheet-mixin.d.ts, packages/tabsheet/src/vaadin-tabsheet-mixin.js
Updated JSDoc for `ListMixin` to not mention `dom-repeat` and `<vaadin-combo-box>` - both are leftovers from the very early implementation. Mentions of the internal `ItemMixin` are also somewhat confusing in public JSDoc for `vaadin-tabs` and `vaadin-list-box` so I removed that as well. Also modified the `vaadin-tabsheet` JSDoc accordingly. 
=> docs: do not mention dom-repeat and combo-box in items JSDoc

packages/dashboard/src/styles/vaadin-dashboard-button-base-styles.js, packages/dashboard/src/styles/vaadin-dashboard-widget-section-base-styles.js, packages/dashboard/src/vaadin-dashboard-layout.js, packages/dashboard/src/vaadin-dashboard-section.js, packages/dashboard/src/vaadin-dashboard-widget.js, packages/dashboard/src/vaadin-dashboard.js, packages/vaadin-lumo-styles/src/components/dashboard-layout.css, packages/vaadin-lumo-styles/src/components/dashboard-section.css, packages/vaadin-lumo-styles/src/components/dashboard-widget.css, packages/vaadin-lumo-styles/src/components/dashboard.css, packages/vaadin-lumo-styles/src/mixins/dashboard-item.css
- Added `includeBaseStyles: true` to dashboard, dashboard-layout, widget and section elements
- Moved `padding: 4px` to the dashboard-button base styles to not override Lumo theme padding
- Refactor
=> refactor: update dashboard to use base styles, cleanup Lumo CSS

packages/rich-text-editor/src/styles/vaadin-rich-text-editor-base-styles.js, packages/rich-text-editor/src/vaadin-rich-text-editor.js, packages/vaadin-lumo-styles/src/components/rich-text-editor.css
Added `includeBaseStyles: true` to rich-text-editor.
- Refactor
=> refactor: update RTE to use base styles, cleanup Lumo CSS

packages/vaadin-lumo-styles/src/components/scroller.css
Removed duplicated CSS for `overflow-indicators` variant present in base styles.
Also fixed the `focus-ring` to reset `outline: none` coming from base styles.
- Refactor
=> refactor: cleanup scroller Lumo CSS covered by base styles

packages/message-list/src/vaadin-message.js, packages/vaadin-lumo-styles/src/components/message.css
Updated `vaadin-message` to use base styles.
- Refactor
=> refactor: update message to use base styles, cleanup Lumo CSS

packages/combo-box/src/vaadin-combo-box.d.ts, packages/combo-box/src/vaadin-combo-box.js, packages/date-picker/src/vaadin-date-picker.d.ts, packages/date-picker/src/vaadin-date-picker.js, packages/email-field/src/vaadin-email-field.d.ts, packages/email-field/src/vaadin-email-field.js, packages/integer-field/src/vaadin-integer-field.d.ts, packages/integer-field/src/vaadin-integer-field.js, packages/number-field/src/vaadin-number-field.d.ts, packages/number-field/src/vaadin-number-field.js, packages/password-field/src/vaadin-password-field.d.ts, packages/password-field/src/vaadin-password-field.js, packages/select/src/vaadin-select.d.ts, packages/select/src/vaadin-select.js, packages/text-area/src/vaadin-text-area.d.ts, packages/text-area/src/vaadin-text-area.js, packages/text-field/src/vaadin-text-field.d.ts, packages/text-field/src/vaadin-text-field.js, packages/time-picker/src/vaadin-time-picker.d.ts, packages/time-picker/src/vaadin-time-picker.js
Manual cherry-pick of #10068 to `24.9` branch, needed to backport `has-tooltip` attribute feature.
- Cherry-pick
=> docs: list parts and attributes in JSDoc of all field components (#10068) (CP: 24.9)

packages/grid/src/vaadin-grid-scroll-mixin.js, packages/grid/test/helpers.js, packages/grid/test/scrolling-mode.test.js
Replace the custom overflow logic in Grid's `ScrollMixin` in favor of using `OverflowController`.
This removes "left" and "right" values from the "overflow" attribute
Refactor / breaking change
=> refactor!: replace custom grid logic with overflow controller

packages/rich-text-editor/src/vaadin-rich-text-editor-mixin.js, packages/rich-text-editor/test/toolbar.test.js
There is an issue in RTE where tooltip for `color` or `background` button is shown above the popup:
To reproduce, hover over button and click it during the 500ms tooltip delay. The overlay will open.
I also tried using `shouldShow` but it's called immediately on `mouseenter`, which is too early.
- Bugfix
=> fix: hide opening tooltip on color or background button click

packages/rich-text-editor/src/vaadin-rich-text-editor-mixin.js, packages/rich-text-editor/test/toolbar.test.js
The RTE uses custom event listeners for tooltip and that doesn't check for keyboard focus, unlike the `focusin` [logic](https://github.com/vaadin/web-components/blob/7794173471997fa017f186416d63dc82d662e1fe/packages/tooltip/src/vaadin-tooltip-mixin.js#L504-L507) in `vaadin-tooltip` itself. This can cause tooltips open unexpectedly on mobile e.g. for the link dialog:
- Bugfix
=> fix: only show toolbar button tooltip on keyboard focus

packages/grid/src/vaadin-grid-column-reordering-mixin.js, packages/grid/test/column-reordering.test.js
Allow reordering grid columns inside a draggable parent
Fixes https://github.com/vaadin/flow-components/issues/7899
Bugfix
=> fix: allow reordering grid columns inside a draggable parent

dev/grid.html
Fix a couple of issues on the grid dev page:
- Use a data provider instead of a hierarchical `items` array (which isn't supported). The issue:
https://github.com/user-attachments/assets/47f27e3f-92de-4f5a-84b8-05afe9209fe9
- Make sure `detailsOpenedItems` is empty if `rowDetailsRenderer` is not set. The issue:
https://github.com/user-attachments/assets/5dde1b11-4544-411d-9ba7-4674e92d7fe3
Chore
=> chore: grid dev page fixes

packages/overlay/src/styles/vaadin-overlay-base-styles.js, packages/vaadin-lumo-styles/src/mixins/overlay.css
This is needed for Vaadin Start which contains following CSS:
```css
vaadin-dialog-overlay {
bottom: 0;
left: 0;
right: 0;
top: 0;
}
@media (min-width: 640px) {
vaadin-dialog-overlay {
bottom: var(--lumo-space-m);
left: var(--lumo-space-m);
right: var(--lumo-space-m);
top: var(--lumo-space-m);
}
}
```
- Feature
=> feat: add custom CSS property to control overlay viewport inset

packages/overlay/src/vaadin-overlay-position-mixin.js, packages/overlay/test/position-mixin.test.js
Extracted from https://github.com/vaadin/web-components/pull/10079
Improved `PositionMixin` logic for resetting position settings (and also changed to cover `__margins`).
- Bugfix / refactor
=> fix: update position target reset logic to cover margins

packages/vaadin-themable-mixin/package.json, packages/vaadin-themable-mixin/src/lumo-modules.js, packages/vaadin-themable-mixin/test/lumo-modules.test.js
The PR adds a try-catch block around `mediaText` access in LumoInjector to suppress a DOM exception when the browser denies access to this property and show a warning instead.
=> fix: do not throw when media text is not accessible

packages/field-base/src/input-control-mixin.js
The following CSS in a theme would otherwise override the autofill styles:
```css
::part(input-field) {
--vaadin-input-field-background: white;
}
```
=> fix: don't allow themes to accidentally override autofill styles

packages/time-picker/src/vaadin-time-picker-mixin.d.ts, packages/time-picker/src/vaadin-time-picker-mixin.js, packages/time-picker/test/keyboard-navigation.test.js, packages/time-picker/test/time-picker.test.js, packages/time-picker/test/typings/time-picker.types.ts
Adds support for partial I18N objects to time picker. This allows setting an I18N object that only overrides some of the translations and uses default translations as fallback.
- Feature
=> feat: support partial i18n in time picker

packages/side-nav/src/styles/vaadin-side-nav-base-styles.js
Make sure the label stays legible even if the root font size is made really small.
=> fix: min font-size for side-nav label

packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-mixin.d.ts, packages/multi-select-combo-box/src/vaadin-multi-select-combo-box-mixin.js, packages/multi-select-combo-box/test/i18n.test.js, packages/multi-select-combo-box/test/typings/multi-select-combo-box.types.ts
Adds support for partial I18N objects to multi-select combo box. This allows setting an I18N object that only overrides some of the translations and uses default translations as fallback.
- Feature
=> feat: support partial i18n in multi-select-combo-box

packages/grid/src/vaadin-grid-column-mixin.js
The textAlign fallback was originally added in [this commit](https://github.com/vaadin/web-components/commit/51d412db275cf040018907afa53089902573dd3a). It seems there used to be an issue with the `start` and `end` values so `left` and `right` values needed to be used instead. However, that no longer seems to be neccessary. Also, removing this workaround prevents one forced reflow in the Flow component during the first render:
=> refactor: remove obsolete textAlign fallback

packages/vaadin-themable-mixin/src/css-property-observer.js, packages/vaadin-themable-mixin/src/lumo-injector.js
The PR ensures all LumoInjector-related CSS properties are defined on the `::before` pseudo-element to avoid cluttering the DOM inspector:
Depends on 
- https://github.com/vaadin/web-components/pull/10172
=> refactor: define all LumoInjector-related styles on ::before

packages/grid/src/vaadin-grid-a11y-mixin.js, packages/grid/src/vaadin-grid-helpers.js, packages/grid/test/accessibility.test.js
When cell focus mode is active and the row is expanded/collapsed via Space key, the state change is not announced for NVDA and VoiceOver.
This PR reflects the row `aria-expanded` state to the toggle cells so that the announcements in cell focus mode works correctly.
Fixes #5791
=> fix: reflect row aria-expanded state for toggle cells

dev/aura.html, packages/aura/src/surface.css
As agreed, let's avoid using `theme` on arbitrary elements for better React support and use CSS class names instead.
- Refactor
=> refactor: replace Aura surface theme variants with class names

dev/assets/lucide-icons/rotate-ccw.svg, dev/aura.html, dev/aura/aura-view.css
- Add missing icon
- Adjust MDL space distribution
- Avoid tiny empty space below the example Grid ("component card" grows taller than 400px)
=> fix: minor fixes and updates to aura dev page

packages/dialog/src/vaadin-dialog-draggable-mixin.js, packages/dialog/test/draggable-resizable.test.js
On drag start, the dialog currently applies position absolute, left and top styles to the overlay. But it does not update the `left` and `top` properties of the dialog. On drag end it always fires a `dragged` event with the coordinates from those properties. However, if you never move the dialog, then the properties will still be undefined and so will the coordinates in the event. That causes an issue for the Flow component which listens for the `dragged` event to update its own properties, which then get synced back to the client as `null`. The property change listener triggers and dialog resets the styles on the overlay, except for the `position`, which causes the jump reported in https://github.com/vaadin/web-components/issues/10154.
Before …
=> fix: set dialog position on drag start

packages/grid/src/vaadin-grid-selection-column-base-mixin.d.ts, packages/grid/src/vaadin-grid-selection-column-base-mixin.js, packages/grid/src/vaadin-grid-selection-column.d.ts, packages/grid/src/vaadin-grid-selection-column.js, packages/grid/src/vaadin-grid-sort-column.d.ts, packages/grid/src/vaadin-grid.js
Aligned `@fires` annotation in `.js` and `.d.ts` files to match each other. Also improved `selectAll` wording a bit.
=> docs: improve grid JSDoc, add missing fires annotations

packages/charts/src/styles/vaadin-chart-base-styles.js
To ensure a good contrast between the background color of a series and its data label color, a custom color is calculated and set to the data labels. That works well for some types of charts where the labels are placed within an area colored by the series color, like for Organization, Gantt, and Treemap. For other types, however, it can lead to unexpected results when the data labels are placed in an area covered by the chart's background, when `useHTML` is used.
This change restricts the setting of these custom colors to the types mentioned above, where they are expected to work well.
Fixes #9988
- Bugfix
=> fix: restrict custom data label colors

packages/vaadin-lumo-styles/src/components/icon.css
Follow-up to https://github.com/vaadin/web-components/pull/10160
Changed Lumo for `vaadin-icon` to allow using `--vaadin-icon-size` custom CSS property.
- Refactor
=> refactor: update Lumo icon to respect size CSS property

packages/component-base/src/data-provider-controller/cache.js, packages/component-base/test/data-provider-controller-cache.test.js, packages/grid/test/basic.test.js
The PR fixes an issue where the data provider controller didn't remove excess items from the cache when its size decreased, leaving them stuck in memory until `clearCache` was explicitly called.
Finding from https://github.com/vaadin/flow-components/issues/8040
=> fix: remove excess items from cache when size decreases

package.json
Manual cherry-pick of #10225 to `22.1` branch.
There is neither web-types nor Lumo autocomplete CSS in V22, so `release` script is just an alias for `analyze`.
- Cherry-pick
=> chore: add separate release scripts (#10225) (CP: 22.1)

dev/playground/combo-box.html, packages/combo-box/src/vaadin-combo-box-items-mixin.d.ts, packages/combo-box/src/vaadin-combo-box-items-mixin.js, packages/combo-box/test/items.test.js, packages/combo-box/test/typings/combo-box.types.ts, packages/multi-select-combo-box/test/chips.test.js, packages/multi-select-combo-box/test/helpers.js, packages/multi-select-combo-box/test/items.test.js, packages/multi-select-combo-box/test/typings/multi-select-combo-box.types.ts
Extracted from https://github.com/vaadin/web-components/pull/10066
Fixes https://github.com/vaadin/web-components/issues/8333
- Feature
=> feat: add itemLabelGenerator to combo-box and multi-select-combo-box

dev/playground/tabsheet.html
Dev pages build was broken as a result of using incorrect import in #10218. This PR fixes that.
=> chore: use correct import in tabsheet playground page

packages/aura/src/typography.css
This makes the default font size, `--aura-font-size-m`, match `1rem` which equals 17px.
=> fix: use default body font size on iOS

dev/aura.html, packages/aura/src/color.css, packages/aura/src/components/app-layout.css
A couple of minor performance improvements.
The selector in app-layout.css was contributing between 200–400ms to the initial page rendering time Chrome. As that is something that Flow already adds to index.html, it doesn't need to be in the theme.
Avoiding relative colors for `--aura-background-light` and `--aura-background-dark` seem to reduce the initial page rendering time about 200ms in Chrome.
=> fix: aura rendering performance improvements

packages/button/src/styles/vaadin-button-base-styles.js, packages/button/test/visual/base/button.test.js
Using `display: contents` is problematic in different ways:
- it causes anonymous text nodes to disappear in Safari when the tooltip is shown,
- it causes problems in Start where we use `part="label"` for editing button text.
Let's change to `display: inline` as that eliminates both problems.
- Bugfix
https://github.com/user-attachments/assets/61f22d56-e0e7-42c1-9e35-4899cf2d7644
https://github.com/user-attachments/assets/e1755763-75be-4ee8-915b-c52f5363769a
=> fix: set display: inline on the label part in base styles

packages/tooltip/src/vaadin-tooltip-mixin.js, packages/tooltip/src/vaadin-tooltip.js, test/integration/component-tooltip.test.js
Part of #10255
Fixes the finding from https://github.com/vaadin/web-components/issues/10255#issuecomment-3347224080
- Bugfix
=> fix: prevent tooltip click and mousedown from bubbling to target

packages/a11y-base/src/keyboard-direction-mixin.js, packages/a11y-base/test/keyboard-direction-mixin.test.js, packages/menu-bar/src/vaadin-menu-bar-mixin.js, packages/menu-bar/test/keyboard-navigation.test.js
Fixes https://github.com/vaadin/web-components/issues/10250
This fixes two problems in `vaadin-menu-bar`, one of which is a V25 regression and the other one is not:
- First one: `querySelector('[tabindex="0]')` can incorrectly return a sub-menu item from the `submenu` slot
- Second one: with only a single item present, <kbd>Tab</kbd> key press is prevented with `tabNavigation`
I will create separate PRs to backport the corresponding `KeyboardDirectionMixin` fix and tests to 24.9 and 24.8.
- Bugfix
=> fix: ensure menu-bar is focusable after closing and moving focus

packages/menu-bar/src/vaadin-menu-bar-mixin.js, packages/menu-bar/test/sub-menu.test.js
Fixes https://github.com/vaadin/web-components/issues/6918
Fixes https://github.com/vaadin/web-components/issues/5942
Currently, menu-bar behaves is as follows:
- Moving cursor on the item without children closes sub-menu (which is aligned with the [ARIA example](https://www.w3.org/WAI/ARIA/apg/patterns/menubar/examples/menubar-navigation/)).
- But unlike in the example above, sub-menu doesn't get reopened (see the second issue linked above).
Now when we have a BFP (the first issue linked above) about closing being problematic, it sounds easier to just keep the sub-menu opened in the first place. We can then reconsider making it configurable in case someone requests that.
- Bugfix
=> fix: do not close submenu on hovering button without items

packages/menu-bar/src/vaadin-menu-bar-mixin.js, packages/menu-bar/test/sub-menu.test.js
Cherry-pick or #10274 to `24.9` branch.
There was a merge conflict due to `nextRender(subMenu)` in v24 and `nextRender()` on main.
- Cherry-pick
=> fix: do not close submenu on hovering button without items (#10274) (CP: 24.9)

packages/aura/src/components/upload.css, packages/upload/src/styles/vaadin-upload-base-styles.js, packages/upload/src/styles/vaadin-upload-file-base-styles.js, packages/upload/src/styles/vaadin-upload-file-list-base-styles.js, packages/vaadin-lumo-styles/components/upload.css
Align with other component base styles, that we only have separate `border-width` and `border-color` properties and not the shorthand property in addition to those.
Rename the divider border property between files in the file list.
=> refactor: remove shorthand border props, rename border to divider

packages/dialog/src/styles/vaadin-dialog-overlay-base-styles.js, packages/dialog/test/dialog.test.js, packages/dialog/test/draggable-resizable.test.js
Restrict dialog max-width to 100%. This affects Confirm Dialog base styles, which override the max-width.
=> fix: dialog base styles max-width
